SELECT 1 AS `1`;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT DISTINCT 1 AS `1`;
SELECT 1 AS `1` GROUP BY 1;
SELECT json_length(CAST(1 AS JSON)) AS `json_length(CAST(1 AS JSON))`;
SELECT 1. AS `name`;
SELECT 1 AS `1` LIMIT 1;
SELECT 1 AS `1` LIMIT 0;
SELECT 1 AS `1` LIMIT 0;
SELECT CAST(1 AS FLOAT) AS `CAST(1 AS FLOAT)`;
SELECT 1 AS `1` GROUP BY 1;
SELECT 1 AS `1` GROUP BY 1;
SELECT 1 AS `1` LIMIT 5;
SELECT 1 AS `1` ORDER BY 1 DESC;
SELECT 1. AS `name`;
SELECT 1 AS `1` GROUP BY 1;
SELECT 1 AS `1` GROUP BY 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = TRUE LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds';
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds' ORDER BY `information_schema`.`be_configs`.`value` DESC  LIMIT 1;
WITH `srfuzz_n1` AS (SELECT `information_schema`.`be_configs`.`BE_ID`, `information_schema`.`be_configs`.`NAME`, `information_schema`.`be_configs`.`VALUE`, `information_schema`.`be_configs`.`TYPE`, `information_schema`.`be_configs`.`DEFAULT`, `information_schema`.`be_configs`.`MUTABLE` FROM `information_schema`.`be_configs`) SELECT `be_configs`.`value` FROM `srfuzz_n1` AS be_configs WHERE `be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`value` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `be_configs`.`value` FROM (SELECT `information_schema`.`be_configs`.`BE_ID`, `information_schema`.`be_configs`.`NAME`, `information_schema`.`be_configs`.`VALUE`, `information_schema`.`be_configs`.`TYPE`, `information_schema`.`be_configs`.`DEFAULT`, `information_schema`.`be_configs`.`MUTABLE` FROM `information_schema`.`be_configs` UNION SELECT `information_schema`.`be_configs`.`BE_ID`, `information_schema`.`be_configs`.`NAME`, `information_schema`.`be_configs`.`VALUE`, `information_schema`.`be_configs`.`TYPE`, `information_schema`.`be_configs`.`DEFAULT`, `information_schema`.`be_configs`.`MUTABLE` FROM `information_schema`.`be_configs`) `be_configs` WHERE `be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `be_configs`.`value` FROM (SELECT `information_schema`.`be_configs`.`BE_ID`, `information_schema`.`be_configs`.`NAME`, `information_schema`.`be_configs`.`VALUE`, `information_schema`.`be_configs`.`TYPE`, `information_schema`.`be_configs`.`DEFAULT`, `information_schema`.`be_configs`.`MUTABLE` FROM `information_schema`.`be_configs`) `be_configs` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  WHERE `be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE 'base_compaction_check_interval_seconds' = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = '\\' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds' ORDER BY `information_schema`.`be_configs`.`value` ASC NULLS LAST  LIMIT 1;
WITH `srfuzz_n1` AS (SELECT `information_schema`.`be_configs`.`BE_ID`, `information_schema`.`be_configs`.`NAME`, `information_schema`.`be_configs`.`VALUE`, `information_schema`.`be_configs`.`TYPE`, `information_schema`.`be_configs`.`DEFAULT`, `information_schema`.`be_configs`.`MUTABLE` FROM `information_schema`.`be_configs`) SELECT `be_configs`.`value` FROM `srfuzz_n1` AS be_configs WHERE `be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = `information_schema`.`be_configs`.`value` LIMIT 1;
SELECT `be_configs`.`value` FROM (SELECT `information_schema`.`be_configs`.`BE_ID`, `information_schema`.`be_configs`.`NAME`, `information_schema`.`be_configs`.`VALUE`, `information_schema`.`be_configs`.`TYPE`, `information_schema`.`be_configs`.`DEFAULT`, `information_schema`.`be_configs`.`MUTABLE` FROM `information_schema`.`be_configs` UNION SELECT `information_schema`.`be_configs`.`BE_ID`, `information_schema`.`be_configs`.`NAME`, `information_schema`.`be_configs`.`VALUE`, `information_schema`.`be_configs`.`TYPE`, `information_schema`.`be_configs`.`DEFAULT`, `information_schema`.`be_configs`.`MUTABLE` FROM `information_schema`.`be_configs`) `be_configs` WHERE `be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT rank() OVER (PARTITION BY `information_schema`.`be_configs`.`name` ORDER BY `information_schema`.`be_configs`.`value` ASC ) AS `rank() OVER (PARTITION BY name ORDER BY value ASC )` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT CAST((CAST(`information_schema`.`be_configs`.`value` AS DATE)) AS BOOLEAN) AS `CAST((CAST(value AS DATE)) AS BOOLEAN)` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE (json_length(CAST(`information_schema`.`be_configs`.`name` AS JSON))) = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`value` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT max(`information_schema`.`be_configs`.`value`) OVER () AS `max(value) OVER ()` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT DISTINCT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`value` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT dense_rank() OVER (ORDER BY `information_schema`.`be_configs`.`value` ASC ) AS `dense_rank() OVER (ORDER BY value ASC )` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = '0' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds';
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE 'base_compaction_check_interval_seconds' = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = `information_schema`.`be_configs`.`name` LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 1.0E308 LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = `information_schema`.`be_configs`.`name` LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`value` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = -1 LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = `information_schema`.`be_configs`.`value` LIMIT 1;
SELECT `be_configs`.`value` FROM (SELECT `information_schema`.`be_configs`.`BE_ID`, `information_schema`.`be_configs`.`NAME`, `information_schema`.`be_configs`.`VALUE`, `information_schema`.`be_configs`.`TYPE`, `information_schema`.`be_configs`.`DEFAULT`, `information_schema`.`be_configs`.`MUTABLE` FROM `information_schema`.`be_configs`) `be_configs` WHERE `be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`value` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE 'base_compaction_check_interval_seconds' = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 1 LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds';
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = `information_schema`.`be_configs`.`name` LIMIT 1;
SELECT `be_configs`.`value` FROM (SELECT `information_schema`.`be_configs`.`BE_ID`, `information_schema`.`be_configs`.`NAME`, `information_schema`.`be_configs`.`VALUE`, `information_schema`.`be_configs`.`TYPE`, `information_schema`.`be_configs`.`DEFAULT`, `information_schema`.`be_configs`.`MUTABLE` FROM `information_schema`.`be_configs` INTERSECT SELECT `information_schema`.`be_configs`.`BE_ID`, `information_schema`.`be_configs`.`NAME`, `information_schema`.`be_configs`.`VALUE`, `information_schema`.`be_configs`.`TYPE`, `information_schema`.`be_configs`.`DEFAULT`, `information_schema`.`be_configs`.`MUTABLE` FROM `information_schema`.`be_configs`) `be_configs` WHERE `be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`value` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = `information_schema`.`be_configs`.`value` LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = `information_schema`.`be_configs`.`name` LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = `information_schema`.`be_configs`.`value` LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds' GROUP BY `information_schema`.`be_configs`.`value` LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds' ORDER BY `information_schema`.`be_configs`.`value` ASC  LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = -2147483648 LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = FALSE LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT dense_rank() OVER (PARTITION BY `information_schema`.`be_configs`.`name` ORDER BY `information_schema`.`be_configs`.`value` ASC ) AS `dense_rank() OVER (PARTITION BY name ORDER BY value ASC )` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE get_json_string(CAST((`information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds') AS JSON), '$.a') LIMIT 1;
SELECT CAST(`information_schema`.`be_configs`.`value` AS JSON)->'$.a' AS `CAST(value AS JSON)->'$.a'` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT avg(`information_schema`.`be_configs`.`value`) OVER () AS `avg(value) OVER ()` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds';
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`value` = 'base_compaction_check_interval_seconds' LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 1 LIMIT 1;
SELECT `information_schema`.`be_configs`.`value` FROM `information_schema`.`be_configs` WHERE `information_schema`.`be_configs`.`name` = 'base_compaction_check_interval_seconds' LIMIT 1;