SELECT `srfuzz_mut_914`.`test_table`.`id`, `srfuzz_mut_914`.`test_table`.`name`, `srfuzz_mut_914`.`test_table`.`email` FROM `srfuzz_mut_914`.`test_table`;
SELECT `srfuzz_mut_914`.`test_table`.`id`, `srfuzz_mut_914`.`test_table`.`name`, `srfuzz_mut_914`.`test_table`.`email` FROM `srfuzz_mut_914`.`test_table`;
SELECT `srfuzz_mut_914`.`test_table`.`id`, `srfuzz_mut_914`.`test_table`.`age` FROM `srfuzz_mut_914`.`test_table`;
SELECT `srfuzz_mut_914`.`test_table`.`id`, `srfuzz_mut_914`.`test_table`.`age` FROM `srfuzz_mut_914`.`test_table`;
SELECT `srfuzz_mut_914`.`test_table`.`id`, `srfuzz_mut_914`.`test_table`.`name`, `srfuzz_mut_914`.`test_table`.`age` FROM `srfuzz_mut_914`.`test_table`;
SELECT `srfuzz_mut_914`.`test_table`.`name`, `srfuzz_mut_914`.`test_table`.`age`, `srfuzz_mut_914`.`test_table`.`email` FROM `srfuzz_mut_914`.`test_table` WHERE `srfuzz_mut_914`.`test_table`.`age` > 25;
SELECT `srfuzz_mut_914`.`test_table`.`id`, `srfuzz_mut_914`.`test_table`.`name`, `srfuzz_mut_914`.`test_table`.`email` FROM `srfuzz_mut_914`.`test_table` WHERE `srfuzz_mut_914`.`test_table`.`id` = 1;
SELECT `srfuzz_mut_914`.`test_table`.`id`, `srfuzz_mut_914`.`test_table`.`name`, `srfuzz_mut_914`.`test_table`.`email` FROM `srfuzz_mut_914`.`test_table`;
SELECT `srfuzz_mut_914`.`test_table`.`id`, `srfuzz_mut_914`.`test_table`.`age`, `srfuzz_mut_914`.`test_table`.`email` FROM `srfuzz_mut_914`.`test_table`;
WITH `cte1` AS (SELECT `srfuzz_mut_914`.`test_table`.`id`, `srfuzz_mut_914`.`test_table`.`age`, `srfuzz_mut_914`.`test_table`.`email` FROM `srfuzz_mut_914`.`test_table`) SELECT `cte1`.`id`, `cte1`.`age`, `cte1`.`email` FROM `cte1`;
SELECT `r`.`id`, `r`.`age`, `r`.`email` FROM (SELECT `srfuzz_mut_914`.`test_table`.`id`, `srfuzz_mut_914`.`test_table`.`age`, `srfuzz_mut_914`.`test_table`.`email` FROM `srfuzz_mut_914`.`test_table`) `r`;