SELECT initcap('hello world') AS `initcap('hello world')`;
SELECT initcap('HELLO WORLD') AS `initcap('HELLO WORLD')`;
SELECT initcap('hElLo wOrLd') AS `initcap('hElLo wOrLd')`;
SELECT initcap('starrocks database') AS `initcap('starrocks database')`;
SELECT initcap('   hello   world   ') AS `initcap('   hello   world   ')`;
SELECT initcap('one,two.three;four') AS `initcap('one,two.three;four')`;
SELECT initcap('alpha-beta_gamma') AS `initcap('alpha-beta_gamma')`;
SELECT initcap('1st place') AS `initcap('1st place')`;
SELECT initcap('word1 word2') AS `initcap('word1 word2')`;
SELECT initcap('123abc456') AS `initcap('123abc456')`;
SELECT initcap('macDonald') AS `initcap('macDonald')`;
SELECT initcap('a') AS `initcap('a')`;
SELECT initcap('A') AS `initcap('A')`;
SELECT initcap('z') AS `initcap('z')`;
SELECT initcap('.') AS `initcap('.')`;
SELECT initcap('?') AS `initcap('?')`;
SELECT initcap('') AS `initcap('')`;
SELECT initcap(NULL) AS `initcap(NULL)`;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`str`) AS `initcap(str)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT initcap(initcap('hello world')) AS `initcap(initcap('hello world'))`;
SELECT initcap('hello world') AS `initcap('hello world')` LIMIT 1, 5;
SELECT initcap('macDonald') AS `initcap('macDonald')`;
SELECT initcap(initcap('hello world')) AS `initcap(initcap('hello world'))`;
SELECT initcap('hello world') AS `initcap('hello world')` LIMIT 2;
SELECT initcap('hello world') AS `initcap('hello world')`;
SELECT initcap(initcap('hello world')) AS `initcap(initcap('hello world'))`;
SELECT initcap(initcap('hello world')) AS `initcap(initcap('hello world'))`;
SELECT initcap(1) AS `initcap(1)`;
SELECT initcap(initcap('hello world')) AS `initcap(initcap('hello world'))`;
SELECT initcap('hello world') AS `initcap('hello world')` GROUP BY initcap('hello world');
SELECT initcap('starrocks database') AS `initcap('starrocks database')`;
SELECT initcap('hello world') AS `initcap('hello world')` ORDER BY initcap('hello world') DESC;
SELECT initcap(json_query(CAST('hello world' AS JSON), '$.a')) AS `initcap(json_query(CAST('hello world' AS JSON), '$.a'))`;
SELECT initcap('hello world') AS `initcap('hello world')` LIMIT 100;
SELECT initcap('hello world') AS `initcap('hello world')`;
SELECT initcap('hello world') AS `initcap('hello world')`;
SELECT initcap(-9223372036854775808) AS `initcap(-9223372036854775808)`;
SELECT json_length(CAST((initcap('hello world')) AS JSON)) AS `json_length(CAST((initcap('hello world')) AS JSON))`;
SELECT DISTINCT initcap('hello world') AS `initcap('hello world')`;
SELECT initcap(170141183460469231731687303715884105727) AS `initcap(170141183460469231731687303715884105727)`;
SELECT json_query(CAST((initcap('hello world')) AS JSON), '$.a') AS `json_query(CAST((initcap('hello world')) AS JSON), '$.a')`;
SELECT initcap(CAST('hello world' AS JSON)->'k') AS `initcap(CAST('hello world' AS JSON)->'k')`;
SELECT initcap('123abc456') AS `initcap('123abc456')`;
SELECT get_json_string(CAST((initcap('hello world')) AS JSON), '$.a') AS `get_json_string(CAST((initcap('hello world')) AS JSON), '$.a')`;
SELECT DISTINCT initcap('hello world') AS `initcap('hello world')`;
SELECT initcap('0000-00-00') AS `initcap('0000-00-00')`;
SELECT initcap(repeat('x', 65536)) AS `initcap(repeat('x', 65536))`;
SELECT initcap('HELLO WORLD') AS `initcap('HELLO WORLD')`;
SELECT initcap('hello world') AS `initcap('hello world')` WHERE '123abc456';
SELECT initcap('hello world') AS `initcap('hello world')` GROUP BY initcap('hello world');
SELECT initcap('hello world') AS `initcap('hello world')`;
SELECT initcap('hello world') AS `initcap('hello world')`;
SELECT initcap(NULL) AS `initcap(NULL)`;
SELECT initcap(CAST(NULL AS JSON)) AS `initcap(CAST(NULL AS JSON))`;
SELECT initcap(initcap('HELLO WORLD')) AS `initcap(initcap('HELLO WORLD'))`;
SELECT initcap(initcap('HELLO WORLD')) AS `initcap(initcap('HELLO WORLD'))`;
SELECT initcap(repeat('x', 65536)) AS `initcap(repeat('x', 65536))`;
SELECT initcap(NULL) AS `initcap(NULL)`;
SELECT initcap(CAST(NULL AS JSON)) AS `initcap(CAST(NULL AS JSON))`;
SELECT initcap('HELLO WORLD') AS `initcap('HELLO WORLD')`;
SELECT initcap('HELLO WORLD') AS `initcap('HELLO WORLD')`;
SELECT initcap('HELLO WORLD') AS `initcap('HELLO WORLD')` GROUP BY initcap('HELLO WORLD');
SELECT initcap(NULL) AS `initcap(NULL)`;
SELECT DISTINCT initcap('HELLO WORLD') AS `initcap('HELLO WORLD')`;
SELECT initcap('HELLO WORLD') AS `initcap('HELLO WORLD')`;
SELECT DISTINCT initcap('HELLO WORLD') AS `initcap('HELLO WORLD')`;
SELECT initcap(TRUE) AS `initcap(TRUE)`;
SELECT initcap('HELLO WORLD') AS `initcap('HELLO WORLD')` WHERE initcap('z');
SELECT initcap('0') AS `initcap('0')`;
SELECT initcap(9223372036854775807) AS `initcap(9223372036854775807)`;
SELECT initcap('HELLO WORLD') AS `initcap('HELLO WORLD')`;
SELECT initcap(-1.0E308) AS `initcap(-1.0E308)`;
SELECT initcap(-1.0E308) AS `initcap(-1.0E308)`;
SELECT initcap(CAST(NULL AS JSON)) AS `initcap(CAST(NULL AS JSON))`;
SELECT initcap('HELLO WORLD') AS `initcap('HELLO WORLD')`;
SELECT initcap('0000-00-00') AS `initcap('0000-00-00')`;
SELECT initcap(CAST(NULL AS JSON)) AS `initcap(CAST(NULL AS JSON))`;
SELECT initcap('HELLO WORLD') AS `initcap('HELLO WORLD')`;
SELECT initcap(initcap('HELLO WORLD')) AS `initcap(initcap('HELLO WORLD'))`;
SELECT initcap(-2147483648) AS `initcap(-2147483648)`;
SELECT initcap(2147483647) AS `initcap(2147483647)`;
SELECT initcap('HELLO WORLD') AS `initcap('HELLO WORLD')` ORDER BY initcap('HELLO WORLD') DESC;
SELECT initcap('HELLO WORLD') AS `initcap('HELLO WORLD')` GROUP BY initcap('HELLO WORLD');
SELECT initcap('\\') AS `initcap('\\')`;
SELECT initcap(CAST('hElLo wOrLd' AS DECIMAL128(27,9))) AS `initcap(CAST('hElLo wOrLd' AS DECIMAL128(27,9)))`;
SELECT initcap('hElLo wOrLd') AS `initcap('hElLo wOrLd')` ORDER BY initcap('hElLo wOrLd') DESC NULLS FIRST;
SELECT initcap(initcap('hElLo wOrLd')) AS `initcap(initcap('hElLo wOrLd'))`;
SELECT initcap(0.0) AS `initcap(0.0)`;
SELECT initcap('hElLo wOrLd') AS `initcap('hElLo wOrLd')` GROUP BY initcap('hElLo wOrLd');
SELECT initcap('hElLo wOrLd') AS `initcap('hElLo wOrLd')`;
SELECT initcap('hElLo wOrLd') AS `initcap('hElLo wOrLd')` WHERE 'a';
SELECT initcap('hElLo wOrLd') AS `initcap('hElLo wOrLd')` LIMIT 0;
SELECT initcap(CAST('hElLo wOrLd' AS VARCHAR(1))) AS `initcap(CAST('hElLo wOrLd' AS VARCHAR(1)))`;
SELECT max(initcap('hElLo wOrLd')) OVER () AS `max(initcap('hElLo wOrLd')) OVER ()`;
SELECT initcap(FALSE) AS `initcap(FALSE)`;
SELECT initcap('9999-12-31 23:59:59') AS `initcap('9999-12-31 23:59:59')`;
SELECT initcap('hElLo wOrLd') AS `initcap('hElLo wOrLd')` LIMIT 2;
SELECT initcap(0) AS `initcap(0)`;
SELECT initcap('hElLo wOrLd') AS `initcap('hElLo wOrLd')`;
SELECT initcap(initcap('hElLo wOrLd')) AS `initcap(initcap('hElLo wOrLd'))`;
SELECT initcap(initcap('hElLo wOrLd')) AS `initcap(initcap('hElLo wOrLd'))`;
SELECT initcap('hElLo wOrLd') AS `initcap('hElLo wOrLd')`;
SELECT initcap(0) AS `initcap(0)`;
SELECT CAST((CAST((initcap('hElLo wOrLd')) AS DECIMAL128(38,37))) AS TIME) AS `CAST((CAST((initcap('hElLo wOrLd')) AS DECIMAL128(38,37))) AS TIME)`;
SELECT initcap(TRUE) AS `initcap(TRUE)`;
SELECT initcap(initcap('hElLo wOrLd')) AS `initcap(initcap('hElLo wOrLd'))`;
SELECT initcap('hElLo wOrLd') AS `initcap('hElLo wOrLd')` LIMIT 1, 1;
SELECT initcap(initcap('hElLo wOrLd')) AS `initcap(initcap('hElLo wOrLd'))`;
SELECT initcap('hElLo wOrLd') AS `initcap('hElLo wOrLd')` LIMIT 100;
SELECT initcap('hElLo wOrLd') AS `initcap('hElLo wOrLd')` LIMIT 100;
SELECT initcap(170141183460469231731687303715884105727) AS `initcap(170141183460469231731687303715884105727)`;
SELECT initcap(0) AS `initcap(0)`;
SELECT initcap('hElLo wOrLd') AS `initcap('hElLo wOrLd')` ORDER BY initcap('hElLo wOrLd') ASC;
SELECT initcap(initcap('hElLo wOrLd')) AS `initcap(initcap('hElLo wOrLd'))`;
SELECT initcap(initcap('z')) AS `initcap(initcap('z'))`;
SELECT initcap(initcap('starrocks database')) AS `initcap(initcap('starrocks database'))`;
SELECT initcap('\\') AS `initcap('\\')`;
SELECT sum(initcap('starrocks database')) OVER () AS `sum(initcap('starrocks database')) OVER ()`;
SELECT initcap('starrocks database') AS `initcap('starrocks database')` ORDER BY initcap('starrocks database') ASC;
SELECT initcap('starrocks database') AS `initcap('starrocks database')`;
SELECT initcap(0) AS `initcap(0)`;
SELECT initcap('') AS `initcap('')`;
SELECT initcap(0.0) AS `initcap(0.0)`;
SELECT initcap('starrocks database') AS `initcap('starrocks database')`;
SELECT initcap('starrocks database') AS `initcap('starrocks database')`;
SELECT initcap('starrocks database') AS `initcap('starrocks database')`;
SELECT initcap('9999-12-31 23:59:59') AS `initcap('9999-12-31 23:59:59')`;
SELECT initcap('starrocks database') AS `initcap('starrocks database')`;
SELECT initcap('starrocks database') AS `initcap('starrocks database')`;
SELECT DISTINCT initcap('starrocks database') AS `initcap('starrocks database')`;
SELECT min(initcap('starrocks database')) OVER () AS `min(initcap('starrocks database')) OVER ()`;
SELECT DISTINCT initcap('starrocks database') AS `initcap('starrocks database')`;
SELECT initcap(TRUE) AS `initcap(TRUE)`;
SELECT initcap('starrocks database') AS `initcap('starrocks database')`;
SELECT initcap('starrocks database') AS `initcap('starrocks database')` LIMIT 7, 1;
SELECT initcap('starrocks database') AS `initcap('starrocks database')` LIMIT 2;
SELECT initcap(initcap('starrocks database')) AS `initcap(initcap('starrocks database'))`;
SELECT initcap(initcap('starrocks database')) AS `initcap(initcap('starrocks database'))`;
SELECT initcap('starrocks database') AS `initcap('starrocks database')` ORDER BY initcap('starrocks database') ASC;
SELECT initcap('starrocks database') AS `initcap('starrocks database')`;
SELECT initcap(CAST(NULL AS JSON)) AS `initcap(CAST(NULL AS JSON))`;
SELECT initcap('0000-00-00') AS `initcap('0000-00-00')`;
SELECT CAST((initcap('starrocks database')) AS JSON)->'k' AS `CAST((initcap('starrocks database')) AS JSON)->'k'`;
SELECT initcap(initcap('starrocks database')) AS `initcap(initcap('starrocks database'))`;
SELECT CAST((CAST((initcap('starrocks database')) AS JSON)) AS struct<`a` struct<`b` struct<`c` int(11)>>>) AS `CAST((CAST((initcap('starrocks database')) AS JSON)) AS struct<``a`` struct<``b`` struct<``c`` int(11)>>>)`;
SELECT initcap(initcap('starrocks database')) AS `initcap(initcap('starrocks database'))`;
SELECT initcap('   hello   world   ') AS `initcap('   hello   world   ')` LIMIT 100;
SELECT min(initcap('   hello   world   ')) OVER () AS `min(initcap('   hello   world   ')) OVER ()`;
SELECT initcap('   hello   world   ') AS `initcap('   hello   world   ')`;
SELECT initcap(170141183460469231731687303715884105727) AS `initcap(170141183460469231731687303715884105727)`;
SELECT initcap(initcap('   hello   world   ')) AS `initcap(initcap('   hello   world   '))`;
SELECT initcap('   hello   world   ') AS `initcap('   hello   world   ')`;
SELECT initcap(0.0) AS `initcap(0.0)`;
SELECT initcap('   hello   world   ') AS `initcap('   hello   world   ')`;
SELECT initcap('   hello   world   ') AS `initcap('   hello   world   ')` WHERE initcap('A');
SELECT initcap(repeat('x', 65536)) AS `initcap(repeat('x', 65536))`;
SELECT initcap(TRUE) AS `initcap(TRUE)`;
SELECT DISTINCT initcap('   hello   world   ') AS `initcap('   hello   world   ')`;
SELECT initcap('   hello   world   ') AS `initcap('   hello   world   ')`;
SELECT initcap('   hello   world   ') AS `initcap('   hello   world   ')` LIMIT 7, 1;
SELECT initcap('   hello   world   ') AS `initcap('   hello   world   ')` GROUP BY initcap('   hello   world   ');
SELECT initcap(0.0) AS `initcap(0.0)`;
SELECT initcap('   hello   world   ') AS `initcap('   hello   world   ')` ORDER BY initcap('   hello   world   ') ASC NULLS LAST;
SELECT initcap('   hello   world   ') AS `initcap('   hello   world   ')`;
SELECT initcap('0000-00-00') AS `initcap('0000-00-00')`;
SELECT initcap('   hello   world   ') AS `initcap('   hello   world   ')`;
SELECT DISTINCT initcap('   hello   world   ') AS `initcap('   hello   world   ')`;
SELECT initcap('   hello   world   ') AS `initcap('   hello   world   ')` WHERE initcap('word1 word2');
SELECT DISTINCT initcap('   hello   world   ') AS `initcap('   hello   world   ')`;
SELECT initcap('HELLO WORLD') AS `initcap('HELLO WORLD')`;
SELECT initcap(initcap('   hello   world   ')) AS `initcap(initcap('   hello   world   '))`;
SELECT DISTINCT initcap('   hello   world   ') AS `initcap('   hello   world   ')`;
SELECT initcap(initcap('one,two.three;four')) AS `initcap(initcap('one,two.three;four'))`;
SELECT initcap(1) AS `initcap(1)`;
SELECT DISTINCT initcap('one,two.three;four') AS `initcap('one,two.three;four')`;
SELECT initcap(initcap('one,two.three;four')) AS `initcap(initcap('one,two.three;four'))`;
SELECT initcap(-1.0E308) AS `initcap(-1.0E308)`;
SELECT initcap(CAST('one,two.three;four' AS DECIMAL128(38,37))) AS `initcap(CAST('one,two.three;four' AS DECIMAL128(38,37)))`;
SELECT initcap('one,two.three;four') AS `initcap('one,two.three;four')` ORDER BY initcap('one,two.three;four') DESC;
SELECT initcap(2147483647) AS `initcap(2147483647)`;
SELECT DISTINCT initcap('one,two.three;four') AS `initcap('one,two.three;four')`;
SELECT initcap(NULL) AS `initcap(NULL)`;
SELECT initcap('one,two.three;four') AS `initcap('one,two.three;four')` GROUP BY initcap('one,two.three;four');
SELECT initcap(-1.0E308) AS `initcap(-1.0E308)`;
SELECT CAST((initcap('one,two.three;four')) AS JSON)->'$.a' AS `CAST((initcap('one,two.three;four')) AS JSON)->'$.a'`;
SELECT initcap('one,two.three;four') AS `initcap('one,two.three;four')`;
SELECT count(initcap('one,two.three;four')) OVER () AS `count(initcap('one,two.three;four')) OVER ()`;
SELECT initcap(initcap('one,two.three;four')) AS `initcap(initcap('one,two.three;four'))`;
SELECT initcap('one,two.three;four') AS `initcap('one,two.three;four')`;
SELECT initcap('one,two.three;four') AS `initcap('one,two.three;four')` GROUP BY initcap('one,two.three;four');
SELECT initcap(initcap('one,two.three;four')) AS `initcap(initcap('one,two.three;four'))`;
SELECT min(initcap('one,two.three;four')) OVER () AS `min(initcap('one,two.three;four')) OVER ()`;
SELECT initcap('one,two.three;four') AS `initcap('one,two.three;four')` ORDER BY initcap('one,two.three;four') DESC;
SELECT initcap('one,two.three;four') AS `initcap('one,two.three;four')`;
SELECT initcap('one,two.three;four') AS `initcap('one,two.three;four')`;
SELECT initcap(initcap('one,two.three;four')) AS `initcap(initcap('one,two.three;four'))`;
SELECT DISTINCT initcap('one,two.three;four') AS `initcap('one,two.three;four')`;
SELECT initcap('one,two.three;four') AS `initcap('one,two.three;four')`;
SELECT initcap('\\') AS `initcap('\\')`;
SELECT initcap(initcap('one,two.three;four')) AS `initcap(initcap('one,two.three;four'))`;
SELECT DISTINCT initcap('one,two.three;four') AS `initcap('one,two.three;four')`;
SELECT DISTINCT initcap('alpha-beta_gamma') AS `initcap('alpha-beta_gamma')`;
SELECT initcap('alpha-beta_gamma') AS `initcap('alpha-beta_gamma')`;
SELECT initcap('alpha-beta_gamma') AS `initcap('alpha-beta_gamma')`;
SELECT initcap(-9223372036854775808) AS `initcap(-9223372036854775808)`;
SELECT initcap(1.0E308) AS `initcap(1.0E308)`;
SELECT initcap('HELLO WORLD') AS `initcap('HELLO WORLD')`;
SELECT initcap('alpha-beta_gamma') AS `initcap('alpha-beta_gamma')`;
SELECT initcap('alpha-beta_gamma') AS `initcap('alpha-beta_gamma')` GROUP BY initcap('alpha-beta_gamma');
SELECT CAST((initcap('alpha-beta_gamma')) AS JSON)->'$.a' AS `CAST((initcap('alpha-beta_gamma')) AS JSON)->'$.a'`;
SELECT initcap('alpha-beta_gamma') AS `initcap('alpha-beta_gamma')`;
SELECT initcap('alpha-beta_gamma') AS `initcap('alpha-beta_gamma')`;
SELECT initcap('alpha-beta_gamma') AS `initcap('alpha-beta_gamma')`;
SELECT initcap('%') AS `initcap('%')`;
SELECT initcap(1) AS `initcap(1)`;
SELECT initcap(repeat('x', 65536)) AS `initcap(repeat('x', 65536))`;
SELECT initcap(-1.0E308) AS `initcap(-1.0E308)`;
SELECT initcap(initcap('alpha-beta_gamma')) AS `initcap(initcap('alpha-beta_gamma'))`;
SELECT initcap('alpha-beta_gamma') AS `initcap('alpha-beta_gamma')`;
SELECT initcap('alpha-beta_gamma') AS `initcap('alpha-beta_gamma')` WHERE initcap('hElLo wOrLd');
SELECT initcap('alpha-beta_gamma') AS `initcap('alpha-beta_gamma')` ORDER BY initcap('alpha-beta_gamma') ASC;
SELECT initcap('alpha-beta_gamma') AS `initcap('alpha-beta_gamma')` GROUP BY initcap('alpha-beta_gamma');
SELECT initcap('.') AS `initcap('.')`;
SELECT initcap('alpha-beta_gamma') AS `initcap('alpha-beta_gamma')`;
SELECT initcap(initcap('alpha-beta_gamma')) AS `initcap(initcap('alpha-beta_gamma'))`;
SELECT initcap('\\') AS `initcap('\\')`;
SELECT initcap(NULL) AS `initcap(NULL)`;
SELECT initcap(initcap('alpha-beta_gamma')) AS `initcap(initcap('alpha-beta_gamma'))`;
SELECT initcap(initcap('alpha-beta_gamma')) AS `initcap(initcap('alpha-beta_gamma'))`;
SELECT initcap(initcap('alpha-beta_gamma')) AS `initcap(initcap('alpha-beta_gamma'))`;
SELECT initcap('alpha-beta_gamma') AS `initcap('alpha-beta_gamma')`;
SELECT initcap(TRUE) AS `initcap(TRUE)`;
SELECT initcap('1970-01-01') AS `initcap('1970-01-01')`;
SELECT initcap(1) AS `initcap(1)`;
SELECT initcap('alpha-beta_gamma') AS `initcap('alpha-beta_gamma')`;
SELECT initcap('1st place') AS `initcap('1st place')` GROUP BY initcap('1st place');
SELECT initcap('1st place') AS `initcap('1st place')` LIMIT 2;
SELECT initcap('1st place') AS `initcap('1st place')` LIMIT 2;
SELECT initcap('1st place') AS `initcap('1st place')` WHERE '';
SELECT initcap(1) AS `initcap(1)`;
SELECT initcap('1st place') AS `initcap('1st place')` GROUP BY initcap('1st place');
SELECT initcap(initcap('1st place')) AS `initcap(initcap('1st place'))`;
SELECT initcap('1st place') AS `initcap('1st place')` ORDER BY initcap('1st place') ASC NULLS LAST;
SELECT CAST((CAST((CAST((initcap('1st place')) AS DOUBLE)) AS FLOAT)) AS BOOLEAN) AS `CAST((CAST((CAST((initcap('1st place')) AS DOUBLE)) AS FLOAT)) AS BOOLEAN)`;
SELECT initcap(initcap('1st place')) AS `initcap(initcap('1st place'))`;
SELECT initcap('1st place') AS `initcap('1st place')` ORDER BY initcap('1st place') DESC;
SELECT initcap('1st place') AS `initcap('1st place')`;
SELECT initcap('1st place') AS `initcap('1st place')` ORDER BY initcap('1st place') ASC;
SELECT initcap('1st place') AS `initcap('1st place')` WHERE 'hElLo wOrLd';
SELECT initcap(initcap('')) AS `initcap(initcap(''))`;
SELECT initcap(1.0E308) AS `initcap(1.0E308)`;
SELECT initcap(0.0) AS `initcap(0.0)`;
SELECT initcap('1st place') AS `initcap('1st place')` LIMIT 7, 1;
SELECT initcap('1st place') AS `initcap('1st place')`;
SELECT max(initcap('1st place')) OVER () AS `max(initcap('1st place')) OVER ()`;
SELECT initcap(1) AS `initcap(1)`;
SELECT initcap('1st place') AS `initcap('1st place')`;
SELECT initcap(1) AS `initcap(1)`;
SELECT initcap('0') AS `initcap('0')`;
SELECT DISTINCT initcap('1st place') AS `initcap('1st place')`;
SELECT initcap('1st place') AS `initcap('1st place')`;
SELECT DISTINCT initcap('1st place') AS `initcap('1st place')`;
SELECT initcap(170141183460469231731687303715884105727) AS `initcap(170141183460469231731687303715884105727)`;
SELECT initcap('word1 word2') AS `initcap('word1 word2')` LIMIT 100;
SELECT initcap('word1 word2') AS `initcap('word1 word2')`;
SELECT initcap('word1 word2') AS `initcap('word1 word2')`;
SELECT initcap('word1 word2') AS `initcap('word1 word2')`;
SELECT initcap('word1 word2') AS `initcap('word1 word2')` GROUP BY initcap('word1 word2');
SELECT initcap(-1) AS `initcap(-1)`;
SELECT initcap('0000-00-00') AS `initcap('0000-00-00')`;
SELECT initcap('word1 word2') AS `initcap('word1 word2')`;
SELECT initcap('1970-01-01') AS `initcap('1970-01-01')`;
SELECT initcap('word1 word2') AS `initcap('word1 word2')`;
SELECT min(initcap('word1 word2')) OVER () AS `min(initcap('word1 word2')) OVER ()`;
SELECT initcap(repeat('x', 65536)) AS `initcap(repeat('x', 65536))`;
SELECT initcap('word1 word2') AS `initcap('word1 word2')` WHERE 'A';
SELECT DISTINCT initcap('word1 word2') AS `initcap('word1 word2')`;
SELECT initcap(initcap('word1 word2')) AS `initcap(initcap('word1 word2'))`;
SELECT initcap(initcap('   hello   world   ')) AS `initcap(initcap('   hello   world   '))`;
SELECT initcap('9999-12-31 23:59:59') AS `initcap('9999-12-31 23:59:59')`;
SELECT initcap('word1 word2') AS `initcap('word1 word2')` WHERE 'a';
SELECT initcap(initcap('word1 word2')) AS `initcap(initcap('word1 word2'))`;
SELECT initcap('word1 word2') AS `initcap('word1 word2')`;
SELECT initcap('word1 word2') AS `initcap('word1 word2')` WHERE initcap('alpha-beta_gamma');
SELECT initcap(initcap('word1 word2')) AS `initcap(initcap('word1 word2'))`;
SELECT initcap(initcap('word1 word2')) AS `initcap(initcap('word1 word2'))`;
SELECT initcap('word1 word2') AS `initcap('word1 word2')` WHERE initcap('macDonald');
SELECT initcap('word1 word2') AS `initcap('word1 word2')` ORDER BY initcap('word1 word2') DESC;
SELECT initcap(initcap('word1 word2')) AS `initcap(initcap('word1 word2'))`;
SELECT initcap('%') AS `initcap('%')`;
SELECT initcap('0000-00-00') AS `initcap('0000-00-00')`;
SELECT initcap('123abc456') AS `initcap('123abc456')`;
SELECT DISTINCT initcap('123abc456') AS `initcap('123abc456')`;
SELECT initcap(initcap('123abc456')) AS `initcap(initcap('123abc456'))`;
SELECT initcap(CAST('123abc456' AS JSON)->'$.a') AS `initcap(CAST('123abc456' AS JSON)->'$.a')`;
SELECT initcap('123abc456') AS `initcap('123abc456')` LIMIT 100;
SELECT initcap('123abc456') AS `initcap('123abc456')`;
SELECT initcap('0') AS `initcap('0')`;
SELECT initcap(CAST((CAST('123abc456' AS JSON)) AS FLOAT)) AS `initcap(CAST((CAST('123abc456' AS JSON)) AS FLOAT))`;
SELECT initcap(-1) AS `initcap(-1)`;
SELECT initcap('123abc456') AS `initcap('123abc456')`;
SELECT initcap('123abc456') AS `initcap('123abc456')` GROUP BY initcap('123abc456');
SELECT initcap(initcap('123abc456')) AS `initcap(initcap('123abc456'))`;
SELECT initcap(1) AS `initcap(1)`;
SELECT initcap('123abc456') AS `initcap('123abc456')`;
SELECT initcap(0.0) AS `initcap(0.0)`;
SELECT initcap('1970-01-01') AS `initcap('1970-01-01')`;
SELECT initcap(initcap('123abc456')) AS `initcap(initcap('123abc456'))`;
SELECT initcap('123abc456') AS `initcap('123abc456')`;
SELECT initcap(1.0E308) AS `initcap(1.0E308)`;
SELECT initcap('123abc456') AS `initcap('123abc456')`;
SELECT initcap('123abc456') AS `initcap('123abc456')` WHERE initcap('hElLo wOrLd');
SELECT json_query(CAST((initcap('123abc456')) AS JSON), '$.a') AS `json_query(CAST((initcap('123abc456')) AS JSON), '$.a')`;
SELECT initcap('123abc456') AS `initcap('123abc456')`;
SELECT initcap('1st place') AS `initcap('1st place')`;
SELECT initcap('123abc456') AS `initcap('123abc456')`;
SELECT DISTINCT initcap('123abc456') AS `initcap('123abc456')`;
SELECT DISTINCT initcap('123abc456') AS `initcap('123abc456')`;
SELECT DISTINCT initcap('123abc456') AS `initcap('123abc456')`;
SELECT initcap(initcap('123abc456')) AS `initcap(initcap('123abc456'))`;
SELECT initcap('123abc456') AS `initcap('123abc456')` LIMIT 100;
SELECT initcap('%') AS `initcap('%')`;
SELECT initcap('macDonald') AS `initcap('macDonald')`;
SELECT initcap('macDonald') AS `initcap('macDonald')`;
SELECT initcap('macDonald') AS `initcap('macDonald')`;
SELECT initcap(1.0E308) AS `initcap(1.0E308)`;
SELECT initcap(get_json_string(CAST('macDonald' AS JSON), '$.a')) AS `initcap(get_json_string(CAST('macDonald' AS JSON), '$.a'))`;
SELECT initcap(initcap('macDonald')) AS `initcap(initcap('macDonald'))`;
SELECT initcap(initcap('macDonald')) AS `initcap(initcap('macDonald'))`;
SELECT initcap('macDonald') AS `initcap('macDonald')`;
SELECT initcap(initcap('macDonald')) AS `initcap(initcap('macDonald'))`;
SELECT initcap(initcap('macDonald')) AS `initcap(initcap('macDonald'))`;
SELECT initcap('macDonald') AS `initcap('macDonald')` ORDER BY initcap('macDonald') ASC;
SELECT initcap('0000-00-00') AS `initcap('0000-00-00')`;
SELECT initcap('macDonald') AS `initcap('macDonald')`;
SELECT initcap('macDonald') AS `initcap('macDonald')`;
SELECT initcap(0.0) AS `initcap(0.0)`;
SELECT initcap('macDonald') AS `initcap('macDonald')` ORDER BY initcap('macDonald') DESC NULLS FIRST;
SELECT initcap('macDonald') AS `initcap('macDonald')`;
SELECT initcap(initcap('macDonald')) AS `initcap(initcap('macDonald'))`;
SELECT initcap(CAST(NULL AS JSON)) AS `initcap(CAST(NULL AS JSON))`;
SELECT initcap('macDonald') AS `initcap('macDonald')` LIMIT 7, 100;
SELECT initcap(-1) AS `initcap(-1)`;
SELECT initcap('macDonald') AS `initcap('macDonald')` WHERE initcap('hello world');
SELECT initcap('macDonald') AS `initcap('macDonald')` WHERE initcap('?');
SELECT initcap('') AS `initcap('')`;
SELECT initcap('macDonald') AS `initcap('macDonald')`;
SELECT initcap('macDonald') AS `initcap('macDonald')` WHERE '';
SELECT initcap('macDonald') AS `initcap('macDonald')`;
SELECT initcap('%') AS `initcap('%')`;
SELECT initcap(initcap('a')) AS `initcap(initcap('a'))`;
SELECT initcap(NULL) AS `initcap(NULL)`;
SELECT initcap('a') AS `initcap('a')` GROUP BY initcap('a');
SELECT DISTINCT initcap('a') AS `initcap('a')`;
SELECT initcap('a') AS `initcap('a')` LIMIT 1, 100;
SELECT initcap(initcap('a')) AS `initcap(initcap('a'))`;
SELECT initcap('a') AS `initcap('a')` LIMIT 1, 2;
SELECT initcap('a') AS `initcap('a')`;
SELECT CAST((initcap('a')) AS JSON)->'k' AS `CAST((initcap('a')) AS JSON)->'k'`;
SELECT initcap('') AS `initcap('')`;
SELECT initcap('a') AS `initcap('a')` LIMIT 7, 2;
SELECT initcap('a') AS `initcap('a')` WHERE initcap('A');
SELECT initcap('a') AS `initcap('a')`;
SELECT initcap('a') AS `initcap('a')`;
SELECT initcap('a') AS `initcap('a')`;
SELECT initcap('%') AS `initcap('%')`;
SELECT initcap(-9223372036854775808) AS `initcap(-9223372036854775808)`;
SELECT initcap(initcap('a')) AS `initcap(initcap('a'))`;
SELECT initcap(initcap('a')) AS `initcap(initcap('a'))`;
SELECT initcap('a') AS `initcap('a')`;
SELECT initcap(initcap('a')) AS `initcap(initcap('a'))`;
SELECT initcap('\\') AS `initcap('\\')`;
SELECT initcap('z') AS `initcap('z')`;
SELECT initcap(1.0E308) AS `initcap(1.0E308)`;
SELECT initcap(-1.0E308) AS `initcap(-1.0E308)`;
SELECT DISTINCT initcap('a') AS `initcap('a')`;
SELECT initcap('a') AS `initcap('a')` WHERE initcap('hello world');
SELECT initcap(9223372036854775807) AS `initcap(9223372036854775807)`;
SELECT initcap('a') AS `initcap('a')`;
SELECT get_json_string(CAST((initcap('a')) AS JSON), '$.a') AS `get_json_string(CAST((initcap('a')) AS JSON), '$.a')`;
SELECT initcap(0.0) AS `initcap(0.0)`;
SELECT DISTINCT initcap('a') AS `initcap('a')`;
SELECT DISTINCT initcap('a') AS `initcap('a')`;
SELECT initcap(-1) AS `initcap(-1)`;
SELECT initcap(initcap('A')) AS `initcap(initcap('A'))`;
SELECT initcap(initcap('A')) AS `initcap(initcap('A'))`;
SELECT initcap('1970-01-01') AS `initcap('1970-01-01')`;
SELECT initcap('A') AS `initcap('A')` ORDER BY initcap('A') ASC NULLS LAST;
SELECT DISTINCT initcap('A') AS `initcap('A')`;
SELECT initcap(CAST('A' AS JSON)->'k') AS `initcap(CAST('A' AS JSON)->'k')`;
SELECT initcap('A') AS `initcap('A')` WHERE initcap('123abc456');
SELECT initcap(json_query(CAST('A' AS JSON), '$.a')) AS `initcap(json_query(CAST('A' AS JSON), '$.a'))`;
SELECT initcap('A') AS `initcap('A')` GROUP BY initcap('A');
SELECT initcap('A') AS `initcap('A')` WHERE 'z';
SELECT initcap('A') AS `initcap('A')`;
SELECT initcap('A') AS `initcap('A')` GROUP BY initcap('A');
SELECT initcap('123abc456') AS `initcap('123abc456')`;
SELECT initcap(2147483647) AS `initcap(2147483647)`;
SELECT initcap('0') AS `initcap('0')`;
SELECT initcap('A') AS `initcap('A')`;
SELECT initcap(CAST(NULL AS JSON)) AS `initcap(CAST(NULL AS JSON))`;
SELECT initcap('A') AS `initcap('A')` LIMIT 5;
SELECT initcap('A') AS `initcap('A')`;
SELECT initcap('A') AS `initcap('A')` GROUP BY initcap('A');
SELECT initcap(1.0E308) AS `initcap(1.0E308)`;
SELECT initcap('A') AS `initcap('A')`;
SELECT initcap('A') AS `initcap('A')` ORDER BY initcap('A') DESC;
SELECT initcap(initcap('A')) AS `initcap(initcap('A'))`;
SELECT initcap(initcap('A')) AS `initcap(initcap('A'))`;
SELECT CAST((initcap('A')) AS JSON)->'$' AS `CAST((initcap('A')) AS JSON)->'$'`;
SELECT initcap('A') AS `initcap('A')`;
SELECT initcap(TRUE) AS `initcap(TRUE)`;
SELECT initcap(NULL) AS `initcap(NULL)`;
SELECT initcap('A') AS `initcap('A')` LIMIT 1;
SELECT initcap(json_length(CAST('z' AS JSON))) AS `initcap(json_length(CAST('z' AS JSON)))`;
SELECT initcap(initcap('alpha-beta_gamma')) AS `initcap(initcap('alpha-beta_gamma'))`;
SELECT initcap('z') AS `initcap('z')` GROUP BY initcap('z');
SELECT initcap(1.0E308) AS `initcap(1.0E308)`;
SELECT initcap(-9223372036854775808) AS `initcap(-9223372036854775808)`;
SELECT initcap('0000-00-00') AS `initcap('0000-00-00')`;
SELECT initcap('') AS `initcap('')`;
SELECT initcap(initcap('z')) AS `initcap(initcap('z'))`;
SELECT initcap('z') AS `initcap('z')`;
SELECT initcap(initcap('z')) AS `initcap(initcap('z'))`;
SELECT initcap(9223372036854775807) AS `initcap(9223372036854775807)`;
SELECT initcap(1.0E308) AS `initcap(1.0E308)`;
SELECT initcap(-2147483648) AS `initcap(-2147483648)`;
SELECT initcap('z') AS `initcap('z')` LIMIT 1;
SELECT initcap('z') AS `initcap('z')` GROUP BY initcap('z');
SELECT initcap('z') AS `initcap('z')` LIMIT 2;
SELECT initcap(initcap('z')) AS `initcap(initcap('z'))`;
SELECT DISTINCT initcap('z') AS `initcap('z')`;
SELECT initcap('z') AS `initcap('z')` GROUP BY initcap('z');
SELECT initcap(CAST(NULL AS JSON)) AS `initcap(CAST(NULL AS JSON))`;
SELECT DISTINCT initcap('z') AS `initcap('z')`;
SELECT initcap('z') AS `initcap('z')`;
SELECT initcap('z') AS `initcap('z')` ORDER BY initcap('z') DESC NULLS FIRST;
SELECT initcap(initcap('z')) AS `initcap(initcap('z'))`;
SELECT initcap('z') AS `initcap('z')` GROUP BY initcap('z');
SELECT initcap('9999-12-31 23:59:59') AS `initcap('9999-12-31 23:59:59')`;
SELECT initcap(initcap('.')) AS `initcap(initcap('.'))`;
SELECT initcap('.') AS `initcap('.')` ORDER BY initcap('.') ASC;
SELECT initcap(initcap('.')) AS `initcap(initcap('.'))`;
SELECT DISTINCT initcap('.') AS `initcap('.')`;
SELECT initcap(CAST('.' AS JSON)->'$.a') AS `initcap(CAST('.' AS JSON)->'$.a')`;
SELECT sum(initcap('.')) OVER () AS `sum(initcap('.')) OVER ()`;
SELECT initcap('.') AS `initcap('.')` GROUP BY initcap('.');
SELECT initcap(1) AS `initcap(1)`;
SELECT initcap('.') AS `initcap('.')` ORDER BY initcap('.') DESC;
SELECT DISTINCT initcap('.') AS `initcap('.')`;
SELECT initcap('.') AS `initcap('.')`;
SELECT initcap(initcap('.')) AS `initcap(initcap('.'))`;
SELECT initcap(initcap('.')) AS `initcap(initcap('.'))`;
SELECT initcap(repeat('x', 65536)) AS `initcap(repeat('x', 65536))`;
SELECT initcap(1) AS `initcap(1)`;
SELECT initcap(CAST(NULL AS JSON)) AS `initcap(CAST(NULL AS JSON))`;
SELECT avg(initcap('.')) OVER () AS `avg(initcap('.')) OVER ()`;
SELECT initcap(CAST(NULL AS JSON)) AS `initcap(CAST(NULL AS JSON))`;
SELECT initcap(json_query(CAST('.' AS JSON), '$.a')) AS `initcap(json_query(CAST('.' AS JSON), '$.a'))`;
SELECT initcap('.') AS `initcap('.')`;
SELECT sum(initcap('.')) OVER () AS `sum(initcap('.')) OVER ()`;
SELECT initcap(initcap('.')) AS `initcap(initcap('.'))`;
SELECT initcap('.') AS `initcap('.')` GROUP BY initcap('.');
SELECT DISTINCT initcap('.') AS `initcap('.')`;
SELECT initcap(CAST((CAST('.' AS TINYINT)) AS DECIMAL128(38,38))) AS `initcap(CAST((CAST('.' AS TINYINT)) AS DECIMAL128(38,38)))`;
SELECT initcap('0000-00-00') AS `initcap('0000-00-00')`;
SELECT initcap('.') AS `initcap('.')`;
SELECT initcap(initcap('.')) AS `initcap(initcap('.'))`;
SELECT initcap(2147483647) AS `initcap(2147483647)`;
SELECT initcap('?') AS `initcap('?')` GROUP BY initcap('?');
SELECT DISTINCT initcap('?') AS `initcap('?')`;
SELECT initcap('?') AS `initcap('?')`;
SELECT initcap('?') AS `initcap('?')` ORDER BY initcap('?') ASC;
SELECT initcap('?') AS `initcap('?')` WHERE '.';
SELECT initcap('?') AS `initcap('?')`;
SELECT initcap(0.0) AS `initcap(0.0)`;
SELECT initcap(initcap('?')) AS `initcap(initcap('?'))`;
SELECT initcap('?') AS `initcap('?')`;
SELECT initcap(initcap('?')) AS `initcap(initcap('?'))`;
SELECT initcap('?') AS `initcap('?')`;
SELECT initcap(initcap('?')) AS `initcap(initcap('?'))`;
SELECT initcap(initcap('?')) AS `initcap(initcap('?'))`;
SELECT initcap('') AS `initcap('')`;
SELECT DISTINCT initcap('?') AS `initcap('?')`;
SELECT initcap('?') AS `initcap('?')` LIMIT 0;
SELECT initcap('?') AS `initcap('?')` LIMIT 0;
SELECT initcap('') AS `initcap('')`;
SELECT initcap('?') AS `initcap('?')` ORDER BY initcap('?') DESC;
SELECT initcap('0') AS `initcap('0')`;
SELECT initcap(initcap('?')) AS `initcap(initcap('?'))`;
SELECT initcap(initcap('?')) AS `initcap(initcap('?'))`;
SELECT initcap(initcap('?')) AS `initcap(initcap('?'))`;
SELECT initcap('?') AS `initcap('?')`;
SELECT DISTINCT initcap('?') AS `initcap('?')`;
SELECT initcap('') AS `initcap('')`;
SELECT initcap('1970-01-01') AS `initcap('1970-01-01')`;
SELECT initcap(initcap('?')) AS `initcap(initcap('?'))`;
SELECT initcap('?') AS `initcap('?')`;
SELECT initcap(initcap('?')) AS `initcap(initcap('?'))`;
SELECT initcap(json_query(CAST('?' AS JSON), '$.a')) AS `initcap(json_query(CAST('?' AS JSON), '$.a'))`;
SELECT initcap('?') AS `initcap('?')` GROUP BY initcap('?');
SELECT initcap('?') AS `initcap('?')`;
SELECT initcap('?') AS `initcap('?')`;
SELECT initcap('') AS `initcap('')`;
SELECT DISTINCT initcap('') AS `initcap('')`;
SELECT json_length(CAST((initcap('')) AS JSON)) AS `json_length(CAST((initcap('')) AS JSON))`;
SELECT initcap(initcap('')) AS `initcap(initcap(''))`;
SELECT initcap(NULL) AS `initcap(NULL)`;
SELECT initcap('') AS `initcap('')` LIMIT 100;
SELECT initcap('9999-12-31 23:59:59') AS `initcap('9999-12-31 23:59:59')`;
SELECT initcap(initcap('')) AS `initcap(initcap(''))`;
SELECT initcap('') AS `initcap('')` ORDER BY initcap('') DESC NULLS FIRST;
SELECT initcap(TRUE) AS `initcap(TRUE)`;
SELECT initcap(2147483647) AS `initcap(2147483647)`;
SELECT initcap(0) AS `initcap(0)`;
SELECT min(initcap('')) OVER () AS `min(initcap('')) OVER ()`;
SELECT initcap(get_json_string(CAST('' AS JSON), '$.a')) AS `initcap(get_json_string(CAST('' AS JSON), '$.a'))`;
SELECT DISTINCT initcap('') AS `initcap('')`;
SELECT initcap('') AS `initcap('')`;
SELECT initcap(initcap('')) AS `initcap(initcap(''))`;
SELECT initcap('1970-01-01') AS `initcap('1970-01-01')`;
SELECT initcap('') AS `initcap('')`;
SELECT initcap('') AS `initcap('')` ORDER BY initcap('') DESC;
SELECT initcap(initcap('')) AS `initcap(initcap(''))`;
SELECT initcap('') AS `initcap('')`;
SELECT initcap('') AS `initcap('')`;
SELECT initcap(-2147483648) AS `initcap(-2147483648)`;
SELECT initcap('') AS `initcap('')` LIMIT 5;
SELECT initcap(1) AS `initcap(1)`;
SELECT initcap('') AS `initcap('')` ORDER BY initcap('') DESC;
SELECT initcap(initcap('')) AS `initcap(initcap(''))`;
SELECT DISTINCT initcap('') AS `initcap('')`;
SELECT initcap(-1) AS `initcap(-1)`;
SELECT initcap('') AS `initcap('')` ORDER BY initcap('') DESC;
SELECT initcap(initcap('')) AS `initcap(initcap(''))`;
SELECT DISTINCT initcap('') AS `initcap('')`;
SELECT json_query(CAST((initcap('')) AS JSON), '$.a') AS `json_query(CAST((initcap('')) AS JSON), '$.a')`;
SELECT initcap('') AS `initcap('')`;
SELECT initcap('') AS `initcap('')`;
SELECT initcap('') AS `initcap('')`;
SELECT initcap(NULL) AS `initcap(NULL)`;
SELECT initcap(170141183460469231731687303715884105727) AS `initcap(170141183460469231731687303715884105727)`;
SELECT initcap(NULL) AS `initcap(NULL)` WHERE initcap('z');
SELECT initcap(NULL) AS `initcap(NULL)` GROUP BY initcap(NULL);
SELECT initcap('0') AS `initcap('0')`;
SELECT initcap(0) AS `initcap(0)`;
SELECT initcap('%') AS `initcap('%')`;
SELECT initcap('0') AS `initcap('0')`;
SELECT initcap(NULL) AS `initcap(NULL)` GROUP BY initcap(NULL);
SELECT initcap(array_length(NULL)) AS `initcap(array_length(NULL))`;
SELECT initcap(9223372036854775807) AS `initcap(9223372036854775807)`;
SELECT initcap(TRUE) AS `initcap(TRUE)`;
SELECT initcap(9223372036854775807) AS `initcap(9223372036854775807)`;
SELECT initcap(initcap('hElLo wOrLd')) AS `initcap(initcap('hElLo wOrLd'))`;
SELECT initcap(0.0) AS `initcap(0.0)`;
SELECT initcap(initcap(NULL)) AS `initcap(initcap(NULL))`;
SELECT initcap('   hello   world   ') AS `initcap('   hello   world   ')`;
SELECT initcap(NULL) AS `initcap(NULL)` ORDER BY initcap(NULL) ASC;
SELECT initcap(initcap(NULL)) AS `initcap(initcap(NULL))`;
SELECT initcap(NULL) AS `initcap(NULL)`;
SELECT initcap(NULL) AS `initcap(NULL)` ORDER BY initcap(NULL) ASC NULLS LAST;
SELECT initcap(NULL) AS `initcap(NULL)` WHERE 'hello world';
SELECT initcap(9223372036854775807) AS `initcap(9223372036854775807)`;
SELECT initcap(-2147483648) AS `initcap(-2147483648)`;
SELECT initcap(NULL) AS `initcap(NULL)`;
SELECT initcap(NULL) AS `initcap(NULL)` ORDER BY initcap(NULL) DESC;
SELECT DISTINCT initcap(NULL) AS `initcap(NULL)`;
SELECT initcap(TRUE) AS `initcap(TRUE)`;
SELECT initcap(NULL) AS `initcap(NULL)`;
SELECT initcap(CAST(NULL AS JSON)) AS `initcap(CAST(NULL AS JSON))`;
SELECT DISTINCT initcap(NULL) AS `initcap(NULL)`;
SELECT initcap(NULL) AS `initcap(NULL)` LIMIT 1;
SELECT initcap(initcap(NULL)) AS `initcap(initcap(NULL))`;
SELECT initcap(NULL) AS `initcap(NULL)` ORDER BY initcap(NULL) DESC;
SELECT initcap(initcap(NULL)) AS `initcap(initcap(NULL))`;
SELECT `t_initcap_test`.`id`, `t_initcap_test`.`str`, initcap(`t_initcap_test`.`str`) AS `initcap(str)` FROM (SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str` FROM `srfuzz_mut_1196`.`t_initcap_test` UNION SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str` FROM `srfuzz_mut_1196`.`t_initcap_test`) `t_initcap_test` ORDER BY `t_initcap_test`.`id` ASC;
SELECT DISTINCT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`str`) AS `initcap(str)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT DISTINCT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`str`) AS `initcap(str)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`id`) AS `initcap(id)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`id`) AS `initcap(srfuzz_mut_1196.t_initcap_test.id)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `t_initcap_test`.`id`, `t_initcap_test`.`str`, initcap(`t_initcap_test`.`str`) AS `initcap(str)` FROM (SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str` FROM `srfuzz_mut_1196`.`t_initcap_test`) `t_initcap_test` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  ORDER BY `t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`str`) AS `initcap(srfuzz_mut_1196.t_initcap_test.str)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`str`) AS `initcap(str)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`id`) AS `initcap(srfuzz_mut_1196.t_initcap_test.id)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`str`) AS `initcap(str)` FROM `srfuzz_mut_1196`.`t_initcap_test` GROUP BY `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`str`) ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`id`) AS `initcap(srfuzz_mut_1196.t_initcap_test.id)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `t_initcap_test`.`id`, `t_initcap_test`.`str`, initcap(`t_initcap_test`.`str`) AS `initcap(str)` FROM (SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str` FROM `srfuzz_mut_1196`.`t_initcap_test`) `t_initcap_test` ORDER BY `t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`str`) AS `initcap(srfuzz_mut_1196.t_initcap_test.str)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`id`) AS `initcap(srfuzz_mut_1196.t_initcap_test.id)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`str`) AS `initcap(str)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`id`) AS `initcap(id)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`id`) AS `initcap(id)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`str`) AS `initcap(str)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`id`) AS `initcap(srfuzz_mut_1196.t_initcap_test.id)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`str`) AS `initcap(str)` FROM `srfuzz_mut_1196`.`t_initcap_test` WHERE initcap(`srfuzz_mut_1196`.`t_initcap_test`.`str`) ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`id`) AS `initcap(id)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`str`) AS `initcap(srfuzz_mut_1196.t_initcap_test.str)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`str`) AS `initcap(srfuzz_mut_1196.t_initcap_test.str)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`id`) AS `initcap(srfuzz_mut_1196.t_initcap_test.id)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(CAST(`srfuzz_mut_1196`.`t_initcap_test`.`str` AS DOUBLE)) AS `initcap(CAST(str AS DOUBLE))` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`id`) AS `initcap(id)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`str`) AS `initcap(str)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `t_initcap_test`.`id`, `t_initcap_test`.`str`, initcap(`t_initcap_test`.`str`) AS `initcap(str)` FROM (SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str` FROM `srfuzz_mut_1196`.`t_initcap_test` EXCEPT SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str` FROM `srfuzz_mut_1196`.`t_initcap_test`) `t_initcap_test` ORDER BY `t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`str`) AS `initcap(str)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`str`) AS `initcap(str)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC  LIMIT 1;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`id`) AS `initcap(id)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str` FROM `srfuzz_mut_1196`.`t_initcap_test`) SELECT `t_initcap_test`.`id`, `t_initcap_test`.`str`, initcap(`t_initcap_test`.`str`) AS `initcap(str)` FROM `srfuzz_n1` AS t_initcap_test ORDER BY `t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(initcap(`srfuzz_mut_1196`.`t_initcap_test`.`str`)) AS `initcap(initcap(srfuzz_mut_1196.t_initcap_test.str))` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`str`) AS `initcap(srfuzz_mut_1196.t_initcap_test.str)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`str`) AS `initcap(srfuzz_mut_1196.t_initcap_test.str)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`str`) AS `initcap(srfuzz_mut_1196.t_initcap_test.str)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(initcap(`srfuzz_mut_1196`.`t_initcap_test`.`str`)) AS `initcap(initcap(srfuzz_mut_1196.t_initcap_test.str))` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;
SELECT `srfuzz_mut_1196`.`t_initcap_test`.`id`, `srfuzz_mut_1196`.`t_initcap_test`.`str`, initcap(`srfuzz_mut_1196`.`t_initcap_test`.`str`) AS `initcap(srfuzz_mut_1196.t_initcap_test.str)` FROM `srfuzz_mut_1196`.`t_initcap_test` ORDER BY `srfuzz_mut_1196`.`t_initcap_test`.`id` ASC;