SELECT blake3('abc') AS `blake3('abc')`;
SELECT blake3('l') AS `blake3('l')`;
SELECT blake3('StarRocks') AS `blake3('StarRocks')`;
SELECT blake3('') AS `blake3('')`;
SELECT blake3(CAST(NULL AS VARCHAR)) AS `blake3(CAST(NULL AS VARCHAR))`;
SELECT blake3('hello') AS `blake3('hello')`;
SELECT length(blake3('abc')) AS `length(blake3('abc'))`;
SELECT (blake3('abc')) = (blake3('abc')) AS `(blake3('abc')) = (blake3('abc'))`;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(`srfuzz_mut_414`.`t1`.`v`) AS `blake3(v)` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, length(blake3(`srfuzz_mut_414`.`t1`.`v`)) AS `length(blake3(v))` FROM `srfuzz_mut_414`.`t1` WHERE `srfuzz_mut_414`.`t1`.`v` IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT blake3(blake3('abc')) AS `blake3(blake3('abc'))`;
SELECT blake3('abc') AS `blake3('abc')` ORDER BY blake3('abc') ASC NULLS LAST;
SELECT blake3('StarRocks') AS `blake3('StarRocks')`;
SELECT DISTINCT blake3('abc') AS `blake3('abc')`;
SELECT blake3('abc') AS `blake3('abc')` LIMIT 1, 5;
SELECT blake3('1970-01-01') AS `blake3('1970-01-01')`;
SELECT blake3(0) AS `blake3(0)`;
SELECT blake3('abc') AS `blake3('abc')` ORDER BY blake3('abc') DESC NULLS FIRST;
SELECT blake3(blake3('abc')) AS `blake3(blake3('abc'))`;
SELECT blake3(blake3('abc')) AS `blake3(blake3('abc'))`;
SELECT blake3(blake3('abc')) AS `blake3(blake3('abc'))`;
SELECT blake3('%') AS `blake3('%')`;
SELECT blake3(blake3('abc')) AS `blake3(blake3('abc'))`;
SELECT blake3(CAST(NULL AS JSON)) AS `blake3(CAST(NULL AS JSON))`;
SELECT blake3(CAST(NULL AS JSON)) AS `blake3(CAST(NULL AS JSON))`;
SELECT blake3(-2147483648) AS `blake3(-2147483648)`;
SELECT blake3(blake3('abc')) AS `blake3(blake3('abc'))`;
SELECT blake3(1.0E308) AS `blake3(1.0E308)`;
SELECT blake3('abc') AS `blake3('abc')`;
SELECT blake3('abc') AS `blake3('abc')`;
SELECT blake3('abc') AS `blake3('abc')` LIMIT 5;
SELECT DISTINCT blake3('abc') AS `blake3('abc')`;
SELECT blake3(1.0E308) AS `blake3(1.0E308)`;
SELECT blake3('abc') AS `blake3('abc')`;
SELECT blake3('0') AS `blake3('0')`;
SELECT blake3(blake3('abc')) AS `blake3(blake3('abc'))`;
SELECT blake3(blake3('abc')) AS `blake3(blake3('abc'))`;
SELECT blake3('\\') AS `blake3('\\')`;
SELECT blake3('l') AS `blake3('l')` LIMIT 7, 5;
SELECT blake3(CAST('l' AS JSON)->'$.a') AS `blake3(CAST('l' AS JSON)->'$.a')`;
SELECT blake3(1.0E308) AS `blake3(1.0E308)`;
SELECT CAST((blake3('l')) AS VARCHAR) AS `CAST((blake3('l')) AS VARCHAR)`;
SELECT blake3(blake3('l')) AS `blake3(blake3('l'))`;
SELECT DISTINCT blake3('l') AS `blake3('l')`;
SELECT blake3(blake3('l')) AS `blake3(blake3('l'))`;
SELECT blake3(blake3('l')) AS `blake3(blake3('l'))`;
SELECT blake3(9223372036854775807) AS `blake3(9223372036854775807)`;
SELECT blake3(1) AS `blake3(1)`;
SELECT blake3(FALSE) AS `blake3(FALSE)`;
SELECT blake3(1.0E308) AS `blake3(1.0E308)`;
SELECT blake3('l') AS `blake3('l')`;
SELECT blake3(blake3('l')) AS `blake3(blake3('l'))`;
SELECT blake3('l') AS `blake3('l')` GROUP BY blake3('l');
SELECT blake3(0.0) AS `blake3(0.0)`;
SELECT CAST((blake3('l')) AS JSON)->'$.a' AS `CAST((blake3('l')) AS JSON)->'$.a'`;
SELECT blake3('l') AS `blake3('l')` WHERE (blake3('abc')) = (blake3('abc'));
SELECT blake3('l') AS `blake3('l')` WHERE (blake3('abc')) = (blake3('abc'));
SELECT blake3(blake3('l')) AS `blake3(blake3('l'))`;
SELECT blake3('l') AS `blake3('l')`;
SELECT blake3(FALSE) AS `blake3(FALSE)`;
SELECT blake3('l') AS `blake3('l')` LIMIT 2;
SELECT blake3(repeat('x', 65536)) AS `blake3(repeat('x', 65536))`;
SELECT blake3('l') AS `blake3('l')` GROUP BY blake3('l');
SELECT blake3('l') AS `blake3('l')` LIMIT 1, 1;
SELECT blake3('l') AS `blake3('l')` LIMIT 2;
SELECT blake3('1970-01-01') AS `blake3('1970-01-01')`;
SELECT blake3('StarRocks') AS `blake3('StarRocks')` GROUP BY blake3('StarRocks');
SELECT json_query(CAST((blake3('StarRocks')) AS JSON), '$.a') AS `json_query(CAST((blake3('StarRocks')) AS JSON), '$.a')`;
SELECT blake3('hello') AS `blake3('hello')`;
SELECT blake3(blake3('StarRocks')) AS `blake3(blake3('StarRocks'))`;
SELECT blake3('abc') AS `blake3('abc')`;
SELECT blake3(blake3('StarRocks')) AS `blake3(blake3('StarRocks'))`;
SELECT blake3(-1) AS `blake3(-1)`;
SELECT blake3(blake3('StarRocks')) AS `blake3(blake3('StarRocks'))`;
SELECT DISTINCT blake3('StarRocks') AS `blake3('StarRocks')`;
SELECT blake3(blake3('StarRocks')) AS `blake3(blake3('StarRocks'))`;
SELECT blake3('%') AS `blake3('%')`;
SELECT blake3('\\') AS `blake3('\\')`;
SELECT blake3(blake3('StarRocks')) AS `blake3(blake3('StarRocks'))`;
SELECT blake3(blake3('StarRocks')) AS `blake3(blake3('StarRocks'))`;
SELECT blake3('') AS `blake3('')`;
SELECT blake3(blake3('StarRocks')) AS `blake3(blake3('StarRocks'))`;
SELECT CAST((blake3('StarRocks')) AS JSON)->'$.a' AS `CAST((blake3('StarRocks')) AS JSON)->'$.a'`;
SELECT blake3(2147483647) AS `blake3(2147483647)`;
SELECT DISTINCT blake3('StarRocks') AS `blake3('StarRocks')`;
SELECT blake3(-9223372036854775808) AS `blake3(-9223372036854775808)`;
SELECT blake3(blake3('StarRocks')) AS `blake3(blake3('StarRocks'))`;
SELECT blake3(blake3('StarRocks')) AS `blake3(blake3('StarRocks'))`;
SELECT blake3('0') AS `blake3('0')`;
SELECT blake3('') AS `blake3('')`;
SELECT blake3('StarRocks') AS `blake3('StarRocks')` LIMIT 100;
SELECT blake3('StarRocks') AS `blake3('StarRocks')`;
SELECT blake3('StarRocks') AS `blake3('StarRocks')` ORDER BY blake3('StarRocks') ASC;
SELECT blake3(blake3('StarRocks')) AS `blake3(blake3('StarRocks'))`;
SELECT blake3(blake3('StarRocks')) AS `blake3(blake3('StarRocks'))`;
SELECT blake3('0000-00-00') AS `blake3('0000-00-00')`;
SELECT blake3(CAST('StarRocks' AS DECIMAL128(38,0))) AS `blake3(CAST('StarRocks' AS DECIMAL128(38,0)))`;
SELECT blake3('StarRocks') AS `blake3('StarRocks')` LIMIT 0;
SELECT blake3('StarRocks') AS `blake3('StarRocks')`;
SELECT blake3('1970-01-01') AS `blake3('1970-01-01')`;
SELECT blake3(0) AS `blake3(0)`;
SELECT blake3('') AS `blake3('')`;
SELECT blake3('StarRocks') AS `blake3('StarRocks')`;
SELECT blake3(blake3('')) AS `blake3(blake3(''))`;
SELECT blake3('') AS `blake3('')` LIMIT 5;
SELECT blake3('') AS `blake3('')` LIMIT 100;
SELECT blake3('') AS `blake3('')`;
SELECT blake3(9223372036854775807) AS `blake3(9223372036854775807)`;
SELECT blake3(repeat('x', 65536)) AS `blake3(repeat('x', 65536))`;
SELECT blake3('1970-01-01') AS `blake3('1970-01-01')`;
SELECT blake3(-1.0E308) AS `blake3(-1.0E308)`;
SELECT blake3(FALSE) AS `blake3(FALSE)`;
SELECT DISTINCT blake3('') AS `blake3('')`;
SELECT blake3('') AS `blake3('')`;
SELECT blake3(CAST('' AS JSON)->'$.a') AS `blake3(CAST('' AS JSON)->'$.a')`;
SELECT blake3('') AS `blake3('')` WHERE (blake3('abc')) = (blake3('abc'));
SELECT blake3(CAST((CAST((CAST('' AS VARCHAR)) AS VARCHAR(1))) AS DECIMAL128(38,0))) AS `blake3(CAST((CAST((CAST('' AS VARCHAR)) AS VARCHAR(1))) AS DECIMAL128(38,0)))`;
SELECT CAST((blake3('')) AS LARGEINT) AS `CAST((blake3('')) AS LARGEINT)`;
SELECT blake3(-1) AS `blake3(-1)`;
SELECT blake3('') AS `blake3('')`;
SELECT blake3(0) AS `blake3(0)`;
SELECT blake3(repeat('x', 65536)) AS `blake3(repeat('x', 65536))`;
SELECT blake3(1) AS `blake3(1)`;
SELECT blake3('9999-12-31 23:59:59') AS `blake3('9999-12-31 23:59:59')`;
SELECT blake3(0) AS `blake3(0)`;
SELECT blake3(blake3('')) AS `blake3(blake3(''))`;
SELECT blake3(-1) AS `blake3(-1)`;
SELECT blake3(repeat('x', 65536)) AS `blake3(repeat('x', 65536))`;
SELECT blake3(CAST((CAST((CAST(NULL AS VARCHAR)) AS DECIMAL128(38,37))) AS TINYINT)) AS `blake3(CAST((CAST((CAST(NULL AS VARCHAR)) AS DECIMAL128(38,37))) AS TINYINT))`;
SELECT blake3(blake3(CAST(NULL AS VARCHAR))) AS `blake3(blake3(CAST(NULL AS VARCHAR)))`;
SELECT blake3(CAST(FALSE AS VARCHAR)) AS `blake3(CAST(FALSE AS VARCHAR))`;
SELECT blake3(CAST(NULL AS VARCHAR)) AS `blake3(CAST(NULL AS VARCHAR))`;
SELECT blake3(CAST(NULL AS VARCHAR)) AS `blake3(CAST(NULL AS VARCHAR))` GROUP BY blake3(CAST(NULL AS VARCHAR));
SELECT blake3(CAST((cardinality(NULL)) AS VARCHAR)) AS `blake3(CAST((cardinality(NULL)) AS VARCHAR))`;
SELECT blake3(CAST(NULL AS VARCHAR)) AS `blake3(CAST(NULL AS VARCHAR))`;
SELECT blake3(CAST(-1 AS VARCHAR)) AS `blake3(CAST(-1 AS VARCHAR))`;
SELECT blake3(CAST(NULL AS VARCHAR)) AS `blake3(CAST(NULL AS VARCHAR))` LIMIT 1, 100;
SELECT blake3(CAST(NULL AS VARCHAR)) AS `blake3(CAST(NULL AS VARCHAR))`;
SELECT blake3(CAST(NULL AS VARCHAR)) AS `blake3(CAST(NULL AS VARCHAR))` ORDER BY blake3(CAST(NULL AS VARCHAR)) ASC;
SELECT blake3(NULL) AS `blake3(NULL)`;
SELECT blake3(CAST((CAST(NULL AS VARCHAR)) AS VARCHAR)) AS `blake3(CAST((CAST(NULL AS VARCHAR)) AS VARCHAR))`;
SELECT blake3(blake3(CAST(NULL AS VARCHAR))) AS `blake3(blake3(CAST(NULL AS VARCHAR)))`;
SELECT blake3(CAST((CAST(NULL AS VARCHAR)) AS VARCHAR)) AS `blake3(CAST((CAST(NULL AS VARCHAR)) AS VARCHAR))`;
SELECT DISTINCT blake3(CAST(NULL AS VARCHAR)) AS `blake3(CAST(NULL AS VARCHAR))`;
SELECT blake3(CAST(NULL AS VARCHAR)) AS `blake3(CAST(NULL AS VARCHAR))`;
SELECT blake3(CAST(NULL AS VARCHAR)) AS `blake3(CAST(NULL AS VARCHAR))`;
SELECT blake3(CAST(NULL AS VARCHAR)) AS `blake3(CAST(NULL AS VARCHAR))` WHERE (blake3('abc')) = (blake3('abc'));
SELECT blake3(CAST(-9223372036854775808 AS VARCHAR)) AS `blake3(CAST(-9223372036854775808 AS VARCHAR))`;
SELECT blake3(NULL) AS `blake3(NULL)`;
SELECT blake3(CAST((CAST(NULL AS VARCHAR)) AS JSON)->'$') AS `blake3(CAST((CAST(NULL AS VARCHAR)) AS JSON)->'$')`;
SELECT blake3(CAST(NULL AS VARCHAR)) AS `blake3(CAST(NULL AS VARCHAR))` ORDER BY blake3(CAST(NULL AS VARCHAR)) DESC;
SELECT blake3(CAST(NULL AS VARCHAR)) AS `blake3(CAST(NULL AS VARCHAR))` LIMIT 0;
SELECT blake3(CAST((CAST(NULL AS DECIMAL128(38,0))) AS VARCHAR)) AS `blake3(CAST((CAST(NULL AS DECIMAL128(38,0))) AS VARCHAR))`;
SELECT blake3(CAST(NULL AS VARCHAR)) AS `blake3(CAST(NULL AS VARCHAR))`;
SELECT blake3(CAST((blake3(CAST(NULL AS VARCHAR))) AS VARCHAR)) AS `blake3(CAST((blake3(CAST(NULL AS VARCHAR))) AS VARCHAR))`;
SELECT CAST((blake3(CAST(NULL AS VARCHAR))) AS ARRAY<ARRAY<INT>>) AS `CAST((blake3(CAST(NULL AS VARCHAR))) AS ARRAY<ARRAY<INT>>)`;
SELECT blake3(blake3('hello')) AS `blake3(blake3('hello'))`;
SELECT blake3(blake3(CAST(NULL AS VARCHAR))) AS `blake3(blake3(CAST(NULL AS VARCHAR)))`;
SELECT blake3(CAST('abc' AS VARCHAR)) AS `blake3(CAST('abc' AS VARCHAR))`;
SELECT blake3(CAST(NULL AS VARCHAR)) AS `blake3(CAST(NULL AS VARCHAR))` LIMIT 2;
SELECT blake3(CAST(NULL AS VARCHAR)) AS `blake3(CAST(NULL AS VARCHAR))`;
SELECT blake3('hello') AS `blake3('hello')` GROUP BY blake3('hello');
SELECT blake3(2147483647) AS `blake3(2147483647)`;
SELECT blake3('hello') AS `blake3('hello')` GROUP BY blake3('hello');
SELECT blake3('hello') AS `blake3('hello')` GROUP BY blake3('hello');
SELECT blake3(blake3('hello')) AS `blake3(blake3('hello'))`;
SELECT blake3(0.0) AS `blake3(0.0)`;
SELECT blake3(blake3('hello')) AS `blake3(blake3('hello'))`;
SELECT blake3(NULL) AS `blake3(NULL)`;
SELECT blake3(0.0) AS `blake3(0.0)`;
SELECT blake3('hello') AS `blake3('hello')` GROUP BY blake3('hello');
SELECT blake3('hello') AS `blake3('hello')` ORDER BY blake3('hello') DESC;
SELECT blake3('hello') AS `blake3('hello')` GROUP BY blake3('hello');
SELECT blake3(TRUE) AS `blake3(TRUE)`;
SELECT blake3('hello') AS `blake3('hello')`;
SELECT blake3('hello') AS `blake3('hello')`;
SELECT blake3('hello') AS `blake3('hello')`;
SELECT blake3(0.0) AS `blake3(0.0)`;
SELECT blake3(2147483647) AS `blake3(2147483647)`;
SELECT blake3('hello') AS `blake3('hello')` ORDER BY blake3('hello') ASC;
SELECT blake3(blake3('hello')) AS `blake3(blake3('hello'))`;
SELECT blake3(repeat('x', 65536)) AS `blake3(repeat('x', 65536))`;
SELECT blake3(1) AS `blake3(1)`;
SELECT blake3(NULL) AS `blake3(NULL)`;
SELECT blake3('hello') AS `blake3('hello')`;
SELECT blake3('hello') AS `blake3('hello')` WHERE (blake3('abc')) = (blake3('abc'));
SELECT blake3(0.0) AS `blake3(0.0)`;
SELECT blake3('hello') AS `blake3('hello')`;
SELECT blake3(170141183460469231731687303715884105727) AS `blake3(170141183460469231731687303715884105727)`;
SELECT blake3('hello') AS `blake3('hello')`;
SELECT blake3(1.0E308) AS `blake3(1.0E308)`;
SELECT DISTINCT blake3('hello') AS `blake3('hello')`;
SELECT blake3('0000-00-00') AS `blake3('0000-00-00')`;
SELECT blake3('0000-00-00') AS `blake3('0000-00-00')`;
SELECT DISTINCT blake3('hello') AS `blake3('hello')`;
SELECT length(blake3('abc')) AS `length(blake3('abc'))` ORDER BY length(blake3('abc')) DESC;
SELECT length(blake3('abc')) AS `length(blake3('abc'))` ORDER BY length(blake3('abc')) DESC;
SELECT length(blake3('abc')) AS `length(blake3('abc'))` WHERE (blake3('abc')) = (blake3('abc'));
SELECT length(month('abc')) AS `length(month('abc'))`;
SELECT length(blake3(-1)) AS `length(blake3(-1))`;
SELECT length(blake3(1.0E308)) AS `length(blake3(1.0E308))`;
SELECT length(blake3(length(blake3('abc')))) AS `length(blake3(length(blake3('abc'))))`;
SELECT length(blake3('1970-01-01')) AS `length(blake3('1970-01-01'))`;
SELECT length('abc') AS `length('abc')`;
SELECT length(md5('abc')) AS `length(md5('abc'))`;
SELECT length(blake3(length(blake3('abc')))) AS `length(blake3(length(blake3('abc'))))`;
SELECT length(blake3('abc')) AS `length(blake3('abc'))`;
SELECT length(blake3('abc')) AS `length(blake3('abc'))` GROUP BY length(blake3('abc'));
SELECT length(blake3('abc')) AS `length(blake3('abc'))`;
SELECT length(blake3('9999-12-31 23:59:59')) AS `length(blake3('9999-12-31 23:59:59'))`;
SELECT length(json_query(CAST((blake3('abc')) AS JSON), '$.a')) AS `length(json_query(CAST((blake3('abc')) AS JSON), '$.a'))`;
SELECT length(length(blake3('abc'))) AS `length(length(blake3('abc')))`;
SELECT length(bitmap_count('abc')) AS `length(bitmap_count('abc'))`;
SELECT length(blake3('abc')) AS `length(blake3('abc'))`;
SELECT length(ceil('abc')) AS `length(ceil('abc'))`;
SELECT length(blake3(length(blake3('abc')))) AS `length(blake3(length(blake3('abc'))))`;
SELECT DISTINCT length(blake3('abc')) AS `length(blake3('abc'))`;
SELECT length(blake3(json_length(CAST('abc' AS JSON)))) AS `length(blake3(json_length(CAST('abc' AS JSON))))`;
SELECT length(blake3('abc')) AS `length(blake3('abc'))` GROUP BY length(blake3('abc'));
SELECT length(blake3('abc')) AS `length(blake3('abc'))`;
SELECT length(abs('abc')) AS `length(abs('abc'))`;
SELECT length(blake3(blake3('StarRocks'))) AS `length(blake3(blake3('StarRocks')))`;
SELECT length(blake3('abc')) AS `length(blake3('abc'))` GROUP BY length(blake3('abc'));
SELECT length(blake3(TRUE)) AS `length(blake3(TRUE))`;
SELECT length(blake3('0')) AS `length(blake3('0'))`;
SELECT length(sign('abc')) AS `length(sign('abc'))`;
SELECT (blake3('abc')) = (blake3('abc')) AS `(blake3('abc')) = (blake3('abc'))` GROUP BY (blake3('abc')) = (blake3('abc'));
SELECT (blake3(-2147483648)) = (blake3('abc')) AS `(blake3(-2147483648)) = (blake3('abc'))`;
SELECT (blake3('abc')) = (blake3(blake3('abc'))) AS `(blake3('abc')) = (blake3(blake3('abc')))`;
SELECT (ln('abc')) = (blake3('abc')) AS `(ln('abc')) = (blake3('abc'))`;
SELECT DISTINCT (blake3('abc')) = (blake3('abc')) AS `(blake3('abc')) = (blake3('abc'))`;
SELECT (blake3('abc')) = (blake3('abc')) AS `(blake3('abc')) = (blake3('abc'))` GROUP BY (blake3('abc')) = (blake3('abc'));
SELECT (blake3('abc')) = (blake3('abc')) AS `(blake3('abc')) = (blake3('abc'))` GROUP BY (blake3('abc')) = (blake3('abc'));
SELECT (blake3('abc')) = (blake3('abc')) AS `(blake3('abc')) = (blake3('abc'))` WHERE (blake3('abc')) = (blake3('abc'));
SELECT (blake3('abc')) = (blake3('abc')) AS `(blake3('abc')) = (blake3('abc'))` GROUP BY (blake3('abc')) = (blake3('abc'));
SELECT (blake3('abc')) = (blake3('abc')) AS `(blake3('abc')) = (blake3('abc'))` GROUP BY (blake3('abc')) = (blake3('abc'));
SELECT (blake3('abc')) = (blake3('abc')) AS `(blake3('abc')) = (blake3('abc'))` GROUP BY (blake3('abc')) = (blake3('abc'));
SELECT (blake3('StarRocks')) = (blake3('abc')) AS `(blake3('StarRocks')) = (blake3('abc'))`;
SELECT (blake3('abc')) = (blake3(-1)) AS `(blake3('abc')) = (blake3(-1))`;
SELECT (blake3('abc')) = (blake3('abc')) AS `(blake3('abc')) = (blake3('abc'))`;
SELECT (blake3('abc')) = (blake3('abc')) AS `(blake3('abc')) = (blake3('abc'))`;
SELECT (blake3('1970-01-01')) = (blake3('abc')) AS `(blake3('1970-01-01')) = (blake3('abc'))`;
SELECT (blake3('abc')) = (blake3('0000-00-00')) AS `(blake3('abc')) = (blake3('0000-00-00'))`;
SELECT (blake3(-9223372036854775808)) = (blake3('abc')) AS `(blake3(-9223372036854775808)) = (blake3('abc'))`;
SELECT DISTINCT (blake3('abc')) = (blake3('abc')) AS `(blake3('abc')) = (blake3('abc'))`;
SELECT 'abc' = (blake3('abc')) AS `'abc' = (blake3('abc'))`;
SELECT (blake3('abc')) = (blake3('abc')) AS `(blake3('abc')) = (blake3('abc'))` ORDER BY (blake3('abc')) = (blake3('abc')) ASC;
SELECT (blake3('abc')) = (blake3(CAST('abc' AS BOOLEAN))) AS `(blake3('abc')) = (blake3(CAST('abc' AS BOOLEAN)))`;
SELECT (blake3('abc')) = (blake3(json_query(CAST('abc' AS JSON), '$.a'))) AS `(blake3('abc')) = (blake3(json_query(CAST('abc' AS JSON), '$.a')))`;
SELECT (blake3('abc')) = (blake3('abc')) AS `(blake3('abc')) = (blake3('abc'))`;
SELECT (blake3('abc')) = (blake3('abc')) AS `(blake3('abc')) = (blake3('abc'))` LIMIT 1, 100;
SELECT (blake3(blake3('abc'))) = (blake3('abc')) AS `(blake3(blake3('abc'))) = (blake3('abc'))`;
SELECT 'abc' = (blake3('abc')) AS `'abc' = (blake3('abc'))`;
SELECT (blake3('abc')) = (blake3(TRUE)) AS `(blake3('abc')) = (blake3(TRUE))`;
SELECT (blake3('abc')) = (blake3('abc')) AS `(blake3('abc')) = (blake3('abc'))`;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(`srfuzz_mut_414`.`t1`.`v`) AS `blake3(v)` FROM `srfuzz_mut_414`.`t1` WHERE (blake3('abc')) = (blake3('abc')) ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, max(blake3(`srfuzz_mut_414`.`t1`.`v`)) OVER (PARTITION BY `srfuzz_mut_414`.`t1`.`id` ) AS `max(blake3(v)) OVER (PARTITION BY id )` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_414`.`t1`.`id`, `srfuzz_mut_414`.`t1`.`v` FROM `srfuzz_mut_414`.`t1`) SELECT `t1`.`id`, blake3(`t1`.`v`) AS `blake3(v)` FROM `srfuzz_n1` AS t1 ORDER BY `t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(`srfuzz_mut_414`.`t1`.`v`) AS `blake3(srfuzz_mut_414.t1.v)` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT DISTINCT `srfuzz_mut_414`.`t1`.`id`, blake3(`srfuzz_mut_414`.`t1`.`v`) AS `blake3(v)` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `t1`.`id`, blake3(`t1`.`v`) AS `blake3(v)` FROM (SELECT `srfuzz_mut_414`.`t1`.`id`, `srfuzz_mut_414`.`t1`.`v` FROM `srfuzz_mut_414`.`t1` UNION SELECT `srfuzz_mut_414`.`t1`.`id`, `srfuzz_mut_414`.`t1`.`v` FROM `srfuzz_mut_414`.`t1`) `t1` ORDER BY `t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(`srfuzz_mut_414`.`t1`.`v`) AS `blake3(v)` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC  LIMIT 7, 1;
SELECT `t1`.`id`, blake3(`t1`.`v`) AS `blake3(v)` FROM (SELECT `srfuzz_mut_414`.`t1`.`id`, `srfuzz_mut_414`.`t1`.`v` FROM `srfuzz_mut_414`.`t1` INTERSECT SELECT `srfuzz_mut_414`.`t1`.`id`, `srfuzz_mut_414`.`t1`.`v` FROM `srfuzz_mut_414`.`t1`) `t1` ORDER BY `t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, CAST((blake3(`srfuzz_mut_414`.`t1`.`v`)) AS INT) AS `CAST((blake3(v)) AS INT)` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(`srfuzz_mut_414`.`t1`.`id`) AS `blake3(id)` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `t1`.`id`, blake3(`t1`.`v`) AS `blake3(v)` FROM (SELECT `srfuzz_mut_414`.`t1`.`id`, `srfuzz_mut_414`.`t1`.`v` FROM `srfuzz_mut_414`.`t1` UNION ALL SELECT `srfuzz_mut_414`.`t1`.`id`, `srfuzz_mut_414`.`t1`.`v` FROM `srfuzz_mut_414`.`t1`) `t1` ORDER BY `t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(`srfuzz_mut_414`.`t1`.`id`) AS `blake3(srfuzz_mut_414.t1.id)` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(length(blake3(`srfuzz_mut_414`.`t1`.`v`))) AS `blake3(length(blake3(srfuzz_mut_414.t1.v)))` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(`srfuzz_mut_414`.`t1`.`id`) AS `blake3(id)` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(blake3(`srfuzz_mut_414`.`t1`.`v`)) AS `blake3(blake3(srfuzz_mut_414.t1.v))` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(`srfuzz_mut_414`.`t1`.`id`) AS `blake3(srfuzz_mut_414.t1.id)` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT CAST(`srfuzz_mut_414`.`t1`.`id` AS JSON)->'$' AS `CAST(id AS JSON)->'$'`, blake3(`srfuzz_mut_414`.`t1`.`v`) AS `blake3(v)` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT DISTINCT `srfuzz_mut_414`.`t1`.`id`, blake3(`srfuzz_mut_414`.`t1`.`v`) AS `blake3(v)` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(`srfuzz_mut_414`.`t1`.`id`) AS `blake3(id)` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(`srfuzz_mut_414`.`t1`.`v`) AS `blake3(v)` FROM `srfuzz_mut_414`.`t1`;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(length(blake3(`srfuzz_mut_414`.`t1`.`v`))) AS `blake3(length(blake3(srfuzz_mut_414.t1.v)))` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(blake3(`srfuzz_mut_414`.`t1`.`v`)) AS `blake3(blake3(srfuzz_mut_414.t1.v))` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `t1`.`id`, blake3(`t1`.`v`) AS `blake3(v)` FROM (SELECT `srfuzz_mut_414`.`t1`.`id`, `srfuzz_mut_414`.`t1`.`v` FROM `srfuzz_mut_414`.`t1` EXCEPT SELECT `srfuzz_mut_414`.`t1`.`id`, `srfuzz_mut_414`.`t1`.`v` FROM `srfuzz_mut_414`.`t1`) `t1` ORDER BY `t1`.`id` ASC;
SELECT `t1`.`id`, blake3(`t1`.`v`) AS `blake3(v)` FROM (SELECT `srfuzz_mut_414`.`t1`.`id`, `srfuzz_mut_414`.`t1`.`v` FROM `srfuzz_mut_414`.`t1`) `t1` ORDER BY `t1`.`id` ASC;
SELECT sum(`srfuzz_mut_414`.`t1`.`id`) OVER () AS `sum(id) OVER ()`, blake3(`srfuzz_mut_414`.`t1`.`v`) AS `blake3(v)` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(`srfuzz_mut_414`.`t1`.`v`) AS `blake3(v)` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(`srfuzz_mut_414`.`t1`.`id`) AS `blake3(id)` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(`srfuzz_mut_414`.`t1`.`id`) AS `blake3(id)` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(`srfuzz_mut_414`.`t1`.`id`) AS `blake3(srfuzz_mut_414.t1.id)` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(`srfuzz_mut_414`.`t1`.`id`) AS `blake3(srfuzz_mut_414.t1.id)` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(`srfuzz_mut_414`.`t1`.`v`) AS `blake3(v)` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(`srfuzz_mut_414`.`t1`.`v`) AS `blake3(v)` FROM `srfuzz_mut_414`.`t1` GROUP BY `srfuzz_mut_414`.`t1`.`id`, blake3(`srfuzz_mut_414`.`t1`.`v`) ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(`srfuzz_mut_414`.`t1`.`v`) AS `blake3(v)` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(`srfuzz_mut_414`.`t1`.`v`) AS `blake3(v)` FROM `srfuzz_mut_414`.`t1`;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(`srfuzz_mut_414`.`t1`.`id`) AS `blake3(id)` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(`srfuzz_mut_414`.`t1`.`id`) AS `blake3(id)` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, blake3(`srfuzz_mut_414`.`t1`.`id`) AS `blake3(id)` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT CAST(`srfuzz_mut_414`.`t1`.`id` AS JSON)->'$.a' AS `CAST(id AS JSON)->'$.a'`, blake3(`srfuzz_mut_414`.`t1`.`v`) AS `blake3(v)` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `t1`.`id`, blake3(`t1`.`v`) AS `blake3(v)` FROM (SELECT `srfuzz_mut_414`.`t1`.`id`, `srfuzz_mut_414`.`t1`.`v` FROM `srfuzz_mut_414`.`t1` UNION SELECT `srfuzz_mut_414`.`t1`.`id`, `srfuzz_mut_414`.`t1`.`v` FROM `srfuzz_mut_414`.`t1`) `t1` ORDER BY `t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, length(length(blake3(`srfuzz_mut_414`.`t1`.`v`))) AS `length(length(blake3(srfuzz_mut_414.t1.v)))` FROM `srfuzz_mut_414`.`t1` WHERE `srfuzz_mut_414`.`t1`.`v` IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_414`.`t1`.`id`, `srfuzz_mut_414`.`t1`.`v` FROM `srfuzz_mut_414`.`t1`) SELECT `t1`.`id`, length(blake3(`t1`.`v`)) AS `length(blake3(v))` FROM `srfuzz_n1` AS t1 WHERE `t1`.`v` IS NOT NULL ORDER BY `t1`.`id` ASC;
SELECT count(`srfuzz_mut_414`.`t1`.`id`) OVER (PARTITION BY length(blake3(`srfuzz_mut_414`.`t1`.`v`)) ) AS `count(id) OVER (PARTITION BY length(blake3(v)) )`, length(blake3(`srfuzz_mut_414`.`t1`.`v`)) AS `length(blake3(v))` FROM `srfuzz_mut_414`.`t1` WHERE `srfuzz_mut_414`.`t1`.`v` IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, length(blake3(`srfuzz_mut_414`.`t1`.`v`)) AS `length(blake3(v))` FROM `srfuzz_mut_414`.`t1` WHERE `srfuzz_mut_414`.`t1`.`v` IS NOT NULL GROUP BY `srfuzz_mut_414`.`t1`.`id`, length(blake3(`srfuzz_mut_414`.`t1`.`v`)) ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, rank() OVER (ORDER BY length(blake3(`srfuzz_mut_414`.`t1`.`v`)) ASC ) AS `rank() OVER (ORDER BY length(blake3(v)) ASC )` FROM `srfuzz_mut_414`.`t1` WHERE `srfuzz_mut_414`.`t1`.`v` IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, length(blake3(`srfuzz_mut_414`.`t1`.`v`)) AS `length(blake3(v))` FROM `srfuzz_mut_414`.`t1` WHERE `srfuzz_mut_414`.`t1`.`id` IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `t1`.`id`, length(blake3(`t1`.`v`)) AS `length(blake3(v))` FROM (SELECT `srfuzz_mut_414`.`t1`.`id`, `srfuzz_mut_414`.`t1`.`v` FROM `srfuzz_mut_414`.`t1` EXCEPT SELECT `srfuzz_mut_414`.`t1`.`id`, `srfuzz_mut_414`.`t1`.`v` FROM `srfuzz_mut_414`.`t1`) `t1` WHERE `t1`.`v` IS NOT NULL ORDER BY `t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, length(blake3(`srfuzz_mut_414`.`t1`.`v`)) AS `length(blake3(v))` FROM `srfuzz_mut_414`.`t1` WHERE `srfuzz_mut_414`.`t1`.`v` IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, length(blake3(`srfuzz_mut_414`.`t1`.`id`)) AS `length(blake3(id))` FROM `srfuzz_mut_414`.`t1` WHERE `srfuzz_mut_414`.`t1`.`v` IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `t1`.`id`, length(blake3(`t1`.`v`)) AS `length(blake3(v))` FROM (SELECT `srfuzz_mut_414`.`t1`.`id`, `srfuzz_mut_414`.`t1`.`v` FROM `srfuzz_mut_414`.`t1` UNION ALL SELECT `srfuzz_mut_414`.`t1`.`id`, `srfuzz_mut_414`.`t1`.`v` FROM `srfuzz_mut_414`.`t1`) `t1` WHERE `t1`.`v` IS NOT NULL ORDER BY `t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, length(blake3(`srfuzz_mut_414`.`t1`.`v`)) AS `length(blake3(v))` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, length(blake3(`srfuzz_mut_414`.`t1`.`v`)) AS `length(blake3(v))` FROM `srfuzz_mut_414`.`t1` WHERE `srfuzz_mut_414`.`t1`.`v` IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_414`.`t1`.`id`, `srfuzz_mut_414`.`t1`.`v` FROM `srfuzz_mut_414`.`t1`) SELECT `t1`.`id`, length(blake3(`t1`.`v`)) AS `length(blake3(v))` FROM `srfuzz_n1` AS t1 WHERE `t1`.`v` IS NOT NULL ORDER BY `t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, length(floor(`srfuzz_mut_414`.`t1`.`v`)) AS `length(floor(v))` FROM `srfuzz_mut_414`.`t1` WHERE `srfuzz_mut_414`.`t1`.`v` IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, length(blake3(`srfuzz_mut_414`.`t1`.`v`)) AS `length(blake3(v))` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT min(`srfuzz_mut_414`.`t1`.`id`) OVER () AS `min(id) OVER ()`, length(blake3(`srfuzz_mut_414`.`t1`.`v`)) AS `length(blake3(v))` FROM `srfuzz_mut_414`.`t1` WHERE `srfuzz_mut_414`.`t1`.`v` IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, length(blake3(`srfuzz_mut_414`.`t1`.`v`)) AS `length(blake3(v))` FROM `srfuzz_mut_414`.`t1` WHERE 'l' IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, length(get_json_string(CAST((blake3(`srfuzz_mut_414`.`t1`.`v`)) AS JSON), '$.a')) AS `length(get_json_string(CAST((blake3(v)) AS JSON), '$.a'))` FROM `srfuzz_mut_414`.`t1` WHERE `srfuzz_mut_414`.`t1`.`v` IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, length(char_length(`srfuzz_mut_414`.`t1`.`v`)) AS `length(char_length(v))` FROM `srfuzz_mut_414`.`t1` WHERE `srfuzz_mut_414`.`t1`.`v` IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_414`.`t1`.`id`, `srfuzz_mut_414`.`t1`.`v` FROM `srfuzz_mut_414`.`t1`) SELECT `t1`.`id`, length(blake3(`t1`.`v`)) AS `length(blake3(v))` FROM `srfuzz_n1` AS t1 WHERE `t1`.`v` IS NOT NULL ORDER BY `t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, length(blake3(`srfuzz_mut_414`.`t1`.`id`)) AS `length(blake3(id))` FROM `srfuzz_mut_414`.`t1` WHERE `srfuzz_mut_414`.`t1`.`v` IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, rank() OVER (ORDER BY length(blake3(`srfuzz_mut_414`.`t1`.`v`)) ASC ) AS `rank() OVER (ORDER BY length(blake3(v)) ASC )` FROM `srfuzz_mut_414`.`t1` WHERE `srfuzz_mut_414`.`t1`.`v` IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT DISTINCT `srfuzz_mut_414`.`t1`.`id`, length(blake3(`srfuzz_mut_414`.`t1`.`v`)) AS `length(blake3(v))` FROM `srfuzz_mut_414`.`t1` WHERE `srfuzz_mut_414`.`t1`.`v` IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, length(blake3(`srfuzz_mut_414`.`t1`.`id`)) AS `length(blake3(srfuzz_mut_414.t1.id))` FROM `srfuzz_mut_414`.`t1` WHERE `srfuzz_mut_414`.`t1`.`v` IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, length(lower(`srfuzz_mut_414`.`t1`.`v`)) AS `length(lower(v))` FROM `srfuzz_mut_414`.`t1` WHERE `srfuzz_mut_414`.`t1`.`v` IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, length(blake3(`srfuzz_mut_414`.`t1`.`v`)) AS `length(blake3(v))` FROM `srfuzz_mut_414`.`t1` ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, length(blake3(`srfuzz_mut_414`.`t1`.`id`)) AS `length(blake3(id))` FROM `srfuzz_mut_414`.`t1` WHERE `srfuzz_mut_414`.`t1`.`v` IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, length(blake3(`srfuzz_mut_414`.`t1`.`v`)) AS `length(blake3(v))` FROM `srfuzz_mut_414`.`t1` WHERE (blake3('l')) IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, length(blake3(`srfuzz_mut_414`.`t1`.`id`)) AS `length(blake3(srfuzz_mut_414.t1.id))` FROM `srfuzz_mut_414`.`t1` WHERE `srfuzz_mut_414`.`t1`.`v` IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, count(length(blake3(`srfuzz_mut_414`.`t1`.`v`))) OVER (PARTITION BY `srfuzz_mut_414`.`t1`.`id` ) AS `count(length(blake3(v))) OVER (PARTITION BY id )` FROM `srfuzz_mut_414`.`t1` WHERE `srfuzz_mut_414`.`t1`.`v` IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, length(blake3(`srfuzz_mut_414`.`t1`.`v`)) AS `length(blake3(v))` FROM `srfuzz_mut_414`.`t1` WHERE (length(blake3(`srfuzz_mut_414`.`t1`.`v`))) IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, length(blake3(`srfuzz_mut_414`.`t1`.`v`)) AS `length(blake3(srfuzz_mut_414.t1.v))` FROM `srfuzz_mut_414`.`t1` WHERE `srfuzz_mut_414`.`t1`.`v` IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, length(hex(`srfuzz_mut_414`.`t1`.`v`)) AS `length(hex(v))` FROM `srfuzz_mut_414`.`t1` WHERE `srfuzz_mut_414`.`t1`.`v` IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, length(blake3(length(blake3(`srfuzz_mut_414`.`t1`.`v`)))) AS `length(blake3(length(blake3(srfuzz_mut_414.t1.v))))` FROM `srfuzz_mut_414`.`t1` WHERE `srfuzz_mut_414`.`t1`.`v` IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;
SELECT `srfuzz_mut_414`.`t1`.`id`, length(blake3(`srfuzz_mut_414`.`t1`.`id`)) AS `length(blake3(srfuzz_mut_414.t1.id))` FROM `srfuzz_mut_414`.`t1` WHERE `srfuzz_mut_414`.`t1`.`v` IS NOT NULL ORDER BY `srfuzz_mut_414`.`t1`.`id` ASC;