SELECT is_json_scalar(parse_json('123')) AS `test_number`;
SELECT is_json_scalar(parse_json('123.456')) AS `test_float`;
SELECT is_json_scalar(parse_json('-999')) AS `test_negative`;
SELECT is_json_scalar(parse_json('"hello"')) AS `test_string`;
SELECT is_json_scalar(parse_json('""')) AS `test_empty_string`;
SELECT is_json_scalar(parse_json('true')) AS `test_true`;
SELECT is_json_scalar(parse_json('false')) AS `test_false`;
SELECT is_json_scalar(json_query(parse_json('{"a": null}'), '$.a')) AS `test_json_null`;
SELECT is_json_scalar(parse_json('{}')) AS `test_empty_object`;
SELECT is_json_scalar(parse_json('{"user": {"name": "Bob", "age": 30}}')) AS `test_nested_object`;
SELECT is_json_scalar(parse_json('[[1, 2], [3, 4]]')) AS `test_nested_array`;
SELECT is_json_scalar(NULL) AS `test_sql_null`;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC;
SELECT is_json_scalar(parse_json('9223372036854775807')) AS `test_large_number`;
SELECT is_json_scalar(parse_json('-9223372036854775808')) AS `test_small_number`;
SELECT is_json_scalar(parse_json(repeat('a', 1000))) AS `test_long_string`;
SELECT is_json_scalar(parse_json('"\\n\\t\\r"')) AS `test_special_chars`;
SELECT is_json_scalar(parse_json('123')) AS `test_number`;
SELECT is_json_scalar(parse_json('123')) AS `test_number` LIMIT 2;
SELECT is_json_scalar(parse_json(-1.0E308)) AS `test_number`;
SELECT is_json_scalar(parse_json('123')) AS `test_number` GROUP BY is_json_scalar(parse_json('123'));
SELECT is_json_scalar(parse_json('123')) AS `test_number` GROUP BY is_json_scalar(parse_json('123'));
SELECT is_json_scalar(parse_json(parse_json('123'))) AS `test_number`;
SELECT is_json_scalar(parse_json(parse_json('123'))) AS `test_number`;
SELECT is_json_scalar(parse_json('123')) AS `test_number`;
SELECT is_json_scalar(parse_json(0.0)) AS `test_number`;
SELECT is_json_scalar(parse_json('123')) AS `test_number`;
SELECT is_json_scalar(parse_json(parse_json('123'))) AS `test_number`;
SELECT DISTINCT is_json_scalar(parse_json('123')) AS `test_number`;
SELECT is_json_scalar(parse_json('123')) AS `test_number` LIMIT 1, 2;
SELECT is_json_scalar(parse_json(parse_json('123'))) AS `test_number`;
SELECT is_json_scalar(floor('123')) AS `test_number`;
SELECT is_json_scalar(sign('123')) AS `test_number`;
SELECT is_json_scalar(parse_json(parse_json('123'))) AS `test_number`;
SELECT is_json_scalar(parse_json('123')) AS `test_number`;
SELECT DISTINCT is_json_scalar(parse_json('123')) AS `test_number`;
SELECT is_json_scalar(hex('123')) AS `test_number`;
SELECT is_json_scalar(parse_json('123')) AS `test_number`;
SELECT is_json_scalar(parse_json(FALSE)) AS `test_number`;
SELECT is_json_scalar(parse_json('123')) AS `test_number` WHERE is_json_scalar(parse_json(repeat('a', 1000)));
SELECT is_json_scalar(parse_json(CAST('123' AS JSON)->'$.a')) AS `test_number`;
SELECT is_json_scalar(year('123')) AS `test_number`;
SELECT is_json_scalar('123') AS `test_number`;
SELECT is_json_scalar(sqrt('123')) AS `test_number`;
SELECT json_query(CAST((is_json_scalar(parse_json('123'))) AS JSON), '$.a') AS `test_number`;
SELECT is_json_scalar(parse_json('123')) AS `test_number` GROUP BY is_json_scalar(parse_json('123'));
SELECT is_json_scalar(parse_json(1.0E308)) AS `test_number`;
SELECT is_json_scalar(parse_json('123')) AS `test_number` WHERE is_json_scalar(parse_json('9223372036854775807'));
SELECT is_json_scalar(parse_json(170141183460469231731687303715884105727)) AS `test_number`;
SELECT is_json_scalar(abs('123.456')) AS `test_float`;
SELECT is_json_scalar(parse_json(parse_json('123.456'))) AS `test_float`;
SELECT is_json_scalar(parse_json('123.456')) AS `test_float`;
SELECT is_json_scalar(CAST((parse_json('123.456')) AS JSON)->'$.a') AS `test_float`;
SELECT DISTINCT is_json_scalar(parse_json('123.456')) AS `test_float`;
SELECT is_json_scalar(parse_json('[[1, 2], [3, 4]]')) AS `test_float`;
SELECT is_json_scalar(parse_json('123.456')) AS `test_float` LIMIT 0;
SELECT is_json_scalar(parse_json('123.456')) AS `test_float`;
SELECT DISTINCT is_json_scalar(parse_json('123.456')) AS `test_float`;
SELECT is_json_scalar(parse_json(2147483647)) AS `test_float`;
SELECT is_json_scalar(parse_json(-9223372036854775808)) AS `test_float`;
SELECT is_json_scalar(parse_json('123.456')) AS `test_float` WHERE is_json_scalar(NULL);
SELECT is_json_scalar(parse_json('123.456')) AS `test_float` LIMIT 1;
SELECT is_json_scalar(parse_json(-9223372036854775808)) AS `test_float`;
SELECT is_json_scalar(parse_json('123.456')) AS `test_float` GROUP BY is_json_scalar(parse_json('123.456'));
SELECT is_json_scalar(parse_json(CAST('123.456' AS VARCHAR(1)))) AS `test_float`;
SELECT is_json_scalar(parse_json(0.0)) AS `test_float`;
SELECT is_json_scalar(lower('123.456')) AS `test_float`;
SELECT is_json_scalar(parse_json(-2147483648)) AS `test_float`;
SELECT is_json_scalar(parse_json('123.456')) AS `test_float`;
SELECT is_json_scalar(unhex('123.456')) AS `test_float`;
SELECT is_json_scalar(parse_json(FALSE)) AS `test_float`;
SELECT json_length(CAST((is_json_scalar(parse_json('123.456'))) AS JSON)) AS `test_float`;
SELECT is_json_scalar(parse_json('123.456')) AS `test_float` ORDER BY is_json_scalar(parse_json('123.456')) DESC;
SELECT DISTINCT is_json_scalar(parse_json('123.456')) AS `test_float`;
SELECT is_json_scalar(parse_json('0000-00-00')) AS `test_float`;
SELECT is_json_scalar(parse_json(repeat('x', 65536))) AS `test_float`;
SELECT is_json_scalar(parse_json('123.456')) AS `test_float` ORDER BY is_json_scalar(parse_json('123.456')) ASC;
SELECT is_json_scalar(parse_json(1.0E308)) AS `test_float`;
SELECT is_json_scalar(parse_json(FALSE)) AS `test_float`;
SELECT count(is_json_scalar(parse_json('-999'))) OVER () AS `test_negative`;
SELECT is_json_scalar(parse_json('-999')) AS `test_negative` LIMIT 1, 1;
SELECT is_json_scalar(bitmap_count('-999')) AS `test_negative`;
SELECT is_json_scalar(unhex('-999')) AS `test_negative`;
SELECT DISTINCT is_json_scalar(parse_json('-999')) AS `test_negative`;
SELECT is_json_scalar('-999') AS `test_negative`;
SELECT is_json_scalar(bitmap_count('-999')) AS `test_negative`;
SELECT is_json_scalar(parse_json('-999')) AS `test_negative`;
SELECT is_json_scalar(parse_json('-999')) AS `test_negative`;
SELECT is_json_scalar(parse_json(parse_json(repeat('a', 1000)))) AS `test_negative`;
SELECT is_json_scalar(parse_json('-999')) AS `test_negative`;
SELECT is_json_scalar(parse_json(parse_json('-999'))) AS `test_negative`;
SELECT is_json_scalar(CAST((parse_json('-999')) AS JSON)->'$') AS `test_negative`;
SELECT is_json_scalar(parse_json('-999')) AS `test_negative` LIMIT 7, 100;
SELECT is_json_scalar(hll_cardinality('-999')) AS `test_negative`;
SELECT CAST((is_json_scalar(parse_json('-999'))) AS JSON)->'k' AS `test_negative`;
SELECT is_json_scalar(parse_json(get_json_string(CAST('-999' AS JSON), '$.a'))) AS `test_negative`;
SELECT is_json_scalar(parse_json(NULL)) AS `test_negative`;
SELECT is_json_scalar(parse_json(parse_json('-999'))) AS `test_negative`;
SELECT is_json_scalar(parse_json('-999')) AS `test_negative` ORDER BY is_json_scalar(parse_json('-999')) DESC;
SELECT is_json_scalar('-999') AS `test_negative`;
SELECT is_json_scalar(parse_json(parse_json('-999'))) AS `test_negative`;
SELECT is_json_scalar(sqrt('-999')) AS `test_negative`;
SELECT is_json_scalar('-999') AS `test_negative`;
SELECT is_json_scalar(parse_json('-999')) AS `test_negative` ORDER BY is_json_scalar(parse_json('-999')) ASC;
SELECT is_json_scalar(parse_json('0000-00-00')) AS `test_negative`;
SELECT is_json_scalar('-999') AS `test_negative`;
SELECT is_json_scalar(char_length('-999')) AS `test_negative`;
SELECT is_json_scalar(parse_json(parse_json('-999'))) AS `test_negative`;
SELECT is_json_scalar('-999') AS `test_negative`;
SELECT is_json_scalar(parse_json('-999')) AS `test_negative` WHERE is_json_scalar(json_query(parse_json('{"a": null}'), '$.a'));
SELECT is_json_scalar(parse_json('%')) AS `test_string`;
SELECT is_json_scalar(parse_json(parse_json('"hello"'))) AS `test_string`;
SELECT DISTINCT is_json_scalar(parse_json('"hello"')) AS `test_string`;
SELECT is_json_scalar(parse_json(json_query(CAST('"hello"' AS JSON), '$.a'))) AS `test_string`;
SELECT CAST((is_json_scalar(parse_json('"hello"'))) AS ARRAY<JSON>) AS `test_string`;
SELECT CAST((is_json_scalar(parse_json('"hello"'))) AS JSON)->'$' AS `test_string`;
SELECT is_json_scalar(char_length('"hello"')) AS `test_string`;
SELECT is_json_scalar(md5('"hello"')) AS `test_string`;
SELECT is_json_scalar(ln('"hello"')) AS `test_string`;
SELECT is_json_scalar(parse_json('"hello"')) AS `test_string` WHERE is_json_scalar(parse_json('123.456'));
SELECT is_json_scalar(parse_json('')) AS `test_string`;
SELECT is_json_scalar(json_query(CAST((parse_json('"hello"')) AS JSON), '$.a')) AS `test_string`;
SELECT is_json_scalar(parse_json(CAST(NULL AS JSON))) AS `test_string`;
SELECT is_json_scalar(parse_json(parse_json('"hello"'))) AS `test_string`;
SELECT is_json_scalar(parse_json('"hello"')) AS `test_string`;
SELECT is_json_scalar(parse_json('"hello"')) AS `test_string` ORDER BY is_json_scalar(parse_json('"hello"')) ASC NULLS LAST;
SELECT is_json_scalar(parse_json('"hello"')) AS `test_string` ORDER BY is_json_scalar(parse_json('"hello"')) ASC;
SELECT is_json_scalar(parse_json(parse_json('123.456'))) AS `test_string`;
SELECT is_json_scalar(parse_json(parse_json('"hello"'))) AS `test_string`;
SELECT is_json_scalar(parse_json('\\')) AS `test_string`;
SELECT is_json_scalar(ln('"hello"')) AS `test_string`;
SELECT is_json_scalar(parse_json('"hello"')) AS `test_string` ORDER BY is_json_scalar(parse_json('"hello"')) ASC;
SELECT is_json_scalar(parse_json(json_length(CAST('"hello"' AS JSON)))) AS `test_string`;
SELECT is_json_scalar(parse_json(parse_json('true'))) AS `test_string`;
SELECT is_json_scalar(parse_json('"hello"')) AS `test_string` GROUP BY is_json_scalar(parse_json('"hello"'));
SELECT is_json_scalar('"hello"') AS `test_string`;
SELECT is_json_scalar(parse_json(CAST('"hello"' AS JSON)->'k')) AS `test_string`;
SELECT is_json_scalar(length('"hello"')) AS `test_string`;
SELECT is_json_scalar(parse_json('"hello"')) AS `test_string`;
SELECT DISTINCT is_json_scalar(parse_json('"hello"')) AS `test_string`;
SELECT DISTINCT is_json_scalar(parse_json('"hello"')) AS `test_string`;
SELECT is_json_scalar(lower('"hello"')) AS `test_string`;
SELECT is_json_scalar(length('"hello"')) AS `test_string`;
SELECT is_json_scalar(ceil('"hello"')) AS `test_string`;
SELECT DISTINCT is_json_scalar(parse_json('""')) AS `test_empty_string`;
SELECT is_json_scalar(parse_json('""')) AS `test_empty_string` WHERE is_json_scalar(NULL);
SELECT is_json_scalar(parse_json(parse_json('""'))) AS `test_empty_string`;
SELECT is_json_scalar(hex('""')) AS `test_empty_string`;
SELECT is_json_scalar(char_length('""')) AS `test_empty_string`;
SELECT is_json_scalar(parse_json('""')) AS `test_empty_string` LIMIT 5;
SELECT is_json_scalar(parse_json(parse_json('""'))) AS `test_empty_string`;
SELECT is_json_scalar(parse_json('""')) AS `test_empty_string`;
SELECT is_json_scalar(md5('""')) AS `test_empty_string`;
SELECT is_json_scalar(parse_json('""')) AS `test_empty_string` GROUP BY is_json_scalar(parse_json('""'));
SELECT sum(is_json_scalar(parse_json('""'))) OVER () AS `test_empty_string`;
SELECT is_json_scalar(year('""')) AS `test_empty_string`;
SELECT is_json_scalar(parse_json('""')) AS `test_empty_string`;
SELECT is_json_scalar(parse_json('""')) AS `test_empty_string` WHERE is_json_scalar(parse_json('{"user": {"name": "Bob", "age": 30}}'));
SELECT is_json_scalar(md5('""')) AS `test_empty_string`;
SELECT is_json_scalar(unhex('""')) AS `test_empty_string`;
SELECT is_json_scalar(parse_json(1.0E308)) AS `test_empty_string`;
SELECT DISTINCT is_json_scalar(parse_json('""')) AS `test_empty_string`;
SELECT is_json_scalar(parse_json('""')) AS `test_empty_string` ORDER BY is_json_scalar(parse_json('""')) DESC;
SELECT is_json_scalar('""') AS `test_empty_string`;
SELECT is_json_scalar(parse_json('""')) AS `test_empty_string`;
SELECT is_json_scalar(parse_json('""')) AS `test_empty_string`;
SELECT is_json_scalar(month('""')) AS `test_empty_string`;
SELECT is_json_scalar(parse_json(parse_json('""'))) AS `test_empty_string`;
SELECT is_json_scalar('""') AS `test_empty_string`;
SELECT is_json_scalar(parse_json(parse_json('""'))) AS `test_empty_string`;
SELECT sum(is_json_scalar(parse_json('""'))) OVER () AS `test_empty_string`;
SELECT is_json_scalar(parse_json('""')) AS `test_empty_string` ORDER BY is_json_scalar(parse_json('""')) DESC;
SELECT is_json_scalar(parse_json('""')) AS `test_empty_string` WHERE is_json_scalar(parse_json('[[1, 2], [3, 4]]'));
SELECT is_json_scalar('""') AS `test_empty_string`;
SELECT is_json_scalar(hex('""')) AS `test_empty_string`;
SELECT is_json_scalar(parse_json('""')) AS `test_empty_string` LIMIT 7, 5;
SELECT is_json_scalar(parse_json('""')) AS `test_empty_string` WHERE is_json_scalar(parse_json('[[1, 2], [3, 4]]'));
SELECT is_json_scalar('true') AS `test_true`;
SELECT is_json_scalar(parse_json('true')) AS `test_true` GROUP BY is_json_scalar(parse_json('true'));
SELECT is_json_scalar(parse_json(parse_json('true'))) AS `test_true`;
SELECT is_json_scalar(parse_json(0.0)) AS `test_true`;
SELECT is_json_scalar(parse_json(-1.0E308)) AS `test_true`;
SELECT is_json_scalar(md5('true')) AS `test_true`;
SELECT is_json_scalar(parse_json(parse_json('{"a": null}'))) AS `test_true`;
SELECT DISTINCT is_json_scalar(parse_json('true')) AS `test_true`;
SELECT is_json_scalar(parse_json(parse_json('true'))) AS `test_true`;
SELECT is_json_scalar(parse_json(2147483647)) AS `test_true`;
SELECT CAST((is_json_scalar(parse_json('true'))) AS MAP<VARCHAR(16),struct<`a` int(11)>>) AS `test_true`;
SELECT is_json_scalar('[[1, 2], [3, 4]]') AS `test_true`;
SELECT is_json_scalar(parse_json(CAST((CAST('true' AS VARCHAR(65533))) AS TINYINT))) AS `test_true`;
SELECT is_json_scalar('true') AS `test_true`;
SELECT is_json_scalar(parse_json('%')) AS `test_true`;
SELECT is_json_scalar(month('true')) AS `test_true`;
SELECT json_length(CAST((is_json_scalar(parse_json('true'))) AS JSON)) AS `test_true`;
SELECT is_json_scalar(floor('true')) AS `test_true`;
SELECT is_json_scalar(abs('true')) AS `test_true`;
SELECT is_json_scalar(CAST((CAST((CAST((parse_json('true')) AS DECIMAL128(38,0))) AS BIGINT)) AS BOOLEAN)) AS `test_true`;
SELECT is_json_scalar(md5('true')) AS `test_true`;
SELECT is_json_scalar(parse_json(TRUE)) AS `test_true`;
SELECT is_json_scalar(parse_json(parse_json('true'))) AS `test_true`;
SELECT is_json_scalar(sign('true')) AS `test_true`;
SELECT is_json_scalar(sign('true')) AS `test_true`;
SELECT is_json_scalar(bitmap_count('true')) AS `test_true`;
SELECT is_json_scalar(month('true')) AS `test_true`;
SELECT is_json_scalar(parse_json('true')) AS `test_true`;
SELECT is_json_scalar(parse_json(parse_json('true'))) AS `test_true`;
SELECT is_json_scalar(parse_json(parse_json('true'))) AS `test_true`;
SELECT is_json_scalar(upper('true')) AS `test_true`;
SELECT is_json_scalar(ln('true')) AS `test_true`;
SELECT is_json_scalar(parse_json('true')) AS `test_true` ORDER BY is_json_scalar(parse_json('true')) ASC NULLS LAST;
SELECT is_json_scalar(parse_json(NULL)) AS `test_true`;
SELECT is_json_scalar(sqrt('true')) AS `test_true`;
SELECT is_json_scalar(parse_json('false')) AS `test_false` LIMIT 1, 5;
SELECT is_json_scalar(parse_json('false')) AS `test_false` GROUP BY is_json_scalar(parse_json('false'));
SELECT is_json_scalar(month('false')) AS `test_false`;
SELECT is_json_scalar(parse_json('%')) AS `test_false`;
SELECT is_json_scalar(ln('false')) AS `test_false`;
SELECT is_json_scalar(parse_json('false')) AS `test_false` LIMIT 5;
SELECT is_json_scalar(bitmap_count('false')) AS `test_false`;
SELECT is_json_scalar(parse_json(parse_json('false'))) AS `test_false`;
SELECT is_json_scalar(parse_json('{"a": null}')) AS `test_false`;
SELECT is_json_scalar(parse_json('a')) AS `test_false`;
SELECT is_json_scalar(parse_json('false')) AS `test_false` WHERE is_json_scalar(parse_json('false'));
SELECT is_json_scalar(parse_json(170141183460469231731687303715884105727)) AS `test_false`;
SELECT is_json_scalar(parse_json(parse_json('false'))) AS `test_false`;
SELECT DISTINCT is_json_scalar(parse_json('false')) AS `test_false`;
SELECT is_json_scalar(parse_json(repeat('a', 1000))) AS `test_false`;
SELECT is_json_scalar(parse_json('false')) AS `test_false`;
SELECT is_json_scalar('false') AS `test_false`;
SELECT is_json_scalar(parse_json(parse_json('false'))) AS `test_false`;
SELECT is_json_scalar(parse_json(-2147483648)) AS `test_false`;
SELECT is_json_scalar(parse_json('false')) AS `test_false` ORDER BY is_json_scalar(parse_json('false')) DESC;
SELECT is_json_scalar(parse_json(2147483647)) AS `test_false`;
SELECT is_json_scalar(parse_json('false')) AS `test_false` WHERE is_json_scalar(NULL);
SELECT is_json_scalar(parse_json(parse_json('false'))) AS `test_false`;
SELECT is_json_scalar(parse_json('false')) AS `test_false` ORDER BY is_json_scalar(parse_json('false')) ASC NULLS LAST;
SELECT is_json_scalar(parse_json('false')) AS `test_false` GROUP BY is_json_scalar(parse_json('false'));
SELECT is_json_scalar('false') AS `test_false`;
SELECT is_json_scalar(parse_json(parse_json('false'))) AS `test_false`;
SELECT is_json_scalar(floor('false')) AS `test_false`;
SELECT is_json_scalar(hll_cardinality('false')) AS `test_false`;
SELECT DISTINCT is_json_scalar(parse_json('false')) AS `test_false`;
SELECT is_json_scalar(hll_cardinality('false')) AS `test_false`;
SELECT is_json_scalar(parse_json(CAST('false' AS DOUBLE))) AS `test_false`;
SELECT DISTINCT is_json_scalar(parse_json('false')) AS `test_false`;
SELECT is_json_scalar(json_query(parse_json(FALSE), '$.a')) AS `test_json_null`;
SELECT is_json_scalar(json_query(parse_json('{"a": null}'), '$.a')) AS `test_json_null`;
SELECT CAST((is_json_scalar(json_query(parse_json('{"a": null}'), '$.a'))) AS CHAR(1)) AS `test_json_null`;
SELECT is_json_scalar(json_query(parse_json('{"a": null}'), parse_json('{"a": null}'))) AS `test_json_null`;
SELECT is_json_scalar(json_query(ceil('{"a": null}'), '$.a')) AS `test_json_null`;
SELECT is_json_scalar(json_query(parse_json(CAST('{"a": null}' AS LARGEINT)), '$.a')) AS `test_json_null`;
SELECT DISTINCT is_json_scalar(json_query(parse_json('{"a": null}'), '$.a')) AS `test_json_null`;
SELECT is_json_scalar(json_query(parse_json('{"a": null}'), '$.a')) AS `test_json_null` LIMIT 5;
SELECT is_json_scalar(json_query(year('{"a": null}'), '$.a')) AS `test_json_null`;
SELECT is_json_scalar(json_query(bitmap_count('{"a": null}'), '$.a')) AS `test_json_null`;
SELECT is_json_scalar(json_query(parse_json('a'), '$.a')) AS `test_json_null`;
SELECT is_json_scalar(json_query(sign('{"a": null}'), '$.a')) AS `test_json_null`;
SELECT is_json_scalar(json_query(parse_json(json_query(parse_json('{"a": null}'), '$.a')), '$.a')) AS `test_json_null`;
SELECT is_json_scalar(json_query(parse_json('{"a": null}'), '$.a')) AS `test_json_null` LIMIT 0;
SELECT is_json_scalar(json_query(exp('{"a": null}'), '$.a')) AS `test_json_null`;
SELECT is_json_scalar(json_query(unhex('{"a": null}'), '$.a')) AS `test_json_null`;
SELECT DISTINCT is_json_scalar(json_query(parse_json('{"a": null}'), '$.a')) AS `test_json_null`;
SELECT is_json_scalar(json_query(parse_json('{"a": null}'), TRUE)) AS `test_json_null`;
SELECT is_json_scalar(json_query(parse_json(FALSE), '$.a')) AS `test_json_null`;
SELECT is_json_scalar(json_query(parse_json('{"a": null}'), json_query(parse_json('{"a": null}'), '$.a'))) AS `test_json_null`;
SELECT is_json_scalar(json_query(parse_json(json_query(parse_json('{"a": null}'), '$.a')), '$.a')) AS `test_json_null`;
SELECT is_json_scalar(json_query(parse_json('{"a": null}'), '$.a')) AS `test_json_null` LIMIT 5;
SELECT is_json_scalar(json_query(CAST((parse_json('{"a": null}')) AS JSON)->'k', '$.a')) AS `test_json_null`;
SELECT is_json_scalar(json_query(parse_json('{"a": null}'), CAST((CAST('$.a' AS CHAR(1))) AS DECIMAL64(1,0)))) AS `test_json_null`;
SELECT is_json_scalar(json_query(parse_json('{"a": null}'), '$.a')) AS `test_json_null` ORDER BY is_json_scalar(json_query(parse_json('{"a": null}'), '$.a')) ASC;
SELECT is_json_scalar(json_query(parse_json('{"a": null}'), CAST(NULL AS JSON))) AS `test_json_null`;
SELECT is_json_scalar(json_query(parse_json(-1), '$.a')) AS `test_json_null`;
SELECT is_json_scalar(json_query(parse_json('{"a": null}'), '$.a')) AS `test_json_null` GROUP BY is_json_scalar(json_query(parse_json('{"a": null}'), '$.a'));
SELECT is_json_scalar(json_query(parse_json('{"a": null}'), -1.0E308)) AS `test_json_null`;
SELECT is_json_scalar(json_query(parse_json('{"a": null}'), '$.a')) AS `test_json_null` ORDER BY is_json_scalar(json_query(parse_json('{"a": null}'), '$.a')) ASC NULLS LAST;
SELECT is_json_scalar(json_query(parse_json(TRUE), '$.a')) AS `test_json_null`;
SELECT is_json_scalar(parse_json('{}')) AS `test_empty_object` WHERE is_json_scalar(parse_json('[[1, 2], [3, 4]]'));
SELECT is_json_scalar(parse_json(-2147483648)) AS `test_empty_object`;
SELECT is_json_scalar(parse_json('{}')) AS `test_empty_object` LIMIT 7, 5;
SELECT is_json_scalar(parse_json(0)) AS `test_empty_object`;
SELECT is_json_scalar(parse_json(parse_json('{}'))) AS `test_empty_object`;
SELECT is_json_scalar(parse_json('{}')) AS `test_empty_object` ORDER BY is_json_scalar(parse_json('{}')) ASC;
SELECT DISTINCT is_json_scalar(parse_json('{}')) AS `test_empty_object`;
SELECT is_json_scalar(parse_json('{}')) AS `test_empty_object` ORDER BY is_json_scalar(parse_json('{}')) ASC;
SELECT is_json_scalar(char_length('{}')) AS `test_empty_object`;
SELECT is_json_scalar(parse_json('{}')) AS `test_empty_object`;
SELECT is_json_scalar(parse_json('{}')) AS `test_empty_object` ORDER BY is_json_scalar(parse_json('{}')) DESC;
SELECT is_json_scalar(parse_json('{}')) AS `test_empty_object`;
SELECT is_json_scalar(parse_json('{}')) AS `test_empty_object` WHERE is_json_scalar(parse_json('false'));
SELECT is_json_scalar('{}') AS `test_empty_object`;
SELECT is_json_scalar(parse_json('{}')) AS `test_empty_object`;
SELECT is_json_scalar('{}') AS `test_empty_object`;
SELECT is_json_scalar(ln('{}')) AS `test_empty_object`;
SELECT is_json_scalar(parse_json('{}')) AS `test_empty_object` GROUP BY is_json_scalar(parse_json('{}'));
SELECT is_json_scalar('{}') AS `test_empty_object`;
SELECT DISTINCT is_json_scalar(parse_json('{}')) AS `test_empty_object`;
SELECT is_json_scalar(parse_json(-9223372036854775808)) AS `test_empty_object`;
SELECT is_json_scalar(parse_json('{}')) AS `test_empty_object` ORDER BY is_json_scalar(parse_json('{}')) ASC NULLS LAST;
SELECT is_json_scalar(parse_json(0.0)) AS `test_empty_object`;
SELECT is_json_scalar(floor('{}')) AS `test_empty_object`;
SELECT is_json_scalar(parse_json('{}')) AS `test_empty_object` LIMIT 2;
SELECT is_json_scalar(parse_json(1.0E308)) AS `test_empty_object`;
SELECT is_json_scalar(length('{}')) AS `test_empty_object`;
SELECT DISTINCT is_json_scalar(parse_json('{}')) AS `test_empty_object`;
SELECT is_json_scalar(parse_json(-1)) AS `test_empty_object`;
SELECT is_json_scalar(parse_json('\\')) AS `test_empty_object`;
SELECT is_json_scalar(parse_json(CAST(NULL AS JSON))) AS `test_empty_object`;
SELECT is_json_scalar(parse_json('{}')) AS `test_empty_object` GROUP BY is_json_scalar(parse_json('{}'));
SELECT is_json_scalar(parse_json(0)) AS `test_empty_object`;
SELECT is_json_scalar(parse_json(1)) AS `test_empty_object`;
SELECT CAST((CAST((is_json_scalar(parse_json('{}'))) AS DECIMAL128(27,9))) AS VARCHAR(65533)) AS `test_empty_object`;
SELECT is_json_scalar(parse_json('{}')) AS `test_empty_object`;
SELECT is_json_scalar(parse_json('{"user": {"name": "Bob", "age": 30}}')) AS `test_nested_object`;
SELECT is_json_scalar(parse_json('{"user": {"name": "Bob", "age": 30}}')) AS `test_nested_object`;
SELECT is_json_scalar(month('{"user": {"name": "Bob", "age": 30}}')) AS `test_nested_object`;
SELECT is_json_scalar(parse_json('-9223372036854775808')) AS `test_nested_object`;
SELECT is_json_scalar(upper('{"user": {"name": "Bob", "age": 30}}')) AS `test_nested_object`;
SELECT is_json_scalar(parse_json(parse_json('{"user": {"name": "Bob", "age": 30}}'))) AS `test_nested_object`;
SELECT is_json_scalar(abs('{"user": {"name": "Bob", "age": 30}}')) AS `test_nested_object`;
SELECT is_json_scalar(parse_json('{"user": {"name": "Bob", "age": 30}}')) AS `test_nested_object`;
SELECT is_json_scalar(parse_json('{"user": {"name": "Bob", "age": 30}}')) AS `test_nested_object`;
SELECT is_json_scalar(1000) AS `test_nested_object`;
SELECT is_json_scalar(parse_json(170141183460469231731687303715884105727)) AS `test_nested_object`;
SELECT is_json_scalar(parse_json(-9223372036854775808)) AS `test_nested_object`;
SELECT is_json_scalar(parse_json('{"user": {"name": "Bob", "age": 30}}')) AS `test_nested_object`;
SELECT is_json_scalar(unhex('{"user": {"name": "Bob", "age": 30}}')) AS `test_nested_object`;
SELECT is_json_scalar(parse_json('{"user": {"name": "Bob", "age": 30}}')) AS `test_nested_object` GROUP BY is_json_scalar(parse_json('{"user": {"name": "Bob", "age": 30}}'));
SELECT is_json_scalar(parse_json('{"user": {"name": "Bob", "age": 30}}')) AS `test_nested_object`;
SELECT is_json_scalar(parse_json('{"user": {"name": "Bob", "age": 30}}')) AS `test_nested_object` WHERE is_json_scalar(parse_json('[[1, 2], [3, 4]]'));
SELECT is_json_scalar(parse_json('{"user": {"name": "Bob", "age": 30}}')) AS `test_nested_object` GROUP BY is_json_scalar(parse_json('{"user": {"name": "Bob", "age": 30}}'));
SELECT is_json_scalar(year('{"user": {"name": "Bob", "age": 30}}')) AS `test_nested_object`;
SELECT is_json_scalar(md5('{"user": {"name": "Bob", "age": 30}}')) AS `test_nested_object`;
SELECT is_json_scalar(parse_json('{"user": {"name": "Bob", "age": 30}}')) AS `test_nested_object` ORDER BY is_json_scalar(parse_json('{"user": {"name": "Bob", "age": 30}}')) DESC;
SELECT is_json_scalar(parse_json('{"user": {"name": "Bob", "age": 30}}')) AS `test_nested_object`;
SELECT is_json_scalar(parse_json(0.0)) AS `test_nested_object`;
SELECT is_json_scalar(parse_json(parse_json('{"user": {"name": "Bob", "age": 30}}'))) AS `test_nested_object`;
SELECT is_json_scalar(parse_json('{"user": {"name": "Bob", "age": 30}}')) AS `test_nested_object` LIMIT 7, 0;
SELECT is_json_scalar(sqrt('{"user": {"name": "Bob", "age": 30}}')) AS `test_nested_object`;
SELECT is_json_scalar(parse_json(CAST(NULL AS JSON))) AS `test_nested_object`;
SELECT is_json_scalar(parse_json('123.456')) AS `test_nested_object`;
SELECT is_json_scalar(parse_json('[[1, 2], [3, 4]]')) AS `test_nested_object`;
SELECT is_json_scalar(parse_json('{"user": {"name": "Bob", "age": 30}}')) AS `test_nested_object` LIMIT 7, 100;
SELECT is_json_scalar(unhex('{"user": {"name": "Bob", "age": 30}}')) AS `test_nested_object`;
SELECT is_json_scalar(parse_json('9999-12-31 23:59:59')) AS `test_nested_array`;
SELECT is_json_scalar(parse_json('[[1, 2], [3, 4]]')) AS `test_nested_array` ORDER BY is_json_scalar(parse_json('[[1, 2], [3, 4]]')) DESC NULLS FIRST;
SELECT is_json_scalar(parse_json('[[1, 2], [3, 4]]')) AS `test_nested_array` GROUP BY is_json_scalar(parse_json('[[1, 2], [3, 4]]'));
SELECT is_json_scalar(parse_json('[[1, 2], [3, 4]]')) AS `test_nested_array` ORDER BY is_json_scalar(parse_json('[[1, 2], [3, 4]]')) DESC;
SELECT is_json_scalar(length('[[1, 2], [3, 4]]')) AS `test_nested_array`;
SELECT is_json_scalar(parse_json('[[1, 2], [3, 4]]')) AS `test_nested_array` GROUP BY is_json_scalar(parse_json('[[1, 2], [3, 4]]'));
SELECT is_json_scalar(month('[[1, 2], [3, 4]]')) AS `test_nested_array`;
SELECT is_json_scalar(md5('[[1, 2], [3, 4]]')) AS `test_nested_array`;
SELECT is_json_scalar('[[1, 2], [3, 4]]') AS `test_nested_array`;
SELECT is_json_scalar(parse_json('[[1, 2], [3, 4]]')) AS `test_nested_array` LIMIT 1, 100;
SELECT is_json_scalar(parse_json('[[1, 2], [3, 4]]')) AS `test_nested_array`;
SELECT is_json_scalar('[[1, 2], [3, 4]]') AS `test_nested_array`;
SELECT is_json_scalar(parse_json('[[1, 2], [3, 4]]')) AS `test_nested_array` LIMIT 7, 0;
SELECT is_json_scalar(sqrt('[[1, 2], [3, 4]]')) AS `test_nested_array`;
SELECT is_json_scalar(parse_json(170141183460469231731687303715884105727)) AS `test_nested_array`;
SELECT is_json_scalar(parse_json('[[1, 2], [3, 4]]')) AS `test_nested_array`;
SELECT is_json_scalar(parse_json(parse_json('[[1, 2], [3, 4]]'))) AS `test_nested_array`;
SELECT is_json_scalar(parse_json('[[1, 2], [3, 4]]')) AS `test_nested_array` GROUP BY is_json_scalar(parse_json('[[1, 2], [3, 4]]'));
SELECT is_json_scalar(parse_json(parse_json('[[1, 2], [3, 4]]'))) AS `test_nested_array`;
SELECT is_json_scalar(exp('[[1, 2], [3, 4]]')) AS `test_nested_array`;
SELECT is_json_scalar(parse_json('[[1, 2], [3, 4]]')) AS `test_nested_array`;
SELECT is_json_scalar(parse_json(CAST(NULL AS JSON))) AS `test_nested_array`;
SELECT is_json_scalar(upper('[[1, 2], [3, 4]]')) AS `test_nested_array`;
SELECT is_json_scalar(parse_json(9223372036854775807)) AS `test_nested_array`;
SELECT is_json_scalar(unhex('[[1, 2], [3, 4]]')) AS `test_nested_array`;
SELECT is_json_scalar(parse_json('[[1, 2], [3, 4]]')) AS `test_nested_array` LIMIT 100;
SELECT is_json_scalar(parse_json('[[1, 2], [3, 4]]')) AS `test_nested_array`;
SELECT is_json_scalar(parse_json('[[1, 2], [3, 4]]')) AS `test_nested_array`;
SELECT is_json_scalar(parse_json(parse_json('[[1, 2], [3, 4]]'))) AS `test_nested_array`;
SELECT is_json_scalar(parse_json('[[1, 2], [3, 4]]')) AS `test_nested_array`;
SELECT is_json_scalar(month('[[1, 2], [3, 4]]')) AS `test_nested_array`;
SELECT is_json_scalar(NULL) AS `test_sql_null`;
SELECT is_json_scalar(NULL) AS `test_sql_null` LIMIT 1;
SELECT is_json_scalar(NULL) AS `test_sql_null` WHERE is_json_scalar(parse_json(repeat('a', 1000)));
SELECT json_query(CAST((is_json_scalar(NULL)) AS JSON), '$.a') AS `test_sql_null`;
SELECT is_json_scalar(0.0) AS `test_sql_null`;
SELECT is_json_scalar('1970-01-01') AS `test_sql_null`;
SELECT is_json_scalar(NULL) AS `test_sql_null`;
SELECT is_json_scalar(NULL) AS `test_sql_null` GROUP BY is_json_scalar(NULL);
SELECT is_json_scalar(NULL) AS `test_sql_null`;
SELECT is_json_scalar(0) AS `test_sql_null`;
SELECT is_json_scalar(170141183460469231731687303715884105727) AS `test_sql_null`;
SELECT is_json_scalar(parse_json('9223372036854775807')) AS `test_sql_null`;
SELECT is_json_scalar(NULL) AS `test_sql_null`;
SELECT is_json_scalar(NULL) AS `test_sql_null`;
SELECT is_json_scalar(0) AS `test_sql_null`;
SELECT is_json_scalar(0.0) AS `test_sql_null`;
SELECT is_json_scalar(repeat('x', 65536)) AS `test_sql_null`;
SELECT is_json_scalar(NULL) AS `test_sql_null` ORDER BY is_json_scalar(NULL) ASC;
SELECT is_json_scalar(CAST(NULL AS FLOAT)) AS `test_sql_null`;
SELECT is_json_scalar(NULL) AS `test_sql_null` LIMIT 1, 2;
SELECT is_json_scalar(TRUE) AS `test_sql_null`;
SELECT is_json_scalar(NULL) AS `test_sql_null` ORDER BY is_json_scalar(NULL) DESC;
SELECT is_json_scalar(-9223372036854775808) AS `test_sql_null`;
SELECT is_json_scalar(170141183460469231731687303715884105727) AS `test_sql_null`;
SELECT is_json_scalar(NULL) AS `test_sql_null`;
SELECT is_json_scalar(NULL) AS `test_sql_null` LIMIT 5;
SELECT is_json_scalar(NULL) AS `test_sql_null` LIMIT 7, 100;
SELECT is_json_scalar(NULL) AS `test_sql_null` GROUP BY is_json_scalar(NULL);
SELECT is_json_scalar(NULL) AS `test_sql_null` ORDER BY is_json_scalar(NULL) ASC;
SELECT is_json_scalar(NULL) AS `test_sql_null` GROUP BY is_json_scalar(NULL);
SELECT is_json_scalar(NULL) AS `test_sql_null`;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, CAST(`srfuzz_mut_680`.`test_json_scalar`.`description` AS JSON)->'$.a' AS `CAST(description AS JSON)->'$.a'`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC  LIMIT 1, 0;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`id`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`description`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC  LIMIT 0;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(parse_json('"\\n\\t\\r"')) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_length(CAST((json_string(`srfuzz_mut_680`.`test_json_scalar`.`json_data`)) AS JSON)) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC;
SELECT `test_json_scalar`.`id`, `test_json_scalar`.`description`, is_json_scalar(`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`test_json_scalar`.`json_data`) AS `json_value` FROM (SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`json_data`, `srfuzz_mut_680`.`test_json_scalar`.`description` FROM `srfuzz_mut_680`.`test_json_scalar`) `test_json_scalar` ORDER BY `test_json_scalar`.`id` ASC;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`description`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`description`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC;
SELECT DISTINCT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`id`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC;
SELECT `test_json_scalar`.`id`, `test_json_scalar`.`description`, is_json_scalar(`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`test_json_scalar`.`json_data`) AS `json_value` FROM (SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`json_data`, `srfuzz_mut_680`.`test_json_scalar`.`description` FROM `srfuzz_mut_680`.`test_json_scalar`) `test_json_scalar` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  ORDER BY `test_json_scalar`.`id` ASC;
SELECT `test_json_scalar`.`id`, `test_json_scalar`.`description`, is_json_scalar(`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`test_json_scalar`.`json_data`) AS `json_value` FROM (SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`json_data`, `srfuzz_mut_680`.`test_json_scalar`.`description` FROM `srfuzz_mut_680`.`test_json_scalar` UNION SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`json_data`, `srfuzz_mut_680`.`test_json_scalar`.`description` FROM `srfuzz_mut_680`.`test_json_scalar`) `test_json_scalar` ORDER BY `test_json_scalar`.`id` ASC;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`description`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` WHERE is_json_scalar(parse_json('true')) ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`description`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC;
SELECT `test_json_scalar`.`id`, `test_json_scalar`.`description`, is_json_scalar(`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`test_json_scalar`.`json_data`) AS `json_value` FROM (SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`json_data`, `srfuzz_mut_680`.`test_json_scalar`.`description` FROM `srfuzz_mut_680`.`test_json_scalar`) `test_json_scalar` ORDER BY `test_json_scalar`.`id` ASC;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar`;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`description`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, avg(is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`)) OVER () AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` WHERE is_json_scalar(parse_json('false')) ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC;
SELECT DISTINCT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC;
SELECT `test_json_scalar`.`id`, `test_json_scalar`.`description`, is_json_scalar(`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`test_json_scalar`.`json_data`) AS `json_value` FROM (SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`json_data`, `srfuzz_mut_680`.`test_json_scalar`.`description` FROM `srfuzz_mut_680`.`test_json_scalar` UNION SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`json_data`, `srfuzz_mut_680`.`test_json_scalar`.`description` FROM `srfuzz_mut_680`.`test_json_scalar`) `test_json_scalar` ORDER BY `test_json_scalar`.`id` ASC;
SELECT `test_json_scalar`.`id`, `test_json_scalar`.`description`, is_json_scalar(`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`test_json_scalar`.`json_data`) AS `json_value` FROM (SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`json_data`, `srfuzz_mut_680`.`test_json_scalar`.`description` FROM `srfuzz_mut_680`.`test_json_scalar` INTERSECT SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`json_data`, `srfuzz_mut_680`.`test_json_scalar`.`description` FROM `srfuzz_mut_680`.`test_json_scalar`) `test_json_scalar` ORDER BY `test_json_scalar`.`id` ASC;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC;
SELECT CAST(`srfuzz_mut_680`.`test_json_scalar`.`id` AS JSON)->'$.a' AS `CAST(id AS JSON)->'$.a'`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`id`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC  LIMIT 1, 100;
SELECT `srfuzz_mut_680`.`test_json_scalar`.`id`, `srfuzz_mut_680`.`test_json_scalar`.`description`, is_json_scalar(`srfuzz_mut_680`.`test_json_scalar`.`json_data`) AS `is_scalar`, json_string(`srfuzz_mut_680`.`test_json_scalar`.`id`) AS `json_value` FROM `srfuzz_mut_680`.`test_json_scalar` ORDER BY `srfuzz_mut_680`.`test_json_scalar`.`id` ASC;
SELECT is_json_scalar(parse_json(parse_json('9223372036854775807'))) AS `test_large_number`;
SELECT is_json_scalar(parse_json('9223372036854775807')) AS `test_large_number` GROUP BY is_json_scalar(parse_json('9223372036854775807'));
SELECT is_json_scalar(parse_json(9223372036854775807)) AS `test_large_number`;
SELECT is_json_scalar(json_query(CAST((parse_json('9223372036854775807')) AS JSON), '$.a')) AS `test_large_number`;
SELECT is_json_scalar(sign('9223372036854775807')) AS `test_large_number`;
SELECT is_json_scalar(parse_json('9223372036854775807')) AS `test_large_number` GROUP BY is_json_scalar(parse_json('9223372036854775807'));
SELECT is_json_scalar(parse_json(FALSE)) AS `test_large_number`;
SELECT is_json_scalar('9223372036854775807') AS `test_large_number`;
SELECT is_json_scalar(parse_json('9223372036854775807')) AS `test_large_number`;
SELECT is_json_scalar(parse_json('9223372036854775807')) AS `test_large_number` GROUP BY is_json_scalar(parse_json('9223372036854775807'));
SELECT is_json_scalar(parse_json('9223372036854775807')) AS `test_large_number` LIMIT 2;
SELECT is_json_scalar(parse_json('9223372036854775807')) AS `test_large_number` GROUP BY is_json_scalar(parse_json('9223372036854775807'));
SELECT is_json_scalar(parse_json('9223372036854775807')) AS `test_large_number`;
SELECT is_json_scalar('9223372036854775807') AS `test_large_number`;
SELECT is_json_scalar(parse_json('9223372036854775807')) AS `test_large_number` LIMIT 100;
SELECT is_json_scalar(parse_json('1970-01-01')) AS `test_large_number`;
SELECT is_json_scalar(parse_json('9223372036854775807')) AS `test_large_number` WHERE is_json_scalar(parse_json('-999'));
SELECT is_json_scalar(parse_json(TRUE)) AS `test_large_number`;
SELECT is_json_scalar(parse_json('9223372036854775807')) AS `test_large_number`;
SELECT is_json_scalar(parse_json(0)) AS `test_large_number`;
SELECT is_json_scalar(parse_json('9223372036854775807')) AS `test_large_number` GROUP BY is_json_scalar(parse_json('9223372036854775807'));
SELECT DISTINCT is_json_scalar(parse_json('9223372036854775807')) AS `test_large_number`;
SELECT is_json_scalar(json_length(CAST((parse_json('9223372036854775807')) AS JSON))) AS `test_large_number`;
SELECT is_json_scalar(char_length('9223372036854775807')) AS `test_large_number`;
SELECT is_json_scalar(parse_json(CAST(NULL AS JSON))) AS `test_large_number`;
SELECT is_json_scalar(parse_json(2147483647)) AS `test_large_number`;
SELECT is_json_scalar('9223372036854775807') AS `test_large_number`;
SELECT is_json_scalar(parse_json(9223372036854775807)) AS `test_large_number`;
SELECT is_json_scalar(exp('9223372036854775807')) AS `test_large_number`;
SELECT is_json_scalar(parse_json(0)) AS `test_small_number`;
SELECT is_json_scalar(bitmap_count('-9223372036854775808')) AS `test_small_number`;
SELECT is_json_scalar(bitmap_count('-9223372036854775808')) AS `test_small_number`;
SELECT is_json_scalar(parse_json(get_json_string(CAST('-9223372036854775808' AS JSON), '$.a'))) AS `test_small_number`;
SELECT is_json_scalar(lower('-9223372036854775808')) AS `test_small_number`;
SELECT is_json_scalar(exp('-9223372036854775808')) AS `test_small_number`;
SELECT is_json_scalar(parse_json('-9223372036854775808')) AS `test_small_number` LIMIT 0;
SELECT is_json_scalar(parse_json(1)) AS `test_small_number`;
SELECT count(is_json_scalar(parse_json('-9223372036854775808'))) OVER () AS `test_small_number`;
SELECT is_json_scalar(parse_json('-9223372036854775808')) AS `test_small_number`;
SELECT is_json_scalar('-9223372036854775808') AS `test_small_number`;
SELECT is_json_scalar(parse_json('-9223372036854775808')) AS `test_small_number`;
SELECT is_json_scalar('-9223372036854775808') AS `test_small_number`;
SELECT DISTINCT is_json_scalar(parse_json('-9223372036854775808')) AS `test_small_number`;
SELECT is_json_scalar(parse_json('-9223372036854775808')) AS `test_small_number` ORDER BY is_json_scalar(parse_json('-9223372036854775808')) ASC;
SELECT is_json_scalar(get_json_string(CAST((parse_json('-9223372036854775808')) AS JSON), '$.a')) AS `test_small_number`;
SELECT is_json_scalar(parse_json(-1.0E308)) AS `test_small_number`;
SELECT is_json_scalar(parse_json('-9223372036854775808')) AS `test_small_number` WHERE is_json_scalar(parse_json('[[1, 2], [3, 4]]'));
SELECT is_json_scalar(ceil('-9223372036854775808')) AS `test_small_number`;
SELECT is_json_scalar(parse_json(-1.0E308)) AS `test_small_number`;
SELECT DISTINCT is_json_scalar(parse_json('-9223372036854775808')) AS `test_small_number`;
SELECT is_json_scalar(parse_json('-9223372036854775808')) AS `test_small_number`;
SELECT is_json_scalar(char_length('-9223372036854775808')) AS `test_small_number`;
SELECT is_json_scalar(hll_cardinality('-9223372036854775808')) AS `test_small_number`;
SELECT is_json_scalar(parse_json('-9223372036854775808')) AS `test_small_number`;
SELECT is_json_scalar(parse_json('-9223372036854775808')) AS `test_small_number` WHERE is_json_scalar(parse_json('true'));
SELECT is_json_scalar(parse_json('-9223372036854775808')) AS `test_small_number`;
SELECT DISTINCT is_json_scalar(parse_json('-9223372036854775808')) AS `test_small_number`;
SELECT is_json_scalar(lower('-9223372036854775808')) AS `test_small_number`;
SELECT is_json_scalar(sign('-9223372036854775808')) AS `test_small_number`;
SELECT is_json_scalar(parse_json('-9223372036854775808')) AS `test_small_number` WHERE is_json_scalar(parse_json('{"user": {"name": "Bob", "age": 30}}'));
SELECT is_json_scalar(parse_json(repeat('x', 65536))) AS `test_small_number`;
SELECT is_json_scalar(parse_json(parse_json('-9223372036854775808'))) AS `test_small_number`;
SELECT is_json_scalar(unhex('-9223372036854775808')) AS `test_small_number`;
SELECT is_json_scalar(parse_json(repeat('a', 1000))) AS `test_long_string` GROUP BY is_json_scalar(parse_json(repeat('a', 1000)));
SELECT is_json_scalar(parse_json(CAST((repeat('a', 1000)) AS BIGINT))) AS `test_long_string`;
SELECT DISTINCT is_json_scalar(parse_json(repeat('a', 1000))) AS `test_long_string`;
SELECT is_json_scalar(upper(repeat('a', 1000))) AS `test_long_string`;
SELECT is_json_scalar(parse_json(repeat(0.0, 1000))) AS `test_long_string`;
SELECT DISTINCT is_json_scalar(parse_json(repeat('a', 1000))) AS `test_long_string`;
SELECT is_json_scalar(parse_json(repeat('a', 'a'))) AS `test_long_string`;
SELECT is_json_scalar(unhex(repeat('a', 1000))) AS `test_long_string`;
SELECT is_json_scalar(repeat('a', 1000)) AS `test_long_string`;
SELECT is_json_scalar(parse_json(repeat('a', 2147483647))) AS `test_long_string`;
SELECT is_json_scalar(parse_json(repeat('a', 1000))) AS `test_long_string`;
SELECT is_json_scalar(parse_json(repeat(repeat('a', 1000), 1000))) AS `test_long_string`;
SELECT is_json_scalar(parse_json(repeat('', 1000))) AS `test_long_string`;
SELECT is_json_scalar(parse_json(repeat('a', 1000))) AS `test_long_string` GROUP BY is_json_scalar(parse_json(repeat('a', 1000)));
SELECT is_json_scalar(sign(repeat('a', 1000))) AS `test_long_string`;
SELECT is_json_scalar(parse_json(date_add('a', INTERVAL 1000 DAY))) AS `test_long_string`;
SELECT is_json_scalar(char_length(repeat('a', 1000))) AS `test_long_string`;
SELECT is_json_scalar(parse_json(repeat('a', 1000))) AS `test_long_string` WHERE is_json_scalar(json_query(parse_json('{"a": null}'), '$.a'));
SELECT is_json_scalar(parse_json(repeat('a', repeat('x', 65536)))) AS `test_long_string`;
SELECT is_json_scalar(bitmap_count(repeat('a', 1000))) AS `test_long_string`;
SELECT is_json_scalar(parse_json(repeat(parse_json(repeat('a', 1000)), 1000))) AS `test_long_string`;
SELECT is_json_scalar(ln(repeat('a', 1000))) AS `test_long_string`;
SELECT is_json_scalar(parse_json(substr('a', 1000))) AS `test_long_string`;
SELECT is_json_scalar(1000) AS `test_long_string`;
SELECT is_json_scalar(parse_json(date_add('a', INTERVAL 1000 DAY))) AS `test_long_string`;
SELECT is_json_scalar(parse_json(repeat(-1.0E308, 1000))) AS `test_long_string`;
SELECT is_json_scalar(parse_json(repeat('a', 1000))) AS `test_long_string` LIMIT 2;
SELECT is_json_scalar(ln(repeat('a', 1000))) AS `test_long_string`;
SELECT count(is_json_scalar(parse_json(repeat('a', 1000)))) OVER () AS `test_long_string`;
SELECT is_json_scalar(parse_json(parse_json('"\\n\\t\\r"'))) AS `test_special_chars`;
SELECT is_json_scalar(parse_json('"\\n\\t\\r"')) AS `test_special_chars`;
SELECT is_json_scalar(lower('"\\n\\t\\r"')) AS `test_special_chars`;
SELECT is_json_scalar(parse_json(parse_json('"\\n\\t\\r"'))) AS `test_special_chars`;
SELECT is_json_scalar(parse_json(FALSE)) AS `test_special_chars`;
SELECT is_json_scalar('"\\n\\t\\r"') AS `test_special_chars`;
SELECT is_json_scalar(parse_json(parse_json('123'))) AS `test_special_chars`;
SELECT is_json_scalar(abs('"\\n\\t\\r"')) AS `test_special_chars`;
SELECT is_json_scalar(length('"\\n\\t\\r"')) AS `test_special_chars`;
SELECT is_json_scalar(parse_json('0')) AS `test_special_chars`;
SELECT is_json_scalar(parse_json('"\\n\\t\\r"')) AS `test_special_chars` GROUP BY is_json_scalar(parse_json('"\\n\\t\\r"'));
SELECT is_json_scalar('"\\n\\t\\r"') AS `test_special_chars`;
SELECT is_json_scalar(parse_json('0000-00-00')) AS `test_special_chars`;
SELECT is_json_scalar(char_length('"\\n\\t\\r"')) AS `test_special_chars`;
SELECT is_json_scalar(parse_json('"\\n\\t\\r"')) AS `test_special_chars` WHERE is_json_scalar(parse_json('-999'));
SELECT is_json_scalar(parse_json(FALSE)) AS `test_special_chars`;
SELECT is_json_scalar(parse_json('"\\n\\t\\r"')) AS `test_special_chars` WHERE is_json_scalar(parse_json('{}'));
SELECT is_json_scalar(parse_json(parse_json('"\\n\\t\\r"'))) AS `test_special_chars`;
SELECT is_json_scalar(parse_json('"\\n\\t\\r"')) AS `test_special_chars` WHERE is_json_scalar(parse_json('{"user": {"name": "Bob", "age": 30}}'));
SELECT is_json_scalar(parse_json(repeat('x', 65536))) AS `test_special_chars`;
SELECT is_json_scalar(parse_json(9223372036854775807)) AS `test_special_chars`;
SELECT is_json_scalar(parse_json('"\\n\\t\\r"')) AS `test_special_chars` LIMIT 2;
SELECT is_json_scalar(parse_json('"\\n\\t\\r"')) AS `test_special_chars` WHERE is_json_scalar(parse_json('123.456'));
SELECT is_json_scalar(parse_json('"\\n\\t\\r"')) AS `test_special_chars`;
SELECT is_json_scalar(parse_json(1)) AS `test_special_chars`;
SELECT is_json_scalar(parse_json('"\\n\\t\\r"')) AS `test_special_chars` ORDER BY is_json_scalar(parse_json('"\\n\\t\\r"')) ASC;
SELECT is_json_scalar(parse_json('"\\n\\t\\r"')) AS `test_special_chars` WHERE is_json_scalar(parse_json('"\\n\\t\\r"'));
SELECT is_json_scalar(year('"\\n\\t\\r"')) AS `test_special_chars`;
SELECT is_json_scalar(parse_json('"\\n\\t\\r"')) AS `test_special_chars` LIMIT 1, 0;