SELECT get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o') AS `get_json_string(j, '$.o')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(`srfuzz_mut_678`.`t`.`j`, '$.o')) AS VARCHAR(65533)) AS `CAST((json_query(j, '$.o')) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((`srfuzz_mut_678`.`t`.`j`->'$.o') AS VARCHAR(65533)) AS `CAST((j->'$.o') AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`srfuzz_mut_678`.`t`.`j`, '$.o.inner') AS `get_json_int(j, '$.o.inner')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE (get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o')) IS NOT NULL;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`id`, '$.o') AS `get_json_string(id, '$.o')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`j`, -9223372036854775808) AS `get_json_string(j, -9223372036854775808)` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`id`, '$.o') AS `get_json_string(id, '$.o')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o') AS `get_json_string(srfuzz_mut_678.t.j, '$.o')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`j`, NULL) AS `get_json_string(j, NULL)` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o') AS `get_json_string(j, '$.o')` FROM `srfuzz_mut_678`.`t` LIMIT 2;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`j`, json_query(CAST('$.o' AS JSON), '$.a')) AS `get_json_string(j, json_query(CAST('$.o' AS JSON), '$.a'))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o') AS `get_json_string(j, '$.o')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o') AS `get_json_string(j, '$.o')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`id`, '$.o') AS `get_json_string(id, '$.o')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`id`, '$.o') AS `get_json_string(id, '$.o')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o') AS `get_json_string(j, '$.o')` FROM `srfuzz_mut_678`.`t` WHERE (get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o')) IS NOT NULL ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`id`, '$.o') AS `get_json_string(srfuzz_mut_678.t.id, '$.o')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o') AS `get_json_string(srfuzz_mut_678.t.j, '$.o')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(CAST((get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o')) AS JSON), '$.a') AS `get_json_string(CAST((get_json_string(j, '$.o')) AS JSON), '$.a')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`j`, '0000-00-00') AS `get_json_string(j, '0000-00-00')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o') AS `get_json_string(srfuzz_mut_678.t.j, '$.o')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`t`.`j`, '$.o') AS `get_json_string(j, '$.o')` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  ORDER BY `t`.`id` ASC  LIMIT 2;
SELECT get_json_string('$.o', '$.o') AS `get_json_string('$.o', '$.o')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`t`.`j`, '$.o') AS `get_json_string(j, '$.o')` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  ORDER BY `t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`j`, get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o')) AS `get_json_string(j, get_json_string(srfuzz_mut_678.t.j, '$.o'))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o') AS `get_json_string(j, '$.o')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`j`, `srfuzz_mut_678`.`t`.`id`) AS `get_json_string(j, srfuzz_mut_678.t.id)` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`j`, -2147483648) AS `get_json_string(j, -2147483648)` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`t`.`j`, '$.o') AS `get_json_string(j, '$.o')` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t` INTERSECT SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` ORDER BY `t`.`id` ASC  LIMIT 2;
SELECT count(get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o')) OVER () AS `count(get_json_string(j, '$.o')) OVER ()` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o') AS `get_json_string(j, '$.o')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o') AS `get_json_string(srfuzz_mut_678.t.j, '$.o')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string('$.o', '$.o') AS `get_json_string('$.o', '$.o')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`t`.`j`, '$.o') AS `get_json_string(j, '$.o')` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t` INTERSECT SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` ORDER BY `t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`j`, 9223372036854775807) AS `get_json_string(j, 9223372036854775807)` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o') AS `get_json_string(j, '$.o')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`j`, `srfuzz_mut_678`.`t`.`id`) AS `get_json_string(j, srfuzz_mut_678.t.id)` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`j`, `srfuzz_mut_678`.`t`.`j`) AS `get_json_string(j, srfuzz_mut_678.t.j)` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_string(`srfuzz_mut_678`.`t`.`j`, -1.0E308) AS `get_json_string(j, -1.0E308)` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(`t`.`j`, '$.o')) AS VARCHAR(65533)) AS `CAST((json_query(j, '$.o')) AS VARCHAR(65533))` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t` UNION ALL SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` ORDER BY `t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(`srfuzz_mut_678`.`t`.`id`, '$.o')) AS VARCHAR(65533)) AS `CAST((json_query(id, '$.o')) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(`t`.`j`, '$.o')) AS VARCHAR(65533)) AS `CAST((json_query(j, '$.o')) AS VARCHAR(65533))` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  ORDER BY `t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(`srfuzz_mut_678`.`t`.`j`, '')) AS VARCHAR(65533)) AS `CAST((json_query(j, '')) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(`srfuzz_mut_678`.`t`.`id`, '$.o')) AS VARCHAR(65533)) AS `CAST((json_query(id, '$.o')) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(`srfuzz_mut_678`.`t`.`j`, `srfuzz_mut_678`.`t`.`id`)) AS VARCHAR(65533)) AS `CAST((json_query(j, srfuzz_mut_678.t.id)) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(`t`.`j`, '$.o')) AS VARCHAR(65533)) AS `CAST((json_query(j, '$.o')) AS VARCHAR(65533))` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t` INTERSECT SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` ORDER BY `t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(`srfuzz_mut_678`.`t`.`id`, '$.o')) AS VARCHAR(65533)) AS `CAST((json_query(srfuzz_mut_678.t.id, '$.o')) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(`srfuzz_mut_678`.`t`.`j`, '$.o')) AS VARCHAR(65533)) AS `CAST((json_query(j, '$.o')) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((truncate(`srfuzz_mut_678`.`t`.`j`, '$.o')) AS VARCHAR(65533)) AS `CAST((truncate(j, '$.o')) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(`t`.`j`, '$.o')) AS VARCHAR(65533)) AS `CAST((json_query(j, '$.o')) AS VARCHAR(65533))` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` ORDER BY `t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(`t`.`j`, '$.o')) AS VARCHAR(65533)) AS `CAST((json_query(j, '$.o')) AS VARCHAR(65533))` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t` UNION SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` ORDER BY `t`.`id` ASC  LIMIT 2;
SELECT CAST((truncate(`srfuzz_mut_678`.`t`.`j`, '$.o')) AS VARCHAR(65533)) AS `CAST((truncate(j, '$.o')) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(`srfuzz_mut_678`.`t`.`j`, CAST((json_query(`srfuzz_mut_678`.`t`.`j`, '$.o')) AS VARCHAR(65533)))) AS VARCHAR(65533)) AS `CAST((json_query(j, CAST((json_query(srfuzz_mut_678.t.j, '$.o')) AS VARCHAR(65533)))) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(`t`.`j`, '$.o')) AS VARCHAR(65533)) AS `CAST((json_query(j, '$.o')) AS VARCHAR(65533))` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t` UNION ALL SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` ORDER BY `t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(`srfuzz_mut_678`.`t`.`id`, '$.o')) AS VARCHAR(65533)) AS `CAST((json_query(id, '$.o')) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT sum(CAST((json_query(`srfuzz_mut_678`.`t`.`j`, '$.o')) AS VARCHAR(65533))) OVER () AS `sum(CAST((json_query(j, '$.o')) AS VARCHAR(65533))) OVER ()` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST(`srfuzz_mut_678`.`t`.`id` AS VARCHAR(65533)) AS `CAST(srfuzz_mut_678.t.id AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(`srfuzz_mut_678`.`t`.`j`, json_query(`srfuzz_mut_678`.`t`.`j`, '$.o'))) AS VARCHAR(65533)) AS `CAST((json_query(j, json_query(srfuzz_mut_678.t.j, '$.o'))) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((concat_ws(`srfuzz_mut_678`.`t`.`j`, '$.o')) AS VARCHAR(65533)) AS `CAST((concat_ws(j, '$.o')) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((round(`srfuzz_mut_678`.`t`.`j`, '$.o')) AS VARCHAR(65533)) AS `CAST((round(j, '$.o')) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(json_query(`srfuzz_mut_678`.`t`.`j`, '$.o'), '$.o')) AS VARCHAR(65533)) AS `CAST((json_query(json_query(srfuzz_mut_678.t.j, '$.o'), '$.o')) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((truncate(`srfuzz_mut_678`.`t`.`j`, '$.o')) AS VARCHAR(65533)) AS `CAST((truncate(j, '$.o')) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query('$.o', '$.o')) AS VARCHAR(65533)) AS `CAST((json_query('$.o', '$.o')) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) SELECT CAST((json_query(`t`.`j`, '$.o')) AS VARCHAR(65533)) AS `CAST((json_query(j, '$.o')) AS VARCHAR(65533))` FROM `srfuzz_n1` AS t ORDER BY `t`.`id` ASC  LIMIT 2;
SELECT CAST('$.o' AS VARCHAR(65533)) AS `CAST('$.o' AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(`t`.`j`, '$.o')) AS VARCHAR(65533)) AS `CAST((json_query(j, '$.o')) AS VARCHAR(65533))` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t` EXCEPT SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` ORDER BY `t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(`t`.`j`, '$.o')) AS VARCHAR(65533)) AS `CAST((json_query(j, '$.o')) AS VARCHAR(65533))` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` ORDER BY `t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(`srfuzz_mut_678`.`t`.`j`, `srfuzz_mut_678`.`t`.`j`)) AS VARCHAR(65533)) AS `CAST((json_query(j, srfuzz_mut_678.t.j)) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(`t`.`j`, '$.o')) AS VARCHAR(65533)) AS `CAST((json_query(j, '$.o')) AS VARCHAR(65533))` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` ORDER BY `t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(`srfuzz_mut_678`.`t`.`j`, '$.o')) AS VARCHAR(65533)) AS `CAST((json_query(j, '$.o')) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(`srfuzz_mut_678`.`t`.`j`, '$.o')) AS VARCHAR(65533)) AS `CAST((json_query(j, '$.o')) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` WHERE (get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o')) IS NOT NULL ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(`srfuzz_mut_678`.`t`.`j`, `srfuzz_mut_678`.`t`.`id`)) AS VARCHAR(65533)) AS `CAST((json_query(j, srfuzz_mut_678.t.id)) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((truncate(`srfuzz_mut_678`.`t`.`j`, '$.o')) AS VARCHAR(65533)) AS `CAST((truncate(j, '$.o')) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(`t`.`j`, '$.o')) AS VARCHAR(65533)) AS `CAST((json_query(j, '$.o')) AS VARCHAR(65533))` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  ORDER BY `t`.`id` ASC  LIMIT 2;
SELECT CAST((`t`.`j`->'$.o') AS VARCHAR(65533)) AS `CAST((j->'$.o') AS VARCHAR(65533))` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t` EXCEPT SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` ORDER BY `t`.`id` ASC  LIMIT 2;
SELECT CAST((`t`.`j`->'$.o') AS VARCHAR(65533)) AS `CAST((j->'$.o') AS VARCHAR(65533))` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` ORDER BY `t`.`id` ASC  LIMIT 2;
SELECT CAST((`srfuzz_mut_678`.`t`.`j`->'$.o') AS VARCHAR(65533)) AS `CAST((j->'$.o') AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC;
SELECT CAST((`srfuzz_mut_678`.`t`.`j`->'0000-00-00') AS VARCHAR(65533)) AS `CAST((j->'0000-00-00') AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((`srfuzz_mut_678`.`t`.`j`->'$.o') AS VARCHAR(65533)) AS `CAST((j->'$.o') AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST(`srfuzz_mut_678`.`t`.`j` AS VARCHAR(65533)) AS `CAST(srfuzz_mut_678.t.j AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((CAST((`srfuzz_mut_678`.`t`.`j`->'$.o') AS VARCHAR(65533))) AS VARCHAR(65533)) AS `CAST((CAST((srfuzz_mut_678.t.j->'$.o') AS VARCHAR(65533))) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((`srfuzz_mut_678`.`t`.`j`->'$.o') AS VARCHAR(65533)) AS `CAST((j->'$.o') AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC;
SELECT CAST((`srfuzz_mut_678`.`t`.`j`->'$.o') AS VARCHAR(65533)) AS `CAST((j->'$.o') AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` LIMIT 2;
SELECT CAST((json_query(`srfuzz_mut_678`.`t`.`j`, '$.o')) AS VARCHAR(65533)) AS `CAST((json_query(srfuzz_mut_678.t.j, '$.o')) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((CAST((`srfuzz_mut_678`.`t`.`j`->'$.o') AS VARCHAR(65533))) AS VARCHAR(65533)) AS `CAST((CAST((srfuzz_mut_678.t.j->'$.o') AS VARCHAR(65533))) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((`srfuzz_mut_678`.`t`.`j`->'$.o') AS VARCHAR(65533)) AS `CAST((j->'$.o') AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) SELECT CAST((`t`.`j`->'$.o') AS VARCHAR(65533)) AS `CAST((j->'$.o') AS VARCHAR(65533))` FROM `srfuzz_n1` AS t ORDER BY `t`.`id` ASC  LIMIT 2;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) SELECT CAST((`t`.`j`->'$.o') AS VARCHAR(65533)) AS `CAST((j->'$.o') AS VARCHAR(65533))` FROM `srfuzz_n1` AS t ORDER BY `t`.`id` ASC  LIMIT 2;
SELECT CAST((`srfuzz_mut_678`.`t`.`j`->'%') AS VARCHAR(65533)) AS `CAST((j->'%') AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST(`srfuzz_mut_678`.`t`.`j` AS VARCHAR(65533)) AS `CAST(srfuzz_mut_678.t.j AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((`srfuzz_mut_678`.`t`.`j`->'$.o') AS VARCHAR(65533)) AS `CAST((j->'$.o') AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC;
SELECT CAST((`srfuzz_mut_678`.`t`.`j`->'$.o') AS VARCHAR(65533)) AS `CAST((srfuzz_mut_678.t.j->'$.o') AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((`srfuzz_mut_678`.`t`.`j`->'$.o') AS VARCHAR(65533)) AS `CAST((srfuzz_mut_678.t.j->'$.o') AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST(`srfuzz_mut_678`.`t`.`j` AS VARCHAR(65533)) AS `CAST(srfuzz_mut_678.t.j AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((json_query(CAST(`srfuzz_mut_678`.`t`.`j` AS JSON), '$.a')->'$.o') AS VARCHAR(65533)) AS `CAST((json_query(CAST(j AS JSON), '$.a')->'$.o') AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((CAST((`srfuzz_mut_678`.`t`.`j`->'$.o') AS VARCHAR(65533))) AS VARCHAR(65533)) AS `CAST((CAST((srfuzz_mut_678.t.j->'$.o') AS VARCHAR(65533))) AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((`srfuzz_mut_678`.`t`.`j`->'$.o'->'$.o') AS VARCHAR(65533)) AS `CAST((srfuzz_mut_678.t.j->'$.o'->'$.o') AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((`srfuzz_mut_678`.`t`.`j`->'$.o') AS VARCHAR(65533)) AS `CAST((j->'$.o') AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT CAST((`srfuzz_mut_678`.`t`.`j`->'$.o') AS VARCHAR(65533)) AS `CAST((j->'$.o') AS VARCHAR(65533))` FROM `srfuzz_mut_678`.`t` LIMIT 2;
SELECT CAST((CAST((get_json_int(`srfuzz_mut_678`.`t`.`j`, '$.o.inner')) AS BOOLEAN)) AS DATE) AS `CAST((CAST((get_json_int(j, '$.o.inner')) AS BOOLEAN)) AS DATE)` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(CAST((CAST(`srfuzz_mut_678`.`t`.`j` AS DECIMAL128(38,0))) AS DECIMAL128(38,37)), '$.o.inner') AS `get_json_int(CAST((CAST(j AS DECIMAL128(38,0))) AS DECIMAL128(38,37)), '$.o.inner')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`srfuzz_mut_678`.`t`.`j`, get_json_int(`srfuzz_mut_678`.`t`.`j`, '$.o.inner')) AS `get_json_int(j, get_json_int(srfuzz_mut_678.t.j, '$.o.inner'))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`t`.`j`, '$.o.inner') AS `get_json_int(j, '$.o.inner')` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` ORDER BY `t`.`id` ASC  LIMIT 2;
SELECT get_json_int(get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o'), '$.o.inner') AS `get_json_int(get_json_string(srfuzz_mut_678.t.j, '$.o'), '$.o.inner')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`srfuzz_mut_678`.`t`.`j`, '$.o.inner') AS `get_json_int(j, '$.o.inner')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`srfuzz_mut_678`.`t`.`id`, '$.o.inner') AS `get_json_int(id, '$.o.inner')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`t`.`j`, '$.o.inner') AS `get_json_int(j, '$.o.inner')` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t` EXCEPT SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` ORDER BY `t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`srfuzz_mut_678`.`t`.`j`, `srfuzz_mut_678`.`t`.`id`) AS `get_json_int(j, srfuzz_mut_678.t.id)` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`srfuzz_mut_678`.`t`.`j`, 1.0E308) AS `get_json_int(j, 1.0E308)` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`srfuzz_mut_678`.`t`.`j`, '$.o.inner') AS `get_json_int(j, '$.o.inner')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`srfuzz_mut_678`.`t`.`j`, '9999-12-31 23:59:59') AS `get_json_int(j, '9999-12-31 23:59:59')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`srfuzz_mut_678`.`t`.`j`, '\\') AS `get_json_int(j, '\\')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(get_json_int(`srfuzz_mut_678`.`t`.`j`, '$.o.inner'), '$.o.inner') AS `get_json_int(get_json_int(srfuzz_mut_678.t.j, '$.o.inner'), '$.o.inner')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`srfuzz_mut_678`.`t`.`j`, '$.o.inner') AS `get_json_int(srfuzz_mut_678.t.j, '$.o.inner')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`srfuzz_mut_678`.`t`.`j`, '$.o.inner') AS `get_json_int(j, '$.o.inner')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`srfuzz_mut_678`.`t`.`j`, '$.o.inner') AS `get_json_int(j, '$.o.inner')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`srfuzz_mut_678`.`t`.`j`, '$.o.inner') AS `get_json_int(j, '$.o.inner')` FROM `srfuzz_mut_678`.`t` WHERE (get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o')) IS NOT NULL ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(get_json_int(`srfuzz_mut_678`.`t`.`j`, '$.o.inner'), '$.o.inner') AS `get_json_int(get_json_int(srfuzz_mut_678.t.j, '$.o.inner'), '$.o.inner')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`srfuzz_mut_678`.`t`.`j`, 2147483647) AS `get_json_int(j, 2147483647)` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`srfuzz_mut_678`.`t`.`j`, '$.o.inner') AS `get_json_int(j, '$.o.inner')` FROM `srfuzz_mut_678`.`t` WHERE (get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o')) IS NOT NULL ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`srfuzz_mut_678`.`t`.`j`, '$.o.inner') AS `get_json_int(srfuzz_mut_678.t.j, '$.o.inner')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`t`.`j`, '$.o.inner') AS `get_json_int(j, '$.o.inner')` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t` EXCEPT SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` ORDER BY `t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`srfuzz_mut_678`.`t`.`j`, '$.o.inner') AS `get_json_int(j, '$.o.inner')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`srfuzz_mut_678`.`t`.`j`, '\\') AS `get_json_int(j, '\\')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`srfuzz_mut_678`.`t`.`j`, '$.o.inner') AS `get_json_int(j, '$.o.inner')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC;
SELECT get_json_int(`srfuzz_mut_678`.`t`.`j`, get_json_int(`srfuzz_mut_678`.`t`.`j`, '$.o.inner')) AS `get_json_int(j, get_json_int(srfuzz_mut_678.t.j, '$.o.inner'))` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int('$.o.inner', '$.o.inner') AS `get_json_int('$.o.inner', '$.o.inner')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) SELECT get_json_int(`t`.`j`, '$.o.inner') AS `get_json_int(j, '$.o.inner')` FROM `srfuzz_n1` AS t ORDER BY `t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`srfuzz_mut_678`.`t`.`id`, '$.o.inner') AS `get_json_int(id, '$.o.inner')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`srfuzz_mut_678`.`t`.`j`, '$.o.inner') AS `get_json_int(j, '$.o.inner')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`srfuzz_mut_678`.`t`.`j`, '$.o.inner') AS `get_json_int(j, '$.o.inner')` FROM `srfuzz_mut_678`.`t` ORDER BY `srfuzz_mut_678`.`t`.`id` ASC  LIMIT 2;
SELECT get_json_int(`t`.`j`, '$.o.inner') AS `get_json_int(j, '$.o.inner')` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  ORDER BY `t`.`id` ASC  LIMIT 2;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE (get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o')) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE (get_json_string('$.o', '$.o')) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE (split(`srfuzz_mut_678`.`t`.`j`, '$.o')) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` WHERE (get_json_string(`t`.`j`, '$.o')) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE (get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o')) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE (get_json_string(`srfuzz_mut_678`.`t`.`j`, -9223372036854775808)) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE (get_json_string(`srfuzz_mut_678`.`t`.`j`, `srfuzz_mut_678`.`t`.`j`)) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE (get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o')) IS NOT NULL GROUP BY `srfuzz_mut_678`.`t`.`id`;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE (json_query(`srfuzz_mut_678`.`t`.`j`, '$.o')) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE CAST(((get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o')) IS NOT NULL) AS DECIMAL128(27,9));
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE (get_json_string('$.o', '$.o')) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE (get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o')) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE (get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o')) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t` INTERSECT SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` WHERE (get_json_string(`t`.`j`, '$.o')) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE '$.o' IS NOT NULL;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE (get_json_string(`srfuzz_mut_678`.`t`.`j`, `srfuzz_mut_678`.`t`.`j`)) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t` UNION SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` WHERE (get_json_string(`t`.`j`, '$.o')) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE (get_json_string('$.o', '$.o')) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE (get_json_string(`srfuzz_mut_678`.`t`.`j`, get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o'))) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` WHERE (get_json_string(`t`.`j`, '$.o')) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE `srfuzz_mut_678`.`t`.`j` IS NOT NULL;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE (json_query(`srfuzz_mut_678`.`t`.`j`, '$.o')) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE (get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o')) IS NOT NULL HAVING (count(*)) >= 2;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE (get_json_string(`srfuzz_mut_678`.`t`.`j`, json_length(CAST('$.o' AS JSON)))) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE (get_json_string(`srfuzz_mut_678`.`t`.`j`, get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o'))) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` WHERE (get_json_string(`t`.`j`, '$.o')) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE (truncate(`srfuzz_mut_678`.`t`.`j`, '$.o')) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE (get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o')) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_678`.`t`.`id`, `srfuzz_mut_678`.`t`.`j` FROM `srfuzz_mut_678`.`t`) `t` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  WHERE (get_json_string(`t`.`j`, '$.o')) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE (concat_ws(`srfuzz_mut_678`.`t`.`j`, '$.o')) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE (json_query(`srfuzz_mut_678`.`t`.`j`, '$.o')) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE (get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o')) IS NOT NULL;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_678`.`t` WHERE (get_json_string(`srfuzz_mut_678`.`t`.`j`, '$.o')) IS NOT NULL;