SELECT substr('', `srfuzz_mut_442`.`t1`.`v`) AS `substr('', v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`) AS `substring('', v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`) AS `substr('', v)` FROM `srfuzz_mut_442`.`t1` WHERE substr('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`);
SELECT substr('', '') AS `substr('', '')` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`) AS `substr('', v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr(0.0, `srfuzz_mut_442`.`t1`.`v`) AS `substr(0.0, v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `t1`.`v`) AS `substr('', v)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1` INTERSECT SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`) AS `substr('', v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('1970-01-01', `srfuzz_mut_442`.`t1`.`v`) AS `substr('1970-01-01', v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`) AS `substr('', srfuzz_mut_442.t1.v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `t1`.`v`) AS `substr('', v)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1` EXCEPT SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`) AS `substr('', v)` FROM `srfuzz_mut_442`.`t1` GROUP BY substr('', `srfuzz_mut_442`.`t1`.`v`);
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`) AS `substr('', v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`) AS `substr('', srfuzz_mut_442.t1.v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr(substr('', `srfuzz_mut_442`.`t1`.`v`), `srfuzz_mut_442`.`t1`.`v`) AS `substr(substr('', srfuzz_mut_442.t1.v), v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`) AS `substr('', srfuzz_mut_442.t1.v)` FROM `srfuzz_mut_442`.`t1`;
SELECT sum(substr('', `srfuzz_mut_442`.`t1`.`v`)) OVER (PARTITION BY `srfuzz_mut_442`.`t1`.`id` ) AS `sum(substr('', v)) OVER (PARTITION BY id )` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`) AS `substr('', srfuzz_mut_442.t1.v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', '') AS `substr('', '')` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `t1`.`v`) AS `substr('', v)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT substr(`srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`v`) AS `substr(srfuzz_mut_442.t1.v, v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', '') AS `substr('', '')` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `t1`.`v`) AS `substr('', v)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT DISTINCT substr('', `srfuzz_mut_442`.`t1`.`v`) AS `substr('', v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`) AS `substr('', srfuzz_mut_442.t1.v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`) AS `substr('', v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`) AS `substr('', v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr(`srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`v`) AS `substr(srfuzz_mut_442.t1.v, v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', '') AS `substr('', '')` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`) AS `substr('', v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`) AS `substr('', v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', substr('', `srfuzz_mut_442`.`t1`.`v`)) AS `substr('', substr('', srfuzz_mut_442.t1.v))` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`) AS `substr('', v)` FROM `srfuzz_mut_442`.`t1` LIMIT 100;
SELECT substr(substr('', `srfuzz_mut_442`.`t1`.`v`), `srfuzz_mut_442`.`t1`.`v`) AS `substr(substr('', srfuzz_mut_442.t1.v), v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`) AS `substr('', srfuzz_mut_442.t1.v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', '') AS `substr('', '')` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `t1`.`v`) AS `substr('', v)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1` EXCEPT SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`, substr('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`)) AS `substr('', v, substr('', srfuzz_mut_442.t1.v, srfuzz_mut_442.t1.id))` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('', v, id)` FROM `srfuzz_mut_442`.`t1` ORDER BY substr('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) DESC;
SELECT DISTINCT substr('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `t1`.`v`, `t1`.`id`) AS `substr('', v, id)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1` INTERSECT SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('', v, srfuzz_mut_442.t1.id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `t1`.`v`, `t1`.`id`) AS `substr('', v, id)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1` UNION ALL SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1`;
SELECT substr('', json_length(CAST(`srfuzz_mut_442`.`t1`.`v` AS JSON)), `srfuzz_mut_442`.`t1`.`id`) AS `substr('', json_length(CAST(v AS JSON)), id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `t1`.`v`, `t1`.`id`) AS `substr('', v, id)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1`;
SELECT substr(substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`), `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr(substring('STARROCKS', srfuzz_mut_442.t1.v, srfuzz_mut_442.t1.id), v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `t1`.`v`, `t1`.`id`) AS `substr('', v, id)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1` EXCEPT SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1`;
SELECT substr(FALSE, `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr(FALSE, v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `t1`.`v`, `t1`.`id`) AS `substr('', v, id)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1` UNION ALL SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('', srfuzz_mut_442.t1.v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('', v, id)` FROM `srfuzz_mut_442`.`t1` ORDER BY substr('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) DESC;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`, substr('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`)) AS `substr('', v, substr('', srfuzz_mut_442.t1.v, srfuzz_mut_442.t1.id))` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`, '') AS `substr('', v, '')` FROM `srfuzz_mut_442`.`t1`;
SELECT dense_rank() OVER (PARTITION BY `srfuzz_mut_442`.`t1`.`id` ORDER BY substr('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) ASC ) AS `dense_rank() OVER (PARTITION BY id ORDER BY substr('', v, id) ASC )` FROM `srfuzz_mut_442`.`t1`;
SELECT substr(substr('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`), `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr(substr('', srfuzz_mut_442.t1.v, srfuzz_mut_442.t1.id), v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('', v, id)` FROM `srfuzz_mut_442`.`t1` ORDER BY substr('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) DESC;
SELECT substr('', `t1`.`v`, `t1`.`id`) AS `substr('', v, id)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1` EXCEPT SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('', id, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('', v, id)` FROM `srfuzz_mut_442`.`t1` ORDER BY substr('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) ASC;
SELECT substr('', `t1`.`v`, `t1`.`id`) AS `substr('', v, id)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1`;
SELECT substr('', `t1`.`v`, `t1`.`id`) AS `substr('', v, id)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('', v, id)` FROM `srfuzz_mut_442`.`t1` ORDER BY substr('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) DESC;
SELECT substr('', `srfuzz_mut_442`.`t1`.`v`, '') AS `substr('', v, '')` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('', `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('', id, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('STARROCKS', `t1`.`v`, `t1`.`id`) AS `substr('STARROCKS', v, id)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1` INTERSECT SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1`;
SELECT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, 'STARROCKS') AS `substr('STARROCKS', v, 'STARROCKS')` FROM `srfuzz_mut_442`.`t1`;
SELECT substr(`srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr(srfuzz_mut_442.t1.id, v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1` WHERE `srfuzz_mut_442`.`t1`.`id`;
SELECT substr('0000-00-00', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('0000-00-00', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr(-9223372036854775808, `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr(-9223372036854775808, v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1` GROUP BY substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`);
SELECT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('STARROCKS', srfuzz_mut_442.t1.v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('STARROCKS', id, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1` ORDER BY substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) ASC;
SELECT substr(`srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr(srfuzz_mut_442.t1.v, v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('0', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('0', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1` WHERE substring('', `srfuzz_mut_442`.`t1`.`v`);
SELECT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, 'STARROCKS') AS `substr('STARROCKS', v, 'STARROCKS')` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`v`) AS `substr('STARROCKS', v, v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('STARROCKS', id, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('0', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('0', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT DISTINCT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr(1, `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr(1, v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('STARROCKS', `t1`.`v`, `t1`.`id`) AS `substr('STARROCKS', v, id)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1` UNION ALL SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1`;
SELECT substr(`srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr(srfuzz_mut_442.t1.id, v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1` WHERE substr('', `srfuzz_mut_442`.`t1`.`v`);
SELECT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('STARROCKS', `t1`.`v`, `t1`.`id`) AS `substr('STARROCKS', v, id)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1` UNION ALL SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1`;
SELECT substr('STARROCKS', substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`), `srfuzz_mut_442`.`t1`.`id`) AS `substr('STARROCKS', substr('STARROCKS', srfuzz_mut_442.t1.v, srfuzz_mut_442.t1.id), id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1` WHERE substring('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`);
SELECT DISTINCT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('STARROCKS', id, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr(`srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr(srfuzz_mut_442.t1.id, v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, 'STARROCKS') AS `substr('STARROCKS', v, 'STARROCKS')` FROM `srfuzz_mut_442`.`t1`;
SELECT substr(0.0, `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr(0.0, v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT DISTINCT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT DISTINCT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substr('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, '') AS `substr('STARROCKS', v, '')` FROM `srfuzz_mut_442`.`t1`;
SELECT substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`)) AS `substr('STARROCKS', v, substr('STARROCKS', srfuzz_mut_442.t1.v, srfuzz_mut_442.t1.id))` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `t1`.`v`) AS `substring('', v)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1` UNION SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`) AS `substring('', v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`) AS `substring('', v)` FROM `srfuzz_mut_442`.`t1` LIMIT 1;
SELECT min(substring('', `srfuzz_mut_442`.`t1`.`v`)) OVER () AS `min(substring('', v)) OVER ()` FROM `srfuzz_mut_442`.`t1`;
SELECT substring(`srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`v`) AS `substring(srfuzz_mut_442.t1.v, v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`) AS `substring('', v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', substring('', `srfuzz_mut_442`.`t1`.`v`)) AS `substring('', substring('', srfuzz_mut_442.t1.v))` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', '') AS `substring('', '')` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', '') AS `substring('', '')` FROM `srfuzz_mut_442`.`t1`;
SELECT substring(2147483647, `srfuzz_mut_442`.`t1`.`v`) AS `substring(2147483647, v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring(repeat('x', 65536), `srfuzz_mut_442`.`t1`.`v`) AS `substring(repeat('x', 65536), v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring(`srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`v`) AS `substring(srfuzz_mut_442.t1.v, v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring(substring('', `srfuzz_mut_442`.`t1`.`v`), `srfuzz_mut_442`.`t1`.`v`) AS `substring(substring('', srfuzz_mut_442.t1.v), v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring(`srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`v`) AS `substring(srfuzz_mut_442.t1.v, v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`) AS `substring('', v)` FROM `srfuzz_mut_442`.`t1` LIMIT 0;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`) AS `substring('', v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring(substring('', `srfuzz_mut_442`.`t1`.`v`), `srfuzz_mut_442`.`t1`.`v`) AS `substring(substring('', srfuzz_mut_442.t1.v), v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', '') AS `substring('', '')` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`) AS `substring('', srfuzz_mut_442.t1.v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring(-1.0E308, `srfuzz_mut_442`.`t1`.`v`) AS `substring(-1.0E308, v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`) AS `substring('', v)` FROM `srfuzz_mut_442`.`t1` LIMIT 0;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`) AS `substring('', srfuzz_mut_442.t1.v)` FROM `srfuzz_mut_442`.`t1`;
SELECT CAST((substring('', `srfuzz_mut_442`.`t1`.`v`)) AS INT) AS `CAST((substring('', v)) AS INT)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring(`srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`v`) AS `substring(srfuzz_mut_442.t1.v, v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring(substring('', `srfuzz_mut_442`.`t1`.`v`), `srfuzz_mut_442`.`t1`.`v`) AS `substring(substring('', srfuzz_mut_442.t1.v), v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `t1`.`v`) AS `substring('', v)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1` INTERSECT SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`) AS `substring('', v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', '') AS `substring('', '')` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`) AS `substring('', srfuzz_mut_442.t1.v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `t1`.`v`) AS `substring('', v)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1` UNION ALL SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1`;
SELECT substring(0, `srfuzz_mut_442`.`t1`.`v`) AS `substring(0, v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`) AS `substring('', v)` FROM `srfuzz_mut_442`.`t1` LIMIT 7, 1;
SELECT substring(`srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`v`) AS `substring(srfuzz_mut_442.t1.v, v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring(`srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring(srfuzz_mut_442.t1.id, v, id)` FROM `srfuzz_mut_442`.`t1`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) SELECT substring('', `t1`.`v`, `t1`.`id`) AS `substring('', v, id)` FROM `srfuzz_n1` AS t1;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`v`) AS `substring('', v, srfuzz_mut_442.t1.v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`, '') AS `substring('', v, '')` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `t1`.`v`, `t1`.`id`) AS `substring('', v, id)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1`;
SELECT substring('', `t1`.`v`, `t1`.`id`) AS `substring('', v, id)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1` EXCEPT SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('', srfuzz_mut_442.t1.id, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('', v, id)` FROM `srfuzz_mut_442`.`t1` GROUP BY substring('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`);
SELECT substring(json_length(CAST('' AS JSON)), `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring(json_length(CAST('' AS JSON)), v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('', v, id)` FROM `srfuzz_mut_442`.`t1`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) SELECT substring('', `t1`.`v`, `t1`.`id`) AS `substring('', v, id)` FROM `srfuzz_n1` AS t1;
SELECT DISTINCT substring('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `t1`.`v`, `t1`.`id`) AS `substring('', v, id)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`, json_length(CAST(`srfuzz_mut_442`.`t1`.`id` AS JSON))) AS `substring('', v, json_length(CAST(id AS JSON)))` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`v`) AS `substring('', v, srfuzz_mut_442.t1.v)` FROM `srfuzz_mut_442`.`t1`;
SELECT DISTINCT substring('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `t1`.`v`, `t1`.`id`) AS `substring('', v, id)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1`;
SELECT substring('', substring('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`), `srfuzz_mut_442`.`t1`.`id`) AS `substring('', substring('', srfuzz_mut_442.t1.v, srfuzz_mut_442.t1.id), id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`, substring('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`)) AS `substring('', v, substring('', srfuzz_mut_442.t1.v, srfuzz_mut_442.t1.id))` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('', srfuzz_mut_442.t1.v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `t1`.`v`, `t1`.`id`) AS `substring('', v, id)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1` UNION SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`v`) AS `substring('', v, srfuzz_mut_442.t1.v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`, 'STARROCKS') AS `substring('', v, 'STARROCKS')` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('', id, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT max(substring('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`)) OVER (PARTITION BY `srfuzz_mut_442`.`t1`.`v` ) AS `max(substring('', v, id)) OVER (PARTITION BY v )` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`v`) AS `substring('', v, v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('', v, srfuzz_mut_442.t1.id)` FROM `srfuzz_mut_442`.`t1`;
SELECT count(substring('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`)) OVER (PARTITION BY `srfuzz_mut_442`.`t1`.`v` ) AS `count(substring('', v, id)) OVER (PARTITION BY v )` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('', v, id)` FROM `srfuzz_mut_442`.`t1` GROUP BY substring('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`);
SELECT substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1` GROUP BY substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`);
SELECT CAST((CAST((substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`)) AS SMALLINT)) AS JSON) AS `CAST((CAST((substring('STARROCKS', v, id)) AS SMALLINT)) AS JSON)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('STARROCKS', `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('STARROCKS', srfuzz_mut_442.t1.id, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring(`srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring(srfuzz_mut_442.t1.id, v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring(substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`), `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring(substring('STARROCKS', srfuzz_mut_442.t1.v, srfuzz_mut_442.t1.id), v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`v`) AS `substring('STARROCKS', v, v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`v`) AS `substring('STARROCKS', v, v)` FROM `srfuzz_mut_442`.`t1`;
SELECT min(substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`)) OVER (PARTITION BY `srfuzz_mut_442`.`t1`.`v` ) AS `min(substring('STARROCKS', v, id)) OVER (PARTITION BY v )` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`v`) AS `substring('STARROCKS', v, v)` FROM `srfuzz_mut_442`.`t1`;
SELECT DISTINCT substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('STARROCKS', `t1`.`v`, `t1`.`id`) AS `substring('STARROCKS', v, id)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT substring('STARROCKS', substr('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`), `srfuzz_mut_442`.`t1`.`id`) AS `substring('STARROCKS', substr('STARROCKS', srfuzz_mut_442.t1.v, srfuzz_mut_442.t1.id), id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('STARROCKS', `t1`.`v`, `t1`.`id`) AS `substring('STARROCKS', v, id)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1` UNION SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1`;
SELECT substring('STARROCKS', substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`), `srfuzz_mut_442`.`t1`.`id`) AS `substring('STARROCKS', substring('STARROCKS', srfuzz_mut_442.t1.v, srfuzz_mut_442.t1.id), id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1` LIMIT 7, 0;
SELECT substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`v`) AS `substring('STARROCKS', v, v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('STARROCKS', `t1`.`v`, `t1`.`id`) AS `substring('STARROCKS', v, id)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1` INTERSECT SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1`;
SELECT substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`v`) AS `substring('STARROCKS', v, v)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('STARROCKS', substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`), `srfuzz_mut_442`.`t1`.`id`) AS `substring('STARROCKS', substring('STARROCKS', srfuzz_mut_442.t1.v, srfuzz_mut_442.t1.id), id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('STARROCKS', `t1`.`v`, `t1`.`id`) AS `substring('STARROCKS', v, id)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1` UNION SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1`;
SELECT substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1` GROUP BY substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`);
SELECT substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('STARROCKS', v, srfuzz_mut_442.t1.id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1` LIMIT 2;
SELECT substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`)) AS `substring('STARROCKS', v, substring('STARROCKS', srfuzz_mut_442.t1.v, srfuzz_mut_442.t1.id))` FROM `srfuzz_mut_442`.`t1`;
SELECT substring(substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`), `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring(substring('STARROCKS', srfuzz_mut_442.t1.v, srfuzz_mut_442.t1.id), v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('STARROCKS', 'STARROCKS', `srfuzz_mut_442`.`t1`.`id`) AS `substring('STARROCKS', 'STARROCKS', id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('STARROCKS', `t1`.`v`, `t1`.`id`) AS `substring('STARROCKS', v, id)` FROM (SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1` UNION ALL SELECT `srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v` FROM `srfuzz_mut_442`.`t1`) `t1`;
SELECT substring(`srfuzz_mut_442`.`t1`.`id`, `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring(srfuzz_mut_442.t1.id, v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('STARROCKS', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('STARROCKS', v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring(170141183460469231731687303715884105727, `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring(170141183460469231731687303715884105727, v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring(-1.0E308, `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring(-1.0E308, v, id)` FROM `srfuzz_mut_442`.`t1`;
SELECT substring('', `srfuzz_mut_442`.`t1`.`v`, `srfuzz_mut_442`.`t1`.`id`) AS `substring('', v, id)` FROM `srfuzz_mut_442`.`t1`;