CREATE TABLE t_or_bitmap (
  id BIGINT NOT NULL,
  a  INT    NOT NULL,
  b  INT    NOT NULL,
  INDEX idx_a (a) USING BITMAP
) ENGINE=OLAP
DUPLICATE KEY(id)
DISTRIBUTED BY HASH(id) BUCKETS 1
PROPERTIES ("replication_num" = "1");
INSERT INTO t_or_bitmap
SELECT generate_series AS id, CAST(generate_series + 1000 AS INT) AS a, 100 AS b
FROM TABLE(generate_series(1, 5000))
UNION ALL SELECT 100001, 1, 2
UNION ALL SELECT 100002, 2, 3
UNION ALL SELECT 100003, 1, 3
UNION ALL SELECT 100004, 2, 2;