SELECT sleep(10) AS `sleep(10)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT min(`information_schema`.`t1`.`NUM_VERSION`) AS `min(NUM_VERSION)` FROM `information_schema`.`be_tablets` AS `t1` , `information_schema`.`tables_config` AS `t2`  WHERE ((`information_schema`.`t2`.`TABLE_NAME` = 't') AND (`information_schema`.`t1`.`TABLE_ID` = `information_schema`.`t2`.`TABLE_ID`)) AND (`information_schema`.`t2`.`TABLE_SCHEMA` = 'test_disable_compaction');
SELECT sleep(10) AS `sleep(10)`;
SELECT DISTINCT sleep(10) AS `sleep(10)`;
SELECT CAST((sleep(10)) AS TINYINT) AS `CAST((sleep(10)) AS TINYINT)`;
SELECT sleep(10) AS `sleep(10)`;
SELECT sleep(10) AS `sleep(10)` GROUP BY sleep(10);
SELECT sleep(10) AS `sleep(10)` LIMIT 0;
SELECT sleep(10) AS `sleep(10)` GROUP BY sleep(10);
SELECT sleep(TRUE) AS `sleep(TRUE)`;
SELECT sleep(FALSE) AS `sleep(FALSE)`;
SELECT sleep('') AS `sleep('')`;
SELECT sleep(10) AS `sleep(10)`;
SELECT sleep('%') AS `sleep('%')`;
SELECT sleep(CAST(10 AS JSON)->'$.a') AS `sleep(CAST(10 AS JSON)->'$.a')`;
SELECT sleep(10) AS `sleep(10)` LIMIT 7, 1;
SELECT sleep(170141183460469231731687303715884105727) AS `sleep(170141183460469231731687303715884105727)`;
SELECT sleep(10) AS `sleep(10)`;
SELECT sleep(1.0E308) AS `sleep(1.0E308)`;
SELECT sleep(-9223372036854775808) AS `sleep(-9223372036854775808)`;
SELECT sleep(10) AS `sleep(10)`;
SELECT sleep(10) AS `sleep(10)`;
SELECT sleep(10) AS `sleep(10)` GROUP BY sleep(10);
SELECT sleep(10) AS `sleep(10)`;
SELECT sleep(10) AS `sleep(10)`;
SELECT sleep('0000-00-00') AS `sleep('0000-00-00')`;
SELECT sleep(10) AS `sleep(10)` ORDER BY sleep(10) DESC;
SELECT sleep(10) AS `sleep(10)` WHERE sleep(3);
SELECT CAST((CAST((CAST((sleep(10)) AS DECIMAL128(38,37))) AS DECIMAL128(38,38))) AS BIGINT) AS `CAST((CAST((CAST((sleep(10)) AS DECIMAL128(38,37))) AS DECIMAL128(38,38))) AS BIGINT)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep('1970-01-01') AS `sleep('1970-01-01')`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep('0') AS `sleep('0')`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT json_length(CAST((sleep(3)) AS JSON)) AS `json_length(CAST((sleep(3)) AS JSON))`;
SELECT sleep('') AS `sleep('')`;
SELECT sleep('\\') AS `sleep('\\')`;
SELECT sleep('0') AS `sleep('0')`;
SELECT sleep('9999-12-31 23:59:59') AS `sleep('9999-12-31 23:59:59')`;
SELECT dense_rank() OVER (ORDER BY sleep(3) ASC ) AS `dense_rank() OVER (ORDER BY sleep(3) ASC )`;
SELECT sleep('%') AS `sleep('%')`;
SELECT CAST((CAST((CAST((sleep(3)) AS JSON)) AS FLOAT)) AS DECIMAL128(38,0)) AS `CAST((CAST((CAST((sleep(3)) AS JSON)) AS FLOAT)) AS DECIMAL128(38,0))`;
SELECT CAST((sleep(3)) AS MAP<VARCHAR(16),struct<`a` int(11)>>) AS `CAST((sleep(3)) AS MAP<VARCHAR(16),struct<``a`` int(11)>>)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep('%') AS `sleep('%')`;
SELECT sleep(1.0E308) AS `sleep(1.0E308)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)` ORDER BY sleep(3) DESC;
SELECT sleep('%') AS `sleep('%')`;
SELECT get_json_string(CAST((sleep(3)) AS JSON), '$.a') AS `get_json_string(CAST((sleep(3)) AS JSON), '$.a')`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(170141183460469231731687303715884105727) AS `sleep(170141183460469231731687303715884105727)`;
SELECT json_length(CAST((sleep(3)) AS JSON)) AS `json_length(CAST((sleep(3)) AS JSON))`;
SELECT DISTINCT sleep(3) AS `sleep(3)`;
SELECT sleep('0') AS `sleep('0')`;
SELECT sleep(get_json_string(CAST(3 AS JSON), '$.a')) AS `sleep(get_json_string(CAST(3 AS JSON), '$.a'))`;
SELECT sleep(-9223372036854775808) AS `sleep(-9223372036854775808)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT min(`information_schema`.`t1`.`NUM_VERSION`) AS `min(NUM_VERSION)` FROM `information_schema`.`be_tablets` AS `t1` , `information_schema`.`tables_config` AS `t2`  WHERE (('t' = 't') AND (`information_schema`.`t1`.`TABLE_ID` = `information_schema`.`t2`.`TABLE_ID`)) AND (`information_schema`.`t2`.`TABLE_SCHEMA` = 'test_disable_compaction');
SELECT min(`information_schema`.`t1`.`NUM_VERSION`) AS `min(NUM_VERSION)` FROM `information_schema`.`be_tablets` AS `t1` , `information_schema`.`tables_config` AS `t2`;
SELECT min(`information_schema`.`t1`.`NUM_VERSION`) AS `min(NUM_VERSION)` FROM `information_schema`.`be_tablets` AS `t1` , `information_schema`.`tables_config` AS `t2`  WHERE ((`information_schema`.`t2`.`TABLE_NAME` = 't') AND (`information_schema`.`t1`.`TABLE_ID` = `information_schema`.`t2`.`TABLE_ID`)) AND (`information_schema`.`t2`.`TABLE_SCHEMA` = 'test_disable_compaction') ORDER BY min(`information_schema`.`t1`.`NUM_VERSION`) ASC;
SELECT min(`information_schema`.`t1`.`NUM_VERSION`) AS `min(NUM_VERSION)` FROM `information_schema`.`be_tablets` AS `t1` , ((SELECT `information_schema`.`t2`.`TABLE_SCHEMA`, `information_schema`.`t2`.`TABLE_NAME`, `information_schema`.`t2`.`TABLE_ENGINE`, `information_schema`.`t2`.`TABLE_MODEL`, `information_schema`.`t2`.`PRIMARY_KEY`, `information_schema`.`t2`.`PARTITION_KEY`, `information_schema`.`t2`.`DISTRIBUTE_KEY`, `information_schema`.`t2`.`DISTRIBUTE_TYPE`, `information_schema`.`t2`.`DISTRIBUTE_BUCKET`, `information_schema`.`t2`.`SORT_KEY`, `information_schema`.`t2`.`PROPERTIES`, `information_schema`.`t2`.`TABLE_ID` FROM `information_schema`.`tables_config` AS `t2`) `t2` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`) )  WHERE ((`t2`.`TABLE_NAME` = 't') AND (`information_schema`.`t1`.`TABLE_ID` = `t2`.`TABLE_ID`)) AND (`t2`.`TABLE_SCHEMA` = 'test_disable_compaction');
SELECT min(`information_schema`.`t2`.`TABLE_NAME`) AS `min(TABLE_NAME)` FROM `information_schema`.`be_tablets` AS `t1` , `information_schema`.`tables_config` AS `t2`  WHERE ((`information_schema`.`t2`.`TABLE_NAME` = 't') AND (`information_schema`.`t1`.`TABLE_ID` = `information_schema`.`t2`.`TABLE_ID`)) AND (`information_schema`.`t2`.`TABLE_SCHEMA` = 'test_disable_compaction');
SELECT min(`information_schema`.`t1`.`NUM_VERSION`) AS `min(NUM_VERSION)` FROM `information_schema`.`be_tablets` AS `t1` , `information_schema`.`tables_config` AS `t2`  WHERE ((`information_schema`.`t2`.`TABLE_NAME` = 't') AND (`information_schema`.`t1`.`NUM_VERSION` = `information_schema`.`t2`.`TABLE_ID`)) AND (`information_schema`.`t2`.`TABLE_SCHEMA` = 'test_disable_compaction');
SELECT min(`information_schema`.`t1`.`NUM_VERSION`) AS `min(NUM_VERSION)` FROM `information_schema`.`be_tablets` AS `t1` , `information_schema`.`tables_config` AS `t2`  WHERE (((`information_schema`.`t2`.`TABLE_NAME` = 't') AND (`information_schema`.`t1`.`TABLE_ID` = `information_schema`.`t2`.`TABLE_ID`)) AND (`information_schema`.`t2`.`TABLE_SCHEMA` = 'test_disable_compaction')) AND (`information_schema`.`t2`.`TABLE_SCHEMA` = 'test_disable_compaction');
SELECT min(`information_schema`.`t1`.`NUM_VERSION`) AS `min(NUM_VERSION)` FROM `information_schema`.`be_tablets` AS `t1` , `information_schema`.`tables_config` AS `t2`  WHERE ((`information_schema`.`t2`.`TABLE_NAME` = 't') AND (CAST((`information_schema`.`t1`.`TABLE_ID` = `information_schema`.`t2`.`TABLE_ID`) AS DOUBLE))) AND (`information_schema`.`t2`.`TABLE_SCHEMA` = 'test_disable_compaction');
SELECT min(`information_schema`.`t1`.`NUM_VERSION`) AS `min(NUM_VERSION)` FROM `information_schema`.`be_tablets` AS `t1` , `information_schema`.`tables_config` AS `t2`  WHERE ((`information_schema`.`t2`.`TABLE_NAME` = 't') AND (`information_schema`.`t1`.`TABLE_ID` = `information_schema`.`t2`.`TABLE_ID`)) AND (`information_schema`.`t2`.`TABLE_SCHEMA` = 'test_disable_compaction') HAVING (count(*)) > 0;
WITH `srfuzz_n1` AS (SELECT `information_schema`.`t2`.`TABLE_SCHEMA`, `information_schema`.`t2`.`TABLE_NAME`, `information_schema`.`t2`.`TABLE_ENGINE`, `information_schema`.`t2`.`TABLE_MODEL`, `information_schema`.`t2`.`PRIMARY_KEY`, `information_schema`.`t2`.`PARTITION_KEY`, `information_schema`.`t2`.`DISTRIBUTE_KEY`, `information_schema`.`t2`.`DISTRIBUTE_TYPE`, `information_schema`.`t2`.`DISTRIBUTE_BUCKET`, `information_schema`.`t2`.`SORT_KEY`, `information_schema`.`t2`.`PROPERTIES`, `information_schema`.`t2`.`TABLE_ID` FROM `information_schema`.`tables_config` AS `t2`) SELECT min(`information_schema`.`t1`.`NUM_VERSION`) AS `min(NUM_VERSION)` FROM `information_schema`.`be_tablets` AS `t1` , `srfuzz_n1` AS t2  WHERE ((`t2`.`TABLE_NAME` = 't') AND (`information_schema`.`t1`.`TABLE_ID` = `t2`.`TABLE_ID`)) AND (`t2`.`TABLE_SCHEMA` = 'test_disable_compaction');
SELECT min(`information_schema`.`t1`.`NUM_VERSION`) AS `min(NUM_VERSION)` FROM `information_schema`.`be_tablets` AS `t1` , `information_schema`.`tables_config` AS `t2`  WHERE ((`information_schema`.`t2`.`TABLE_NAME` = 't') AND (`information_schema`.`t1`.`TABLE_ID` = `information_schema`.`t2`.`TABLE_SCHEMA`)) AND (`information_schema`.`t2`.`TABLE_SCHEMA` = 'test_disable_compaction');
SELECT min(`information_schema`.`t1`.`NUM_VERSION`) AS `min(NUM_VERSION)` FROM `information_schema`.`be_tablets` AS `t1` , `information_schema`.`tables_config` AS `t2`  WHERE ((`information_schema`.`t2`.`TABLE_NAME` = 't') AND (`information_schema`.`t1`.`TABLE_ID` = `information_schema`.`t2`.`TABLE_ID`)) AND (`information_schema`.`t1`.`TABLE_ID` = 'test_disable_compaction');
SELECT min(`information_schema`.`t1`.`NUM_VERSION`) AS `min(NUM_VERSION)` FROM `information_schema`.`be_tablets` AS `t1` , `information_schema`.`tables_config` AS `t2`  WHERE ((`information_schema`.`t2`.`TABLE_NAME` = 't') AND (`information_schema`.`t1`.`TABLE_ID` = `information_schema`.`t2`.`TABLE_ID`)) AND (`information_schema`.`t2`.`TABLE_SCHEMA` = 'test_disable_compaction') GROUP BY `information_schema`.`t1`.`NUM_VERSION`;
SELECT min(`information_schema`.`t1`.`NUM_VERSION`) AS `min(NUM_VERSION)` FROM `information_schema`.`be_tablets` AS `t1` , `information_schema`.`tables_config` AS `t2`  WHERE ((`information_schema`.`t2`.`TABLE_NAME` = 't') AND (`information_schema`.`t1`.`TABLE_ID` = `information_schema`.`t2`.`TABLE_ID`)) AND (`information_schema`.`t2`.`TABLE_NAME` = 't');
SELECT min(`information_schema`.`t1`.`NUM_VERSION`) AS `min(NUM_VERSION)` FROM `information_schema`.`be_tablets` AS `t1` , `information_schema`.`tables_config` AS `t2`  WHERE (`information_schema`.`t2`.`TABLE_SCHEMA` = 'test_disable_compaction') AND (`information_schema`.`t2`.`TABLE_SCHEMA` = 'test_disable_compaction');
SELECT min(`information_schema`.`t1`.`NUM_VERSION`) AS `min(NUM_VERSION)` FROM `information_schema`.`be_tablets` AS `t1` , `information_schema`.`tables_config` AS `t2`  WHERE ((`information_schema`.`t2`.`TABLE_NAME` = 't') AND (`information_schema`.`t1`.`TABLE_ID` = `information_schema`.`t2`.`TABLE_ID`)) AND (`information_schema`.`t2`.`TABLE_SCHEMA` = `information_schema`.`t2`.`TABLE_SCHEMA`);
SELECT min(`t1`.`NUM_VERSION`) AS `min(NUM_VERSION)` FROM (SELECT `information_schema`.`t1`.`BE_ID`, `information_schema`.`t1`.`TABLE_ID`, `information_schema`.`t1`.`PARTITION_ID`, `information_schema`.`t1`.`TABLET_ID`, `information_schema`.`t1`.`NUM_VERSION`, `information_schema`.`t1`.`MAX_VERSION`, `information_schema`.`t1`.`MIN_VERSION`, `information_schema`.`t1`.`NUM_ROWSET`, `information_schema`.`t1`.`NUM_ROW`, `information_schema`.`t1`.`DATA_SIZE`, `information_schema`.`t1`.`INDEX_MEM`, `information_schema`.`t1`.`CREATE_TIME`, `information_schema`.`t1`.`STATE`, `information_schema`.`t1`.`TYPE`, `information_schema`.`t1`.`DATA_DIR`, `information_schema`.`t1`.`SHARD_ID`, `information_schema`.`t1`.`SCHEMA_HASH`, `information_schema`.`t1`.`INDEX_DISK`, `information_schema`.`t1`.`MEDIUM_TYPE`, `information_schema`.`t1`.`NUM_SEGMENT` FROM `information_schema`.`be_tablets` AS `t1`) `t1` , `information_schema`.`tables_config` AS `t2`  WHERE ((`information_schema`.`t2`.`TABLE_NAME` = 't') AND (`t1`.`TABLE_ID` = `information_schema`.`t2`.`TABLE_ID`)) AND (`information_schema`.`t2`.`TABLE_SCHEMA` = 'test_disable_compaction');
SELECT min(`information_schema`.`t1`.`NUM_VERSION`) AS `min(NUM_VERSION)` FROM `information_schema`.`be_tablets` AS `t1` , `information_schema`.`tables_config` AS `t2`  WHERE ((`information_schema`.`t2`.`TABLE_NAME` = 't') AND (`information_schema`.`t1`.`TABLE_ID` = `information_schema`.`t1`.`NUM_VERSION`)) AND (`information_schema`.`t2`.`TABLE_SCHEMA` = 'test_disable_compaction');
SELECT min(`information_schema`.`t1`.`NUM_VERSION`) AS `min(NUM_VERSION)` FROM `information_schema`.`be_tablets` AS `t1` , `information_schema`.`tables_config` AS `t2`  WHERE ((`information_schema`.`t2`.`TABLE_ID` = 't') AND (`information_schema`.`t1`.`TABLE_ID` = `information_schema`.`t2`.`TABLE_ID`)) AND (`information_schema`.`t2`.`TABLE_SCHEMA` = 'test_disable_compaction');
SELECT min(`information_schema`.`t1`.`NUM_VERSION`) AS `min(NUM_VERSION)` FROM `information_schema`.`be_tablets` AS `t1` , `information_schema`.`tables_config` AS `t2`  WHERE ((`information_schema`.`t2`.`TABLE_NAME` = 0.0) AND (`information_schema`.`t1`.`TABLE_ID` = `information_schema`.`t2`.`TABLE_ID`)) AND (`information_schema`.`t2`.`TABLE_SCHEMA` = 'test_disable_compaction');
SELECT min(`information_schema`.`t1`.`NUM_VERSION`) AS `min(NUM_VERSION)` FROM `information_schema`.`be_tablets` AS `t1` , (SELECT `information_schema`.`t2`.`TABLE_SCHEMA`, `information_schema`.`t2`.`TABLE_NAME`, `information_schema`.`t2`.`TABLE_ENGINE`, `information_schema`.`t2`.`TABLE_MODEL`, `information_schema`.`t2`.`PRIMARY_KEY`, `information_schema`.`t2`.`PARTITION_KEY`, `information_schema`.`t2`.`DISTRIBUTE_KEY`, `information_schema`.`t2`.`DISTRIBUTE_TYPE`, `information_schema`.`t2`.`DISTRIBUTE_BUCKET`, `information_schema`.`t2`.`SORT_KEY`, `information_schema`.`t2`.`PROPERTIES`, `information_schema`.`t2`.`TABLE_ID` FROM `information_schema`.`tables_config` AS `t2` EXCEPT SELECT `information_schema`.`t2`.`TABLE_SCHEMA`, `information_schema`.`t2`.`TABLE_NAME`, `information_schema`.`t2`.`TABLE_ENGINE`, `information_schema`.`t2`.`TABLE_MODEL`, `information_schema`.`t2`.`PRIMARY_KEY`, `information_schema`.`t2`.`PARTITION_KEY`, `information_schema`.`t2`.`DISTRIBUTE_KEY`, `information_schema`.`t2`.`DISTRIBUTE_TYPE`, `information_schema`.`t2`.`DISTRIBUTE_BUCKET`, `information_schema`.`t2`.`SORT_KEY`, `information_schema`.`t2`.`PROPERTIES`, `information_schema`.`t2`.`TABLE_ID` FROM `information_schema`.`tables_config` AS `t2`) `t2`  WHERE ((`t2`.`TABLE_NAME` = 't') AND (`information_schema`.`t1`.`TABLE_ID` = `t2`.`TABLE_ID`)) AND (`t2`.`TABLE_SCHEMA` = 'test_disable_compaction');
SELECT min(`information_schema`.`t1`.`NUM_VERSION`) AS `min(NUM_VERSION)` FROM `information_schema`.`be_tablets` AS `t1` , `information_schema`.`tables_config` AS `t2`;
SELECT min(`information_schema`.`t1`.`NUM_VERSION`) AS `min(NUM_VERSION)` FROM `information_schema`.`be_tablets` AS `t1` , `information_schema`.`tables_config` AS `t2`  WHERE (('test_disable_compaction' = 't') AND (`information_schema`.`t1`.`TABLE_ID` = `information_schema`.`t2`.`TABLE_ID`)) AND (`information_schema`.`t2`.`TABLE_SCHEMA` = 'test_disable_compaction');
SELECT min(`information_schema`.`t1`.`NUM_VERSION`) AS `min(NUM_VERSION)` FROM `information_schema`.`be_tablets` AS `t1` , `information_schema`.`tables_config` AS `t2`  WHERE ((`information_schema`.`t2`.`TABLE_NAME` = 't') AND (`information_schema`.`t1`.`TABLE_ID` = `information_schema`.`t2`.`TABLE_ID`)) AND (((`information_schema`.`t2`.`TABLE_NAME` = 't') AND (`information_schema`.`t1`.`TABLE_ID` = `information_schema`.`t2`.`TABLE_ID`)) AND (`information_schema`.`t2`.`TABLE_SCHEMA` = 'test_disable_compaction'));