SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)` ORDER BY sleep(3) DESC;
SELECT sleep(3) AS `sleep(3)`;
SELECT avg(sleep(3)) OVER () AS `avg(sleep(3)) OVER ()`;
SELECT sleep(CAST(3 AS JSON)->'$.a') AS `sleep(CAST(3 AS JSON)->'$.a')`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(CAST(3 AS JSON)->'$.a') AS `sleep(CAST(3 AS JSON)->'$.a')`;
SELECT sleep('') AS `sleep('')`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)` ORDER BY sleep(3) ASC;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)` GROUP BY sleep(3);
SELECT sleep(3) AS `sleep(3)` LIMIT 2;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)` ORDER BY sleep(3) DESC;
SELECT sleep(3) AS `sleep(3)`;
SELECT max(sleep(3)) OVER () AS `max(sleep(3)) OVER ()`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)` WHERE sleep(3);
SELECT sleep('') AS `sleep('')`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(0.0) AS `sleep(0.0)`;
SELECT row_number() OVER (ORDER BY sleep(3) ASC ) AS `row_number() OVER (ORDER BY sleep(3) ASC )`;
SELECT sleep(0) AS `sleep(0)`;
SELECT DISTINCT sleep(3) AS `sleep(3)`;
SELECT get_json_string(CAST((sleep(3)) AS JSON), '$.a') AS `get_json_string(CAST((sleep(3)) AS JSON), '$.a')`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT min(sleep(3)) OVER () AS `min(sleep(3)) OVER ()`;
SELECT sleep(3) AS `sleep(3)` GROUP BY sleep(3);
SELECT sleep(3) AS `sleep(3)` LIMIT 5;
SELECT sleep('0') AS `sleep('0')`;