SELECT sleep(2) AS `sleep(2)`;
SELECT (count(*)) > 2 AS `(count(*)) > 2` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = 'test_clear_stats.tbl';
SELECT sleep('test_clear_stats.tbl') AS `sleep('test_clear_stats.tbl')`;
SELECT sleep(2) AS `sleep(2)` ORDER BY sleep(2) ASC;
SELECT sleep(2) AS `sleep(2)` ORDER BY sleep(2) DESC;
SELECT DISTINCT sleep(2) AS `sleep(2)`;
SELECT sleep(2147483647) AS `sleep(2147483647)`;
SELECT sleep(FALSE) AS `sleep(FALSE)`;
SELECT sleep(2) AS `sleep(2)` GROUP BY sleep(2);
SELECT sleep(2) AS `sleep(2)`;
SELECT sleep(2) AS `sleep(2)`;
SELECT sleep(1.0E308) AS `sleep(1.0E308)`;
SELECT sleep(0) AS `sleep(0)`;
SELECT json_length(CAST((sleep(2)) AS JSON)) AS `json_length(CAST((sleep(2)) AS JSON))`;
SELECT sleep(2) AS `sleep(2)`;
SELECT min(sleep(2)) OVER () AS `min(sleep(2)) OVER ()`;
SELECT sleep(170141183460469231731687303715884105727) AS `sleep(170141183460469231731687303715884105727)`;
SELECT sleep(2) AS `sleep(2)`;
SELECT sleep(2) AS `sleep(2)`;
SELECT sleep(2) AS `sleep(2)` LIMIT 2;
SELECT sleep(9223372036854775807) AS `sleep(9223372036854775807)`;
SELECT sleep(2) AS `sleep(2)`;
SELECT sleep(2) AS `sleep(2)`;
SELECT sleep(-2147483648) AS `sleep(-2147483648)`;
SELECT sleep(2) AS `sleep(2)` WHERE sleep(2);
SELECT sleep(2) AS `sleep(2)`;
SELECT sleep(2) AS `sleep(2)`;
SELECT CAST((sleep(2)) AS JSON)->'$' AS `CAST((sleep(2)) AS JSON)->'$'`;
SELECT sleep(FALSE) AS `sleep(FALSE)`;
SELECT sleep(2) AS `sleep(2)`;
SELECT (count(*)) > 2 AS `(count(*)) > 2` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = 'test_clear_stats.tbl';
SELECT (count(*)) > 2 AS `(count(*)) > 2` FROM (SELECT `_statistics_`.`column_statistics`.`table_id`, `_statistics_`.`column_statistics`.`partition_id`, `_statistics_`.`column_statistics`.`column_name`, `_statistics_`.`column_statistics`.`db_id`, `_statistics_`.`column_statistics`.`table_name`, `_statistics_`.`column_statistics`.`partition_name`, `_statistics_`.`column_statistics`.`row_count`, `_statistics_`.`column_statistics`.`data_size`, `_statistics_`.`column_statistics`.`ndv`, `_statistics_`.`column_statistics`.`null_count`, `_statistics_`.`column_statistics`.`max`, `_statistics_`.`column_statistics`.`min`, `_statistics_`.`column_statistics`.`update_time`, `_statistics_`.`column_statistics`.`collection_size` FROM `_statistics_`.`column_statistics` UNION ALL SELECT `_statistics_`.`column_statistics`.`table_id`, `_statistics_`.`column_statistics`.`partition_id`, `_statistics_`.`column_statistics`.`column_name`, `_statistics_`.`column_statistics`.`db_id`, `_statistics_`.`column_statistics`.`table_name`, `_statistics_`.`column_statistics`.`partition_name`, `_statistics_`.`column_statistics`.`row_count`, `_statistics_`.`column_statistics`.`data_size`, `_statistics_`.`column_statistics`.`ndv`, `_statistics_`.`column_statistics`.`null_count`, `_statistics_`.`column_statistics`.`max`, `_statistics_`.`column_statistics`.`min`, `_statistics_`.`column_statistics`.`update_time`, `_statistics_`.`column_statistics`.`collection_size` FROM `_statistics_`.`column_statistics`) `column_statistics` WHERE `column_statistics`.`table_name` = 'test_clear_stats.tbl';
SELECT (count(*)) > 2 AS `(count(*)) > 2` FROM (SELECT `_statistics_`.`column_statistics`.`table_id`, `_statistics_`.`column_statistics`.`partition_id`, `_statistics_`.`column_statistics`.`column_name`, `_statistics_`.`column_statistics`.`db_id`, `_statistics_`.`column_statistics`.`table_name`, `_statistics_`.`column_statistics`.`partition_name`, `_statistics_`.`column_statistics`.`row_count`, `_statistics_`.`column_statistics`.`data_size`, `_statistics_`.`column_statistics`.`ndv`, `_statistics_`.`column_statistics`.`null_count`, `_statistics_`.`column_statistics`.`max`, `_statistics_`.`column_statistics`.`min`, `_statistics_`.`column_statistics`.`update_time`, `_statistics_`.`column_statistics`.`collection_size` FROM `_statistics_`.`column_statistics`) `column_statistics` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  WHERE `column_statistics`.`table_name` = 'test_clear_stats.tbl';
SELECT (count(*)) > 2 AS `(count(*)) > 2` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = 2;
SELECT (count(*)) > 2 AS `(count(*)) > 2` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = 'test_clear_stats.tbl';
SELECT (count(*)) > 2 AS `(count(*)) > 2` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = 'test_clear_stats.tbl' HAVING (count(*)) > 0;
SELECT (count(*)) > 2 AS `(count(*)) > 2` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = 9223372036854775807;
SELECT (count(*)) > 2 AS `(count(*)) > 2` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = 'test_clear_stats.tbl';
SELECT (count(*)) > 2 AS `(count(*)) > 2` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = 'test_clear_stats.tbl';
SELECT (count(*)) > 'test_clear_stats.tbl' AS `(count(*)) > 'test_clear_stats.tbl'` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = 'test_clear_stats.tbl';
SELECT (count(*)) > 'test_clear_stats.tbl' AS `(count(*)) > 'test_clear_stats.tbl'` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = 'test_clear_stats.tbl';
SELECT (count(*)) > 2 AS `(count(*)) > 2` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = -9223372036854775808;
SELECT (count(*)) > (count(*)) AS `(count(*)) > (count(*))` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = 'test_clear_stats.tbl';
SELECT (count(*)) > (count(*)) AS `(count(*)) > (count(*))` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = 'test_clear_stats.tbl';
SELECT (count(*)) > 2 AS `(count(*)) > 2` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = 'test_clear_stats.tbl';
SELECT (count(*)) > 2 AS `(count(*)) > 2` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = '\\';
SELECT (count(*)) > 2 AS `(count(*)) > 2` FROM (SELECT `_statistics_`.`column_statistics`.`table_id`, `_statistics_`.`column_statistics`.`partition_id`, `_statistics_`.`column_statistics`.`column_name`, `_statistics_`.`column_statistics`.`db_id`, `_statistics_`.`column_statistics`.`table_name`, `_statistics_`.`column_statistics`.`partition_name`, `_statistics_`.`column_statistics`.`row_count`, `_statistics_`.`column_statistics`.`data_size`, `_statistics_`.`column_statistics`.`ndv`, `_statistics_`.`column_statistics`.`null_count`, `_statistics_`.`column_statistics`.`max`, `_statistics_`.`column_statistics`.`min`, `_statistics_`.`column_statistics`.`update_time`, `_statistics_`.`column_statistics`.`collection_size` FROM `_statistics_`.`column_statistics`) `column_statistics` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  WHERE `column_statistics`.`table_name` = 'test_clear_stats.tbl';
SELECT 'test_clear_stats.tbl' > 2 AS `'test_clear_stats.tbl' > 2` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = 'test_clear_stats.tbl';
SELECT 'test_clear_stats.tbl' > 2 AS `'test_clear_stats.tbl' > 2` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = 'test_clear_stats.tbl';
SELECT (count(*)) > 2 AS `(count(*)) > 2` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = '9999-12-31 23:59:59';
SELECT (count(*)) > 2 AS `(count(*)) > 2` FROM `_statistics_`.`column_statistics` WHERE CAST((CAST((`_statistics_`.`column_statistics`.`table_name` = 'test_clear_stats.tbl') AS DECIMAL128(38,0))) AS DECIMAL64(1,0));
SELECT (count(*)) > 2 AS `(count(*)) > 2` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = 'test_clear_stats.tbl';
SELECT (count(*)) > 2 AS `(count(*)) > 2` FROM `_statistics_`.`column_statistics` WHERE 'test_clear_stats.tbl' = 'test_clear_stats.tbl';
SELECT (count(*)) > 2 AS `(count(*)) > 2` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = `_statistics_`.`column_statistics`.`table_name`;
SELECT 'test_clear_stats.tbl' > 2 AS `'test_clear_stats.tbl' > 2` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = 'test_clear_stats.tbl';
SELECT 'test_clear_stats.tbl' > 2 AS `'test_clear_stats.tbl' > 2` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = 'test_clear_stats.tbl';
SELECT (count(*)) > 2 AS `(count(*)) > 2` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = 2;
SELECT (count(*)) > 170141183460469231731687303715884105727 AS `(count(*)) > 170141183460469231731687303715884105727` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = 'test_clear_stats.tbl';
SELECT (count(*)) > 'test_clear_stats.tbl' AS `(count(*)) > 'test_clear_stats.tbl'` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = 'test_clear_stats.tbl';
SELECT (count(*)) > 2 AS `(count(*)) > 2` FROM `_statistics_`.`column_statistics` WHERE `_statistics_`.`column_statistics`.`table_name` = 'test_clear_stats.tbl';