SELECT count(*) AS `count(*)` FROM `srfuzz_mut_190`.`t1`;
SELECT `srfuzz_mut_190`.`t1`.`id`, `srfuzz_mut_190`.`t1`.`tags` FROM `srfuzz_mut_190`.`t1` ORDER BY `srfuzz_mut_190`.`t1`.`id` ASC;
SELECT CAST((CAST((count(*)) AS VARCHAR(1))) AS DATE) AS `CAST((CAST((count(*)) AS VARCHAR(1))) AS DATE)` FROM `srfuzz_mut_190`.`t1`;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_190`.`t1` ORDER BY count(*) ASC;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_190`.`t1`.`id`, `srfuzz_mut_190`.`t1`.`tags` FROM `srfuzz_mut_190`.`t1` UNION SELECT `srfuzz_mut_190`.`t1`.`id`, `srfuzz_mut_190`.`t1`.`tags` FROM `srfuzz_mut_190`.`t1`) `t1`;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_190`.`t1` ORDER BY count(*) ASC;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_190`.`t1`.`id`, `srfuzz_mut_190`.`t1`.`tags` FROM `srfuzz_mut_190`.`t1`) SELECT count(*) AS `count(*)` FROM `srfuzz_n1` AS t1;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_190`.`t1` HAVING (count(*)) > 0;
SELECT `srfuzz_mut_190`.`t1`.`id`, max(`srfuzz_mut_190`.`t1`.`tags`) OVER () AS `max(tags) OVER ()` FROM `srfuzz_mut_190`.`t1` ORDER BY `srfuzz_mut_190`.`t1`.`id` ASC;
SELECT `srfuzz_mut_190`.`t1`.`id`, `srfuzz_mut_190`.`t1`.`tags` FROM `srfuzz_mut_190`.`t1` WHERE `srfuzz_mut_190`.`t1`.`id` ORDER BY `srfuzz_mut_190`.`t1`.`id` ASC;
SELECT `t1`.`id`, `t1`.`tags` FROM (SELECT `srfuzz_mut_190`.`t1`.`id`, `srfuzz_mut_190`.`t1`.`tags` FROM `srfuzz_mut_190`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  ORDER BY `t1`.`id` ASC;
SELECT `t1`.`id`, `t1`.`tags` FROM (SELECT `srfuzz_mut_190`.`t1`.`id`, `srfuzz_mut_190`.`t1`.`tags` FROM `srfuzz_mut_190`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  ORDER BY `t1`.`id` ASC;
SELECT `srfuzz_mut_190`.`t1`.`id`, sum(`srfuzz_mut_190`.`t1`.`tags`) OVER () AS `sum(tags) OVER ()` FROM `srfuzz_mut_190`.`t1` ORDER BY `srfuzz_mut_190`.`t1`.`id` ASC;
SELECT `t1`.`id`, `t1`.`tags` FROM (SELECT `srfuzz_mut_190`.`t1`.`id`, `srfuzz_mut_190`.`t1`.`tags` FROM `srfuzz_mut_190`.`t1`) `t1` ORDER BY `t1`.`id` ASC;
SELECT CAST(`srfuzz_mut_190`.`t1`.`id` AS BOOLEAN) AS `CAST(id AS BOOLEAN)`, `srfuzz_mut_190`.`t1`.`tags` FROM `srfuzz_mut_190`.`t1` ORDER BY `srfuzz_mut_190`.`t1`.`id` ASC;
SELECT `srfuzz_mut_190`.`t1`.`id`, `srfuzz_mut_190`.`t1`.`tags` FROM `srfuzz_mut_190`.`t1`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_190`.`t1`.`id`, `srfuzz_mut_190`.`t1`.`tags` FROM `srfuzz_mut_190`.`t1`) SELECT `t1`.`id`, `t1`.`tags` FROM `srfuzz_n1` AS t1 ORDER BY `t1`.`id` ASC;
SELECT `srfuzz_mut_190`.`t1`.`id`, `srfuzz_mut_190`.`t1`.`tags` FROM `srfuzz_mut_190`.`t1` GROUP BY `srfuzz_mut_190`.`t1`.`id`, `srfuzz_mut_190`.`t1`.`tags` ORDER BY `srfuzz_mut_190`.`t1`.`id` ASC;
SELECT `srfuzz_mut_190`.`t1`.`id`, `srfuzz_mut_190`.`t1`.`tags` FROM `srfuzz_mut_190`.`t1` WHERE `srfuzz_mut_190`.`t1`.`tags` ORDER BY `srfuzz_mut_190`.`t1`.`id` ASC;
SELECT `t1`.`id`, `t1`.`tags` FROM (SELECT `srfuzz_mut_190`.`t1`.`id`, `srfuzz_mut_190`.`t1`.`tags` FROM `srfuzz_mut_190`.`t1` EXCEPT SELECT `srfuzz_mut_190`.`t1`.`id`, `srfuzz_mut_190`.`t1`.`tags` FROM `srfuzz_mut_190`.`t1`) `t1` ORDER BY `t1`.`id` ASC;
SELECT `t1`.`id`, `t1`.`tags` FROM (SELECT `srfuzz_mut_190`.`t1`.`id`, `srfuzz_mut_190`.`t1`.`tags` FROM `srfuzz_mut_190`.`t1` INTERSECT SELECT `srfuzz_mut_190`.`t1`.`id`, `srfuzz_mut_190`.`t1`.`tags` FROM `srfuzz_mut_190`.`t1`) `t1` ORDER BY `t1`.`id` ASC;
SELECT `t1`.`id`, `t1`.`tags` FROM (SELECT `srfuzz_mut_190`.`t1`.`id`, `srfuzz_mut_190`.`t1`.`tags` FROM `srfuzz_mut_190`.`t1` UNION ALL SELECT `srfuzz_mut_190`.`t1`.`id`, `srfuzz_mut_190`.`t1`.`tags` FROM `srfuzz_mut_190`.`t1`) `t1` ORDER BY `t1`.`id` ASC;