SELECT 'Query 1: Validate that invalid paths return NULL' AS `test_description`;
SELECT 'Query 2: Validate invalid paths with get_variant_int' AS `test_description`;
SELECT 'Query 3: Validate array access on non-array types returns NULL' AS `test_description`;
SELECT 'Query 4: Validate object field access on non-object types returns NULL' AS `test_description`;
SELECT 'Query 5: Validate nested path on scalar values returns NULL' AS `test_description`;
SELECT 'Query 6: Validate CAST of non-numeric string to INT' AS `test_description`;
SELECT 'Query 7: Validate numeric overflow handling for SMALLINT' AS `test_description`;
SELECT 'Query 8: Validate CAST of complex types to primitives fails gracefully' AS `test_description`;
SELECT 'Query 9: Verify variant_typeof for various data types' AS `test_description`;
SELECT 'Query 10: Combined error scenarios' AS `test_description`;
SELECT DISTINCT 'Query 1: Validate that invalid paths return NULL' AS `test_description`;
SELECT DISTINCT 'Query 1: Validate that invalid paths return NULL' AS `test_description`;
SELECT json_length(CAST('Query 1: Validate that invalid paths return NULL' AS JSON)) AS `test_description`;
SELECT get_json_string(CAST('Query 1: Validate that invalid paths return NULL' AS JSON), '$.a') AS `test_description`;
SELECT 'Query 1: Validate that invalid paths return NULL' AS `test_description` LIMIT 1, 5;
SELECT 'Query 1: Validate that invalid paths return NULL' AS `test_description` ORDER BY 'Query 1: Validate that invalid paths return NULL' ASC;
SELECT 'Query 1: Validate that invalid paths return NULL' AS `test_description` WHERE 'Query 4: Validate object field access on non-object types returns NULL';
SELECT 'Query 1: Validate that invalid paths return NULL' AS `test_description` WHERE 'Query 1: Validate that invalid paths return NULL';
SELECT 'Query 1: Validate that invalid paths return NULL' AS `test_description` ORDER BY 'Query 1: Validate that invalid paths return NULL' ASC;
SELECT 'Query 2: Validate invalid paths with get_variant_int' AS `test_description` GROUP BY 'Query 2: Validate invalid paths with get_variant_int';
SELECT 'Query 2: Validate invalid paths with get_variant_int' AS `test_description` WHERE 'Query 3: Validate array access on non-array types returns NULL';
SELECT DISTINCT 'Query 2: Validate invalid paths with get_variant_int' AS `test_description`;
SELECT json_length(CAST('Query 2: Validate invalid paths with get_variant_int' AS JSON)) AS `test_description`;
SELECT count('Query 2: Validate invalid paths with get_variant_int') OVER () AS `test_description`;
SELECT 'Query 2: Validate invalid paths with get_variant_int' AS `test_description` LIMIT 7, 5;
SELECT 'Query 2: Validate invalid paths with get_variant_int' AS `test_description` LIMIT 5;
SELECT get_json_string(CAST('Query 2: Validate invalid paths with get_variant_int' AS JSON), '$.a') AS `test_description`;
SELECT 'Query 2: Validate invalid paths with get_variant_int' AS `test_description` LIMIT 7, 5;
SELECT get_json_string(CAST('Query 2: Validate invalid paths with get_variant_int' AS JSON), '$.a') AS `test_description`;
SELECT json_length(CAST('Query 3: Validate array access on non-array types returns NULL' AS JSON)) AS `test_description`;
SELECT 'Query 3: Validate array access on non-array types returns NULL' AS `test_description` ORDER BY 'Query 3: Validate array access on non-array types returns NULL' DESC;
SELECT json_query(CAST('Query 3: Validate array access on non-array types returns NULL' AS JSON), '$.a') AS `test_description`;
SELECT 'Query 3: Validate array access on non-array types returns NULL' AS `test_description` WHERE 'Query 10: Combined error scenarios';
SELECT avg('Query 3: Validate array access on non-array types returns NULL') OVER () AS `test_description`;
SELECT 'Query 3: Validate array access on non-array types returns NULL' AS `test_description` LIMIT 7, 2;
SELECT 'Query 3: Validate array access on non-array types returns NULL' AS `test_description` ORDER BY 'Query 3: Validate array access on non-array types returns NULL' ASC;
SELECT count('Query 4: Validate object field access on non-object types returns NULL') OVER () AS `test_description`;
SELECT 'Query 4: Validate object field access on non-object types returns NULL' AS `test_description` LIMIT 7, 5;
SELECT 'Query 4: Validate object field access on non-object types returns NULL' AS `test_description` GROUP BY 'Query 4: Validate object field access on non-object types returns NULL';
SELECT avg('Query 4: Validate object field access on non-object types returns NULL') OVER () AS `test_description`;
SELECT 'Query 4: Validate object field access on non-object types returns NULL' AS `test_description` GROUP BY 'Query 4: Validate object field access on non-object types returns NULL';
SELECT 'Query 4: Validate object field access on non-object types returns NULL' AS `test_description` LIMIT 1, 100;
SELECT 'Query 4: Validate object field access on non-object types returns NULL' AS `test_description` GROUP BY 'Query 4: Validate object field access on non-object types returns NULL';
SELECT 'Query 4: Validate object field access on non-object types returns NULL' AS `test_description` ORDER BY 'Query 4: Validate object field access on non-object types returns NULL' DESC;
SELECT 'Query 4: Validate object field access on non-object types returns NULL' AS `test_description` WHERE 'Query 6: Validate CAST of non-numeric string to INT';
SELECT 'Query 4: Validate object field access on non-object types returns NULL' AS `test_description` ORDER BY 'Query 4: Validate object field access on non-object types returns NULL' DESC;
SELECT 'Query 4: Validate object field access on non-object types returns NULL' AS `test_description` WHERE 'Query 2: Validate invalid paths with get_variant_int';
SELECT 'Query 4: Validate object field access on non-object types returns NULL' AS `test_description` WHERE 'Query 2: Validate invalid paths with get_variant_int';
SELECT get_json_string(CAST('Query 5: Validate nested path on scalar values returns NULL' AS JSON), '$.a') AS `test_description`;
SELECT 'Query 5: Validate nested path on scalar values returns NULL' AS `test_description` LIMIT 0;
SELECT avg('Query 5: Validate nested path on scalar values returns NULL') OVER () AS `test_description`;
SELECT 'Query 5: Validate nested path on scalar values returns NULL' AS `test_description` LIMIT 2;
SELECT 'Query 5: Validate nested path on scalar values returns NULL' AS `test_description` WHERE 'Query 4: Validate object field access on non-object types returns NULL';
SELECT json_query(CAST('Query 5: Validate nested path on scalar values returns NULL' AS JSON), '$.a') AS `test_description`;
SELECT 'Query 5: Validate nested path on scalar values returns NULL' AS `test_description` LIMIT 1, 0;
SELECT 'Query 5: Validate nested path on scalar values returns NULL' AS `test_description` ORDER BY 'Query 5: Validate nested path on scalar values returns NULL' ASC;
SELECT DISTINCT 'Query 5: Validate nested path on scalar values returns NULL' AS `test_description`;
SELECT json_length(CAST('Query 5: Validate nested path on scalar values returns NULL' AS JSON)) AS `test_description`;
SELECT CAST('Query 5: Validate nested path on scalar values returns NULL' AS DATE) AS `test_description`;
SELECT 'Query 5: Validate nested path on scalar values returns NULL' AS `test_description` ORDER BY 'Query 5: Validate nested path on scalar values returns NULL' ASC;
SELECT json_query(CAST('Query 6: Validate CAST of non-numeric string to INT' AS JSON), '$.a') AS `test_description`;
SELECT 'Query 6: Validate CAST of non-numeric string to INT' AS `test_description` GROUP BY 'Query 6: Validate CAST of non-numeric string to INT';
SELECT CAST('Query 6: Validate CAST of non-numeric string to INT' AS DATETIME) AS `test_description`;
SELECT 'Query 6: Validate CAST of non-numeric string to INT' AS `test_description` LIMIT 2;
SELECT json_length(CAST('Query 6: Validate CAST of non-numeric string to INT' AS JSON)) AS `test_description`;
SELECT 'Query 6: Validate CAST of non-numeric string to INT' AS `test_description` ORDER BY 'Query 6: Validate CAST of non-numeric string to INT' ASC;
SELECT sum('Query 6: Validate CAST of non-numeric string to INT') OVER () AS `test_description`;
SELECT 'Query 6: Validate CAST of non-numeric string to INT' AS `test_description` GROUP BY 'Query 6: Validate CAST of non-numeric string to INT';
SELECT DISTINCT 'Query 6: Validate CAST of non-numeric string to INT' AS `test_description`;
SELECT CAST('Query 7: Validate numeric overflow handling for SMALLINT' AS JSON)->'$' AS `test_description`;
SELECT 'Query 7: Validate numeric overflow handling for SMALLINT' AS `test_description` ORDER BY 'Query 7: Validate numeric overflow handling for SMALLINT' ASC NULLS LAST;
SELECT DISTINCT 'Query 7: Validate numeric overflow handling for SMALLINT' AS `test_description`;
SELECT 'Query 7: Validate numeric overflow handling for SMALLINT' AS `test_description` ORDER BY 'Query 7: Validate numeric overflow handling for SMALLINT' DESC;
SELECT 'Query 7: Validate numeric overflow handling for SMALLINT' AS `test_description` GROUP BY 'Query 7: Validate numeric overflow handling for SMALLINT';
SELECT 'Query 7: Validate numeric overflow handling for SMALLINT' AS `test_description` GROUP BY 'Query 7: Validate numeric overflow handling for SMALLINT';
SELECT 'Query 7: Validate numeric overflow handling for SMALLINT' AS `test_description` ORDER BY 'Query 7: Validate numeric overflow handling for SMALLINT' DESC;
SELECT sum('Query 7: Validate numeric overflow handling for SMALLINT') OVER () AS `test_description`;
SELECT 'Query 7: Validate numeric overflow handling for SMALLINT' AS `test_description` LIMIT 0;
SELECT 'Query 7: Validate numeric overflow handling for SMALLINT' AS `test_description` WHERE 'Query 7: Validate numeric overflow handling for SMALLINT';
SELECT 'Query 8: Validate CAST of complex types to primitives fails gracefully' AS `test_description` ORDER BY 'Query 8: Validate CAST of complex types to primitives fails gracefully' ASC;
SELECT CAST((CAST('Query 8: Validate CAST of complex types to primitives fails gracefully' AS DECIMAL128(38,38))) AS DOUBLE) AS `test_description`;
SELECT 'Query 8: Validate CAST of complex types to primitives fails gracefully' AS `test_description` ORDER BY 'Query 8: Validate CAST of complex types to primitives fails gracefully' DESC;
SELECT CAST((CAST('Query 8: Validate CAST of complex types to primitives fails gracefully' AS DECIMAL128(38,0))) AS FLOAT) AS `test_description`;
SELECT 'Query 8: Validate CAST of complex types to primitives fails gracefully' AS `test_description` WHERE 'Query 7: Validate numeric overflow handling for SMALLINT';
SELECT sum('Query 8: Validate CAST of complex types to primitives fails gracefully') OVER () AS `test_description`;
SELECT max('Query 8: Validate CAST of complex types to primitives fails gracefully') OVER () AS `test_description`;
SELECT get_json_string(CAST('Query 8: Validate CAST of complex types to primitives fails gracefully' AS JSON), '$.a') AS `test_description`;
SELECT CAST('Query 8: Validate CAST of complex types to primitives fails gracefully' AS JSON)->'$' AS `test_description`;
SELECT DISTINCT 'Query 9: Verify variant_typeof for various data types' AS `test_description`;
SELECT 'Query 9: Verify variant_typeof for various data types' AS `test_description` LIMIT 100;
SELECT avg('Query 9: Verify variant_typeof for various data types') OVER () AS `test_description`;
SELECT CAST((CAST((CAST('Query 9: Verify variant_typeof for various data types' AS INT)) AS BOOLEAN)) AS VARCHAR) AS `test_description`;
SELECT 'Query 9: Verify variant_typeof for various data types' AS `test_description` LIMIT 1;
SELECT DISTINCT 'Query 9: Verify variant_typeof for various data types' AS `test_description`;
SELECT 'Query 9: Verify variant_typeof for various data types' AS `test_description` ORDER BY 'Query 9: Verify variant_typeof for various data types' DESC;
SELECT max('Query 9: Verify variant_typeof for various data types') OVER () AS `test_description`;
SELECT min('Query 9: Verify variant_typeof for various data types') OVER () AS `test_description`;
SELECT 'Query 9: Verify variant_typeof for various data types' AS `test_description` ORDER BY 'Query 9: Verify variant_typeof for various data types' ASC;
SELECT 'Query 9: Verify variant_typeof for various data types' AS `test_description` LIMIT 1;
SELECT 'Query 9: Verify variant_typeof for various data types' AS `test_description` WHERE 'Query 7: Validate numeric overflow handling for SMALLINT';
SELECT 'Query 9: Verify variant_typeof for various data types' AS `test_description` GROUP BY 'Query 9: Verify variant_typeof for various data types';
SELECT DISTINCT 'Query 10: Combined error scenarios' AS `test_description`;
SELECT DISTINCT 'Query 10: Combined error scenarios' AS `test_description`;
SELECT 'Query 10: Combined error scenarios' AS `test_description` LIMIT 7, 0;
SELECT 'Query 10: Combined error scenarios' AS `test_description` LIMIT 100;
SELECT 'Query 10: Combined error scenarios' AS `test_description` LIMIT 100;
SELECT DISTINCT 'Query 10: Combined error scenarios' AS `test_description`;