SELECT `srfuzz_mut_86`.`mv1`.`k`, `srfuzz_mut_86`.`mv1`.`cnt` FROM `srfuzz_mut_86`.`mv1` ORDER BY `srfuzz_mut_86`.`mv1`.`k` ASC;
SELECT `srfuzz_mut_86`.`mv1`.`k`, `srfuzz_mut_86`.`mv1`.`cnt` FROM `srfuzz_mut_86`.`mv1`;
SELECT `srfuzz_mut_86`.`mv1`.`k`, `srfuzz_mut_86`.`mv1`.`cnt` FROM `srfuzz_mut_86`.`mv1` GROUP BY `srfuzz_mut_86`.`mv1`.`k`, `srfuzz_mut_86`.`mv1`.`cnt` ORDER BY `srfuzz_mut_86`.`mv1`.`k` ASC;
SELECT `mv1`.`k`, `mv1`.`cnt` FROM (SELECT `srfuzz_mut_86`.`mv1`.`k`, `srfuzz_mut_86`.`mv1`.`cnt` FROM `srfuzz_mut_86`.`mv1` UNION ALL SELECT `srfuzz_mut_86`.`mv1`.`k`, `srfuzz_mut_86`.`mv1`.`cnt` FROM `srfuzz_mut_86`.`mv1`) `mv1` ORDER BY `mv1`.`k` ASC;
SELECT `srfuzz_mut_86`.`mv1`.`k`, `srfuzz_mut_86`.`mv1`.`cnt` FROM `srfuzz_mut_86`.`mv1`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_86`.`mv1`.`k`, `srfuzz_mut_86`.`mv1`.`cnt` FROM `srfuzz_mut_86`.`mv1`) SELECT `mv1`.`k`, `mv1`.`cnt` FROM `srfuzz_n1` AS mv1 ORDER BY `mv1`.`k` ASC;
SELECT DISTINCT `srfuzz_mut_86`.`mv1`.`k`, `srfuzz_mut_86`.`mv1`.`cnt` FROM `srfuzz_mut_86`.`mv1` ORDER BY `srfuzz_mut_86`.`mv1`.`k` ASC;
SELECT `srfuzz_mut_86`.`mv1`.`k`, `srfuzz_mut_86`.`mv1`.`cnt` FROM `srfuzz_mut_86`.`mv1` WHERE `srfuzz_mut_86`.`mv1`.`cnt` ORDER BY `srfuzz_mut_86`.`mv1`.`k` ASC;
SELECT `mv1`.`k`, `mv1`.`cnt` FROM (SELECT `srfuzz_mut_86`.`mv1`.`k`, `srfuzz_mut_86`.`mv1`.`cnt` FROM `srfuzz_mut_86`.`mv1` INTERSECT SELECT `srfuzz_mut_86`.`mv1`.`k`, `srfuzz_mut_86`.`mv1`.`cnt` FROM `srfuzz_mut_86`.`mv1`) `mv1` ORDER BY `mv1`.`k` ASC;
SELECT max(`srfuzz_mut_86`.`mv1`.`k`) OVER (PARTITION BY `srfuzz_mut_86`.`mv1`.`cnt` ) AS `max(k) OVER (PARTITION BY cnt )`, `srfuzz_mut_86`.`mv1`.`cnt` FROM `srfuzz_mut_86`.`mv1` ORDER BY `srfuzz_mut_86`.`mv1`.`k` ASC;
SELECT DISTINCT `srfuzz_mut_86`.`mv1`.`k`, `srfuzz_mut_86`.`mv1`.`cnt` FROM `srfuzz_mut_86`.`mv1` ORDER BY `srfuzz_mut_86`.`mv1`.`k` ASC;
SELECT `srfuzz_mut_86`.`mv1`.`k`, `srfuzz_mut_86`.`mv1`.`cnt` FROM `srfuzz_mut_86`.`mv1` ORDER BY `srfuzz_mut_86`.`mv1`.`k` ASC  LIMIT 7, 5;