SELECT json_pretty('{"a": 1, "b": 2}') AS `json_pretty('{"a": 1, "b": 2}')`;
SELECT json_pretty('[1, 2, 3]') AS `json_pretty('[1, 2, 3]')`;
SELECT json_pretty('{"a": true, "b": null, "c": "string"}') AS `json_pretty('{"a": true, "b": null, "c": "string"}')`;
SELECT json_pretty('{"level1": {"level2": {"level3": "value"}}}') AS `json_pretty('{"level1": {"level2": {"level3": "value"}}}')`;
SELECT json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]') AS `json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]')`;
SELECT json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}') AS `json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}')`;
SELECT json_pretty('{}') AS `json_pretty('{}')`;
SELECT json_pretty('[]') AS `json_pretty('[]')`;
SELECT json_pretty('{"int": 123, "float": 12.34}') AS `json_pretty('{"int": 123, "float": 12.34}')`;
SELECT `srfuzz_mut_684`.`json_pretty_test_table`.`id`, json_pretty(`srfuzz_mut_684`.`json_pretty_test_table`.`data`) AS `json_pretty(data)` FROM `srfuzz_mut_684`.`json_pretty_test_table` ORDER BY `srfuzz_mut_684`.`json_pretty_test_table`.`id` ASC;
SELECT json_pretty(0) AS `json_pretty(0)`;
SELECT CAST((CAST((CAST((json_pretty('{"a": 1, "b": 2}')) AS VARCHAR(1))) AS DECIMAL128(38,37))) AS SMALLINT) AS `CAST((CAST((CAST((json_pretty('{"a": 1, "b": 2}')) AS VARCHAR(1))) AS DECIMAL128(38,37))) AS SMALLINT)`;
SELECT json_pretty('{"a": 1, "b": 2}') AS `json_pretty('{"a": 1, "b": 2}')` LIMIT 1, 0;
SELECT json_pretty(9223372036854775807) AS `json_pretty(9223372036854775807)`;
SELECT json_pretty(-2147483648) AS `json_pretty(-2147483648)`;
SELECT json_pretty(-2147483648) AS `json_pretty(-2147483648)`;
SELECT json_pretty('{"a": 1, "b": 2}') AS `json_pretty('{"a": 1, "b": 2}')` LIMIT 7, 0;
SELECT json_pretty(CAST((CAST('{"a": 1, "b": 2}' AS BIGINT)) AS DOUBLE)) AS `json_pretty(CAST((CAST('{"a": 1, "b": 2}' AS BIGINT)) AS DOUBLE))`;
SELECT json_pretty('{"a": 1, "b": 2}') AS `json_pretty('{"a": 1, "b": 2}')`;
SELECT json_pretty(json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]')) AS `json_pretty(json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]'))`;
SELECT json_pretty('{"a": 1, "b": 2}') AS `json_pretty('{"a": 1, "b": 2}')` GROUP BY json_pretty('{"a": 1, "b": 2}');
SELECT json_pretty('0') AS `json_pretty('0')`;
SELECT json_pretty('{"a": 1, "b": 2}') AS `json_pretty('{"a": 1, "b": 2}')`;
SELECT json_pretty(CAST('{"a": 1, "b": 2}' AS JSON)->'k') AS `json_pretty(CAST('{"a": 1, "b": 2}' AS JSON)->'k')`;
SELECT json_pretty(json_pretty('{"level1": {"level2": {"level3": "value"}}}')) AS `json_pretty(json_pretty('{"level1": {"level2": {"level3": "value"}}}'))`;
SELECT json_pretty(NULL) AS `json_pretty(NULL)`;
SELECT json_pretty('{"a": 1, "b": 2}') AS `json_pretty('{"a": 1, "b": 2}')`;
SELECT json_pretty(json_pretty('{"a": 1, "b": 2}')) AS `json_pretty(json_pretty('{"a": 1, "b": 2}'))`;
SELECT json_pretty(0) AS `json_pretty(0)`;
SELECT json_pretty('{"a": 1, "b": 2}') AS `json_pretty('{"a": 1, "b": 2}')`;
SELECT json_pretty('{"a": 1, "b": 2}') AS `json_pretty('{"a": 1, "b": 2}')` ORDER BY json_pretty('{"a": 1, "b": 2}') ASC NULLS LAST;
SELECT json_pretty(json_pretty('{"a": 1, "b": 2}')) AS `json_pretty(json_pretty('{"a": 1, "b": 2}'))`;
SELECT json_pretty(1) AS `json_pretty(1)`;
SELECT json_pretty('{"a": 1, "b": 2}') AS `json_pretty('{"a": 1, "b": 2}')`;
SELECT json_pretty('{"a": 1, "b": 2}') AS `json_pretty('{"a": 1, "b": 2}')`;
SELECT json_pretty(0.0) AS `json_pretty(0.0)`;
SELECT json_pretty('{"a": 1, "b": 2}') AS `json_pretty('{"a": 1, "b": 2}')`;
SELECT json_pretty(json_pretty('{"a": 1, "b": 2}')) AS `json_pretty(json_pretty('{"a": 1, "b": 2}'))`;
SELECT json_pretty(json_pretty('{"a": 1, "b": 2}')) AS `json_pretty(json_pretty('{"a": 1, "b": 2}'))`;
SELECT json_pretty(json_pretty('{"a": 1, "b": 2}')) AS `json_pretty(json_pretty('{"a": 1, "b": 2}'))`;
SELECT json_pretty('{"a": 1, "b": 2}') AS `json_pretty('{"a": 1, "b": 2}')` LIMIT 5;
SELECT json_pretty('{"a": 1, "b": 2}') AS `json_pretty('{"a": 1, "b": 2}')`;
SELECT json_pretty(json_pretty('{"a": 1, "b": 2}')) AS `json_pretty(json_pretty('{"a": 1, "b": 2}'))`;
SELECT json_pretty(json_pretty('{"a": 1, "b": 2}')) AS `json_pretty(json_pretty('{"a": 1, "b": 2}'))`;
SELECT json_pretty('[1, 2, 3]') AS `json_pretty('[1, 2, 3]')` WHERE json_pretty('[1, 2, 3]');
SELECT json_pretty('[1, 2, 3]') AS `json_pretty('[1, 2, 3]')` GROUP BY json_pretty('[1, 2, 3]');
SELECT json_pretty('0000-00-00') AS `json_pretty('0000-00-00')`;
SELECT json_pretty(json_pretty('[1, 2, 3]')) AS `json_pretty(json_pretty('[1, 2, 3]'))`;
SELECT json_pretty('\\') AS `json_pretty('\\')`;
SELECT json_pretty(CAST((CAST((CAST('[1, 2, 3]' AS DECIMAL128(38,38))) AS DECIMAL128(38,37))) AS BIGINT)) AS `json_pretty(CAST((CAST((CAST('[1, 2, 3]' AS DECIMAL128(38,38))) AS DECIMAL128(38,37))) AS BIGINT))`;
SELECT json_pretty('0000-00-00') AS `json_pretty('0000-00-00')`;
SELECT json_pretty(json_pretty('{"int": 123, "float": 12.34}')) AS `json_pretty(json_pretty('{"int": 123, "float": 12.34}'))`;
SELECT json_pretty('[1, 2, 3]') AS `json_pretty('[1, 2, 3]')` GROUP BY json_pretty('[1, 2, 3]');
SELECT json_pretty('[1, 2, 3]') AS `json_pretty('[1, 2, 3]')`;
SELECT json_pretty(json_pretty('[1, 2, 3]')) AS `json_pretty(json_pretty('[1, 2, 3]'))`;
SELECT json_pretty(json_length(CAST('[1, 2, 3]' AS JSON))) AS `json_pretty(json_length(CAST('[1, 2, 3]' AS JSON)))`;
SELECT DISTINCT json_pretty('[1, 2, 3]') AS `json_pretty('[1, 2, 3]')`;
SELECT json_pretty(repeat('x', 65536)) AS `json_pretty(repeat('x', 65536))`;
SELECT json_pretty(json_pretty('[1, 2, 3]')) AS `json_pretty(json_pretty('[1, 2, 3]'))`;
SELECT json_pretty('[1, 2, 3]') AS `json_pretty('[1, 2, 3]')` WHERE json_pretty('{"level1": {"level2": {"level3": "value"}}}');
SELECT json_pretty('0') AS `json_pretty('0')`;
SELECT json_pretty('[1, 2, 3]') AS `json_pretty('[1, 2, 3]')`;
SELECT json_pretty(FALSE) AS `json_pretty(FALSE)`;
SELECT json_pretty(0.0) AS `json_pretty(0.0)`;
SELECT json_pretty(json_pretty('[1, 2, 3]')) AS `json_pretty(json_pretty('[1, 2, 3]'))`;
SELECT json_pretty(1) AS `json_pretty(1)`;
SELECT json_pretty('[1, 2, 3]') AS `json_pretty('[1, 2, 3]')` ORDER BY json_pretty('[1, 2, 3]') ASC;
SELECT json_pretty('[1, 2, 3]') AS `json_pretty('[1, 2, 3]')` GROUP BY json_pretty('[1, 2, 3]');
SELECT json_pretty(FALSE) AS `json_pretty(FALSE)`;
SELECT json_pretty(CAST('[1, 2, 3]' AS JSON)->'$') AS `json_pretty(CAST('[1, 2, 3]' AS JSON)->'$')`;
SELECT json_pretty('%') AS `json_pretty('%')`;
SELECT json_pretty(2147483647) AS `json_pretty(2147483647)`;
SELECT json_pretty('[1, 2, 3]') AS `json_pretty('[1, 2, 3]')` WHERE '[1, 2, 3]';
SELECT json_pretty(repeat('x', 65536)) AS `json_pretty(repeat('x', 65536))`;
SELECT json_pretty(-9223372036854775808) AS `json_pretty(-9223372036854775808)`;
SELECT CAST((json_pretty('[1, 2, 3]')) AS JSON)->'$' AS `CAST((json_pretty('[1, 2, 3]')) AS JSON)->'$'`;
SELECT json_pretty('0000-00-00') AS `json_pretty('0000-00-00')`;
SELECT json_pretty(json_query(CAST('{"a": true, "b": null, "c": "string"}' AS JSON), '$.a')) AS `json_pretty(json_query(CAST('{"a": true, "b": null, "c": "string"}' AS JSON), '$.a'))`;
SELECT json_pretty(json_pretty('{"a": true, "b": null, "c": "string"}')) AS `json_pretty(json_pretty('{"a": true, "b": null, "c": "string"}'))`;
SELECT json_pretty('{"a": true, "b": null, "c": "string"}') AS `json_pretty('{"a": true, "b": null, "c": "string"}')`;
SELECT json_pretty(TRUE) AS `json_pretty(TRUE)`;
SELECT json_pretty('{"a": true, "b": null, "c": "string"}') AS `json_pretty('{"a": true, "b": null, "c": "string"}')` GROUP BY json_pretty('{"a": true, "b": null, "c": "string"}');
SELECT json_pretty('[]') AS `json_pretty('[]')`;
SELECT json_pretty('{"a": true, "b": null, "c": "string"}') AS `json_pretty('{"a": true, "b": null, "c": "string"}')` GROUP BY json_pretty('{"a": true, "b": null, "c": "string"}');
SELECT json_pretty('') AS `json_pretty('')`;
SELECT DISTINCT json_pretty('{"a": true, "b": null, "c": "string"}') AS `json_pretty('{"a": true, "b": null, "c": "string"}')`;
SELECT json_pretty('{"a": true, "b": null, "c": "string"}') AS `json_pretty('{"a": true, "b": null, "c": "string"}')` ORDER BY json_pretty('{"a": true, "b": null, "c": "string"}') ASC;
SELECT json_pretty(0.0) AS `json_pretty(0.0)`;
SELECT json_pretty(json_pretty('{"a": true, "b": null, "c": "string"}')) AS `json_pretty(json_pretty('{"a": true, "b": null, "c": "string"}'))`;
SELECT json_pretty(-1) AS `json_pretty(-1)`;
SELECT json_pretty(json_pretty('{"a": true, "b": null, "c": "string"}')) AS `json_pretty(json_pretty('{"a": true, "b": null, "c": "string"}'))`;
SELECT json_pretty(json_pretty('{"a": true, "b": null, "c": "string"}')) AS `json_pretty(json_pretty('{"a": true, "b": null, "c": "string"}'))`;
SELECT json_pretty('{"a": true, "b": null, "c": "string"}') AS `json_pretty('{"a": true, "b": null, "c": "string"}')` GROUP BY json_pretty('{"a": true, "b": null, "c": "string"}');
SELECT DISTINCT json_pretty('{"a": true, "b": null, "c": "string"}') AS `json_pretty('{"a": true, "b": null, "c": "string"}')`;
SELECT json_pretty(json_pretty('{"a": true, "b": null, "c": "string"}')) AS `json_pretty(json_pretty('{"a": true, "b": null, "c": "string"}'))`;
SELECT json_pretty('{"level1": {"level2": {"level3": "value"}}}') AS `json_pretty('{"level1": {"level2": {"level3": "value"}}}')`;
SELECT json_pretty(9223372036854775807) AS `json_pretty(9223372036854775807)`;
SELECT json_pretty('{"a": true, "b": null, "c": "string"}') AS `json_pretty('{"a": true, "b": null, "c": "string"}')` LIMIT 1, 0;
SELECT json_pretty('{"a": true, "b": null, "c": "string"}') AS `json_pretty('{"a": true, "b": null, "c": "string"}')` GROUP BY json_pretty('{"a": true, "b": null, "c": "string"}');
SELECT json_pretty(json_pretty('{"a": true, "b": null, "c": "string"}')) AS `json_pretty(json_pretty('{"a": true, "b": null, "c": "string"}'))`;
SELECT json_pretty('{"a": true, "b": null, "c": "string"}') AS `json_pretty('{"a": true, "b": null, "c": "string"}')` WHERE '{"int": 123, "float": 12.34}';
SELECT json_pretty(json_pretty('{"level1": {"level2": {"level3": "value"}}}')) AS `json_pretty(json_pretty('{"level1": {"level2": {"level3": "value"}}}'))`;
SELECT json_pretty(json_pretty('{"a": true, "b": null, "c": "string"}')) AS `json_pretty(json_pretty('{"a": true, "b": null, "c": "string"}'))`;
SELECT json_pretty(json_pretty('{"a": true, "b": null, "c": "string"}')) AS `json_pretty(json_pretty('{"a": true, "b": null, "c": "string"}'))`;
SELECT CAST((CAST((CAST((json_pretty('{"a": true, "b": null, "c": "string"}')) AS DECIMAL128(38,0))) AS TINYINT)) AS LARGEINT) AS `CAST((CAST((CAST((json_pretty('{"a": true, "b": null, "c": "string"}')) AS DECIMAL128(38,0))) AS TINYINT)) AS LARGEINT)`;
SELECT json_pretty(json_pretty('{"a": true, "b": null, "c": "string"}')) AS `json_pretty(json_pretty('{"a": true, "b": null, "c": "string"}'))`;
SELECT json_pretty('') AS `json_pretty('')`;
SELECT json_pretty(NULL) AS `json_pretty(NULL)`;
SELECT CAST((json_pretty('{"a": true, "b": null, "c": "string"}')) AS JSON)->'$.a' AS `CAST((json_pretty('{"a": true, "b": null, "c": "string"}')) AS JSON)->'$.a'`;
SELECT json_pretty('{"a": true, "b": null, "c": "string"}') AS `json_pretty('{"a": true, "b": null, "c": "string"}')`;
SELECT json_pretty('{"a": true, "b": null, "c": "string"}') AS `json_pretty('{"a": true, "b": null, "c": "string"}')`;
SELECT json_pretty(json_pretty('{"level1": {"level2": {"level3": "value"}}}')) AS `json_pretty(json_pretty('{"level1": {"level2": {"level3": "value"}}}'))`;
SELECT json_pretty('{"level1": {"level2": {"level3": "value"}}}') AS `json_pretty('{"level1": {"level2": {"level3": "value"}}}')`;
SELECT json_pretty('[]') AS `json_pretty('[]')`;
SELECT json_pretty('{"level1": {"level2": {"level3": "value"}}}') AS `json_pretty('{"level1": {"level2": {"level3": "value"}}}')` GROUP BY json_pretty('{"level1": {"level2": {"level3": "value"}}}');
SELECT json_pretty(NULL) AS `json_pretty(NULL)`;
SELECT json_pretty('{"level1": {"level2": {"level3": "value"}}}') AS `json_pretty('{"level1": {"level2": {"level3": "value"}}}')` WHERE json_pretty('{"a": true, "b": null, "c": "string"}');
SELECT json_pretty(-9223372036854775808) AS `json_pretty(-9223372036854775808)`;
SELECT json_pretty('{"level1": {"level2": {"level3": "value"}}}') AS `json_pretty('{"level1": {"level2": {"level3": "value"}}}')`;
SELECT json_pretty(9223372036854775807) AS `json_pretty(9223372036854775807)`;
SELECT json_pretty('{"level1": {"level2": {"level3": "value"}}}') AS `json_pretty('{"level1": {"level2": {"level3": "value"}}}')`;
SELECT json_pretty('{"level1": {"level2": {"level3": "value"}}}') AS `json_pretty('{"level1": {"level2": {"level3": "value"}}}')` LIMIT 7, 1;
SELECT json_pretty('{"level1": {"level2": {"level3": "value"}}}') AS `json_pretty('{"level1": {"level2": {"level3": "value"}}}')`;
SELECT DISTINCT json_pretty('{"level1": {"level2": {"level3": "value"}}}') AS `json_pretty('{"level1": {"level2": {"level3": "value"}}}')`;
SELECT json_pretty(json_pretty('{"level1": {"level2": {"level3": "value"}}}')) AS `json_pretty(json_pretty('{"level1": {"level2": {"level3": "value"}}}'))`;
SELECT json_pretty('{"level1": {"level2": {"level3": "value"}}}') AS `json_pretty('{"level1": {"level2": {"level3": "value"}}}')` WHERE '[1, 2, 3]';
SELECT json_pretty('{"level1": {"level2": {"level3": "value"}}}') AS `json_pretty('{"level1": {"level2": {"level3": "value"}}}')`;
SELECT json_pretty(NULL) AS `json_pretty(NULL)`;
SELECT json_pretty(NULL) AS `json_pretty(NULL)`;
SELECT json_pretty('{"level1": {"level2": {"level3": "value"}}}') AS `json_pretty('{"level1": {"level2": {"level3": "value"}}}')` ORDER BY json_pretty('{"level1": {"level2": {"level3": "value"}}}') ASC;
SELECT json_pretty(0.0) AS `json_pretty(0.0)`;
SELECT DISTINCT json_pretty('{"level1": {"level2": {"level3": "value"}}}') AS `json_pretty('{"level1": {"level2": {"level3": "value"}}}')`;
SELECT json_pretty('{"level1": {"level2": {"level3": "value"}}}') AS `json_pretty('{"level1": {"level2": {"level3": "value"}}}')` WHERE json_pretty('[1, 2, 3]');
SELECT json_pretty('{"level1": {"level2": {"level3": "value"}}}') AS `json_pretty('{"level1": {"level2": {"level3": "value"}}}')` ORDER BY json_pretty('{"level1": {"level2": {"level3": "value"}}}') ASC;
SELECT json_pretty('{"level1": {"level2": {"level3": "value"}}}') AS `json_pretty('{"level1": {"level2": {"level3": "value"}}}')` GROUP BY json_pretty('{"level1": {"level2": {"level3": "value"}}}');
SELECT json_pretty(json_pretty('{"level1": {"level2": {"level3": "value"}}}')) AS `json_pretty(json_pretty('{"level1": {"level2": {"level3": "value"}}}'))`;
SELECT json_pretty(170141183460469231731687303715884105727) AS `json_pretty(170141183460469231731687303715884105727)`;
SELECT json_pretty('{"level1": {"level2": {"level3": "value"}}}') AS `json_pretty('{"level1": {"level2": {"level3": "value"}}}')` GROUP BY json_pretty('{"level1": {"level2": {"level3": "value"}}}');
SELECT json_pretty(NULL) AS `json_pretty(NULL)`;
SELECT DISTINCT json_pretty('{"level1": {"level2": {"level3": "value"}}}') AS `json_pretty('{"level1": {"level2": {"level3": "value"}}}')`;
SELECT json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]') AS `json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]')`;
SELECT CAST((CAST((json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]')) AS FLOAT)) AS DECIMAL128(38,38)) AS `CAST((CAST((json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]')) AS FLOAT)) AS DECIMAL128(38,38))`;
SELECT json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]') AS `json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]')`;
SELECT json_pretty(-1.0E308) AS `json_pretty(-1.0E308)`;
SELECT json_pretty(CAST(NULL AS JSON)) AS `json_pretty(CAST(NULL AS JSON))`;
SELECT json_pretty('') AS `json_pretty('')`;
SELECT json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]') AS `json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]')` LIMIT 0;
SELECT json_pretty(repeat('x', 65536)) AS `json_pretty(repeat('x', 65536))`;
SELECT sum(json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]')) OVER () AS `sum(json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]')) OVER ()`;
SELECT json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]') AS `json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]')` ORDER BY json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]') ASC;
SELECT json_pretty(-1) AS `json_pretty(-1)`;
SELECT json_pretty(1.0E308) AS `json_pretty(1.0E308)`;
SELECT json_pretty(json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]')) AS `json_pretty(json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]'))`;
SELECT json_pretty(json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]')) AS `json_pretty(json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]'))`;
SELECT json_pretty(json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]')) AS `json_pretty(json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]'))`;
SELECT json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]') AS `json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]')`;
SELECT json_pretty('{"a": 1, "b": 2}') AS `json_pretty('{"a": 1, "b": 2}')`;
SELECT json_pretty(FALSE) AS `json_pretty(FALSE)`;
SELECT json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]') AS `json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]')`;
SELECT json_pretty(json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]')) AS `json_pretty(json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]'))`;
SELECT json_pretty('0') AS `json_pretty('0')`;
SELECT json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]') AS `json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]')`;
SELECT json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]') AS `json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]')` ORDER BY json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]') DESC;
SELECT json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]') AS `json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]')` LIMIT 1, 1;
SELECT json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]') AS `json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]')`;
SELECT json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]') AS `json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]')` ORDER BY json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]') ASC;
SELECT json_pretty(json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]')) AS `json_pretty(json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]'))`;
SELECT json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]') AS `json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]')`;
SELECT json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]') AS `json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]')`;
SELECT json_pretty(json_query(CAST('[{"id": 1, "val": [10, 20]}, {"id": 2}]' AS JSON), '$.a')) AS `json_pretty(json_query(CAST('[{"id": 1, "val": [10, 20]}, {"id": 2}]' AS JSON), '$.a'))`;
SELECT json_pretty(-2147483648) AS `json_pretty(-2147483648)`;
SELECT json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}') AS `json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}')` LIMIT 7, 2;
SELECT json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}') AS `json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}')` LIMIT 1;
SELECT json_pretty(json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}')) AS `json_pretty(json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}'))`;
SELECT json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}') AS `json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}')` LIMIT 7, 1;
SELECT json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}') AS `json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}')` GROUP BY json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}');
SELECT count(json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}')) OVER () AS `count(json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}')) OVER ()`;
SELECT json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}') AS `json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}')` GROUP BY json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}');
SELECT json_pretty(0.0) AS `json_pretty(0.0)`;
SELECT json_pretty(-1) AS `json_pretty(-1)`;
SELECT DISTINCT json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}') AS `json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}')`;
SELECT json_pretty('0000-00-00') AS `json_pretty('0000-00-00')`;
SELECT json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}') AS `json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}')`;
SELECT json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}') AS `json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}')`;
SELECT json_pretty(NULL) AS `json_pretty(NULL)`;
SELECT json_pretty(-1.0E308) AS `json_pretty(-1.0E308)`;
SELECT json_pretty(-1) AS `json_pretty(-1)`;
SELECT json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}') AS `json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}')`;
SELECT json_pretty(json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}')) AS `json_pretty(json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}'))`;
SELECT DISTINCT json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}') AS `json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}')`;
SELECT json_pretty(json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}')) AS `json_pretty(json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}'))`;
SELECT json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}') AS `json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}')`;
SELECT json_pretty(json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}')) AS `json_pretty(json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}'))`;
SELECT json_pretty(-1) AS `json_pretty(-1)`;
SELECT json_pretty(-2147483648) AS `json_pretty(-2147483648)`;
SELECT json_pretty(2147483647) AS `json_pretty(2147483647)`;
SELECT json_pretty(json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}')) AS `json_pretty(json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}'))`;
SELECT json_pretty(0.0) AS `json_pretty(0.0)`;
SELECT json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}') AS `json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}')` GROUP BY json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}');
SELECT json_pretty(json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}')) AS `json_pretty(json_pretty('{"message": "Hello { world }", "tags": "[tag1, tag2]"}'))`;
SELECT json_pretty('{}') AS `json_pretty('{}')` WHERE '[]';
SELECT json_pretty('1970-01-01') AS `json_pretty('1970-01-01')`;
SELECT json_pretty(json_pretty('{}')) AS `json_pretty(json_pretty('{}'))`;
SELECT json_pretty('0000-00-00') AS `json_pretty('0000-00-00')`;
SELECT json_pretty('{}') AS `json_pretty('{}')`;
SELECT json_pretty(json_length(CAST('{}' AS JSON))) AS `json_pretty(json_length(CAST('{}' AS JSON)))`;
SELECT json_pretty('{}') AS `json_pretty('{}')`;
SELECT json_pretty('{}') AS `json_pretty('{}')` WHERE '{}';
SELECT json_pretty(TRUE) AS `json_pretty(TRUE)`;
SELECT json_pretty(json_pretty('{}')) AS `json_pretty(json_pretty('{}'))`;
SELECT json_pretty('{}') AS `json_pretty('{}')` ORDER BY json_pretty('{}') ASC;
SELECT json_pretty('') AS `json_pretty('')`;
SELECT json_pretty('{}') AS `json_pretty('{}')`;
SELECT json_pretty(0) AS `json_pretty(0)`;
SELECT json_pretty(json_pretty('{}')) AS `json_pretty(json_pretty('{}'))`;
SELECT json_pretty('') AS `json_pretty('')`;
SELECT json_pretty('{}') AS `json_pretty('{}')` LIMIT 1, 0;
SELECT json_pretty(-2147483648) AS `json_pretty(-2147483648)`;
SELECT CAST((json_pretty('{}')) AS JSON)->'$' AS `CAST((json_pretty('{}')) AS JSON)->'$'`;
SELECT json_pretty('0000-00-00') AS `json_pretty('0000-00-00')`;
SELECT json_pretty(json_pretty('{}')) AS `json_pretty(json_pretty('{}'))`;
SELECT json_pretty(1) AS `json_pretty(1)`;
SELECT json_pretty('{}') AS `json_pretty('{}')`;
SELECT json_pretty('{}') AS `json_pretty('{}')`;
SELECT json_pretty(json_pretty('{}')) AS `json_pretty(json_pretty('{}'))`;
SELECT json_pretty(json_pretty('{}')) AS `json_pretty(json_pretty('{}'))`;
SELECT json_pretty(-1) AS `json_pretty(-1)`;
SELECT json_pretty(json_pretty('{}')) AS `json_pretty(json_pretty('{}'))`;
SELECT json_pretty('9999-12-31 23:59:59') AS `json_pretty('9999-12-31 23:59:59')`;
SELECT CAST((json_pretty('{}')) AS CHAR(1)) AS `CAST((json_pretty('{}')) AS CHAR(1))`;
SELECT json_pretty(-1.0E308) AS `json_pretty(-1.0E308)`;
SELECT json_pretty('%') AS `json_pretty('%')`;
SELECT json_pretty(CAST((CAST('{}' AS SMALLINT)) AS INT)) AS `json_pretty(CAST((CAST('{}' AS SMALLINT)) AS INT))`;
SELECT json_pretty('{}') AS `json_pretty('{}')` LIMIT 7, 1;
SELECT json_pretty(TRUE) AS `json_pretty(TRUE)`;
SELECT json_pretty('[]') AS `json_pretty('[]')` LIMIT 1, 0;
SELECT json_pretty(json_pretty('[]')) AS `json_pretty(json_pretty('[]'))`;
SELECT json_pretty(json_pretty('[]')) AS `json_pretty(json_pretty('[]'))`;
SELECT min(json_pretty('[]')) OVER () AS `min(json_pretty('[]')) OVER ()`;
SELECT json_pretty('[]') AS `json_pretty('[]')` ORDER BY json_pretty('[]') ASC;
SELECT json_pretty(170141183460469231731687303715884105727) AS `json_pretty(170141183460469231731687303715884105727)`;
SELECT json_pretty(json_pretty('[]')) AS `json_pretty(json_pretty('[]'))`;
SELECT json_pretty(0.0) AS `json_pretty(0.0)`;
SELECT json_pretty('[]') AS `json_pretty('[]')` WHERE json_pretty('[{"id": 1, "val": [10, 20]}, {"id": 2}]');
SELECT DISTINCT json_pretty('[]') AS `json_pretty('[]')`;
SELECT json_pretty('[]') AS `json_pretty('[]')`;
SELECT json_pretty('[]') AS `json_pretty('[]')`;
SELECT json_pretty(1) AS `json_pretty(1)`;
SELECT json_pretty(-1.0E308) AS `json_pretty(-1.0E308)`;
SELECT json_pretty('[]') AS `json_pretty('[]')`;
SELECT json_pretty('[]') AS `json_pretty('[]')` WHERE '[]';
SELECT json_pretty(NULL) AS `json_pretty(NULL)`;
SELECT json_pretty(0.0) AS `json_pretty(0.0)`;
SELECT json_pretty('[]') AS `json_pretty('[]')` WHERE json_pretty('{}');
SELECT CAST((json_pretty('[]')) AS JSON)->'k' AS `CAST((json_pretty('[]')) AS JSON)->'k'`;
SELECT json_pretty('0000-00-00') AS `json_pretty('0000-00-00')`;
SELECT json_pretty(9223372036854775807) AS `json_pretty(9223372036854775807)`;
SELECT json_pretty(1) AS `json_pretty(1)`;
SELECT json_pretty(2147483647) AS `json_pretty(2147483647)`;
SELECT json_pretty('0') AS `json_pretty('0')`;
SELECT json_pretty(CAST('[]' AS TINYINT)) AS `json_pretty(CAST('[]' AS TINYINT))`;
SELECT json_pretty(-2147483648) AS `json_pretty(-2147483648)`;
SELECT json_pretty('9999-12-31 23:59:59') AS `json_pretty('9999-12-31 23:59:59')`;
SELECT json_pretty(0) AS `json_pretty(0)`;
SELECT json_pretty(json_pretty('[]')) AS `json_pretty(json_pretty('[]'))`;
SELECT json_pretty(json_pretty('{"int": 123, "float": 12.34}')) AS `json_pretty(json_pretty('{"int": 123, "float": 12.34}'))`;
SELECT json_pretty('{"int": 123, "float": 12.34}') AS `json_pretty('{"int": 123, "float": 12.34}')` GROUP BY json_pretty('{"int": 123, "float": 12.34}');
SELECT json_pretty('{"int": 123, "float": 12.34}') AS `json_pretty('{"int": 123, "float": 12.34}')`;
SELECT json_pretty(json_pretty('{"int": 123, "float": 12.34}')) AS `json_pretty(json_pretty('{"int": 123, "float": 12.34}'))`;
SELECT json_pretty('%') AS `json_pretty('%')`;
SELECT json_pretty(0.0) AS `json_pretty(0.0)`;
SELECT json_pretty(json_pretty('{}')) AS `json_pretty(json_pretty('{}'))`;
SELECT json_pretty('{"int": 123, "float": 12.34}') AS `json_pretty('{"int": 123, "float": 12.34}')`;
SELECT json_pretty('{"int": 123, "float": 12.34}') AS `json_pretty('{"int": 123, "float": 12.34}')` WHERE json_pretty('{}');
SELECT json_pretty(repeat('x', 65536)) AS `json_pretty(repeat('x', 65536))`;
SELECT DISTINCT json_pretty('{"int": 123, "float": 12.34}') AS `json_pretty('{"int": 123, "float": 12.34}')`;
SELECT json_pretty('1970-01-01') AS `json_pretty('1970-01-01')`;
SELECT json_pretty('{"int": 123, "float": 12.34}') AS `json_pretty('{"int": 123, "float": 12.34}')`;
SELECT json_pretty(json_pretty('{"int": 123, "float": 12.34}')) AS `json_pretty(json_pretty('{"int": 123, "float": 12.34}'))`;
SELECT json_pretty('{"int": 123, "float": 12.34}') AS `json_pretty('{"int": 123, "float": 12.34}')`;
SELECT json_pretty(json_pretty('{"int": 123, "float": 12.34}')) AS `json_pretty(json_pretty('{"int": 123, "float": 12.34}'))`;
SELECT json_pretty(0.0) AS `json_pretty(0.0)`;
SELECT min(json_pretty('{"int": 123, "float": 12.34}')) OVER () AS `min(json_pretty('{"int": 123, "float": 12.34}')) OVER ()`;
SELECT json_pretty('\\') AS `json_pretty('\\')`;
SELECT min(json_pretty('{"int": 123, "float": 12.34}')) OVER () AS `min(json_pretty('{"int": 123, "float": 12.34}')) OVER ()`;
SELECT json_pretty('{"int": 123, "float": 12.34}') AS `json_pretty('{"int": 123, "float": 12.34}')`;
SELECT json_pretty('{"int": 123, "float": 12.34}') AS `json_pretty('{"int": 123, "float": 12.34}')`;
SELECT json_pretty(json_pretty('{"int": 123, "float": 12.34}')) AS `json_pretty(json_pretty('{"int": 123, "float": 12.34}'))`;
SELECT json_pretty('{"int": 123, "float": 12.34}') AS `json_pretty('{"int": 123, "float": 12.34}')` GROUP BY json_pretty('{"int": 123, "float": 12.34}');
SELECT json_pretty(json_pretty('{"int": 123, "float": 12.34}')) AS `json_pretty(json_pretty('{"int": 123, "float": 12.34}'))`;
SELECT json_pretty('0') AS `json_pretty('0')`;