create table t(id bigint, ts bigint) partition by from_unixtime(ts, 'yyyy-MM-dd HH:mm:ss', 'UTC');
insert into t values(1, 1196440219);
insert into t values(1, 1196440219);
create table t(id bigint, ts bigint) partition by from_unixtime(ts, 'yyyy-MM-dd HH:mm:ss');
insert into t values(1, 1196440219);
insert into t values(1, 1196440219);
create table t(id bigint, ts bigint) partition by from_unixtime(ts, 'yyyy-MM-dd HH:mm:ss', 'UTC');
insert into t(id) values(1);
create table t(ts bigint, format string, timezone string);
insert into t values(1, 'yyyy-MM-dd HH:mm:ss', 'UTC');