SELECT `srfuzz_mut_9`.`tab1`.`c0`, `srfuzz_mut_9`.`tab1`.`c1` FROM `srfuzz_mut_9`.`tab1`;
SELECT `srfuzz_mut_9`.`tab1`.`c0`, `srfuzz_mut_9`.`tab1`.`c1` FROM `srfuzz_mut_9`.`tab1`;
SELECT `srfuzz_mut_9`.`tab1`.`c0`, `srfuzz_mut_9`.`tab1`.`c1` FROM `srfuzz_mut_9`.`tab1`;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_9`.`mv1`;
SELECT `srfuzz_mut_9`.`tab1`.`c0`, `srfuzz_mut_9`.`tab1`.`c1` FROM `srfuzz_mut_9`.`tab1`;
SELECT `srfuzz_mut_9`.`tab1`.`c0`, `srfuzz_mut_9`.`tab1`.`c1` FROM `srfuzz_mut_9`.`tab1`;
SELECT `srfuzz_mut_9`.`tab1`.`c0`, `srfuzz_mut_9`.`tab1`.`c1` FROM `srfuzz_mut_9`.`tab1`;
SELECT `srfuzz_mut_9`.`tab1`.`c0`, `srfuzz_mut_9`.`tab1`.`c1` FROM `srfuzz_mut_9`.`tab1`;
SELECT `srfuzz_mut_9`.`tab1`.`c0`, `srfuzz_mut_9`.`tab1`.`c1` FROM `srfuzz_mut_9`.`tab1`;
SELECT `srfuzz_mut_9`.`tab1`.`c0`, `srfuzz_mut_9`.`tab1`.`c1` FROM `srfuzz_mut_9`.`tab1`;
SELECT `srfuzz_mut_9`.`tab1`.`c0`, `srfuzz_mut_9`.`tab1`.`c1` FROM `srfuzz_mut_9`.`tab1`;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_9`.`mv1`;
SELECT `srfuzz_mut_9`.`tab1`.`c0`, `srfuzz_mut_9`.`tab1`.`c1` FROM `srfuzz_mut_9`.`tab1`;
SELECT `srfuzz_mut_9`.`tab1`.`c0`, `srfuzz_mut_9`.`tab1`.`c1` FROM `srfuzz_mut_9`.`tab1`;
SELECT `srfuzz_mut_9`.`tab1`.`c0`, `srfuzz_mut_9`.`tab1`.`c1` FROM `srfuzz_mut_9`.`tab1`;
SELECT `srfuzz_mut_9`.`tab1`.`c0`, `srfuzz_mut_9`.`tab1`.`c1` FROM `srfuzz_mut_9`.`tab1`;
SELECT `srfuzz_mut_9`.`tab1`.`c0`, `srfuzz_mut_9`.`tab1`.`c1` FROM `srfuzz_mut_9`.`tab1`;
SELECT `srfuzz_mut_9`.`t`.`c1`, `srfuzz_mut_9`.`t`.`c2` FROM `srfuzz_mut_9`.`t`;
SELECT `srfuzz_mut_9`.`t`.`c1`, `srfuzz_mut_9`.`t`.`c2` FROM `srfuzz_mut_9`.`t`;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_9`.`mv1`.`c0`, `srfuzz_mut_9`.`mv1`.`c1` FROM `srfuzz_mut_9`.`mv1` EXCEPT SELECT `srfuzz_mut_9`.`mv1`.`c0`, `srfuzz_mut_9`.`mv1`.`c1` FROM `srfuzz_mut_9`.`mv1`) `mv1`;
SELECT json_length(CAST((count(*)) AS JSON)) AS `json_length(CAST((count(*)) AS JSON))` FROM `srfuzz_mut_9`.`mv1`;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_9`.`mv1`.`c0`, `srfuzz_mut_9`.`mv1`.`c1` FROM `srfuzz_mut_9`.`mv1` UNION ALL SELECT `srfuzz_mut_9`.`mv1`.`c0`, `srfuzz_mut_9`.`mv1`.`c1` FROM `srfuzz_mut_9`.`mv1`) `mv1`;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_9`.`mv1` LIMIT 7, 100;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_9`.`mv1`.`c0`, `srfuzz_mut_9`.`mv1`.`c1` FROM `srfuzz_mut_9`.`mv1` INTERSECT SELECT `srfuzz_mut_9`.`mv1`.`c0`, `srfuzz_mut_9`.`mv1`.`c1` FROM `srfuzz_mut_9`.`mv1`) `mv1`;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_9`.`mv1`.`c0`, `srfuzz_mut_9`.`mv1`.`c1` FROM `srfuzz_mut_9`.`mv1`) `mv1`;
SELECT CAST((CAST((count(*)) AS LARGEINT)) AS DOUBLE) AS `CAST((CAST((count(*)) AS LARGEINT)) AS DOUBLE)` FROM `srfuzz_mut_9`.`mv1`;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_9`.`mv1`.`c0`, `srfuzz_mut_9`.`mv1`.`c1` FROM `srfuzz_mut_9`.`mv1`) `mv1`;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_9`.`mv1` HAVING (count(*)) < 10;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_9`.`mv1` LIMIT 7, 100;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_9`.`mv1` HAVING (count(*)) > 1;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_9`.`mv1`.`c0`, `srfuzz_mut_9`.`mv1`.`c1` FROM `srfuzz_mut_9`.`mv1`) SELECT count(*) AS `count(*)` FROM `srfuzz_n1` AS mv1;
SELECT CAST((count(*)) AS DECIMAL128(38,0)) AS `CAST((count(*)) AS DECIMAL128(38,0))` FROM `srfuzz_mut_9`.`mv1`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_9`.`mv1`.`c0`, `srfuzz_mut_9`.`mv1`.`c1` FROM `srfuzz_mut_9`.`mv1`) SELECT count(*) AS `count(*)` FROM `srfuzz_n1` AS mv1;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_9`.`mv1`.`c0`, `srfuzz_mut_9`.`mv1`.`c1` FROM `srfuzz_mut_9`.`mv1`) `mv1`;
SELECT CAST((CAST((count(*)) AS JSON)) AS MAP<VARCHAR(16),MAP<INT,ARRAY<JSON>>>) AS `CAST((CAST((count(*)) AS JSON)) AS MAP<VARCHAR(16),MAP<INT,ARRAY<JSON>>>)` FROM `srfuzz_mut_9`.`mv1`;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_9`.`mv1`.`c0`, `srfuzz_mut_9`.`mv1`.`c1` FROM `srfuzz_mut_9`.`mv1` EXCEPT SELECT `srfuzz_mut_9`.`mv1`.`c0`, `srfuzz_mut_9`.`mv1`.`c1` FROM `srfuzz_mut_9`.`mv1`) `mv1`;
SELECT CAST((count(*)) AS JSON)->'k' AS `CAST((count(*)) AS JSON)->'k'` FROM `srfuzz_mut_9`.`mv1`;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_9`.`mv1`.`c0`, `srfuzz_mut_9`.`mv1`.`c1` FROM `srfuzz_mut_9`.`mv1`) `mv1`;
SELECT CAST((CAST((CAST((count(*)) AS DOUBLE)) AS LARGEINT)) AS VARBINARY) AS `CAST((CAST((CAST((count(*)) AS DOUBLE)) AS LARGEINT)) AS VARBINARY)` FROM `srfuzz_mut_9`.`mv1`;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_9`.`mv1` ORDER BY count(*) ASC;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_9`.`mv1` ORDER BY count(*) DESC;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_9`.`mv1`.`c0`, `srfuzz_mut_9`.`mv1`.`c1` FROM `srfuzz_mut_9`.`mv1`) `mv1`;
SELECT CAST((count(*)) AS JSON) AS `CAST((count(*)) AS JSON)` FROM `srfuzz_mut_9`.`mv1`;