SELECT get_query_profile(last_query_id()) AS `get_query_profile(last_query_id())`;
SELECT get_query_profile(get_query_profile(last_query_id())) AS `get_query_profile(get_query_profile(last_query_id()))`;
SELECT get_query_profile(last_query_id()) AS `get_query_profile(last_query_id())`;
SELECT get_query_profile(last_query_id()) AS `get_query_profile(last_query_id())`;
SELECT get_query_profile(last_query_id()) AS `get_query_profile(last_query_id())`;
SELECT get_query_profile(last_query_id()) AS `get_query_profile(last_query_id())`;
SELECT get_query_profile(last_query_id()) AS `get_query_profile(last_query_id())` LIMIT 7, 1;
SELECT get_query_profile(CAST((last_query_id()) AS JSON)->'$.a') AS `get_query_profile(CAST((last_query_id()) AS JSON)->'$.a')`;
SELECT get_query_profile(json_query(CAST((last_query_id()) AS JSON), '$.a')) AS `get_query_profile(json_query(CAST((last_query_id()) AS JSON), '$.a'))`;
SELECT CAST((get_query_profile(last_query_id())) AS JSON)->'$.a' AS `CAST((get_query_profile(last_query_id())) AS JSON)->'$.a'`;
SELECT get_query_profile(last_query_id()) AS `get_query_profile(last_query_id())`;
SELECT get_query_profile(get_query_profile(last_query_id())) AS `get_query_profile(get_query_profile(last_query_id()))`;
SELECT get_query_profile(get_query_profile(last_query_id())) AS `get_query_profile(get_query_profile(last_query_id()))`;
SELECT get_query_profile(get_query_profile(last_query_id())) AS `get_query_profile(get_query_profile(last_query_id()))`;
SELECT get_query_profile(get_query_profile(last_query_id())) AS `get_query_profile(get_query_profile(last_query_id()))`;
SELECT get_query_profile(last_query_id()) AS `get_query_profile(last_query_id())`;
SELECT get_query_profile(last_query_id()) AS `get_query_profile(last_query_id())`;
SELECT get_query_profile(last_query_id()) AS `get_query_profile(last_query_id())` LIMIT 1;
SELECT get_query_profile(last_query_id()) AS `get_query_profile(last_query_id())`;
SELECT max(get_query_profile(last_query_id())) OVER () AS `max(get_query_profile(last_query_id())) OVER ()`;
SELECT get_query_profile(last_query_id()) AS `get_query_profile(last_query_id())`;
SELECT get_query_profile(last_query_id()) AS `get_query_profile(last_query_id())`;
SELECT get_query_profile(last_query_id()) AS `get_query_profile(last_query_id())`;
SELECT get_query_profile(get_query_profile(last_query_id())) AS `get_query_profile(get_query_profile(last_query_id()))`;
SELECT get_query_profile(last_query_id()) AS `get_query_profile(last_query_id())`;
SELECT get_query_profile(last_query_id()) AS `get_query_profile(last_query_id())`;
SELECT get_query_profile(last_query_id()) AS `get_query_profile(last_query_id())`;
SELECT get_query_profile(last_query_id()) AS `get_query_profile(last_query_id())`;
SELECT CAST((get_query_profile(last_query_id())) AS JSON)->'$' AS `CAST((get_query_profile(last_query_id())) AS JSON)->'$'`;
SELECT get_query_profile(get_query_profile(last_query_id())) AS `get_query_profile(get_query_profile(last_query_id()))`;
SELECT sum(get_query_profile(last_query_id())) OVER () AS `sum(get_query_profile(last_query_id())) OVER ()`;
SELECT get_query_profile(get_query_profile(last_query_id())) AS `get_query_profile(get_query_profile(last_query_id()))`;
SELECT get_query_profile(get_query_profile(last_query_id())) AS `get_query_profile(get_query_profile(last_query_id()))`;
SELECT max(get_query_profile(last_query_id())) OVER () AS `max(get_query_profile(last_query_id())) OVER ()`;
SELECT get_query_profile(last_query_id()) AS `get_query_profile(last_query_id())`;