SELECT `srfuzz_mut_175`.`t_struct_binary`.`id`, `srfuzz_mut_175`.`t_struct_binary`.`payload` FROM `srfuzz_mut_175`.`t_struct_binary` ORDER BY `srfuzz_mut_175`.`t_struct_binary`.`id` ASC;
SELECT `srfuzz_mut_175`.`t_array_binary`.`id`, `srfuzz_mut_175`.`t_array_binary`.`bins` FROM `srfuzz_mut_175`.`t_array_binary` ORDER BY `srfuzz_mut_175`.`t_array_binary`.`id` ASC;
SELECT `srfuzz_mut_175`.`t_map_binary`.`id`, `srfuzz_mut_175`.`t_map_binary`.`kv` FROM `srfuzz_mut_175`.`t_map_binary` ORDER BY `srfuzz_mut_175`.`t_map_binary`.`id` ASC;
SELECT ARRAY<VARBINARY>[to_binary('AABB', 'hex'), NULL] AS `[to_binary('AABB', 'hex'), NULL]`;
SELECT named_struct('bin_field', to_binary('DEADBEEF', 'hex'), 'arr_field', ARRAY<VARBINARY>[to_binary('00', 'hex'), to_binary('01', 'hex')]) AS `named_struct('bin_field', to_binary('DEADBEEF', 'hex'), 'arr_field', [to_binary('00', 'hex'), to_binary('01', 'hex')])`;
SELECT MAP<VARCHAR,VARBINARY>{'k1':to_binary('CAFE', 'hex'),'k2':NULL} AS `map{'k1':to_binary('CAFE', 'hex'),'k2':NULL}`;
SELECT ARRAY<VARBINARY>[to_binary('AABB', 'hex'), NULL] AS `[to_binary('AABB', 'hex'), NULL]`;
SELECT to_binary('AABB', 'hex') AS `to_binary('AABB', 'hex')`;
SELECT to_binary('AABB', 'hex') AS `to_binary('AABB', 'hex')`;
SELECT ARRAY<VARBINARY>[to_binary('414243', 'hex'), NULL] AS `[to_binary('414243', 'hex'), NULL]`;
SELECT to_binary('414243', 'hex') AS `to_binary('414243', 'hex')`;
SELECT `srfuzz_mut_175`.`t_struct_binary`.`id`, dense_rank() OVER (PARTITION BY `srfuzz_mut_175`.`t_struct_binary`.`id` ORDER BY `srfuzz_mut_175`.`t_struct_binary`.`payload` ASC ) AS `dense_rank() OVER (PARTITION BY id ORDER BY payload ASC )` FROM `srfuzz_mut_175`.`t_struct_binary` ORDER BY `srfuzz_mut_175`.`t_struct_binary`.`id` ASC;
SELECT `t_struct_binary`.`id`, `t_struct_binary`.`payload` FROM (SELECT `srfuzz_mut_175`.`t_struct_binary`.`id`, `srfuzz_mut_175`.`t_struct_binary`.`payload` FROM `srfuzz_mut_175`.`t_struct_binary`) `t_struct_binary` ORDER BY `t_struct_binary`.`id` ASC;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_175`.`t_struct_binary`.`id`, `srfuzz_mut_175`.`t_struct_binary`.`payload` FROM `srfuzz_mut_175`.`t_struct_binary`) SELECT `t_struct_binary`.`id`, `t_struct_binary`.`payload` FROM `srfuzz_n1` AS t_struct_binary ORDER BY `t_struct_binary`.`id` ASC;
SELECT CAST(`srfuzz_mut_175`.`t_struct_binary`.`id` AS JSON)->'$' AS `CAST(id AS JSON)->'$'`, `srfuzz_mut_175`.`t_struct_binary`.`payload` FROM `srfuzz_mut_175`.`t_struct_binary` ORDER BY `srfuzz_mut_175`.`t_struct_binary`.`id` ASC;
SELECT `t_struct_binary`.`id`, `t_struct_binary`.`payload` FROM (SELECT `srfuzz_mut_175`.`t_struct_binary`.`id`, `srfuzz_mut_175`.`t_struct_binary`.`payload` FROM `srfuzz_mut_175`.`t_struct_binary`) `t_struct_binary` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  ORDER BY `t_struct_binary`.`id` ASC;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_175`.`t_struct_binary`.`id`, `srfuzz_mut_175`.`t_struct_binary`.`payload` FROM `srfuzz_mut_175`.`t_struct_binary`) SELECT `t_struct_binary`.`id`, `t_struct_binary`.`payload` FROM `srfuzz_n1` AS t_struct_binary ORDER BY `t_struct_binary`.`id` ASC;
SELECT `srfuzz_mut_175`.`t_struct_binary`.`id`, `srfuzz_mut_175`.`t_struct_binary`.`payload` FROM `srfuzz_mut_175`.`t_struct_binary` GROUP BY `srfuzz_mut_175`.`t_struct_binary`.`id`, `srfuzz_mut_175`.`t_struct_binary`.`payload` ORDER BY `srfuzz_mut_175`.`t_struct_binary`.`id` ASC;
SELECT `srfuzz_mut_175`.`t_struct_binary`.`id`, `srfuzz_mut_175`.`t_struct_binary`.`payload` FROM `srfuzz_mut_175`.`t_struct_binary` ORDER BY `srfuzz_mut_175`.`t_struct_binary`.`id` ASC  LIMIT 5;
SELECT `srfuzz_mut_175`.`t_struct_binary`.`id`, `srfuzz_mut_175`.`t_struct_binary`.`payload` FROM `srfuzz_mut_175`.`t_struct_binary` ORDER BY `srfuzz_mut_175`.`t_struct_binary`.`id` ASC  LIMIT 0;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_175`.`t_struct_binary`.`id`, `srfuzz_mut_175`.`t_struct_binary`.`payload` FROM `srfuzz_mut_175`.`t_struct_binary`) SELECT `t_struct_binary`.`id`, `t_struct_binary`.`payload` FROM `srfuzz_n1` AS t_struct_binary ORDER BY `t_struct_binary`.`id` ASC;
SELECT `srfuzz_mut_175`.`t_struct_binary`.`id`, `srfuzz_mut_175`.`t_struct_binary`.`payload` FROM `srfuzz_mut_175`.`t_struct_binary` ORDER BY `srfuzz_mut_175`.`t_struct_binary`.`id` ASC  LIMIT 0;
SELECT `srfuzz_mut_175`.`t_struct_binary`.`id`, `srfuzz_mut_175`.`t_struct_binary`.`payload` FROM `srfuzz_mut_175`.`t_struct_binary` GROUP BY `srfuzz_mut_175`.`t_struct_binary`.`id`, `srfuzz_mut_175`.`t_struct_binary`.`payload` ORDER BY `srfuzz_mut_175`.`t_struct_binary`.`id` ASC;
SELECT `t_struct_binary`.`id`, `t_struct_binary`.`payload` FROM (SELECT `srfuzz_mut_175`.`t_struct_binary`.`id`, `srfuzz_mut_175`.`t_struct_binary`.`payload` FROM `srfuzz_mut_175`.`t_struct_binary`) `t_struct_binary` ORDER BY `t_struct_binary`.`id` ASC;
SELECT `srfuzz_mut_175`.`t_struct_binary`.`id`, `srfuzz_mut_175`.`t_struct_binary`.`payload` FROM `srfuzz_mut_175`.`t_struct_binary`;
SELECT `t_array_binary`.`id`, `t_array_binary`.`bins` FROM (SELECT `srfuzz_mut_175`.`t_array_binary`.`id`, `srfuzz_mut_175`.`t_array_binary`.`bins` FROM `srfuzz_mut_175`.`t_array_binary`) `t_array_binary` ORDER BY `t_array_binary`.`id` ASC;
SELECT `srfuzz_mut_175`.`t_array_binary`.`id`, `srfuzz_mut_175`.`t_array_binary`.`bins` FROM `srfuzz_mut_175`.`t_array_binary` GROUP BY `srfuzz_mut_175`.`t_array_binary`.`id`, `srfuzz_mut_175`.`t_array_binary`.`bins` ORDER BY `srfuzz_mut_175`.`t_array_binary`.`id` ASC;
SELECT `t_array_binary`.`id`, `t_array_binary`.`bins` FROM (SELECT `srfuzz_mut_175`.`t_array_binary`.`id`, `srfuzz_mut_175`.`t_array_binary`.`bins` FROM `srfuzz_mut_175`.`t_array_binary`) `t_array_binary` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  ORDER BY `t_array_binary`.`id` ASC;
SELECT `srfuzz_mut_175`.`t_array_binary`.`id`, `srfuzz_mut_175`.`t_array_binary`.`bins` FROM `srfuzz_mut_175`.`t_array_binary` ORDER BY `srfuzz_mut_175`.`t_array_binary`.`id` ASC  LIMIT 5;
SELECT `srfuzz_mut_175`.`t_array_binary`.`id`, `srfuzz_mut_175`.`t_array_binary`.`bins` FROM `srfuzz_mut_175`.`t_array_binary` WHERE '00' ORDER BY `srfuzz_mut_175`.`t_array_binary`.`id` ASC;
SELECT `t_array_binary`.`id`, `t_array_binary`.`bins` FROM (SELECT `srfuzz_mut_175`.`t_array_binary`.`id`, `srfuzz_mut_175`.`t_array_binary`.`bins` FROM `srfuzz_mut_175`.`t_array_binary` UNION SELECT `srfuzz_mut_175`.`t_array_binary`.`id`, `srfuzz_mut_175`.`t_array_binary`.`bins` FROM `srfuzz_mut_175`.`t_array_binary`) `t_array_binary` ORDER BY `t_array_binary`.`id` ASC;
SELECT `srfuzz_mut_175`.`t_array_binary`.`id`, `srfuzz_mut_175`.`t_array_binary`.`bins` FROM `srfuzz_mut_175`.`t_array_binary` GROUP BY `srfuzz_mut_175`.`t_array_binary`.`id`, `srfuzz_mut_175`.`t_array_binary`.`bins` ORDER BY `srfuzz_mut_175`.`t_array_binary`.`id` ASC;
SELECT `srfuzz_mut_175`.`t_array_binary`.`id`, rank() OVER (PARTITION BY `srfuzz_mut_175`.`t_array_binary`.`id` ORDER BY `srfuzz_mut_175`.`t_array_binary`.`bins` ASC ) AS `rank() OVER (PARTITION BY id ORDER BY bins ASC )` FROM `srfuzz_mut_175`.`t_array_binary` ORDER BY `srfuzz_mut_175`.`t_array_binary`.`id` ASC;
SELECT `t_array_binary`.`id`, `t_array_binary`.`bins` FROM (SELECT `srfuzz_mut_175`.`t_array_binary`.`id`, `srfuzz_mut_175`.`t_array_binary`.`bins` FROM `srfuzz_mut_175`.`t_array_binary` UNION SELECT `srfuzz_mut_175`.`t_array_binary`.`id`, `srfuzz_mut_175`.`t_array_binary`.`bins` FROM `srfuzz_mut_175`.`t_array_binary`) `t_array_binary` ORDER BY `t_array_binary`.`id` ASC;
SELECT `srfuzz_mut_175`.`t_array_binary`.`id`, `srfuzz_mut_175`.`t_array_binary`.`bins` FROM `srfuzz_mut_175`.`t_array_binary` WHERE 'AABB' ORDER BY `srfuzz_mut_175`.`t_array_binary`.`id` ASC;
SELECT `srfuzz_mut_175`.`t_map_binary`.`id`, `srfuzz_mut_175`.`t_map_binary`.`kv` FROM `srfuzz_mut_175`.`t_map_binary`;
SELECT `t_map_binary`.`id`, `t_map_binary`.`kv` FROM (SELECT `srfuzz_mut_175`.`t_map_binary`.`id`, `srfuzz_mut_175`.`t_map_binary`.`kv` FROM `srfuzz_mut_175`.`t_map_binary`) `t_map_binary` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  ORDER BY `t_map_binary`.`id` ASC;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_175`.`t_map_binary`.`id`, `srfuzz_mut_175`.`t_map_binary`.`kv` FROM `srfuzz_mut_175`.`t_map_binary`) SELECT `t_map_binary`.`id`, `t_map_binary`.`kv` FROM `srfuzz_n1` AS t_map_binary ORDER BY `t_map_binary`.`id` ASC;
SELECT `t_map_binary`.`id`, `t_map_binary`.`kv` FROM (SELECT `srfuzz_mut_175`.`t_map_binary`.`id`, `srfuzz_mut_175`.`t_map_binary`.`kv` FROM `srfuzz_mut_175`.`t_map_binary`) `t_map_binary` ORDER BY `t_map_binary`.`id` ASC;
SELECT `t_map_binary`.`id`, `t_map_binary`.`kv` FROM (SELECT `srfuzz_mut_175`.`t_map_binary`.`id`, `srfuzz_mut_175`.`t_map_binary`.`kv` FROM `srfuzz_mut_175`.`t_map_binary` INTERSECT SELECT `srfuzz_mut_175`.`t_map_binary`.`id`, `srfuzz_mut_175`.`t_map_binary`.`kv` FROM `srfuzz_mut_175`.`t_map_binary`) `t_map_binary` ORDER BY `t_map_binary`.`id` ASC;
SELECT `t_map_binary`.`id`, `t_map_binary`.`kv` FROM (SELECT `srfuzz_mut_175`.`t_map_binary`.`id`, `srfuzz_mut_175`.`t_map_binary`.`kv` FROM `srfuzz_mut_175`.`t_map_binary` EXCEPT SELECT `srfuzz_mut_175`.`t_map_binary`.`id`, `srfuzz_mut_175`.`t_map_binary`.`kv` FROM `srfuzz_mut_175`.`t_map_binary`) `t_map_binary` ORDER BY `t_map_binary`.`id` ASC;
SELECT `srfuzz_mut_175`.`t_map_binary`.`id`, `srfuzz_mut_175`.`t_map_binary`.`kv` FROM `srfuzz_mut_175`.`t_map_binary` GROUP BY `srfuzz_mut_175`.`t_map_binary`.`id`, `srfuzz_mut_175`.`t_map_binary`.`kv` ORDER BY `srfuzz_mut_175`.`t_map_binary`.`id` ASC;
SELECT `t_map_binary`.`id`, `t_map_binary`.`kv` FROM (SELECT `srfuzz_mut_175`.`t_map_binary`.`id`, `srfuzz_mut_175`.`t_map_binary`.`kv` FROM `srfuzz_mut_175`.`t_map_binary` INTERSECT SELECT `srfuzz_mut_175`.`t_map_binary`.`id`, `srfuzz_mut_175`.`t_map_binary`.`kv` FROM `srfuzz_mut_175`.`t_map_binary`) `t_map_binary` ORDER BY `t_map_binary`.`id` ASC;
SELECT `t_map_binary`.`id`, `t_map_binary`.`kv` FROM (SELECT `srfuzz_mut_175`.`t_map_binary`.`id`, `srfuzz_mut_175`.`t_map_binary`.`kv` FROM `srfuzz_mut_175`.`t_map_binary` UNION ALL SELECT `srfuzz_mut_175`.`t_map_binary`.`id`, `srfuzz_mut_175`.`t_map_binary`.`kv` FROM `srfuzz_mut_175`.`t_map_binary`) `t_map_binary` ORDER BY `t_map_binary`.`id` ASC;
SELECT `srfuzz_mut_175`.`t_map_binary`.`id`, `srfuzz_mut_175`.`t_map_binary`.`kv`[1] AS `kv[1]` FROM `srfuzz_mut_175`.`t_map_binary` ORDER BY `srfuzz_mut_175`.`t_map_binary`.`id` ASC;
SELECT named_struct('bin_field', to_binary('DEADBEEF', 'hex'), 'arr_field', to_binary('00', 'hex')) AS `named_struct('bin_field', to_binary('DEADBEEF', 'hex'), 'arr_field', to_binary('00', 'hex'))`;
SELECT to_binary('AABB', NULL) AS `to_binary('AABB', NULL)`;
SELECT to_binary('0000-00-00', 'hex') AS `to_binary('0000-00-00', 'hex')`;
SELECT to_binary(2147483647, 'hex') AS `to_binary(2147483647, 'hex')`;
SELECT to_binary('hex', 'hex') AS `to_binary('hex', 'hex')`;
SELECT to_binary('AABB', json_length(CAST('hex' AS JSON))) AS `to_binary('AABB', json_length(CAST('hex' AS JSON)))`;
SELECT to_binary(to_binary('AABB', 'hex'), 'hex') AS `to_binary(to_binary('AABB', 'hex'), 'hex')`;
SELECT to_binary('AABB', to_binary('AABB', 'hex')) AS `to_binary('AABB', to_binary('AABB', 'hex'))`;
SELECT to_binary('', 'hex') AS `to_binary('', 'hex')`;
SELECT to_binary('AABB', 'hex') AS `to_binary('AABB', 'hex')` WHERE 'k1';
SELECT to_binary('AABB', 'hex') AS `to_binary('AABB', 'hex')`;
SELECT to_binary('AABB', 'hex') AS `to_binary('AABB', 'hex')` WHERE 'DEADBEEF';
SELECT to_binary('DEADBEEF', 'hex') AS `to_binary('DEADBEEF', 'hex')`;
SELECT to_binary('AABB', 'hex') AS `to_binary('AABB', 'hex')`;
SELECT to_binary(0.0, 'hex') AS `to_binary(0.0, 'hex')`;
SELECT to_binary('AABB', 'hex') AS `to_binary('AABB', 'hex')` ORDER BY to_binary('AABB', 'hex') ASC;
SELECT to_binary(to_binary('AABB', 'hex'), 'hex') AS `to_binary(to_binary('AABB', 'hex'), 'hex')`;
SELECT to_binary(CAST(NULL AS JSON), 'hex') AS `to_binary(CAST(NULL AS JSON), 'hex')`;
SELECT to_binary(to_binary('AABB', 'hex'), 'hex') AS `to_binary(to_binary('AABB', 'hex'), 'hex')`;
SELECT to_binary('AABB', 1) AS `to_binary('AABB', 1)`;
SELECT to_binary(to_binary('AABB', 'hex'), 'hex') AS `to_binary(to_binary('AABB', 'hex'), 'hex')`;
SELECT to_binary('AABB', 'hex') AS `to_binary('AABB', 'hex')` ORDER BY to_binary('AABB', 'hex') ASC;
SELECT to_binary(-2147483648, 'hex') AS `to_binary(-2147483648, 'hex')`;
SELECT to_binary('AABB', 'AABB') AS `to_binary('AABB', 'AABB')`;
SELECT to_binary('AABB', 'hex') AS `to_binary('AABB', 'hex')` LIMIT 1;
SELECT to_binary('AABB', 'hex') AS `to_binary('AABB', 'hex')`;
SELECT to_binary('AABB', NULL) AS `to_binary('AABB', NULL)`;
SELECT to_binary('AABB', to_binary('AABB', 'hex')) AS `to_binary('AABB', to_binary('AABB', 'hex'))`;
SELECT to_binary('AABB', '9999-12-31 23:59:59') AS `to_binary('AABB', '9999-12-31 23:59:59')`;
SELECT to_binary('AABB', to_binary('AABB', 'hex')) AS `to_binary('AABB', to_binary('AABB', 'hex'))`;
SELECT to_binary(to_binary('AABB', 'hex'), 'hex') AS `to_binary(to_binary('AABB', 'hex'), 'hex')`;
SELECT to_binary(to_binary('AABB', 'hex'), 'hex') AS `to_binary(to_binary('AABB', 'hex'), 'hex')`;
SELECT to_binary('AABB', 0.0) AS `to_binary('AABB', 0.0)`;
SELECT to_binary('hex', 'hex') AS `to_binary('hex', 'hex')`;
SELECT to_binary('AABB', 'hex') AS `to_binary('AABB', 'hex')` LIMIT 1, 5;
SELECT to_binary('AABB', 'hex') AS `to_binary('AABB', 'hex')`;
SELECT to_binary(to_binary('00', 'hex'), 'hex') AS `to_binary(to_binary('00', 'hex'), 'hex')`;
SELECT to_binary('AABB', to_binary('AABB', 'hex')) AS `to_binary('AABB', to_binary('AABB', 'hex'))`;
SELECT to_binary('%', 'hex') AS `to_binary('%', 'hex')`;
SELECT to_binary('AABB', '') AS `to_binary('AABB', '')`;
SELECT to_binary(9223372036854775807, 'hex') AS `to_binary(9223372036854775807, 'hex')`;
SELECT to_binary('hex', 'hex') AS `to_binary('hex', 'hex')`;
SELECT to_binary('AABB', 'hex') AS `to_binary('AABB', 'hex')` GROUP BY to_binary('AABB', 'hex');
SELECT to_binary('AABB', NULL) AS `to_binary('AABB', NULL)`;
SELECT to_binary('AABB', 'hex') AS `to_binary('AABB', 'hex')` GROUP BY to_binary('AABB', 'hex');
SELECT to_binary('AABB', 'hex') AS `to_binary('AABB', 'hex')` WHERE 'k1';
SELECT to_binary('0', 'hex') AS `to_binary('0', 'hex')`;
SELECT to_binary('AABB', 'hex') AS `to_binary('AABB', 'hex')`;
SELECT to_binary('AABB', 'hex') AS `to_binary('AABB', 'hex')` LIMIT 0;
SELECT to_binary('hex', 'hex') AS `to_binary('hex', 'hex')`;
SELECT to_binary('AABB', 'AABB') AS `to_binary('AABB', 'AABB')`;
SELECT to_binary(-1, 'hex') AS `to_binary(-1, 'hex')`;
SELECT to_binary('AABB', 'hex') AS `to_binary('AABB', 'hex')` WHERE 'AABB';
SELECT to_binary('AABB', to_binary('AABB', 'hex')) AS `to_binary('AABB', to_binary('AABB', 'hex'))`;
SELECT to_binary(-1.0E308, 'hex') AS `to_binary(-1.0E308, 'hex')`;
SELECT to_binary(to_binary('AABB', 'hex'), 'hex') AS `to_binary(to_binary('AABB', 'hex'), 'hex')`;
SELECT to_binary('hex', 'hex') AS `to_binary('hex', 'hex')`;
SELECT to_binary('414243', CAST('hex' AS JSON)) AS `to_binary('414243', CAST('hex' AS JSON))`;
SELECT to_binary('414243', FALSE) AS `to_binary('414243', FALSE)`;
SELECT to_binary('414243', FALSE) AS `to_binary('414243', FALSE)`;
SELECT to_binary('hex', 'hex') AS `to_binary('hex', 'hex')`;
SELECT to_binary('1970-01-01', 'hex') AS `to_binary('1970-01-01', 'hex')`;
SELECT to_binary('414243', 'hex') AS `to_binary('414243', 'hex')` ORDER BY to_binary('414243', 'hex') DESC;
SELECT to_binary('414243', 'hex') AS `to_binary('414243', 'hex')` ORDER BY to_binary('414243', 'hex') ASC;
SELECT to_binary('hex', 'hex') AS `to_binary('hex', 'hex')`;
SELECT to_binary('9999-12-31 23:59:59', 'hex') AS `to_binary('9999-12-31 23:59:59', 'hex')`;
SELECT to_binary('414243', 'hex') AS `to_binary('414243', 'hex')`;
SELECT to_binary('414243', 'hex') AS `to_binary('414243', 'hex')` LIMIT 1, 1;
SELECT to_binary('414243', 9223372036854775807) AS `to_binary('414243', 9223372036854775807)`;
SELECT to_binary('414243', -2147483648) AS `to_binary('414243', -2147483648)`;
SELECT to_binary('414243', 0.0) AS `to_binary('414243', 0.0)`;
SELECT to_binary('414243', '0') AS `to_binary('414243', '0')`;
SELECT to_binary('414243', '01') AS `to_binary('414243', '01')`;
SELECT to_binary(json_query(CAST('414243' AS JSON), '$.a'), 'hex') AS `to_binary(json_query(CAST('414243' AS JSON), '$.a'), 'hex')`;
SELECT to_binary(json_length(CAST('414243' AS JSON)), 'hex') AS `to_binary(json_length(CAST('414243' AS JSON)), 'hex')`;
SELECT to_binary('414243', 'hex') AS `to_binary('414243', 'hex')` GROUP BY to_binary('414243', 'hex');
SELECT to_binary('414243', 'hex') AS `to_binary('414243', 'hex')` GROUP BY to_binary('414243', 'hex');
SELECT to_binary('414243', 'hex') AS `to_binary('414243', 'hex')`;
SELECT to_binary('414243', '414243') AS `to_binary('414243', '414243')`;
SELECT to_binary(to_binary('414243', 'hex'), 'hex') AS `to_binary(to_binary('414243', 'hex'), 'hex')`;
SELECT to_binary(0.0, 'hex') AS `to_binary(0.0, 'hex')`;
SELECT to_binary(to_binary('CAFE', 'hex'), 'hex') AS `to_binary(to_binary('CAFE', 'hex'), 'hex')`;
SELECT to_binary(9223372036854775807, 'hex') AS `to_binary(9223372036854775807, 'hex')`;
SELECT to_binary('414243', '414243') AS `to_binary('414243', '414243')`;
SELECT to_binary(to_binary('414243', 'hex'), 'hex') AS `to_binary(to_binary('414243', 'hex'), 'hex')`;
SELECT to_binary(CAST('414243' AS JSON)->'$', 'hex') AS `to_binary(CAST('414243' AS JSON)->'$', 'hex')`;