SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1`;
SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`) SELECT @a AS `@a`, @b AS `@b` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1`;
SELECT @a AS `@a` FROM `srfuzz_mut_477`.`t1`;
SELECT @a AS `@a` FROM `srfuzz_mut_477`.`t1`;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1`;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a,@b,@c SEPARATOR ',') AS `group_concat(@a,@b,@c SEPARATOR ',')` FROM `cte_1`;
SELECT @test AS `@test`;
SELECT @test AS `@test`;
SELECT @test AS `@test`;
SELECT @test AS `@test`;
SELECT @test AS `@test`;
SELECT @test AS `@test`;
SELECT @test AS `@test`;
SELECT @test AS `@test`;
SELECT @test AS `@test`;
SELECT @test AS `@test`;
SELECT @test AS `@test`;
SELECT @test AS `@test`;
SELECT (@test) = (concat(upper('a'), '\\', '"', '\'', 'b')) AS `(@test) = (concat(upper('a'), '\\', '"', '\'', 'b'))`;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar`;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar`;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar`;
SELECT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint`;
SELECT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint`;
SELECT @xVar AS `@xVar`, @yVar AS `@yVar`, @zVar AS `@zVar`;
SELECT @xVar AS `@xVar`, @yVar AS `@yVar`, @zVar AS `@zVar`;
SELECT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint`;
SELECT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint`;
SELECT @secondVar AS `@secondVar`, @thirdVar AS `@thirdVar`;
SELECT @a AS `@a`, @b AS `@b` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` UNION SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1`;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1` GROUP BY @a, @b;
SELECT @a AS `@a`, @b AS `@b` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` EXCEPT SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1`;
SELECT @a AS `@a`, @b AS `@b` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT DISTINCT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1`;
SELECT DISTINCT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1`;
SELECT @a AS `@a`, @b AS `@b` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` EXCEPT SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1`;
SELECT @a AS `@a`, @b AS `@b` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` INTERSECT SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1`;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT @a AS `@a`, @b AS `@b` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1`;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1` ORDER BY @b DESC;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1` GROUP BY @a, @b;
SELECT @a AS `@a`, @b AS `@b` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1` RIGHT OUTER JOIN (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `srfuzz_n1` ON 1 = 1;
SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2` LIMIT 7, 2;
SELECT DISTINCT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`) SELECT `t2`.`c0`, `t2`.`c1`, `t2`.`c2`, `t2`.`c3` FROM `srfuzz_n1` AS t2;
SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2` LIMIT 0;
SELECT `t2`.`c0`, `t2`.`c1`, `t2`.`c2`, `t2`.`c3`, `srfuzz_n1`.`e` FROM (SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`) `t2` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT `t2`.`c0`, `t2`.`c1`, `t2`.`c2`, `t2`.`c3` FROM (SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2` EXCEPT SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`) `t2`;
SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT DISTINCT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`;
SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT DISTINCT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`;
SELECT `t2`.`c0`, `t2`.`c1`, `t2`.`c2`, `t2`.`c3`, `srfuzz_n1`.`c0`, `srfuzz_n1`.`c1`, `srfuzz_n1`.`c2`, `srfuzz_n1`.`c3` FROM (SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`) `t2` RIGHT OUTER JOIN (SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`) `srfuzz_n1` ON 1 = 1;
SELECT `t2`.`c0`, `t2`.`c1`, `t2`.`c2`, `t2`.`c3`, `srfuzz_n1`.`c0`, `srfuzz_n1`.`c1`, `srfuzz_n1`.`c2`, `srfuzz_n1`.`c3` FROM (SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`) `t2` RIGHT OUTER JOIN (SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`) `srfuzz_n1` ON 1 = 1;
SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT `t2`.`c0`, `t2`.`c1`, `t2`.`c2`, `t2`.`c3`, `srfuzz_n1`.`c0`, `srfuzz_n1`.`c1`, `srfuzz_n1`.`c2`, `srfuzz_n1`.`c3` FROM (SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`) `t2` RIGHT OUTER JOIN (SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`) `srfuzz_n1` ON 1 = 1;
SELECT `t2`.`c0`, `t2`.`c1`, `t2`.`c2`, `t2`.`c3` FROM (SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2` EXCEPT SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`) `t2`;
SELECT `t2`.`c0`, `t2`.`c1`, `t2`.`c2`, `t2`.`c3`, `srfuzz_n1`.`e` FROM (SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`) `t2` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`) SELECT `t2`.`c0`, `t2`.`c1`, `t2`.`c2`, `t2`.`c3` FROM `srfuzz_n1` AS t2;
SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT @a AS `@a`, CAST((@b) AS JSON)->'k' AS `CAST((@b) AS JSON)->'k'` FROM `srfuzz_mut_477`.`t1`;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT @a AS `@a`, CAST((@b) AS ARRAY<ARRAY<INT>>) AS `CAST((@b) AS ARRAY<ARRAY<INT>>)` FROM `srfuzz_mut_477`.`t1`;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1` ORDER BY @b DESC;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1` LIMIT 1, 100;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1` GROUP BY @a, @b;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1` LIMIT 100;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT @a AS `@a`, @b AS `@b` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` UNION ALL SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1`;
SELECT DISTINCT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1`;
SELECT DISTINCT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1`;
SELECT @a AS `@a`, @b AS `@b` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` UNION SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1`;
WITH `cte_1` AS (SELECT `t2`.`c0`, `t2`.`c1`, `t2`.`c2`, `t2`.`c3` FROM (WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`) SELECT `srfuzz_n1`.`c0`, `srfuzz_n1`.`c1`, `srfuzz_n1`.`c2`, `srfuzz_n1`.`c3` FROM `srfuzz_n1`) `t2`) SELECT @a AS `@a`, @b AS `@b` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`) SELECT @a AS `@a`, @b AS `@b` FROM (SELECT `cte_1`.`c0`, `cte_1`.`c1`, `cte_1`.`c2`, `cte_1`.`c3` FROM `cte_1` INTERSECT SELECT `cte_1`.`c0`, `cte_1`.`c1`, `cte_1`.`c2`, `cte_1`.`c3` FROM `cte_1`) `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`) SELECT sum(@a) OVER () AS `sum(@a) OVER ()`, @b AS `@b` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`) SELECT CAST((CAST((CAST((@a) AS TIME)) AS VARCHAR(1))) AS ARRAY<MAP<VARCHAR(16),INT>>) AS `CAST((CAST((CAST((@a) AS TIME)) AS VARCHAR(1))) AS ARRAY<MAP<VARCHAR(16),INT>>)`, @b AS `@b` FROM `cte_1`;
WITH `cte_1` AS (SELECT `t2`.`c0`, `t2`.`c1`, `t2`.`c2`, `t2`.`c3` FROM (SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2` INTERSECT SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`) `t2`) SELECT @a AS `@a`, @b AS `@b` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`) SELECT @a AS `@a`, CAST((@b) AS DECIMAL128(38,0)) AS `CAST((@b) AS DECIMAL128(38,0))` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2` LIMIT 5) SELECT @a AS `@a`, @b AS `@b` FROM `cte_1`;
WITH `cte_1` AS (SELECT `t2`.`c0`, `t2`.`c1`, `t2`.`c2`, `t2`.`c3` FROM (SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2` UNION ALL SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`) `t2`) SELECT @a AS `@a`, @b AS `@b` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`) SELECT @a AS `@a`, json_length(CAST((@b) AS JSON)) AS `json_length(CAST((@b) AS JSON))` FROM `cte_1`;
WITH `cte_1` AS (SELECT DISTINCT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`) SELECT @a AS `@a`, @b AS `@b` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`) SELECT @a AS `@a`, @b AS `@b` FROM (SELECT `cte_1`.`c0`, `cte_1`.`c1`, `cte_1`.`c2`, `cte_1`.`c3` FROM `cte_1`) `cte_1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
WITH `cte_1` AS (SELECT `t2`.`c0`, `t2`.`c1`, `t2`.`c2`, `t2`.`c3` FROM (SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2` EXCEPT SELECT `srfuzz_mut_477`.`t2`.`c0`, `srfuzz_mut_477`.`t2`.`c1`, `srfuzz_mut_477`.`t2`.`c2`, `srfuzz_mut_477`.`t2`.`c3` FROM `srfuzz_mut_477`.`t2`) `t2`) SELECT @a AS `@a`, @b AS `@b` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1` HAVING (count(*)) > 1;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(CAST((@a) AS LARGEINT) SEPARATOR ',') AS `group_concat(CAST((@a) AS LARGEINT) SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(',' SEPARATOR ',') AS `group_concat(',' SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(',' SEPARATOR ',') AS `group_concat(',' SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM (SELECT `cte_1`.`c0`, `cte_1`.`c1`, `cte_1`.`c2`, `cte_1`.`c3` FROM `cte_1`) `cte_1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR '0') AS `group_concat(@a SEPARATOR '0')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `t1`.`c0`, `t1`.`c1`, `t1`.`c2`, `t1`.`c3` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` EXCEPT SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT CAST((group_concat(@a SEPARATOR ',')) AS JSON)->'k' AS `CAST((group_concat(@a SEPARATOR ',')) AS JSON)->'k'` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(',' SEPARATOR ',') AS `group_concat(',' SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT DISTINCT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1` ORDER BY group_concat(@a SEPARATOR ',') ASC NULLS LAST;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(',' SEPARATOR ',') AS `group_concat(',' SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR @a) AS `group_concat(@a SEPARATOR @a)` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) , `srfuzz_n1` AS (SELECT `cte_1`.`c0`, `cte_1`.`c1`, `cte_1`.`c2`, `cte_1`.`c3` FROM `cte_1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `srfuzz_n1` AS cte_1;
WITH `cte_1` AS (SELECT `t1`.`c0`, `t1`.`c1`, `t1`.`c2`, `t1`.`c3`, `srfuzz_n1`.`c0`, `srfuzz_n1`.`c1`, `srfuzz_n1`.`c2`, `srfuzz_n1`.`c3` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1` RIGHT OUTER JOIN (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `srfuzz_n1` ON 1 = 1) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `t1`.`c0`, `t1`.`c1`, `t1`.`c2`, `t1`.`c3` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` EXCEPT SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1` LIMIT 7, 100;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@bVar SEPARATOR ',') AS `group_concat(@bVar SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@xVar SEPARATOR ',') AS `group_concat(@xVar SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR @a) AS `group_concat(@a SEPARATOR @a)` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` LIMIT 7, 1) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT DISTINCT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1` LIMIT 7, 2;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM (SELECT `cte_1`.`c0`, `cte_1`.`c1`, `cte_1`.`c2`, `cte_1`.`c3` FROM `cte_1` INTERSECT SELECT `cte_1`.`c0`, `cte_1`.`c1`, `cte_1`.`c2`, `cte_1`.`c3` FROM `cte_1`) `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1` HAVING (count(*)) > 0;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1` HAVING (count(*)) < 10;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'))) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1` LIMIT 0;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1` LIMIT 5;
WITH `cte_1` AS (SELECT DISTINCT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(',' SEPARATOR ',') AS `group_concat(',' SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(get_json_string(CAST((@a) AS JSON), '$.a') SEPARATOR ',') AS `group_concat(get_json_string(CAST((@a) AS JSON), '$.a') SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat('"' SEPARATOR ',') AS `group_concat('"' SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1` ORDER BY group_concat(@a SEPARATOR ',') ASC;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(',' SEPARATOR ',') AS `group_concat(',' SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR '\'') AS `group_concat(@a SEPARATOR '\'')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a SEPARATOR ',') AS `group_concat(@a SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(concat(upper('a'), '\\', '"', '\'', 'b') SEPARATOR ',') AS `group_concat(concat(upper('a'), '\\', '"', '\'', 'b') SEPARATOR ',')` FROM `cte_1`;
SELECT @a AS `@a` FROM `srfuzz_mut_477`.`t1` ORDER BY @a ASC;
SELECT DISTINCT @a AS `@a` FROM `srfuzz_mut_477`.`t1`;
SELECT count(@a) OVER () AS `count(@a) OVER ()` FROM `srfuzz_mut_477`.`t1`;
SELECT @a AS `@a` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1`;
SELECT CAST((CAST((@a) AS LARGEINT)) AS DECIMAL128(38,0)) AS `CAST((CAST((@a) AS LARGEINT)) AS DECIMAL128(38,0))` FROM `srfuzz_mut_477`.`t1`;
SELECT @a AS `@a` FROM `srfuzz_mut_477`.`t1` GROUP BY @a;
SELECT min(@a) OVER () AS `min(@a) OVER ()` FROM `srfuzz_mut_477`.`t1`;
SELECT @a AS `@a` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT @a AS `@a` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` UNION ALL SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1`;
SELECT @a AS `@a` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1` RIGHT OUTER JOIN (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `srfuzz_n1` ON 1 = 1;
SELECT @a AS `@a` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1`;
SELECT CAST((CAST((CAST((@a) AS DECIMAL128(38,0))) AS BOOLEAN)) AS MAP<VARCHAR(16),INT>) AS `CAST((CAST((CAST((@a) AS DECIMAL128(38,0))) AS BOOLEAN)) AS MAP<VARCHAR(16),INT>)` FROM `srfuzz_mut_477`.`t1`;
SELECT @a AS `@a` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1` RIGHT OUTER JOIN (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `srfuzz_n1` ON 1 = 1;
SELECT @a AS `@a` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1` RIGHT OUTER JOIN (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `srfuzz_n1` ON 1 = 1;
SELECT @a AS `@a` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` UNION ALL SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1`;
SELECT count(@a) OVER () AS `count(@a) OVER ()` FROM `srfuzz_mut_477`.`t1`;
SELECT @a AS `@a` FROM `srfuzz_mut_477`.`t1` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT @a AS `@a` FROM `srfuzz_mut_477`.`t1` ORDER BY @a DESC;
SELECT CAST((CAST((@a) AS DATE)) AS TIME) AS `CAST((CAST((@a) AS DATE)) AS TIME)` FROM `srfuzz_mut_477`.`t1`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_n1` AS t1;
SELECT @a AS `@a`, @b AS `@b` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` INTERSECT SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1`;
SELECT @a AS `@a`, @b AS `@b` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` EXCEPT SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1`;
SELECT sum(@a) OVER () AS `sum(@a) OVER ()`, @b AS `@b` FROM `srfuzz_mut_477`.`t1`;
SELECT @a AS `@a`, @b AS `@b` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1` RIGHT OUTER JOIN (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `srfuzz_n1` ON 1 = 1;
SELECT @a AS `@a`, @b AS `@b` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1` RIGHT OUTER JOIN (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `srfuzz_n1` ON 1 = 1;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1` GROUP BY @a, @b;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1` LIMIT 7, 0;
SELECT DISTINCT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1`;
SELECT @a AS `@a`, @b AS `@b` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` INTERSECT SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1`;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1` GROUP BY @a, @b;
SELECT @a AS `@a`, @b AS `@b` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` UNION ALL SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1`;
SELECT @a AS `@a`, @b AS `@b` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` INTERSECT SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1`;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT @a AS `@a`, @b AS `@b` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` UNION ALL SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1`;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1` ORDER BY @b DESC NULLS FIRST;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1` LIMIT 1, 100;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1` LIMIT 5;
SELECT @a AS `@a`, @b AS `@b` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` EXCEPT SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1`;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT DISTINCT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1`;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1` LIMIT 0;
SELECT @a AS `@a`, @b AS `@b` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` UNION ALL SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1`;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1` ORDER BY @b ASC;
SELECT @a AS `@a`, @b AS `@b` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` INTERSECT SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1`;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1` GROUP BY @a, @b;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1` LIMIT 5;
SELECT @a AS `@a`, @b AS `@b` FROM `srfuzz_mut_477`.`t1` LIMIT 5;
SELECT @a AS `@a`, @b AS `@b` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@b,@b,@c SEPARATOR ',') AS `group_concat(@b,@b,@c SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `t1`.`c0`, `t1`.`c1`, `t1`.`c2`, `t1`.`c3` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` UNION ALL SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1`) SELECT group_concat(@a,@b,@c SEPARATOR ',') AS `group_concat(@a,@b,@c SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` LIMIT 100) SELECT group_concat(@a,@b,@c SEPARATOR ',') AS `group_concat(@a,@b,@c SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a,@b,@c SEPARATOR ',') AS `group_concat(@a,@b,@c SEPARATOR ',')` FROM (SELECT `cte_1`.`c0`, `cte_1`.`c1`, `cte_1`.`c2`, `cte_1`.`c3` FROM `cte_1`) `cte_1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@c,@b,@c SEPARATOR ',') AS `group_concat(@c,@b,@c SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a,@b,@c SEPARATOR ',') AS `group_concat(@a,@b,@c SEPARATOR ',')` FROM `cte_1` HAVING (count(*)) > 1;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a,@b,@c SEPARATOR NULL) AS `group_concat(@a,@b,@c SEPARATOR NULL)` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a,@thirdVar,@c SEPARATOR ',') AS `group_concat(@a,@thirdVar,@c SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `t1`.`c0`, `t1`.`c1`, `t1`.`c2`, `t1`.`c3` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` UNION ALL SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1`) SELECT group_concat(@a,@b,@c SEPARATOR ',') AS `group_concat(@a,@b,@c SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` LIMIT 0) SELECT group_concat(@a,@b,@c SEPARATOR ',') AS `group_concat(@a,@b,@c SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@b,@b,@c SEPARATOR ',') AS `group_concat(@b,@b,@c SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a,@b,@c SEPARATOR '0000-00-00') AS `group_concat(@a,@b,@c SEPARATOR '0000-00-00')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a,@b,@c SEPARATOR ',') AS `group_concat(@a,@b,@c SEPARATOR ',')` FROM (SELECT `cte_1`.`c0`, `cte_1`.`c1`, `cte_1`.`c2`, `cte_1`.`c3` FROM `cte_1` UNION ALL SELECT `cte_1`.`c0`, `cte_1`.`c1`, `cte_1`.`c2`, `cte_1`.`c3` FROM `cte_1`) `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a,@b,@c SEPARATOR ',') AS `group_concat(@a,@b,@c SEPARATOR ',')` FROM (SELECT `cte_1`.`c0`, `cte_1`.`c1`, `cte_1`.`c2`, `cte_1`.`c3` FROM `cte_1` UNION ALL SELECT `cte_1`.`c0`, `cte_1`.`c1`, `cte_1`.`c2`, `cte_1`.`c3` FROM `cte_1`) `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a,@b,@b SEPARATOR ',') AS `group_concat(@a,@b,@b SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a,@b,@c SEPARATOR ',') AS `group_concat(@a,@b,@c SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a,@b,@a SEPARATOR ',') AS `group_concat(@a,@b,@a SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a,',',@c SEPARATOR ',') AS `group_concat(@a,',',@c SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a,@b,@c SEPARATOR ',') AS `group_concat(@a,@b,@c SEPARATOR ',')` FROM `cte_1` HAVING (count(*)) < 10;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a,@c,@c SEPARATOR ',') AS `group_concat(@a,@c,@c SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a,@a,@c SEPARATOR ',') AS `group_concat(@a,@a,@c SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a,@a,@c SEPARATOR ',') AS `group_concat(@a,@a,@c SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a,@b,@c SEPARATOR ',') AS `group_concat(@a,@b,@c SEPARATOR ',')` FROM (SELECT `cte_1`.`c0`, `cte_1`.`c1`, `cte_1`.`c2`, `cte_1`.`c3` FROM `cte_1`) `cte_1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'))) SELECT group_concat(@a,@b,@c SEPARATOR ',') AS `group_concat(@a,@b,@c SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a,@b,@c SEPARATOR @aVar) AS `group_concat(@a,@b,@c SEPARATOR @aVar)` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a,@b,@b SEPARATOR ',') AS `group_concat(@a,@b,@b SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a,@b,@c SEPARATOR ',') AS `group_concat(@a,@b,@c SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a,@b,@c SEPARATOR '1970-01-01') AS `group_concat(@a,@b,@c SEPARATOR '1970-01-01')` FROM `cte_1`;
WITH `cte_1` AS (SELECT DISTINCT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a,@b,@c SEPARATOR ',') AS `group_concat(@a,@b,@c SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a,@b,@c SEPARATOR ',') AS `group_concat(@a,@b,@c SEPARATOR ',')` FROM `cte_1`;
WITH `cte_1` AS (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) SELECT group_concat(@a,@b,@c SEPARATOR ',') AS `group_concat(@a,@b,@c SEPARATOR ',')` FROM (SELECT `cte_1`.`c0`, `cte_1`.`c1`, `cte_1`.`c2`, `cte_1`.`c3` FROM `cte_1`) `cte_1`;
WITH `cte_1` AS (SELECT `t1`.`c0`, `t1`.`c1`, `t1`.`c2`, `t1`.`c3` FROM (SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1` EXCEPT SELECT `srfuzz_mut_477`.`t1`.`c0`, `srfuzz_mut_477`.`t1`.`c1`, `srfuzz_mut_477`.`t1`.`c2`, `srfuzz_mut_477`.`t1`.`c3` FROM `srfuzz_mut_477`.`t1`) `t1`) SELECT group_concat(@a,@b,@c SEPARATOR ',') AS `group_concat(@a,@b,@c SEPARATOR ',')` FROM `cte_1`;
SELECT @test AS `@test` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT DISTINCT @test AS `@test`;
SELECT max(@test) OVER () AS `max(@test) OVER ()`;
SELECT count(@test) OVER () AS `count(@test) OVER ()`;
SELECT @test AS `@test` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT @test AS `@test` GROUP BY @test;
SELECT max(@test) OVER () AS `max(@test) OVER ()`;
SELECT @test AS `@test` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT @test AS `@test` ORDER BY @test DESC;
SELECT @test AS `@test` ORDER BY @test ASC;
SELECT @test AS `@test` GROUP BY @test;
SELECT DISTINCT @test AS `@test`;
SELECT min(@test) OVER () AS `min(@test) OVER ()`;
SELECT CAST((@test) AS JSON)->'k' AS `CAST((@test) AS JSON)->'k'`;
SELECT DISTINCT @test AS `@test`;
SELECT @test AS `@test` LIMIT 2;
SELECT @test AS `@test` LIMIT 1;
SELECT @test AS `@test` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT avg(@test) OVER () AS `avg(@test) OVER ()`;
SELECT get_json_string(CAST((@test) AS JSON), '$.a') AS `get_json_string(CAST((@test) AS JSON), '$.a')`;
SELECT @test AS `@test` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT DISTINCT @test AS `@test`;
SELECT @test AS `@test` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT @test AS `@test` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT DISTINCT @test AS `@test`;
SELECT CAST((@test) AS JSON)->'$' AS `CAST((@test) AS JSON)->'$'`;
SELECT CAST((CAST((@test) AS FLOAT)) AS BOOLEAN) AS `CAST((CAST((@test) AS FLOAT)) AS BOOLEAN)`;
SELECT min(@test) OVER () AS `min(@test) OVER ()`;
SELECT CAST((@test) AS JSON)->'k' AS `CAST((@test) AS JSON)->'k'`;
SELECT @test AS `@test` GROUP BY @test;
SELECT json_length(CAST((@test) AS JSON)) AS `json_length(CAST((@test) AS JSON))`;
SELECT @test AS `@test` GROUP BY @test;
SELECT @test AS `@test` ORDER BY @test ASC NULLS LAST;
SELECT count(@test) OVER () AS `count(@test) OVER ()`;
SELECT avg(@test) OVER () AS `avg(@test) OVER ()`;
SELECT @test AS `@test` ORDER BY @test ASC;
SELECT DISTINCT @test AS `@test`;
SELECT @test AS `@test` GROUP BY @test;
SELECT avg(@test) OVER () AS `avg(@test) OVER ()`;
SELECT get_json_string(CAST((@test) AS JSON), '$.a') AS `get_json_string(CAST((@test) AS JSON), '$.a')`;
SELECT @test AS `@test` LIMIT 0;
SELECT CAST((@test) AS VARCHAR(65533)) AS `CAST((@test) AS VARCHAR(65533))`;
SELECT json_query(CAST((@test) AS JSON), '$.a') AS `json_query(CAST((@test) AS JSON), '$.a')`;
SELECT @test AS `@test` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT @test AS `@test` ORDER BY @test DESC;
SELECT @test AS `@test` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT @test AS `@test` GROUP BY @test;
SELECT @test AS `@test` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT json_length(CAST((@test) AS JSON)) AS `json_length(CAST((@test) AS JSON))`;
SELECT @test AS `@test` GROUP BY @test;
SELECT @test AS `@test` GROUP BY @test;
SELECT @test AS `@test` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT @test AS `@test` ORDER BY @test DESC;
SELECT @test AS `@test` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT json_length(CAST((@test) AS JSON)) AS `json_length(CAST((@test) AS JSON))`;
SELECT @test AS `@test` LIMIT 100;
SELECT @test AS `@test` ORDER BY @test ASC NULLS LAST;
SELECT @test AS `@test` LIMIT 5;
SELECT @test AS `@test` LIMIT 7, 0;
SELECT @test AS `@test` GROUP BY @test;
SELECT @test AS `@test` GROUP BY @test;
SELECT @test AS `@test` ORDER BY @test DESC;
SELECT @test AS `@test` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT count(@test) OVER () AS `count(@test) OVER ()`;
SELECT @test AS `@test` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT @test AS `@test` ORDER BY @test DESC;
SELECT CAST((CAST((CAST((@test) AS DECIMAL128(27,9))) AS BIGINT)) AS DOUBLE) AS `CAST((CAST((CAST((@test) AS DECIMAL128(27,9))) AS BIGINT)) AS DOUBLE)`;
SELECT DISTINCT @test AS `@test`;
SELECT max(@test) OVER () AS `max(@test) OVER ()`;
SELECT @test AS `@test` LIMIT 7, 0;
SELECT @test AS `@test` ORDER BY @test DESC;
SELECT @test AS `@test` LIMIT 5;
SELECT get_json_string(CAST((@test) AS JSON), '$.a') AS `get_json_string(CAST((@test) AS JSON), '$.a')`;
SELECT sum(@test) OVER () AS `sum(@test) OVER ()`;
SELECT CAST((@test) AS JSON)->'$.a' AS `CAST((@test) AS JSON)->'$.a'`;
SELECT @test AS `@test` GROUP BY @test;
SELECT CAST((CAST((@test) AS VARCHAR(1))) AS DECIMAL128(38,37)) AS `CAST((CAST((@test) AS VARCHAR(1))) AS DECIMAL128(38,37))`;
SELECT @test AS `@test` LIMIT 1, 1;
SELECT @test AS `@test` ORDER BY @test ASC;
SELECT get_json_string(CAST((@test) AS JSON), '$.a') AS `get_json_string(CAST((@test) AS JSON), '$.a')`;
SELECT @test AS `@test` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT CAST((@test) AS JSON)->'$' AS `CAST((@test) AS JSON)->'$'`;
SELECT CAST((@test) AS JSON)->'k' AS `CAST((@test) AS JSON)->'k'`;
SELECT CAST((CAST((@test) AS TINYINT)) AS DOUBLE) AS `CAST((CAST((@test) AS TINYINT)) AS DOUBLE)`;
SELECT @test AS `@test` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT CAST((@test) AS JSON)->'$' AS `CAST((@test) AS JSON)->'$'`;
SELECT @test AS `@test` GROUP BY @test;
SELECT DISTINCT @test AS `@test`;
SELECT @test AS `@test` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT DISTINCT @test AS `@test`;
SELECT @test AS `@test` LIMIT 0;
SELECT min(@test) OVER () AS `min(@test) OVER ()`;
SELECT CAST((CAST((@test) AS VARBINARY)) AS VARCHAR(1)) AS `CAST((CAST((@test) AS VARBINARY)) AS VARCHAR(1))`;
SELECT DISTINCT @test AS `@test`;
SELECT CAST((CAST((CAST((@test) AS BOOLEAN)) AS JSON)) AS BIGINT) AS `CAST((CAST((CAST((@test) AS BOOLEAN)) AS JSON)) AS BIGINT)`;
SELECT CAST((@test) AS JSON)->'$.a' AS `CAST((@test) AS JSON)->'$.a'`;
SELECT CAST((@test) AS JSON)->'k' AS `CAST((@test) AS JSON)->'k'`;
SELECT @test AS `@test` GROUP BY @test;
SELECT sum(@test) OVER () AS `sum(@test) OVER ()`;
SELECT @test AS `@test` GROUP BY @test;
SELECT json_query(CAST((@test) AS JSON), '$.a') AS `json_query(CAST((@test) AS JSON), '$.a')`;
SELECT @test AS `@test` GROUP BY @test;
SELECT @test AS `@test` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT min(@test) OVER () AS `min(@test) OVER ()`;
SELECT @test AS `@test` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT @test AS `@test` ORDER BY @test ASC;
SELECT @test AS `@test` ORDER BY @test DESC;
SELECT @test AS `@test` GROUP BY @test;
SELECT CAST((@test) AS JSON)->'$.a' AS `CAST((@test) AS JSON)->'$.a'`;
SELECT @test AS `@test` GROUP BY @test;
SELECT @test AS `@test` GROUP BY @test;
SELECT @test AS `@test` GROUP BY @test;
SELECT DISTINCT @test AS `@test`;
SELECT @test AS `@test` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT CAST((CAST((@test) AS SMALLINT)) AS DECIMAL128(38,0)) AS `CAST((CAST((@test) AS SMALLINT)) AS DECIMAL128(38,0))`;
SELECT @test AS `@test` ORDER BY @test DESC;
SELECT @test AS `@test` LIMIT 7, 0;
SELECT @test AS `@test` LIMIT 1, 100;
SELECT @test AS `@test` GROUP BY @test;
SELECT min(@test) OVER () AS `min(@test) OVER ()`;
SELECT DISTINCT @test AS `@test`;
SELECT @test AS `@test` GROUP BY @test;
SELECT sum(@test) OVER () AS `sum(@test) OVER ()`;
SELECT @test AS `@test` LIMIT 1, 2;
SELECT @test AS `@test` LIMIT 2;
SELECT @test AS `@test` LIMIT 5;
SELECT @test AS `@test` GROUP BY @test;
SELECT DISTINCT @test AS `@test`;
SELECT @test AS `@test` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT (@test) = (concat(upper('a'), '\\', CAST(NULL AS JSON), '\'', 'b')) AS `(@test) = (concat(upper('a'), '\\', CAST(NULL AS JSON), '\'', 'b'))`;
SELECT (@test) = (concat(upper('a'), '\\', '"', '\'', 'b')) AS `(@test) = (concat(upper('a'), '\\', '"', '\'', 'b'))` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT (@test) = (concat(upper(@xVar), '\\', '"', '\'', 'b')) AS `(@test) = (concat(upper(@xVar), '\\', '"', '\'', 'b'))`;
SELECT 'a' = (concat(upper('a'), '\\', '"', '\'', 'b')) AS `'a' = (concat(upper('a'), '\\', '"', '\'', 'b'))`;
SELECT (@test) = (@cVar) AS `(@test) = (@cVar)`;
SELECT (@test) = (concat(upper('a'), -9223372036854775808, '"', '\'', 'b')) AS `(@test) = (concat(upper('a'), -9223372036854775808, '"', '\'', 'b'))`;
SELECT (@test) = (concat(upper('a'), '\\', '"', '\'', upper('a'))) AS `(@test) = (concat(upper('a'), '\\', '"', '\'', upper('a')))`;
SELECT (@test) = (concat(upper('a'), '\\', '"', '\'', 'b')) AS `(@test) = (concat(upper('a'), '\\', '"', '\'', 'b'))` ORDER BY (@test) = (concat(upper('a'), '\\', '"', '\'', 'b')) ASC NULLS LAST;
SELECT (@test) = (concat(ceil('a'), '\\', '"', '\'', 'b')) AS `(@test) = (concat(ceil('a'), '\\', '"', '\'', 'b'))`;
SELECT (@test) = (concat(upper('a'), '\\', '"', '\'', 'b')) AS `(@test) = (concat(upper('a'), '\\', '"', '\'', 'b'))`;
SELECT (@test) = (concat(upper('a'), '\\', '"', '\'', 'b')) AS `(@test) = (concat(upper('a'), '\\', '"', '\'', 'b'))` LIMIT 7, 2;
SELECT (@test) = (concat(upper('a'), '\\', '"', '\'', '0000-00-00')) AS `(@test) = (concat(upper('a'), '\\', '"', '\'', '0000-00-00'))`;
SELECT (@test) = (concat(lower('a'), '\\', '"', '\'', 'b')) AS `(@test) = (concat(lower('a'), '\\', '"', '\'', 'b'))`;
SELECT (@test) = (concat(upper('a'), '\\', '"', '\'', 'b')) AS `(@test) = (concat(upper('a'), '\\', '"', '\'', 'b'))` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT (@test) = (concat(upper('a'), NULL, '"', '\'', 'b')) AS `(@test) = (concat(upper('a'), NULL, '"', '\'', 'b'))`;
SELECT (@test) = (concat(upper('a'), '\\', '"', '\'', 'b')) AS `(@test) = (concat(upper('a'), '\\', '"', '\'', 'b'))` LIMIT 2;
SELECT DISTINCT (@test) = (concat(upper('a'), '\\', '"', '\'', 'b')) AS `(@test) = (concat(upper('a'), '\\', '"', '\'', 'b'))`;
SELECT sum((@test) = (concat(upper('a'), '\\', '"', '\'', 'b'))) OVER () AS `sum((@test) = (concat(upper('a'), '\\', '"', '\'', 'b'))) OVER ()`;
SELECT (@test) = (concat(char_length('a'), '\\', '"', '\'', 'b')) AS `(@test) = (concat(char_length('a'), '\\', '"', '\'', 'b'))`;
SELECT (@test) = (concat(upper('a'), '\\', '"', '\'', 'b')) AS `(@test) = (concat(upper('a'), '\\', '"', '\'', 'b'))` GROUP BY (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT (@test) = (concat(upper('a'), '\\', '"', '\'', 'b')) AS `(@test) = (concat(upper('a'), '\\', '"', '\'', 'b'))` LIMIT 2;
SELECT (@test) = (concat(upper('a'), '\\', repeat('x', 65536), '\'', 'b')) AS `(@test) = (concat(upper('a'), '\\', repeat('x', 65536), '\'', 'b'))`;
SELECT (@test) = (concat(upper(@test), '\\', '"', '\'', 'b')) AS `(@test) = (concat(upper(@test), '\\', '"', '\'', 'b'))`;
SELECT (@test) = (concat(upper('a'), @test, '"', '\'', 'b')) AS `(@test) = (concat(upper('a'), @test, '"', '\'', 'b'))`;
SELECT (@test) = (concat(upper('a'), '\\', '"', '\'', 'b')) AS `(@test) = (concat(upper('a'), '\\', '"', '\'', 'b'))` GROUP BY (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT (@test) = (concat(upper('a'), 'b', '"', '\'', 'b')) AS `(@test) = (concat(upper('a'), 'b', '"', '\'', 'b'))`;
SELECT (@test) = (concat(upper('a'), '\\', @secondVar, '\'', 'b')) AS `(@test) = (concat(upper('a'), '\\', @secondVar, '\'', 'b'))`;
SELECT (@test) = (concat(upper('a'), '\\', '"', '\'', 0.0)) AS `(@test) = (concat(upper('a'), '\\', '"', '\'', 0.0))`;
SELECT (@test) = (concat(upper('a'), '\\', '"', '\'', 'b')) AS `(@test) = (concat(upper('a'), '\\', '"', '\'', 'b'))` ORDER BY (@test) = (concat(upper('a'), '\\', '"', '\'', 'b')) ASC;
SELECT (json_length(CAST((@test) AS JSON))) = (concat(upper('a'), '\\', '"', '\'', 'b')) AS `(json_length(CAST((@test) AS JSON))) = (concat(upper('a'), '\\', '"', '\'', 'b'))`;
SELECT (@test) = (concat(upper('a'), '\\', '"', TRUE, 'b')) AS `(@test) = (concat(upper('a'), '\\', '"', TRUE, 'b'))`;
SELECT (@test) = (concat(upper('a'), '\\', '"', '\'', 'b')) AS `(@test) = (concat(upper('a'), '\\', '"', '\'', 'b'))` ORDER BY (@test) = (concat(upper('a'), '\\', '"', '\'', 'b')) DESC;
SELECT (@test) = (concat(upper('a'), '\\', concat(upper('a'), '\\', '"', '\'', 'b'), '\'', 'b')) AS `(@test) = (concat(upper('a'), '\\', concat(upper('a'), '\\', '"', '\'', 'b'), '\'', 'b'))`;
SELECT (@test) = (concat(upper('a'), '\\', '"', '\'', 'b')) AS `(@test) = (concat(upper('a'), '\\', '"', '\'', 'b'))` GROUP BY (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar` LIMIT 1, 5;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar` ORDER BY @aVar DESC NULLS FIRST;
SELECT json_query(CAST((@aVar) AS JSON), '$.a') AS `json_query(CAST((@aVar) AS JSON), '$.a')`, @bVar AS `@bVar`, @cVar AS `@cVar`;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, json_query(CAST((@cVar) AS JSON), '$.a') AS `json_query(CAST((@cVar) AS JSON), '$.a')`;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, CAST((@cVar) AS JSON)->'$' AS `CAST((@cVar) AS JSON)->'$'`;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar` GROUP BY @aVar, @bVar, @cVar;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar` LIMIT 100;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar` GROUP BY @aVar, @bVar, @cVar;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar` LIMIT 0;
SELECT CAST((CAST((@aVar) AS BOOLEAN)) AS VARCHAR(65533)) AS `CAST((CAST((@aVar) AS BOOLEAN)) AS VARCHAR(65533))`, @bVar AS `@bVar`, @cVar AS `@cVar`;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar` GROUP BY @aVar, @bVar, @cVar;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar` ORDER BY @bVar DESC NULLS FIRST;
SELECT DISTINCT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar`;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar` LIMIT 1, 0;
SELECT @aVar AS `@aVar`, get_json_string(CAST((@bVar) AS JSON), '$.a') AS `get_json_string(CAST((@bVar) AS JSON), '$.a')`, @cVar AS `@cVar`;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar` LIMIT 100;
SELECT json_length(CAST((@aVar) AS JSON)) AS `json_length(CAST((@aVar) AS JSON))`, @bVar AS `@bVar`, @cVar AS `@cVar`;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar` GROUP BY @aVar, @bVar, @cVar;
SELECT DISTINCT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar`;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar` LIMIT 1, 100;
SELECT @aVar AS `@aVar`, CAST((@bVar) AS JSON)->'$' AS `CAST((@bVar) AS JSON)->'$'`, @cVar AS `@cVar`;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar` LIMIT 2;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar` GROUP BY @aVar, @bVar, @cVar;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, count(@cVar) OVER () AS `count(@cVar) OVER ()`;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar` ORDER BY @cVar DESC;
SELECT @aVar AS `@aVar`, CAST((@bVar) AS JSON)->'k' AS `CAST((@bVar) AS JSON)->'k'`, @cVar AS `@cVar`;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar` GROUP BY @aVar, @bVar, @cVar;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar` ORDER BY @aVar ASC;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar` ORDER BY @bVar ASC;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, CAST((@cVar) AS JSON)->'k' AS `CAST((@cVar) AS JSON)->'k'`;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar` ORDER BY @bVar ASC;
SELECT @aVar AS `@aVar`, CAST((@bVar) AS JSON)->'$.a' AS `CAST((@bVar) AS JSON)->'$.a'`, @cVar AS `@cVar`;
SELECT @aVar AS `@aVar`, avg(@bVar) OVER () AS `avg(@bVar) OVER ()`, @cVar AS `@cVar`;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar` LIMIT 1;
SELECT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar` ORDER BY @cVar DESC;
SELECT DISTINCT @aVar AS `@aVar`, @bVar AS `@bVar`, @cVar AS `@cVar`;
SELECT @aVar AS `@aVar`, json_query(CAST((@bVar) AS JSON), '$.a') AS `json_query(CAST((@bVar) AS JSON), '$.a')`, @cVar AS `@cVar`;
SELECT CAST((CAST((CAST((@aVarHint) AS VARBINARY)) AS VARCHAR(1))) AS LARGEINT) AS `CAST((CAST((CAST((@aVarHint) AS VARBINARY)) AS VARCHAR(1))) AS LARGEINT)`, @bVarHint AS `@bVarHint`;
SELECT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint` GROUP BY @aVarHint, @bVarHint;
SELECT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint` ORDER BY @bVarHint ASC;
SELECT DISTINCT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint`;
SELECT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint` ORDER BY @bVarHint DESC;
SELECT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint` GROUP BY @aVarHint, @bVarHint;
SELECT @aVarHint AS `@aVarHint`, get_json_string(CAST((@bVarHint) AS JSON), '$.a') AS `get_json_string(CAST((@bVarHint) AS JSON), '$.a')`;
SELECT json_query(CAST((@aVarHint) AS JSON), '$.a') AS `json_query(CAST((@aVarHint) AS JSON), '$.a')`, @bVarHint AS `@bVarHint`;
SELECT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint` ORDER BY @bVarHint DESC NULLS FIRST;
SELECT DISTINCT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint`;
SELECT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint` LIMIT 1;
SELECT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint` ORDER BY @bVarHint ASC;
SELECT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint` GROUP BY @aVarHint, @bVarHint;
SELECT DISTINCT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint`;
SELECT DISTINCT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint`;
SELECT @aVarHint AS `@aVarHint`, CAST((@bVarHint) AS JSON)->'$' AS `CAST((@bVarHint) AS JSON)->'$'`;
SELECT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint` LIMIT 0;
SELECT DISTINCT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint`;
SELECT CAST((@aVarHint) AS DECIMAL128(27,9)) AS `CAST((@aVarHint) AS DECIMAL128(27,9))`, @bVarHint AS `@bVarHint`;
SELECT @xVar AS `@xVar`, @yVar AS `@yVar`, @zVar AS `@zVar` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT @xVar AS `@xVar`, @yVar AS `@yVar`, @zVar AS `@zVar` ORDER BY @zVar ASC;
SELECT DISTINCT @xVar AS `@xVar`, @yVar AS `@yVar`, @zVar AS `@zVar`;
SELECT @xVar AS `@xVar`, @yVar AS `@yVar`, CAST((@zVar) AS BIGINT) AS `CAST((@zVar) AS BIGINT)`;
SELECT DISTINCT @xVar AS `@xVar`, @yVar AS `@yVar`, @zVar AS `@zVar`;
SELECT DISTINCT @xVar AS `@xVar`, @yVar AS `@yVar`, @zVar AS `@zVar`;
SELECT @xVar AS `@xVar`, @yVar AS `@yVar`, @zVar AS `@zVar` ORDER BY @zVar ASC;
SELECT @xVar AS `@xVar`, @yVar AS `@yVar`, @zVar AS `@zVar` GROUP BY @xVar, @yVar, @zVar;
SELECT DISTINCT @xVar AS `@xVar`, @yVar AS `@yVar`, @zVar AS `@zVar`;
SELECT DISTINCT @xVar AS `@xVar`, @yVar AS `@yVar`, @zVar AS `@zVar`;
SELECT @xVar AS `@xVar`, @yVar AS `@yVar`, @zVar AS `@zVar` LIMIT 7, 1;
SELECT @xVar AS `@xVar`, @yVar AS `@yVar`, @zVar AS `@zVar` GROUP BY @xVar, @yVar, @zVar;
SELECT @xVar AS `@xVar`, @yVar AS `@yVar`, @zVar AS `@zVar` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT @xVar AS `@xVar`, @yVar AS `@yVar`, @zVar AS `@zVar` ORDER BY @xVar ASC;
SELECT @xVar AS `@xVar`, @yVar AS `@yVar`, json_query(CAST((@zVar) AS JSON), '$.a') AS `json_query(CAST((@zVar) AS JSON), '$.a')`;
SELECT @xVar AS `@xVar`, @yVar AS `@yVar`, @zVar AS `@zVar` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT min(@xVar) OVER () AS `min(@xVar) OVER ()`, @yVar AS `@yVar`, @zVar AS `@zVar`;
SELECT @xVar AS `@xVar`, @yVar AS `@yVar`, @zVar AS `@zVar` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT @xVar AS `@xVar`, @yVar AS `@yVar`, @zVar AS `@zVar` LIMIT 2;
SELECT @xVar AS `@xVar`, @yVar AS `@yVar`, @zVar AS `@zVar` LIMIT 1, 1;
SELECT @xVar AS `@xVar`, @yVar AS `@yVar`, @zVar AS `@zVar` LIMIT 7, 2;
SELECT @xVar AS `@xVar`, CAST((@yVar) AS JSON)->'$.a' AS `CAST((@yVar) AS JSON)->'$.a'`, @zVar AS `@zVar`;
SELECT DISTINCT @xVar AS `@xVar`, @yVar AS `@yVar`, @zVar AS `@zVar`;
SELECT CAST((@aVarHint) AS JSON)->'$' AS `CAST((@aVarHint) AS JSON)->'$'`, @bVarHint AS `@bVarHint`;
SELECT @aVarHint AS `@aVarHint`, sum(@bVarHint) OVER () AS `sum(@bVarHint) OVER ()`;
SELECT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint` LIMIT 1, 2;
SELECT @aVarHint AS `@aVarHint`, CAST((@bVarHint) AS ARRAY<struct<`a` int(11), `b` varchar(8)>>) AS `CAST((@bVarHint) AS ARRAY<struct<``a`` int(11), ``b`` varchar(8)>>)`;
SELECT get_json_string(CAST((@aVarHint) AS JSON), '$.a') AS `get_json_string(CAST((@aVarHint) AS JSON), '$.a')`, @bVarHint AS `@bVarHint`;
SELECT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint` WHERE (@test) = (concat(upper('a'), '\\', '"', '\'', 'b'));
SELECT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint` ORDER BY @bVarHint DESC;
SELECT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint` ORDER BY @bVarHint DESC;
SELECT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint` LIMIT 1, 2;
SELECT DISTINCT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint`;
SELECT @aVarHint AS `@aVarHint`, CAST((CAST((@bVarHint) AS BOOLEAN)) AS DOUBLE) AS `CAST((CAST((@bVarHint) AS BOOLEAN)) AS DOUBLE)`;
SELECT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint` GROUP BY @aVarHint, @bVarHint;
SELECT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint` GROUP BY @aVarHint, @bVarHint;
SELECT @aVarHint AS `@aVarHint`, CAST((@bVarHint) AS JSON)->'k' AS `CAST((@bVarHint) AS JSON)->'k'`;
SELECT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint` ORDER BY @aVarHint ASC;
SELECT DISTINCT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint`;
SELECT CAST((@aVarHint) AS ARRAY<MAP<VARCHAR(16),INT>>) AS `CAST((@aVarHint) AS ARRAY<MAP<VARCHAR(16),INT>>)`, @bVarHint AS `@bVarHint`;
SELECT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint` LIMIT 1;
SELECT DISTINCT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint`;
SELECT DISTINCT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint`;
SELECT @aVarHint AS `@aVarHint`, @bVarHint AS `@bVarHint` GROUP BY @aVarHint, @bVarHint;
SELECT DISTINCT @secondVar AS `@secondVar`, @thirdVar AS `@thirdVar`;
SELECT DISTINCT @secondVar AS `@secondVar`, @thirdVar AS `@thirdVar`;
SELECT @secondVar AS `@secondVar`, @thirdVar AS `@thirdVar` LIMIT 1, 2;
SELECT DISTINCT @secondVar AS `@secondVar`, @thirdVar AS `@thirdVar`;
SELECT @secondVar AS `@secondVar`, @thirdVar AS `@thirdVar` GROUP BY @secondVar, @thirdVar;
SELECT CAST((@secondVar) AS JSON)->'$.a' AS `CAST((@secondVar) AS JSON)->'$.a'`, @thirdVar AS `@thirdVar`;
SELECT @secondVar AS `@secondVar`, @thirdVar AS `@thirdVar` ORDER BY @thirdVar ASC;
SELECT CAST((@secondVar) AS FLOAT) AS `CAST((@secondVar) AS FLOAT)`, @thirdVar AS `@thirdVar`;
SELECT get_json_string(CAST((@secondVar) AS JSON), '$.a') AS `get_json_string(CAST((@secondVar) AS JSON), '$.a')`, @thirdVar AS `@thirdVar`;
SELECT CAST((@secondVar) AS VARBINARY) AS `CAST((@secondVar) AS VARBINARY)`, @thirdVar AS `@thirdVar`;