SELECT sleep((mod(second(now()), 5)) + 1) AS `sleep((mod(second(now()), 5)) + 1)`;
SELECT sleep((mod(second(now()), -2147483648)) + 1) AS `sleep((mod(second(now()), -2147483648)) + 1)`;
SELECT sleep((mod(second(now()), 5)) + ((mod(second(now()), 5)) + 1)) AS `sleep((mod(second(now()), 5)) + ((mod(second(now()), 5)) + 1))`;
SELECT sleep(1 + 1) AS `sleep(1 + 1)`;
SELECT sleep((mod(second(second(now())), 5)) + 1) AS `sleep((mod(second(second(now())), 5)) + 1)`;
SELECT sleep((mod(second(now()), 5)) + 1) AS `sleep((mod(second(now()), 5)) + 1)` ORDER BY sleep((mod(second(now()), 5)) + 1) DESC;
SELECT DISTINCT sleep((mod(second(now()), 5)) + 1) AS `sleep((mod(second(now()), 5)) + 1)`;
SELECT DISTINCT sleep((mod(second(now()), 5)) + 1) AS `sleep((mod(second(now()), 5)) + 1)`;
SELECT sleep((mod(second(now()), 5)) + 1) AS `sleep((mod(second(now()), 5)) + 1)` LIMIT 1;
SELECT sleep((mod(second(now()), CAST(5 AS JSON)->'$.a')) + 1) AS `sleep((mod(second(now()), CAST(5 AS JSON)->'$.a')) + 1)`;
SELECT sleep((mod(second(now()), 5)) + 1) AS `sleep((mod(second(now()), 5)) + 1)` WHERE sleep((mod(second(now()), 5)) + 1);
SELECT sleep((mod(second(now()), 5)) + 1) AS `sleep((mod(second(now()), 5)) + 1)` LIMIT 100;
SELECT row_number() OVER (ORDER BY sleep((mod(second(now()), 5)) + 1) ASC ) AS `row_number() OVER (ORDER BY sleep((mod(second(now()), 5)) + 1) ASC )`;
SELECT sleep((mod((mod(second(now()), 5)) + 1, 5)) + 1) AS `sleep((mod((mod(second(now()), 5)) + 1, 5)) + 1)`;
SELECT sleep((mod(second(1), 5)) + 1) AS `sleep((mod(second(1), 5)) + 1)`;
SELECT sleep((mod(second(now()), now())) + 1) AS `sleep((mod(second(now()), now())) + 1)`;
SELECT json_length(CAST((sleep((mod(second(now()), 5)) + 1)) AS JSON)) AS `json_length(CAST((sleep((mod(second(now()), 5)) + 1)) AS JSON))`;
SELECT sleep((mod(second(now()), FALSE)) + 1) AS `sleep((mod(second(now()), FALSE)) + 1)`;
SELECT sleep(second(now())) AS `sleep(second(now()))`;
SELECT sleep((mod(second(now()), mod(second(now()), 5))) + 1) AS `sleep((mod(second(now()), mod(second(now()), 5))) + 1)`;
SELECT sleep((mod(year(now()), 5)) + 1) AS `sleep((mod(year(now()), 5)) + 1)`;
SELECT sleep((second(now())) + 1) AS `sleep((second(now())) + 1)`;
SELECT sleep((mod(second(now()), 5)) + 1) AS `sleep((mod(second(now()), 5)) + 1)` GROUP BY sleep((mod(second(now()), 5)) + 1);
SELECT sleep((mod(second(now()), 5)) + 1) AS `sleep((mod(second(now()), 5)) + 1)` GROUP BY sleep((mod(second(now()), 5)) + 1);
SELECT sleep((mod(upper(now()), 5)) + 1) AS `sleep((mod(upper(now()), 5)) + 1)`;
SELECT sleep((mod(md5(now()), 5)) + 1) AS `sleep((mod(md5(now()), 5)) + 1)`;
SELECT sleep((mod(second(now()), 5)) + 1) AS `sleep((mod(second(now()), 5)) + 1)`;
SELECT sleep((mod(second(1), 5)) + 1) AS `sleep((mod(second(1), 5)) + 1)`;
SELECT sleep((mod(second(now()), 5)) + (mod(second(now()), 5))) AS `sleep((mod(second(now()), 5)) + (mod(second(now()), 5)))`;