CREATE TABLE ss( event_day DATE, pv BIGINT) DUPLICATE KEY(event_day) DISTRIBUTED BY HASH(event_day) BUCKETS 8 PROPERTIES("replication_num" = "1");
CREATE TABLE jj( event_day DATE, pv BIGINT) DUPLICATE KEY(event_day) DISTRIBUTED BY HASH(event_day) BUCKETS 8 PROPERTIES("replication_num" = "1");
insert into ss values('2020-01-14', 2);
insert into ss values('2020-01-14', 3);
insert into ss values('2020-01-15', 2);
insert into jj values('2020-01-16', 1);
CREATE VIEW view1 AS SELECT event_day, sum(pv) as sum_pv FROM ss GROUP BY event_day;
CREATE MATERIALIZED VIEW mv_on_view_1 REFRESH ASYNC AS select * from view1;
insert into ss values('2020-01-15', 3);
ALTER TABLE jj ADD COLUMN extra int;
ALTER TABLE jj DROP COLUMN pv;
ALTER TABLE jj ADD COLUMN pv int;
ALTER TABLE ss DROP COLUMN pv;
DROP VIEW view1;
CREATE VIEW view1 AS SELECT event_day, sum(pv) as sum_pv FROM jj GROUP BY event_day;