SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_1`) AS `count(DISTINCT tinyint_col_1)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT tinyint_col_2)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_1`) AS `count(DISTINCT tinyint_col_1)` FROM `srfuzz_mut_30`.`t1` LIMIT 7, 2;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_1`) AS `count(DISTINCT srfuzz_mut_30.t1.tinyint_col_1)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_1`) AS `count(DISTINCT tinyint_col_1)` FROM `srfuzz_mut_30`.`t1`;
SELECT get_json_string(CAST((count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_1`)) AS JSON), '$.a') AS `get_json_string(CAST((count(DISTINCT tinyint_col_1)) AS JSON), '$.a')` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_1`) AS `count(DISTINCT srfuzz_mut_30.t1.tinyint_col_1)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_1`) AS `count(DISTINCT tinyint_col_1)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT tinyint_col_2)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_1`) AS `count(DISTINCT srfuzz_mut_30.t1.tinyint_col_1)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `t1`.`tinyint_col_1`) AS `count(DISTINCT tinyint_col_1)` FROM (SELECT `srfuzz_mut_30`.`t1`.`tinyint_col_1`, `srfuzz_mut_30`.`t1`.`tinyint_col_2` FROM `srfuzz_mut_30`.`t1` UNION SELECT `srfuzz_mut_30`.`t1`.`tinyint_col_1`, `srfuzz_mut_30`.`t1`.`tinyint_col_2` FROM `srfuzz_mut_30`.`t1`) `t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_1`) AS `count(DISTINCT srfuzz_mut_30.t1.tinyint_col_1)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_1`) AS `count(DISTINCT tinyint_col_1)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_1`) AS `count(DISTINCT tinyint_col_1)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_1`) AS `count(DISTINCT tinyint_col_1)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_1`) AS `count(DISTINCT tinyint_col_1)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_1`) AS `count(DISTINCT tinyint_col_1)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `t1`.`tinyint_col_1`) AS `count(DISTINCT tinyint_col_1)` FROM (SELECT `srfuzz_mut_30`.`t1`.`tinyint_col_1`, `srfuzz_mut_30`.`t1`.`tinyint_col_2` FROM `srfuzz_mut_30`.`t1` UNION SELECT `srfuzz_mut_30`.`t1`.`tinyint_col_1`, `srfuzz_mut_30`.`t1`.`tinyint_col_2` FROM `srfuzz_mut_30`.`t1`) `t1`;
SELECT count(DISTINCT `t1`.`tinyint_col_1`) AS `count(DISTINCT tinyint_col_1)` FROM (SELECT `srfuzz_mut_30`.`t1`.`tinyint_col_1`, `srfuzz_mut_30`.`t1`.`tinyint_col_2` FROM `srfuzz_mut_30`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT count(DISTINCT `t1`.`tinyint_col_1`) AS `count(DISTINCT tinyint_col_1)` FROM (SELECT `srfuzz_mut_30`.`t1`.`tinyint_col_1`, `srfuzz_mut_30`.`t1`.`tinyint_col_2` FROM `srfuzz_mut_30`.`t1`) `t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_1`) AS `count(DISTINCT tinyint_col_1)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `t1`.`tinyint_col_1`) AS `count(DISTINCT tinyint_col_1)` FROM (SELECT `srfuzz_mut_30`.`t1`.`tinyint_col_1`, `srfuzz_mut_30`.`t1`.`tinyint_col_2` FROM `srfuzz_mut_30`.`t1` INTERSECT SELECT `srfuzz_mut_30`.`t1`.`tinyint_col_1`, `srfuzz_mut_30`.`t1`.`tinyint_col_2` FROM `srfuzz_mut_30`.`t1`) `t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_1`) AS `count(DISTINCT tinyint_col_1)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_1`) AS `count(DISTINCT srfuzz_mut_30.t1.tinyint_col_1)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_1`) AS `count(DISTINCT tinyint_col_1)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_1`) AS `count(DISTINCT srfuzz_mut_30.t1.tinyint_col_1)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `t1`.`tinyint_col_2`) AS `count(DISTINCT tinyint_col_2)` FROM (SELECT `srfuzz_mut_30`.`t1`.`tinyint_col_1`, `srfuzz_mut_30`.`t1`.`tinyint_col_2` FROM `srfuzz_mut_30`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_1`) AS `count(DISTINCT tinyint_col_1)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT tinyint_col_2)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `t1`.`tinyint_col_2`) AS `count(DISTINCT tinyint_col_2)` FROM (SELECT `srfuzz_mut_30`.`t1`.`tinyint_col_1`, `srfuzz_mut_30`.`t1`.`tinyint_col_2` FROM `srfuzz_mut_30`.`t1` INTERSECT SELECT `srfuzz_mut_30`.`t1`.`tinyint_col_1`, `srfuzz_mut_30`.`t1`.`tinyint_col_2` FROM `srfuzz_mut_30`.`t1`) `t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT tinyint_col_2)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT srfuzz_mut_30.t1.tinyint_col_2)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT tinyint_col_2)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT tinyint_col_2)` FROM `srfuzz_mut_30`.`t1` ORDER BY count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) DESC;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT tinyint_col_2)` FROM `srfuzz_mut_30`.`t1` GROUP BY `srfuzz_mut_30`.`t1`.`tinyint_col_1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT srfuzz_mut_30.t1.tinyint_col_2)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT tinyint_col_2)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT tinyint_col_2)` FROM `srfuzz_mut_30`.`t1` LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT tinyint_col_2)` FROM `srfuzz_mut_30`.`t1` ORDER BY count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) DESC NULLS FIRST;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT srfuzz_mut_30.t1.tinyint_col_2)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT tinyint_col_2)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT srfuzz_mut_30.t1.tinyint_col_2)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT tinyint_col_2)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT srfuzz_mut_30.t1.tinyint_col_2)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT tinyint_col_2)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT srfuzz_mut_30.t1.tinyint_col_2)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT tinyint_col_2)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `t1`.`tinyint_col_2`) AS `count(DISTINCT tinyint_col_2)` FROM (SELECT `srfuzz_mut_30`.`t1`.`tinyint_col_1`, `srfuzz_mut_30`.`t1`.`tinyint_col_2` FROM `srfuzz_mut_30`.`t1` INTERSECT SELECT `srfuzz_mut_30`.`t1`.`tinyint_col_1`, `srfuzz_mut_30`.`t1`.`tinyint_col_2` FROM `srfuzz_mut_30`.`t1`) `t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT srfuzz_mut_30.t1.tinyint_col_2)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT tinyint_col_2)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT tinyint_col_2)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT srfuzz_mut_30.t1.tinyint_col_2)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT srfuzz_mut_30.t1.tinyint_col_2)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `t1`.`tinyint_col_2`) AS `count(DISTINCT tinyint_col_2)` FROM (SELECT `srfuzz_mut_30`.`t1`.`tinyint_col_1`, `srfuzz_mut_30`.`t1`.`tinyint_col_2` FROM `srfuzz_mut_30`.`t1` UNION SELECT `srfuzz_mut_30`.`t1`.`tinyint_col_1`, `srfuzz_mut_30`.`t1`.`tinyint_col_2` FROM `srfuzz_mut_30`.`t1`) `t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT srfuzz_mut_30.t1.tinyint_col_2)` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT get_json_string(CAST(`srfuzz_mut_30`.`t1`.`tinyint_col_2` AS JSON), '$.a')) AS `count(DISTINCT get_json_string(CAST(tinyint_col_2 AS JSON), '$.a'))` FROM `srfuzz_mut_30`.`t1`;
SELECT count(DISTINCT `srfuzz_mut_30`.`t1`.`tinyint_col_2`) AS `count(DISTINCT tinyint_col_2)` FROM `srfuzz_mut_30`.`t1`;