SELECT bitmap_union_int(`srfuzz_mut_41`.`t1`.`c2`) AS `bitmap_union_int(c2)` FROM `srfuzz_mut_41`.`t1`;
SELECT bitmap_union_int(`t1`.`c2`) AS `bitmap_union_int(c2)` FROM (SELECT `srfuzz_mut_41`.`t1`.`c1`, `srfuzz_mut_41`.`t1`.`c2` FROM `srfuzz_mut_41`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_41`.`t1`.`c1`, `srfuzz_mut_41`.`t1`.`c2` FROM `srfuzz_mut_41`.`t1`) SELECT bitmap_union_int(`t1`.`c2`) AS `bitmap_union_int(c2)` FROM `srfuzz_n1` AS t1;
SELECT bitmap_union_int(`srfuzz_mut_41`.`t1`.`c2`) AS `bitmap_union_int(srfuzz_mut_41.t1.c2)` FROM `srfuzz_mut_41`.`t1`;
SELECT bitmap_union_int(`srfuzz_mut_41`.`t1`.`c2`) AS `bitmap_union_int(srfuzz_mut_41.t1.c2)` FROM `srfuzz_mut_41`.`t1`;
SELECT bitmap_union_int(`srfuzz_mut_41`.`t1`.`c2`) AS `bitmap_union_int(srfuzz_mut_41.t1.c2)` FROM `srfuzz_mut_41`.`t1`;
SELECT bitmap_union_int(`t1`.`c2`) AS `bitmap_union_int(c2)` FROM (SELECT `srfuzz_mut_41`.`t1`.`c1`, `srfuzz_mut_41`.`t1`.`c2` FROM `srfuzz_mut_41`.`t1` UNION ALL SELECT `srfuzz_mut_41`.`t1`.`c1`, `srfuzz_mut_41`.`t1`.`c2` FROM `srfuzz_mut_41`.`t1`) `t1`;
SELECT bitmap_union_int(`srfuzz_mut_41`.`t1`.`c2`) AS `bitmap_union_int(c2)` FROM `srfuzz_mut_41`.`t1`;
SELECT bitmap_union_int(`srfuzz_mut_41`.`t1`.`c2`) AS `bitmap_union_int(srfuzz_mut_41.t1.c2)` FROM `srfuzz_mut_41`.`t1`;
SELECT count(bitmap_union_int(`srfuzz_mut_41`.`t1`.`c2`)) OVER () AS `count(bitmap_union_int(c2)) OVER ()` FROM `srfuzz_mut_41`.`t1`;
SELECT dense_rank() OVER (ORDER BY bitmap_union_int(`srfuzz_mut_41`.`t1`.`c2`) ASC ) AS `dense_rank() OVER (ORDER BY bitmap_union_int(c2) ASC )` FROM `srfuzz_mut_41`.`t1`;
SELECT bitmap_union_int(`t1`.`c2`) AS `bitmap_union_int(c2)` FROM (SELECT `srfuzz_mut_41`.`t1`.`c1`, `srfuzz_mut_41`.`t1`.`c2` FROM `srfuzz_mut_41`.`t1` EXCEPT SELECT `srfuzz_mut_41`.`t1`.`c1`, `srfuzz_mut_41`.`t1`.`c2` FROM `srfuzz_mut_41`.`t1`) `t1`;
SELECT bitmap_union_int(`srfuzz_mut_41`.`t1`.`c2`) AS `bitmap_union_int(c2)` FROM `srfuzz_mut_41`.`t1`;
SELECT bitmap_union_int(`srfuzz_mut_41`.`t1`.`c2`) AS `bitmap_union_int(c2)` FROM `srfuzz_mut_41`.`t1` WHERE `srfuzz_mut_41`.`t1`.`c2`;
SELECT bitmap_union_int(`srfuzz_mut_41`.`t1`.`c2`) AS `bitmap_union_int(c2)` FROM `srfuzz_mut_41`.`t1`;
SELECT bitmap_union_int(`srfuzz_mut_41`.`t1`.`c2`) AS `bitmap_union_int(c2)` FROM `srfuzz_mut_41`.`t1`;
SELECT bitmap_union_int(`t1`.`c2`) AS `bitmap_union_int(c2)` FROM (SELECT `srfuzz_mut_41`.`t1`.`c1`, `srfuzz_mut_41`.`t1`.`c2` FROM `srfuzz_mut_41`.`t1` EXCEPT SELECT `srfuzz_mut_41`.`t1`.`c1`, `srfuzz_mut_41`.`t1`.`c2` FROM `srfuzz_mut_41`.`t1`) `t1`;
SELECT bitmap_union_int(`srfuzz_mut_41`.`t1`.`c2`) AS `bitmap_union_int(srfuzz_mut_41.t1.c2)` FROM `srfuzz_mut_41`.`t1`;
SELECT bitmap_union_int(`srfuzz_mut_41`.`t1`.`c2`) AS `bitmap_union_int(c2)` FROM `srfuzz_mut_41`.`t1`;
SELECT bitmap_union_int(`srfuzz_mut_41`.`t1`.`c2`) AS `bitmap_union_int(c2)` FROM `srfuzz_mut_41`.`t1`;
SELECT bitmap_union_int(`srfuzz_mut_41`.`t1`.`c2`) AS `bitmap_union_int(c2)` FROM `srfuzz_mut_41`.`t1` ORDER BY bitmap_union_int(`srfuzz_mut_41`.`t1`.`c2`) DESC;
SELECT bitmap_union_int(`srfuzz_mut_41`.`t1`.`c2`) AS `bitmap_union_int(c2)` FROM `srfuzz_mut_41`.`t1`;
SELECT bitmap_union_int(`srfuzz_mut_41`.`t1`.`c2`) AS `bitmap_union_int(srfuzz_mut_41.t1.c2)` FROM `srfuzz_mut_41`.`t1`;
SELECT bitmap_union_int(`srfuzz_mut_41`.`t1`.`c2`) AS `bitmap_union_int(srfuzz_mut_41.t1.c2)` FROM `srfuzz_mut_41`.`t1`;
SELECT bitmap_union_int(`srfuzz_mut_41`.`t1`.`c2`) AS `bitmap_union_int(c2)` FROM `srfuzz_mut_41`.`t1`;