SELECT `srfuzz_mut_317`.`t_range_date`.`v` FROM `srfuzz_mut_317`.`t_range_date` WHERE `srfuzz_mut_317`.`t_range_date`.`dt` = '2024-01-05' ORDER BY `srfuzz_mut_317`.`t_range_date`.`v` ASC;
SELECT `srfuzz_mut_317`.`t_range_date`.`v` FROM `srfuzz_mut_317`.`t_range_date` WHERE `srfuzz_mut_317`.`t_range_date`.`dt` >= '2024-01-10' ORDER BY `srfuzz_mut_317`.`t_range_date`.`v` ASC;
SELECT `srfuzz_mut_317`.`t_range_date`.`v` FROM `srfuzz_mut_317`.`t_range_date` WHERE `srfuzz_mut_317`.`t_range_date`.`dt` BETWEEN '2024-01-03' AND '2024-01-07' ORDER BY `srfuzz_mut_317`.`t_range_date`.`v` ASC;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_317`.`t_range_date` WHERE `srfuzz_mut_317`.`t_range_date`.`dt` = '2024-01-20';
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_317`.`t_range_date` WHERE `srfuzz_mut_317`.`t_range_date`.`dt` = '2024-03-01';
SELECT `srfuzz_mut_317`.`t_range_int`.`v` FROM `srfuzz_mut_317`.`t_range_int` WHERE `srfuzz_mut_317`.`t_range_int`.`k` = 150;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_317`.`t_range_int` WHERE (`srfuzz_mut_317`.`t_range_int`.`k` >= 100) AND (`srfuzz_mut_317`.`t_range_int`.`k` < 200);
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_317`.`t_range_int` WHERE (`srfuzz_mut_317`.`t_range_int`.`k` >= 50) AND (`srfuzz_mut_317`.`t_range_int`.`k` <= 250);
SELECT `srfuzz_mut_317`.`t_range_null_date`.`v` FROM `srfuzz_mut_317`.`t_range_null_date` WHERE `srfuzz_mut_317`.`t_range_null_date`.`dt` IS NULL ORDER BY `srfuzz_mut_317`.`t_range_null_date`.`v` ASC;
SELECT `srfuzz_mut_317`.`t_range_null_date`.`v` FROM `srfuzz_mut_317`.`t_range_null_date` WHERE `srfuzz_mut_317`.`t_range_null_date`.`dt` IS NOT NULL ORDER BY `srfuzz_mut_317`.`t_range_null_date`.`v` ASC;
SELECT `srfuzz_mut_317`.`t_range_null_date`.`v` FROM `srfuzz_mut_317`.`t_range_null_date` WHERE `srfuzz_mut_317`.`t_range_null_date`.`dt` = '2024-01-15';
SELECT `srfuzz_mut_317`.`t_range_null_date`.`v` FROM `srfuzz_mut_317`.`t_range_null_date` WHERE `srfuzz_mut_317`.`t_range_null_date`.`dt` <=> NULL ORDER BY `srfuzz_mut_317`.`t_range_null_date`.`v` ASC;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_317`.`t_range_null_date` WHERE (`srfuzz_mut_317`.`t_range_null_date`.`dt` IS NULL) OR (`srfuzz_mut_317`.`t_range_null_date`.`dt` = '2024-02-15');
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_317`.`t_range_null_date`;
SELECT `srfuzz_mut_317`.`t_range_null_tinyint`.`v` FROM `srfuzz_mut_317`.`t_range_null_tinyint` WHERE `srfuzz_mut_317`.`t_range_null_tinyint`.`k` IS NULL ORDER BY `srfuzz_mut_317`.`t_range_null_tinyint`.`v` ASC;
SELECT `srfuzz_mut_317`.`t_range_null_tinyint`.`v` FROM `srfuzz_mut_317`.`t_range_null_tinyint` WHERE `srfuzz_mut_317`.`t_range_null_tinyint`.`k` = -10;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_317`.`t_range_null_tinyint` WHERE `srfuzz_mut_317`.`t_range_null_tinyint`.`k` IS NOT NULL;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_317`.`t_range_null_tinyint`;
SELECT `srfuzz_mut_317`.`t_range_null_tinyint`.`v` FROM `srfuzz_mut_317`.`t_range_null_tinyint` WHERE `srfuzz_mut_317`.`t_range_null_tinyint`.`k` = 25;
SELECT `srfuzz_mut_317`.`t_range_null_smallint`.`v` FROM `srfuzz_mut_317`.`t_range_null_smallint` WHERE `srfuzz_mut_317`.`t_range_null_smallint`.`k` IS NULL;
SELECT `srfuzz_mut_317`.`t_range_null_smallint`.`v` FROM `srfuzz_mut_317`.`t_range_null_smallint` WHERE `srfuzz_mut_317`.`t_range_null_smallint`.`k` = -32100;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_317`.`t_range_null_smallint`;
SELECT `srfuzz_mut_317`.`t_list_int`.`v` FROM `srfuzz_mut_317`.`t_list_int` WHERE `srfuzz_mut_317`.`t_list_int`.`k` = 2;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_317`.`t_list_int` WHERE `srfuzz_mut_317`.`t_list_int`.`k` IN (1, 7);
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_317`.`t_list_int` WHERE (`srfuzz_mut_317`.`t_list_int`.`k` >= 3) AND (`srfuzz_mut_317`.`t_list_int`.`k` <= 7);
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_317`.`t_list_int` WHERE `srfuzz_mut_317`.`t_list_int`.`k` = 100;
SELECT `srfuzz_mut_317`.`t_list_null`.`v` FROM `srfuzz_mut_317`.`t_list_null` WHERE `srfuzz_mut_317`.`t_list_null`.`k` IS NULL ORDER BY `srfuzz_mut_317`.`t_list_null`.`v` ASC;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_317`.`t_list_null` WHERE `srfuzz_mut_317`.`t_list_null`.`k` IS NOT NULL;
SELECT `srfuzz_mut_317`.`t_list_null`.`v` FROM `srfuzz_mut_317`.`t_list_null` WHERE `srfuzz_mut_317`.`t_list_null`.`k` = 1;
SELECT `srfuzz_mut_317`.`t_list_null`.`v` FROM `srfuzz_mut_317`.`t_list_null` WHERE `srfuzz_mut_317`.`t_list_null`.`k` <=> NULL ORDER BY `srfuzz_mut_317`.`t_list_null`.`v` ASC;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_317`.`t_list_null`;
SELECT `srfuzz_mut_317`.`t_list_null_mixed`.`v` FROM `srfuzz_mut_317`.`t_list_null_mixed` WHERE `srfuzz_mut_317`.`t_list_null_mixed`.`k` IS NULL;
SELECT `srfuzz_mut_317`.`t_list_null_mixed`.`v` FROM `srfuzz_mut_317`.`t_list_null_mixed` WHERE `srfuzz_mut_317`.`t_list_null_mixed`.`k` = 0;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_317`.`t_list_null_mixed` WHERE (`srfuzz_mut_317`.`t_list_null_mixed`.`k` IS NULL) OR (`srfuzz_mut_317`.`t_list_null_mixed`.`k` = 4);
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_317`.`t_list_null_mixed`;
SELECT `srfuzz_mut_317`.`t_list_multi_null`.`v` FROM `srfuzz_mut_317`.`t_list_multi_null` WHERE (`srfuzz_mut_317`.`t_list_multi_null`.`c1` IS NULL) AND (`srfuzz_mut_317`.`t_list_multi_null`.`c2` IS NULL);
SELECT `srfuzz_mut_317`.`t_list_multi_null`.`v` FROM `srfuzz_mut_317`.`t_list_multi_null` WHERE `srfuzz_mut_317`.`t_list_multi_null`.`c1` IS NULL;
SELECT `srfuzz_mut_317`.`t_list_multi_null`.`v` FROM `srfuzz_mut_317`.`t_list_multi_null` WHERE (`srfuzz_mut_317`.`t_list_multi_null`.`c1` = 1) AND (`srfuzz_mut_317`.`t_list_multi_null`.`c2` = 10);
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_317`.`t_list_multi_null`;
SELECT `srfuzz_mut_317`.`t_limit_test`.`v` FROM `srfuzz_mut_317`.`t_limit_test` WHERE `srfuzz_mut_317`.`t_limit_test`.`k` = 50;
SELECT `srfuzz_mut_317`.`t_limit_test`.`v` FROM `srfuzz_mut_317`.`t_limit_test` WHERE `srfuzz_mut_317`.`t_limit_test`.`k` = 150;
SELECT `srfuzz_mut_317`.`t_limit_test`.`v` FROM `srfuzz_mut_317`.`t_limit_test` WHERE `srfuzz_mut_317`.`t_limit_test`.`k` = 50;
SELECT `srfuzz_mut_317`.`t_limit_test`.`v` FROM `srfuzz_mut_317`.`t_limit_test` WHERE `srfuzz_mut_317`.`t_limit_test`.`k` = 150;
SELECT `srfuzz_mut_317`.`t_limit_test`.`v` FROM `srfuzz_mut_317`.`t_limit_test` WHERE `srfuzz_mut_317`.`t_limit_test`.`k` = 50;
SELECT `srfuzz_mut_317`.`t_limit_test`.`v` FROM `srfuzz_mut_317`.`t_limit_test` WHERE `srfuzz_mut_317`.`t_limit_test`.`k` = 150;
SELECT `srfuzz_mut_317`.`t_range_cast`.`v` FROM `srfuzz_mut_317`.`t_range_cast` WHERE `srfuzz_mut_317`.`t_range_cast`.`dt` = (CAST('2024-02-15' AS DATE));
SELECT `srfuzz_mut_317`.`t_range_cast`.`v` FROM `srfuzz_mut_317`.`t_range_cast` WHERE `srfuzz_mut_317`.`t_range_cast`.`dt` = '2024-03-15';
SELECT `srfuzz_mut_317`.`t_range_cast`.`v` FROM `srfuzz_mut_317`.`t_range_cast` WHERE `srfuzz_mut_317`.`t_range_cast`.`dt` = (date_add('2024-01-14 00:00:00', INTERVAL 1 DAY));
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_317`.`t_range_cast`;
SELECT `srfuzz_mut_317`.`t_multi_pred`.`v` FROM `srfuzz_mut_317`.`t_multi_pred` WHERE (`srfuzz_mut_317`.`t_multi_pred`.`dt` >= '2024-01-05') AND (`srfuzz_mut_317`.`t_multi_pred`.`dt` < '2024-01-10') ORDER BY `srfuzz_mut_317`.`t_multi_pred`.`v` ASC;
SELECT `srfuzz_mut_317`.`t_multi_pred`.`v` FROM `srfuzz_mut_317`.`t_multi_pred` WHERE ((`srfuzz_mut_317`.`t_multi_pred`.`dt` >= '2024-01-10') AND (`srfuzz_mut_317`.`t_multi_pred`.`dt` < '2024-01-20')) AND (`srfuzz_mut_317`.`t_multi_pred`.`dt` != '2024-01-12') ORDER BY `srfuzz_mut_317`.`t_multi_pred`.`v` ASC;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_317`.`t_multi_pred` WHERE (`srfuzz_mut_317`.`t_multi_pred`.`dt` = '2024-01-22') AND (`srfuzz_mut_317`.`t_multi_pred`.`v` > 0);
SELECT `srfuzz_mut_317`.`t_open_bound`.`v` FROM `srfuzz_mut_317`.`t_open_bound` WHERE `srfuzz_mut_317`.`t_open_bound`.`k` = 50;
SELECT `srfuzz_mut_317`.`t_open_bound`.`v` FROM `srfuzz_mut_317`.`t_open_bound` WHERE `srfuzz_mut_317`.`t_open_bound`.`k` = 999;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_317`.`t_open_bound` WHERE `srfuzz_mut_317`.`t_open_bound`.`k` >= 100;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_317`.`t_open_bound`;
SELECT `srfuzz_mut_317`.`t_null_combined`.`v` FROM `srfuzz_mut_317`.`t_null_combined` WHERE (`srfuzz_mut_317`.`t_null_combined`.`dt` IS NULL) AND (`srfuzz_mut_317`.`t_null_combined`.`category` = 1);
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_317`.`t_null_combined` WHERE `srfuzz_mut_317`.`t_null_combined`.`dt` IS NULL;
SELECT `srfuzz_mut_317`.`t_null_combined`.`v` FROM `srfuzz_mut_317`.`t_null_combined` WHERE `srfuzz_mut_317`.`t_null_combined`.`dt` = '2024-01-15';
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_317`.`t_null_combined` WHERE (`srfuzz_mut_317`.`t_null_combined`.`dt` IS NOT NULL) AND (`srfuzz_mut_317`.`t_null_combined`.`category` = 1);