SELECT sleep((mod(second(now()), 10)) + 1) AS `sleep((mod(second(now()), 10)) + 1)`;
SELECT sleep((mod(second(mod(second(now()), 10)), 10)) + 1) AS `sleep((mod(second(mod(second(now()), 10)), 10)) + 1)`;
SELECT sleep((mod(mod(second(now()), 10), 10)) + 1) AS `sleep((mod(mod(second(now()), 10), 10)) + 1)`;
SELECT sleep((mod(second(now()), 10)) + 1) AS `sleep((mod(second(now()), 10)) + 1)`;
SELECT sleep(1) AS `sleep(1)`;
SELECT DISTINCT sleep((mod(second(now()), 10)) + 1) AS `sleep((mod(second(now()), 10)) + 1)`;
SELECT sleep(now()) AS `sleep(now())`;
SELECT sleep((mod(second(now()), 10)) + 1) AS `sleep((mod(second(now()), 10)) + 1)` GROUP BY sleep((mod(second(now()), 10)) + 1);
SELECT sleep((mod(second(now()), 10)) + 1) AS `sleep((mod(second(now()), 10)) + 1)`;
SELECT sleep(second(now())) AS `sleep(second(now()))`;
SELECT sleep((mod(second(now()), CAST(10 AS VARCHAR))) + 1) AS `sleep((mod(second(now()), CAST(10 AS VARCHAR))) + 1)`;
SELECT sleep((mod(second(mod(second(now()), 10)), 10)) + 1) AS `sleep((mod(second(mod(second(now()), 10)), 10)) + 1)`;
SELECT sleep((mod(second(now()), 10)) + 1) AS `sleep((mod(second(now()), 10)) + 1)` LIMIT 7, 2;
SELECT sleep((mod(second(now()), 10)) + 1) AS `sleep((mod(second(now()), 10)) + 1)` GROUP BY sleep((mod(second(now()), 10)) + 1);
SELECT sleep((mod(second(now()), 10)) + (mod(second(now()), 10))) AS `sleep((mod(second(now()), 10)) + (mod(second(now()), 10)))`;
SELECT sleep((mod(second((mod(second(now()), 10)) + 1), 10)) + 1) AS `sleep((mod(second((mod(second(now()), 10)) + 1), 10)) + 1)`;
SELECT sleep((mod(second(mod(second(now()), 10)), 10)) + 1) AS `sleep((mod(second(mod(second(now()), 10)), 10)) + 1)`;
SELECT sleep((mod(second(now()), 10)) + 1) AS `sleep((mod(second(now()), 10)) + 1)` GROUP BY sleep((mod(second(now()), 10)) + 1);
SELECT sleep((mod(second(now()), 1)) + 1) AS `sleep((mod(second(now()), 1)) + 1)`;
SELECT sleep((mod(ceil(now()), 10)) + 1) AS `sleep((mod(ceil(now()), 10)) + 1)`;
SELECT DISTINCT sleep((mod(second(now()), 10)) + 1) AS `sleep((mod(second(now()), 10)) + 1)`;
SELECT sleep((mod(second(mod(second(now()), 10)), 10)) + 1) AS `sleep((mod(second(mod(second(now()), 10)), 10)) + 1)`;
SELECT sleep((mod(second(10), 10)) + 1) AS `sleep((mod(second(10), 10)) + 1)`;
SELECT sleep((mod(second(second(now())), 10)) + 1) AS `sleep((mod(second(second(now())), 10)) + 1)`;
SELECT sleep(mod(second(now()), 10)) AS `sleep(mod(second(now()), 10))`;
SELECT sleep((mod(second(now()), 10)) + 1) AS `sleep((mod(second(now()), 10)) + 1)` WHERE sleep((mod(second(now()), 10)) + 1);
SELECT sleep((mod(second(now()), second(now()))) + 1) AS `sleep((mod(second(now()), second(now()))) + 1)`;
SELECT sleep(CAST(((mod(second(now()), 10)) + 1) AS JSON)->'$') AS `sleep(CAST(((mod(second(now()), 10)) + 1) AS JSON)->'$')`;
SELECT sleep(second(now())) AS `sleep(second(now()))`;
SELECT sleep(10) AS `sleep(10)`;
SELECT sleep((mod(ceil(now()), 10)) + 1) AS `sleep((mod(ceil(now()), 10)) + 1)`;
SELECT sleep((mod(second(now()), 10)) + (mod(second(now()), 10))) AS `sleep((mod(second(now()), 10)) + (mod(second(now()), 10)))`;
SELECT sleep((get_json_string(CAST((mod(second(now()), 10)) AS JSON), '$.a')) + 1) AS `sleep((get_json_string(CAST((mod(second(now()), 10)) AS JSON), '$.a')) + 1)`;
SELECT sleep((mod(second(mod(second(now()), 10)), 10)) + 1) AS `sleep((mod(second(mod(second(now()), 10)), 10)) + 1)`;
SELECT sleep((mod(second(now()), 10)) + 1) AS `sleep((mod(second(now()), 10)) + 1)` GROUP BY sleep((mod(second(now()), 10)) + 1);