CREATE TABLE t1 (
    c VARCHAR(65535) NULL COMMENT ""
)
ENGINE = OLAP
DUPLICATE KEY(c)
DISTRIBUTED BY RANDOM
PROPERTIES (
    "replication_num" = "1"
);
INSERT INTO t1 VALUES ('A'), ('A');
drop table t1;