SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%' LIMIT 1;
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`) LIMIT 0) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT DISTINCT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE CAST((`v`.`line` LIKE '%RowsRead: 0%') AS DECIMAL128(38,38));
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '0000-00-00';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%' LIMIT 5;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%' LIMIT 0;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` EXCEPT SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT DISTINCT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT DISTINCT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line`, `srfuzz_n1`.`e` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` UNION SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line`, `srfuzz_n1`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` RIGHT OUTER JOIN (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `srfuzz_n1` ON `v`.`line` = `srfuzz_n1`.`line` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line`, `srfuzz_n1`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` RIGHT OUTER JOIN (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `srfuzz_n1` ON `v`.`line` > `srfuzz_n1`.`line` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` UNION SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` INTERSECT SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%' ORDER BY `v`.`line` ASC;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` UNION ALL SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line`, `srfuzz_n1`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` RIGHT OUTER JOIN (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `srfuzz_n1` ON `v`.`line` = `srfuzz_n1`.`line` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`) GROUP BY `t`.`line`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line`, `srfuzz_n1`.`e` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line`, `srfuzz_n1`.`e` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%' ORDER BY `v`.`line` DESC;
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` INTERSECT SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE (get_json_string(CAST(`v`.`line` AS JSON), '$.a')) LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%' LIMIT 2;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT DISTINCT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` EXCEPT SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line`, `srfuzz_n1`.`e` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE ' ';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` UNION SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT DISTINCT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line`, `srfuzz_n1`.`e` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE NULL;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '9999-12-31 23:59:59';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE ' ';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE (repeat('x', 65536));
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE (last_query_id());
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line`, `srfuzz_n1`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` RIGHT OUTER JOIN (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `srfuzz_n1` ON `v`.`line` = `srfuzz_n1`.`line` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '\\';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` INTERSECT SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE (get_json_string(CAST(`v`.`line` AS JSON), '$.a')) LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`) GROUP BY `t`.`line`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` INTERSECT SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT DISTINCT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` UNION SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`) LIMIT 1, 0) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE CAST((`v`.`line` LIKE '%RowsRead: 0%') AS JSON);
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE (repeat('x', 65536));
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '1970-01-01';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` UNION ALL SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line`, `srfuzz_n1`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` RIGHT OUTER JOIN (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `srfuzz_n1` ON `v`.`line` = `srfuzz_n1`.`line` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` EXCEPT SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line`, `srfuzz_n1`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` RIGHT OUTER JOIN (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `srfuzz_n1` ON `v`.`line` > `srfuzz_n1`.`line` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`) LIMIT 7, 100) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%' LIMIT 1;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` UNION ALL SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line`, `srfuzz_n1`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` RIGHT OUTER JOIN (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `srfuzz_n1` ON `v`.`line` = `srfuzz_n1`.`line` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` UNION SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE CAST((CAST((`v`.`line` LIKE '%RowsRead: 0%') AS DECIMAL128(38,38))) AS DECIMAL128(38,38));
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`) GROUP BY `t`.`line`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%' LIMIT 100;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE CAST((`v`.`line` LIKE '%RowsRead: 0%') AS JSON)->'$';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` INTERSECT SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE ' ' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`) LIMIT 100) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE (repeat('x', 65536));
SELECT DISTINCT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`) LIMIT 0) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE (CAST((CAST(`v`.`line` AS DECIMAL128(38,0))) AS VARCHAR)) LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE (get_query_profile(last_query_id()));
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT DISTINCT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` INTERSECT SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line`, `srfuzz_n1`.`e` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT DISTINCT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '1970-01-01';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE CAST((CAST((`v`.`line` LIKE '%RowsRead: 0%') AS DECIMAL64(1,0))) AS FLOAT);
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`) GROUP BY `t`.`line`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` INTERSECT SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line`, `srfuzz_n1`.`e` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%' ORDER BY `v`.`line` DESC;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` UNION ALL SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`) GROUP BY `t`.`line`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE json_query(CAST((`v`.`line` LIKE '%RowsRead: 0%') AS JSON), '$.a');
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` INTERSECT SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`) LIMIT 1, 0) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line`, `srfuzz_n1`.`e` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line`, `srfuzz_n1`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` RIGHT OUTER JOIN (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `srfuzz_n1` ON `v`.`line` = `srfuzz_n1`.`line` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` INTERSECT SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%' ORDER BY `v`.`line` ASC;
SELECT `v`.`line`, `srfuzz_n1`.`e` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` INTERSECT SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE (repeat('x', 65536));
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` UNION ALL SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT DISTINCT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE json_length(CAST((`v`.`line` LIKE '%RowsRead: 0%') AS JSON));
SELECT `v`.`line`, `srfuzz_n1`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` RIGHT OUTER JOIN (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `srfuzz_n1` ON `v`.`line` = `srfuzz_n1`.`line` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` UNION ALL SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` UNION SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line`, `srfuzz_n1`.`e` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT DISTINCT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`) GROUP BY `t`.`line`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%' ORDER BY `v`.`line` ASC;
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` UNION SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT DISTINCT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` UNION ALL SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT DISTINCT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` UNION ALL SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '0';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%' ORDER BY `v`.`line` ASC;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%' ORDER BY `v`.`line` ASC;
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` UNION SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line`, `srfuzz_n1`.`e` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT DISTINCT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` INTERSECT SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%' LIMIT 7, 1;
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` UNION SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE NULL;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`) GROUP BY `t`.`line`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`;
SELECT `v`.`line`, `srfuzz_n1`.`e` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '0';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '9999-12-31 23:59:59';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`) GROUP BY `t`.`line`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` EXCEPT SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%' ORDER BY `v`.`line` ASC;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE ' ';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '1970-01-01';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE ' ';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` UNION SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '9999-12-31 23:59:59';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT DISTINCT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` UNION SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE CAST((CAST((CAST((`v`.`line` LIKE '%RowsRead: 0%') AS LARGEINT)) AS DECIMAL64(1,0))) AS TIME);
SELECT `v`.`line`, `srfuzz_n1`.`e` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line`, `srfuzz_n1`.`e` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '0000-00-00';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%' ORDER BY `v`.`line` DESC;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line`, `srfuzz_n1`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` RIGHT OUTER JOIN (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `srfuzz_n1` ON `v`.`line` = `srfuzz_n1`.`line` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%' ORDER BY `v`.`line` DESC;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%' ORDER BY `v`.`line` DESC NULLS FIRST;
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` UNION ALL SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` UNION ALL SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE (get_query_profile(last_query_id()));
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` EXCEPT SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT DISTINCT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` INTERSECT SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` UNION ALL SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE `v`.`line`;
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE (get_query_profile(last_query_id()));
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE '%RowsRead: 0%' LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`;
SELECT `v`.`line` FROM (SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` INTERSECT SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v`) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`)) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';
SELECT `v`.`line` FROM (SELECT `t`.`line` FROM TABLE(unnest(split(get_query_profile(last_query_id()), ' '))) t(`line`) LIMIT 7, 1) `v` WHERE `v`.`line` LIKE '%RowsRead: 0%';