SELECT `srfuzz_mut_1180`.`test_normal`.`id` FROM `srfuzz_mut_1180`.`test_normal` ORDER BY `srfuzz_mut_1180`.`test_normal`.`id` ASC;
SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default` ORDER BY `srfuzz_mut_1180`.`test_default`.`id` ASC;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_1180`.`test_normal`.`id` FROM `srfuzz_mut_1180`.`test_normal`) SELECT `test_normal`.`id` FROM `srfuzz_n1` AS test_normal ORDER BY `test_normal`.`id` ASC;
SELECT `srfuzz_mut_1180`.`test_normal`.`id` FROM `srfuzz_mut_1180`.`test_normal` WHERE `srfuzz_mut_1180`.`test_normal`.`id` ORDER BY `srfuzz_mut_1180`.`test_normal`.`id` ASC;
SELECT `srfuzz_mut_1180`.`test_normal`.`id` FROM `srfuzz_mut_1180`.`test_normal` ORDER BY `srfuzz_mut_1180`.`test_normal`.`id` ASC  LIMIT 5;
SELECT `srfuzz_mut_1180`.`test_normal`.`id` FROM `srfuzz_mut_1180`.`test_normal`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_1180`.`test_normal`.`id` FROM `srfuzz_mut_1180`.`test_normal`) SELECT `test_normal`.`id` FROM `srfuzz_n1` AS test_normal ORDER BY `test_normal`.`id` ASC;
SELECT `test_normal`.`id` FROM (SELECT `srfuzz_mut_1180`.`test_normal`.`id` FROM `srfuzz_mut_1180`.`test_normal` EXCEPT SELECT `srfuzz_mut_1180`.`test_normal`.`id` FROM `srfuzz_mut_1180`.`test_normal`) `test_normal` ORDER BY `test_normal`.`id` ASC;
SELECT DISTINCT `srfuzz_mut_1180`.`test_normal`.`id` FROM `srfuzz_mut_1180`.`test_normal` ORDER BY `srfuzz_mut_1180`.`test_normal`.`id` ASC;
SELECT `test_normal`.`id`, `srfuzz_n1`.`e` FROM (SELECT `srfuzz_mut_1180`.`test_normal`.`id` FROM `srfuzz_mut_1180`.`test_normal`) `test_normal` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  ORDER BY `test_normal`.`id` ASC;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_1180`.`test_normal`.`id` FROM `srfuzz_mut_1180`.`test_normal`) SELECT `test_normal`.`id` FROM `srfuzz_n1` AS test_normal ORDER BY `test_normal`.`id` ASC;
SELECT `srfuzz_mut_1180`.`test_normal`.`id` FROM `srfuzz_mut_1180`.`test_normal` ORDER BY `srfuzz_mut_1180`.`test_normal`.`id` ASC  LIMIT 7, 0;
SELECT `test_normal`.`id` FROM (SELECT `srfuzz_mut_1180`.`test_normal`.`id` FROM `srfuzz_mut_1180`.`test_normal` UNION ALL SELECT `srfuzz_mut_1180`.`test_normal`.`id` FROM `srfuzz_mut_1180`.`test_normal`) `test_normal` ORDER BY `test_normal`.`id` ASC;
SELECT `srfuzz_mut_1180`.`test_normal`.`id` FROM `srfuzz_mut_1180`.`test_normal` ORDER BY `srfuzz_mut_1180`.`test_normal`.`id` ASC  LIMIT 0;
SELECT DISTINCT `srfuzz_mut_1180`.`test_normal`.`id` FROM `srfuzz_mut_1180`.`test_normal` ORDER BY `srfuzz_mut_1180`.`test_normal`.`id` ASC;
SELECT `test_default`.`id` FROM (SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default` INTERSECT SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default`) `test_default` ORDER BY `test_default`.`id` ASC;
SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default` ORDER BY `srfuzz_mut_1180`.`test_default`.`id` ASC  LIMIT 1, 100;
SELECT `test_default`.`id` FROM (SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default` UNION SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default`) `test_default` ORDER BY `test_default`.`id` ASC;
SELECT `test_default`.`id`, `srfuzz_n1`.`e` FROM (SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default`) `test_default` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  ORDER BY `test_default`.`id` ASC;
SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default`;
SELECT `test_default`.`id` FROM (SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default` UNION ALL SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default`) `test_default` ORDER BY `test_default`.`id` ASC;
SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default` ORDER BY `srfuzz_mut_1180`.`test_default`.`id` ASC  LIMIT 0;
SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default` ORDER BY `srfuzz_mut_1180`.`test_default`.`id` ASC  LIMIT 1;
SELECT `test_default`.`id` FROM (SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default` EXCEPT SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default`) `test_default` ORDER BY `test_default`.`id` ASC;
SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default`;
SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default` WHERE `srfuzz_mut_1180`.`test_default`.`id` ORDER BY `srfuzz_mut_1180`.`test_default`.`id` ASC;
SELECT `test_default`.`id` FROM (SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default` UNION ALL SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default`) `test_default` ORDER BY `test_default`.`id` ASC;
SELECT `test_default`.`id` FROM (SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default` UNION ALL SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default`) `test_default` ORDER BY `test_default`.`id` ASC;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default`) SELECT `test_default`.`id` FROM `srfuzz_n1` AS test_default ORDER BY `test_default`.`id` ASC;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default`) SELECT `test_default`.`id` FROM `srfuzz_n1` AS test_default ORDER BY `test_default`.`id` ASC;
SELECT `test_default`.`id` FROM (SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default` EXCEPT SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default`) `test_default` ORDER BY `test_default`.`id` ASC;
SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default` ORDER BY `srfuzz_mut_1180`.`test_default`.`id` ASC  LIMIT 5;
SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default` ORDER BY `srfuzz_mut_1180`.`test_default`.`id` ASC  LIMIT 1;
SELECT `srfuzz_mut_1180`.`test_default`.`id` FROM `srfuzz_mut_1180`.`test_default`;