SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`;
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`;
SELECT `bill_detail`.`bill_code` FROM (SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` EXCEPT SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`) `bill_detail`;
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` LIMIT 7, 1;
SELECT DISTINCT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`;
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`) SELECT `bill_detail`.`bill_code` FROM `srfuzz_n1` AS bill_detail;
SELECT `bill_detail`.`bill_code` FROM (SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`) `bill_detail`;
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` ORDER BY `srfuzz_mut_945`.`bill_detail`.`bill_code` ASC;
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` LIMIT 1;
SELECT `bill_detail`.`bill_code` FROM (SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` EXCEPT SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`) `bill_detail`;
SELECT `bill_detail`.`bill_code` FROM (SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`) `bill_detail`;
SELECT `bill_detail`.`bill_code` FROM (SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` EXCEPT SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`) `bill_detail`;
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` LIMIT 1, 0;
SELECT DISTINCT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`;
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `bill_detail`.`bill_code` FROM (SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` EXCEPT SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`) `bill_detail`;
SELECT DISTINCT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`;
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` ORDER BY `srfuzz_mut_945`.`bill_detail`.`bill_code` DESC;
SELECT `bill_detail`.`bill_code` FROM (SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` EXCEPT SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`) `bill_detail`;
SELECT `bill_detail`.`bill_code` FROM (SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`) `bill_detail`;
SELECT `bill_detail`.`bill_code`, `srfuzz_n1`.`e` FROM (SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`) `bill_detail` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT `bill_detail`.`bill_code`, `srfuzz_n1`.`bill_code` FROM (SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`) `bill_detail` RIGHT OUTER JOIN (SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`) `srfuzz_n1` ON `bill_detail`.`bill_code` = `srfuzz_n1`.`bill_code`;
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT DISTINCT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT DISTINCT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE 'JT2921712368984' = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 1.0E308;
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE 'JT2921712368984' = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`;
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984' ORDER BY `srfuzz_mut_945`.`bill_detail`.`bill_code` DESC NULLS FIRST;
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = -2147483648;
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`) SELECT `bill_detail`.`bill_code` FROM `srfuzz_n1` AS bill_detail WHERE `bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 1.0E308;
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = (get_json_string(CAST('JT2921712368984' AS JSON), '$.a'));
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984' ORDER BY `srfuzz_mut_945`.`bill_detail`.`bill_code` ASC;
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984' ORDER BY `srfuzz_mut_945`.`bill_detail`.`bill_code` ASC;
SELECT DISTINCT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE (CAST(`srfuzz_mut_945`.`bill_detail`.`bill_code` AS JSON)->'k') = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = `srfuzz_mut_945`.`bill_detail`.`bill_code`;
SELECT `bill_detail`.`bill_code`, `srfuzz_n1`.`bill_code` FROM (SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`) `bill_detail` RIGHT OUTER JOIN (SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`) `srfuzz_n1` ON `bill_detail`.`bill_code` = `srfuzz_n1`.`bill_code`;
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` ORDER BY `srfuzz_mut_945`.`bill_detail`.`bill_code` DESC NULLS FIRST;
SELECT `bill_detail`.`bill_code` FROM (SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` UNION SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`) `bill_detail`;
SELECT DISTINCT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`;
SELECT DISTINCT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`;
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` ORDER BY `srfuzz_mut_945`.`bill_detail`.`bill_code` ASC;
SELECT DISTINCT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`;
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `bill_detail`.`bill_code`, `srfuzz_n1`.`e` FROM (SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`) `bill_detail` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`) SELECT `bill_detail`.`bill_code` FROM `srfuzz_n1` AS bill_detail;
SELECT `bill_detail`.`bill_code` FROM (SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` EXCEPT SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`) `bill_detail`;
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` ORDER BY `srfuzz_mut_945`.`bill_detail`.`bill_code` DESC;
SELECT `bill_detail`.`bill_code` FROM (SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` UNION ALL SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail`) `bill_detail`;
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` WHERE `srfuzz_mut_945`.`bill_detail`.`bill_code` = 'JT2921712368984';
SELECT `srfuzz_mut_945`.`bill_detail`.`bill_code` FROM `srfuzz_mut_945`.`bill_detail` ORDER BY `srfuzz_mut_945`.`bill_detail`.`bill_code` ASC;