SELECT `srfuzz_mut_304`.`test_table`.`id1`, `srfuzz_mut_304`.`test_table`.`id2` FROM `srfuzz_mut_304`.`test_table`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t`;
SELECT `srfuzz_mut_304`.`t_dictmapping_add_generated_column_with_dict_mapping`.`col_1`, `srfuzz_mut_304`.`t_dictmapping_add_generated_column_with_dict_mapping`.`col_2` FROM `srfuzz_mut_304`.`t_dictmapping_add_generated_column_with_dict_mapping`;
SELECT dict_mapping('t_dictmapping_null_if_not_found', 2) AS `dict_mapping('t_dictmapping_null_if_not_found', 2)`;
SELECT dict_mapping('t_dictmapping_null_if_not_found', 2, FALSE) AS `dict_mapping('t_dictmapping_null_if_not_found', 2, FALSE)`;
SELECT dict_mapping('t_dictmapping_null_if_not_found', 2, TRUE) AS `dict_mapping('t_dictmapping_null_if_not_found', 2, TRUE)`;
SELECT `test_table`.`id1`, `test_table`.`id2`, `srfuzz_n1`.`id1`, `srfuzz_n1`.`id2` FROM (SELECT `srfuzz_mut_304`.`test_table`.`id1`, `srfuzz_mut_304`.`test_table`.`id2` FROM `srfuzz_mut_304`.`test_table`) `test_table` RIGHT OUTER JOIN (SELECT `srfuzz_mut_304`.`test_table`.`id1`, `srfuzz_mut_304`.`test_table`.`id2` FROM `srfuzz_mut_304`.`test_table`) `srfuzz_n1` ON 1 = 1;
SELECT `test_table`.`id1`, `test_table`.`id2` FROM (SELECT `srfuzz_mut_304`.`test_table`.`id1`, `srfuzz_mut_304`.`test_table`.`id2` FROM `srfuzz_mut_304`.`test_table` INTERSECT SELECT `srfuzz_mut_304`.`test_table`.`id1`, `srfuzz_mut_304`.`test_table`.`id2` FROM `srfuzz_mut_304`.`test_table`) `test_table`;
SELECT `srfuzz_mut_304`.`test_table`.`id1`, `srfuzz_mut_304`.`test_table`.`id2` FROM `srfuzz_mut_304`.`test_table` WHERE TRUE;
SELECT `test_table`.`id1`, `test_table`.`id2` FROM (SELECT `srfuzz_mut_304`.`test_table`.`id1`, `srfuzz_mut_304`.`test_table`.`id2` FROM `srfuzz_mut_304`.`test_table` UNION ALL SELECT `srfuzz_mut_304`.`test_table`.`id1`, `srfuzz_mut_304`.`test_table`.`id2` FROM `srfuzz_mut_304`.`test_table`) `test_table`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_304`.`test_table`.`id1`, `srfuzz_mut_304`.`test_table`.`id2` FROM `srfuzz_mut_304`.`test_table`) SELECT `test_table`.`id1`, `test_table`.`id2` FROM `srfuzz_n1` AS test_table;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_304`.`test_table`.`id1`, `srfuzz_mut_304`.`test_table`.`id2` FROM `srfuzz_mut_304`.`test_table`) SELECT `test_table`.`id1`, `test_table`.`id2` FROM `srfuzz_n1` AS test_table;
SELECT `srfuzz_mut_304`.`test_table`.`id1`, `srfuzz_mut_304`.`test_table`.`id2` FROM `srfuzz_mut_304`.`test_table` LIMIT 100;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_304`.`test_table`.`id1`, `srfuzz_mut_304`.`test_table`.`id2` FROM `srfuzz_mut_304`.`test_table`) SELECT `test_table`.`id1`, `test_table`.`id2` FROM `srfuzz_n1` AS test_table;
SELECT `test_table`.`id1`, `test_table`.`id2` FROM (SELECT `srfuzz_mut_304`.`test_table`.`id1`, `srfuzz_mut_304`.`test_table`.`id2` FROM `srfuzz_mut_304`.`test_table` EXCEPT SELECT `srfuzz_mut_304`.`test_table`.`id1`, `srfuzz_mut_304`.`test_table`.`id2` FROM `srfuzz_mut_304`.`test_table`) `test_table`;
SELECT `srfuzz_mut_304`.`test_table`.`id1`, `srfuzz_mut_304`.`test_table`.`id2` FROM `srfuzz_mut_304`.`test_table` WHERE FALSE;
SELECT `srfuzz_mut_304`.`test_table`.`id1`, `srfuzz_mut_304`.`test_table`.`id2` FROM `srfuzz_mut_304`.`test_table` LIMIT 7, 5;
SELECT `srfuzz_mut_304`.`test_table`.`id1`, `srfuzz_mut_304`.`test_table`.`id2` FROM `srfuzz_mut_304`.`test_table` LIMIT 1, 5;
SELECT DISTINCT `srfuzz_mut_304`.`test_table`.`id1`, `srfuzz_mut_304`.`test_table`.`id2` FROM `srfuzz_mut_304`.`test_table`;
SELECT `srfuzz_mut_304`.`test_table`.`id1`, `srfuzz_mut_304`.`test_table`.`id2` FROM `srfuzz_mut_304`.`test_table` LIMIT 1, 1;
SELECT `srfuzz_mut_304`.`test_table`.`id1`, `srfuzz_mut_304`.`test_table`.`id2` FROM `srfuzz_mut_304`.`test_table` LIMIT 1, 2;
SELECT `test_table`.`id1`, `test_table`.`id2` FROM (SELECT `srfuzz_mut_304`.`test_table`.`id1`, `srfuzz_mut_304`.`test_table`.`id2` FROM `srfuzz_mut_304`.`test_table` UNION SELECT `srfuzz_mut_304`.`test_table`.`id1`, `srfuzz_mut_304`.`test_table`.`id2` FROM `srfuzz_mut_304`.`test_table`) `test_table`;
SELECT `srfuzz_mut_304`.`test_table`.`id1`, `srfuzz_mut_304`.`test_table`.`id2` FROM `srfuzz_mut_304`.`test_table` WHERE TRUE;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, 'dict') AS `dict_mapping('dict', col_1, 'dict')` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_2`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_2, col_2)` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `t`.`col_1`, `t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM (SELECT `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2` FROM `srfuzz_mut_304`.`t` UNION SELECT `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2` FROM `srfuzz_mut_304`.`t`) `t`;
SELECT DISTINCT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', 'dict', `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', 'dict', col_2)` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `t`.`col_1`, `t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM (SELECT `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2` FROM `srfuzz_mut_304`.`t` EXCEPT SELECT `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2` FROM `srfuzz_mut_304`.`t`) `t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t` LIMIT 1, 2;
SELECT dict_mapping('dict', 'dict', `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', 'dict', col_2)` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, get_json_string(CAST(`srfuzz_mut_304`.`t`.`col_2` AS JSON), '$.a')) AS `dict_mapping('dict', col_1, get_json_string(CAST(col_2 AS JSON), '$.a'))` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_1`) AS `dict_mapping('dict', col_1, col_1)` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t` ORDER BY dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) ASC;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', srfuzz_mut_304.t.col_1, col_2)` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t` LIMIT 5;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_1`) AS `dict_mapping('dict', col_1, srfuzz_mut_304.t.col_1)` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', 'dict', `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', 'dict', col_2)` FROM `srfuzz_mut_304`.`t`;
SELECT DISTINCT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t`;
SELECT json_query(CAST((dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`)) AS JSON), '$.a') AS `json_query(CAST((dict_mapping('dict', col_1, col_2)) AS JSON), '$.a')` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `t`.`col_1`, `t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM (SELECT `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2` FROM `srfuzz_mut_304`.`t`) `t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t` GROUP BY dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`);
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`)) AS `dict_mapping('dict', col_1, dict_mapping('dict', srfuzz_mut_304.t.col_1, srfuzz_mut_304.t.col_2))` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `t`.`col_1`, `t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM (SELECT `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2` FROM `srfuzz_mut_304`.`t` UNION SELECT `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2` FROM `srfuzz_mut_304`.`t`) `t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t` LIMIT 0;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t` ORDER BY dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) ASC NULLS LAST;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t` GROUP BY dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`);
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t`;
SELECT json_query(CAST((dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`)) AS JSON), '$.a') AS `json_query(CAST((dict_mapping('dict', col_1, col_2)) AS JSON), '$.a')` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, 'dict') AS `dict_mapping('dict', col_1, 'dict')` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_2`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', srfuzz_mut_304.t.col_2, col_2)` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', 'dict', `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', 'dict', col_2)` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, 'dict') AS `dict_mapping('dict', col_1, 'dict')` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t` WHERE FALSE;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t` LIMIT 5;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, CAST((CAST(`srfuzz_mut_304`.`t`.`col_2` AS BOOLEAN)) AS FLOAT)) AS `dict_mapping('dict', col_1, CAST((CAST(col_2 AS BOOLEAN)) AS FLOAT))` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `t`.`col_1`, `t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM (SELECT `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2` FROM `srfuzz_mut_304`.`t`) `t`;
SELECT dict_mapping('dict', dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`), `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', dict_mapping('dict', srfuzz_mut_304.t.col_1, srfuzz_mut_304.t.col_2), col_2)` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t` ORDER BY dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) DESC;
SELECT dict_mapping('dict', dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`), `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', dict_mapping('dict', srfuzz_mut_304.t.col_1, srfuzz_mut_304.t.col_2), col_2)` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, get_json_string(CAST(`srfuzz_mut_304`.`t`.`col_2` AS JSON), '$.a')) AS `dict_mapping('dict', col_1, get_json_string(CAST(col_2 AS JSON), '$.a'))` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, 'dict') AS `dict_mapping('dict', col_1, 'dict')` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t` WHERE FALSE;
SELECT dict_mapping('dict', 'dict', `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', 'dict', col_2)` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t` ORDER BY dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) DESC;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_2`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_2, col_2)` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t`;
SELECT DISTINCT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, 'dict') AS `dict_mapping('dict', col_1, 'dict')` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t`;
SELECT dict_mapping('dict', `t`.`col_1`, `t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM (SELECT `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2` FROM `srfuzz_mut_304`.`t` UNION SELECT `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2` FROM `srfuzz_mut_304`.`t`) `t`;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, `srfuzz_mut_304`.`t`.`col_2`) AS `dict_mapping('dict', col_1, col_2)` FROM `srfuzz_mut_304`.`t` WHERE FALSE;
SELECT dict_mapping('dict', `srfuzz_mut_304`.`t`.`col_1`, CAST(`srfuzz_mut_304`.`t`.`col_2` AS DECIMAL64(1,0))) AS `dict_mapping('dict', col_1, CAST(col_2 AS DECIMAL64(1,0)))` FROM `srfuzz_mut_304`.`t`;