SELECT `srfuzz_mut_1069`.`test_json_config`.`id`, `srfuzz_mut_1069`.`test_json_config`.`my_json_col` FROM `srfuzz_mut_1069`.`test_json_config` ORDER BY `srfuzz_mut_1069`.`test_json_config`.`id` ASC;
SELECT `srfuzz_mut_1069`.`test_json_config`.`id`, `srfuzz_mut_1069`.`test_json_config`.`my_json_col` FROM `srfuzz_mut_1069`.`test_json_config` ORDER BY `srfuzz_mut_1069`.`test_json_config`.`id` ASC;
SELECT `srfuzz_mut_1069`.`test_json_config`.`id`, `srfuzz_mut_1069`.`test_json_config`.`my_json_col`->'$.key1' AS `my_json_col->'$.key1'` FROM `srfuzz_mut_1069`.`test_json_config` ORDER BY `srfuzz_mut_1069`.`test_json_config`.`id` ASC;
SELECT `srfuzz_mut_1069`.`test_json_config`.`id`, `srfuzz_mut_1069`.`test_json_config`.`my_json_col` FROM `srfuzz_mut_1069`.`test_json_config` ORDER BY `srfuzz_mut_1069`.`test_json_config`.`id` ASC;
SELECT `srfuzz_mut_1069`.`test_json_config`.`id`, `srfuzz_mut_1069`.`test_json_config`.`my_json_col`->'$.key2' AS `my_json_col->'$.key2'` FROM `srfuzz_mut_1069`.`test_json_config` ORDER BY `srfuzz_mut_1069`.`test_json_config`.`id` ASC;
SELECT `srfuzz_mut_1069`.`test_json_config`.`id`, `srfuzz_mut_1069`.`test_json_config`.`my_json_col` FROM `srfuzz_mut_1069`.`test_json_config` ORDER BY `srfuzz_mut_1069`.`test_json_config`.`id` ASC;
SELECT `srfuzz_mut_1069`.`test_json_config`.`id`, `srfuzz_mut_1069`.`test_json_config`.`my_json_col`->'$.key3' AS `my_json_col->'$.key3'` FROM `srfuzz_mut_1069`.`test_json_config` ORDER BY `srfuzz_mut_1069`.`test_json_config`.`id` ASC;
SELECT `srfuzz_mut_1069`.`test_json_config`.`id`, `srfuzz_mut_1069`.`test_json_config`.`my_json_col` FROM `srfuzz_mut_1069`.`test_json_config` ORDER BY `srfuzz_mut_1069`.`test_json_config`.`id` ASC;
SELECT `srfuzz_mut_1069`.`test_json_config`.`id`, `srfuzz_mut_1069`.`test_json_config`.`my_json_col`->'$.key1' AS `my_json_col->'$.key1'` FROM `srfuzz_mut_1069`.`test_json_config` ORDER BY `srfuzz_mut_1069`.`test_json_config`.`id` ASC;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1069`.`test_json_config`;
SELECT `srfuzz_mut_1069`.`test_json_config`.`id`, `srfuzz_mut_1069`.`test_json_config`.`my_json_col` FROM `srfuzz_mut_1069`.`test_json_config` ORDER BY `srfuzz_mut_1069`.`test_json_config`.`id` ASC;
SELECT `srfuzz_mut_1069`.`test_json_config`.`id`, `srfuzz_mut_1069`.`test_json_config`.`my_json_col`->'$.key2' AS `my_json_col->'$.key2'` FROM `srfuzz_mut_1069`.`test_json_config` ORDER BY `srfuzz_mut_1069`.`test_json_config`.`id` ASC;
SELECT `srfuzz_mut_1069`.`test_json_config`.`id` FROM `srfuzz_mut_1069`.`test_json_config` ORDER BY `srfuzz_mut_1069`.`test_json_config`.`id` ASC;
SELECT `srfuzz_mut_1069`.`test_json_config`.`my_json_col` FROM `srfuzz_mut_1069`.`test_json_config` ORDER BY `srfuzz_mut_1069`.`test_json_config`.`id` ASC;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1069`.`test_json_config`;
SELECT `srfuzz_mut_1069`.`test_json_config`.`id`, `srfuzz_mut_1069`.`test_json_config`.`my_json_col`->'$.key1' AS `my_json_col->'$.key1'` FROM `srfuzz_mut_1069`.`test_json_config` ORDER BY `srfuzz_mut_1069`.`test_json_config`.`id` ASC;
SELECT `srfuzz_mut_1069`.`test_json_config`.`id`, `srfuzz_mut_1069`.`test_json_config`.`my_json_col` FROM `srfuzz_mut_1069`.`test_json_config` ORDER BY `srfuzz_mut_1069`.`test_json_config`.`id` ASC;
SELECT `srfuzz_mut_1069`.`test_json_config`.`id`, `srfuzz_mut_1069`.`test_json_config`.`my_json_col` FROM `srfuzz_mut_1069`.`test_json_config` ORDER BY `srfuzz_mut_1069`.`test_json_config`.`id` ASC;
SELECT `srfuzz_mut_1069`.`test_json_config`.`my_json_col`->'$.key1' AS `my_json_col->'$.key1'` FROM `srfuzz_mut_1069`.`test_json_config` ORDER BY `srfuzz_mut_1069`.`test_json_config`.`id` ASC;
SELECT `srfuzz_mut_1069`.`test_json_config`.`my_json_col`->'$.key2' AS `my_json_col->'$.key2'` FROM `srfuzz_mut_1069`.`test_json_config` ORDER BY `srfuzz_mut_1069`.`test_json_config`.`id` ASC;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1069`.`test_json_config`;