SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city`, 255) AS `dict_merge(city, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_null`, 255) AS `dict_merge(city_null, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array`, 255) AS `dict_merge(city_array, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array_null`, 255) AS `dict_merge(city_array_null, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 256) AS `dict_merge(c2, 256)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 512) AS `dict_merge(c2, 512)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 1024) AS `dict_merge(c2, 1024)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t2`.`c1`, 256) AS `dict_merge(c1, 256)` FROM `srfuzz_mut_45`.`t2` GROUP BY `srfuzz_mut_45`.`t2`.`c1` ORDER BY `srfuzz_mut_45`.`t2`.`c1` ASC  LIMIT 10;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city`, 255) AS `dict_merge(city, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city`, 255) AS `dict_merge(city, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`test_dict_merge`.`city`, 255) AS `dict_merge(city, 255)` FROM (SELECT `srfuzz_mut_45`.`test_dict_merge`.`id`, `srfuzz_mut_45`.`test_dict_merge`.`city`, `srfuzz_mut_45`.`test_dict_merge`.`city_null`, `srfuzz_mut_45`.`test_dict_merge`.`city_array`, `srfuzz_mut_45`.`test_dict_merge`.`city_array_null` FROM `srfuzz_mut_45`.`test_dict_merge` INTERSECT SELECT `srfuzz_mut_45`.`test_dict_merge`.`id`, `srfuzz_mut_45`.`test_dict_merge`.`city`, `srfuzz_mut_45`.`test_dict_merge`.`city_null`, `srfuzz_mut_45`.`test_dict_merge`.`city_array`, `srfuzz_mut_45`.`test_dict_merge`.`city_array_null` FROM `srfuzz_mut_45`.`test_dict_merge`) `test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city`, 255) AS `dict_merge(city, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(255, 255) AS `dict_merge(255, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT avg(dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city`, 255)) OVER () AS `avg(dict_merge(city, 255)) OVER ()` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city`, 255) AS `dict_merge(city, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city`, 255) AS `dict_merge(city, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city`, 255) AS `dict_merge(city, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city`, 255) AS `dict_merge(city, 255)` FROM `srfuzz_mut_45`.`test_dict_merge` LIMIT 7, 2;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city`, 255) AS `dict_merge(srfuzz_mut_45.test_dict_merge.city, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`test_dict_merge`.`city`, 255) AS `dict_merge(city, 255)` FROM (SELECT `srfuzz_mut_45`.`test_dict_merge`.`id`, `srfuzz_mut_45`.`test_dict_merge`.`city`, `srfuzz_mut_45`.`test_dict_merge`.`city_null`, `srfuzz_mut_45`.`test_dict_merge`.`city_array`, `srfuzz_mut_45`.`test_dict_merge`.`city_array_null` FROM `srfuzz_mut_45`.`test_dict_merge` UNION SELECT `srfuzz_mut_45`.`test_dict_merge`.`id`, `srfuzz_mut_45`.`test_dict_merge`.`city`, `srfuzz_mut_45`.`test_dict_merge`.`city_null`, `srfuzz_mut_45`.`test_dict_merge`.`city_array`, `srfuzz_mut_45`.`test_dict_merge`.`city_array_null` FROM `srfuzz_mut_45`.`test_dict_merge`) `test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city`, 255) AS `dict_merge(srfuzz_mut_45.test_dict_merge.city, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array`, 255) AS `dict_merge(city_array, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city`, 255) AS `dict_merge(srfuzz_mut_45.test_dict_merge.city, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city`, 255) AS `dict_merge(city, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city`, 255) AS `dict_merge(city, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_null`, 255) AS `dict_merge(city_null, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`test_dict_merge`.`city_null`, 255) AS `dict_merge(city_null, 255)` FROM (SELECT `srfuzz_mut_45`.`test_dict_merge`.`id`, `srfuzz_mut_45`.`test_dict_merge`.`city`, `srfuzz_mut_45`.`test_dict_merge`.`city_null`, `srfuzz_mut_45`.`test_dict_merge`.`city_array`, `srfuzz_mut_45`.`test_dict_merge`.`city_array_null` FROM `srfuzz_mut_45`.`test_dict_merge` INTERSECT SELECT `srfuzz_mut_45`.`test_dict_merge`.`id`, `srfuzz_mut_45`.`test_dict_merge`.`city`, `srfuzz_mut_45`.`test_dict_merge`.`city_null`, `srfuzz_mut_45`.`test_dict_merge`.`city_array`, `srfuzz_mut_45`.`test_dict_merge`.`city_array_null` FROM `srfuzz_mut_45`.`test_dict_merge`) `test_dict_merge`;
SELECT dict_merge(`test_dict_merge`.`city_null`, 255) AS `dict_merge(city_null, 255)` FROM (SELECT `srfuzz_mut_45`.`test_dict_merge`.`id`, `srfuzz_mut_45`.`test_dict_merge`.`city`, `srfuzz_mut_45`.`test_dict_merge`.`city_null`, `srfuzz_mut_45`.`test_dict_merge`.`city_array`, `srfuzz_mut_45`.`test_dict_merge`.`city_array_null` FROM `srfuzz_mut_45`.`test_dict_merge` UNION SELECT `srfuzz_mut_45`.`test_dict_merge`.`id`, `srfuzz_mut_45`.`test_dict_merge`.`city`, `srfuzz_mut_45`.`test_dict_merge`.`city_null`, `srfuzz_mut_45`.`test_dict_merge`.`city_array`, `srfuzz_mut_45`.`test_dict_merge`.`city_array_null` FROM `srfuzz_mut_45`.`test_dict_merge`) `test_dict_merge`;
SELECT dict_merge(`test_dict_merge`.`city_null`, 255) AS `dict_merge(city_null, 255)` FROM (SELECT `srfuzz_mut_45`.`test_dict_merge`.`id`, `srfuzz_mut_45`.`test_dict_merge`.`city`, `srfuzz_mut_45`.`test_dict_merge`.`city_null`, `srfuzz_mut_45`.`test_dict_merge`.`city_array`, `srfuzz_mut_45`.`test_dict_merge`.`city_array_null` FROM `srfuzz_mut_45`.`test_dict_merge` EXCEPT SELECT `srfuzz_mut_45`.`test_dict_merge`.`id`, `srfuzz_mut_45`.`test_dict_merge`.`city`, `srfuzz_mut_45`.`test_dict_merge`.`city_null`, `srfuzz_mut_45`.`test_dict_merge`.`city_array`, `srfuzz_mut_45`.`test_dict_merge`.`city_array_null` FROM `srfuzz_mut_45`.`test_dict_merge`) `test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_null`, 1) AS `dict_merge(city_null, 1)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_null`, 255) AS `dict_merge(city_null, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_null`, 255) AS `dict_merge(city_null, 255)` FROM `srfuzz_mut_45`.`test_dict_merge` ORDER BY dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_null`, 255) DESC NULLS FIRST;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_null`, 255) AS `dict_merge(city_null, 255)` FROM `srfuzz_mut_45`.`test_dict_merge` ORDER BY dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_null`, 255) DESC;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_null`, 255) AS `dict_merge(city_null, 255)` FROM `srfuzz_mut_45`.`test_dict_merge` ORDER BY dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_null`, 255) DESC;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_null`, 255) AS `dict_merge(city_null, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city`, 255) AS `dict_merge(city, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`test_dict_merge`.`city_null`, 255) AS `dict_merge(city_null, 255)` FROM (SELECT `srfuzz_mut_45`.`test_dict_merge`.`id`, `srfuzz_mut_45`.`test_dict_merge`.`city`, `srfuzz_mut_45`.`test_dict_merge`.`city_null`, `srfuzz_mut_45`.`test_dict_merge`.`city_array`, `srfuzz_mut_45`.`test_dict_merge`.`city_array_null` FROM `srfuzz_mut_45`.`test_dict_merge` EXCEPT SELECT `srfuzz_mut_45`.`test_dict_merge`.`id`, `srfuzz_mut_45`.`test_dict_merge`.`city`, `srfuzz_mut_45`.`test_dict_merge`.`city_null`, `srfuzz_mut_45`.`test_dict_merge`.`city_array`, `srfuzz_mut_45`.`test_dict_merge`.`city_array_null` FROM `srfuzz_mut_45`.`test_dict_merge`) `test_dict_merge`;
SELECT dict_merge(255, 255) AS `dict_merge(255, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dense_rank() OVER (ORDER BY dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_null`, 255) ASC ) AS `dense_rank() OVER (ORDER BY dict_merge(city_null, 255) ASC )` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_null`, 255) AS `dict_merge(srfuzz_mut_45.test_dict_merge.city_null, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(255, 255) AS `dict_merge(255, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_null`, 255) AS `dict_merge(srfuzz_mut_45.test_dict_merge.city_null, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`test_dict_merge`.`city_null`, 255) AS `dict_merge(city_null, 255)` FROM (SELECT `srfuzz_mut_45`.`test_dict_merge`.`id`, `srfuzz_mut_45`.`test_dict_merge`.`city`, `srfuzz_mut_45`.`test_dict_merge`.`city_null`, `srfuzz_mut_45`.`test_dict_merge`.`city_array`, `srfuzz_mut_45`.`test_dict_merge`.`city_array_null` FROM `srfuzz_mut_45`.`test_dict_merge` UNION ALL SELECT `srfuzz_mut_45`.`test_dict_merge`.`id`, `srfuzz_mut_45`.`test_dict_merge`.`city`, `srfuzz_mut_45`.`test_dict_merge`.`city_null`, `srfuzz_mut_45`.`test_dict_merge`.`city_array`, `srfuzz_mut_45`.`test_dict_merge`.`city_array_null` FROM `srfuzz_mut_45`.`test_dict_merge`) `test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_null`, 255) AS `dict_merge(city_null, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_null`, 255) AS `dict_merge(city_null, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_45`.`test_dict_merge`.`id`, `srfuzz_mut_45`.`test_dict_merge`.`city`, `srfuzz_mut_45`.`test_dict_merge`.`city_null`, `srfuzz_mut_45`.`test_dict_merge`.`city_array`, `srfuzz_mut_45`.`test_dict_merge`.`city_array_null` FROM `srfuzz_mut_45`.`test_dict_merge`) SELECT dict_merge(`test_dict_merge`.`city_array`, 255) AS `dict_merge(city_array, 255)` FROM `srfuzz_n1` AS test_dict_merge;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array`[1], 255) AS `dict_merge(city_array[1], 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT CAST((dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array`, 255)) AS JSON)->'k' AS `CAST((dict_merge(city_array, 255)) AS JSON)->'k'` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT row_number() OVER (ORDER BY dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array`, 255) ASC ) AS `row_number() OVER (ORDER BY dict_merge(city_array, 255) ASC )` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT rank() OVER (ORDER BY dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array`, 255) ASC ) AS `rank() OVER (ORDER BY dict_merge(city_array, 255) ASC )` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(255, 255) AS `dict_merge(255, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array`, 255) AS `dict_merge(city_array, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT json_length(CAST((dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array`, 255)) AS JSON)) AS `json_length(CAST((dict_merge(city_array, 255)) AS JSON))` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`test_dict_merge`.`city_array`, 255) AS `dict_merge(city_array, 255)` FROM (SELECT `srfuzz_mut_45`.`test_dict_merge`.`id`, `srfuzz_mut_45`.`test_dict_merge`.`city`, `srfuzz_mut_45`.`test_dict_merge`.`city_null`, `srfuzz_mut_45`.`test_dict_merge`.`city_array`, `srfuzz_mut_45`.`test_dict_merge`.`city_array_null` FROM `srfuzz_mut_45`.`test_dict_merge` UNION SELECT `srfuzz_mut_45`.`test_dict_merge`.`id`, `srfuzz_mut_45`.`test_dict_merge`.`city`, `srfuzz_mut_45`.`test_dict_merge`.`city_null`, `srfuzz_mut_45`.`test_dict_merge`.`city_array`, `srfuzz_mut_45`.`test_dict_merge`.`city_array_null` FROM `srfuzz_mut_45`.`test_dict_merge`) `test_dict_merge`;
SELECT dict_merge(`test_dict_merge`.`city_array`, 255) AS `dict_merge(city_array, 255)` FROM (SELECT `srfuzz_mut_45`.`test_dict_merge`.`id`, `srfuzz_mut_45`.`test_dict_merge`.`city`, `srfuzz_mut_45`.`test_dict_merge`.`city_null`, `srfuzz_mut_45`.`test_dict_merge`.`city_array`, `srfuzz_mut_45`.`test_dict_merge`.`city_array_null` FROM `srfuzz_mut_45`.`test_dict_merge` INTERSECT SELECT `srfuzz_mut_45`.`test_dict_merge`.`id`, `srfuzz_mut_45`.`test_dict_merge`.`city`, `srfuzz_mut_45`.`test_dict_merge`.`city_null`, `srfuzz_mut_45`.`test_dict_merge`.`city_array`, `srfuzz_mut_45`.`test_dict_merge`.`city_array_null` FROM `srfuzz_mut_45`.`test_dict_merge`) `test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array`, 255) AS `dict_merge(city_array, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array`, 255) AS `dict_merge(city_array, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array`, 255) AS `dict_merge(srfuzz_mut_45.test_dict_merge.city_array, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array`, 255) AS `dict_merge(srfuzz_mut_45.test_dict_merge.city_array, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array`, 255) AS `dict_merge(city_array, 255)` FROM `srfuzz_mut_45`.`test_dict_merge` LIMIT 7, 1;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array`[2], 255) AS `dict_merge(city_array[2], 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(255, 255) AS `dict_merge(255, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array`, 255) AS `dict_merge(city_array, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array_null`, 255) AS `dict_merge(city_array_null, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array_null`, 255) AS `dict_merge(srfuzz_mut_45.test_dict_merge.city_array_null, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array_null`, 255) AS `dict_merge(srfuzz_mut_45.test_dict_merge.city_array_null, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array_null`, 255) AS `dict_merge(city_array_null, 255)` FROM `srfuzz_mut_45`.`test_dict_merge` LIMIT 1;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array_null`, 255) AS `dict_merge(srfuzz_mut_45.test_dict_merge.city_array_null, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city`, 255) AS `dict_merge(city, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array_null`, 255) AS `dict_merge(city_array_null, 255)` FROM `srfuzz_mut_45`.`test_dict_merge` LIMIT 7, 2;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array_null`, CAST(255 AS INT)) AS `dict_merge(city_array_null, CAST(255 AS INT))` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`test_dict_merge`.`city_array_null`, 255) AS `dict_merge(city_array_null, 255)` FROM (SELECT `srfuzz_mut_45`.`test_dict_merge`.`id`, `srfuzz_mut_45`.`test_dict_merge`.`city`, `srfuzz_mut_45`.`test_dict_merge`.`city_null`, `srfuzz_mut_45`.`test_dict_merge`.`city_array`, `srfuzz_mut_45`.`test_dict_merge`.`city_array_null` FROM `srfuzz_mut_45`.`test_dict_merge`) `test_dict_merge` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_45`.`test_dict_merge`.`id`, `srfuzz_mut_45`.`test_dict_merge`.`city`, `srfuzz_mut_45`.`test_dict_merge`.`city_null`, `srfuzz_mut_45`.`test_dict_merge`.`city_array`, `srfuzz_mut_45`.`test_dict_merge`.`city_array_null` FROM `srfuzz_mut_45`.`test_dict_merge`) SELECT dict_merge(`test_dict_merge`.`city_array_null`, 255) AS `dict_merge(city_array_null, 255)` FROM `srfuzz_n1` AS test_dict_merge;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array_null`, 255) AS `dict_merge(city_array_null, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array_null`, 255) AS `dict_merge(city_array_null, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`test_dict_merge`.`city_array_null`, 255) AS `dict_merge(city_array_null, 255)` FROM (SELECT `srfuzz_mut_45`.`test_dict_merge`.`id`, `srfuzz_mut_45`.`test_dict_merge`.`city`, `srfuzz_mut_45`.`test_dict_merge`.`city_null`, `srfuzz_mut_45`.`test_dict_merge`.`city_array`, `srfuzz_mut_45`.`test_dict_merge`.`city_array_null` FROM `srfuzz_mut_45`.`test_dict_merge` EXCEPT SELECT `srfuzz_mut_45`.`test_dict_merge`.`id`, `srfuzz_mut_45`.`test_dict_merge`.`city`, `srfuzz_mut_45`.`test_dict_merge`.`city_null`, `srfuzz_mut_45`.`test_dict_merge`.`city_array`, `srfuzz_mut_45`.`test_dict_merge`.`city_array_null` FROM `srfuzz_mut_45`.`test_dict_merge`) `test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array_null`, 255) AS `dict_merge(city_array_null, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array_null`, 255) AS `dict_merge(city_array_null, 255)` FROM `srfuzz_mut_45`.`test_dict_merge` LIMIT 7, 2;
SELECT dict_merge(`srfuzz_mut_45`.`test_dict_merge`.`city_array_null`, 255) AS `dict_merge(city_array_null, 255)` FROM `srfuzz_mut_45`.`test_dict_merge` LIMIT 5;
SELECT dict_merge(255, 255) AS `dict_merge(255, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(255, 255) AS `dict_merge(255, 255)` FROM `srfuzz_mut_45`.`test_dict_merge`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 256) AS `dict_merge(c2, 256)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 256) AS `dict_merge(c2, 256)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 256) AS `dict_merge(c2, 256)` FROM `srfuzz_mut_45`.`t1`;
SELECT get_json_string(CAST((dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 256)) AS JSON), '$.a') AS `get_json_string(CAST((dict_merge(c2, 256)) AS JSON), '$.a')` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 256) AS `dict_merge(srfuzz_mut_45.t1.c2, 256)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 256) AS `dict_merge(c2, 256)` FROM `srfuzz_mut_45`.`t1` LIMIT 1, 100;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 256) AS `dict_merge(c2, 256)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 256) AS `dict_merge(c2, 256)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 256) AS `dict_merge(c2, 256)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`t1`.`c2`, 256) AS `dict_merge(c2, 256)` FROM (SELECT `srfuzz_mut_45`.`t1`.`c1`, `srfuzz_mut_45`.`t1`.`c2` FROM `srfuzz_mut_45`.`t1` UNION SELECT `srfuzz_mut_45`.`t1`.`c1`, `srfuzz_mut_45`.`t1`.`c2` FROM `srfuzz_mut_45`.`t1`) `t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 256) AS `dict_merge(c2, 256)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 256) AS `dict_merge(c2, 256)` FROM `srfuzz_mut_45`.`t1` ORDER BY dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 256) DESC NULLS FIRST;
SELECT dict_merge(256, 256) AS `dict_merge(256, 256)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 256) AS `dict_merge(c2, 256)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 256) AS `dict_merge(c2, 256)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 0) AS `dict_merge(c2, 0)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`t1`.`c2`, 256) AS `dict_merge(c2, 256)` FROM (SELECT `srfuzz_mut_45`.`t1`.`c1`, `srfuzz_mut_45`.`t1`.`c2` FROM `srfuzz_mut_45`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 256) AS `dict_merge(c2, 256)` FROM `srfuzz_mut_45`.`t1` WHERE 1024;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 256) AS `dict_merge(srfuzz_mut_45.t1.c2, 256)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`t1`.`c2`, 256) AS `dict_merge(c2, 256)` FROM (SELECT `srfuzz_mut_45`.`t1`.`c1`, `srfuzz_mut_45`.`t1`.`c2` FROM `srfuzz_mut_45`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 512) AS `dict_merge(c2, 512)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 512) AS `dict_merge(c2, 512)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 512) AS `dict_merge(c2, 512)` FROM `srfuzz_mut_45`.`t1` ORDER BY dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 512) DESC;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 512) AS `dict_merge(c2, 512)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 512) AS `dict_merge(c2, 512)` FROM `srfuzz_mut_45`.`t1` LIMIT 7, 1;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 512) AS `dict_merge(srfuzz_mut_45.t1.c2, 512)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`t1`.`c2`, 512) AS `dict_merge(c2, 512)` FROM (SELECT `srfuzz_mut_45`.`t1`.`c1`, `srfuzz_mut_45`.`t1`.`c2` FROM `srfuzz_mut_45`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 512) AS `dict_merge(c2, 512)` FROM `srfuzz_mut_45`.`t1`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_45`.`t1`.`c1`, `srfuzz_mut_45`.`t1`.`c2` FROM `srfuzz_mut_45`.`t1`) SELECT dict_merge(`t1`.`c2`, 512) AS `dict_merge(c2, 512)` FROM `srfuzz_n1` AS t1;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 512) AS `dict_merge(srfuzz_mut_45.t1.c2, 512)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 512) AS `dict_merge(c2, 512)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 512) AS `dict_merge(c2, 512)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 512) AS `dict_merge(c2, 512)` FROM `srfuzz_mut_45`.`t1` LIMIT 7, 1;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 512) AS `dict_merge(c2, 512)` FROM `srfuzz_mut_45`.`t1`;
SELECT CAST((dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 512)) AS JSON)->'k' AS `CAST((dict_merge(c2, 512)) AS JSON)->'k'` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 512) AS `dict_merge(c2, 512)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 1024) AS `dict_merge(c2, 1024)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 1024) AS `dict_merge(c2, 1024)` FROM `srfuzz_mut_45`.`t1` LIMIT 1;
SELECT dict_merge(1024, 1024) AS `dict_merge(1024, 1024)` FROM `srfuzz_mut_45`.`t1`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_45`.`t1`.`c1`, `srfuzz_mut_45`.`t1`.`c2` FROM `srfuzz_mut_45`.`t1`) SELECT dict_merge(`t1`.`c2`, 1024) AS `dict_merge(c2, 1024)` FROM `srfuzz_n1` AS t1;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 1024) AS `dict_merge(c2, 1024)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(1024, 1024) AS `dict_merge(1024, 1024)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 1024) AS `dict_merge(c2, 1024)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(1024, 1024) AS `dict_merge(1024, 1024)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`t1`.`c2`, 1024) AS `dict_merge(c2, 1024)` FROM (SELECT `srfuzz_mut_45`.`t1`.`c1`, `srfuzz_mut_45`.`t1`.`c2` FROM `srfuzz_mut_45`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 1024) AS `dict_merge(c2, 1024)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(1024, 1024) AS `dict_merge(1024, 1024)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 1024) AS `dict_merge(srfuzz_mut_45.t1.c2, 1024)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 1024) AS `dict_merge(c2, 1024)` FROM `srfuzz_mut_45`.`t1` ORDER BY dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 1024) ASC NULLS LAST;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 1024) AS `dict_merge(c2, 1024)` FROM `srfuzz_mut_45`.`t1`;
SELECT dict_merge(`t1`.`c2`, 1024) AS `dict_merge(c2, 1024)` FROM (SELECT `srfuzz_mut_45`.`t1`.`c1`, `srfuzz_mut_45`.`t1`.`c2` FROM `srfuzz_mut_45`.`t1` INTERSECT SELECT `srfuzz_mut_45`.`t1`.`c1`, `srfuzz_mut_45`.`t1`.`c2` FROM `srfuzz_mut_45`.`t1`) `t1`;
SELECT dict_merge(`srfuzz_mut_45`.`t1`.`c2`, 1024) AS `dict_merge(c2, 1024)` FROM `srfuzz_mut_45`.`t1` LIMIT 1, 0;
SELECT dict_merge(`srfuzz_mut_45`.`t2`.`c1`, 256) AS `dict_merge(c1, 256)` FROM `srfuzz_mut_45`.`t2` GROUP BY `srfuzz_mut_45`.`t2`.`c1` ORDER BY `srfuzz_mut_45`.`t2`.`c1` ASC  LIMIT 10;
SELECT dict_merge(`srfuzz_mut_45`.`t2`.`c1`, 256) AS `dict_merge(c1, 256)` FROM `srfuzz_mut_45`.`t2` WHERE 256 GROUP BY `srfuzz_mut_45`.`t2`.`c1` ORDER BY `srfuzz_mut_45`.`t2`.`c1` ASC  LIMIT 10;
SELECT dict_merge(`srfuzz_mut_45`.`t2`.`c1`, 256) AS `dict_merge(c1, 256)` FROM `srfuzz_mut_45`.`t2` GROUP BY `srfuzz_mut_45`.`t2`.`c1` ORDER BY `srfuzz_mut_45`.`t2`.`c1` ASC  LIMIT 10;
SELECT dict_merge(`srfuzz_mut_45`.`t2`.`c1`, 256) AS `dict_merge(c1, 256)` FROM `srfuzz_mut_45`.`t2` GROUP BY `srfuzz_mut_45`.`t2`.`c1` ORDER BY `srfuzz_mut_45`.`t2`.`c1` ASC  LIMIT 10;
SELECT dict_merge(`srfuzz_mut_45`.`t2`.`c1`, 256) AS `dict_merge(c1, 256)` FROM `srfuzz_mut_45`.`t2` GROUP BY `srfuzz_mut_45`.`t2`.`c1` LIMIT 10;
SELECT dict_merge(`t2`.`c1`, 256) AS `dict_merge(c1, 256)` FROM (SELECT `srfuzz_mut_45`.`t2`.`c1`, `srfuzz_mut_45`.`t2`.`c2` FROM `srfuzz_mut_45`.`t2`) `t2` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  GROUP BY `t2`.`c1` ORDER BY `t2`.`c1` ASC  LIMIT 10;
SELECT dict_merge(`srfuzz_mut_45`.`t2`.`c1`, 256) AS `dict_merge(c1, 256)` FROM `srfuzz_mut_45`.`t2` GROUP BY `srfuzz_mut_45`.`t2`.`c1` ORDER BY `srfuzz_mut_45`.`t2`.`c1` ASC;
SELECT dict_merge(`t2`.`c1`, 256) AS `dict_merge(c1, 256)` FROM (SELECT `srfuzz_mut_45`.`t2`.`c1`, `srfuzz_mut_45`.`t2`.`c2` FROM `srfuzz_mut_45`.`t2` UNION SELECT `srfuzz_mut_45`.`t2`.`c1`, `srfuzz_mut_45`.`t2`.`c2` FROM `srfuzz_mut_45`.`t2`) `t2` GROUP BY `t2`.`c1` ORDER BY `t2`.`c1` ASC  LIMIT 10;
SELECT dict_merge(`srfuzz_mut_45`.`t2`.`c1`, 0) AS `dict_merge(c1, 0)` FROM `srfuzz_mut_45`.`t2` GROUP BY `srfuzz_mut_45`.`t2`.`c1` ORDER BY `srfuzz_mut_45`.`t2`.`c1` ASC  LIMIT 10;
SELECT dict_merge(`srfuzz_mut_45`.`t2`.`c1`, 256) AS `dict_merge(c1, 256)` FROM `srfuzz_mut_45`.`t2` GROUP BY `srfuzz_mut_45`.`t2`.`c1` LIMIT 10;
SELECT DISTINCT dict_merge(`srfuzz_mut_45`.`t2`.`c1`, 256) AS `dict_merge(c1, 256)` FROM `srfuzz_mut_45`.`t2` GROUP BY `srfuzz_mut_45`.`t2`.`c1` ORDER BY `srfuzz_mut_45`.`t2`.`c1` ASC  LIMIT 10;
SELECT dict_merge(`t2`.`c1`, 256) AS `dict_merge(c1, 256)` FROM (SELECT `srfuzz_mut_45`.`t2`.`c1`, `srfuzz_mut_45`.`t2`.`c2` FROM `srfuzz_mut_45`.`t2`) `t2` GROUP BY `t2`.`c1` ORDER BY `t2`.`c1` ASC  LIMIT 10;
SELECT dict_merge(`srfuzz_mut_45`.`t2`.`c1`, 256) AS `dict_merge(c1, 256)` FROM `srfuzz_mut_45`.`t2` GROUP BY `srfuzz_mut_45`.`t2`.`c1` ORDER BY `srfuzz_mut_45`.`t2`.`c1` ASC  LIMIT 10;
SELECT dict_merge(`srfuzz_mut_45`.`t2`.`c1`, 256) AS `dict_merge(c1, 256)` FROM `srfuzz_mut_45`.`t2` GROUP BY `srfuzz_mut_45`.`t2`.`c1` LIMIT 10;
SELECT dict_merge(`srfuzz_mut_45`.`t2`.`c1`, 256) AS `dict_merge(srfuzz_mut_45.t2.c1, 256)` FROM `srfuzz_mut_45`.`t2` GROUP BY `srfuzz_mut_45`.`t2`.`c1` ORDER BY `srfuzz_mut_45`.`t2`.`c1` ASC  LIMIT 10;
SELECT dict_merge(`t2`.`c1`, 256) AS `dict_merge(c1, 256)` FROM (SELECT `srfuzz_mut_45`.`t2`.`c1`, `srfuzz_mut_45`.`t2`.`c2` FROM `srfuzz_mut_45`.`t2` EXCEPT SELECT `srfuzz_mut_45`.`t2`.`c1`, `srfuzz_mut_45`.`t2`.`c2` FROM `srfuzz_mut_45`.`t2`) `t2` GROUP BY `t2`.`c1` ORDER BY `t2`.`c1` ASC  LIMIT 10;