SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` WHERE `srfuzz_mut_1140`.`unique_tbl`.`a` = 1;
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` WHERE `srfuzz_mut_1140`.`unique_tbl`.`a` = 1 LIMIT 100;
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` WHERE `srfuzz_mut_1140`.`unique_tbl`.`a` = 1 ORDER BY `srfuzz_mut_1140`.`unique_tbl`.`a` DESC;
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` WHERE `srfuzz_mut_1140`.`unique_tbl`.`a` = NULL;
SELECT `unique_tbl`.`a`, `unique_tbl`.`b` FROM (SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` UNION SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl`) `unique_tbl` WHERE `unique_tbl`.`a` = 1;
SELECT `unique_tbl`.`a`, `unique_tbl`.`b` FROM (SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` UNION ALL SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl`) `unique_tbl` WHERE `unique_tbl`.`a` = 1;
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` WHERE `srfuzz_mut_1140`.`unique_tbl`.`a` = 1.0E308;
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` WHERE `srfuzz_mut_1140`.`unique_tbl`.`a` = 1;
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` WHERE 1 = 1;
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` WHERE `srfuzz_mut_1140`.`unique_tbl`.`a` = 1 LIMIT 1, 1;
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` WHERE `srfuzz_mut_1140`.`unique_tbl`.`a` = 1;
SELECT `unique_tbl`.`a`, `unique_tbl`.`b` FROM (SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` EXCEPT SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl`) `unique_tbl` WHERE `unique_tbl`.`a` = 1;
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` WHERE CAST((CAST((CAST((`srfuzz_mut_1140`.`unique_tbl`.`a` = 1) AS JSON)) AS VARCHAR(65533))) AS INT);
SELECT `unique_tbl`.`a`, `unique_tbl`.`b` FROM (SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` INTERSECT SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl`) `unique_tbl` WHERE `unique_tbl`.`a` = 1;
SELECT `unique_tbl`.`a`, `unique_tbl`.`b` FROM (SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl`) `unique_tbl` WHERE `unique_tbl`.`a` = 1;
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` WHERE `srfuzz_mut_1140`.`unique_tbl`.`a` = '1970-01-01';
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` WHERE `srfuzz_mut_1140`.`unique_tbl`.`a` = 1;
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` WHERE `srfuzz_mut_1140`.`unique_tbl`.`a` = 1;
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` WHERE `srfuzz_mut_1140`.`unique_tbl`.`a` = 1 LIMIT 1, 2;
SELECT `unique_tbl`.`a`, `unique_tbl`.`b` FROM (SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` UNION SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl`) `unique_tbl` WHERE `unique_tbl`.`a` = 1;
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` WHERE `srfuzz_mut_1140`.`unique_tbl`.`a` = `srfuzz_mut_1140`.`unique_tbl`.`a`;
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` WHERE `srfuzz_mut_1140`.`unique_tbl`.`a` = 1;
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` WHERE `srfuzz_mut_1140`.`unique_tbl`.`a` = 1;
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl`;
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` WHERE `srfuzz_mut_1140`.`unique_tbl`.`a` = '';
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl`;
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` WHERE `srfuzz_mut_1140`.`unique_tbl`.`a` = NULL;
SELECT `unique_tbl`.`a`, `unique_tbl`.`b` FROM (SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` INTERSECT SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl`) `unique_tbl` WHERE `unique_tbl`.`a` = 1;
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` WHERE `srfuzz_mut_1140`.`unique_tbl`.`a` = 1;
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` WHERE `srfuzz_mut_1140`.`unique_tbl`.`a` = 1;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl`) SELECT `unique_tbl`.`a`, `unique_tbl`.`b` FROM `srfuzz_n1` AS unique_tbl WHERE `unique_tbl`.`a` = 1;
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` WHERE 1 = 1;
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` WHERE `srfuzz_mut_1140`.`unique_tbl`.`a` = 1 LIMIT 7, 2;
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl`;
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl`;
SELECT `srfuzz_mut_1140`.`unique_tbl`.`a`, `srfuzz_mut_1140`.`unique_tbl`.`b` FROM `srfuzz_mut_1140`.`unique_tbl` WHERE 1 = 1;