SELECT json_remove('{"a": 1, "b": 2, "c": 3}', '$.a') AS `remove_single_key`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', '$.a', '$.c') AS `remove_multiple_keys`;
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', '$.b[1]') AS `remove_array_element`;
SELECT json_remove('{"a": {"x": 1, "y": 2}, "b": 3}', '$.a.x') AS `remove_nested_key`;
SELECT json_remove('{"level1": {"level2": {"level3": "value"}}}', '$.level1.level2') AS `remove_nested_object`;
SELECT json_remove('{"a": 1, "b": 2}', '$.nonexistent') AS `remove_nonexistent_key`;
SELECT json_remove('{"a": 1, "b": 2}', 'invalid_path') AS `remove_invalid_path`;
SELECT json_remove('{"a": 1, "b": 2}', '$.a', '$.nonexistent', '$.b') AS `remove_mixed_paths`;
SELECT json_remove('{}', '$.a') AS `remove_from_empty_object`;
SELECT json_remove('{"a": 1}', '$.a') AS `remove_all_keys`;
SELECT json_remove('{"a": []}', '$.a') AS `remove_empty_array`;
SELECT json_remove('{"str": "hello", "num": 42, "bool": true, "null": null}', '$.str', '$.bool') AS `remove_various_types`;
SELECT json_remove('{"users": [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}], "count": 2}', '$.count') AS `remove_from_complex`;
SELECT json_length(json_remove('{"a": 1, "b": 2, "c": 3}', '$.b')) AS `length_after_remove`;
SELECT json_keys(json_remove('{"x": 1, "y": 2, "z": 3}', '$.y')) AS `keys_after_remove`;
SELECT json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a') AS `exists_after_remove`;
SELECT json_remove(parse_json('{"temp": "data", "keep": "this"}'), '$.temp') AS `parsed_and_removed`;
SELECT json_remove('{"a": 1}', '$') AS `root_path`;
SELECT json_remove('{"a": 1}', '$.') AS `dot_path`;
SELECT json_remove('{"a": {"b": {"c": {"d": {"e": "deep"}}}}}', '$.a.b.c.d') AS `remove_deep_nested`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[0]') AS `remove_first_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[4]') AS `remove_last_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[2]') AS `remove_middle_element`;
SELECT json_remove('{"key with spaces": "value", "normal": "data"}', '$."key with spaces"') AS `remove_special_key`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', '{"a": 1, "b": 2, "c": 3}') AS `remove_single_key`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', 1.0E308) AS `remove_single_key`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', repeat('x', 65536)) AS `remove_single_key`;
SELECT json_remove('$.a', '$.a') AS `remove_single_key`;
SELECT json_remove('0', '$.a') AS `remove_single_key`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', '$.a') AS `remove_single_key`;
SELECT json_remove(json_remove('{"a": 1, "b": 2, "c": 3}', '$.a'), '$.a') AS `remove_single_key`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', '$.a') AS `remove_single_key` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', 1) AS `remove_single_key`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', TRUE) AS `remove_single_key`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', '') AS `remove_single_key`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', '{"a": 1, "b": 2, "c": 3}') AS `remove_single_key`;
SELECT json_remove('$.a', '$.a') AS `remove_single_key`;
SELECT json_remove('$.a', '$.a') AS `remove_single_key`;
SELECT json_remove('$.a', '$.a') AS `remove_single_key`;
SELECT json_remove(-1.0E308, '$.a') AS `remove_single_key`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', '$.a') AS `remove_single_key`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', json_remove('{"a": 1, "b": 2, "c": 3}', '$.a')) AS `remove_single_key`;
SELECT json_remove('$.a', '$.a') AS `remove_single_key`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', 0) AS `remove_single_key`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', '$.a') AS `remove_single_key`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', '{"a": 1, "b": 2, "c": 3}') AS `remove_single_key`;
SELECT json_remove('$.a', '$.a') AS `remove_single_key`;
SELECT json_remove(json_remove('{"a": 1, "b": 2, "c": 3}', '$.a'), '$.a') AS `remove_single_key`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', '{"a": {"x": 1, "y": 2}, "b": 3}') AS `remove_single_key`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', '$.a', '$.c') AS `remove_multiple_keys` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', '$.a', 1.0E308) AS `remove_multiple_keys`;
SELECT json_remove(170141183460469231731687303715884105727, '$.a', '$.c') AS `remove_multiple_keys`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', '$.a', 2147483647) AS `remove_multiple_keys`;
SELECT json_remove(json_remove('{"key with spaces": "value", "normal": "data"}', '$."key with spaces"'), '$.a', '$.c') AS `remove_multiple_keys`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', '$.a', '{"x": 1, "y": 2, "z": 3}') AS `remove_multiple_keys`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', '$.a', CAST(NULL AS JSON)) AS `remove_multiple_keys`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', '$.a', '$.c') AS `remove_multiple_keys`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', '$.a', '$.a') AS `remove_multiple_keys`;
SELECT json_remove(json_length(CAST('{"a": 1, "b": 2, "c": 3}' AS JSON)), '$.a', '$.c') AS `remove_multiple_keys`;
SELECT json_remove(0.0, '$.a', '$.c') AS `remove_multiple_keys`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', '$.a', json_remove('{"a": 1, "b": 2, "c": 3}', '$.a', '$.c')) AS `remove_multiple_keys`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', '{"a": 1, "b": 2, "c": 3}', '$.c') AS `remove_multiple_keys`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', '$.a', '$.a') AS `remove_multiple_keys`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', '$.a', '$.c') AS `remove_multiple_keys` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', json_length(CAST('$.a' AS JSON)), '$.c') AS `remove_multiple_keys`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', 0, '$.c') AS `remove_multiple_keys`;
SELECT json_remove(json_length(CAST('{"a": 1, "b": 2, "c": 3}' AS JSON)), '$.a', '$.c') AS `remove_multiple_keys`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', -1, '$.c') AS `remove_multiple_keys`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', '$.a', '$.c') AS `remove_multiple_keys` LIMIT 100;
SELECT json_remove(-1, '$.a', '$.c') AS `remove_multiple_keys`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', '$.c', '$.c') AS `remove_multiple_keys`;
SELECT json_remove('{"a": 1, "b": 2, "c": 3}', '$.a', '$.c') AS `remove_multiple_keys` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('$."key with spaces"', '$.a', '$.c') AS `remove_multiple_keys`;
SELECT json_remove(json_remove('{"a": 1, "b": 2, "c": 3}', '$.a', '$.c'), '$.a', '$.c') AS `remove_multiple_keys`;
SELECT json_remove(-1, '$.a', '$.c') AS `remove_multiple_keys`;
SELECT json_remove(1.0E308, '$.b[1]') AS `remove_array_element`;
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', 1) AS `remove_array_element`;
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', -2147483648) AS `remove_array_element`;
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', '$.b[1]') AS `remove_array_element`;
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', json_remove('{"a": 1, "b": [10, 20, 30]}', '$.b[1]')) AS `remove_array_element`;
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', 0) AS `remove_array_element`;
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', '$.b[1]') AS `remove_array_element` LIMIT 1;
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', '$.b[1]') AS `remove_array_element`;
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', '\\') AS `remove_array_element`;
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', '0000-00-00') AS `remove_array_element`;
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', json_remove('{"a": 1, "b": [10, 20, 30]}', '$.b[1]')) AS `remove_array_element`;
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', '$.b[1]') AS `remove_array_element`;
SELECT json_remove('\\', '$.b[1]') AS `remove_array_element`;
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', TRUE) AS `remove_array_element`;
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', json_remove('{"a": 1}', '$.')) AS `remove_array_element`;
SELECT json_remove(-2147483648, '$.b[1]') AS `remove_array_element`;
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', '\\') AS `remove_array_element`;
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', '{"a": 1, "b": [10, 20, 30]}') AS `remove_array_element`;
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', '$.b[1]') AS `remove_array_element` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', '{"a": 1, "b": [10, 20, 30]}') AS `remove_array_element`;
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', '{"a": 1, "b": [10, 20, 30]}') AS `remove_array_element`;
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', '$.b[1]') AS `remove_array_element` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', CAST((CAST('$.b[1]' AS DECIMAL128(27,9))) AS BIGINT)) AS `remove_array_element`;
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', '$.b[1]') AS `remove_array_element`;
SELECT json_remove('$.b[1]', '$.b[1]') AS `remove_array_element`;
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', json_remove('{"a": 1, "b": [10, 20, 30]}', '$.b[1]')) AS `remove_array_element`;
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', json_remove('{"a": 1, "b": [10, 20, 30]}', '$.b[1]')) AS `remove_array_element`;
SELECT CAST((json_remove('{"a": 1, "b": [10, 20, 30]}', '$.b[1]')) AS JSON)->'$' AS `remove_array_element`;
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', '{"a": 1, "b": [10, 20, 30]}') AS `remove_array_element`;
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', '$.b[1]') AS `remove_array_element` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove(9223372036854775807, '$.b[1]') AS `remove_array_element`;
SELECT json_remove('{"a": 1, "b": [10, 20, 30]}', '{"a": 1, "b": [10, 20, 30]}') AS `remove_array_element`;
SELECT json_remove('{"a": {"x": 1, "y": 2}, "b": 3}', 0) AS `remove_nested_key`;
SELECT json_remove('{"a": {"x": 1, "y": 2}, "b": 3}', '$.a.x') AS `remove_nested_key`;
SELECT json_remove('{"a": {"x": 1, "y": 2}, "b": 3}', '$.a.x') AS `remove_nested_key` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove(json_remove('{"a": {"x": 1, "y": 2}, "b": 3}', '$.a.x'), '$.a.x') AS `remove_nested_key`;
SELECT json_remove('{"a": {"x": 1, "y": 2}, "b": 3}', NULL) AS `remove_nested_key`;
SELECT json_remove('{"a": {"x": 1, "y": 2}, "b": 3}', '$.a.x') AS `remove_nested_key`;
SELECT json_remove('{"a": {"x": 1, "y": 2}, "b": 3}', -1.0E308) AS `remove_nested_key`;
SELECT json_remove('{"a": {"x": 1, "y": 2}, "b": 3}', '$.a.x') AS `remove_nested_key`;
SELECT json_remove(json_remove('{"a": {"x": 1, "y": 2}, "b": 3}', '$.a.x'), '$.a.x') AS `remove_nested_key`;
SELECT json_remove(json_remove('{"a": {"x": 1, "y": 2}, "b": 3}', '$.a.x'), '$.a.x') AS `remove_nested_key`;
SELECT json_remove(CAST('{"a": {"x": 1, "y": 2}, "b": 3}' AS JSON)->'$', '$.a.x') AS `remove_nested_key`;
SELECT json_remove('{"a": {"x": 1, "y": 2}, "b": 3}', '') AS `remove_nested_key`;
SELECT json_remove('{"a": {"x": 1, "y": 2}, "b": 3}', '$.a.x') AS `remove_nested_key`;
SELECT json_remove('{"a": {"x": 1, "y": 2}, "b": 3}', '$.a.x') AS `remove_nested_key` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('{"a": {"x": 1, "y": 2}, "b": 3}', json_remove('{"a": {"x": 1, "y": 2}, "b": 3}', '$.a.x')) AS `remove_nested_key`;
SELECT json_remove('{"a": {"x": 1, "y": 2}, "b": 3}', '$.a.x') AS `remove_nested_key`;
SELECT json_remove('{"a": {"x": 1, "y": 2}, "b": 3}', '') AS `remove_nested_key`;
SELECT json_remove('{"a": {"x": 1, "y": 2}, "b": 3}', repeat('x', 65536)) AS `remove_nested_key`;
SELECT count(json_remove('{"a": {"x": 1, "y": 2}, "b": 3}', '$.a.x')) OVER () AS `remove_nested_key`;
SELECT json_remove('{"a": {"x": 1, "y": 2}, "b": 3}', '$.a') AS `remove_nested_key`;
SELECT json_remove('{"a": {"x": 1, "y": 2}, "b": 3}', '{"a": {"x": 1, "y": 2}, "b": 3}') AS `remove_nested_key`;
SELECT json_remove('{"a": {"x": 1, "y": 2}, "b": 3}', '$.a.x') AS `remove_nested_key`;
SELECT json_remove(CAST(NULL AS JSON), '$.a.x') AS `remove_nested_key`;
SELECT json_remove('{"level1": {"level2": {"level3": "value"}}}', '') AS `remove_nested_object`;
SELECT json_remove('{"level1": {"level2": {"level3": "value"}}}', '$.str') AS `remove_nested_object`;
SELECT json_remove('{"level1": {"level2": {"level3": "value"}}}', '{"level1": {"level2": {"level3": "value"}}}') AS `remove_nested_object`;
SELECT json_remove('{"level1": {"level2": {"level3": "value"}}}', '$.level1.level2') AS `remove_nested_object`;
SELECT json_remove('{"level1": {"level2": {"level3": "value"}}}', '$.level1.level2') AS `remove_nested_object` LIMIT 0;
SELECT json_remove('{"level1": {"level2": {"level3": "value"}}}', -9223372036854775808) AS `remove_nested_object`;
SELECT json_remove('{"level1": {"level2": {"level3": "value"}}}', json_remove('{"level1": {"level2": {"level3": "value"}}}', '$.level1.level2')) AS `remove_nested_object`;
SELECT json_remove('{"level1": {"level2": {"level3": "value"}}}', 9223372036854775807) AS `remove_nested_object`;
SELECT json_remove('{"level1": {"level2": {"level3": "value"}}}', '$.a') AS `remove_nested_object`;
SELECT json_remove('{"level1": {"level2": {"level3": "value"}}}', '0') AS `remove_nested_object`;
SELECT json_remove(json_length(CAST('{"level1": {"level2": {"level3": "value"}}}' AS JSON)), '$.level1.level2') AS `remove_nested_object`;
SELECT json_remove(json_remove('{"level1": {"level2": {"level3": "value"}}}', '$.level1.level2'), '$.level1.level2') AS `remove_nested_object`;
SELECT json_remove('{"level1": {"level2": {"level3": "value"}}}', json_remove('{"level1": {"level2": {"level3": "value"}}}', '$.level1.level2')) AS `remove_nested_object`;
SELECT json_remove(TRUE, '$.level1.level2') AS `remove_nested_object`;
SELECT json_remove('{"level1": {"level2": {"level3": "value"}}}', 0.0) AS `remove_nested_object`;
SELECT json_remove('{"level1": {"level2": {"level3": "value"}}}', '1970-01-01') AS `remove_nested_object`;
SELECT json_remove('{"level1": {"level2": {"level3": "value"}}}', '$.level1.level2') AS `remove_nested_object` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('{"level1": {"level2": {"level3": "value"}}}', CAST('$.level1.level2' AS VARCHAR(1))) AS `remove_nested_object`;
SELECT json_remove('{"level1": {"level2": {"level3": "value"}}}', CAST(NULL AS JSON)) AS `remove_nested_object`;
SELECT json_remove('{"level1": {"level2": {"level3": "value"}}}', '$.level1.level2') AS `remove_nested_object` LIMIT 1, 5;
SELECT json_remove('{"a": 1, "b": 2}', '$.nonexistent') AS `remove_nonexistent_key`;
SELECT json_remove('{"a": 1, "b": 2}', '$.nonexistent') AS `remove_nonexistent_key` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('{"a": 1, "b": 2}', '%') AS `remove_nonexistent_key`;
SELECT json_remove('{"a": 1, "b": 2}', 0) AS `remove_nonexistent_key`;
SELECT json_remove('{"a": 1, "b": 2}', 0.0) AS `remove_nonexistent_key`;
SELECT json_remove('$.', '$.nonexistent') AS `remove_nonexistent_key`;
SELECT json_remove('{"a": 1, "b": 2}', '$.nonexistent') AS `remove_nonexistent_key` LIMIT 100;
SELECT json_remove('{"a": 1, "b": 2}', '$.nonexistent') AS `remove_nonexistent_key`;
SELECT json_remove(0.0, '$.nonexistent') AS `remove_nonexistent_key`;
SELECT json_remove('{"a": 1, "b": 2}', -1) AS `remove_nonexistent_key`;
SELECT json_remove('{"a": 1, "b": 2}', '$.nonexistent') AS `remove_nonexistent_key`;
SELECT json_remove('$.nonexistent', '$.nonexistent') AS `remove_nonexistent_key`;
SELECT json_remove('{"a": 1, "b": 2}', '$.nonexistent') AS `remove_nonexistent_key` LIMIT 100;
SELECT json_remove('{"a": 1, "b": 2}', 1.0E308) AS `remove_nonexistent_key`;
SELECT json_remove(json_remove('{"a": 1, "b": 2}', '$.nonexistent'), '$.nonexistent') AS `remove_nonexistent_key`;
SELECT json_remove('{"a": 1, "b": 2}', 0) AS `remove_nonexistent_key`;
SELECT json_remove('', '$.nonexistent') AS `remove_nonexistent_key`;
SELECT json_remove('{"a": 1, "b": 2}', '$.nonexistent') AS `remove_nonexistent_key` LIMIT 7, 1;
SELECT json_remove('{"a": 1, "b": 2}', '9999-12-31 23:59:59') AS `remove_nonexistent_key`;
SELECT json_remove('{"a": 1, "b": 2}', 1.0E308) AS `remove_nonexistent_key`;
SELECT json_remove('{"a": 1, "b": 2}', 'invalid_path') AS `remove_invalid_path`;
SELECT json_remove('{"a": 1, "b": 2}', '%') AS `remove_invalid_path`;
SELECT json_remove('{"a": 1, "b": 2}', '1970-01-01') AS `remove_invalid_path`;
SELECT json_remove('{"a": 1, "b": 2}', '{"a": 1, "b": 2}') AS `remove_invalid_path`;
SELECT json_remove('invalid_path', 'invalid_path') AS `remove_invalid_path`;
SELECT json_remove('{"a": 1, "b": 2}', 'invalid_path') AS `remove_invalid_path`;
SELECT json_remove('{"a": 1, "b": 2}', 'invalid_path') AS `remove_invalid_path`;
SELECT json_remove(json_remove('{"a": 1, "b": 2}', 'invalid_path'), 'invalid_path') AS `remove_invalid_path`;
SELECT json_remove('{"a": 1, "b": 2}', -1.0E308) AS `remove_invalid_path`;
SELECT json_remove(-2147483648, 'invalid_path') AS `remove_invalid_path`;
SELECT json_remove(json_remove('{"a": 1, "b": 2}', 'invalid_path'), 'invalid_path') AS `remove_invalid_path`;
SELECT json_remove(-2147483648, 'invalid_path') AS `remove_invalid_path`;
SELECT json_remove(json_remove('{"a": 1, "b": 2}', 'invalid_path'), 'invalid_path') AS `remove_invalid_path`;
SELECT json_remove('{"a": 1, "b": 2}', 'invalid_path') AS `remove_invalid_path` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('{"a": 1, "b": 2}', CAST('invalid_path' AS JSON)->'k') AS `remove_invalid_path`;
SELECT CAST((json_remove('{"a": 1, "b": 2}', 'invalid_path')) AS JSON)->'$.a' AS `remove_invalid_path`;
SELECT json_remove('\\', 'invalid_path') AS `remove_invalid_path`;
SELECT json_remove(json_remove('{"a": 1, "b": 2}', '$.nonexistent'), 'invalid_path') AS `remove_invalid_path`;
SELECT json_remove('{"a": 1, "b": 2}', '%') AS `remove_invalid_path`;
SELECT json_remove('{"a": 1, "b": 2}', 'invalid_path') AS `remove_invalid_path`;
SELECT json_remove('{"a": 1, "b": 2}', 'invalid_path') AS `remove_invalid_path` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('invalid_path', 'invalid_path') AS `remove_invalid_path`;
SELECT json_remove('{"a": 1, "b": 2}', 'invalid_path') AS `remove_invalid_path`;
SELECT json_remove('{"a": 1, "b": 2}', '$.a', '$.nonexistent', -1.0E308) AS `remove_mixed_paths`;
SELECT json_remove('{"a": 1, "b": 2}', '$.a', '$.nonexistent', '$.b') AS `remove_mixed_paths`;
SELECT count(json_remove('{"a": 1, "b": 2}', '$.a', '$.nonexistent', '$.b')) OVER () AS `remove_mixed_paths`;
SELECT json_remove('$.a', '$.a', '$.nonexistent', '$.b') AS `remove_mixed_paths`;
SELECT json_remove(CAST('{"a": 1, "b": 2}' AS SMALLINT), '$.a', '$.nonexistent', '$.b') AS `remove_mixed_paths`;
SELECT json_remove('{"a": 1, "b": 2}', '$.a', '$.a', '$.b') AS `remove_mixed_paths`;
SELECT json_remove('{"a": 1, "b": 2}', '$.a', '$.nonexistent', '{"a": []}') AS `remove_mixed_paths`;
SELECT json_remove('{"a": 1, "b": 2}', json_remove('{"a": 1, "b": 2}', '$.a', '$.nonexistent', '$.b'), '$.nonexistent', '$.b') AS `remove_mixed_paths`;
SELECT json_remove('{"a": 1, "b": 2}', '$.a', '$.b', '$.b') AS `remove_mixed_paths`;
SELECT json_remove('{"a": 1, "b": 2}', 0.0, '$.nonexistent', '$.b') AS `remove_mixed_paths`;
SELECT json_remove('{"a": 1, "b": 2}', '$.b', '$.nonexistent', '$.b') AS `remove_mixed_paths`;
SELECT json_remove('{"a": 1, "b": 2}', '$.a', get_json_string(CAST('$.nonexistent' AS JSON), '$.a'), '$.b') AS `remove_mixed_paths`;
SELECT json_remove('{"a": 1, "b": 2}', '$.a', '$.nonexistent', '{"a": 1, "b": 2}') AS `remove_mixed_paths`;
SELECT json_remove('{"a": 1, "b": 2}', '$.a', '$.nonexistent', '$.b') AS `remove_mixed_paths`;
SELECT json_remove('{"a": 1, "b": 2}', '$.a', json_remove('{"a": 1, "b": 2}', '$.a', '$.nonexistent', '$.b'), '$.b') AS `remove_mixed_paths`;
SELECT json_remove('{"a": 1, "b": 2}', '$.b', '$.nonexistent', '$.b') AS `remove_mixed_paths`;
SELECT json_remove('{"a": 1, "b": 2}', '$.a', '$.count', '$.b') AS `remove_mixed_paths`;
SELECT json_remove('{"a": 1, "b": 2}', '$.a', '$.nonexistent', '$.count') AS `remove_mixed_paths`;
SELECT json_remove(CAST(NULL AS JSON), '$.a', '$.nonexistent', '$.b') AS `remove_mixed_paths`;
SELECT json_remove('{"a": 1, "b": 2}', '$.a', '$.nonexistent', '$.b') AS `remove_mixed_paths` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('{"a": 1, "b": 2}', '$.a', '$.nonexistent', CAST('$.b' AS JSON)->'$') AS `remove_mixed_paths`;
SELECT json_remove('{"a": 1, "b": 2}', '$.a', '$.a', '$.b') AS `remove_mixed_paths`;
SELECT json_remove('{"a": 1, "b": 2}', '$.a', '$.nonexistent', '$.b') AS `remove_mixed_paths` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('{"a": 1, "b": 2}', '$.a', '$.nonexistent', '9999-12-31 23:59:59') AS `remove_mixed_paths`;
SELECT json_remove('{"a": 1, "b": 2}', '$.a', '$.nonexistent', CAST((CAST((CAST('$.b' AS VARCHAR(65533))) AS CHAR(1))) AS TIME)) AS `remove_mixed_paths`;
SELECT json_remove('{"a": 1, "b": 2}', '$.a', '$.nonexistent', '$.b') AS `remove_mixed_paths` LIMIT 7, 100;
SELECT json_remove(json_remove('{}', '$.a'), '$.a') AS `remove_from_empty_object`;
SELECT json_remove('{}', '$.') AS `remove_from_empty_object`;
SELECT json_remove('$.a', '$.a') AS `remove_from_empty_object`;
SELECT json_remove('{}', '$.a') AS `remove_from_empty_object`;
SELECT json_remove('{}', '1970-01-01') AS `remove_from_empty_object`;
SELECT json_remove(json_remove('{}', '$.a'), '$.a') AS `remove_from_empty_object`;
SELECT json_remove(json_remove('{}', '$.a'), '$.a') AS `remove_from_empty_object`;
SELECT json_remove('{}', 0.0) AS `remove_from_empty_object`;
SELECT json_remove('{}', '{}') AS `remove_from_empty_object`;
SELECT json_remove('{"a": 1, "b": 2}', '$.a') AS `remove_from_empty_object`;
SELECT json_remove('{}', '$.a') AS `remove_from_empty_object` LIMIT 7, 2;
SELECT CAST((json_remove('{}', '$.a')) AS JSON)->'$.a' AS `remove_from_empty_object`;
SELECT json_remove('{}', '$.c') AS `remove_from_empty_object`;
SELECT json_remove(json_remove('{}', '$.a'), '$.a') AS `remove_from_empty_object`;
SELECT json_remove('{}', '$.a') AS `remove_from_empty_object`;
SELECT json_remove('1970-01-01', '$.a') AS `remove_from_empty_object`;
SELECT json_remove('{}', json_remove('{}', '$.a')) AS `remove_from_empty_object`;
SELECT json_remove(json_remove('{}', '$.a'), '$.a') AS `remove_from_empty_object`;
SELECT json_remove('{}', '') AS `remove_from_empty_object`;
SELECT json_remove('{"a": 1}', '{"a": 1}') AS `remove_all_keys`;
SELECT json_remove('{"a": 1}', '$.a') AS `remove_all_keys`;
SELECT json_remove('{"a": 1}', '$.a') AS `remove_all_keys`;
SELECT json_remove('{"a": 1}', 9223372036854775807) AS `remove_all_keys`;
SELECT json_remove('$.a', '$.a') AS `remove_all_keys`;
SELECT json_remove('{"a": 1}', 0.0) AS `remove_all_keys`;
SELECT json_remove('{"a": 1}', '{"a": 1}') AS `remove_all_keys`;
SELECT json_remove('{"a": 1}', -1) AS `remove_all_keys`;
SELECT json_remove('{"a": 1}', '$.a') AS `remove_all_keys` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('$.a', '$.a') AS `remove_all_keys`;
SELECT json_remove('{"a": 1}', FALSE) AS `remove_all_keys`;
SELECT json_remove('{"a": 1}', '{"a": 1}') AS `remove_all_keys`;
SELECT json_remove(CAST('{"a": 1}' AS JSON)->'k', '$.a') AS `remove_all_keys`;
SELECT json_remove(json_remove('{"a": 1}', '$.a'), '$.a') AS `remove_all_keys`;
SELECT json_remove(json_remove('{"a": 1}', '$.a'), '$.a') AS `remove_all_keys`;
SELECT json_remove('{"a": 1}', '') AS `remove_all_keys`;
SELECT json_remove('{"a": 1}', '$.a') AS `remove_all_keys`;
SELECT json_remove(CAST('{"a": 1}' AS INT), '$.a') AS `remove_all_keys`;
SELECT json_remove('{"a": 1}', '{"a": 1}') AS `remove_all_keys`;
SELECT json_remove('{"a": 1}', -1) AS `remove_all_keys`;
SELECT json_remove('{"a": 1}', '$.a') AS `remove_all_keys` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('{"a": 1}', json_remove('{"a": 1}', '$.a')) AS `remove_all_keys`;
SELECT json_remove(json_remove('{"a": 1}', '$.a'), '$.a') AS `remove_all_keys`;
SELECT json_remove('0000-00-00', '$.a') AS `remove_all_keys`;
SELECT json_remove('{"a": 1}', '{"a": 1}') AS `remove_all_keys`;
SELECT json_remove('{"a": 1}', '') AS `remove_all_keys`;
SELECT json_remove(json_remove('{"a": 1}', '$.a'), '$.a') AS `remove_all_keys`;
SELECT json_remove('$.a', '$.a') AS `remove_all_keys`;
SELECT json_remove('{"a": 1}', '{"a": 1}') AS `remove_all_keys`;
SELECT json_remove(TRUE, '$.a') AS `remove_empty_array`;
SELECT json_length(CAST((json_remove('{"a": []}', '$.a')) AS JSON)) AS `remove_empty_array`;
SELECT json_remove('$.a', '$.a') AS `remove_empty_array`;
SELECT json_remove('{"a": []}', '$.a') AS `remove_empty_array` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove(json_remove('{"a": []}', '$.a'), '$.a') AS `remove_empty_array`;
SELECT json_remove('$.a', '$.a') AS `remove_empty_array`;
SELECT json_remove('{"a": []}', 0.0) AS `remove_empty_array`;
SELECT json_remove(json_remove('{"a": []}', '$.a'), '$.a') AS `remove_empty_array`;
SELECT json_remove('{"a": []}', '$.a') AS `remove_empty_array` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove(-2147483648, '$.a') AS `remove_empty_array`;
SELECT json_remove(json_remove('{"a": 1, "b": 2}', '$.nonexistent'), '$.a') AS `remove_empty_array`;
SELECT json_remove('{"a": []}', CAST('$.a' AS JSON)->'$.a') AS `remove_empty_array`;
SELECT json_remove(json_remove('{"a": []}', '$.a'), '$.a') AS `remove_empty_array`;
SELECT json_remove(json_remove('{"a": []}', '$.a'), '$.a') AS `remove_empty_array`;
SELECT json_remove(json_remove('{"a": []}', '$.a'), '$.a') AS `remove_empty_array`;
SELECT json_remove('{"a": []}', '$.a') AS `remove_empty_array` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('{"a": []}', '$.a') AS `remove_empty_array` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('{"a": []}', json_remove('{"a": []}', '$.a')) AS `remove_empty_array`;
SELECT json_remove('%', '$.a') AS `remove_empty_array`;
SELECT json_remove('{"a": []}', '$.a') AS `remove_empty_array`;
SELECT json_remove(CAST('{"a": []}' AS FLOAT), '$.a') AS `remove_empty_array`;
SELECT json_remove('{"a": []}', '{"a": []}') AS `remove_empty_array`;
SELECT json_remove(json_remove('{}', '$.a'), '$.a') AS `remove_empty_array`;
SELECT json_remove('{"a": []}', '$.a') AS `remove_empty_array` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('{"a": []}', CAST(NULL AS JSON)) AS `remove_empty_array`;
SELECT json_remove('{"a": []}', '{"a": []}') AS `remove_empty_array`;
SELECT json_remove('{"a": []}', repeat('x', 65536)) AS `remove_empty_array`;
SELECT json_remove('{"str": "hello", "num": 42, "bool": true, "null": null}', '$.str', -1) AS `remove_various_types`;
SELECT json_remove(json_remove('{"str": "hello", "num": 42, "bool": true, "null": null}', '$.str', '$.bool'), '$.str', '$.bool') AS `remove_various_types`;
SELECT json_remove(-1.0E308, '$.str', '$.bool') AS `remove_various_types`;
SELECT json_remove('{"str": "hello", "num": 42, "bool": true, "null": null}', '1970-01-01', '$.bool') AS `remove_various_types`;
SELECT json_remove('%', '$.str', '$.bool') AS `remove_various_types`;
SELECT json_remove('{"str": "hello", "num": 42, "bool": true, "null": null}', json_remove('{"a": []}', '$.a'), '$.bool') AS `remove_various_types`;
SELECT json_remove(repeat('x', 65536), '$.str', '$.bool') AS `remove_various_types`;
SELECT json_remove('{"str": "hello", "num": 42, "bool": true, "null": null}', json_remove('{"str": "hello", "num": 42, "bool": true, "null": null}', '$.str', '$.bool'), '$.bool') AS `remove_various_types`;
SELECT json_remove('{"str": "hello", "num": 42, "bool": true, "null": null}', '$.str', '$.bool') AS `remove_various_types` LIMIT 7, 5;
SELECT json_remove(FALSE, '$.str', '$.bool') AS `remove_various_types`;
SELECT json_remove(FALSE, '$.str', '$.bool') AS `remove_various_types`;
SELECT json_remove('{"str": "hello", "num": 42, "bool": true, "null": null}', '$.str', '{"str": "hello", "num": 42, "bool": true, "null": null}') AS `remove_various_types`;
SELECT json_remove('{"str": "hello", "num": 42, "bool": true, "null": null}', '$.str', '$.bool') AS `remove_various_types`;
SELECT json_remove('{"str": "hello", "num": 42, "bool": true, "null": null}', '$.str', CAST(NULL AS JSON)) AS `remove_various_types`;
SELECT json_remove('{"str": "hello", "num": 42, "bool": true, "null": null}', '$.str', '$.bool') AS `remove_various_types` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('{"str": "hello", "num": 42, "bool": true, "null": null}', '$.str', '$.bool') AS `remove_various_types` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('{"str": "hello", "num": 42, "bool": true, "null": null}', '$.str', '9999-12-31 23:59:59') AS `remove_various_types`;
SELECT json_remove('$.str', '$.str', '$.bool') AS `remove_various_types`;
SELECT json_remove('{"str": "hello", "num": 42, "bool": true, "null": null}', '$.str', '$.bool') AS `remove_various_types` LIMIT 7, 1;
SELECT json_remove('$.bool', '$.str', '$.bool') AS `remove_various_types`;
SELECT json_remove('{"str": "hello", "num": 42, "bool": true, "null": null}', '$.str', '$.bool') AS `remove_various_types` LIMIT 0;
SELECT get_json_string(CAST((json_remove('{"str": "hello", "num": 42, "bool": true, "null": null}', '$.str', '$.bool')) AS JSON), '$.a') AS `remove_various_types`;
SELECT json_remove('{"str": "hello", "num": 42, "bool": true, "null": null}', '$.str', CAST(NULL AS JSON)) AS `remove_various_types`;
SELECT json_remove('{"str": "hello", "num": 42, "bool": true, "null": null}', '0000-00-00', '$.bool') AS `remove_various_types`;
SELECT json_remove('{"str": "hello", "num": 42, "bool": true, "null": null}', '$.str', '$.bool') AS `remove_various_types`;
SELECT json_remove('{"users": [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}], "count": 2}', 1.0E308) AS `remove_from_complex`;
SELECT json_remove('{"users": [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}], "count": 2}', NULL) AS `remove_from_complex`;
SELECT json_remove(json_remove('{}', '$.a'), '$.count') AS `remove_from_complex`;
SELECT json_remove('{"users": [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}], "count": 2}', '1970-01-01') AS `remove_from_complex`;
SELECT json_remove('{"users": [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}], "count": 2}', '%') AS `remove_from_complex`;
SELECT json_remove('{"users": [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}], "count": 2}', '$.count') AS `remove_from_complex`;
SELECT json_remove('{"users": [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}], "count": 2}', '%') AS `remove_from_complex`;
SELECT json_remove('{"users": [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}], "count": 2}', '$.count') AS `remove_from_complex`;
SELECT json_remove('$.count', '$.count') AS `remove_from_complex`;
SELECT json_remove('{"users": [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}], "count": 2}', json_remove('{"users": [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}], "count": 2}', '$.count')) AS `remove_from_complex`;
SELECT json_remove('{"users": [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}], "count": 2}', '$.count') AS `remove_from_complex`;
SELECT json_remove('$.count', '$.count') AS `remove_from_complex`;
SELECT json_remove(0.0, '$.count') AS `remove_from_complex`;
SELECT json_remove('{"users": [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}], "count": 2}', '$.level1.level2') AS `remove_from_complex`;
SELECT json_remove('{"users": [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}], "count": 2}', '1970-01-01') AS `remove_from_complex`;
SELECT json_remove('{"a": 1, "b": 2}', '$.count') AS `remove_from_complex`;
SELECT json_remove(-1, '$.count') AS `remove_from_complex`;
SELECT json_remove('0', '$.count') AS `remove_from_complex`;
SELECT json_remove('{"users": [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}], "count": 2}', '{"users": [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}], "count": 2}') AS `remove_from_complex`;
SELECT json_remove('{"users": [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}], "count": 2}', json_remove('{"users": [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}], "count": 2}', '$.count')) AS `remove_from_complex`;
SELECT json_remove(json_remove('{"users": [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}], "count": 2}', '$.count'), '$.count') AS `remove_from_complex`;
SELECT json_remove('{"users": [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}], "count": 2}', '$.count') AS `remove_from_complex`;
SELECT json_remove('{"users": [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}], "count": 2}', FALSE) AS `remove_from_complex`;
SELECT json_remove('{"users": [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}], "count": 2}', CAST((CAST('$.count' AS VARCHAR(1))) AS JSON)) AS `remove_from_complex`;
SELECT json_remove(0.0, '$.count') AS `remove_from_complex`;
SELECT json_remove('{"users": [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}], "count": 2}', json_remove('{"a": []}', '$.a')) AS `remove_from_complex`;
SELECT json_remove('{"users": [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}], "count": 2}', '') AS `remove_from_complex`;
SELECT json_length(json_remove('{"a": 1, "b": 2, "c": 3}', '$.b')) AS `length_after_remove` LIMIT 1;
SELECT DISTINCT json_length(json_remove('{"a": 1, "b": 2, "c": 3}', '$.b')) AS `length_after_remove`;
SELECT json_length(json_remove('{"a": 1, "b": 2, "c": 3}', '$.b')) AS `length_after_remove`;
SELECT json_length(json_remove('{"a": 1, "b": 2, "c": 3}', '$.b')) AS `length_after_remove` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_length(json_remove('{"a": 1, "b": 2, "c": 3}', '$.b')) AS `length_after_remove`;
SELECT json_length(json_length(json_remove('{"a": 1, "b": 2, "c": 3}', '$.b'))) AS `length_after_remove`;
SELECT json_length(truncate('{"a": 1, "b": 2, "c": 3}', '$.b')) AS `length_after_remove`;
SELECT DISTINCT json_length(json_remove('{"a": 1, "b": 2, "c": 3}', '$.b')) AS `length_after_remove`;
SELECT json_length(json_remove('{"a": 1, "b": 2, "c": 3}', '$.b')) AS `length_after_remove` ORDER BY json_length(json_remove('{"a": 1, "b": 2, "c": 3}', '$.b')) DESC NULLS FIRST;
SELECT json_length(json_remove('{"str": "hello", "num": 42, "bool": true, "null": null}', '$.b')) AS `length_after_remove`;
SELECT json_length(json_remove(json_remove('{"a": 1, "b": 2, "c": 3}', '$.b'), '$.b')) AS `length_after_remove`;
SELECT DISTINCT json_length(json_remove('{"a": 1, "b": 2, "c": 3}', '$.b')) AS `length_after_remove`;
SELECT json_length(json_remove(json_query(CAST('{"a": 1, "b": 2, "c": 3}' AS JSON), '$.a'), '$.b')) AS `length_after_remove`;
SELECT json_length(json_remove(170141183460469231731687303715884105727, '$.b')) AS `length_after_remove`;
SELECT json_length(json_remove(1.0E308, '$.b')) AS `length_after_remove`;
SELECT json_length(json_remove(json_length(json_remove('{"a": 1, "b": 2, "c": 3}', '$.b')), '$.b')) AS `length_after_remove`;
SELECT json_length(json_remove('{"a": 1, "b": 2, "c": 3}', '$.b')) AS `length_after_remove` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_length(json_remove('{"a": 1, "b": 2, "c": 3}', json_length(json_remove('{"a": 1, "b": 2, "c": 3}', '$.b')))) AS `length_after_remove`;
SELECT json_length(json_remove('{"a": 1, "b": 2, "c": 3}', '$.c')) AS `length_after_remove`;
SELECT json_length(json_remove('{"a": 1, "b": 2, "c": 3}', '$')) AS `length_after_remove`;
SELECT json_length(json_remove('{"a": 1, "b": 2, "c": 3}', json_length(json_remove('{"a": 1, "b": 2, "c": 3}', '$.b')))) AS `length_after_remove`;
SELECT json_length(truncate('{"a": 1, "b": 2, "c": 3}', '$.b')) AS `length_after_remove`;
SELECT json_length(json_remove(CAST('{"a": 1, "b": 2, "c": 3}' AS JSON)->'$', '$.b')) AS `length_after_remove`;
SELECT json_length(json_query('{"a": 1, "b": 2, "c": 3}', '$.b')) AS `length_after_remove`;
SELECT json_length(json_remove(json_remove('{"a": 1, "b": 2, "c": 3}', '$.b'), '$.b')) AS `length_after_remove`;
SELECT json_length(json_remove('{"a": 1, "b": 2, "c": 3}', json_length(json_remove('{"a": 1, "b": 2, "c": 3}', '$.b')))) AS `length_after_remove`;
SELECT DISTINCT json_length(json_remove('{"a": 1, "b": 2, "c": 3}', '$.b')) AS `length_after_remove`;
SELECT json_length(json_remove('{"a": 1, "b": 2, "c": 3}', json_length(json_remove('{"a": 1, "b": 2, "c": 3}', '$.b')))) AS `length_after_remove`;
SELECT json_length(json_remove('%', '$.b')) AS `length_after_remove`;
SELECT json_length(json_remove('{"a": 1, "b": 2, "c": 3}', 1.0E308)) AS `length_after_remove`;
SELECT json_length(json_remove('{"a": 1, "b": 2, "c": 3}', '{"a": 1, "b": 2, "c": 3}')) AS `length_after_remove`;
SELECT json_length(json_remove(repeat('x', 65536), '$.b')) AS `length_after_remove`;
SELECT json_length('{"a": 1, "b": 2, "c": 3}') AS `length_after_remove`;
SELECT json_keys(json_remove('{"x": 1, "y": 2, "z": 3}', json_remove('{"a": 1}', '$'))) AS `keys_after_remove`;
SELECT json_keys(json_remove(json_remove('{"x": 1, "y": 2, "z": 3}', '$.y'), '$.y')) AS `keys_after_remove`;
SELECT json_keys(json_remove(json_remove('{"x": 1, "y": 2, "z": 3}', '$.y'), '$.y')) AS `keys_after_remove`;
SELECT json_keys(json_remove('{"x": 1, "y": 2, "z": 3}', '$.y')) AS `keys_after_remove` LIMIT 2;
SELECT json_keys(json_remove('{"x": 1, "y": 2, "z": 3}', '$.y')) AS `keys_after_remove`;
SELECT json_keys(json_remove(0.0, '$.y')) AS `keys_after_remove`;
SELECT json_keys(json_remove(json_remove('{"x": 1, "y": 2, "z": 3}', '$.y'), '$.y')) AS `keys_after_remove`;
SELECT json_keys(json_remove('{"x": 1, "y": 2, "z": 3}', '$.y')) AS `keys_after_remove`;
SELECT json_keys(json_remove(TRUE, '$.y')) AS `keys_after_remove`;
SELECT json_keys(json_remove(json_keys(json_remove('{"x": 1, "y": 2, "z": 3}', '$.y')), '$.y')) AS `keys_after_remove`;
SELECT json_keys(json_remove('{"x": 1, "y": 2, "z": 3}', '$.y')) AS `keys_after_remove` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_keys(json_remove(json_remove('{"x": 1, "y": 2, "z": 3}', '$.y'), '$.y')) AS `keys_after_remove`;
SELECT json_keys(json_remove('{"x": 1, "y": 2, "z": 3}', -2147483648)) AS `keys_after_remove`;
SELECT json_keys(json_remove('', '$.y')) AS `keys_after_remove`;
SELECT json_keys(json_remove('{"x": 1, "y": 2, "z": 3}', '$.y')) AS `keys_after_remove` LIMIT 100;
SELECT json_keys(round('{"x": 1, "y": 2, "z": 3}', '$.y')) AS `keys_after_remove`;
SELECT json_keys(concat_ws('{"x": 1, "y": 2, "z": 3}', '$.y')) AS `keys_after_remove`;
SELECT json_keys(json_remove(1, '$.y')) AS `keys_after_remove`;
SELECT json_keys(json_remove('%', '$.y')) AS `keys_after_remove`;
SELECT json_keys(json_remove(9223372036854775807, '$.y')) AS `keys_after_remove`;
SELECT json_keys(json_remove('{"x": 1, "y": 2, "z": 3}', 170141183460469231731687303715884105727)) AS `keys_after_remove`;
SELECT CAST((json_keys(json_remove('{"x": 1, "y": 2, "z": 3}', '$.y'))) AS JSON)->'k' AS `keys_after_remove`;
SELECT json_keys(json_remove(170141183460469231731687303715884105727, '$.y')) AS `keys_after_remove`;
SELECT json_keys(json_remove('{"x": 1, "y": 2, "z": 3}', '\\')) AS `keys_after_remove`;
SELECT json_keys(json_remove('{"x": 1, "y": 2, "z": 3}', 1)) AS `keys_after_remove`;
SELECT json_keys(json_remove('{"x": 1, "y": 2, "z": 3}', '$.y')) AS `keys_after_remove`;
SELECT json_keys(json_remove('{"x": 1, "y": 2, "z": 3}', '$.y')) AS `keys_after_remove` LIMIT 1, 2;
SELECT json_keys(json_remove('{"x": 1, "y": 2, "z": 3}', 9223372036854775807)) AS `keys_after_remove`;
SELECT json_keys(json_remove('0', '$.y')) AS `keys_after_remove`;
SELECT max(json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a')) OVER () AS `exists_after_remove`;
SELECT json_exists(json_remove(CAST((CAST('{"a": 1, "b": 2}' AS DECIMAL128(38,37))) AS VARCHAR(65533)), '$.a'), '$.a') AS `exists_after_remove`;
SELECT json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '{"a": 1, "b": 2}') AS `exists_after_remove`;
SELECT json_exists(json_remove('{"a": 1, "b": 2}', CAST((CAST((CAST('$.a' AS BIGINT)) AS CHAR(1))) AS DOUBLE)), '$.a') AS `exists_after_remove`;
SELECT CAST((CAST((json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a')) AS LARGEINT)) AS DECIMAL128(38,0)) AS `exists_after_remove`;
SELECT json_exists(json_remove('{"a": 1, "b": [10, 20, 30]}', '$.a'), '$.a') AS `exists_after_remove`;
SELECT json_exists('{"a": 1, "b": 2}', '$.a') AS `exists_after_remove`;
SELECT json_exists(json_remove(json_keys(json_remove('{"x": 1, "y": 2, "z": 3}', '$.y')), '$.a'), '$.a') AS `exists_after_remove`;
SELECT json_exists(json_remove('{"a": 1, "b": 2}', '{"a": 1, "b": 2}'), '$.a') AS `exists_after_remove`;
SELECT json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), 9223372036854775807) AS `exists_after_remove`;
SELECT json_exists(json_remove('$.a', '$.a'), '$.a') AS `exists_after_remove`;
SELECT json_exists(json_remove('{"a": 1, "b": 2}', json_remove('{"a": 1, "b": 2}', '$.a')), '$.a') AS `exists_after_remove`;
SELECT json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), get_json_string(CAST('$.a' AS JSON), '$.a')) AS `exists_after_remove`;
SELECT count(json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a')) OVER () AS `exists_after_remove`;
SELECT json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a') AS `exists_after_remove` ORDER BY json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a') ASC NULLS LAST;
SELECT json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), json_remove('{"a": 1, "b": 2}', '$.a')) AS `exists_after_remove`;
SELECT json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '{"a": 1, "b": 2}') AS `exists_after_remove`;
SELECT json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a') AS `exists_after_remove`;
SELECT json_exists(json_remove('$.a', '$.a'), '$.a') AS `exists_after_remove`;
SELECT json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a') AS `exists_after_remove` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_exists(round('{"a": 1, "b": 2}', '$.a'), '$.a') AS `exists_after_remove`;
SELECT json_exists(json_remove('{"a": 1, "b": 2, "c": 3}', '$.a'), '$.a') AS `exists_after_remove`;
SELECT json_exists(json_remove('$.a', '$.a'), '$.a') AS `exists_after_remove`;
SELECT json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a') AS `exists_after_remove` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_exists(json_remove(0.0, '$.a'), '$.a') AS `exists_after_remove`;
SELECT json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), json_remove('{"a": 1, "b": 2}', '$.a')) AS `exists_after_remove`;
SELECT json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '0') AS `exists_after_remove`;
SELECT json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), json_remove('{"a": 1, "b": 2}', '$.a')) AS `exists_after_remove`;
SELECT json_exists(json_remove('$.a', '$.a'), '$.a') AS `exists_after_remove`;
SELECT json_exists(json_remove('{"a": 1, "b": 2}', json_remove('{"a": 1, "b": 2}', '$.a')), '$.a') AS `exists_after_remove`;
SELECT json_exists(json_remove('{"a": 1, "b": 2}', '{"a": 1, "b": 2}'), '$.a') AS `exists_after_remove`;
SELECT json_exists(json_remove('{"a": 1, "b": 2}', -1), '$.a') AS `exists_after_remove`;
SELECT json_remove(parse_json(170141183460469231731687303715884105727), '$.temp') AS `parsed_and_removed`;
SELECT json_remove(unhex('{"temp": "data", "keep": "this"}'), '$.temp') AS `parsed_and_removed`;
SELECT json_remove(parse_json('{"temp": "data", "keep": "this"}'), '$.temp') AS `parsed_and_removed` LIMIT 0;
SELECT json_remove(parse_json('{"temp": "data", "keep": "this"}'), '{"temp": "data", "keep": "this"}') AS `parsed_and_removed`;
SELECT json_remove(parse_json(0), '$.temp') AS `parsed_and_removed`;
SELECT json_remove(parse_json('{"temp": "data", "keep": "this"}'), '0') AS `parsed_and_removed`;
SELECT json_remove(abs('{"temp": "data", "keep": "this"}'), '$.temp') AS `parsed_and_removed`;
SELECT json_remove(parse_json('$.temp'), '$.temp') AS `parsed_and_removed`;
SELECT json_remove(sqrt('{"temp": "data", "keep": "this"}'), '$.temp') AS `parsed_and_removed`;
SELECT json_remove(parse_json('{"temp": "data", "keep": "this"}'), '$.temp') AS `parsed_and_removed`;
SELECT json_remove(parse_json('{"temp": "data", "keep": "this"}'), '$.temp') AS `parsed_and_removed`;
SELECT json_remove(json_remove(parse_json('{"temp": "data", "keep": "this"}'), '$.temp'), '$.temp') AS `parsed_and_removed`;
SELECT json_remove(CAST((parse_json('{"temp": "data", "keep": "this"}')) AS JSON)->'$', '$.temp') AS `parsed_and_removed`;
SELECT json_remove(parse_json('{"temp": "data", "keep": "this"}'), json_query(CAST('$.temp' AS JSON), '$.a')) AS `parsed_and_removed`;
SELECT json_remove('{"temp": "data", "keep": "this"}', '$.temp') AS `parsed_and_removed`;
SELECT json_remove(parse_json('{"temp": "data", "keep": "this"}'), '$.temp') AS `parsed_and_removed` LIMIT 7, 100;
SELECT json_remove('{"temp": "data", "keep": "this"}', '$.temp') AS `parsed_and_removed`;
SELECT json_remove(parse_json('{"temp": "data", "keep": "this"}'), '$.temp') AS `parsed_and_removed`;
SELECT json_remove(year('{"temp": "data", "keep": "this"}'), '$.temp') AS `parsed_and_removed`;
SELECT json_remove(parse_json('$.a.b.c.d'), '$.temp') AS `parsed_and_removed`;
SELECT json_remove(parse_json('{"temp": "data", "keep": "this"}'), 1.0E308) AS `parsed_and_removed`;
SELECT json_remove(parse_json('{"temp": "data", "keep": "this"}'), '$.temp') AS `parsed_and_removed` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove(parse_json(1), '$.temp') AS `parsed_and_removed`;
SELECT json_remove(parse_json('{"temp": "data", "keep": "this"}'), '$.temp') AS `parsed_and_removed` LIMIT 1;
SELECT json_remove(parse_json('{"temp": "data", "keep": "this"}'), json_remove(parse_json('{"temp": "data", "keep": "this"}'), '$.temp')) AS `parsed_and_removed`;
SELECT json_remove(sqrt('{"temp": "data", "keep": "this"}'), '$.temp') AS `parsed_and_removed`;
SELECT json_remove('{"temp": "data", "keep": "this"}', '$.temp') AS `parsed_and_removed`;
SELECT json_remove(length('{"temp": "data", "keep": "this"}'), '$.temp') AS `parsed_and_removed`;
SELECT json_remove(parse_json(NULL), '$.temp') AS `parsed_and_removed`;
SELECT json_query(CAST((json_remove('{"a": 1}', '$')) AS JSON), '$.a') AS `root_path`;
SELECT json_remove(-2147483648, '$') AS `root_path`;
SELECT json_remove('{"a": 1}', '{"a": 1}') AS `root_path`;
SELECT json_remove('{"a": 1}', '{"a": 1}') AS `root_path`;
SELECT json_remove('{"a": 1}', 0.0) AS `root_path`;
SELECT json_remove('{"a": 1}', 0.0) AS `root_path`;
SELECT json_remove(json_remove('{"a": 1}', '$'), '$') AS `root_path`;
SELECT json_remove('{"a": 1}', '$') AS `root_path`;
SELECT json_remove(2147483647, '$') AS `root_path`;
SELECT json_remove('$', '$') AS `root_path`;
SELECT json_remove('{"a": 1}', json_remove('{"a": 1}', '$')) AS `root_path`;
SELECT json_remove('{"a": 1}', '$') AS `root_path`;
SELECT json_remove('{"a": 1}', '9999-12-31 23:59:59') AS `root_path`;
SELECT json_remove(-1, '$') AS `root_path`;
SELECT json_remove('{"a": 1}', '%') AS `root_path`;
SELECT json_remove('{"a": 1}', '$') AS `root_path`;
SELECT json_remove('$', '$') AS `root_path`;
SELECT json_remove('{"a": 1}', json_length(json_remove('{"a": 1, "b": 2, "c": 3}', '$.b'))) AS `root_path`;
SELECT json_remove('{"a": 1}', '$') AS `root_path` LIMIT 2;
SELECT json_remove('{"a": 1}', json_remove('{"a": 1}', '$')) AS `root_path`;
SELECT json_remove('{"a": 1}', 2147483647) AS `root_path`;
SELECT json_remove('{"a": 1}', -1) AS `root_path`;
SELECT json_remove(json_remove('{"a": 1}', '$'), '$') AS `root_path`;
SELECT json_remove(json_remove('{"a": 1}', '$'), '$') AS `root_path`;
SELECT json_remove(1, '$.') AS `dot_path`;
SELECT count(json_remove('{"a": 1}', '$.')) OVER () AS `dot_path`;
SELECT json_remove('{"a": 1}', '$.') AS `dot_path` LIMIT 5;
SELECT json_remove('{"a": 1}', '$.') AS `dot_path`;
SELECT json_remove(-2147483648, '$.') AS `dot_path`;
SELECT json_remove('$', '$.') AS `dot_path`;
SELECT json_remove('{"a": 1}', '{"a": 1}') AS `dot_path`;
SELECT json_remove('{"a": 1}', -2147483648) AS `dot_path`;
SELECT json_remove(9223372036854775807, '$.') AS `dot_path`;
SELECT json_remove('{"a": 1}', '$.') AS `dot_path` LIMIT 2;
SELECT json_remove(2147483647, '$.') AS `dot_path`;
SELECT json_remove('{"a": 1}', -1.0E308) AS `dot_path`;
SELECT json_remove('{"a": 1}', 2147483647) AS `dot_path`;
SELECT json_remove(json_remove('{"a": 1}', '$.'), '$.') AS `dot_path`;
SELECT json_remove('{"a": 1}', '$.') AS `dot_path` LIMIT 0;
SELECT json_remove('{"a": 1}', 0.0) AS `dot_path`;
SELECT json_remove('$.a.x', '$.') AS `dot_path`;
SELECT CAST((json_remove('{"a": 1}', '$.')) AS JSON)->'$.a' AS `dot_path`;
SELECT json_remove('{"a": 1}', '$.') AS `dot_path` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('{"a": 1}', -9223372036854775808) AS `dot_path`;
SELECT json_remove(CAST('{"a": 1}' AS VARCHAR(65533)), '$.') AS `dot_path`;
SELECT json_remove('{"a": 1}', '$.') AS `dot_path` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('{"a": 1}', '$.') AS `dot_path` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove(0.0, '$.a.b.c.d') AS `remove_deep_nested`;
SELECT json_remove('{"a": {"b": {"c": {"d": {"e": "deep"}}}}}', '$.a.b.c.d') AS `remove_deep_nested`;
SELECT json_remove(repeat('x', 65536), '$.a.b.c.d') AS `remove_deep_nested`;
SELECT json_remove('{"a": {"b": {"c": {"d": {"e": "deep"}}}}}', json_remove('{"a": {"b": {"c": {"d": {"e": "deep"}}}}}', '$.a.b.c.d')) AS `remove_deep_nested`;
SELECT json_remove('{"a": {"b": {"c": {"d": {"e": "deep"}}}}}', '0000-00-00') AS `remove_deep_nested`;
SELECT json_remove(1.0E308, '$.a.b.c.d') AS `remove_deep_nested`;
SELECT json_remove('$.a.b.c.d', '$.a.b.c.d') AS `remove_deep_nested`;
SELECT json_remove('{"a": {"b": {"c": {"d": {"e": "deep"}}}}}', '$.a.b.c.d') AS `remove_deep_nested`;
SELECT json_remove('{"a": {"b": {"c": {"d": {"e": "deep"}}}}}', '$.a.b.c.d') AS `remove_deep_nested`;
SELECT json_remove('{"a": {"b": {"c": {"d": {"e": "deep"}}}}}', json_remove('{"a": {"b": {"c": {"d": {"e": "deep"}}}}}', '$.a.b.c.d')) AS `remove_deep_nested`;
SELECT json_remove(-2147483648, '$.a.b.c.d') AS `remove_deep_nested`;
SELECT json_remove('{"a": {"b": {"c": {"d": {"e": "deep"}}}}}', '$.a.b.c.d') AS `remove_deep_nested` LIMIT 1, 1;
SELECT json_remove('{"a": {"b": {"c": {"d": {"e": "deep"}}}}}', repeat('x', 65536)) AS `remove_deep_nested`;
SELECT json_remove(json_remove('{"a": {"b": {"c": {"d": {"e": "deep"}}}}}', '$.a.b.c.d'), '$.a.b.c.d') AS `remove_deep_nested`;
SELECT json_remove(CAST('{"a": {"b": {"c": {"d": {"e": "deep"}}}}}' AS JSON)->'$', '$.a.b.c.d') AS `remove_deep_nested`;
SELECT json_remove('{"a": {"b": {"c": {"d": {"e": "deep"}}}}}', '$.a.b.c.d') AS `remove_deep_nested` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('{"a": {"b": {"c": {"d": {"e": "deep"}}}}}', '$.a.b.c.d') AS `remove_deep_nested`;
SELECT json_remove('{"a": {"b": {"c": {"d": {"e": "deep"}}}}}', 9223372036854775807) AS `remove_deep_nested`;
SELECT json_remove('{"a": {"b": {"c": {"d": {"e": "deep"}}}}}', 0) AS `remove_deep_nested`;
SELECT json_remove('$.a.b.c.d', '$.a.b.c.d') AS `remove_deep_nested`;
SELECT json_remove(9223372036854775807, '$.a.b.c.d') AS `remove_deep_nested`;
SELECT json_remove(1.0E308, '$.a.b.c.d') AS `remove_deep_nested`;
SELECT json_remove('{"a": {"b": {"c": {"d": {"e": "deep"}}}}}', '%') AS `remove_deep_nested`;
SELECT json_remove('{"a": {"b": {"c": {"d": {"e": "deep"}}}}}', CAST((CAST('$.a.b.c.d' AS DATE)) AS TINYINT)) AS `remove_deep_nested`;
SELECT json_remove('{"a": {"b": {"c": {"d": {"e": "deep"}}}}}', '$.a.b.c.d') AS `remove_deep_nested`;
SELECT json_remove('{"a": {"b": {"c": {"d": {"e": "deep"}}}}}', '1970-01-01') AS `remove_deep_nested`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '%') AS `remove_first_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[0]') AS `remove_first_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[0]') AS `remove_first_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', 'invalid_path') AS `remove_first_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', -1.0E308) AS `remove_first_element`;
SELECT CAST((json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[0]')) AS JSON)->'$' AS `remove_first_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[0]') AS `remove_first_element` LIMIT 2;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', 1) AS `remove_first_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[0]') AS `remove_first_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[0]') AS `remove_first_element`;
SELECT json_remove(0.0, '$.arr[0]') AS `remove_first_element`;
SELECT json_remove('$.arr[0]', '$.arr[0]') AS `remove_first_element`;
SELECT json_remove(170141183460469231731687303715884105727, '$.arr[0]') AS `remove_first_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', 1) AS `remove_first_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', 170141183460469231731687303715884105727) AS `remove_first_element`;
SELECT json_remove('$.arr[0]', '$.arr[0]') AS `remove_first_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', CAST((CAST((CAST('$.arr[0]' AS VARCHAR(65533))) AS DECIMAL128(38,0))) AS LARGEINT)) AS `remove_first_element`;
SELECT json_remove('invalid_path', '$.arr[0]') AS `remove_first_element`;
SELECT json_remove(-1.0E308, '$.arr[0]') AS `remove_first_element`;
SELECT json_remove(9223372036854775807, '$.arr[0]') AS `remove_first_element`;
SELECT json_remove(json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[0]'), '$.arr[0]') AS `remove_first_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', 0) AS `remove_first_element`;
SELECT json_remove(1, '$.arr[0]') AS `remove_first_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[0]') AS `remove_first_element`;
SELECT json_remove(json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[0]'), '$.arr[0]') AS `remove_first_element`;
SELECT json_remove('{"a": 1}', '$.arr[0]') AS `remove_first_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', 0) AS `remove_first_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[0]') AS `remove_first_element`;
SELECT json_remove(json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[0]'), '$.arr[0]') AS `remove_first_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', -1.0E308) AS `remove_first_element`;
SELECT json_remove(json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[0]'), '$.arr[0]') AS `remove_first_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', 2147483647) AS `remove_first_element`;
SELECT json_remove(0.0, '$.arr[4]') AS `remove_last_element`;
SELECT json_remove(json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[4]'), '$.arr[4]') AS `remove_last_element`;
SELECT json_remove(json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[4]'), '$.arr[4]') AS `remove_last_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '') AS `remove_last_element`;
SELECT json_remove('$.nonexistent', '$.arr[4]') AS `remove_last_element`;
SELECT json_remove('$.arr[4]', '$.arr[4]') AS `remove_last_element`;
SELECT json_remove(0.0, '$.arr[4]') AS `remove_last_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[4]') AS `remove_last_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[4]') AS `remove_last_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '%') AS `remove_last_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '{"arr": [0, 1, 2, 3, 4]}') AS `remove_last_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', 1) AS `remove_last_element`;
SELECT json_remove(0, '$.arr[4]') AS `remove_last_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[4]') AS `remove_last_element`;
SELECT count(json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[4]')) OVER () AS `remove_last_element`;
SELECT json_remove(170141183460469231731687303715884105727, '$.arr[4]') AS `remove_last_element`;
SELECT json_remove('$.arr[4]', '$.arr[4]') AS `remove_last_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '%') AS `remove_last_element`;
SELECT json_remove('$.arr[4]', '$.arr[4]') AS `remove_last_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', FALSE) AS `remove_last_element`;
SELECT CAST((json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[4]')) AS JSON)->'$' AS `remove_last_element`;
SELECT json_remove(FALSE, '$.arr[4]') AS `remove_last_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '1970-01-01') AS `remove_last_element`;
SELECT json_remove(-2147483648, '$.arr[4]') AS `remove_last_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[4]') AS `remove_last_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', -9223372036854775808) AS `remove_last_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[4]') AS `remove_last_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[2]') AS `remove_middle_element` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '0000-00-00') AS `remove_middle_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[2]') AS `remove_middle_element` LIMIT 5;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '{"arr": [0, 1, 2, 3, 4]}') AS `remove_middle_element`;
SELECT json_remove('$.arr[2]', '$.arr[2]') AS `remove_middle_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '{"arr": [0, 1, 2, 3, 4]}') AS `remove_middle_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', -9223372036854775808) AS `remove_middle_element`;
SELECT json_remove(json_remove('{}', '$.a'), '$.arr[2]') AS `remove_middle_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', 9223372036854775807) AS `remove_middle_element`;
SELECT json_remove('$.arr[2]', '$.arr[2]') AS `remove_middle_element`;
SELECT json_remove('$.arr[2]', '$.arr[2]') AS `remove_middle_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '') AS `remove_middle_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[2]') AS `remove_middle_element` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', CAST(NULL AS JSON)) AS `remove_middle_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[2]') AS `remove_middle_element` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('$.arr[2]', '$.arr[2]') AS `remove_middle_element`;
SELECT json_remove(json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[2]'), '$.arr[2]') AS `remove_middle_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[2]') AS `remove_middle_element`;
SELECT json_remove(json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[2]'), '$.arr[2]') AS `remove_middle_element`;
SELECT json_remove('1970-01-01', '$.arr[2]') AS `remove_middle_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[2]') AS `remove_middle_element` LIMIT 2;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[2]') AS `remove_middle_element` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', 0) AS `remove_middle_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[2]') AS `remove_middle_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', -1.0E308) AS `remove_middle_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', json_length(CAST('$.arr[2]' AS JSON))) AS `remove_middle_element`;
SELECT json_remove(json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[2]'), '$.arr[2]') AS `remove_middle_element`;
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[2]') AS `remove_middle_element` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('{"arr": [0, 1, 2, 3, 4]}', CAST('$.arr[2]' AS VARCHAR(65533))) AS `remove_middle_element`;
SELECT json_remove(FALSE, '$.arr[2]') AS `remove_middle_element`;
SELECT json_length(CAST((json_remove('{"key with spaces": "value", "normal": "data"}', '$."key with spaces"')) AS JSON)) AS `remove_special_key`;
SELECT json_remove('0000-00-00', '$."key with spaces"') AS `remove_special_key`;
SELECT json_remove(json_remove('{"arr": [0, 1, 2, 3, 4]}', '$.arr[4]'), '$."key with spaces"') AS `remove_special_key`;
SELECT json_remove('{"key with spaces": "value", "normal": "data"}', '{"a": []}') AS `remove_special_key`;
SELECT json_remove('{"key with spaces": "value", "normal": "data"}', CAST('$."key with spaces"' AS JSON)->'$') AS `remove_special_key`;
SELECT json_remove('0000-00-00', '$."key with spaces"') AS `remove_special_key`;
SELECT json_remove('', '$."key with spaces"') AS `remove_special_key`;
SELECT json_remove('{"key with spaces": "value", "normal": "data"}', '$."key with spaces"') AS `remove_special_key` LIMIT 1, 100;
SELECT json_remove('$."key with spaces"', '$."key with spaces"') AS `remove_special_key`;
SELECT json_remove('{"key with spaces": "value", "normal": "data"}', 1.0E308) AS `remove_special_key`;
SELECT json_remove('{"key with spaces": "value", "normal": "data"}', 2147483647) AS `remove_special_key`;
SELECT json_remove(CAST('{"key with spaces": "value", "normal": "data"}' AS LARGEINT), '$."key with spaces"') AS `remove_special_key`;
SELECT json_remove(json_query(CAST('{"key with spaces": "value", "normal": "data"}' AS JSON), '$.a'), '$."key with spaces"') AS `remove_special_key`;
SELECT json_remove('{"key with spaces": "value", "normal": "data"}', '$."key with spaces"') AS `remove_special_key` LIMIT 5;
SELECT CAST((CAST((json_remove('{"key with spaces": "value", "normal": "data"}', '$."key with spaces"')) AS DECIMAL128(38,37))) AS FLOAT) AS `remove_special_key`;
SELECT json_remove('{"key with spaces": "value", "normal": "data"}', 0.0) AS `remove_special_key`;
SELECT json_remove('{"key with spaces": "value", "normal": "data"}', '$."key with spaces"') AS `remove_special_key`;
SELECT json_remove('{"key with spaces": "value", "normal": "data"}', 1.0E308) AS `remove_special_key`;
SELECT json_remove('{"key with spaces": "value", "normal": "data"}', FALSE) AS `remove_special_key`;
SELECT json_remove('{"key with spaces": "value", "normal": "data"}', '0') AS `remove_special_key`;
SELECT json_remove('{"key with spaces": "value", "normal": "data"}', '$."key with spaces"') AS `remove_special_key`;
SELECT json_remove('{"key with spaces": "value", "normal": "data"}', '$."key with spaces"') AS `remove_special_key` LIMIT 0;
SELECT json_remove(9223372036854775807, '$."key with spaces"') AS `remove_special_key`;
SELECT json_remove('{"key with spaces": "value", "normal": "data"}', '$."key with spaces"') AS `remove_special_key` WHERE json_exists(json_remove('{"a": 1, "b": 2}', '$.a'), '$.a');
SELECT json_remove('{"key with spaces": "value", "normal": "data"}', '{"key with spaces": "value", "normal": "data"}') AS `remove_special_key`;
SELECT json_remove('9999-12-31 23:59:59', '$."key with spaces"') AS `remove_special_key`;
SELECT json_remove('{"key with spaces": "value", "normal": "data"}', json_remove('{"a": 1, "b": [10, 20, 30]}', '$.b[1]')) AS `remove_special_key`;