SELECT count(*) AS `count(*)`, sum(`srfuzz_mut_1209`.`t`.`v`) AS `sum(v)` FROM `srfuzz_mut_1209`.`t`;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1209`.`t` WHERE `srfuzz_mut_1209`.`t`.`k` = 0;
SELECT CAST((count(*)) AS DOUBLE) AS `CAST((count(*)) AS DOUBLE)`, sum(`srfuzz_mut_1209`.`t`.`v`) AS `sum(v)` FROM `srfuzz_mut_1209`.`t`;
SELECT count(*) AS `count(*)`, sum(`srfuzz_mut_1209`.`t`.`v`) AS `sum(v)` FROM `srfuzz_mut_1209`.`t`;
SELECT count(*) AS `count(*)`, sum(`srfuzz_mut_1209`.`t`.`v`) AS `sum(v)` FROM `srfuzz_mut_1209`.`t`;
SELECT count(*) AS `count(*)`, sum(`srfuzz_mut_1209`.`t`.`v`) AS `sum(v)` FROM `srfuzz_mut_1209`.`t`;
SELECT count(*) AS `count(*)`, sum(`srfuzz_mut_1209`.`t`.`v`) AS `sum(v)` FROM `srfuzz_mut_1209`.`t` HAVING (count(*)) > 1;
SELECT count(*) AS `count(*)`, sum(0) AS `sum(0)` FROM `srfuzz_mut_1209`.`t`;
SELECT count(*) AS `count(*)`, sum(`srfuzz_mut_1209`.`t`.`v`) AS `sum(v)` FROM `srfuzz_mut_1209`.`t`;
SELECT count(*) AS `count(*)`, sum(`srfuzz_mut_1209`.`t`.`v`) AS `sum(srfuzz_mut_1209.t.v)` FROM `srfuzz_mut_1209`.`t`;
SELECT count(*) AS `count(*)`, sum(`srfuzz_mut_1209`.`t`.`v`) AS `sum(v)` FROM `srfuzz_mut_1209`.`t`;
SELECT count(*) AS `count(*)`, sum(`srfuzz_mut_1209`.`t`.`v`) AS `sum(v)` FROM `srfuzz_mut_1209`.`t` LIMIT 0;
SELECT count(*) AS `count(*)`, sum(`srfuzz_mut_1209`.`t`.`v`) AS `sum(v)` FROM `srfuzz_mut_1209`.`t`;
SELECT count(*) AS `count(*)`, sum(`srfuzz_mut_1209`.`t`.`v`) AS `sum(v)` FROM `srfuzz_mut_1209`.`t`;
SELECT count(*) AS `count(*)`, sum(CAST(`srfuzz_mut_1209`.`t`.`v` AS SMALLINT)) AS `sum(CAST(v AS SMALLINT))` FROM `srfuzz_mut_1209`.`t`;
SELECT count(*) AS `count(*)`, sum(`srfuzz_mut_1209`.`t`.`v`) AS `sum(srfuzz_mut_1209.t.v)` FROM `srfuzz_mut_1209`.`t`;
SELECT count(*) AS `count(*)`, sum(`srfuzz_mut_1209`.`t`.`v`) AS `sum(v)` FROM `srfuzz_mut_1209`.`t` GROUP BY `srfuzz_mut_1209`.`t`.`v`;
SELECT count(*) AS `count(*)`, sum(`t`.`v`) AS `sum(v)` FROM (SELECT `srfuzz_mut_1209`.`t`.`k`, `srfuzz_mut_1209`.`t`.`v` FROM `srfuzz_mut_1209`.`t` UNION SELECT `srfuzz_mut_1209`.`t`.`k`, `srfuzz_mut_1209`.`t`.`v` FROM `srfuzz_mut_1209`.`t`) `t`;
SELECT count(*) AS `count(*)`, sum(`srfuzz_mut_1209`.`t`.`k`) AS `sum(srfuzz_mut_1209.t.k)` FROM `srfuzz_mut_1209`.`t`;
SELECT count(*) AS `count(*)`, sum(`srfuzz_mut_1209`.`t`.`v`) AS `sum(v)` FROM `srfuzz_mut_1209`.`t`;
SELECT count(*) AS `count(*)`, sum(`t`.`v`) AS `sum(v)` FROM (SELECT `srfuzz_mut_1209`.`t`.`k`, `srfuzz_mut_1209`.`t`.`v` FROM `srfuzz_mut_1209`.`t` INTERSECT SELECT `srfuzz_mut_1209`.`t`.`k`, `srfuzz_mut_1209`.`t`.`v` FROM `srfuzz_mut_1209`.`t`) `t`;
SELECT count(*) AS `count(*)`, sum(`srfuzz_mut_1209`.`t`.`v`) AS `sum(v)` FROM `srfuzz_mut_1209`.`t` GROUP BY `srfuzz_mut_1209`.`t`.`v`;
SELECT count(*) AS `count(*)`, sum(`srfuzz_mut_1209`.`t`.`v`) AS `sum(v)` FROM `srfuzz_mut_1209`.`t` LIMIT 5;
SELECT count(*) AS `count(*)`, sum(`srfuzz_mut_1209`.`t`.`v`) AS `sum(v)` FROM `srfuzz_mut_1209`.`t` ORDER BY count(*) ASC;
SELECT count(*) AS `count(*)`, sum(`t`.`v`) AS `sum(v)` FROM (SELECT `srfuzz_mut_1209`.`t`.`k`, `srfuzz_mut_1209`.`t`.`v` FROM `srfuzz_mut_1209`.`t` UNION SELECT `srfuzz_mut_1209`.`t`.`k`, `srfuzz_mut_1209`.`t`.`v` FROM `srfuzz_mut_1209`.`t`) `t`;
SELECT count(*) AS `count(*)`, sum(`srfuzz_mut_1209`.`t`.`v`) AS `sum(v)` FROM `srfuzz_mut_1209`.`t`;
SELECT count(*) AS `count(*)`, sum(`srfuzz_mut_1209`.`t`.`v`) AS `sum(v)` FROM `srfuzz_mut_1209`.`t` ORDER BY count(*) ASC NULLS LAST;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_1209`.`t`.`k`, `srfuzz_mut_1209`.`t`.`v` FROM `srfuzz_mut_1209`.`t`) `t` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  WHERE `t`.`k` = 0;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1209`.`t` WHERE `srfuzz_mut_1209`.`t`.`k` = 0 GROUP BY `srfuzz_mut_1209`.`t`.`v`;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1209`.`t` WHERE `srfuzz_mut_1209`.`t`.`k` = 0;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1209`.`t` WHERE `srfuzz_mut_1209`.`t`.`k` = (json_length(CAST(0 AS JSON)));
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1209`.`t` WHERE 0 = 0;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1209`.`t` WHERE `srfuzz_mut_1209`.`t`.`k` = 0 GROUP BY `srfuzz_mut_1209`.`t`.`v`;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1209`.`t` WHERE 0 = 0;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_1209`.`t`.`k`, `srfuzz_mut_1209`.`t`.`v` FROM `srfuzz_mut_1209`.`t`) `t` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  WHERE `t`.`k` = 0;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1209`.`t` WHERE `srfuzz_mut_1209`.`t`.`k` = 0;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1209`.`t` WHERE `srfuzz_mut_1209`.`t`.`k` = `srfuzz_mut_1209`.`t`.`k`;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_1209`.`t`.`k`, `srfuzz_mut_1209`.`t`.`v` FROM `srfuzz_mut_1209`.`t`) `t` WHERE `t`.`k` = 0;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1209`.`t` WHERE `srfuzz_mut_1209`.`t`.`k` = -9223372036854775808;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1209`.`t` WHERE `srfuzz_mut_1209`.`t`.`k` = 0;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1209`.`t` WHERE `srfuzz_mut_1209`.`t`.`k` = 1;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1209`.`t` WHERE `srfuzz_mut_1209`.`t`.`k` = 0.0;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1209`.`t` WHERE 0 = 0;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1209`.`t` WHERE `srfuzz_mut_1209`.`t`.`k` = 0 GROUP BY `srfuzz_mut_1209`.`t`.`v`;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_1209`.`t`.`k`, `srfuzz_mut_1209`.`t`.`v` FROM `srfuzz_mut_1209`.`t`) `t` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  WHERE `t`.`k` = 0;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_1209`.`t`.`k`, `srfuzz_mut_1209`.`t`.`v` FROM `srfuzz_mut_1209`.`t` INTERSECT SELECT `srfuzz_mut_1209`.`t`.`k`, `srfuzz_mut_1209`.`t`.`v` FROM `srfuzz_mut_1209`.`t`) `t` WHERE `t`.`k` = 0;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1209`.`t` WHERE `srfuzz_mut_1209`.`t`.`k` = `srfuzz_mut_1209`.`t`.`k`;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_1209`.`t`.`k`, `srfuzz_mut_1209`.`t`.`v` FROM `srfuzz_mut_1209`.`t`) `t` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  WHERE `t`.`k` = 0;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_1209`.`t`.`k`, `srfuzz_mut_1209`.`t`.`v` FROM `srfuzz_mut_1209`.`t`) `t` WHERE `t`.`k` = 0;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1209`.`t` WHERE `srfuzz_mut_1209`.`t`.`k` = `srfuzz_mut_1209`.`t`.`k`;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1209`.`t`;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1209`.`t` WHERE `srfuzz_mut_1209`.`t`.`k` = `srfuzz_mut_1209`.`t`.`k`;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1209`.`t`;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_1209`.`t`.`k`, `srfuzz_mut_1209`.`t`.`v` FROM `srfuzz_mut_1209`.`t` UNION ALL SELECT `srfuzz_mut_1209`.`t`.`k`, `srfuzz_mut_1209`.`t`.`v` FROM `srfuzz_mut_1209`.`t`) `t` WHERE `t`.`k` = 0;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_1209`.`t`.`k`, `srfuzz_mut_1209`.`t`.`v` FROM `srfuzz_mut_1209`.`t` UNION SELECT `srfuzz_mut_1209`.`t`.`k`, `srfuzz_mut_1209`.`t`.`v` FROM `srfuzz_mut_1209`.`t`) `t` WHERE `t`.`k` = 0;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1209`.`t` WHERE `srfuzz_mut_1209`.`t`.`k` = TRUE;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1209`.`t` WHERE `srfuzz_mut_1209`.`t`.`k` = 0;
SELECT count(*) AS `count(*)` FROM `srfuzz_mut_1209`.`t`;
SELECT count(*) AS `count(*)` FROM (SELECT `srfuzz_mut_1209`.`t`.`k`, `srfuzz_mut_1209`.`t`.`v` FROM `srfuzz_mut_1209`.`t`) `t` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  WHERE `t`.`k` = 0;