SELECT to_json(row(1, 1)) AS `to_json(row(1, 1))`;
SELECT to_json(NULL) AS `to_json(NULL)`;
SELECT to_json(MAP<BOOLEAN,BOOLEAN>{NULL:NULL}) AS `to_json(map{NULL:NULL})`;
SELECT to_json(MAP<BOOLEAN,BOOLEAN>{NULL:NULL}) AS `to_json(map{NULL:NULL})`;
SELECT to_json(row(1, 1)) AS `to_json(row(1, 1))`;
SELECT to_json(row(FALSE, 1)) AS `to_json(row(FALSE, 1))`;
SELECT to_json(row(CAST((CAST(1 AS DECIMAL128(27,9))) AS VARCHAR(1)), 1)) AS `to_json(row(CAST((CAST(1 AS DECIMAL128(27,9))) AS VARCHAR(1)), 1))`;
SELECT to_json(row(FALSE, 1)) AS `to_json(row(FALSE, 1))`;
SELECT to_json(row(1, 1)) AS `to_json(row(1, 1))` WHERE to_json(row(1, 1));
SELECT to_json(row(to_json(row(1, 1)), 1)) AS `to_json(row(to_json(row(1, 1)), 1))`;
SELECT to_json(row(1, 1)) AS `to_json(row(1, 1))` WHERE to_json(NULL);
SELECT to_json(row(NULL, 1)) AS `to_json(row(NULL, 1))`;
SELECT to_json(row(1, to_json(row(1, 1)))) AS `to_json(row(1, to_json(row(1, 1))))`;
SELECT to_json(row(1, 1)) AS `to_json(row(1, 1))`;
SELECT to_json(row(to_json(row(1, 1)), 1)) AS `to_json(row(to_json(row(1, 1)), 1))`;
SELECT to_json(row(1, 1.0E308)) AS `to_json(row(1, 1.0E308))`;
SELECT to_json(row(MAP<BOOLEAN,BOOLEAN>{NULL:NULL}, 1)) AS `to_json(row(map{NULL:NULL}, 1))`;
SELECT to_json(row(1, 1.0E308)) AS `to_json(row(1, 1.0E308))`;
SELECT to_json(row(1, 1)) AS `to_json(row(1, 1))` WHERE to_json(row(1, 1));
SELECT to_json(row(1, MAP<BOOLEAN,BOOLEAN>{NULL:NULL})) AS `to_json(row(1, map{NULL:NULL}))`;
SELECT to_json(row(1, '0000-00-00')) AS `to_json(row(1, '0000-00-00'))`;
SELECT to_json(row(1, 1.0E308)) AS `to_json(row(1, 1.0E308))`;
SELECT to_json(row('0', 1)) AS `to_json(row('0', 1))`;
SELECT to_json(row(1, FALSE)) AS `to_json(row(1, FALSE))`;
SELECT to_json(row(to_json(row(1, 1)), 1)) AS `to_json(row(to_json(row(1, 1)), 1))`;
SELECT to_json(row(1, NULL)) AS `to_json(row(1, NULL))`;
SELECT to_json(row(json_query(CAST(1 AS JSON), '$.a'), 1)) AS `to_json(row(json_query(CAST(1 AS JSON), '$.a'), 1))`;
SELECT to_json(row(1, CAST(1 AS JSON)->'$')) AS `to_json(row(1, CAST(1 AS JSON)->'$'))`;
SELECT to_json(row(0.0, 1)) AS `to_json(row(0.0, 1))`;
SELECT to_json(NULL) AS `to_json(NULL)`;
SELECT to_json(NULL) AS `to_json(NULL)`;
SELECT json_length(CAST((to_json(NULL)) AS JSON)) AS `json_length(CAST((to_json(NULL)) AS JSON))`;
SELECT to_json(MAP<BOOLEAN,BOOLEAN>{NULL:NULL}) AS `to_json(map{NULL:NULL})`;
SELECT to_json(NULL) AS `to_json(NULL)` WHERE NULL;
SELECT to_json(NULL) AS `to_json(NULL)`;
SELECT to_json(NULL) AS `to_json(NULL)`;
SELECT to_json(MAP<BOOLEAN,BOOLEAN>{NULL:NULL}) AS `to_json(map{NULL:NULL})`;
SELECT to_json(MAP<BOOLEAN,BOOLEAN>{NULL:NULL}) AS `to_json(map{NULL:NULL})`;
SELECT to_json(NULL) AS `to_json(NULL)`;
SELECT to_json(MAP<BOOLEAN,BOOLEAN>{NULL:NULL}) AS `to_json(map{NULL:NULL})`;
SELECT to_json(NULL) AS `to_json(NULL)`;
SELECT to_json(MAP<BOOLEAN,BOOLEAN>{NULL:NULL}) AS `to_json(map{NULL:NULL})`;
SELECT to_json(NULL) AS `to_json(NULL)`;
SELECT to_json(MAP<BOOLEAN,BOOLEAN>{NULL:NULL}) AS `to_json(map{NULL:NULL})`;
SELECT to_json(row(1, 1)) AS `to_json(row(1, 1))`;
SELECT to_json(MAP<BOOLEAN,BOOLEAN>{NULL:NULL}) AS `to_json(map{NULL:NULL})`;
SELECT to_json(MAP<BOOLEAN,BOOLEAN>{NULL:NULL}) AS `to_json(map{NULL:NULL})`;
SELECT to_json(NULL) AS `to_json(NULL)`;