SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_count(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_count(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT bitmap_from_binary(to_binary('1234')) AS `bitmap_from_binary(to_binary('1234'))`;
SELECT bitmap_from_binary(to_binary('')) AS `bitmap_from_binary(to_binary(''))`;
SELECT bitmap_from_binary(NULL) AS `bitmap_from_binary(NULL)`;
SELECT bitmap_to_binary(NULL) AS `bitmap_to_binary(NULL)`;
SELECT bitmap_to_binary(bitmap_from_string('abc')) AS `bitmap_to_binary(bitmap_from_string('abc'))`;
SELECT sum(`srfuzz_mut_178`.`t1`.`c1`) OVER () AS `sum(c1) OVER ()`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(`srfuzz_mut_178`.`t1`.`c1`) AS `hex(srfuzz_mut_178.t1.c1)` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))) AS `hex(bitmap_to_binary(hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, avg(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) OVER (PARTITION BY `srfuzz_mut_178`.`t1`.`c1` ) AS `avg(hex(bitmap_to_binary(c2))) OVER (PARTITION BY c1 )` FROM `srfuzz_mut_178`.`t1`;
SELECT CAST(`srfuzz_mut_178`.`t1`.`c1` AS JSON)->'$' AS `CAST(c1 AS JSON)->'$'`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) SELECT `t1`.`c1`, hex(bitmap_to_binary(`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_n1` AS t1;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_count(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_count(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, min(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) OVER (PARTITION BY `srfuzz_mut_178`.`t1`.`c1` ) AS `min(hex(bitmap_to_binary(c2))) OVER (PARTITION BY c1 )` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))) AS `hex(bitmap_to_binary(hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC NULLS LAST;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` GROUP BY `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`));
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_count(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_count(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` ORDER BY bitmap_count(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) DESC NULLS FIRST;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_count(unhex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_count(unhex(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_count(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_count(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT DISTINCT `srfuzz_mut_178`.`t1`.`c1`, bitmap_count(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_count(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_count(bitmap_from_binary(bitmap_to_binary(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))))) AS `bitmap_count(bitmap_from_binary(bitmap_to_binary(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2)))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_count(unhex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_count(unhex(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `t1`.`c1`, bitmap_count(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_count(bitmap_from_binary(bitmap_to_binary(c2)))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1`;
SELECT `t1`.`c1`, bitmap_count(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_count(bitmap_from_binary(bitmap_to_binary(c2)))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_count(unhex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_count(unhex(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_count(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_count(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_count(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_count(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` LIMIT 5;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_count(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_count(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `t1`.`c1`, bitmap_count(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_count(bitmap_from_binary(bitmap_to_binary(c2)))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1` UNION ALL SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1`;
SELECT DISTINCT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))) AS `hex(bitmap_to_binary(hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))) AS `hex(bitmap_to_binary(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))) AS `hex(bitmap_to_binary(hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `t1`.`c1`, hex(bitmap_to_binary(`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1` UNION ALL SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` LIMIT 0;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` LIMIT 7, 100;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` GROUP BY `c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`));
SELECT rank() OVER (PARTITION BY hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC ) AS `rank() OVER (PARTITION BY hex(bitmap_to_binary(c2)) ORDER BY c1 ASC )`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(`srfuzz_mut_178`.`t1`.`c1`) AS `hex(srfuzz_mut_178.t1.c1)` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` GROUP BY `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`));
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))) AS `hex(bitmap_to_binary(hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` GROUP BY `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`));
SELECT `t1`.`c1`, hex(bitmap_to_binary(`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1` UNION ALL SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))) AS `bitmap_to_string(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT DISTINCT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` ORDER BY bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(upper(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(upper(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT count(`srfuzz_mut_178`.`t1`.`c1`) OVER (PARTITION BY bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) ) AS `count(c1) OVER (PARTITION BY bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2))) )`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1` UNION ALL SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(md5(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(md5(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary('1234')) AS `bitmap_to_string(bitmap_from_binary('1234'))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` LIMIT 1;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(upper(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(upper(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT `t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2)))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` WHERE '';
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2)))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` GROUP BY `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)));
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2)))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2))))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `hex(hex(bitmap_to_binary(srfuzz_mut_178.t1.c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `t1`.`c1`, hex(bitmap_to_binary(`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` GROUP BY `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`));
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `t1`.`c1`, hex(bitmap_to_binary(`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1` UNION ALL SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `hex(hex(bitmap_to_binary(srfuzz_mut_178.t1.c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))) AS `hex(bitmap_to_binary(hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` LIMIT 1, 100;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT DISTINCT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `hex(hex(bitmap_to_binary(srfuzz_mut_178.t1.c2)))` FROM `srfuzz_mut_178`.`t1`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) SELECT `t1`.`c1`, hex(bitmap_to_binary(`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_n1` AS t1;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(`srfuzz_mut_178`.`t1`.`c1`) AS `hex(srfuzz_mut_178.t1.c1)` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` ORDER BY hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) ASC;
SELECT `t1`.`c1`, hex(bitmap_to_binary(`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` WHERE to_binary('');
SELECT `t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(`srfuzz_mut_178`.`t1`.`c1`)) AS `bitmap_to_string(bitmap_from_binary(srfuzz_mut_178.t1.c1))` FROM `srfuzz_mut_178`.`t1`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) SELECT `t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_n1` AS t1;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(md5(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(md5(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2))))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` GROUP BY `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)));
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(`srfuzz_mut_178`.`t1`.`c2`) AS `bitmap_to_string(srfuzz_mut_178.t1.c2)` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` WHERE `srfuzz_mut_178`.`t1`.`c1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))) AS `bitmap_to_string(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` GROUP BY `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)));
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` WHERE bitmap_to_binary(NULL);
SELECT `srfuzz_mut_178`.`t1`.`c1`, sum(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))) OVER () AS `sum(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))) OVER ()` FROM `srfuzz_mut_178`.`t1`;
SELECT DISTINCT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, rank() OVER (ORDER BY bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) ASC ) AS `rank() OVER (ORDER BY bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2))) ASC )` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1` UNION ALL SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` DESC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_count(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_count(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT DISTINCT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(`srfuzz_mut_178`.`t1`.`c1`) AS `hex(srfuzz_mut_178.t1.c1)` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(`srfuzz_mut_178`.`t1`.`c1`) AS `hex(srfuzz_mut_178.t1.c1)` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `hex(hex(bitmap_to_binary(srfuzz_mut_178.t1.c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` LIMIT 1;
SELECT `srfuzz_mut_178`.`t1`.`c1`, count(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) OVER () AS `count(hex(bitmap_to_binary(c2))) OVER ()` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT json_query(CAST(`srfuzz_mut_178`.`t1`.`c1` AS JSON), '$.a') AS `json_query(CAST(c1 AS JSON), '$.a')`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `hex(hex(bitmap_to_binary(srfuzz_mut_178.t1.c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))) AS `hex(bitmap_to_binary(hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `t1`.`c1`, hex(bitmap_to_binary(`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `hex(hex(bitmap_to_binary(srfuzz_mut_178.t1.c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT sum(`srfuzz_mut_178`.`t1`.`c1`) OVER () AS `sum(c1) OVER ()`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))) AS `hex(bitmap_to_binary(hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))))` FROM `srfuzz_mut_178`.`t1`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) SELECT `t1`.`c1`, hex(bitmap_to_binary(`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_n1` AS t1;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_count(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_count(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` GROUP BY `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`));
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))))) AS `hex(bitmap_to_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2)))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))) AS `hex(bitmap_to_binary(hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))) AS `bitmap_to_string(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2))))` FROM `srfuzz_mut_178`.`t1`;
SELECT DISTINCT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(`srfuzz_mut_178`.`t1`.`c2`) AS `bitmap_to_string(srfuzz_mut_178.t1.c2)` FROM `srfuzz_mut_178`.`t1`;
SELECT `t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2)))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT DISTINCT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2))))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` GROUP BY `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)));
SELECT `t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT `t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1`;
SELECT `t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1` UNION ALL SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1`;
SELECT `t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2)))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_count(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))))) AS `bitmap_to_string(bitmap_from_binary(bitmap_count(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2)))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` WHERE `srfuzz_mut_178`.`t1`.`c1`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) SELECT `t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_n1` AS t1;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(hex(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(md5(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(md5(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(`srfuzz_mut_178`.`t1`.`c1`) AS `hex(srfuzz_mut_178.t1.c1)` FROM `srfuzz_mut_178`.`t1`;
SELECT `t1`.`c1`, hex(bitmap_to_binary(`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1` UNION ALL SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))) AS `hex(bitmap_to_binary(hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(to_binary('')) AS `hex(to_binary(''))` FROM `srfuzz_mut_178`.`t1`;
SELECT `t1`.`c1`, hex(bitmap_to_binary(`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))) AS `hex(bitmap_to_binary(hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))))` FROM `srfuzz_mut_178`.`t1`;
SELECT avg(`srfuzz_mut_178`.`t1`.`c1`) OVER (PARTITION BY hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) ) AS `avg(c1) OVER (PARTITION BY hex(bitmap_to_binary(c2)) )`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `t1`.`c1`, hex(bitmap_to_binary(`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT DISTINCT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT DISTINCT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) SELECT `t1`.`c1`, hex(bitmap_to_binary(`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_n1` AS t1;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(NULL)) AS `hex(bitmap_to_binary(NULL))` FROM `srfuzz_mut_178`.`t1`;
SELECT min(`srfuzz_mut_178`.`t1`.`c1`) OVER (PARTITION BY hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) ) AS `min(c1) OVER (PARTITION BY hex(bitmap_to_binary(c2)) )`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))) AS `hex(bitmap_to_binary(hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))))` FROM `srfuzz_mut_178`.`t1`;
SELECT avg(`srfuzz_mut_178`.`t1`.`c1`) OVER (PARTITION BY hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) ) AS `avg(c1) OVER (PARTITION BY hex(bitmap_to_binary(c2)) )`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` GROUP BY `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`));
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(`srfuzz_mut_178`.`t1`.`c1`) AS `hex(srfuzz_mut_178.t1.c1)` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(to_binary('1234')) AS `hex(to_binary('1234'))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` LIMIT 7, 2;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_count(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_count(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` WHERE 'abc';
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` LIMIT 1;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_count(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))))) AS `bitmap_to_string(bitmap_from_binary(bitmap_count(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2)))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(upper(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(upper(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) SELECT `t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_n1` AS t1;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` DESC NULLS FIRST;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2)))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` LIMIT 0;
SELECT `t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1` UNION ALL SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT `t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1` UNION ALL SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1`;
SELECT `t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1` UNION ALL SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1`;
SELECT `t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1`;
SELECT CAST(`srfuzz_mut_178`.`t1`.`c1` AS JSON)->'$.a' AS `CAST(c1 AS JSON)->'$.a'`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2)))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` WHERE bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`);
SELECT `t1`.`c1`, hex(bitmap_to_binary(`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))) AS `hex(bitmap_to_binary(hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(`srfuzz_mut_178`.`t1`.`c1`) AS `hex(srfuzz_mut_178.t1.c1)` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))) AS `hex(bitmap_to_binary(hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` LIMIT 2;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` GROUP BY `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`));
SELECT DISTINCT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` LIMIT 1, 100;
SELECT `srfuzz_mut_178`.`t1`.`c1`, CAST((hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS JSON)->'$.a' AS `CAST((hex(bitmap_to_binary(c2))) AS JSON)->'$.a'` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))` FROM `srfuzz_mut_178`.`t1`;
SELECT `t1`.`c1`, hex(bitmap_to_binary(`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1` UNION ALL SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(`srfuzz_mut_178`.`t1`.`c1`) AS `hex(srfuzz_mut_178.t1.c1)` FROM `srfuzz_mut_178`.`t1`;
SELECT `t1`.`c1`, hex(bitmap_to_binary(`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1`;
SELECT DISTINCT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` GROUP BY `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)));
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` LIMIT 5;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2))))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2)))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_count(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_count(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(lower(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(lower(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(`srfuzz_mut_178`.`t1`.`c1`)) AS `bitmap_to_string(bitmap_from_binary(srfuzz_mut_178.t1.c1))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2))))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2))))))` FROM `srfuzz_mut_178`.`t1`;
SELECT DISTINCT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, min(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))) OVER () AS `min(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))) OVER ()` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2))))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2))))))` FROM `srfuzz_mut_178`.`t1`;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(`srfuzz_mut_178`.`t1`.`c1`) AS `hex(srfuzz_mut_178.t1.c1)` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, CAST((hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS JSON)->'k' AS `CAST((hex(bitmap_to_binary(c2))) AS JSON)->'k'` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` GROUP BY `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, rank() OVER (ORDER BY hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) ASC ) AS `rank() OVER (ORDER BY hex(bitmap_to_binary(c2)) ASC )` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary('')) AS `hex(bitmap_to_binary(''))` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT `t1`.`c1`, hex(bitmap_to_binary(`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  ORDER BY `t1`.`c1` ASC;
SELECT rank() OVER (ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC ) AS `rank() OVER (ORDER BY c1 ASC )`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))) AS `hex(bitmap_to_binary(hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))))` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, CAST((hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS DECIMAL128(38,38)) AS `CAST((hex(bitmap_to_binary(c2))) AS DECIMAL128(38,38))` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, count(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) OVER () AS `count(hex(bitmap_to_binary(c2))) OVER ()` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))) AS `hex(bitmap_to_binary(hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))))` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))) AS `hex(bitmap_to_binary(hex(bitmap_to_binary(srfuzz_mut_178.t1.c2))))` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT CAST(`srfuzz_mut_178`.`t1`.`c1` AS JSON)->'$.a' AS `CAST(c1 AS JSON)->'$.a'`, hex(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) SELECT `t1`.`c1`, hex(bitmap_to_binary(`t1`.`c2`)) AS `hex(bitmap_to_binary(c2))` FROM `srfuzz_n1` AS t1 ORDER BY `t1`.`c1` ASC;
SELECT `t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1` UNION ALL SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1` ORDER BY `t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2)))` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` GROUP BY `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT `t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1` UNION ALL SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1` ORDER BY `t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` WHERE bitmap_to_binary(NULL) ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1` UNION ALL SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1` ORDER BY `t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2)))` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1`;
SELECT `t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  ORDER BY `t1`.`c1` ASC;
SELECT `t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM (SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1` UNION ALL SELECT `srfuzz_mut_178`.`t1`.`c1`, `srfuzz_mut_178`.`t1`.`c2` FROM `srfuzz_mut_178`.`t1`) `t1` ORDER BY `t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(bitmap_to_string(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2))))))` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, CAST((bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`)))) AS JSON)->'k' AS `CAST((bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))) AS JSON)->'k'` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT avg(`srfuzz_mut_178`.`t1`.`c1`) OVER () AS `avg(c1) OVER ()`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(c2)))` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT `srfuzz_mut_178`.`t1`.`c1`, bitmap_to_string(bitmap_from_binary(bitmap_to_binary(`srfuzz_mut_178`.`t1`.`c2`))) AS `bitmap_to_string(bitmap_from_binary(bitmap_to_binary(srfuzz_mut_178.t1.c2)))` FROM `srfuzz_mut_178`.`t1` ORDER BY `srfuzz_mut_178`.`t1`.`c1` ASC;
SELECT bitmap_from_binary(to_binary(-9223372036854775808)) AS `bitmap_from_binary(to_binary(-9223372036854775808))`;
SELECT bitmap_from_binary(to_binary('1234')) AS `bitmap_from_binary(to_binary('1234'))`;
SELECT bitmap_from_binary(to_binary('1234')) AS `bitmap_from_binary(to_binary('1234'))`;
SELECT bitmap_from_binary(to_binary('1234')) AS `bitmap_from_binary(to_binary('1234'))`;
SELECT bitmap_from_binary(lower('1234')) AS `bitmap_from_binary(lower('1234'))`;
SELECT bitmap_from_binary(hll_cardinality('1234')) AS `bitmap_from_binary(hll_cardinality('1234'))`;
SELECT bitmap_from_binary(to_binary('%')) AS `bitmap_from_binary(to_binary('%'))`;
SELECT bitmap_from_binary(to_binary(9223372036854775807)) AS `bitmap_from_binary(to_binary(9223372036854775807))`;
SELECT bitmap_from_binary(to_binary('abc')) AS `bitmap_from_binary(to_binary('abc'))`;
SELECT bitmap_from_binary(hex('1234')) AS `bitmap_from_binary(hex('1234'))`;
SELECT bitmap_from_binary(length('1234')) AS `bitmap_from_binary(length('1234'))`;
SELECT bitmap_from_binary(unhex('1234')) AS `bitmap_from_binary(unhex('1234'))`;
SELECT bitmap_from_binary('1234') AS `bitmap_from_binary('1234')`;
SELECT bitmap_from_binary(md5('1234')) AS `bitmap_from_binary(md5('1234'))`;
SELECT bitmap_from_binary(to_binary(FALSE)) AS `bitmap_from_binary(to_binary(FALSE))`;
SELECT bitmap_from_binary(upper('1234')) AS `bitmap_from_binary(upper('1234'))`;
SELECT bitmap_from_binary(to_binary('1234')) AS `bitmap_from_binary(to_binary('1234'))` LIMIT 0;
SELECT bitmap_from_binary(char_length('')) AS `bitmap_from_binary(char_length(''))`;
SELECT bitmap_from_binary(char_length('')) AS `bitmap_from_binary(char_length(''))`;
SELECT bitmap_from_binary(to_binary(CAST(NULL AS JSON))) AS `bitmap_from_binary(to_binary(CAST(NULL AS JSON)))`;
SELECT bitmap_from_binary(upper('')) AS `bitmap_from_binary(upper(''))`;
SELECT bitmap_from_binary(to_binary('\\')) AS `bitmap_from_binary(to_binary('\\'))`;
SELECT bitmap_from_binary(to_binary('')) AS `bitmap_from_binary(to_binary(''))` WHERE '1234';
SELECT bitmap_from_binary(to_binary('')) AS `bitmap_from_binary(to_binary(''))` WHERE '1234';
SELECT bitmap_from_binary(to_binary(9223372036854775807)) AS `bitmap_from_binary(to_binary(9223372036854775807))`;
SELECT bitmap_from_binary('') AS `bitmap_from_binary('')`;
SELECT bitmap_from_binary(to_binary('')) AS `bitmap_from_binary(to_binary(''))`;
SELECT bitmap_from_binary(to_binary(FALSE)) AS `bitmap_from_binary(to_binary(FALSE))`;
SELECT bitmap_from_binary(to_binary('1234')) AS `bitmap_from_binary(to_binary('1234'))`;
SELECT bitmap_from_binary(to_binary('')) AS `bitmap_from_binary(to_binary(''))` WHERE to_binary('');
SELECT bitmap_from_binary(upper('')) AS `bitmap_from_binary(upper(''))`;
SELECT bitmap_from_binary(to_binary(to_binary(''))) AS `bitmap_from_binary(to_binary(to_binary('')))`;
SELECT bitmap_from_binary(to_binary(to_binary('1234'))) AS `bitmap_from_binary(to_binary(to_binary('1234')))`;
SELECT bitmap_from_binary(9223372036854775807) AS `bitmap_from_binary(9223372036854775807)`;
SELECT bitmap_from_binary(-1.0E308) AS `bitmap_from_binary(-1.0E308)`;
SELECT bitmap_from_binary(-2147483648) AS `bitmap_from_binary(-2147483648)`;
SELECT bitmap_from_binary(NULL) AS `bitmap_from_binary(NULL)`;
SELECT bitmap_from_binary(NULL) AS `bitmap_from_binary(NULL)`;
SELECT bitmap_from_binary(NULL) AS `bitmap_from_binary(NULL)`;
SELECT bitmap_from_binary('0') AS `bitmap_from_binary('0')`;
SELECT bitmap_from_binary(array_length(NULL)) AS `bitmap_from_binary(array_length(NULL))`;
SELECT bitmap_from_binary(CAST(NULL AS LARGEINT)) AS `bitmap_from_binary(CAST(NULL AS LARGEINT))`;
SELECT bitmap_from_binary(NULL) AS `bitmap_from_binary(NULL)` WHERE '';
SELECT bitmap_from_binary(-9223372036854775808) AS `bitmap_from_binary(-9223372036854775808)`;
SELECT bitmap_from_binary('9999-12-31 23:59:59') AS `bitmap_from_binary('9999-12-31 23:59:59')`;
SELECT bitmap_from_binary(2147483647) AS `bitmap_from_binary(2147483647)`;
SELECT bitmap_from_binary(1) AS `bitmap_from_binary(1)`;
SELECT bitmap_from_binary(0) AS `bitmap_from_binary(0)`;
SELECT bitmap_from_binary(NULL) AS `bitmap_from_binary(NULL)`;
SELECT bitmap_from_binary(NULL) AS `bitmap_from_binary(NULL)` LIMIT 100;
SELECT bitmap_to_binary(NULL) AS `bitmap_to_binary(NULL)`;
SELECT bitmap_to_binary(NULL) AS `bitmap_to_binary(NULL)` LIMIT 0;
SELECT bitmap_to_binary(NULL) AS `bitmap_to_binary(NULL)` LIMIT 1, 2;
SELECT bitmap_to_binary(NULL) AS `bitmap_to_binary(NULL)` ORDER BY bitmap_to_binary(NULL) ASC;
SELECT bitmap_to_binary(NULL) AS `bitmap_to_binary(NULL)` GROUP BY bitmap_to_binary(NULL);
SELECT bitmap_to_binary(bitmap_from_binary(NULL)) AS `bitmap_to_binary(bitmap_from_binary(NULL))`;
SELECT bitmap_to_binary('') AS `bitmap_to_binary('')`;
SELECT bitmap_to_binary(NULL) AS `bitmap_to_binary(NULL)` LIMIT 0;
SELECT bitmap_to_binary(NULL) AS `bitmap_to_binary(NULL)` WHERE to_binary('1234');
SELECT bitmap_to_binary(NULL) AS `bitmap_to_binary(NULL)` ORDER BY bitmap_to_binary(NULL) ASC NULLS LAST;
SELECT bitmap_to_binary('0000-00-00') AS `bitmap_to_binary('0000-00-00')`;
SELECT bitmap_to_binary(NULL) AS `bitmap_to_binary(NULL)`;
SELECT bitmap_to_binary(bitmap_from_string('abc')) AS `bitmap_to_binary(bitmap_from_string('abc'))` WHERE '1234';
SELECT bitmap_to_binary(bitmap_from_string('abc')) AS `bitmap_to_binary(bitmap_from_string('abc'))` ORDER BY bitmap_to_binary(bitmap_from_string('abc')) ASC;
SELECT bitmap_to_binary(bitmap_from_string('abc')) AS `bitmap_to_binary(bitmap_from_string('abc'))`;
SELECT bitmap_to_binary(bitmap_from_string('\\')) AS `bitmap_to_binary(bitmap_from_string('\\'))`;
SELECT bitmap_to_binary(lower('abc')) AS `bitmap_to_binary(lower('abc'))`;
SELECT bitmap_to_binary(bitmap_from_string(NULL)) AS `bitmap_to_binary(bitmap_from_string(NULL))`;
SELECT bitmap_to_binary(bitmap_from_string('abc')) AS `bitmap_to_binary(bitmap_from_string('abc'))`;
SELECT bitmap_to_binary(unhex('abc')) AS `bitmap_to_binary(unhex('abc'))`;
SELECT bitmap_to_binary(bitmap_from_string('abc')) AS `bitmap_to_binary(bitmap_from_string('abc'))` GROUP BY bitmap_to_binary(bitmap_from_string('abc'));
SELECT bitmap_to_binary(bitmap_from_string('%')) AS `bitmap_to_binary(bitmap_from_string('%'))`;
SELECT bitmap_to_binary(bitmap_from_string('abc')) AS `bitmap_to_binary(bitmap_from_string('abc'))` GROUP BY bitmap_to_binary(bitmap_from_string('abc'));
SELECT bitmap_to_binary(bitmap_from_string('abc')) AS `bitmap_to_binary(bitmap_from_string('abc'))` GROUP BY bitmap_to_binary(bitmap_from_string('abc'));
SELECT bitmap_to_binary(bitmap_from_string('abc')) AS `bitmap_to_binary(bitmap_from_string('abc'))` ORDER BY bitmap_to_binary(bitmap_from_string('abc')) DESC;
SELECT bitmap_to_binary(bitmap_from_string('abc')) AS `bitmap_to_binary(bitmap_from_string('abc'))`;
SELECT bitmap_to_binary(bitmap_from_string('abc')) AS `bitmap_to_binary(bitmap_from_string('abc'))` ORDER BY bitmap_to_binary(bitmap_from_string('abc')) DESC;
SELECT bitmap_to_binary(bitmap_from_string(1)) AS `bitmap_to_binary(bitmap_from_string(1))`;
SELECT bitmap_to_binary(bitmap_from_string('abc')) AS `bitmap_to_binary(bitmap_from_string('abc'))`;
SELECT bitmap_to_binary(lower('abc')) AS `bitmap_to_binary(lower('abc'))`;
SELECT bitmap_to_binary(hex('abc')) AS `bitmap_to_binary(hex('abc'))`;
SELECT bitmap_to_binary(lower('abc')) AS `bitmap_to_binary(lower('abc'))`;
SELECT bitmap_to_binary('') AS `bitmap_to_binary('')`;