SELECT count(1) AS `count(1)` FROM `_statistics_`.`query_history`;
SELECT count(1) AS `count(1)` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b`;
SELECT count(1) AS `count(1)` FROM `srfuzz_mut_994`.`t1`;
SELECT sleep(2) AS `sleep(2)`;
SELECT (count(1)) > 0 AS `(count(1)) > 0` FROM `_statistics_`.`query_history` WHERE `_statistics_`.`query_history`.`sql_digest` LIKE '%count%';
SELECT count(1) AS `count(1)` FROM `_statistics_`.`query_history`;
SELECT count(1) AS `count(1)` FROM (SELECT `_statistics_`.`query_history`.`dt`, `_statistics_`.`query_history`.`frontend`, `_statistics_`.`query_history`.`db`, `_statistics_`.`query_history`.`sql_digest`, `_statistics_`.`query_history`.`sql`, `_statistics_`.`query_history`.`plan`, `_statistics_`.`query_history`.`plan_costs`, `_statistics_`.`query_history`.`query_ms`, `_statistics_`.`query_history`.`other` FROM `_statistics_`.`query_history` INTERSECT SELECT `_statistics_`.`query_history`.`dt`, `_statistics_`.`query_history`.`frontend`, `_statistics_`.`query_history`.`db`, `_statistics_`.`query_history`.`sql_digest`, `_statistics_`.`query_history`.`sql`, `_statistics_`.`query_history`.`plan`, `_statistics_`.`query_history`.`plan_costs`, `_statistics_`.`query_history`.`query_ms`, `_statistics_`.`query_history`.`other` FROM `_statistics_`.`query_history`) `query_history`;
SELECT count('0000-00-00') AS `count('0000-00-00')` FROM `_statistics_`.`query_history`;
SELECT count('0') AS `count('0')` FROM `_statistics_`.`query_history`;
SELECT count(1) AS `count(1)` FROM `_statistics_`.`query_history`;
SELECT count(0.0) AS `count(0.0)` FROM `_statistics_`.`query_history`;
SELECT count(1) AS `count(1)` FROM `_statistics_`.`query_history`;
SELECT count(-1.0E308) AS `count(-1.0E308)` FROM `_statistics_`.`query_history`;
SELECT count(1) AS `count(1)` FROM (SELECT `_statistics_`.`query_history`.`dt`, `_statistics_`.`query_history`.`frontend`, `_statistics_`.`query_history`.`db`, `_statistics_`.`query_history`.`sql_digest`, `_statistics_`.`query_history`.`sql`, `_statistics_`.`query_history`.`plan`, `_statistics_`.`query_history`.`plan_costs`, `_statistics_`.`query_history`.`query_ms`, `_statistics_`.`query_history`.`other` FROM `_statistics_`.`query_history` UNION ALL SELECT `_statistics_`.`query_history`.`dt`, `_statistics_`.`query_history`.`frontend`, `_statistics_`.`query_history`.`db`, `_statistics_`.`query_history`.`sql_digest`, `_statistics_`.`query_history`.`sql`, `_statistics_`.`query_history`.`plan`, `_statistics_`.`query_history`.`plan_costs`, `_statistics_`.`query_history`.`query_ms`, `_statistics_`.`query_history`.`other` FROM `_statistics_`.`query_history`) `query_history`;
SELECT count(1) AS `count(1)` FROM `_statistics_`.`query_history`;
SELECT count(1) AS `count(1)` FROM `_statistics_`.`query_history` GROUP BY `_statistics_`.`query_history`.`sql_digest`;
SELECT count('9999-12-31 23:59:59') AS `count('9999-12-31 23:59:59')` FROM `_statistics_`.`query_history`;
SELECT count(1) AS `count(1)` FROM `_statistics_`.`query_history`;
SELECT count(CAST(NULL AS JSON)) AS `count(CAST(NULL AS JSON))` FROM `_statistics_`.`query_history`;
SELECT count(1) AS `count(1)` FROM (SELECT `_statistics_`.`query_history`.`dt`, `_statistics_`.`query_history`.`frontend`, `_statistics_`.`query_history`.`db`, `_statistics_`.`query_history`.`sql_digest`, `_statistics_`.`query_history`.`sql`, `_statistics_`.`query_history`.`plan`, `_statistics_`.`query_history`.`plan_costs`, `_statistics_`.`query_history`.`query_ms`, `_statistics_`.`query_history`.`other` FROM `_statistics_`.`query_history` EXCEPT SELECT `_statistics_`.`query_history`.`dt`, `_statistics_`.`query_history`.`frontend`, `_statistics_`.`query_history`.`db`, `_statistics_`.`query_history`.`sql_digest`, `_statistics_`.`query_history`.`sql`, `_statistics_`.`query_history`.`plan`, `_statistics_`.`query_history`.`plan_costs`, `_statistics_`.`query_history`.`query_ms`, `_statistics_`.`query_history`.`other` FROM `_statistics_`.`query_history`) `query_history`;
SELECT count(1) AS `count(1)` FROM (SELECT `_statistics_`.`query_history`.`dt`, `_statistics_`.`query_history`.`frontend`, `_statistics_`.`query_history`.`db`, `_statistics_`.`query_history`.`sql_digest`, `_statistics_`.`query_history`.`sql`, `_statistics_`.`query_history`.`plan`, `_statistics_`.`query_history`.`plan_costs`, `_statistics_`.`query_history`.`query_ms`, `_statistics_`.`query_history`.`other` FROM `_statistics_`.`query_history` EXCEPT SELECT `_statistics_`.`query_history`.`dt`, `_statistics_`.`query_history`.`frontend`, `_statistics_`.`query_history`.`db`, `_statistics_`.`query_history`.`sql_digest`, `_statistics_`.`query_history`.`sql`, `_statistics_`.`query_history`.`plan`, `_statistics_`.`query_history`.`plan_costs`, `_statistics_`.`query_history`.`query_ms`, `_statistics_`.`query_history`.`other` FROM `_statistics_`.`query_history`) `query_history`;
SELECT count(1) AS `count(1)` FROM (SELECT `_statistics_`.`query_history`.`dt`, `_statistics_`.`query_history`.`frontend`, `_statistics_`.`query_history`.`db`, `_statistics_`.`query_history`.`sql_digest`, `_statistics_`.`query_history`.`sql`, `_statistics_`.`query_history`.`plan`, `_statistics_`.`query_history`.`plan_costs`, `_statistics_`.`query_history`.`query_ms`, `_statistics_`.`query_history`.`other` FROM `_statistics_`.`query_history`) `query_history` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT count(1) AS `count(1)` FROM `_statistics_`.`query_history` LIMIT 1, 5;
SELECT count(1) AS `count(1)` FROM (SELECT `_statistics_`.`query_history`.`dt`, `_statistics_`.`query_history`.`frontend`, `_statistics_`.`query_history`.`db`, `_statistics_`.`query_history`.`sql_digest`, `_statistics_`.`query_history`.`sql`, `_statistics_`.`query_history`.`plan`, `_statistics_`.`query_history`.`plan_costs`, `_statistics_`.`query_history`.`query_ms`, `_statistics_`.`query_history`.`other` FROM `_statistics_`.`query_history` UNION SELECT `_statistics_`.`query_history`.`dt`, `_statistics_`.`query_history`.`frontend`, `_statistics_`.`query_history`.`db`, `_statistics_`.`query_history`.`sql_digest`, `_statistics_`.`query_history`.`sql`, `_statistics_`.`query_history`.`plan`, `_statistics_`.`query_history`.`plan_costs`, `_statistics_`.`query_history`.`query_ms`, `_statistics_`.`query_history`.`other` FROM `_statistics_`.`query_history`) `query_history`;
SELECT count(0.0) AS `count(0.0)` FROM `_statistics_`.`query_history`;
SELECT count(1) AS `count(1)` FROM `_statistics_`.`query_history`;
WITH `srfuzz_n1` AS (SELECT `_statistics_`.`query_history`.`dt`, `_statistics_`.`query_history`.`frontend`, `_statistics_`.`query_history`.`db`, `_statistics_`.`query_history`.`sql_digest`, `_statistics_`.`query_history`.`sql`, `_statistics_`.`query_history`.`plan`, `_statistics_`.`query_history`.`plan_costs`, `_statistics_`.`query_history`.`query_ms`, `_statistics_`.`query_history`.`other` FROM `_statistics_`.`query_history`) SELECT count(1) AS `count(1)` FROM `srfuzz_n1` AS query_history;
SELECT count(CAST(NULL AS JSON)) AS `count(CAST(NULL AS JSON))` FROM `_statistics_`.`query_history`;
SELECT count(1) AS `count(1)` FROM `_statistics_`.`query_history`;
SELECT count(1) AS `count(1)` FROM (SELECT `_statistics_`.`query_history`.`dt`, `_statistics_`.`query_history`.`frontend`, `_statistics_`.`query_history`.`db`, `_statistics_`.`query_history`.`sql_digest`, `_statistics_`.`query_history`.`sql`, `_statistics_`.`query_history`.`plan`, `_statistics_`.`query_history`.`plan_costs`, `_statistics_`.`query_history`.`query_ms`, `_statistics_`.`query_history`.`other` FROM `_statistics_`.`query_history` UNION ALL SELECT `_statistics_`.`query_history`.`dt`, `_statistics_`.`query_history`.`frontend`, `_statistics_`.`query_history`.`db`, `_statistics_`.`query_history`.`sql_digest`, `_statistics_`.`query_history`.`sql`, `_statistics_`.`query_history`.`plan`, `_statistics_`.`query_history`.`plan_costs`, `_statistics_`.`query_history`.`query_ms`, `_statistics_`.`query_history`.`other` FROM `_statistics_`.`query_history`) `query_history`;
SELECT count(1) AS `count(1)` FROM `_statistics_`.`query_history` LIMIT 100;
SELECT count(1) AS `count(1)` FROM (SELECT `_statistics_`.`query_history`.`dt`, `_statistics_`.`query_history`.`frontend`, `_statistics_`.`query_history`.`db`, `_statistics_`.`query_history`.`sql_digest`, `_statistics_`.`query_history`.`sql`, `_statistics_`.`query_history`.`plan`, `_statistics_`.`query_history`.`plan_costs`, `_statistics_`.`query_history`.`query_ms`, `_statistics_`.`query_history`.`other` FROM `_statistics_`.`query_history`) `query_history`;
SELECT count(TRUE) AS `count(TRUE)` FROM `_statistics_`.`query_history`;
SELECT count(1) AS `count(1)` FROM (SELECT `srfuzz_mut_994`.`a`.`k1`, `srfuzz_mut_994`.`a`.`k2`, `srfuzz_mut_994`.`a`.`k3`, `srfuzz_mut_994`.`b`.`k1`, `srfuzz_mut_994`.`b`.`k2`, `srfuzz_mut_994`.`b`.`k3` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b`  UNION ALL SELECT `srfuzz_mut_994`.`a`.`k1`, `srfuzz_mut_994`.`a`.`k2`, `srfuzz_mut_994`.`a`.`k3`, `srfuzz_mut_994`.`b`.`k1`, `srfuzz_mut_994`.`b`.`k2`, `srfuzz_mut_994`.`b`.`k3` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b` ) `srfuzz_n1`;
SELECT count(1) AS `count(1)` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b`;
SELECT count(1) AS `count(1)` FROM (SELECT `srfuzz_mut_994`.`a`.`k1`, `srfuzz_mut_994`.`a`.`k2`, `srfuzz_mut_994`.`a`.`k3` FROM `srfuzz_mut_994`.`t1` AS `a` UNION ALL SELECT `srfuzz_mut_994`.`a`.`k1`, `srfuzz_mut_994`.`a`.`k2`, `srfuzz_mut_994`.`a`.`k3` FROM `srfuzz_mut_994`.`t1` AS `a`) `a` , `srfuzz_mut_994`.`t1` AS `b`;
SELECT count(0.0) AS `count(0.0)` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b`;
SELECT count(1) AS `count(1)` FROM (SELECT `srfuzz_mut_994`.`a`.`k1`, `srfuzz_mut_994`.`a`.`k2`, `srfuzz_mut_994`.`a`.`k3`, `srfuzz_mut_994`.`b`.`k1`, `srfuzz_mut_994`.`b`.`k2`, `srfuzz_mut_994`.`b`.`k3` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b`  UNION ALL SELECT `srfuzz_mut_994`.`a`.`k1`, `srfuzz_mut_994`.`a`.`k2`, `srfuzz_mut_994`.`a`.`k3`, `srfuzz_mut_994`.`b`.`k1`, `srfuzz_mut_994`.`b`.`k2`, `srfuzz_mut_994`.`b`.`k3` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b` ) `srfuzz_n1`;
SELECT count(1) AS `count(1)` FROM (SELECT `srfuzz_mut_994`.`a`.`k1`, `srfuzz_mut_994`.`a`.`k2`, `srfuzz_mut_994`.`a`.`k3`, `srfuzz_mut_994`.`b`.`k1`, `srfuzz_mut_994`.`b`.`k2`, `srfuzz_mut_994`.`b`.`k3` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b`  INTERSECT SELECT `srfuzz_mut_994`.`a`.`k1`, `srfuzz_mut_994`.`a`.`k2`, `srfuzz_mut_994`.`a`.`k3`, `srfuzz_mut_994`.`b`.`k1`, `srfuzz_mut_994`.`b`.`k2`, `srfuzz_mut_994`.`b`.`k3` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b` ) `srfuzz_n1`;
SELECT count(1) AS `count(1)` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b`;
SELECT count(1) AS `count(1)` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_994`.`a`.`k1`, `srfuzz_mut_994`.`a`.`k2`, `srfuzz_mut_994`.`a`.`k3` FROM `srfuzz_mut_994`.`t1` AS `a`) SELECT count(1) AS `count(1)` FROM `srfuzz_n1` AS a , `srfuzz_mut_994`.`t1` AS `b`;
SELECT count(1) AS `count(1)` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b`  LIMIT 7, 1;
SELECT count(1) AS `count(1)` FROM (SELECT `srfuzz_mut_994`.`a`.`k1`, `srfuzz_mut_994`.`a`.`k2`, `srfuzz_mut_994`.`a`.`k3`, `srfuzz_mut_994`.`b`.`k1`, `srfuzz_mut_994`.`b`.`k2`, `srfuzz_mut_994`.`b`.`k3` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b` ) `srfuzz_n1` LEFT OUTER JOIN (SELECT `srfuzz_mut_994`.`a`.`k1`, `srfuzz_mut_994`.`a`.`k2`, `srfuzz_mut_994`.`a`.`k3`, `srfuzz_mut_994`.`b`.`k1`, `srfuzz_mut_994`.`b`.`k2`, `srfuzz_mut_994`.`b`.`k3` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b` ) `srfuzz_n2` ON 1 = 1;
SELECT json_query(CAST((count(1)) AS JSON), '$.a') AS `json_query(CAST((count(1)) AS JSON), '$.a')` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b`;
SELECT count(-9223372036854775808) AS `count(-9223372036854775808)` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b`;
SELECT count(1) AS `count(1)` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b`;
SELECT count(1) AS `count(1)` FROM (SELECT `srfuzz_mut_994`.`a`.`k1`, `srfuzz_mut_994`.`a`.`k2`, `srfuzz_mut_994`.`a`.`k3`, `srfuzz_mut_994`.`b`.`k1`, `srfuzz_mut_994`.`b`.`k2`, `srfuzz_mut_994`.`b`.`k3` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b`  EXCEPT SELECT `srfuzz_mut_994`.`a`.`k1`, `srfuzz_mut_994`.`a`.`k2`, `srfuzz_mut_994`.`a`.`k3`, `srfuzz_mut_994`.`b`.`k1`, `srfuzz_mut_994`.`b`.`k2`, `srfuzz_mut_994`.`b`.`k3` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b` ) `srfuzz_n1`;
SELECT count('%') AS `count('%')` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b`;
SELECT count(1) AS `count(1)` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b`  HAVING (count(*)) < 10;
SELECT count(1) AS `count(1)` FROM (SELECT `srfuzz_mut_994`.`a`.`k1`, `srfuzz_mut_994`.`a`.`k2`, `srfuzz_mut_994`.`a`.`k3`, `srfuzz_mut_994`.`b`.`k1`, `srfuzz_mut_994`.`b`.`k2`, `srfuzz_mut_994`.`b`.`k3` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b` ) `srfuzz_n1` , LATERAL generate_series(1,3,1) srfuzz_n2(`e`);
SELECT count(1) AS `count(1)` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b`  HAVING (count(*)) >= 2;
SELECT count(CAST(1 AS JSON)->'$') AS `count(CAST(1 AS JSON)->'$')` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b`;
SELECT count(-9223372036854775808) AS `count(-9223372036854775808)` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b`;
SELECT count('0') AS `count('0')` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b`;
SELECT count(1.0E308) AS `count(1.0E308)` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b`;
SELECT count(1) AS `count(1)` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b`;
SELECT count(TRUE) AS `count(TRUE)` FROM `srfuzz_mut_994`.`t1` AS `a` , `srfuzz_mut_994`.`t1` AS `b`;
SELECT count(1) AS `count(1)` FROM `srfuzz_mut_994`.`t1` AS `a` , (SELECT `srfuzz_mut_994`.`b`.`k1`, `srfuzz_mut_994`.`b`.`k2`, `srfuzz_mut_994`.`b`.`k3` FROM `srfuzz_mut_994`.`t1` AS `b` INTERSECT SELECT `srfuzz_mut_994`.`b`.`k1`, `srfuzz_mut_994`.`b`.`k2`, `srfuzz_mut_994`.`b`.`k3` FROM `srfuzz_mut_994`.`t1` AS `b`) `b`;
SELECT count(0.0) AS `count(0.0)` FROM `srfuzz_mut_994`.`t1`;
SELECT count('9999-12-31 23:59:59') AS `count('9999-12-31 23:59:59')` FROM `srfuzz_mut_994`.`t1`;
SELECT count(1) AS `count(1)` FROM `srfuzz_mut_994`.`t1`;
SELECT count(CAST(1 AS JSON)->'$') AS `count(CAST(1 AS JSON)->'$')` FROM `srfuzz_mut_994`.`t1`;
SELECT count(1) AS `count(1)` FROM `srfuzz_mut_994`.`t1`;
SELECT count(1) AS `count(1)` FROM `srfuzz_mut_994`.`t1` ORDER BY count(1) ASC;
SELECT count(0.0) AS `count(0.0)` FROM `srfuzz_mut_994`.`t1`;
SELECT count(1) AS `count(1)` FROM `srfuzz_mut_994`.`t1`;
SELECT count(NULL) AS `count(NULL)` FROM `srfuzz_mut_994`.`t1`;
SELECT count(1) AS `count(1)` FROM `srfuzz_mut_994`.`t1`;
SELECT count(get_json_string(CAST(1 AS JSON), '$.a')) AS `count(get_json_string(CAST(1 AS JSON), '$.a'))` FROM `srfuzz_mut_994`.`t1`;
SELECT count(1) AS `count(1)` FROM (SELECT `srfuzz_mut_994`.`t1`.`k1`, `srfuzz_mut_994`.`t1`.`k2`, `srfuzz_mut_994`.`t1`.`k3` FROM `srfuzz_mut_994`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT count(1) AS `count(1)` FROM `srfuzz_mut_994`.`t1` ORDER BY count(1) DESC;
SELECT count(1) AS `count(1)` FROM `srfuzz_mut_994`.`t1`;
SELECT count(-2147483648) AS `count(-2147483648)` FROM `srfuzz_mut_994`.`t1`;
SELECT count(1) AS `count(1)` FROM `srfuzz_mut_994`.`t1` HAVING (count(*)) > 1;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_994`.`t1`.`k1`, `srfuzz_mut_994`.`t1`.`k2`, `srfuzz_mut_994`.`t1`.`k3` FROM `srfuzz_mut_994`.`t1`) SELECT count(1) AS `count(1)` FROM `srfuzz_n1` AS t1;
SELECT count(1.0E308) AS `count(1.0E308)` FROM `srfuzz_mut_994`.`t1`;
SELECT count(1) AS `count(1)` FROM `srfuzz_mut_994`.`t1`;
SELECT count(1) AS `count(1)` FROM (SELECT `srfuzz_mut_994`.`t1`.`k1`, `srfuzz_mut_994`.`t1`.`k2`, `srfuzz_mut_994`.`t1`.`k3` FROM `srfuzz_mut_994`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT count(1) AS `count(1)` FROM `srfuzz_mut_994`.`t1` HAVING (count(*)) > 1;
SELECT count(1) AS `count(1)` FROM (SELECT `srfuzz_mut_994`.`t1`.`k1`, `srfuzz_mut_994`.`t1`.`k2`, `srfuzz_mut_994`.`t1`.`k3` FROM `srfuzz_mut_994`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT count(1) AS `count(1)` FROM `srfuzz_mut_994`.`t1` HAVING (count(*)) >= 2;
SELECT count(1) AS `count(1)` FROM `srfuzz_mut_994`.`t1` HAVING (count(*)) > 1;
SELECT count(1.0E308) AS `count(1.0E308)` FROM `srfuzz_mut_994`.`t1`;
SELECT count(1) AS `count(1)` FROM `srfuzz_mut_994`.`t1`;
SELECT count(0) AS `count(0)` FROM `srfuzz_mut_994`.`t1`;
SELECT count('') AS `count('')` FROM `srfuzz_mut_994`.`t1`;
SELECT count(2147483647) AS `count(2147483647)` FROM `srfuzz_mut_994`.`t1`;
SELECT sleep(0.0) AS `sleep(0.0)`;
SELECT sleep(2) AS `sleep(2)`;
SELECT sleep(2) AS `sleep(2)`;
SELECT sleep(2) AS `sleep(2)`;
SELECT sleep(FALSE) AS `sleep(FALSE)`;
SELECT CAST((sleep(2)) AS MAP<VARCHAR(16),MAP<INT,ARRAY<JSON>>>) AS `CAST((sleep(2)) AS MAP<VARCHAR(16),MAP<INT,ARRAY<JSON>>>)`;
SELECT sleep(2) AS `sleep(2)`;
SELECT json_length(CAST((sleep(2)) AS JSON)) AS `json_length(CAST((sleep(2)) AS JSON))`;
SELECT sleep('%count%') AS `sleep('%count%')`;
SELECT sleep(2) AS `sleep(2)`;
SELECT sleep('0000-00-00') AS `sleep('0000-00-00')`;
SELECT sleep(0.0) AS `sleep(0.0)`;
SELECT avg(sleep(2)) OVER () AS `avg(sleep(2)) OVER ()`;
SELECT sleep(CAST(2 AS TINYINT)) AS `sleep(CAST(2 AS TINYINT))`;
SELECT sleep(2) AS `sleep(2)`;
SELECT sleep(2) AS `sleep(2)`;
SELECT sleep(2) AS `sleep(2)` GROUP BY sleep(2);
SELECT sleep(2) AS `sleep(2)` GROUP BY sleep(2);
SELECT sleep(2) AS `sleep(2)`;
SELECT sleep(2147483647) AS `sleep(2147483647)`;
SELECT sleep(2) AS `sleep(2)`;
SELECT sleep(-9223372036854775808) AS `sleep(-9223372036854775808)`;
SELECT sleep(FALSE) AS `sleep(FALSE)`;
SELECT sleep(2) AS `sleep(2)`;
SELECT count(sleep(2)) OVER () AS `count(sleep(2)) OVER ()`;
SELECT sleep(2) AS `sleep(2)` GROUP BY sleep(2);
SELECT sleep(2) AS `sleep(2)`;
SELECT sleep(9223372036854775807) AS `sleep(9223372036854775807)`;
SELECT sleep(2) AS `sleep(2)` GROUP BY sleep(2);
SELECT sleep(2) AS `sleep(2)`;
SELECT sleep('%') AS `sleep('%')`;
SELECT sleep('1970-01-01') AS `sleep('1970-01-01')`;
SELECT CAST((sleep(2)) AS VARBINARY) AS `CAST((sleep(2)) AS VARBINARY)`;
SELECT (count(1)) > 0 AS `(count(1)) > 0` FROM `_statistics_`.`query_history` WHERE `_statistics_`.`query_history`.`sql_digest` LIKE '%count%';
SELECT '%count%' > 0 AS `'%count%' > 0` FROM `_statistics_`.`query_history` WHERE `_statistics_`.`query_history`.`sql_digest` LIKE '%count%';
SELECT (count(1)) > 0 AS `(count(1)) > 0` FROM `_statistics_`.`query_history`;
SELECT (count(1)) > 0 AS `(count(1)) > 0` FROM `_statistics_`.`query_history`;
SELECT (count(1)) > 0 AS `(count(1)) > 0` FROM `_statistics_`.`query_history` WHERE `_statistics_`.`query_history`.`sql_digest` LIKE '%count%' HAVING (count(*)) > 1;
SELECT (exp(1)) > 0 AS `(exp(1)) > 0` FROM `_statistics_`.`query_history` WHERE `_statistics_`.`query_history`.`sql_digest` LIKE '%count%';
SELECT (count(1)) > 0 AS `(count(1)) > 0` FROM (SELECT `_statistics_`.`query_history`.`dt`, `_statistics_`.`query_history`.`frontend`, `_statistics_`.`query_history`.`db`, `_statistics_`.`query_history`.`sql_digest`, `_statistics_`.`query_history`.`sql`, `_statistics_`.`query_history`.`plan`, `_statistics_`.`query_history`.`plan_costs`, `_statistics_`.`query_history`.`query_ms`, `_statistics_`.`query_history`.`other` FROM `_statistics_`.`query_history` UNION SELECT `_statistics_`.`query_history`.`dt`, `_statistics_`.`query_history`.`frontend`, `_statistics_`.`query_history`.`db`, `_statistics_`.`query_history`.`sql_digest`, `_statistics_`.`query_history`.`sql`, `_statistics_`.`query_history`.`plan`, `_statistics_`.`query_history`.`plan_costs`, `_statistics_`.`query_history`.`query_ms`, `_statistics_`.`query_history`.`other` FROM `_statistics_`.`query_history`) `query_history` WHERE `query_history`.`sql_digest` LIKE '%count%';
SELECT (count(1)) > 0 AS `(count(1)) > 0` FROM `_statistics_`.`query_history` WHERE `_statistics_`.`query_history`.`sql_digest` LIKE '%count%' GROUP BY `_statistics_`.`query_history`.`sql_digest`;
SELECT (count(1)) > 0 AS `(count(1)) > 0` FROM (SELECT `_statistics_`.`query_history`.`dt`, `_statistics_`.`query_history`.`frontend`, `_statistics_`.`query_history`.`db`, `_statistics_`.`query_history`.`sql_digest`, `_statistics_`.`query_history`.`sql`, `_statistics_`.`query_history`.`plan`, `_statistics_`.`query_history`.`plan_costs`, `_statistics_`.`query_history`.`query_ms`, `_statistics_`.`query_history`.`other` FROM `_statistics_`.`query_history` INTERSECT SELECT `_statistics_`.`query_history`.`dt`, `_statistics_`.`query_history`.`frontend`, `_statistics_`.`query_history`.`db`, `_statistics_`.`query_history`.`sql_digest`, `_statistics_`.`query_history`.`sql`, `_statistics_`.`query_history`.`plan`, `_statistics_`.`query_history`.`plan_costs`, `_statistics_`.`query_history`.`query_ms`, `_statistics_`.`query_history`.`other` FROM `_statistics_`.`query_history`) `query_history` WHERE `query_history`.`sql_digest` LIKE '%count%';
SELECT (char_length(1)) > 0 AS `(char_length(1)) > 0` FROM `_statistics_`.`query_history` WHERE `_statistics_`.`query_history`.`sql_digest` LIKE '%count%';
SELECT (count(1.0E308)) > 0 AS `(count(1.0E308)) > 0` FROM `_statistics_`.`query_history` WHERE `_statistics_`.`query_history`.`sql_digest` LIKE '%count%';
SELECT (hll_cardinality(1)) > 0 AS `(hll_cardinality(1)) > 0` FROM `_statistics_`.`query_history` WHERE `_statistics_`.`query_history`.`sql_digest` LIKE '%count%';
SELECT (count(1)) > 0 AS `(count(1)) > 0` FROM `_statistics_`.`query_history` WHERE `_statistics_`.`query_history`.`sql_digest` LIKE '%count%' HAVING (count(*)) > 0;
SELECT (ln(1)) > 0 AS `(ln(1)) > 0` FROM `_statistics_`.`query_history` WHERE `_statistics_`.`query_history`.`sql_digest` LIKE '%count%';
WITH `srfuzz_n1` AS (SELECT `_statistics_`.`query_history`.`dt`, `_statistics_`.`query_history`.`frontend`, `_statistics_`.`query_history`.`db`, `_statistics_`.`query_history`.`sql_digest`, `_statistics_`.`query_history`.`sql`, `_statistics_`.`query_history`.`plan`, `_statistics_`.`query_history`.`plan_costs`, `_statistics_`.`query_history`.`query_ms`, `_statistics_`.`query_history`.`other` FROM `_statistics_`.`query_history`) SELECT (count(1)) > 0 AS `(count(1)) > 0` FROM `srfuzz_n1` AS query_history WHERE `query_history`.`sql_digest` LIKE '%count%';
SELECT (count(1)) > 0 AS `(count(1)) > 0` FROM `_statistics_`.`query_history` WHERE `_statistics_`.`query_history`.`sql_digest` LIKE '%count%';
SELECT (count(1)) > 0 AS `(count(1)) > 0` FROM `_statistics_`.`query_history`;
SELECT (count(CAST(1 AS JSON)->'$')) > 0 AS `(count(CAST(1 AS JSON)->'$')) > 0` FROM `_statistics_`.`query_history` WHERE `_statistics_`.`query_history`.`sql_digest` LIKE '%count%';
SELECT (count(1)) > 0 AS `(count(1)) > 0` FROM `_statistics_`.`query_history` WHERE `_statistics_`.`query_history`.`sql_digest` LIKE '%count%';
SELECT json_length(CAST(((count(1)) > 0) AS JSON)) AS `json_length(CAST(((count(1)) > 0) AS JSON))` FROM `_statistics_`.`query_history` WHERE `_statistics_`.`query_history`.`sql_digest` LIKE '%count%';
WITH `srfuzz_n1` AS (SELECT `_statistics_`.`query_history`.`dt`, `_statistics_`.`query_history`.`frontend`, `_statistics_`.`query_history`.`db`, `_statistics_`.`query_history`.`sql_digest`, `_statistics_`.`query_history`.`sql`, `_statistics_`.`query_history`.`plan`, `_statistics_`.`query_history`.`plan_costs`, `_statistics_`.`query_history`.`query_ms`, `_statistics_`.`query_history`.`other` FROM `_statistics_`.`query_history`) SELECT (count(1)) > 0 AS `(count(1)) > 0` FROM `srfuzz_n1` AS query_history WHERE `query_history`.`sql_digest` LIKE '%count%';
SELECT (hex(1)) > 0 AS `(hex(1)) > 0` FROM `_statistics_`.`query_history` WHERE `_statistics_`.`query_history`.`sql_digest` LIKE '%count%';
SELECT (count(1)) > 0 AS `(count(1)) > 0` FROM `_statistics_`.`query_history` WHERE `_statistics_`.`query_history`.`sql_digest` LIKE '%count%';
SELECT (year(1)) > 0 AS `(year(1)) > 0` FROM `_statistics_`.`query_history` WHERE `_statistics_`.`query_history`.`sql_digest` LIKE '%count%';
SELECT (count(1)) > 0 AS `(count(1)) > 0` FROM `_statistics_`.`query_history` WHERE `_statistics_`.`query_history`.`sql_digest` LIKE '%count%';
SELECT (count(1)) > 0 AS `(count(1)) > 0` FROM `_statistics_`.`query_history` WHERE `_statistics_`.`query_history`.`sql_digest` LIKE '%count%';
SELECT (count(1)) > 0 AS `(count(1)) > 0` FROM (SELECT `_statistics_`.`query_history`.`dt`, `_statistics_`.`query_history`.`frontend`, `_statistics_`.`query_history`.`db`, `_statistics_`.`query_history`.`sql_digest`, `_statistics_`.`query_history`.`sql`, `_statistics_`.`query_history`.`plan`, `_statistics_`.`query_history`.`plan_costs`, `_statistics_`.`query_history`.`query_ms`, `_statistics_`.`query_history`.`other` FROM `_statistics_`.`query_history` UNION SELECT `_statistics_`.`query_history`.`dt`, `_statistics_`.`query_history`.`frontend`, `_statistics_`.`query_history`.`db`, `_statistics_`.`query_history`.`sql_digest`, `_statistics_`.`query_history`.`sql`, `_statistics_`.`query_history`.`plan`, `_statistics_`.`query_history`.`plan_costs`, `_statistics_`.`query_history`.`query_ms`, `_statistics_`.`query_history`.`other` FROM `_statistics_`.`query_history`) `query_history` WHERE `query_history`.`sql_digest` LIKE '%count%';