SELECT 'tinyint' AS `typeof(CAST(1 AS TINYINT))`;
SELECT 'smallint' AS `typeof(CAST(1 AS SMALLINT))`;
SELECT 'int' AS `typeof(CAST(1 AS INT))`;
SELECT 'bigint' AS `typeof(CAST(1 AS BIGINT))`;
SELECT 'largeint' AS `typeof(CAST(1 AS LARGEINT))`;
SELECT 'decimal128(19, 2)' AS `typeof(CAST(1 AS DECIMAL128(19,2)))`;
SELECT 'double' AS `typeof(CAST(1 AS DOUBLE))`;
SELECT 'float' AS `typeof(CAST(1 AS FLOAT))`;
SELECT 'boolean' AS `typeof(CAST(1 AS BOOLEAN))`;
SELECT 'char' AS `typeof(CAST(1 AS CHAR))`;
SELECT 'varchar' AS `typeof(CAST(1 AS VARCHAR(65533)))`;
SELECT 'varchar' AS `typeof(CAST(1 AS VARCHAR))`;
SELECT 'varbinary' AS `typeof(CAST('s' AS VARBINARY))`;
SELECT 'date' AS `typeof(CAST('2023-03-07' AS DATE))`;
SELECT 'datetime' AS `typeof(CAST('2023-03-07 11:22:33' AS DATETIME))`;
SELECT 'array<tinyint>' AS `typeof([1, 2, 3])`;
SELECT 'varchar' AS `typeof(get_json_object('{"k1":1, "k2":"v2"}', '$.k1'))`;
SELECT 'map<tinyint,varchar>' AS `typeof(map{1:'apple',2:'orange',3:'pear'})`;
SELECT 'struct<`col1` tinyint, `col2` tinyint, `col3` tinyint, `col4` tinyint>' AS `typeof(row(1, 2, 3, 4))`;
SELECT 'bitmap' AS `typeof(bitmap_empty())`;
SELECT 'hll' AS `typeof(hll_empty())`;
SELECT 'json' AS `typeof(parse_json('{"a": 1, "b": true}'))`;
SELECT 'null_type' AS `typeof(NULL)`;
SELECT 'bitmap' AS `typeof(user_id)` FROM `srfuzz_mut_446`.`pv_bitmap`;
SELECT 'hll' AS `typeof(uv_set)` FROM `srfuzz_mut_446`.`test_uv`;
SELECT 'tinyint' AS `typeof(CAST(0.0 AS TINYINT))`;
SELECT 'varchar' AS `typeof('tinyint')`;
SELECT 'tinyint' AS `typeof(CAST(170141183460469231731687303715884105727 AS TINYINT))`;
SELECT 'varchar' AS `typeof('tinyint')`;
SELECT 'tinyint' AS `typeof(CAST('%' AS TINYINT))`;
SELECT 'tinyint' AS `typeof(CAST(1 AS TINYINT))` WHERE 'hll';
SELECT 'tinyint' AS `typeof(CAST('tinyint' AS TINYINT))`;
SELECT 'tinyint' AS `typeof(CAST('tinyint' AS TINYINT))`;
SELECT 'varchar' AS `typeof('tinyint')`;
SELECT 'tinyint' AS `typeof(CAST('smallint' AS TINYINT))`;
SELECT max('tinyint') OVER () AS `max(typeof(CAST(1 AS TINYINT))) OVER ()`;
SELECT 'varchar' AS `typeof('tinyint')`;
SELECT 'varchar' AS `typeof('tinyint')`;
SELECT 'tinyint' AS `typeof(CAST((repeat('x', 65536)) AS TINYINT))`;
SELECT 'varchar' AS `typeof('bitmap')`;
SELECT 'varchar' AS `typeof('tinyint')`;
SELECT 'tinyint' AS `typeof(CAST('tinyint' AS TINYINT))`;
SELECT 'varchar' AS `typeof('tinyint')`;
SELECT 'tinyint' AS `typeof(CAST('tinyint' AS TINYINT))`;
SELECT DISTINCT 'tinyint' AS `typeof(CAST(1 AS TINYINT))`;
SELECT 'varchar' AS `typeof(CAST((CAST(1 AS TINYINT)) AS VARCHAR))`;
SELECT 'varchar' AS `typeof('tinyint')`;
SELECT 'tinyint' AS `typeof(CAST(-1.0E308 AS TINYINT))`;
SELECT 'varchar' AS `typeof('tinyint')`;
SELECT avg('tinyint') OVER () AS `avg(typeof(CAST(1 AS TINYINT))) OVER ()`;
SELECT 'tinyint' AS `typeof(CAST('tinyint' AS TINYINT))`;
SELECT 'varchar' AS `typeof(get_json_string(CAST((CAST(1 AS TINYINT)) AS JSON), '$.a'))`;
SELECT 'varchar' AS `typeof('tinyint')`;
SELECT 'varchar' AS `typeof('tinyint')`;
SELECT 'varchar' AS `typeof('tinyint')`;
SELECT 'varchar' AS `typeof('tinyint')`;
SELECT 'tinyint' AS `typeof(CAST('tinyint' AS TINYINT))`;
SELECT 'varchar' AS `typeof('smallint')`;
SELECT 'smallint' AS `typeof(CAST((CAST(1 AS JSON)->'k') AS SMALLINT))`;
SELECT 'smallint' AS `typeof(CAST(1 AS SMALLINT))` GROUP BY 'smallint';
SELECT 'smallint' AS `typeof(CAST(1 AS SMALLINT))` LIMIT 7, 5;
SELECT DISTINCT 'smallint' AS `typeof(CAST(1 AS SMALLINT))`;
SELECT 'smallint' AS `typeof(CAST('varchar' AS SMALLINT))`;
SELECT 'varchar' AS `typeof('bigint')`;
SELECT avg('smallint') OVER () AS `avg(typeof(CAST(1 AS SMALLINT))) OVER ()`;
SELECT DISTINCT 'smallint' AS `typeof(CAST(1 AS SMALLINT))`;
SELECT 'smallint' AS `typeof(CAST((CAST(1 AS JSON)->'k') AS SMALLINT))`;
SELECT 'smallint' AS `typeof(CAST(1 AS SMALLINT))` GROUP BY 'smallint';
SELECT 'varchar' AS `typeof('smallint')`;
SELECT 'smallint' AS `typeof(CAST(1 AS SMALLINT))` ORDER BY 'varchar' DESC;
SELECT 'smallint' AS `typeof(CAST('1970-01-01' AS SMALLINT))`;
SELECT 'smallint' AS `typeof(CAST('smallint' AS SMALLINT))`;
SELECT 'smallint' AS `typeof(CAST('smallint' AS SMALLINT))`;
SELECT 'smallint' AS `typeof(CAST('smallint' AS SMALLINT))`;
SELECT 'varchar' AS `typeof('smallint')`;
SELECT 'smallint' AS `typeof(CAST(1 AS SMALLINT))` WHERE 'float';
SELECT 'varchar' AS `typeof('smallint')`;
SELECT 'smallint' AS `typeof(CAST(0.0 AS SMALLINT))`;
SELECT 'smallint' AS `typeof(CAST(-2147483648 AS SMALLINT))`;
SELECT count('smallint') OVER () AS `count(typeof(CAST(1 AS SMALLINT))) OVER ()`;
SELECT 'smallint' AS `typeof(CAST(1 AS SMALLINT))` ORDER BY 'varchar' ASC NULLS LAST;
SELECT 'varchar' AS `typeof('smallint')`;
SELECT 'smallint' AS `typeof(CAST(1 AS SMALLINT))` ORDER BY 'varchar' ASC;
SELECT 'varchar' AS `typeof('int')`;
SELECT 'smallint' AS `typeof(CAST(1 AS SMALLINT))` ORDER BY 'varchar' ASC;
SELECT 'varchar' AS `typeof('int')`;
SELECT 'varchar' AS `typeof('int')`;
SELECT 'varchar' AS `typeof('int')`;
SELECT 'int' AS `typeof(CAST(1 AS INT))` ORDER BY 'varchar' ASC;
SELECT 'int' AS `typeof(CAST('int' AS INT))`;
SELECT 'int' AS `typeof(CAST('\\' AS INT))`;
SELECT 'int' AS `typeof(CAST(1 AS INT))` ORDER BY 'varchar' ASC;
SELECT 'varchar' AS `typeof('int')`;
SELECT DISTINCT 'int' AS `typeof(CAST(1 AS INT))`;
SELECT 'int' AS `typeof(CAST('int' AS INT))`;
SELECT 'varchar' AS `typeof('double')`;
SELECT 'int' AS `typeof(json_length(CAST((CAST(1 AS INT)) AS JSON)))`;
SELECT 'int' AS `typeof(CAST(1 AS INT))` GROUP BY 'int';
SELECT count('int') OVER () AS `count(typeof(CAST(1 AS INT))) OVER ()`;
SELECT 'int' AS `typeof(CAST('9999-12-31 23:59:59' AS INT))`;
SELECT 'int' AS `typeof(CAST('struct<``col1`` tinyint, ``col2`` tinyint, ``col3`` tinyint, ``col4`` tinyint>' AS INT))`;
SELECT 'int' AS `typeof(CAST(0.0 AS INT))`;
SELECT 'int' AS `typeof(CAST('int' AS INT))`;
SELECT 'varchar' AS `typeof('int')`;
SELECT 'varchar' AS `typeof('int')`;
SELECT 'int' AS `typeof(CAST(1 AS INT))` ORDER BY 'varchar' DESC NULLS FIRST;
SELECT 'varchar' AS `typeof('map<tinyint,varchar>')`;
SELECT 'int' AS `typeof(CAST(1 AS INT))` ORDER BY 'varchar' ASC;
SELECT 'int' AS `typeof(CAST(1 AS INT))` LIMIT 100;
SELECT 'int' AS `typeof(CAST('char' AS INT))`;
SELECT 'int' AS `typeof(CAST(1 AS INT))` GROUP BY 'int';
SELECT 'json' AS `typeof(CAST((CAST(1 AS INT)) AS JSON)->'k')`;
SELECT 'varchar' AS `typeof('int')`;
SELECT 'int' AS `typeof(CAST('int' AS INT))`;
SELECT 'int' AS `typeof(CAST(1 AS INT))` ORDER BY 'varchar' ASC;
SELECT 'varchar' AS `typeof('int')`;
SELECT 'varchar' AS `typeof('bigint')`;
SELECT 'bigint' AS `typeof(CAST(1 AS BIGINT))` WHERE 'null_type';
SELECT 'bigint' AS `typeof(CAST('\\' AS BIGINT))`;
SELECT 'varchar' AS `typeof('bigint')`;
SELECT 'varchar' AS `typeof('bigint')`;
SELECT 'varchar' AS `typeof('varchar')`;
SELECT 'varchar' AS `typeof('bigint')`;
SELECT 'bigint' AS `typeof(CAST('bigint' AS BIGINT))`;
SELECT 'bigint' AS `typeof(CAST('bigint' AS BIGINT))`;
SELECT 'bigint' AS `typeof(CAST((CAST(NULL AS JSON)) AS BIGINT))`;
SELECT 'bigint' AS `typeof(CAST('0' AS BIGINT))`;
SELECT 'bigint' AS `typeof(CAST('bigint' AS BIGINT))`;
SELECT 'bigint' AS `typeof(CAST(1 AS BIGINT))` WHERE 'struct<`col1` tinyint, `col2` tinyint, `col3` tinyint, `col4` tinyint>';
SELECT 'bigint' AS `typeof(CAST(1 AS BIGINT))` LIMIT 0;
SELECT 'varchar' AS `typeof('bigint')`;
SELECT 'bigint' AS `typeof(CAST((json_length(CAST(1 AS JSON))) AS BIGINT))`;
SELECT 'bigint' AS `typeof(CAST(1 AS BIGINT))` GROUP BY 'bigint';
SELECT 'bigint' AS `typeof(CAST(1 AS BIGINT))` LIMIT 7, 100;
SELECT 'bigint' AS `typeof(CAST(1 AS BIGINT))` ORDER BY 'varchar' DESC;
SELECT 'bigint' AS `typeof(CAST('bigint' AS BIGINT))`;
SELECT 'varchar' AS `typeof('bigint')`;
SELECT 'varchar' AS `typeof('bigint')`;
SELECT 'varchar' AS `typeof('bigint')`;
SELECT 'bigint' AS `typeof(CAST('largeint' AS BIGINT))`;
SELECT 'varchar' AS `typeof('bigint')`;
SELECT 'bigint' AS `typeof(CAST(-1.0E308 AS BIGINT))`;
SELECT 'varchar' AS `typeof('bigint')`;
SELECT 'varchar' AS `typeof('struct<``col1`` tinyint, ``col2`` tinyint, ``col3`` tinyint, ``col4`` tinyint>')`;
SELECT 'bigint' AS `typeof(CAST(1 AS BIGINT))` ORDER BY 'varchar' ASC;
SELECT 'varchar' AS `typeof('bigint')`;
SELECT 'varchar' AS `typeof('float')`;
SELECT 'bigint' AS `typeof(CAST('bigint' AS BIGINT))`;
SELECT 'varchar' AS `typeof('largeint')`;
SELECT 'largeint' AS `typeof(CAST(0 AS LARGEINT))`;
SELECT 'largeint' AS `typeof(CAST(1 AS LARGEINT))` WHERE 'bitmap';
SELECT 'largeint' AS `typeof(CAST(1 AS LARGEINT))` WHERE 'struct<`col1` tinyint, `col2` tinyint, `col3` tinyint, `col4` tinyint>';
SELECT 'varchar' AS `typeof(get_json_string(CAST((CAST(1 AS LARGEINT)) AS JSON), '$.a'))`;
SELECT 'largeint' AS `typeof(CAST((CAST(1 AS JSON)->'$') AS LARGEINT))`;
SELECT 'largeint' AS `typeof(CAST(1 AS LARGEINT))` GROUP BY 'largeint';
SELECT 'largeint' AS `typeof(CAST(1 AS LARGEINT))` GROUP BY 'largeint';
SELECT 'largeint' AS `typeof(CAST('largeint' AS LARGEINT))`;
SELECT 'varchar' AS `typeof('largeint')`;
SELECT max('largeint') OVER () AS `max(typeof(CAST(1 AS LARGEINT))) OVER ()`;
SELECT 'largeint' AS `typeof(CAST(1 AS LARGEINT))` GROUP BY 'largeint';
SELECT 'largeint' AS `typeof(CAST(1 AS LARGEINT))` GROUP BY 'largeint';
SELECT 'largeint' AS `typeof(CAST(1 AS LARGEINT))` ORDER BY 'varchar' ASC NULLS LAST;
SELECT 'largeint' AS `typeof(CAST(1 AS LARGEINT))`;
SELECT 'varchar' AS `typeof('tinyint')`;
SELECT 'largeint' AS `typeof(CAST(1 AS LARGEINT))` GROUP BY 'largeint';
SELECT 'varchar' AS `typeof('largeint')`;
SELECT 'varchar' AS `typeof('largeint')`;
SELECT DISTINCT 'largeint' AS `typeof(CAST(1 AS LARGEINT))`;
SELECT 'varchar' AS `typeof('smallint')`;
SELECT 'largeint' AS `typeof(CAST(1 AS LARGEINT))` ORDER BY 'varchar' DESC;
SELECT 'json' AS `typeof(CAST((CAST(1 AS LARGEINT)) AS JSON)->'k')`;
SELECT 'largeint' AS `typeof(CAST(1 AS LARGEINT))` WHERE 'float';
SELECT 'largeint' AS `typeof(CAST('largeint' AS LARGEINT))`;
SELECT 'varchar' AS `typeof('int')`;
SELECT 'varchar' AS `typeof('largeint')`;
SELECT 'varchar' AS `typeof('decimal128(19, 2)')`;
SELECT 'varchar' AS `typeof('decimal128(19, 2)')`;
SELECT 'varchar' AS `typeof('decimal128(19, 2)')`;
SELECT 'varchar' AS `typeof('decimal128(19, 2)')`;
SELECT 'decimal128(19, 2)' AS `typeof(CAST('decimal128(19, 2)' AS DECIMAL128(19,2)))`;
SELECT 'decimal128(19, 2)' AS `typeof(CAST(1 AS DECIMAL128(19,2)))` GROUP BY 'decimal128(19, 2)';
SELECT 'varchar' AS `typeof('decimal128(19, 2)')`;
SELECT 'decimal128(19, 2)' AS `typeof(CAST(1 AS DECIMAL128(19,2)))` LIMIT 7, 100;
SELECT 'decimal128(19, 2)' AS `typeof(CAST(1 AS DECIMAL128(19,2)))` ORDER BY 'varchar' DESC NULLS FIRST;
SELECT avg('decimal128(19, 2)') OVER () AS `avg(typeof(CAST(1 AS DECIMAL128(19,2)))) OVER ()`;
SELECT 'varchar' AS `typeof('double')`;
SELECT 'decimal128(19, 2)' AS `typeof(CAST('decimal128(19, 2)' AS DECIMAL128(19,2)))`;
SELECT 'decimal128(19, 2)' AS `typeof(CAST(1 AS DECIMAL128(19,2)))` ORDER BY 'varchar' ASC;
SELECT 'varchar' AS `typeof('decimal128(19, 2)')`;
SELECT 'decimal128(19, 2)' AS `typeof(CAST('decimal128(19, 2)' AS DECIMAL128(19,2)))`;
SELECT 'decimal128(19, 2)' AS `typeof(CAST(-1 AS DECIMAL128(19,2)))`;
SELECT 'varchar' AS `typeof('decimal128(19, 2)')`;
SELECT 'decimal128(19, 2)' AS `typeof(CAST((CAST(1 AS DECIMAL128(27,9))) AS DECIMAL128(19,2)))`;
SELECT 'decimal128(19, 2)' AS `typeof(CAST(1 AS DECIMAL128(19,2)))` GROUP BY 'decimal128(19, 2)';
SELECT 'decimal128(19, 2)' AS `typeof(CAST(1 AS DECIMAL128(19,2)))` WHERE 'datetime';
SELECT 'varchar' AS `typeof('decimal128(19, 2)')`;
SELECT 'varchar' AS `typeof('float')`;
SELECT 'decimal128(19, 2)' AS `typeof(CAST('decimal128(19, 2)' AS DECIMAL128(19,2)))`;
SELECT 'varchar' AS `typeof('decimal128(19, 2)')`;
SELECT 'decimal128(19, 2)' AS `typeof(CAST(1 AS DECIMAL128(19,2)))` LIMIT 1;
SELECT 'varchar' AS `typeof('decimal128(19, 2)')`;
SELECT 'varchar' AS `typeof('hll')`;
SELECT 'decimal128(19, 2)' AS `typeof(CAST(-1 AS DECIMAL128(19,2)))`;
SELECT 'decimal128(19, 2)' AS `typeof(CAST(1 AS DECIMAL128(19,2)))` WHERE 'bigint';
SELECT 'varchar' AS `typeof('decimal128(19, 2)')`;
SELECT 'double' AS `typeof(CAST((CAST(1 AS JSON)->'k') AS DOUBLE))`;
SELECT 'double' AS `typeof(CAST(1 AS DOUBLE))` GROUP BY 'double';
SELECT 'double' AS `typeof(CAST(1.0E308 AS DOUBLE))`;
SELECT 'double' AS `typeof(CAST(1 AS DOUBLE))` LIMIT 1, 1;
SELECT 'double' AS `typeof(CAST('double' AS DOUBLE))`;
SELECT 'double' AS `typeof(CAST(-9223372036854775808 AS DOUBLE))`;
SELECT 'double' AS `typeof(CAST('double' AS DOUBLE))`;
SELECT 'double' AS `typeof(CAST(1 AS DOUBLE))` ORDER BY 'varchar' ASC;
SELECT 'double' AS `typeof(CAST('double' AS DOUBLE))`;
SELECT 'double' AS `typeof(CAST('double' AS DOUBLE))`;
SELECT 'double' AS `typeof(CAST(1 AS DOUBLE))` WHERE 'array<tinyint>';
SELECT DISTINCT 'double' AS `typeof(CAST(1 AS DOUBLE))`;
SELECT 'double' AS `typeof(CAST('double' AS DOUBLE))`;
SELECT 'double' AS `typeof(CAST(TRUE AS DOUBLE))`;
SELECT 'varchar' AS `typeof('double')`;
SELECT 'varchar' AS `typeof('double')`;
SELECT 'double' AS `typeof(CAST('double' AS DOUBLE))`;
SELECT 'double' AS `typeof(CAST(1 AS DOUBLE))` LIMIT 1, 0;
SELECT 'varchar' AS `typeof('double')`;
SELECT 'varchar' AS `typeof('double')`;
SELECT 'double' AS `typeof(CAST(1 AS DOUBLE))` LIMIT 5;
SELECT 'varchar' AS `typeof('varchar')`;
SELECT 'double' AS `typeof(CAST(1 AS DOUBLE))` GROUP BY 'double';
SELECT 'double' AS `typeof(CAST(1 AS DOUBLE))` ORDER BY 'varchar' DESC;
SELECT 'double' AS `typeof(CAST(1 AS DOUBLE))` ORDER BY 'varchar' DESC;
SELECT 'double' AS `typeof(CAST(1 AS DOUBLE))` GROUP BY 'double';
SELECT 'double' AS `typeof(CAST(1 AS DOUBLE))` LIMIT 1;
SELECT min('double') OVER () AS `min(typeof(CAST(1 AS DOUBLE))) OVER ()`;
SELECT 'double' AS `typeof(CAST('date' AS DOUBLE))`;
SELECT 'varchar' AS `typeof('double')`;
SELECT 'double' AS `typeof(CAST('double' AS DOUBLE))`;
SELECT 'varchar' AS `typeof('float')`;
SELECT 'float' AS `typeof(CAST(0.0 AS FLOAT))`;
SELECT 'float' AS `typeof(CAST('float' AS FLOAT))`;
SELECT 'varchar' AS `typeof('float')`;
SELECT 'float' AS `typeof(CAST(1 AS FLOAT))` WHERE 'float';
SELECT 'float' AS `typeof(CAST('float' AS FLOAT))`;
SELECT 'float' AS `typeof(CAST('float' AS FLOAT))`;
SELECT 'float' AS `typeof(CAST('largeint' AS FLOAT))`;
SELECT 'varchar' AS `typeof('float')`;
SELECT 'float' AS `typeof(CAST('' AS FLOAT))`;
SELECT 'float' AS `typeof(CAST(-1 AS FLOAT))`;
SELECT 'float' AS `typeof(CAST('float' AS FLOAT))`;
SELECT 'float' AS `typeof(CAST(-1 AS FLOAT))`;
SELECT 'varchar' AS `typeof('float')`;
SELECT 'varchar' AS `typeof('float')`;
SELECT 'varchar' AS `typeof('array<tinyint>')`;
SELECT 'float' AS `typeof(CAST(1 AS FLOAT))` WHERE 'null_type';
SELECT 'varchar' AS `typeof('boolean')`;
SELECT 'float' AS `typeof(CAST((get_json_string(CAST(1 AS JSON), '$.a')) AS FLOAT))`;
SELECT 'varchar' AS `typeof('float')`;
SELECT 'varchar' AS `typeof('float')`;
SELECT 'float' AS `typeof(CAST(1 AS FLOAT))` ORDER BY 'varchar' DESC NULLS FIRST;
SELECT 'varchar' AS `typeof('float')`;
SELECT 'float' AS `typeof(CAST(1 AS FLOAT))` GROUP BY 'float';
SELECT 'varchar' AS `typeof('float')`;
SELECT 'varchar' AS `typeof('float')`;
SELECT 'varchar' AS `typeof('float')`;
SELECT count('float') OVER () AS `count(typeof(CAST(1 AS FLOAT))) OVER ()`;
SELECT 'varchar' AS `typeof('int')`;
SELECT 'varchar' AS `typeof('float')`;
SELECT 'float' AS `typeof(CAST('%' AS FLOAT))`;
SELECT 'varchar' AS `typeof('float')`;
SELECT 'float' AS `typeof(CAST('float' AS FLOAT))`;
SELECT 'boolean' AS `typeof(CAST(1 AS BOOLEAN))` LIMIT 1, 0;
SELECT 'boolean' AS `typeof(CAST('boolean' AS BOOLEAN))`;
SELECT 'boolean' AS `typeof(CAST((CAST((CAST(1 AS DECIMAL128(27,9))) AS FLOAT)) AS BOOLEAN))`;
SELECT 'boolean' AS `typeof(CAST('9999-12-31 23:59:59' AS BOOLEAN))`;
SELECT 'varchar' AS `typeof('boolean')`;
SELECT 'varchar' AS `typeof('boolean')`;
SELECT 'varchar' AS `typeof('boolean')`;
SELECT 'boolean' AS `typeof(CAST('boolean' AS BOOLEAN))`;
SELECT 'boolean' AS `typeof(CAST('varchar' AS BOOLEAN))`;
SELECT 'boolean' AS `typeof(CAST(1 AS BOOLEAN))` WHERE 'date';
SELECT 'boolean' AS `typeof(CAST(1 AS BOOLEAN))` ORDER BY 'varchar' ASC;
SELECT 'boolean' AS `typeof(CAST(1 AS BOOLEAN))` GROUP BY 'boolean';
SELECT 'varchar' AS `typeof('boolean')`;
SELECT 'boolean' AS `typeof(CAST('boolean' AS BOOLEAN))`;
SELECT 'boolean' AS `typeof(CAST(0.0 AS BOOLEAN))`;
SELECT 'boolean' AS `typeof(CAST('boolean' AS BOOLEAN))`;
SELECT 'varchar' AS `typeof('boolean')`;
SELECT DISTINCT 'boolean' AS `typeof(CAST(1 AS BOOLEAN))`;
SELECT 'varchar' AS `typeof('boolean')`;
SELECT 'boolean' AS `typeof(CAST('%' AS BOOLEAN))`;
SELECT 'boolean' AS `typeof(CAST(1 AS BOOLEAN))` WHERE 'char';
SELECT 'varchar' AS `typeof('boolean')`;
SELECT 'varchar' AS `typeof('boolean')`;
SELECT 'boolean' AS `typeof(CAST('boolean' AS BOOLEAN))`;
SELECT 'boolean' AS `typeof(CAST('0' AS BOOLEAN))`;
SELECT 'json' AS `typeof(CAST((CAST(1 AS BOOLEAN)) AS JSON)->'$')`;
SELECT DISTINCT 'boolean' AS `typeof(CAST(1 AS BOOLEAN))`;
SELECT 'boolean' AS `typeof(CAST('boolean' AS BOOLEAN))`;
SELECT 'boolean' AS `typeof(CAST('boolean' AS BOOLEAN))`;
SELECT 'varchar' AS `typeof('boolean')`;
SELECT 'varchar' AS `typeof('char')`;
SELECT 'varchar' AS `typeof('char')`;
SELECT 'varchar' AS `typeof('char')`;
SELECT 'char' AS `typeof(CAST('char' AS CHAR))`;
SELECT 'char' AS `typeof(CAST(9223372036854775807 AS CHAR))`;
SELECT 'char' AS `typeof(CAST('0' AS CHAR))`;
SELECT 'varchar' AS `typeof('char')`;
SELECT 'char' AS `typeof(CAST(1 AS CHAR))` WHERE 'bigint';
SELECT 'char' AS `typeof(CAST('varchar' AS CHAR))`;
SELECT 'char' AS `typeof(CAST('char' AS CHAR))`;
SELECT 'varchar' AS `typeof('bitmap')`;
SELECT 'char' AS `typeof(CAST('char' AS CHAR))`;
SELECT 'varchar' AS `typeof('char')`;
SELECT 'varchar' AS `typeof('int')`;
SELECT 'char' AS `typeof(CAST(1 AS CHAR))` WHERE 'double';
SELECT 'char' AS `typeof(CAST(1 AS CHAR))` WHERE 'smallint';
SELECT 'char' AS `typeof(CAST(1 AS CHAR))` GROUP BY 'char';
SELECT 'json' AS `typeof(CAST((CAST(1 AS CHAR)) AS JSON)->'$.a')`;
SELECT 'char' AS `typeof(CAST(1 AS CHAR))` WHERE 'decimal128(19, 2)';
SELECT 'varchar' AS `typeof('char')`;
SELECT 'char' AS `typeof(CAST((CAST(NULL AS JSON)) AS CHAR))`;
SELECT 'char' AS `typeof(CAST('char' AS CHAR))`;
SELECT 'char' AS `typeof(CAST('char' AS CHAR))`;
SELECT DISTINCT 'char' AS `typeof(CAST(1 AS CHAR))`;
SELECT 'varchar' AS `typeof('char')`;
SELECT 'char' AS `typeof(CAST(1 AS CHAR))` WHERE 'int';
SELECT 'char' AS `typeof(CAST(1 AS CHAR))` LIMIT 1, 5;
SELECT 'varchar' AS `typeof(CAST(9223372036854775807 AS VARCHAR(65533)))`;
SELECT 'varchar' AS `typeof(CAST((repeat('x', 65536)) AS VARCHAR(65533)))`;
SELECT 'int' AS `typeof(json_length(CAST((CAST(1 AS VARCHAR(65533))) AS JSON)))`;
SELECT 'varchar' AS `typeof(CAST(1 AS VARCHAR(65533)))` WHERE 'null_type';
SELECT 'varchar' AS `typeof(CAST('varchar' AS VARCHAR(65533)))`;
SELECT 'varchar' AS `typeof('varchar')`;
SELECT 'varchar' AS `typeof(CAST('\\' AS VARCHAR(65533)))`;
SELECT 'varchar' AS `typeof(CAST(170141183460469231731687303715884105727 AS VARCHAR(65533)))`;
SELECT 'varchar' AS `typeof('varchar')`;
SELECT 'varchar' AS `typeof(CAST('varchar' AS VARCHAR(65533)))`;
SELECT 'varchar' AS `typeof('varchar')`;
SELECT 'varchar' AS `typeof(CAST('varchar' AS VARCHAR(65533)))`;
SELECT avg('varchar') OVER () AS `avg(typeof(CAST(1 AS VARCHAR(65533)))) OVER ()`;
SELECT 'varchar' AS `typeof(CAST('varchar' AS VARCHAR(65533)))`;
SELECT 'varchar' AS `typeof(CAST((CAST(1 AS JSON)->'k') AS VARCHAR(65533)))`;
SELECT 'varchar' AS `typeof(CAST('varchar' AS VARCHAR(65533)))`;
SELECT 'varchar' AS `typeof('varchar')`;
SELECT 'varchar' AS `typeof('varchar')`;
SELECT 'varchar' AS `typeof(get_json_string(CAST((CAST(1 AS VARCHAR(65533))) AS JSON), '$.a'))`;
SELECT 'varchar' AS `typeof(CAST('0000-00-00' AS VARCHAR(65533)))`;
SELECT max('varchar') OVER () AS `max(typeof(CAST(1 AS VARCHAR(65533)))) OVER ()`;
SELECT 'varchar' AS `typeof(CAST('varchar' AS VARCHAR(65533)))`;
SELECT 'varchar' AS `typeof(CAST(1 AS VARCHAR(65533)))` LIMIT 7, 5;
SELECT 'varchar' AS `typeof(CAST('boolean' AS VARCHAR(65533)))`;
SELECT 'varchar' AS `typeof(CAST('varchar' AS VARCHAR(65533)))`;
SELECT 'varchar' AS `typeof(CAST(1 AS VARCHAR(65533)))` LIMIT 0;
SELECT 'varchar' AS `typeof('varchar')`;
SELECT DISTINCT 'varchar' AS `typeof(CAST(1 AS VARCHAR(65533)))`;
SELECT 'varchar' AS `typeof(CAST('varchar' AS VARCHAR(65533)))`;
SELECT 'varchar' AS `typeof(CAST('varchar' AS VARCHAR(65533)))`;
SELECT 'varchar' AS `typeof('varchar')`;
SELECT 'varchar' AS `typeof('varchar')`;
SELECT 'varchar' AS `typeof('varchar')`;
SELECT 'varchar' AS `typeof(CAST(1 AS VARCHAR))` WHERE 'smallint';
SELECT 'varchar' AS `typeof(CAST('' AS VARCHAR))`;
SELECT DISTINCT 'varchar' AS `typeof(CAST(1 AS VARCHAR))`;
SELECT DISTINCT 'varchar' AS `typeof(CAST(1 AS VARCHAR))`;
SELECT 'varchar' AS `typeof('varchar')`;
SELECT 'varchar' AS `typeof(CAST(0.0 AS VARCHAR))`;
SELECT 'varchar' AS `typeof('varchar')`;
SELECT 'varchar' AS `typeof(CAST('varchar' AS VARCHAR))`;
SELECT 'varchar' AS `typeof('varchar')`;
SELECT 'varchar' AS `typeof('map<tinyint,varchar>')`;
SELECT 'varchar' AS `typeof(CAST('varchar' AS VARCHAR))`;
SELECT 'varchar' AS `typeof('varchar')`;
SELECT 'varchar' AS `typeof(CAST(NULL AS VARCHAR))`;
SELECT 'varchar' AS `typeof(CAST(-2147483648 AS VARCHAR))`;
SELECT 'varchar' AS `typeof(CAST(1.0E308 AS VARCHAR))`;
SELECT 'varchar' AS `typeof(CAST('varchar' AS VARCHAR))`;
SELECT 'varchar' AS `typeof(CAST(1 AS VARCHAR))` GROUP BY 'varchar';
SELECT 'varchar' AS `typeof('null_type')`;
SELECT 'varchar' AS `typeof(CAST('varchar' AS VARCHAR))`;
SELECT 'varchar' AS `typeof('varchar')`;
SELECT 'varchar' AS `typeof('varchar')`;
SELECT count('varchar') OVER () AS `count(typeof(CAST(1 AS VARCHAR))) OVER ()`;
SELECT 'varchar' AS `typeof(CAST(1 AS VARCHAR))`;
SELECT 'varchar' AS `typeof('null_type')`;
SELECT 'varchar' AS `typeof(CAST(-1.0E308 AS VARCHAR))`;
SELECT 'varchar' AS `typeof(CAST((CAST(1 AS VARCHAR)) AS VARCHAR))`;
SELECT 'varbinary' AS `typeof(CAST('' AS VARBINARY))`;
SELECT 'varbinary' AS `typeof(CAST('varbinary' AS VARBINARY))`;
SELECT 'varchar' AS `typeof('varbinary')`;
SELECT 'varchar' AS `typeof('varbinary')`;
SELECT 'varbinary' AS `typeof(CAST('varbinary' AS VARBINARY))`;
SELECT 'varbinary' AS `typeof(CAST('s' AS VARBINARY))` ORDER BY 'varchar' ASC NULLS LAST;
SELECT 'varbinary' AS `typeof(CAST('struct<``col1`` tinyint, ``col2`` tinyint, ``col3`` tinyint, ``col4`` tinyint>' AS VARBINARY))`;
SELECT 'varbinary' AS `typeof(CAST('varbinary' AS VARBINARY))`;
SELECT 'varbinary' AS `typeof(CAST('varbinary' AS VARBINARY))`;
SELECT 'varbinary' AS `typeof(CAST('s' AS VARBINARY))` GROUP BY 'varbinary';
SELECT 'varbinary' AS `typeof(CAST('varbinary' AS VARBINARY))`;
SELECT 'varchar' AS `typeof('boolean')`;
SELECT 'varbinary' AS `typeof(CAST(TRUE AS VARBINARY))`;
SELECT count('varbinary') OVER () AS `count(typeof(CAST('s' AS VARBINARY))) OVER ()`;
SELECT 'varchar' AS `typeof('varbinary')`;
SELECT 'varbinary' AS `typeof(CAST('s' AS VARBINARY))` GROUP BY 'varbinary';
SELECT 'varbinary' AS `typeof(CAST('varbinary' AS VARBINARY))`;
SELECT 'varchar' AS `typeof('varbinary')`;
SELECT 'varchar' AS `typeof('char')`;
SELECT 'largeint' AS `typeof(CAST((CAST('s' AS VARBINARY)) AS LARGEINT))`;
SELECT 'varchar' AS `typeof('double')`;
SELECT 'varbinary' AS `typeof(CAST('s' AS VARBINARY))` GROUP BY 'varbinary';
SELECT DISTINCT 'varbinary' AS `typeof(CAST('s' AS VARBINARY))`;
SELECT 'varbinary' AS `typeof(CAST('varbinary' AS VARBINARY))`;
SELECT 'varbinary' AS `typeof(CAST('s' AS VARBINARY))` WHERE 'null_type';
SELECT 'varchar' AS `typeof('varbinary')`;
SELECT 'varchar' AS `typeof('varbinary')`;
SELECT 'varbinary' AS `typeof(CAST(FALSE AS VARBINARY))`;
SELECT 'varbinary' AS `typeof(CAST('s' AS VARBINARY))` ORDER BY 'varchar' ASC;
SELECT 'varchar' AS `typeof('array<tinyint>')`;
SELECT 'varbinary' AS `typeof(CAST('0000-00-00' AS VARBINARY))`;
SELECT 'varchar' AS `typeof('date')`;
SELECT 'varchar' AS `typeof('date')`;
SELECT 'varchar' AS `typeof('date')`;
SELECT 'date' AS `typeof(CAST('2023-03-07' AS DATE))` LIMIT 100;
SELECT 'date' AS `typeof(CAST('2023-03-07' AS DATE))` LIMIT 1;
SELECT 'varchar' AS `typeof('date')`;
SELECT 'date' AS `typeof(CAST('date' AS DATE))`;
SELECT 'varchar' AS `typeof('varbinary')`;
SELECT 'date' AS `typeof(CAST('json' AS DATE))`;
SELECT 'varchar' AS `typeof('date')`;
SELECT 'date' AS `typeof(CAST('2023-03-07' AS DATE))` WHERE 'largeint';
SELECT 'decimal64(1, 0)' AS `typeof(CAST((CAST('2023-03-07' AS DATE)) AS DECIMAL64(1,0)))`;
SELECT 'date' AS `typeof(CAST('date' AS DATE))`;
SELECT 'date' AS `typeof(CAST('2023-03-07' AS DATE))` WHERE 'largeint';
SELECT 'varchar' AS `typeof('date')`;
SELECT 'date' AS `typeof(CAST(-2147483648 AS DATE))`;
SELECT 'date' AS `typeof(CAST(170141183460469231731687303715884105727 AS DATE))`;
SELECT 'date' AS `typeof(CAST('1970-01-01' AS DATE))`;
SELECT 'date' AS `typeof(CAST('date' AS DATE))`;
SELECT 'date' AS `typeof(CAST('2023-03-07' AS DATE))` GROUP BY 'date';
SELECT 'date' AS `typeof(CAST('0' AS DATE))`;
SELECT 'varchar' AS `typeof('date')`;
SELECT 'date' AS `typeof(CAST('2023-03-07' AS DATE))` ORDER BY 'varchar' DESC;
SELECT 'date' AS `typeof(CAST('largeint' AS DATE))`;
SELECT DISTINCT 'date' AS `typeof(CAST('2023-03-07' AS DATE))`;
SELECT 'date' AS `typeof(CAST(-1 AS DATE))`;
SELECT 'date' AS `typeof(CAST(2147483647 AS DATE))`;
SELECT 'date' AS `typeof(CAST('2023-03-07' AS DATE))` GROUP BY 'date';
SELECT 'date' AS `typeof(CAST('2023-03-07' AS DATE))` ORDER BY 'varchar' ASC;
SELECT 'date' AS `typeof(CAST('2023-03-07' AS DATE))` GROUP BY 'date';
SELECT 'varchar' AS `typeof('date')`;
SELECT 'varchar' AS `typeof('date')`;
SELECT 'date' AS `typeof(CAST('2023-03-07' AS DATE))` ORDER BY 'varchar' DESC;
SELECT 'date' AS `typeof(CAST('2023-03-07' AS DATE))` ORDER BY 'varchar' DESC NULLS FIRST;
SELECT 'datetime' AS `typeof(CAST((repeat('x', 65536)) AS DATETIME))`;
SELECT sum('datetime') OVER () AS `sum(typeof(CAST('2023-03-07 11:22:33' AS DATETIME))) OVER ()`;
SELECT 'datetime' AS `typeof(CAST(-1 AS DATETIME))`;
SELECT 'datetime' AS `typeof(CAST('2023-03-07 11:22:33' AS DATETIME))` ORDER BY 'varchar' DESC;
SELECT 'varchar' AS `typeof('datetime')`;
SELECT 'datetime' AS `typeof(CAST('2023-03-07 11:22:33' AS DATETIME))` ORDER BY 'varchar' DESC;
SELECT 'varchar' AS `typeof('datetime')`;
SELECT 'varchar' AS `typeof('datetime')`;
SELECT 'varchar' AS `typeof('datetime')`;
SELECT 'datetime' AS `typeof(CAST('datetime' AS DATETIME))`;
SELECT DISTINCT 'datetime' AS `typeof(CAST('2023-03-07 11:22:33' AS DATETIME))`;
SELECT 'datetime' AS `typeof(CAST('2023-03-07 11:22:33' AS DATETIME))` WHERE 'datetime';
SELECT 'varchar' AS `typeof('datetime')`;
SELECT 'datetime' AS `typeof(CAST('2023-03-07 11:22:33' AS DATETIME))` ORDER BY 'varchar' DESC;
SELECT 'varchar' AS `typeof('datetime')`;
SELECT 'varchar' AS `typeof('datetime')`;
SELECT 'datetime' AS `typeof(CAST('datetime' AS DATETIME))`;
SELECT 'varchar' AS `typeof('datetime')`;
SELECT 'datetime' AS `typeof(CAST('datetime' AS DATETIME))`;
SELECT max('datetime') OVER () AS `max(typeof(CAST('2023-03-07 11:22:33' AS DATETIME))) OVER ()`;
SELECT 'datetime' AS `typeof(CAST((CAST('2023-03-07 11:22:33' AS DATETIME)) AS DATETIME))`;
SELECT count('datetime') OVER () AS `count(typeof(CAST('2023-03-07 11:22:33' AS DATETIME))) OVER ()`;
SELECT 'varchar' AS `typeof('float')`;
SELECT max('datetime') OVER () AS `max(typeof(CAST('2023-03-07 11:22:33' AS DATETIME))) OVER ()`;
SELECT 'varchar' AS `typeof('datetime')`;
SELECT 'datetime' AS `typeof(CAST('datetime' AS DATETIME))`;
SELECT 'varchar' AS `typeof('datetime')`;
SELECT DISTINCT 'datetime' AS `typeof(CAST('2023-03-07 11:22:33' AS DATETIME))`;
SELECT DISTINCT 'datetime' AS `typeof(CAST('2023-03-07 11:22:33' AS DATETIME))`;
SELECT 'varchar' AS `typeof('decimal128(19, 2)')`;
SELECT 'varchar' AS `typeof('array<tinyint>')`;
SELECT 'varchar' AS `typeof('null_type')`;
SELECT 'varchar' AS `typeof('array<tinyint>')`;
SELECT 'varchar' AS `typeof('tinyint')`;
SELECT 'varchar' AS `typeof('array<tinyint>')`;
SELECT 'varchar' AS `typeof('array<tinyint>')`;
SELECT 'varchar' AS `typeof('array<tinyint>')`;
SELECT 'varchar' AS `typeof('array<tinyint>')`;
SELECT 'varchar' AS `typeof('varchar')`;
SELECT 'array<varchar>' AS `typeof(split('{"k1":1, "k2":"v2"}', '$.k1'))`;
SELECT 'varchar' AS `typeof(get_json_object('{"k1":1, "k2":"v2"}', repeat('x', 65536)))`;
SELECT 'varchar' AS `typeof(get_json_object('{"k1":1, "k2":"v2"}', '$.k1'))` ORDER BY 'varchar' ASC;
SELECT 'varchar' AS `typeof(get_json_object('{"k1":1, "k2":"v2"}', '$.k1'))` ORDER BY 'varchar' DESC;
SELECT 'varchar' AS `typeof(get_json_object(CAST('{"k1":1, "k2":"v2"}' AS JSON)->'$.a', '$.k1'))`;
SELECT 'varchar' AS `typeof(get_json_object(-9223372036854775808, '$.k1'))`;
SELECT 'varchar' AS `typeof(get_json_object('varchar', '$.k1'))`;
SELECT DISTINCT 'varchar' AS `typeof(get_json_object('{"k1":1, "k2":"v2"}', '$.k1'))`;
SELECT 'double' AS `typeof(round('{"k1":1, "k2":"v2"}', '$.k1'))`;
SELECT 'varchar' AS `typeof(get_json_object('varchar', '$.k1'))`;
SELECT 'varchar' AS `typeof(substr('{"k1":1, "k2":"v2"}', '$.k1'))`;
SELECT 'varchar' AS `typeof(get_json_object('varchar', '$.k1'))`;
SELECT 'varchar' AS `typeof(get_json_object('decimal128(19, 2)', '$.k1'))`;
SELECT 'varchar' AS `typeof(get_json_object('{"k1":1, "k2":"v2"}', '$.k1'))` ORDER BY 'varchar' ASC;
SELECT 'datetime' AS `typeof(date_add('{"k1":1, "k2":"v2"}', INTERVAL '$.k1' DAY))`;
SELECT 'varchar' AS `typeof(get_json_object('{"k1":1, "k2":"v2"}', '$.k1'))` ORDER BY 'varchar' ASC;
SELECT 'array<varchar>' AS `typeof(split('{"k1":1, "k2":"v2"}', '$.k1'))`;
SELECT 'varchar' AS `typeof(get_json_object('{"k1":1, "k2":"v2"}', '$.k1'))` GROUP BY 'varchar';
SELECT 'varchar' AS `typeof(get_json_object('{"k1":1, "k2":"v2"}', '1970-01-01'))`;
SELECT 'varchar' AS `typeof(get_json_object('{"k1":1, "k2":"v2"}', 'varchar'))`;
SELECT 'array<varchar>' AS `typeof(split('{"k1":1, "k2":"v2"}', '$.k1'))`;
SELECT 'varchar' AS `typeof('varchar')`;
SELECT 'varchar' AS `typeof(get_json_object('\\', '$.k1'))`;
SELECT 'varchar' AS `typeof(get_json_object('{"k1":1, "k2":"v2"}', '9999-12-31 23:59:59'))`;
SELECT DISTINCT 'varchar' AS `typeof(get_json_object('{"k1":1, "k2":"v2"}', '$.k1'))`;
SELECT 'varchar' AS `typeof('hll')`;
SELECT sum('varchar') OVER () AS `sum(typeof(get_json_object('{"k1":1, "k2":"v2"}', '$.k1'))) OVER ()`;
SELECT 'varchar' AS `typeof('map<tinyint,varchar>')`;
SELECT 'varchar' AS `typeof('struct<``col1`` tinyint, ``col2`` tinyint, ``col3`` tinyint, ``col4`` tinyint>')`;
SELECT 'struct<`col1` tinyint, `col2` tinyint, `col3` tinyint, `col4` tinyint>' AS `typeof(row(1, 2, 3, 4))` GROUP BY 'struct<`col1` tinyint, `col2` tinyint, `col3` tinyint, `col4` tinyint>';
SELECT 'struct<`col1` varchar, `col2` tinyint, `col3` tinyint, `col4` tinyint>' AS `typeof(row('struct<``col1`` tinyint, ``col2`` tinyint, ``col3`` tinyint, ``col4`` tinyint>', 2, 3, 4))`;
SELECT 'struct<`col1` tinyint, `col2` tinyint, `col3` tinyint, `col4` varchar>' AS `typeof(row(1, 2, 3, 'struct<``col1`` tinyint, ``col2`` tinyint, ``col3`` tinyint, ``col4`` tinyint>'))`;
SELECT 'struct<`col1` tinyint, `col2` boolean, `col3` tinyint, `col4` tinyint>' AS `typeof(row(1, NULL, 3, 4))`;
SELECT 'struct<`col1` tinyint, `col2` tinyint, `col3` tinyint, `col4` tinyint>' AS `typeof(row(1, 2, 3, 4))` WHERE 'int';
SELECT 'struct<`col1` tinyint, `col2` tinyint, `col3` varchar, `col4` tinyint>' AS `typeof(row(1, 2, 'struct<``col1`` tinyint, ``col2`` tinyint, ``col3`` tinyint, ``col4`` tinyint>', 4))`;
SELECT 'struct<`col1` tinyint, `col2` tinyint, `col3` tinyint, `col4` int>' AS `typeof(row(1, 2, 3, json_length(CAST(4 AS JSON))))`;
SELECT DISTINCT 'struct<`col1` tinyint, `col2` tinyint, `col3` tinyint, `col4` tinyint>' AS `typeof(row(1, 2, 3, 4))`;
SELECT 'struct<`col1` tinyint, `col2` tinyint, `col3` tinyint, `col4` tinyint>' AS `typeof(row(1, 2, 3, 4))` WHERE 'datetime';
SELECT 'struct<`col1` tinyint, `col2` tinyint, `col3` tinyint, `col4` double>' AS `typeof(row(1, 2, 3, 1.0E308))`;
SELECT 'struct<`col1` tinyint, `col2` tinyint, `col3` tinyint, `col4` tinyint>' AS `typeof(row(1, 2, 3, 0))`;
SELECT 'struct<`col1` tinyint, `col2` tinyint, `col3` varchar, `col4` tinyint>' AS `typeof(row(1, 2, 'struct<``col1`` tinyint, ``col2`` tinyint, ``col3`` tinyint, ``col4`` tinyint>', 4))`;
SELECT DISTINCT 'struct<`col1` tinyint, `col2` tinyint, `col3` tinyint, `col4` tinyint>' AS `typeof(row(1, 2, 3, 4))`;
SELECT 'varchar' AS `typeof('struct<``col1`` tinyint, ``col2`` tinyint, ``col3`` tinyint, ``col4`` tinyint>')`;
SELECT 'varchar' AS `typeof('bigint')`;
SELECT 'struct<`col1` tinyint, `col2` tinyint, `col3` varchar, `col4` tinyint>' AS `typeof(row(1, 2, 'struct<``col1`` tinyint, ``col2`` tinyint, ``col3`` tinyint, ``col4`` tinyint>', 4))`;
SELECT 'struct<`col1` json, `col2` tinyint, `col3` tinyint, `col4` tinyint>' AS `typeof(row(CAST(1 AS JSON)->'$.a', 2, 3, 4))`;
SELECT 'struct<`col1` double, `col2` tinyint, `col3` tinyint, `col4` tinyint>' AS `typeof(row(1.0E308, 2, 3, 4))`;
SELECT 'struct<`col1` tinyint, `col2` tinyint, `col3` tinyint, `col4` tinyint>' AS `typeof(row(1, 2, 3, 4))` LIMIT 5;
SELECT 'struct<`col1` tinyint, `col2` decimal32(1, 1), `col3` tinyint, `col4` tinyint>' AS `typeof(row(1, 0.0, 3, 4))`;
SELECT 'struct<`col1` tinyint, `col2` tinyint, `col3` tinyint, `col4` tinyint>' AS `typeof(row(1, 2, 3, -1))`;
SELECT 'struct<`col1` tinyint, `col2` tinyint, `col3` tinyint, `col4` varchar>' AS `typeof(row(1, 2, 3, 'struct<``col1`` tinyint, ``col2`` tinyint, ``col3`` tinyint, ``col4`` tinyint>'))`;
SELECT 'struct<`col1` tinyint, `col2` tinyint, `col3` tinyint, `col4` tinyint>' AS `typeof(row(1, 2, 3, 1))`;
SELECT 'varchar' AS `typeof('bitmap')`;
SELECT 'varchar' AS `typeof('json')`;
SELECT 'varchar' AS `typeof('bitmap')`;
SELECT 'varchar' AS `typeof('largeint')`;
SELECT 'varchar' AS `typeof('hll')`;
SELECT 'varchar' AS `typeof('bitmap')`;
SELECT 'bitmap' AS `typeof(bitmap_empty())` GROUP BY 'bitmap';
SELECT 'varchar' AS `typeof('bitmap')`;
SELECT 'varchar' AS `typeof('bitmap')`;
SELECT 'varchar' AS `typeof('largeint')`;
SELECT 'varchar' AS `typeof('bitmap')`;
SELECT 'varchar' AS `typeof('bitmap')`;
SELECT DISTINCT 'bitmap' AS `typeof(bitmap_empty())`;
SELECT 'varchar' AS `typeof('bitmap')`;
SELECT 'varchar' AS `typeof('bitmap')`;
SELECT 'varchar' AS `typeof('bitmap')`;
SELECT 'bitmap' AS `typeof(bitmap_empty())` ORDER BY 'varchar' DESC;
SELECT 'bitmap' AS `typeof(bitmap_empty())` LIMIT 7, 5;
SELECT 'varchar' AS `typeof('largeint')`;
SELECT 'varchar' AS `typeof('bitmap')`;
SELECT 'bitmap' AS `typeof(bitmap_empty())` ORDER BY 'varchar' ASC;
SELECT 'varchar' AS `typeof('float')`;
SELECT 'bitmap' AS `typeof(bitmap_empty())` WHERE 'null_type';
SELECT 'varchar' AS `typeof('bitmap')`;
SELECT 'varchar' AS `typeof('hll')`;
SELECT 'varchar' AS `typeof('bitmap')`;
SELECT 'varchar' AS `typeof('boolean')`;
SELECT 'varchar' AS `typeof('varchar')`;
SELECT 'bitmap' AS `typeof(bitmap_empty())` WHERE 'datetime';
SELECT 'varchar' AS `typeof('bitmap')`;
SELECT 'varchar' AS `typeof('bitmap')`;
SELECT 'varchar' AS `typeof('bitmap')`;
SELECT 'hll' AS `typeof(hll_empty())` LIMIT 7, 100;
SELECT 'varchar' AS `typeof('hll')`;
SELECT 'hll' AS `typeof(hll_empty())` LIMIT 100;
SELECT 'varchar' AS `typeof('hll')`;
SELECT 'hll' AS `typeof(hll_empty())` LIMIT 1, 0;
SELECT 'varchar' AS `typeof('hll')`;
SELECT 'varchar' AS `typeof('hll')`;
SELECT 'varchar' AS `typeof('hll')`;
SELECT 'varchar' AS `typeof('hll')`;
SELECT 'varchar' AS `typeof('hll')`;
SELECT count('hll') OVER () AS `count(typeof(hll_empty())) OVER ()`;
SELECT 'hll' AS `typeof(hll_empty())` ORDER BY 'varchar' DESC NULLS FIRST;
SELECT 'hll' AS `typeof(hll_empty())` ORDER BY 'varchar' DESC;
SELECT 'hll' AS `typeof(hll_empty())` LIMIT 5;
SELECT 'hll' AS `typeof(hll_empty())` WHERE 'smallint';
SELECT 'varchar' AS `typeof('hll')`;
SELECT 'varchar' AS `typeof('hll')`;
SELECT 'varchar' AS `typeof('hll')`;
SELECT 'varchar' AS `typeof('hll')`;
SELECT 'varchar' AS `typeof('double')`;
SELECT 'hll' AS `typeof(hll_empty())` ORDER BY 'varchar' ASC;
SELECT 'varchar' AS `typeof('hll')`;
SELECT 'varchar' AS `typeof('hll')`;
SELECT 'hll' AS `typeof(hll_empty())` GROUP BY 'hll';
SELECT 'varchar' AS `typeof('hll')`;
SELECT 'hll' AS `typeof(hll_empty())` ORDER BY 'varchar' ASC;
SELECT 'varchar' AS `typeof('struct<``col1`` tinyint, ``col2`` tinyint, ``col3`` tinyint, ``col4`` tinyint>')`;
SELECT 'varchar' AS `typeof('hll')`;
SELECT 'varchar' AS `typeof('hll')`;
SELECT 'json' AS `typeof(parse_json('{"a": 1, "b": true}'))` ORDER BY 'varchar' ASC;
SELECT 'varchar' AS `typeof(unhex('{"a": 1, "b": true}'))`;
SELECT 'json' AS `typeof(parse_json(170141183460469231731687303715884105727))`;
SELECT 'varchar' AS `typeof(hex('{"a": 1, "b": true}'))`;
SELECT 'json' AS `typeof(parse_json('{"a": 1, "b": true}'))` ORDER BY 'varchar' DESC;
SELECT 'json' AS `typeof(parse_json(0.0))`;
SELECT 'json' AS `typeof(parse_json('{"a": 1, "b": true}'))` GROUP BY 'json';
SELECT 'varchar' AS `typeof(unhex('{"a": 1, "b": true}'))`;
SELECT 'varchar' AS `typeof(md5('{"a": 1, "b": true}'))`;
SELECT 'varchar' AS `typeof('json')`;
SELECT 'varchar' AS `typeof('json')`;
SELECT 'varchar' AS `typeof('bigint')`;
SELECT 'json' AS `typeof(parse_json('{"a": 1, "b": true}'))` LIMIT 1, 2;
SELECT 'json' AS `typeof(parse_json('{"a": 1, "b": true}'))` GROUP BY 'json';
SELECT 'json' AS `typeof(parse_json('{"a": 1, "b": true}'))` ORDER BY 'varchar' ASC;
SELECT 'varchar' AS `typeof('json')`;
SELECT 'bigint' AS `typeof(ceil('{"a": 1, "b": true}'))`;
SELECT 'json' AS `typeof(parse_json('{"a": 1, "b": true}'))` GROUP BY 'json';
SELECT DISTINCT 'json' AS `typeof(parse_json('{"a": 1, "b": true}'))`;
SELECT 'json' AS `typeof(parse_json('json'))`;
SELECT 'json' AS `typeof(parse_json('{"a": 1, "b": true}'))` WHERE 'null_type';
SELECT 'json' AS `typeof(parse_json('json'))`;
SELECT 'bigint' AS `typeof(bitmap_count('{"a": 1, "b": true}'))`;
SELECT sum('json') OVER () AS `sum(typeof(parse_json('{"a": 1, "b": true}'))) OVER ()`;
SELECT 'json' AS `typeof(parse_json(2147483647))`;
SELECT 'json' AS `typeof(parse_json('1970-01-01'))`;
SELECT 'json' AS `typeof(parse_json('{"a": 1, "b": true}'))` WHERE 'null_type';
SELECT 'json' AS `typeof(parse_json('{"a": 1, "b": true}'))` ORDER BY 'varchar' ASC NULLS LAST;
SELECT 'json' AS `typeof(parse_json('{"a": 1, "b": true}'))` GROUP BY 'json';
SELECT 'json' AS `typeof(parse_json('json'))`;
SELECT 'int' AS `typeof(length('{"a": 1, "b": true}'))`;
SELECT 'varchar' AS `typeof('null_type')`;
SELECT 'null_type' AS `typeof(NULL)` ORDER BY 'varchar' DESC;
SELECT 'tinyint' AS `typeof(0)`;
SELECT 'varchar' AS `typeof('hll')`;
SELECT min('null_type') OVER () AS `min(typeof(NULL)) OVER ()`;
SELECT 'boolean' AS `typeof(FALSE)`;
SELECT 'varchar' AS `typeof('null_type')`;
SELECT 'varchar' AS `typeof('0')`;
SELECT 'null_type' AS `typeof(NULL)` ORDER BY 'varchar' DESC;
SELECT 'varchar' AS `typeof('null_type')`;
SELECT 'null_type' AS `typeof(NULL)` ORDER BY 'varchar' ASC;
SELECT 'null_type' AS `typeof(NULL)` LIMIT 100;
SELECT 'varchar' AS `typeof('null_type')`;
SELECT 'null_type' AS `typeof(NULL)` GROUP BY 'null_type';
SELECT 'varchar' AS `typeof('0')`;
SELECT 'varchar' AS `typeof('null_type')`;
SELECT 'varchar' AS `typeof('null_type')`;
SELECT DISTINCT 'null_type' AS `typeof(NULL)`;
SELECT 'null_type' AS `typeof(NULL)` ORDER BY 'varchar' DESC;
SELECT 'varchar' AS `typeof('1970-01-01')`;
SELECT 'double' AS `typeof(-1.0E308)`;
SELECT 'null_type' AS `typeof(NULL)` WHERE 'tinyint';
SELECT 'varchar' AS `typeof('null_type')`;
SELECT 'varchar' AS `typeof('null_type')`;
SELECT 'null_type' AS `typeof(NULL)` WHERE 'varbinary';
SELECT 'varchar' AS `typeof('\\')`;
SELECT 'varchar' AS `typeof('null_type')`;
SELECT 'json' AS `typeof(CAST(NULL AS JSON)->'$')`;
SELECT 'varchar' AS `typeof('null_type')`;
SELECT 'varchar' AS `typeof(repeat('x', 65536))`;
SELECT 'varchar' AS `typeof('null_type')`;
SELECT 'null_type' AS `typeof(NULL)` LIMIT 100;
SELECT 'varchar' AS `typeof('bitmap')` FROM `srfuzz_mut_446`.`pv_bitmap`;
SELECT 'varchar' AS `typeof('bitmap')` FROM `srfuzz_mut_446`.`pv_bitmap`;
SELECT 'varchar' AS `typeof('bitmap')` FROM `srfuzz_mut_446`.`pv_bitmap`;
SELECT 'varchar' AS `typeof('float')` FROM `srfuzz_mut_446`.`pv_bitmap`;
SELECT 'bitmap' AS `typeof(user_id)` FROM `srfuzz_mut_446`.`pv_bitmap` ORDER BY 'varchar' DESC;
SELECT 'varchar' AS `typeof('bitmap')` FROM `srfuzz_mut_446`.`pv_bitmap`;
SELECT 'bitmap' AS `typeof(user_id)` FROM (SELECT `srfuzz_mut_446`.`pv_bitmap`.`dt`, `srfuzz_mut_446`.`pv_bitmap`.`page`, `srfuzz_mut_446`.`pv_bitmap`.`user_id` FROM `srfuzz_mut_446`.`pv_bitmap` UNION ALL SELECT `srfuzz_mut_446`.`pv_bitmap`.`dt`, `srfuzz_mut_446`.`pv_bitmap`.`page`, `srfuzz_mut_446`.`pv_bitmap`.`user_id` FROM `srfuzz_mut_446`.`pv_bitmap`) `pv_bitmap`;
SELECT 'bitmap' AS `typeof(user_id)` FROM `srfuzz_mut_446`.`pv_bitmap` LIMIT 5;
SELECT 'varchar' AS `typeof('bitmap')` FROM `srfuzz_mut_446`.`pv_bitmap`;
SELECT count('bitmap') OVER () AS `count(typeof(user_id)) OVER ()` FROM `srfuzz_mut_446`.`pv_bitmap`;
SELECT 'varchar' AS `typeof('bitmap')` FROM `srfuzz_mut_446`.`pv_bitmap`;
SELECT 'varchar' AS `typeof('bitmap')` FROM `srfuzz_mut_446`.`pv_bitmap`;
SELECT 'varchar' AS `typeof('bitmap')` FROM `srfuzz_mut_446`.`pv_bitmap`;
SELECT 'bitmap' AS `typeof(user_id)` FROM (SELECT `srfuzz_mut_446`.`pv_bitmap`.`dt`, `srfuzz_mut_446`.`pv_bitmap`.`page`, `srfuzz_mut_446`.`pv_bitmap`.`user_id` FROM `srfuzz_mut_446`.`pv_bitmap`) `pv_bitmap`;
SELECT 'varchar' AS `typeof('bitmap')` FROM `srfuzz_mut_446`.`pv_bitmap`;
SELECT 'varchar' AS `typeof('bitmap')` FROM `srfuzz_mut_446`.`pv_bitmap`;
SELECT 'varchar' AS `typeof('bitmap')` FROM `srfuzz_mut_446`.`pv_bitmap`;
SELECT 'varchar' AS `typeof('bitmap')` FROM `srfuzz_mut_446`.`pv_bitmap`;
SELECT 'varchar' AS `typeof('bitmap')` FROM `srfuzz_mut_446`.`pv_bitmap`;
SELECT 'varchar' AS `typeof('bitmap')` FROM `srfuzz_mut_446`.`pv_bitmap`;
SELECT 'bitmap' AS `typeof(user_id)` FROM `srfuzz_mut_446`.`pv_bitmap` LIMIT 0;
SELECT 'bitmap' AS `typeof(user_id)` FROM `srfuzz_mut_446`.`pv_bitmap` GROUP BY 'bitmap';
SELECT 'bitmap' AS `typeof(user_id)` FROM (SELECT `srfuzz_mut_446`.`pv_bitmap`.`dt`, `srfuzz_mut_446`.`pv_bitmap`.`page`, `srfuzz_mut_446`.`pv_bitmap`.`user_id` FROM `srfuzz_mut_446`.`pv_bitmap`) `pv_bitmap` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT 'bitmap' AS `typeof(user_id)` FROM (SELECT `srfuzz_mut_446`.`pv_bitmap`.`dt`, `srfuzz_mut_446`.`pv_bitmap`.`page`, `srfuzz_mut_446`.`pv_bitmap`.`user_id` FROM `srfuzz_mut_446`.`pv_bitmap`) `pv_bitmap` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT 'varchar' AS `typeof('smallint')` FROM `srfuzz_mut_446`.`pv_bitmap`;
SELECT 'bitmap' AS `typeof(user_id)` FROM (SELECT `srfuzz_mut_446`.`pv_bitmap`.`dt`, `srfuzz_mut_446`.`pv_bitmap`.`page`, `srfuzz_mut_446`.`pv_bitmap`.`user_id` FROM `srfuzz_mut_446`.`pv_bitmap`) `pv_bitmap`;
SELECT 'bitmap' AS `typeof(user_id)` FROM `srfuzz_mut_446`.`pv_bitmap` WHERE 'smallint';
SELECT 'varchar' AS `typeof('bitmap')` FROM `srfuzz_mut_446`.`pv_bitmap`;
SELECT 'bitmap' AS `typeof(user_id)` FROM `srfuzz_mut_446`.`pv_bitmap` WHERE 'hll';
SELECT 'varchar' AS `typeof('bitmap')` FROM `srfuzz_mut_446`.`pv_bitmap`;
SELECT 'varchar' AS `typeof('bitmap')` FROM `srfuzz_mut_446`.`pv_bitmap`;
SELECT 'varchar' AS `typeof('datetime')` FROM `srfuzz_mut_446`.`pv_bitmap`;
SELECT 'varchar' AS `typeof('bitmap')` FROM `srfuzz_mut_446`.`pv_bitmap`;
SELECT 'varchar' AS `typeof('hll')` FROM `srfuzz_mut_446`.`test_uv`;
SELECT 'hll' AS `typeof(uv_set)` FROM `srfuzz_mut_446`.`test_uv` ORDER BY 'varchar' ASC NULLS LAST;
SELECT 'varchar' AS `typeof('hll')` FROM `srfuzz_mut_446`.`test_uv`;
SELECT 'hll' AS `typeof(uv_set)` FROM `srfuzz_mut_446`.`test_uv` LIMIT 7, 5;
SELECT 'varchar' AS `typeof('hll')` FROM `srfuzz_mut_446`.`test_uv`;
SELECT 'varchar' AS `typeof('hll')` FROM `srfuzz_mut_446`.`test_uv`;
SELECT min('hll') OVER () AS `min(typeof(uv_set)) OVER ()` FROM `srfuzz_mut_446`.`test_uv`;
SELECT 'hll' AS `typeof(uv_set)` FROM `srfuzz_mut_446`.`test_uv` LIMIT 1;
SELECT 'varchar' AS `typeof('hll')` FROM `srfuzz_mut_446`.`test_uv`;
SELECT 'varchar' AS `typeof('hll')` FROM `srfuzz_mut_446`.`test_uv`;
SELECT 'hll' AS `typeof(uv_set)` FROM `srfuzz_mut_446`.`test_uv` ORDER BY 'varchar' ASC;
SELECT 'varchar' AS `typeof('hll')` FROM `srfuzz_mut_446`.`test_uv`;
SELECT 'hll' AS `typeof(uv_set)` FROM `srfuzz_mut_446`.`test_uv` GROUP BY 'hll';
SELECT 'varchar' AS `typeof('hll')` FROM `srfuzz_mut_446`.`test_uv`;
SELECT 'varchar' AS `typeof('hll')` FROM `srfuzz_mut_446`.`test_uv`;
SELECT 'varchar' AS `typeof('hll')` FROM `srfuzz_mut_446`.`test_uv`;
SELECT 'varchar' AS `typeof('hll')` FROM `srfuzz_mut_446`.`test_uv`;
SELECT 'varchar' AS `typeof('hll')` FROM `srfuzz_mut_446`.`test_uv`;
SELECT 'varchar' AS `typeof('hll')` FROM `srfuzz_mut_446`.`test_uv`;
SELECT 'varchar' AS `typeof('hll')` FROM `srfuzz_mut_446`.`test_uv`;
SELECT 'varchar' AS `typeof('hll')` FROM `srfuzz_mut_446`.`test_uv`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_446`.`test_uv`.`dt`, `srfuzz_mut_446`.`test_uv`.`id`, `srfuzz_mut_446`.`test_uv`.`uv_set` FROM `srfuzz_mut_446`.`test_uv`) SELECT 'hll' AS `typeof(uv_set)` FROM `srfuzz_n1` AS test_uv;
SELECT 'varchar' AS `typeof('hll')` FROM `srfuzz_mut_446`.`test_uv`;
SELECT 'varchar' AS `typeof('hll')` FROM `srfuzz_mut_446`.`test_uv`;
SELECT 'varchar' AS `typeof('hll')` FROM `srfuzz_mut_446`.`test_uv`;
SELECT 'varchar' AS `typeof('hll')` FROM `srfuzz_mut_446`.`test_uv`;