SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT sum(`table_function_generate_series`.`generate_series`) AS `sum(generate_series)` FROM TABLE(generate_series(0,8000,1));
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(srfuzz_mut_181.t1.c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1` LIMIT 5;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(srfuzz_mut_181.t1.c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1` GROUP BY bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`);
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(srfuzz_mut_181.t1.c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT DISTINCT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(srfuzz_mut_181.t1.c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1` WHERE 8000;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(srfuzz_mut_181.t1.c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(srfuzz_mut_181.t1.c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_181`.`t1`.`c1`, `srfuzz_mut_181`.`t1`.`c2` FROM `srfuzz_mut_181`.`t1`) SELECT bitmap_to_array(`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_n1` AS t1;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(srfuzz_mut_181.t1.c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`t1`.`c2`) AS `bitmap_to_array(c2)` FROM (SELECT `srfuzz_mut_181`.`t1`.`c1`, `srfuzz_mut_181`.`t1`.`c2` FROM `srfuzz_mut_181`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`)[-2147483648] AS `bitmap_to_array(c2)[-2147483648]` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(srfuzz_mut_181.t1.c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1` WHERE 1;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(srfuzz_mut_181.t1.c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`t1`.`c2`) AS `bitmap_to_array(c2)` FROM (SELECT `srfuzz_mut_181`.`t1`.`c1`, `srfuzz_mut_181`.`t1`.`c2` FROM `srfuzz_mut_181`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(srfuzz_mut_181.t1.c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(srfuzz_mut_181.t1.c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(srfuzz_mut_181.t1.c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1` GROUP BY bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`);
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1` WHERE 1;
SELECT bitmap_to_array(`t1`.`c2`) AS `bitmap_to_array(c2)` FROM (SELECT `srfuzz_mut_181`.`t1`.`c1`, `srfuzz_mut_181`.`t1`.`c2` FROM `srfuzz_mut_181`.`t1` UNION ALL SELECT `srfuzz_mut_181`.`t1`.`c1`, `srfuzz_mut_181`.`t1`.`c2` FROM `srfuzz_mut_181`.`t1`) `t1`;
SELECT bitmap_to_array(`t1`.`c2`) AS `bitmap_to_array(c2)` FROM (SELECT `srfuzz_mut_181`.`t1`.`c1`, `srfuzz_mut_181`.`t1`.`c2` FROM `srfuzz_mut_181`.`t1`) `t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(srfuzz_mut_181.t1.c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(srfuzz_mut_181.t1.c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1` WHERE 0;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1` GROUP BY bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`);
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(srfuzz_mut_181.t1.c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1` GROUP BY bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`);
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(srfuzz_mut_181.t1.c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT count(bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`)) OVER () AS `count(bitmap_to_array(c2)) OVER ()` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(srfuzz_mut_181.t1.c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`)[-2147483648] AS `bitmap_to_array(c2)[-2147483648]` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1` LIMIT 7, 1;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1` GROUP BY bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`);
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(srfuzz_mut_181.t1.c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1` LIMIT 7, 100;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1` LIMIT 100;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(srfuzz_mut_181.t1.c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`t1`.`c2`) AS `bitmap_to_array(c2)` FROM (SELECT `srfuzz_mut_181`.`t1`.`c1`, `srfuzz_mut_181`.`t1`.`c2` FROM `srfuzz_mut_181`.`t1` UNION ALL SELECT `srfuzz_mut_181`.`t1`.`c1`, `srfuzz_mut_181`.`t1`.`c2` FROM `srfuzz_mut_181`.`t1`) `t1`;
SELECT bitmap_to_array(`t1`.`c2`) AS `bitmap_to_array(c2)` FROM (SELECT `srfuzz_mut_181`.`t1`.`c1`, `srfuzz_mut_181`.`t1`.`c2` FROM `srfuzz_mut_181`.`t1`) `t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1` GROUP BY bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`);
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(srfuzz_mut_181.t1.c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1` WHERE 8000;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(srfuzz_mut_181.t1.c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(srfuzz_mut_181.t1.c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`t1`.`c2`) AS `bitmap_to_array(c2)` FROM (SELECT `srfuzz_mut_181`.`t1`.`c1`, `srfuzz_mut_181`.`t1`.`c2` FROM `srfuzz_mut_181`.`t1`) `t1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`t1`.`c2`) AS `bitmap_to_array(c2)` FROM (SELECT `srfuzz_mut_181`.`t1`.`c1`, `srfuzz_mut_181`.`t1`.`c2` FROM `srfuzz_mut_181`.`t1` UNION ALL SELECT `srfuzz_mut_181`.`t1`.`c1`, `srfuzz_mut_181`.`t1`.`c2` FROM `srfuzz_mut_181`.`t1`) `t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1` LIMIT 5;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1` LIMIT 7, 0;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(srfuzz_mut_181.t1.c2)` FROM `srfuzz_mut_181`.`t1`;
SELECT bitmap_to_array(`srfuzz_mut_181`.`t1`.`c2`) AS `bitmap_to_array(c2)` FROM `srfuzz_mut_181`.`t1` LIMIT 2;
SELECT sum(8000) AS `sum(8000)` FROM TABLE(generate_series(0,8000,1));
SELECT sum(0) AS `sum(0)` FROM TABLE(generate_series(0,8000,1));
SELECT sum(`table_function_generate_series`.`generate_series`) AS `sum(generate_series)` FROM TABLE(generate_series(0,8000,1));
SELECT sum(`table_function_generate_series`.`generate_series`) AS `sum(generate_series)` FROM TABLE(generate_series(0,8000,1));
SELECT sum(`table_function_generate_series`.`generate_series`) AS `sum(table_function_generate_series.generate_series)` FROM TABLE(generate_series(0,8000,1));
SELECT sum(`table_function_generate_series`.`generate_series`) AS `sum(generate_series)` FROM TABLE(generate_series(0,8000,1)) HAVING (count(*)) > 1;
SELECT sum(`table_function_generate_series`.`generate_series`) AS `sum(generate_series)` FROM TABLE(generate_series(0,8000,1));
SELECT sum(`table_function_generate_series`.`generate_series`) AS `sum(generate_series)` FROM TABLE(generate_series(0,8000,1));
SELECT sum(`table_function_generate_series`.`generate_series`) AS `sum(generate_series)` FROM TABLE(generate_series(0,8000,1));
SELECT sum(`table_function_generate_series`.`generate_series`) AS `sum(generate_series)` FROM TABLE(generate_series(0,8000,1)) HAVING (count(*)) >= 2;
SELECT sum(`table_function_generate_series`.`generate_series`) AS `sum(generate_series)` FROM TABLE(generate_series(0,8000,1)) ORDER BY sum(`table_function_generate_series`.`generate_series`) ASC;
SELECT sum(`table_function_generate_series`.`generate_series`) AS `sum(table_function_generate_series.generate_series)` FROM TABLE(generate_series(0,8000,1));
SELECT sum(`table_function_generate_series`.`generate_series`) AS `sum(generate_series)` FROM TABLE(generate_series(0,8000,1));
SELECT sum(8000) AS `sum(8000)` FROM TABLE(generate_series(0,8000,1));
SELECT sum(`table_function_generate_series`.`generate_series`) AS `sum(table_function_generate_series.generate_series)` FROM TABLE(generate_series(0,8000,1));
SELECT sum(`table_function_generate_series`.`generate_series`) AS `sum(generate_series)` FROM TABLE(generate_series(0,8000,1));
SELECT sum(`table_function_generate_series`.`generate_series`) AS `sum(generate_series)` FROM TABLE(generate_series(0,8000,1));
SELECT sum(`table_function_generate_series`.`generate_series`) AS `sum(generate_series)` FROM TABLE(generate_series(0,8000,1));
SELECT sum(CAST(`table_function_generate_series`.`generate_series` AS DOUBLE)) AS `sum(CAST(generate_series AS DOUBLE))` FROM TABLE(generate_series(0,8000,1));
SELECT sum(8000) AS `sum(8000)` FROM TABLE(generate_series(0,8000,1));
SELECT sum(`table_function_generate_series`.`generate_series`) AS `sum(generate_series)` FROM TABLE(generate_series(0,8000,1)) LIMIT 1, 1;
SELECT sum(`table_function_generate_series`.`generate_series`) AS `sum(generate_series)` FROM TABLE(generate_series(0,8000,1));
SELECT sum(`table_function_generate_series`.`generate_series`) AS `sum(table_function_generate_series.generate_series)` FROM TABLE(generate_series(0,8000,1));