SELECT json_set('{"a": 1, "b": 2}', '$.a', 10) AS `update_existing`;
SELECT json_set('{"a": 1}', '$.b', 2) AS `insert_new`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', 10, '$.c', 3) AS `mixed_ops`;
SELECT json_set('{"a": {"x": 1, "y": 2}}', '$.a.x', 100) AS `update_nested`;
SELECT json_set('{"a": {"x": 1}}', '$.a.y', 200) AS `insert_nested`;
SELECT json_set('{"level1": {"level2": {"target": "old"}}}', '$.level1.level2.target', 'new') AS `deep_update`;
SELECT json_set('{"arr": [10, 20, 30]}', '$.arr[1]', 99) AS `update_array_index`;
SELECT json_set('{"arr": [10, 20]}', '$.arr[100]', 30) AS `append_array`;
SELECT json_set('[1, 2, 3]', '$[0]', 9) AS `root_array_update`;
SELECT json_set('{"a": 1}', '$.a.b', 2) AS `set_on_scalar`;
SELECT json_set('{"a": 1}', '$.missing_parent.child', 2) AS `missing_parent`;
SELECT json_set('{"a": 1}', '$', '{"new": "doc"}') AS `replace_root`;
SELECT if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, 'NULL_OK', 'FAIL') AS `set_sql_null`;
SELECT json_set('{"k": "old"}', '$.k', parse_json('null')) AS `set_json_null`;
SELECT json_set('{"k": "old"}', '$.k', TRUE) AS `set_bool`;
SELECT json_set('{"k": "old"}', '$.k', parse_json('{"sub": "json"}')) AS `set_json_object`;
SELECT json_set('{"k": "old"}', '$.k', 123.456) AS `set_double`;
SELECT json_set('{"a": 1}', '$.a', 10, '$.b', 20, '$.a', 30) AS `chain_override`;
SELECT `srfuzz_mut_686`.`json_set_test_table`.`id`, json_set(`srfuzz_mut_686`.`json_set_test_table`.`data`, '$.score', 100) AS `json_set(data, '$.score', 100)` FROM `srfuzz_mut_686`.`json_set_test_table` WHERE `srfuzz_mut_686`.`json_set_test_table`.`id` = 2;
SELECT `srfuzz_mut_686`.`json_set_test_table`.`id`, json_set(`srfuzz_mut_686`.`json_set_test_table`.`data`, '$.city', 'Wonderland') AS `json_set(data, '$.city', 'Wonderland')` FROM `srfuzz_mut_686`.`json_set_test_table` WHERE `srfuzz_mut_686`.`json_set_test_table`.`id` = 1;
SELECT `srfuzz_mut_686`.`json_set_test_table`.`id`, json_set(`srfuzz_mut_686`.`json_set_test_table`.`data`, '$.tags[1]', 'B') AS `json_set(data, '$.tags[1]', 'B')` FROM `srfuzz_mut_686`.`json_set_test_table` WHERE `srfuzz_mut_686`.`json_set_test_table`.`id` = 1;
SELECT `srfuzz_mut_686`.`json_set_test_table`.`id`, if((json_set(`srfuzz_mut_686`.`json_set_test_table`.`data`, '$.a', 1)) IS NULL, 'NULL_OK', 'FAIL') AS `if((json_set(data, '$.a', 1)) IS NULL, 'NULL_OK', 'FAIL')` FROM `srfuzz_mut_686`.`json_set_test_table` WHERE `srfuzz_mut_686`.`json_set_test_table`.`id` = 3;
SELECT if((json_set(NULL, '$.a', 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_doc`;
SELECT if((json_set('{"a": 1}', NULL, 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path`;
SELECT if((json_set('{"a": 1}', '$.a', 1, NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2`;
SELECT json_set('{"a": 1}', '$."key.with.dot"', 2) AS `escaped_key`;
SELECT json_set('{"a": [1, 2]}', '$.a[*]', 10) AS `json_set('{"a": [1, 2]}', '$.a[*]', 10)`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', 0) AS `update_existing`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', NULL) AS `update_existing`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', 10) AS `update_existing`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', 10) AS `update_existing`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', 10) AS `update_existing` WHERE (json_set(NULL, '$.a', 1)) IS NULL;
SELECT json_set('{"a": 1, "b": 2}', 10, 10) AS `update_existing`;
SELECT json_set('{"a": 1, "b": 2}', 2147483647, 10) AS `update_existing`;
SELECT json_set(TRUE, '$.a', 10) AS `update_existing`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', '$.a') AS `update_existing`;
SELECT json_set('{"a": 1, "b": 2}', '{"a": 1, "b": 2}', 10) AS `update_existing`;
SELECT json_set('$.a', '$.a', 10) AS `update_existing`;
SELECT json_set('{"a": 1, "b": 2}', FALSE, 10) AS `update_existing`;
SELECT json_set('{"a": 1, "b": 2}', 0, 10) AS `update_existing`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', '{"a": 1, "b": 2}') AS `update_existing`;
SELECT json_set('%', '$.a', 10) AS `update_existing`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', 10) AS `update_existing`;
SELECT json_set('{"a": 1, "b": 2}', '[1, 2, 3]', 10) AS `update_existing`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', 10) AS `update_existing`;
SELECT json_set('{"a": 1, "b": 2}', json_set('{"a": 1, "b": 2}', '$.a', 10), 10) AS `update_existing`;
SELECT json_set(json_set('{"a": 1, "b": 2}', '$.a', 10), '$.a', 10) AS `update_existing`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', '$.a') AS `update_existing`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', '$.city') AS `update_existing`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', 10) AS `update_existing`;
SELECT json_set(0.0, '$.a', 10) AS `update_existing`;
SELECT json_set('{"a": 1, "b": 2}', 0.0, 10) AS `update_existing`;
SELECT json_set(repeat('x', 65536), '$.b', 2) AS `insert_new`;
SELECT json_set('{"a": 1}', '$.b', 99) AS `insert_new`;
SELECT json_set('{"a": 1}', '$.b', 2) AS `insert_new`;
SELECT json_set('{"a": 1}', '$.b', 2) AS `insert_new` LIMIT 7, 1;
SELECT CAST((json_set('{"a": 1}', '$.b', 2)) AS JSON)->'$.a' AS `insert_new`;
SELECT json_set('{"a": 1}', '$.b', 2) AS `insert_new` WHERE (json_set(NULL, '$.a', 1)) IS NULL;
SELECT json_set('{"a": 1}', '$.b', json_set('{"a": 1}', '$.b', 2)) AS `insert_new`;
SELECT json_set('{"a": 1}', CAST('$.b' AS JSON)->'$.a', 2) AS `insert_new`;
SELECT json_set('{"a": 1}', 2, 2) AS `insert_new`;
SELECT json_set('', '$.b', 2) AS `insert_new`;
SELECT json_set('{"a": 1}', '$.b', '$.a.y') AS `insert_new`;
SELECT json_set('{"a": 1}', NULL, 2) AS `insert_new`;
SELECT json_set('$.b', '$.b', 2) AS `insert_new`;
SELECT json_set('{"a": 1}', '$.b', NULL) AS `insert_new`;
SELECT json_set('{"a": 1}', '$.b', repeat('x', 65536)) AS `insert_new`;
SELECT json_set('{"a": 1}', '$.b', 2) AS `insert_new` WHERE (json_set('{"k": "old"}', '$.k', NULL)) IS NULL;
SELECT json_set('{"a": 1}', '$.b', CAST(2 AS JSON)->'$.a') AS `insert_new`;
SELECT json_set('{"a": 1}', FALSE, 2) AS `insert_new`;
SELECT json_set('{"a": 1}', '$.b', 2) AS `insert_new` WHERE (json_set(NULL, '$.a', 1)) IS NULL;
SELECT json_set('{"a": 1}', '$.b', '0') AS `insert_new`;
SELECT json_set('{"a": 1}', '$.b', 2) AS `insert_new` WHERE (json_set('{"a": 1}', NULL, 1)) IS NULL;
SELECT json_set('{"a": 1}', '$.b', 2) AS `insert_new` LIMIT 1, 100;
SELECT json_set('{"a": 1}', '$.b', json_set('{"a": 1}', '$.b', 2)) AS `insert_new`;
SELECT json_set('{"a": 1}', '1970-01-01', 2) AS `insert_new`;
SELECT json_set('{"a": 1, "b": 2}', 3, 10, '$.c', 3) AS `mixed_ops`;
SELECT count(json_set('{"a": 1, "b": 2}', '$.a', 10, '$.c', 3)) OVER () AS `mixed_ops`;
SELECT json_set(3, '$.a', 10, '$.c', 3) AS `mixed_ops`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', 10, '$.c', 3) AS `mixed_ops`;
SELECT json_set('{"a": 1, "b": 2}', '%', 10, '$.c', 3) AS `mixed_ops`;
SELECT json_set('{"a": 1, "b": 2}', 3, 10, '$.c', 3) AS `mixed_ops`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', 10, 170141183460469231731687303715884105727, 3) AS `mixed_ops`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', 'Wonderland', '$.c', 3) AS `mixed_ops`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', 10, '$.c', -1.0E308) AS `mixed_ops`;
SELECT json_set(0.0, '$.a', 10, '$.c', 3) AS `mixed_ops`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', 1.0E308, '$.c', 3) AS `mixed_ops`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', 10, 0.0, 3) AS `mixed_ops`;
SELECT json_set(json_set('{"a": 1, "b": 2}', '$.a', 10, '$.c', 3), '$.a', 10, '$.c', 3) AS `mixed_ops`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', 10, 3, 3) AS `mixed_ops`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', 10, '$.c', CAST(3 AS JSON)->'$') AS `mixed_ops`;
SELECT json_set('$.c', '$.a', 10, '$.c', 3) AS `mixed_ops`;
SELECT json_set('{"a": 1, "b": 2}', 170141183460469231731687303715884105727, 10, '$.c', 3) AS `mixed_ops`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', 10, '$.c', -1) AS `mixed_ops`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', 10, '$.a', 3) AS `mixed_ops`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', 10, '$.c', CAST(3 AS JSON)->'$.a') AS `mixed_ops`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', 10, '{"a": 1, "b": 2}', 3) AS `mixed_ops`;
SELECT json_set('{"a": 1, "b": 2}', '$.a', TRUE, '$.c', 3) AS `mixed_ops`;
SELECT json_set('{"a": 1, "b": 2}', 10, 10, '$.c', 3) AS `mixed_ops`;
SELECT json_set('{"a": {"x": 1, "y": 2}}', '\\', 100) AS `update_nested`;
SELECT json_set('{"a": {"x": 1, "y": 2}}', '$.a.x', json_set('[1, 2, 3]', '$[0]', 9)) AS `update_nested`;
SELECT json_set('{"a": {"x": 1, "y": 2}}', '', 100) AS `update_nested`;
SELECT json_set('{"a": {"x": 1, "y": 2}}', '$.a.x', '$.a.x') AS `update_nested`;
SELECT json_set('{"a": {"x": 1, "y": 2}}', 100, 100) AS `update_nested`;
SELECT json_set('1970-01-01', '$.a.x', 100) AS `update_nested`;
SELECT json_set('{"a": {"x": 1, "y": 2}}', '$.a.x', 100) AS `update_nested` LIMIT 5;
SELECT json_set('{"a": {"x": 1, "y": 2}}', '$.a.x', 100) AS `update_nested`;
SELECT json_set('{"a": {"x": 1, "y": 2}}', '$.a.x', 100) AS `update_nested` LIMIT 1;
SELECT json_set('{"a": {"x": 1, "y": 2}}', 170141183460469231731687303715884105727, 100) AS `update_nested`;
SELECT json_set(json_set('{"a": {"x": 1, "y": 2}}', '$.a.x', 100), '$.a.x', 100) AS `update_nested`;
SELECT json_set('{"a": {"x": 1, "y": 2}}', '$.a.x', '{"a": {"x": 1, "y": 2}}') AS `update_nested`;
SELECT json_set('{"a": {"x": 1, "y": 2}}', 100, 100) AS `update_nested`;
SELECT json_set('{"a": {"x": 1, "y": 2}}', 100, 100) AS `update_nested`;
SELECT json_set('%', '$.a.x', 100) AS `update_nested`;
SELECT json_set('{"a": {"x": 1, "y": 2}}', '{"a": {"x": 1, "y": 2}}', 100) AS `update_nested`;
SELECT json_set('{"a": {"x": 1, "y": 2}}', '$.a.x', '$.a.x') AS `update_nested`;
SELECT json_set('{"a": {"x": 1, "y": 2}}', '$.a.x', -2147483648) AS `update_nested`;
SELECT json_set('{"a": {"x": 1, "y": 2}}', '$.a.x', json_set('{"a": {"x": 1, "y": 2}}', '$.a.x', 100)) AS `update_nested`;
SELECT json_set('{"a": {"x": 1}}', '$.a.x', 100) AS `update_nested`;
SELECT json_set('{"a": {"x": 1, "y": 2}}', '{"a": {"x": 1, "y": 2}}', 100) AS `update_nested`;
SELECT json_set('{"a": {"x": 1, "y": 2}}', '$.a.x', 100) AS `update_nested` LIMIT 0;
SELECT json_set('{"a": {"x": 1, "y": 2}}', TRUE, 100) AS `update_nested`;
SELECT json_set('{"a": {"x": 1, "y": 2}}', '$.a.x', json_set('{"a": {"x": 1, "y": 2}}', '$.a.x', 100)) AS `update_nested`;
SELECT get_json_string(CAST((json_set('{"a": {"x": 1}}', '$.a.y', 200)) AS JSON), '$.a') AS `insert_nested`;
SELECT json_set(json_set('{"a": {"x": 1}}', '$.a.y', 200), '$.a.y', 200) AS `insert_nested`;
SELECT json_set('{"a": {"x": 1}}', CAST('$.a.y' AS JSON)->'$.a', 200) AS `insert_nested`;
SELECT json_set(CAST('{"a": {"x": 1}}' AS JSON)->'k', '$.a.y', 200) AS `insert_nested`;
SELECT json_set('{"a": {"x": 1}}', '$.a.y', '{"a": {"x": 1}}') AS `insert_nested`;
SELECT json_set(repeat('x', 65536), '$.a.y', 200) AS `insert_nested`;
SELECT json_set('{"a": {"x": 1}}', '$.a.y', '$.a.y') AS `insert_nested`;
SELECT json_set(200, '$.a.y', 200) AS `insert_nested`;
SELECT json_set('{"a": {"x": 1}}', '$.a.y', '$.a.y') AS `insert_nested`;
SELECT json_set(CAST(NULL AS JSON), '$.a.y', 200) AS `insert_nested`;
SELECT json_set('{"a": {"x": 1}}', 0.0, 200) AS `insert_nested`;
SELECT json_set('{"a": {"x": 1}}', '$.a.y', '9999-12-31 23:59:59') AS `insert_nested`;
SELECT json_set('{"a": {"x": 1}}', '{"a": {"x": 1}}', 200) AS `insert_nested`;
SELECT json_set('{"a": {"x": 1}}', '$.a.y', 200) AS `insert_nested` WHERE (json_set('{"a": 1}', NULL, 1)) IS NULL;
SELECT json_set('{"a": {"x": 1}}', '$.a.y', -1.0E308) AS `insert_nested`;
SELECT json_set(json_set('{"a": {"x": 1}}', '$.a.y', 200), '$.a.y', 200) AS `insert_nested`;
SELECT json_set('$.a.y', '$.a.y', 200) AS `insert_nested`;
SELECT json_set('{"a": {"x": 1}}', '{"a": {"x": 1, "y": 2}}', 200) AS `insert_nested`;
SELECT json_set(json_query(CAST('{"a": {"x": 1}}' AS JSON), '$.a'), '$.a.y', 200) AS `insert_nested`;
SELECT json_set('{"a": {"x": 1}}', 200, 200) AS `insert_nested`;
SELECT json_set('{"a": {"x": 1}}', '{"a": {"x": 1}}', 200) AS `insert_nested`;
SELECT json_set('{"a": {"x": 1}}', '{"a": {"x": 1}}', 200) AS `insert_nested`;
SELECT json_set('{"a": {"x": 1}}', '$.a.y', NULL) AS `insert_nested`;
SELECT json_set('{"level1": {"level2": {"target": "old"}}}', json_set('{"a": 1}', NULL, 1), 'new') AS `deep_update`;
SELECT json_set('{"level1": {"level2": {"target": "old"}}}', '$.level1.level2.target', -1) AS `deep_update`;
SELECT json_set(repeat('x', 65536), '$.level1.level2.target', 'new') AS `deep_update`;
SELECT json_set('{"level1": {"level2": {"target": "old"}}}', 'new', 'new') AS `deep_update`;
SELECT json_set(CAST('{"level1": {"level2": {"target": "old"}}}' AS JSON)->'$.a', '$.level1.level2.target', 'new') AS `deep_update`;
SELECT json_set('{"level1": {"level2": {"target": "old"}}}', '$.level1.level2.target', '1970-01-01') AS `deep_update`;
SELECT json_set('\\', '$.level1.level2.target', 'new') AS `deep_update`;
SELECT json_set('{"level1": {"level2": {"target": "old"}}}', '$.level1.level2.target', '9999-12-31 23:59:59') AS `deep_update`;
SELECT json_set(2147483647, '$.level1.level2.target', 'new') AS `deep_update`;
SELECT json_set(FALSE, '$.level1.level2.target', 'new') AS `deep_update`;
SELECT json_set('{"level1": {"level2": {"target": "old"}}}', '$.level1.level2.target', json_set('{"level1": {"level2": {"target": "old"}}}', '$.level1.level2.target', 'new')) AS `deep_update`;
SELECT json_set('{"level1": {"level2": {"target": "old"}}}', '$.level1.level2.target', TRUE) AS `deep_update`;
SELECT json_set('{"level1": {"level2": {"target": "old"}}}', '$.level1.level2.target', '{"level1": {"level2": {"target": "old"}}}') AS `deep_update`;
SELECT json_set('{"level1": {"level2": {"target": "old"}}}', '9999-12-31 23:59:59', 'new') AS `deep_update`;
SELECT json_set(-1.0E308, '$.level1.level2.target', 'new') AS `deep_update`;
SELECT json_set('{"level1": {"level2": {"target": "old"}}}', '{"level1": {"level2": {"target": "old"}}}', 'new') AS `deep_update`;
SELECT json_set('{"level1": {"level2": {"target": "old"}}}', '$.level1.level2.target', 'new') AS `deep_update`;
SELECT json_set('{"level1": {"level2": {"target": "old"}}}', '$.level1.level2.target', '0000-00-00') AS `deep_update`;
SELECT json_set('{"level1": {"level2": {"target": "old"}}}', 'new', 'new') AS `deep_update`;
SELECT json_set('{"level1": {"level2": {"target": "old"}}}', '$.level1.level2.target', 170141183460469231731687303715884105727) AS `deep_update`;
SELECT json_set('{"level1": {"level2": {"target": "old"}}}', CAST(NULL AS JSON), 'new') AS `deep_update`;
SELECT json_set(CAST('{"level1": {"level2": {"target": "old"}}}' AS JSON)->'$', '$.level1.level2.target', 'new') AS `deep_update`;
SELECT json_set('{"level1": {"level2": {"target": "old"}}}', NULL, 'new') AS `deep_update`;
SELECT json_set('new', '$.level1.level2.target', 'new') AS `deep_update`;
SELECT json_set('{"level1": {"level2": {"target": "old"}}}', json_set('{"level1": {"level2": {"target": "old"}}}', '$.level1.level2.target', 'new'), 'new') AS `deep_update`;
SELECT json_set('{"level1": {"level2": {"target": "old"}}}', '$.level1.level2.target', 'new') AS `deep_update` LIMIT 7, 2;
SELECT json_set('{"arr": [10, 20, 30]}', '$.arr[1]', '$.arr[1]') AS `update_array_index`;
SELECT json_set('$.arr[1]', '$.arr[1]', 99) AS `update_array_index`;
SELECT json_set('{"arr": [10, 20, 30]}', '$.arr[1]', json_set('{"arr": [10, 20, 30]}', '$.arr[1]', 99)) AS `update_array_index`;
SELECT json_set(json_length(CAST('{"arr": [10, 20, 30]}' AS JSON)), '$.arr[1]', 99) AS `update_array_index`;
SELECT CAST((json_set('{"arr": [10, 20, 30]}', '$.arr[1]', 99)) AS DECIMAL128(27,9)) AS `update_array_index`;
SELECT json_set('{"arr": [10, 20, 30]}', NULL, 99) AS `update_array_index`;
SELECT json_set(0.0, '$.arr[1]', 99) AS `update_array_index`;
SELECT json_set('{"arr": [10, 20, 30]}', '$.arr[1]', '$.arr[1]') AS `update_array_index`;
SELECT json_set('{"arr": [10, 20, 30]}', '$.arr[1]', -9223372036854775808) AS `update_array_index`;
SELECT json_set('{"arr": [10, 20, 30]}', '$.arr[1]', 9223372036854775807) AS `update_array_index`;
SELECT json_set(-2147483648, '$.arr[1]', 99) AS `update_array_index`;
SELECT json_set('{"arr": [10, 20, 30]}', '$.arr[1]', repeat('x', 65536)) AS `update_array_index`;
SELECT json_set('{"arr": [10, 20, 30]}', '$.arr[1]', '0000-00-00') AS `update_array_index`;
SELECT json_set('{"arr": [10, 20, 30]}', '$.arr[1]', 99) AS `update_array_index`;
SELECT json_set('{"arr": [10, 20, 30]}', '$.arr[1]', FALSE) AS `update_array_index`;
SELECT json_set('%', '$.arr[1]', 99) AS `update_array_index`;
SELECT json_set('{"arr": [10, 20, 30]}', '$.arr[1]', 99) AS `update_array_index`;
SELECT CAST((CAST((json_set('{"arr": [10, 20, 30]}', '$.arr[1]', 99)) AS DOUBLE)) AS TIME) AS `update_array_index`;
SELECT json_set('{"arr": [10, 20, 30]}', 1, 99) AS `update_array_index`;
SELECT json_set('{"arr": [10, 20, 30]}', '$.arr[1]', '{"arr": [10, 20, 30]}') AS `update_array_index`;
SELECT json_set(1, '$.arr[1]', 99) AS `update_array_index`;
SELECT json_set('{"arr": [10, 20, 30]}', -1, 99) AS `update_array_index`;
SELECT json_set(json_set('{"arr": [10, 20, 30]}', '$.arr[1]', 99), '$.arr[1]', 99) AS `update_array_index`;
SELECT json_set('{"arr": [10, 20, 30]}', CAST((CAST('$.arr[1]' AS DECIMAL128(38,37))) AS LARGEINT), 99) AS `update_array_index`;
SELECT json_set('{"arr": [10, 20, 30]}', '$.arr[1]', 99) AS `update_array_index` WHERE TRUE;
SELECT json_set('{"arr": [10, 20, 30]}', '$.arr[1]', json_set('{"arr": [10, 20, 30]}', '$.arr[1]', 99)) AS `update_array_index`;
SELECT json_set('{"arr": [10, 20, 30]}', '$.arr[1]', 99) AS `update_array_index`;
SELECT json_set('{"arr": [10, 20, 30]}', '$.arr[1]', 99) AS `update_array_index`;
SELECT json_set('{"arr": [10, 20]}', '$.arr[100]', '%') AS `append_array`;
SELECT json_set('{"arr": [10, 20]}', json_set('{"arr": [10, 20]}', '$.arr[100]', 30), 30) AS `append_array`;
SELECT json_set('{"arr": [10, 20]}', '$.c', 30) AS `append_array`;
SELECT json_set('{"arr": [10, 20]}', '$.arr[100]', 30) AS `append_array`;
SELECT json_set('{"arr": [10, 20]}', '$.arr[100]', 30) AS `append_array`;
SELECT json_set('{"arr": [10, 20]}', '$.arr[100]', '$') AS `append_array`;
SELECT json_set('', '$.arr[100]', 30) AS `append_array`;
SELECT json_set('{"arr": [10, 20]}', '$.arr[100]', -2147483648) AS `append_array`;
SELECT json_set('{"arr": [10, 20]}', 1, 30) AS `append_array`;
SELECT json_set('{"arr": [10, 20]}', '$.arr[100]', '1970-01-01') AS `append_array`;
SELECT json_set('{"arr": [10, 20]}', '$.arr[100]', '{"arr": [10, 20]}') AS `append_array`;
SELECT json_set('0000-00-00', '$.arr[100]', 30) AS `append_array`;
SELECT json_set('{"arr": [10, 20]}', '{"arr": [10, 20]}', 30) AS `append_array`;
SELECT json_set('[1, 2, 3]', '$.arr[100]', 30) AS `append_array`;
SELECT json_set('{"arr": [10, 20]}', '$.arr[100]', json_set('{"arr": [10, 20]}', '$.arr[100]', 30)) AS `append_array`;
SELECT json_set(FALSE, '$.arr[100]', 30) AS `append_array`;
SELECT json_set(0, '$.arr[100]', 30) AS `append_array`;
SELECT json_set('{"arr": [10, 20]}', '%', 30) AS `append_array`;
SELECT json_set('{"arr": [10, 20]}', -1.0E308, 30) AS `append_array`;
SELECT json_length(CAST((json_set('{"arr": [10, 20]}', '$.arr[100]', 30)) AS JSON)) AS `append_array`;
SELECT json_set('{"arr": [10, 20]}', 1, 30) AS `append_array`;
SELECT json_set('{"arr": [10, 20]}', '$.arr[100]', '0000-00-00') AS `append_array`;
SELECT json_set('{"arr": [10, 20]}', '$.arr[100]', 30) AS `append_array` WHERE TRUE;
SELECT json_set('{"arr": [10, 20]}', 1, 30) AS `append_array`;
SELECT json_set(30, '$.arr[100]', 30) AS `append_array`;
SELECT json_set('[1, 2, 3]', '$[0]', '9999-12-31 23:59:59') AS `root_array_update`;
SELECT json_set('[1, 2, 3]', '$[0]', json_set('[1, 2, 3]', '$[0]', 9)) AS `root_array_update`;
SELECT json_set('$[0]', '$[0]', 9) AS `root_array_update`;
SELECT json_set(-1, '$[0]', 9) AS `root_array_update`;
SELECT json_set('[1, 2, 3]', '$.c', 9) AS `root_array_update`;
SELECT json_set(170141183460469231731687303715884105727, '$[0]', 9) AS `root_array_update`;
SELECT json_set('[1, 2, 3]', '$[0]', 2147483647) AS `root_array_update`;
SELECT json_set('[1, 2, 3]', '$[0]', '[1, 2, 3]') AS `root_array_update`;
SELECT json_set('[1, 2, 3]', '$[0]', 9) AS `root_array_update`;
SELECT json_set('[1, 2, 3]', '$[0]', '$[0]') AS `root_array_update`;
SELECT json_set('[1, 2, 3]', json_set('[1, 2, 3]', '$[0]', 9), 9) AS `root_array_update`;
SELECT json_set('[1, 2, 3]', json_set('[1, 2, 3]', '$[0]', 9), 9) AS `root_array_update`;
SELECT json_set('[1, 2, 3]', '$[0]', -1.0E308) AS `root_array_update`;
SELECT json_set('[1, 2, 3]', '$[0]', json_set('[1, 2, 3]', '$[0]', 9)) AS `root_array_update`;
SELECT json_set(2147483647, '$[0]', 9) AS `root_array_update`;
SELECT json_set('[1, 2, 3]', '$[0]', repeat('x', 65536)) AS `root_array_update`;
SELECT CAST((json_set('[1, 2, 3]', '$[0]', 9)) AS struct<`a` int(11), `b` varchar(8)>) AS `root_array_update`;
SELECT json_set('$[0]', '$[0]', 9) AS `root_array_update`;
SELECT json_set('[1, 2, 3]', '$[0]', NULL) AS `root_array_update`;
SELECT json_set('[1, 2, 3]', '$[0]', 9) AS `root_array_update` WHERE (json_set('{"a": 1}', NULL, 1)) IS NULL;
SELECT json_set('\\', '$[0]', 9) AS `root_array_update`;
SELECT json_set('', '$[0]', 9) AS `root_array_update`;
SELECT json_set(0, '$.a.b', 2) AS `set_on_scalar`;
SELECT json_set('{"a": 1}', '$.a.b', 2) AS `set_on_scalar` LIMIT 7, 2;
SELECT json_set('{"a": 1}', '$.a.b', '{"a": 1}') AS `set_on_scalar`;
SELECT json_set('{"a": 1}', '$.a.b', 2) AS `set_on_scalar` LIMIT 100;
SELECT json_set('{"a": 1}', CAST('$.a.b' AS CHAR(1)), 2) AS `set_on_scalar`;
SELECT json_set('$.a.b', '$.a.b', 2) AS `set_on_scalar`;
SELECT json_set('%', '$.a.b', 2) AS `set_on_scalar`;
SELECT json_set(-2147483648, '$.a.b', 2) AS `set_on_scalar`;
SELECT json_set(2, '$.a.b', 2) AS `set_on_scalar`;
SELECT json_set('{"a": 1}', '$.a.b', 2) AS `set_on_scalar`;
SELECT json_set('{"a": 1}', '$.a.b', TRUE) AS `set_on_scalar`;
SELECT json_set('{"a": 1}', '$.a.b', '{"a": 1}') AS `set_on_scalar`;
SELECT json_set('{"a": 1}', '$.a.b', CAST((CAST((CAST(2 AS TINYINT)) AS BOOLEAN)) AS LARGEINT)) AS `set_on_scalar`;
SELECT json_set('{"a": 1}', '$.a.b', json_set('{"a": 1}', '$.a.b', 2)) AS `set_on_scalar`;
SELECT json_set('{"a": 1}', '$.a.b', 2) AS `set_on_scalar` LIMIT 100;
SELECT json_set(0, '$.a.b', 2) AS `set_on_scalar`;
SELECT json_set('{"a": 1}', json_set('{"a": 1}', '$.a.b', 2), 2) AS `set_on_scalar`;
SELECT json_set('{"a": 1}', '$.a.b', repeat('x', 65536)) AS `set_on_scalar`;
SELECT json_set('{"a": 1}', '$.a.b', '{"a": 1}') AS `set_on_scalar`;
SELECT json_set('{"a": 1}', TRUE, 2) AS `set_on_scalar`;
SELECT json_set('{"a": 1}', '$.a.b', json_set('{"arr": [10, 20]}', '$.arr[100]', 30)) AS `set_on_scalar`;
SELECT json_set('{"a": 1}', json_set('{"a": 1}', '$.a.b', 2), 2) AS `set_on_scalar`;
SELECT json_set('{"a": 1}', '$.missing_parent.child', json_set('{"a": 1}', '$.missing_parent.child', 2)) AS `missing_parent`;
SELECT json_set('{"a": 1}', '$.missing_parent.child', json_set('{"a": 1}', '$.missing_parent.child', 2)) AS `missing_parent`;
SELECT json_set('{"a": 1}', '$.missing_parent.child', -1) AS `missing_parent`;
SELECT json_set('{"a": 1}', '$.missing_parent.child', 2) AS `missing_parent` WHERE (json_set('{"a": 1}', '$.a', 1, NULL, 2)) IS NULL;
SELECT json_set('{"a": 1}', '$.missing_parent.child', 2) AS `missing_parent`;
SELECT json_set('{"a": 1}', '$.missing_parent.child', json_set('{"a": 1}', '$.missing_parent.child', 2)) AS `missing_parent`;
SELECT json_set('{"a": 1}', '$.missing_parent.child', json_set('{"a": 1}', '$.missing_parent.child', 2)) AS `missing_parent`;
SELECT json_set('{"a": 1}', 2147483647, 2) AS `missing_parent`;
SELECT json_set('{"a": 1}', '$.missing_parent.child', 2) AS `missing_parent`;
SELECT json_set('{"a": 1}', '$.missing_parent.child', 2) AS `missing_parent` LIMIT 1, 0;
SELECT json_set('{"a": 1}', '$.missing_parent.child', '0') AS `missing_parent`;
SELECT json_set('{"a": 1}', 2147483647, 2) AS `missing_parent`;
SELECT json_set('{"a": 1}', '$.missing_parent.child', json_set('{"a": 1}', '$.missing_parent.child', 2)) AS `missing_parent`;
SELECT json_set(0.0, '$.missing_parent.child', 2) AS `missing_parent`;
SELECT json_set('{"a": 1}', '$.missing_parent.child', 2) AS `missing_parent` LIMIT 7, 5;
SELECT json_set('{"a": 1}', 2, 2) AS `missing_parent`;
SELECT json_set('{"a": 1}', '$.missing_parent.child', 2) AS `missing_parent` LIMIT 1, 2;
SELECT json_set('{"a": 1}', '$.missing_parent.child', -2147483648) AS `missing_parent`;
SELECT json_set(2, '$.missing_parent.child', 2) AS `missing_parent`;
SELECT json_set('{"a": 1}', '$.missing_parent.child', FALSE) AS `missing_parent`;
SELECT json_set('{"a": 1}', '$.missing_parent.child', 2) AS `missing_parent`;
SELECT json_set('{"a": 1}', json_set('{"a": 1}', '$.missing_parent.child', 2), 2) AS `missing_parent`;
SELECT json_set('{"a": 1}', '$.missing_parent.child', 10) AS `missing_parent`;
SELECT json_set('{"a": 1}', '$.missing_parent.child', '{"a": 1}') AS `missing_parent`;
SELECT json_set(2, '$.missing_parent.child', 2) AS `missing_parent`;
SELECT json_set('{"a": 1}', '$.missing_parent.child', '$.missing_parent.child') AS `missing_parent`;
SELECT json_set('{"a": 1}', '$.missing_parent.child', 2) AS `missing_parent`;
SELECT json_set('{"a": 1}', '$', '{"new": "doc"}') AS `replace_root` LIMIT 7, 100;
SELECT json_set('{"a": 1}', '$', json_set('{"a": 1}', '$.a', 1, NULL, 2)) AS `replace_root`;
SELECT json_set('{"a": 1}', '$', '{"new": "doc"}') AS `replace_root`;
SELECT json_set('{"a": 1}', '$', '{"new": "doc"}') AS `replace_root` LIMIT 7, 5;
SELECT json_set('{"a": 1}', json_set('{"a": 1}', '$', '{"new": "doc"}'), '{"new": "doc"}') AS `replace_root`;
SELECT json_set('{"a": 1}', '$', '{"new": "doc"}') AS `replace_root` WHERE (json_set('{"a": 1}', NULL, 1)) IS NULL;
SELECT json_set('{"a": 1}', '$', '{"new": "doc"}') AS `replace_root` LIMIT 5;
SELECT json_set('{"a": 1}', '$', '{"new": "doc"}') AS `replace_root`;
SELECT json_set('{"a": 1}', '$', '{"new": "doc"}') AS `replace_root` LIMIT 100;
SELECT json_set('{"a": 1}', '$', '{"new": "doc"}') AS `replace_root` LIMIT 1, 2;
SELECT json_set('{"a": 1}', '$', '{"new": "doc"}') AS `replace_root`;
SELECT json_set('{"a": 1}', '$', 0.0) AS `replace_root`;
SELECT json_set('{"a": 1}', NULL, '{"new": "doc"}') AS `replace_root`;
SELECT json_set(9223372036854775807, '$', '{"new": "doc"}') AS `replace_root`;
SELECT json_set('{"new": "doc"}', '$', '{"new": "doc"}') AS `replace_root`;
SELECT json_set('\\', '$', '{"new": "doc"}') AS `replace_root`;
SELECT json_set(CAST('{"a": 1}' AS JSON)->'k', '$', '{"new": "doc"}') AS `replace_root`;
SELECT json_set('{"a": 1}', '$', '{"new": "doc"}') AS `replace_root` LIMIT 2;
SELECT json_set(-1, '$', '{"new": "doc"}') AS `replace_root`;
SELECT json_set('{"a": 1}', json_set('{"a": 1}', '$', '{"new": "doc"}'), '{"new": "doc"}') AS `replace_root`;
SELECT json_set('{"a": 1}', '$', '$') AS `replace_root`;
SELECT json_set(NULL, '$', '{"new": "doc"}') AS `replace_root`;
SELECT json_set('{"a": 1}', -1, '{"new": "doc"}') AS `replace_root`;
SELECT json_set(1, '$', '{"new": "doc"}') AS `replace_root`;
SELECT json_set('{"a": 1}', '$', '{"new": "doc"}') AS `replace_root`;
SELECT json_set('{"a": 1}', json_set('{"a": 1}', '$', '{"new": "doc"}'), '{"new": "doc"}') AS `replace_root`;
SELECT if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, 'NULL_OK', 'FAIL') AS `set_sql_null` LIMIT 7, 100;
SELECT if((json_set(NULL, '$.k', NULL)) IS NULL, 'NULL_OK', 'FAIL') AS `set_sql_null`;
SELECT if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, 0.0, 'FAIL') AS `set_sql_null`;
SELECT if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, json_length(CAST('NULL_OK' AS JSON)), 'FAIL') AS `set_sql_null`;
SELECT if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, 1, 'FAIL') AS `set_sql_null`;
SELECT if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, 'NULL_OK', 'FAIL') AS `set_sql_null`;
SELECT if((json_set('{"k": "old"}', '$.k', 'NULL_OK')) IS NULL, 'NULL_OK', 'FAIL') AS `set_sql_null`;
SELECT if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, 'NULL_OK', 'FAIL') AS `set_sql_null` ORDER BY if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, 'NULL_OK', 'FAIL') ASC;
SELECT if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, '$.k', 'FAIL') AS `set_sql_null`;
SELECT if((json_set(0, '$.k', NULL)) IS NULL, 'NULL_OK', 'FAIL') AS `set_sql_null`;
SELECT if((json_set('{"k": "old"}', 'NULL_OK', NULL)) IS NULL, 'NULL_OK', 'FAIL') AS `set_sql_null`;
SELECT if((json_length(CAST((json_set('{"k": "old"}', '$.k', NULL)) AS JSON))) IS NULL, 'NULL_OK', 'FAIL') AS `set_sql_null`;
SELECT if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, 'NULL_OK', 'FAIL') AS `set_sql_null` ORDER BY if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, 'NULL_OK', 'FAIL') DESC;
SELECT if((json_set('{"k": "old"}', '$.k', json_set('{"a": 1}', '$.b', 2))) IS NULL, 'NULL_OK', 'FAIL') AS `set_sql_null`;
SELECT if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, 'NULL_OK', 'FAIL') AS `set_sql_null` ORDER BY if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, 'NULL_OK', 'FAIL') DESC;
SELECT if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, 'NULL_OK', 'FAIL') AS `set_sql_null` LIMIT 5;
SELECT if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, 'NULL_OK', 'FAIL') AS `set_sql_null`;
SELECT if(json_query(CAST(((json_set('{"k": "old"}', '$.k', NULL)) IS NULL) AS JSON), '$.a'), 'NULL_OK', 'FAIL') AS `set_sql_null`;
SELECT if((json_set(1, '$.k', NULL)) IS NULL, 'NULL_OK', 'FAIL') AS `set_sql_null`;
SELECT if('$.k' IS NULL, 'NULL_OK', 'FAIL') AS `set_sql_null`;
SELECT if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, 'NULL_OK', 'FAIL') AS `set_sql_null` WHERE (json_set('{"a": 1}', NULL, 1)) IS NULL;
SELECT if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, 'NULL_OK', 'FAIL') AS `set_sql_null`;
SELECT if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, 'NULL_OK', 'FAIL') AS `set_sql_null` ORDER BY if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, 'NULL_OK', 'FAIL') DESC;
SELECT if((json_set('{"k": "old"}', '$.k', 3)) IS NULL, 'NULL_OK', 'FAIL') AS `set_sql_null`;
SELECT if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, '\\', 'FAIL') AS `set_sql_null`;
SELECT DISTINCT if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, 'NULL_OK', 'FAIL') AS `set_sql_null`;
SELECT if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, -2147483648, 'FAIL') AS `set_sql_null`;
SELECT if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, 'NULL_OK', 2147483647) AS `set_sql_null`;
SELECT if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, 'NULL_OK', 'FAIL') AS `set_sql_null`;
SELECT if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, 'NULL_OK', 'FAIL') AS `set_sql_null` LIMIT 1;
SELECT json_set('{"k": "old"}', 'null', parse_json('null')) AS `set_json_null`;
SELECT json_set('{"k": "old"}', '', parse_json('null')) AS `set_json_null`;
SELECT json_set('{"k": "old"}', '$.k', parse_json(CAST('null' AS JSON)->'$')) AS `set_json_null`;
SELECT json_set('{"k": "old"}', '$.k', month('null')) AS `set_json_null`;
SELECT json_set('0000-00-00', '$.k', parse_json('null')) AS `set_json_null`;
SELECT json_set('{"k": "old"}', '$.k', parse_json('null')) AS `set_json_null` WHERE (json_set('{"a": 1}', '$.a', 1, NULL, 2)) IS NULL;
SELECT json_set(CAST('{"k": "old"}' AS JSON)->'$', '$.k', parse_json('null')) AS `set_json_null`;
SELECT json_set('{"k": "old"}', '$.k', parse_json('null')) AS `set_json_null`;
SELECT json_set('{"k": "old"}', -1.0E308, parse_json('null')) AS `set_json_null`;
SELECT json_set('{"k": "old"}', '$.k', parse_json(-2147483648)) AS `set_json_null`;
SELECT json_set('$.k', '$.k', parse_json('null')) AS `set_json_null`;
SELECT json_set(9223372036854775807, '$.k', parse_json('null')) AS `set_json_null`;
SELECT json_set('$.k', '$.k', parse_json('null')) AS `set_json_null`;
SELECT json_set('{"k": "old"}', '$.k', parse_json('null')) AS `set_json_null` WHERE (json_set(NULL, '$.a', 1)) IS NULL;
SELECT json_set(-1.0E308, '$.k', parse_json('null')) AS `set_json_null`;
SELECT json_set(json_query(CAST('{"k": "old"}' AS JSON), '$.a'), '$.k', parse_json('null')) AS `set_json_null`;
SELECT json_set('{"k": "old"}', '$.k', parse_json('null')) AS `set_json_null` WHERE (json_set('{"a": 1}', '$.a', 1, NULL, 2)) IS NULL;
SELECT json_set('{"k": "old"}', '$.k', parse_json('null')) AS `set_json_null`;
SELECT json_set('{"k": "old"}', '$.k', parse_json('{"k": "old"}')) AS `set_json_null`;
SELECT json_set('{"k": "old"}', '$.k', parse_json(TRUE)) AS `set_json_null`;
SELECT json_set('{"k": "old"}', '$.k', char_length('null')) AS `set_json_null`;
SELECT json_set('{"k": "old"}', '$.k', year('null')) AS `set_json_null`;
SELECT json_set(0, '$.k', parse_json('null')) AS `set_json_null`;
SELECT json_set('{"k": "old"}', '$.k', '$.k') AS `set_bool`;
SELECT json_set('{"k": "old"}', CAST(NULL AS JSON), TRUE) AS `set_bool`;
SELECT json_set('{"k": "old"}', '$.k', TRUE) AS `set_bool` WHERE TRUE;
SELECT count(json_set('{"k": "old"}', '$.k', TRUE)) OVER () AS `set_bool`;
SELECT json_set('{"k": "old"}', '$.k', '0') AS `set_bool`;
SELECT json_set('{"k": "old"}', '$.k', TRUE) AS `set_bool` LIMIT 2;
SELECT json_set('%', '$.k', TRUE) AS `set_bool`;
SELECT json_set('{"k": "old"}', '$.k', '\\') AS `set_bool`;
SELECT json_set('$.k', '$.k', TRUE) AS `set_bool`;
SELECT json_set('$.k', '$.k', TRUE) AS `set_bool`;
SELECT json_set('1970-01-01', '$.k', TRUE) AS `set_bool`;
SELECT json_set('{"k": "old"}', json_length(CAST('$.k' AS JSON)), TRUE) AS `set_bool`;
SELECT json_set(json_set('{"k": "old"}', '$.k', TRUE), '$.k', TRUE) AS `set_bool`;
SELECT json_set('{"k": "old"}', json_set('{"a": 1}', '$."key.with.dot"', 2), TRUE) AS `set_bool`;
SELECT json_set('{"k": "old"}', -1, TRUE) AS `set_bool`;
SELECT json_set('{"k": "old"}', '$.k', TRUE) AS `set_bool` LIMIT 2;
SELECT json_set('{"k": "old"}', '$.k', FALSE) AS `set_bool`;
SELECT json_set('{"k": "old"}', CAST('$.k' AS JSON)->'k', TRUE) AS `set_bool`;
SELECT json_set('{"k": "old"}', '', TRUE) AS `set_bool`;
SELECT json_set(NULL, '$.k', TRUE) AS `set_bool`;
SELECT json_set(0.0, '$.k', TRUE) AS `set_bool`;
SELECT json_set(json_set('{"k": "old"}', '$.k', TRUE), '$.k', TRUE) AS `set_bool`;
SELECT json_set('{"k": "old"}', 100, TRUE) AS `set_bool`;
SELECT json_set('9999-12-31 23:59:59', '$.k', TRUE) AS `set_bool`;
SELECT json_set('{"k": "old"}', CAST((CAST('$.k' AS DECIMAL128(38,37))) AS SMALLINT), parse_json('{"sub": "json"}')) AS `set_json_object`;
SELECT json_set('{"k": "old"}', '$.k', parse_json(parse_json('{"sub": "json"}'))) AS `set_json_object`;
SELECT json_set(json_set('{"k": "old"}', '$.k', parse_json('{"sub": "json"}')), '$.k', parse_json('{"sub": "json"}')) AS `set_json_object`;
SELECT json_set('{"k": "old"}', '$.k', abs('{"sub": "json"}')) AS `set_json_object`;
SELECT json_set('{"k": "old"}', '$.k', parse_json(CAST('{"sub": "json"}' AS JSON)->'$.a')) AS `set_json_object`;
SELECT json_set('{"k": "old"}', '$.k', parse_json(-1.0E308)) AS `set_json_object`;
SELECT json_set('{"k": "old"}', '{"k": "old"}', parse_json('{"sub": "json"}')) AS `set_json_object`;
SELECT json_set('{"k": "old"}', '{"k": "old"}', parse_json('{"sub": "json"}')) AS `set_json_object`;
SELECT json_set('{"k": "old"}', '$.k', bitmap_count('{"sub": "json"}')) AS `set_json_object`;
SELECT json_set(json_length(CAST('{"k": "old"}' AS JSON)), '$.k', parse_json('{"sub": "json"}')) AS `set_json_object`;
SELECT json_set('{"k": "old"}', parse_json('{"sub": "json"}'), parse_json('{"sub": "json"}')) AS `set_json_object`;
SELECT json_set('{"k": "old"}', '$.k', parse_json('{"sub": "json"}')) AS `set_json_object` WHERE TRUE;
SELECT json_set('{"k": "old"}', '$.k', parse_json(json_set('{"k": "old"}', '$.k', parse_json('{"sub": "json"}')))) AS `set_json_object`;
SELECT json_set('{"k": "old"}', '$.k', '$.k') AS `set_json_object`;
SELECT json_set('{"k": "old"}', '$.k', parse_json('{"sub": "json"}')) AS `set_json_object`;
SELECT json_set('%', '$.k', parse_json('{"sub": "json"}')) AS `set_json_object`;
SELECT json_set('{"k": "old"}', repeat('x', 65536), parse_json('{"sub": "json"}')) AS `set_json_object`;
SELECT json_set('{"k": "old"}', '$.k', month('{"sub": "json"}')) AS `set_json_object`;
SELECT json_set(json_set('{"k": "old"}', '$.k', parse_json('{"sub": "json"}')), '$.k', parse_json('{"sub": "json"}')) AS `set_json_object`;
SELECT json_set(json_set('{"k": "old"}', '$.k', 123.456), '$.k', 123.456) AS `set_double`;
SELECT json_set('{"k": "old"}', '$.k', '{"k": "old"}') AS `set_double`;
SELECT json_set(0, '$.k', 123.456) AS `set_double`;
SELECT json_set('{"k": "old"}', '$.k', 123.456) AS `set_double`;
SELECT json_set(170141183460469231731687303715884105727, '$.k', 123.456) AS `set_double`;
SELECT json_set('{"k": "old"}', '$.k', '\\') AS `set_double`;
SELECT json_set('{"k": "old"}', '$.k', '\\') AS `set_double`;
SELECT json_set('{"k": "old"}', '$.k', '{"k": "old"}') AS `set_double`;
SELECT json_set('{"k": "old"}', '$.k', '$.k') AS `set_double`;
SELECT json_set('{"k": "old"}', '$.k', 123.456) AS `set_double`;
SELECT json_set('{"k": "old"}', -1, 123.456) AS `set_double`;
SELECT json_set('{"k": "old"}', -2147483648, 123.456) AS `set_double`;
SELECT json_set('{"k": "old"}', '$.k', 123.456) AS `set_double`;
SELECT json_set('{"k": "old"}', '$.k', CAST(123.456 AS JSON)->'$.a') AS `set_double`;
SELECT json_set(123.456, '$.k', 123.456) AS `set_double`;
SELECT json_set('{"k": "old"}', '$.k', '{"k": "old"}') AS `set_double`;
SELECT json_set('{"k": "old"}', '$.k', 123.456) AS `set_double` LIMIT 2;
SELECT json_set('{"k": "old"}', '$.k', 1) AS `set_double`;
SELECT json_set('{"k": "old"}', json_set('{"k": "old"}', '$.k', 123.456), 123.456) AS `set_double`;
SELECT json_set(TRUE, '$.k', 123.456) AS `set_double`;
SELECT json_set('{"k": "old"}', json_set('{"k": "old"}', '$.k', 123.456), 123.456) AS `set_double`;
SELECT json_set(-9223372036854775808, '$.k', 123.456) AS `set_double`;
SELECT json_set('\\', '$.k', 123.456) AS `set_double`;
SELECT json_set('{"k": "old"}', '$.k', '0000-00-00') AS `set_double`;
SELECT json_set('1970-01-01', '$.k', 123.456) AS `set_double`;
SELECT json_set(json_set('{"k": "old"}', '$.k', 123.456), '$.k', 123.456) AS `set_double`;
SELECT json_set('{"k": "old"}', '$.k', 123.456) AS `set_double`;
SELECT json_set('{"a": 1}', -1, 10, '$.b', 20, '$.a', 30) AS `chain_override`;
SELECT json_set('{"a": 1}', '$.a', 10, '$.b', 20, json_set('{"a": 1}', '$.a', 10, '$.b', 20, '$.a', 30), 30) AS `chain_override`;
SELECT json_set('{"a": 1}', '$.a', 1.0E308, '$.b', 20, '$.a', 30) AS `chain_override`;
SELECT json_set('{"a": 1}', '$.a', 10, 20, 20, '$.a', 30) AS `chain_override`;
SELECT json_set('{"a": 1}', '$.a', 10, '$.b', 20, '$.b', 30) AS `chain_override`;
SELECT json_set('{"a": 1}', '$.a', 10, '$.b', 20, CAST('$.a' AS DECIMAL128(38,0)), 30) AS `chain_override`;
SELECT json_set('{"a": 1}', '$.a', 10, '$.b', '', '$.a', 30) AS `chain_override`;
SELECT json_set('{"a": 1}', '$.a', 10, '$.b', 20, '$.a', 30) AS `chain_override`;
SELECT json_set(0.0, '$.a', 10, '$.b', 20, '$.a', 30) AS `chain_override`;
SELECT json_set('{"a": 1}', '$.a', 10, '$.b', 20, '0', 30) AS `chain_override`;
SELECT json_set('{"a": 1}', '$.a', 10, '$.b', 20, '$.a', 2147483647) AS `chain_override`;
SELECT json_set('{"a": 1}', '$.a', 10, '$.b', 20, '$.a', NULL) AS `chain_override`;
SELECT json_set('{"a": 1}', '$.a', 10, '$.b', 20, 0.0, 30) AS `chain_override`;
SELECT json_set('{"a": 1}', '$.a', 10, '$.b', 20, '9999-12-31 23:59:59', 30) AS `chain_override`;
SELECT json_set('{"a": 1}', 0.0, 10, '$.b', 20, '$.a', 30) AS `chain_override`;
SELECT json_set('{"a": 1}', '$.a', 10, '$.b', 20, '$.a', 30) AS `chain_override` LIMIT 5;
SELECT json_set('{"a": 1}', '$.a', 10, '$.b', 20, '$.a', 30) AS `chain_override` WHERE (json_set(NULL, '$.a', 1)) IS NULL;
SELECT json_set('{"a": 1}', '$.a', 10, '$.b', 20, '$.a', 30) AS `chain_override` WHERE (json_set('{"a": 1}', NULL, 1)) IS NULL;
SELECT json_set('{"a": 1}', '$.a', 10, '$.b', 20, '$.a', '0000-00-00') AS `chain_override`;
SELECT json_set(30, '$.a', 10, '$.b', 20, '$.a', 30) AS `chain_override`;
SELECT json_set('{"a": 1}', '$.a', 10, '$.b', 20, '$.a', 30) AS `chain_override`;
SELECT json_set('{"a": 1}', '$.a', 10, FALSE, 20, '$.a', 30) AS `chain_override`;
SELECT DISTINCT if((json_set(NULL, '$.a', 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_doc`;
SELECT if((if(NULL, '$.a', 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_doc`;
SELECT if((json_set(NULL, TRUE, 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_doc`;
SELECT if((json_set(NULL, '$.a', 1)) IS NULL, if((json_set(NULL, '$.a', 1)) IS NULL, 'NULL_OK', 'FAIL'), 'FAIL') AS `null_doc`;
SELECT if((json_set(NULL, '$.a', 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_doc` LIMIT 7, 5;
SELECT if((json_set(NULL, '$.a', 1)) IS NULL, 'NULL_OK', 1) AS `null_doc`;
SELECT if((json_set(NULL, '$.a', 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_doc`;
SELECT if((json_set(NULL, '$.a', 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_doc`;
SELECT if((json_set(NULL, '$.a', 1)) IS NULL, 'NULL_OK', -1.0E308) AS `null_doc`;
SELECT if((json_set(NULL, '0000-00-00', 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_doc`;
SELECT if((json_set(NULL, '$.a', 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_doc` ORDER BY if((json_set(NULL, '$.a', 1)) IS NULL, 'NULL_OK', 'FAIL') ASC NULLS LAST;
SELECT if((json_set(NULL, '$.a', '$.a')) IS NULL, 'NULL_OK', 'FAIL') AS `null_doc`;
SELECT if((json_set(NULL, '$.a', 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_doc` LIMIT 1, 1;
SELECT if((json_set(NULL, '$.a', 1)) IS NULL, 'NULL_OK', -1) AS `null_doc`;
SELECT if((json_set(NULL, if((json_set(NULL, '$.a', 1)) IS NULL, 'NULL_OK', 'FAIL'), 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_doc`;
SELECT if(NULL IS NULL, 'NULL_OK', 'FAIL') AS `null_doc`;
SELECT if((json_set(NULL, '$.a', 0.0)) IS NULL, 'NULL_OK', 'FAIL') AS `null_doc`;
SELECT if((json_set(NULL, '$.a', 1)) IS NULL, 'NULL_OK', NULL) AS `null_doc`;
SELECT DISTINCT if((json_set(NULL, '$.a', 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_doc`;
SELECT if((json_set(NULL, '$.a', 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_doc` LIMIT 100;
SELECT if((json_set(NULL, '$.a', 1)) IS NULL, repeat('x', 65536), 'FAIL') AS `null_doc`;
SELECT if(NULL IS NULL, 'NULL_OK', 'FAIL') AS `null_doc`;
SELECT if((json_set(NULL, '$.a', 'FAIL')) IS NULL, 'NULL_OK', 'FAIL') AS `null_doc`;
SELECT if((json_set(NULL, '$.a', 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_doc` GROUP BY if((json_set(NULL, '$.a', 1)) IS NULL, 'NULL_OK', 'FAIL');
SELECT if((json_set('NULL_OK', '$.a', 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_doc`;
SELECT if((json_set(NULL, '$.a', 1)) IS NULL, 'NULL_OK', NULL) AS `null_doc`;
SELECT if((json_set(NULL, 'NULL_OK', 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_doc`;
SELECT if((json_set(NULL, '$.a', 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_doc`;
SELECT if((json_set(NULL, '%', 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_doc`;
SELECT DISTINCT if((json_set(NULL, '$.a', 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_doc`;
SELECT if('FAIL' IS NULL, 'NULL_OK', 'FAIL') AS `null_doc`;
SELECT if((json_set(NULL, '$.a', 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_doc` GROUP BY if((json_set(NULL, '$.a', 1)) IS NULL, 'NULL_OK', 'FAIL');
SELECT if((json_set('{"a": 1}', NULL, 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path`;
SELECT if((json_set('{"a": 1}', FALSE, 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path`;
SELECT count(if((json_set('{"a": 1}', NULL, 1)) IS NULL, 'NULL_OK', 'FAIL')) OVER () AS `null_path`;
SELECT if((json_set('{"a": 1}', NULL, 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path`;
SELECT if((json_set('{"a": 1}', NULL, 1)) IS NULL, 'NULL_OK', '$.a.y') AS `null_path`;
SELECT if((json_set('{"a": 1}', NULL, 1)) IS NULL, 'NULL_OK', 'NULL_OK') AS `null_path`;
SELECT if((json_set('{"a": 1}', NULL, 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path`;
SELECT if((substr('{"a": 1}', NULL, 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path`;
SELECT if((json_set('{"a": 1}', NULL, '{"a": 1}')) IS NULL, 'NULL_OK', 'FAIL') AS `null_path`;
SELECT if((json_set('{"a": 1}', NULL, 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path` ORDER BY if((json_set('{"a": 1}', NULL, 1)) IS NULL, 'NULL_OK', 'FAIL') ASC;
SELECT if((json_set('{"a": 1}', array_length(NULL), 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path`;
SELECT if((json_set('{"a": 1}', NULL, TRUE)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path`;
SELECT if((json_set('{"a": 1}', NULL, 170141183460469231731687303715884105727)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path`;
SELECT if((json_set(json_set('{"a": 1}', NULL, 1), NULL, 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path`;
SELECT if((json_set('{"a": 1}', NULL, 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path`;
SELECT if((json_set('{"a": 1}', NULL, 1)) IS NULL, CAST((CAST('NULL_OK' AS CHAR(1))) AS TINYINT), 'FAIL') AS `null_path`;
SELECT if((json_set('{"a": 1}', NULL, 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path` LIMIT 7, 1;
SELECT DISTINCT if((json_set('{"a": 1}', NULL, 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path`;
SELECT if((json_set('{"a": 1}', NULL, 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path`;
SELECT if((json_set('{"a": 1}', NULL, 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path` WHERE (json_set('{"a": 1}', '$.a', 1, NULL, 2)) IS NULL;
SELECT if((json_set('{"a": 1}', NULL, 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path`;
SELECT if((json_set('{"a": 1}', NULL, 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path`;
SELECT if(TRUE, 'NULL_OK', 'FAIL') AS `null_path`;
SELECT if((substr('{"a": 1}', NULL, 1)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path`;
SELECT if((json_set('{"a": 1}', NULL, 1)) IS NULL, repeat('x', 65536), 'FAIL') AS `null_path`;
SELECT if((json_set('{"a": 1}', '$.a', 1, NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2`;
SELECT if((json_set('{"a": 1}', if((json_set('{"a": 1}', '$.a', 1, NULL, 2)) IS NULL, 'NULL_OK', 'FAIL'), 1, NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2`;
SELECT if((json_set('{"a": 1}', '$.a', 1, NULL, 2)) IS NULL, CAST('NULL_OK' AS DOUBLE), 'FAIL') AS `null_path_arg2`;
SELECT if((json_set('{"a": 1}', '$.a', 1, NULL, 'NULL_OK')) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2`;
SELECT if((json_set('{"a": 1}', '{"arr": [10, 20]}', 1, NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2`;
SELECT if((json_set('{"a": 1}', '$.a', '', NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2`;
SELECT if((json_set('{"a": 1}', '$.a', 1, NULL, 2)) IS NULL, 'NULL_OK', json_set('{"a": 1}', '$.a', 1, NULL, 2)) AS `null_path_arg2`;
SELECT if((json_set('{"a": 1}', '$.a', 1, NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2` ORDER BY if((json_set('{"a": 1}', '$.a', 1, NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') DESC NULLS FIRST;
SELECT if((json_set('{"a": 1}', '$.a', 1, NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2` LIMIT 5;
SELECT if((json_set('{"a": 1}', '$.a', 1, -1, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2`;
SELECT DISTINCT if((json_set('{"a": 1}', '$.a', 1, NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2`;
SELECT if((json_set('{"a": 1}', '$.a', 1, NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2`;
SELECT if((json_set('{"a": 1}', '$.a', 1, NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2` WHERE TRUE;
SELECT if((json_set('{"a": 1}', '$.a', 1, NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2` LIMIT 2;
SELECT if((json_set('{"a": 1}', '$.a', 1, NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2`;
SELECT DISTINCT if((json_set('{"a": 1}', '$.a', 1, NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2`;
SELECT if((json_set('{"a": 1}', '$.a', 1, NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2` LIMIT 7, 2;
SELECT if((json_set('{"a": 1}', '$.a', '0', NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2`;
SELECT if((json_set(2, '$.a', 1, NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2`;
SELECT if((json_set('{"a": 1}', '$.a', 1, NULL, 2)) IS NULL, 'NULL_OK', NULL) AS `null_path_arg2`;
SELECT if((json_set('{"a": 1}', '$.a', json_length(CAST(1 AS JSON)), NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2`;
SELECT if((json_set('{"a": 1}', '$.a', 1, NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2` LIMIT 5;
SELECT if((json_set('{"a": 1}', '$.a', 1, NULL, -2147483648)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2`;
SELECT if((json_set('{"a": 1}', '$.a', 1, -2147483648, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2`;
SELECT if((json_set('{"a": 1}', '$.a', 1, NULL, -1.0E308)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2`;
SELECT if((json_set('{"a": 1}', '$.a', '{"a": 1}', NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2`;
SELECT if((json_set('{"a": 1}', '$.a', 1, NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2` ORDER BY if((json_set('{"a": 1}', '$.a', 1, NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') ASC;
SELECT if((json_set('{"a": 1}', '$.a', 1, 9223372036854775807, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2`;
SELECT if((json_set('{"a": 1}', 'NULL_OK', 1, NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2`;
SELECT if((json_set('{"a": 1}', '$.a', 0.0, NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2`;
SELECT if((json_set('{"a": 1}', '$.a', 1, NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2`;
SELECT if((json_set('{"a": 1}', '$.a', 1, NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2` WHERE (json_set(NULL, '$.a', 1)) IS NULL;
SELECT if((json_set('{"a": 1}', '$.a', 2147483647, NULL, 2)) IS NULL, 'NULL_OK', 'FAIL') AS `null_path_arg2`;
SELECT json_set('{"a": 1}', '$."key.with.dot"', '{"a": 1}') AS `escaped_key`;
SELECT json_set('{"a": 1}', '$."key.with.dot"', 2) AS `escaped_key`;
SELECT json_set('{"a": 1}', '$."key.with.dot"', 2) AS `escaped_key` LIMIT 0;
SELECT json_set(2, '$."key.with.dot"', 2) AS `escaped_key`;
SELECT json_query(CAST((json_set('{"a": 1}', '$."key.with.dot"', 2)) AS JSON), '$.a') AS `escaped_key`;
SELECT json_set('{"a": 1}', '$."key.with.dot"', json_set('{"a": 1}', '$."key.with.dot"', 2)) AS `escaped_key`;
SELECT json_set('{"a": 1}', '$."key.with.dot"', 2) AS `escaped_key`;
SELECT json_set('$."key.with.dot"', '$."key.with.dot"', 2) AS `escaped_key`;
SELECT json_set('{"a": 1}', '$."key.with.dot"', repeat('x', 65536)) AS `escaped_key`;
SELECT json_set('{"a": 1}', '$."key.with.dot"', 2) AS `escaped_key` WHERE (json_set('{"k": "old"}', '$.k', NULL)) IS NULL;
SELECT json_set('{"a": 1}', -1.0E308, 2) AS `escaped_key`;
SELECT json_set('{"a": 1}', repeat('x', 65536), 2) AS `escaped_key`;
SELECT json_set('{"a": 1}', '\\', 2) AS `escaped_key`;
SELECT json_set('{"a": 1}', 2, 2) AS `escaped_key`;
SELECT json_set('{"a": 1}', '$."key.with.dot"', 2) AS `escaped_key`;
SELECT json_set('{"a": 1}', CAST('$."key.with.dot"' AS DECIMAL128(38,37)), 2) AS `escaped_key`;
SELECT json_set('{"a": 1}', '$."key.with.dot"', FALSE) AS `escaped_key`;
SELECT json_set('{"a": 1}', if((json_set('{"k": "old"}', '$.k', NULL)) IS NULL, 'NULL_OK', 'FAIL'), 2) AS `escaped_key`;
SELECT json_set('{"a": 1}', '{"a": 1}', 2) AS `escaped_key`;
SELECT CAST((CAST((json_set('{"a": 1}', '$."key.with.dot"', 2)) AS DECIMAL128(38,37))) AS TIME) AS `escaped_key`;
SELECT json_set(get_json_string(CAST('{"a": 1}' AS JSON), '$.a'), '$."key.with.dot"', 2) AS `escaped_key`;
SELECT json_set(if((json_set('{"a": 1}', NULL, 1)) IS NULL, 'NULL_OK', 'FAIL'), '$."key.with.dot"', 2) AS `escaped_key`;
SELECT json_set('{"a": 1}', '$."key.with.dot"', 2) AS `escaped_key` LIMIT 100;
SELECT json_set('{"a": 1}', -1, 2) AS `escaped_key`;
SELECT json_set('%', '$.a[*]', 10) AS `json_set('%', '$.a[*]', 10)`;
SELECT json_set('{"a": [1, 2]}', json_set('{"a": [1, 2]}', '$.a[*]', 10), 10) AS `json_set('{"a": [1, 2]}', json_set('{"a": [1, 2]}', '$.a[*]', 10), 10)`;
SELECT CAST((json_set('{"a": [1, 2]}', '$.a[*]', 10)) AS JSON)->'$.a' AS `CAST((json_set('{"a": [1, 2]}', '$.a[*]', 10)) AS JSON)->'$.a'`;
SELECT json_set('{"a": [1, 2]}', '$.a[*]', '$.a[*]') AS `json_set('{"a": [1, 2]}', '$.a[*]', '$.a[*]')`;
SELECT json_set('{"a": [1, 2]}', '$.a[*]', '') AS `json_set('{"a": [1, 2]}', '$.a[*]', '')`;
SELECT json_set('{"a": [1, 2]}', '1970-01-01', 10) AS `json_set('{"a": [1, 2]}', '1970-01-01', 10)`;
SELECT json_set(10, '$.a[*]', 10) AS `json_set(10, '$.a[*]', 10)`;
SELECT json_set('{"a": [1, 2]}', '$.a[*]', 10) AS `json_set('{"a": [1, 2]}', '$.a[*]', 10)` WHERE (json_set(NULL, '$.a', 1)) IS NULL;
SELECT json_set(FALSE, '$.a[*]', 10) AS `json_set(FALSE, '$.a[*]', 10)`;
SELECT json_set(10, '$.a[*]', 10) AS `json_set(10, '$.a[*]', 10)`;
SELECT json_set('{"a": [1, 2]}', '$.a[*]', 10) AS `json_set('{"a": [1, 2]}', '$.a[*]', 10)` LIMIT 2;
SELECT json_set('$.a[*]', '$.a[*]', 10) AS `json_set('$.a[*]', '$.a[*]', 10)`;
SELECT json_set('{"a": [1, 2]}', json_set('{"a": [1, 2]}', '$.a[*]', 10), 10) AS `json_set('{"a": [1, 2]}', json_set('{"a": [1, 2]}', '$.a[*]', 10), 10)`;
SELECT json_set('{"a": [1, 2]}', '$.a[*]', 10) AS `json_set('{"a": [1, 2]}', '$.a[*]', 10)`;
SELECT json_set('{"a": [1, 2]}', '$.a[*]', 10) AS `json_set('{"a": [1, 2]}', '$.a[*]', 10)`;
SELECT json_set('{"a": [1, 2]}', '$.a[*]', 10) AS `json_set('{"a": [1, 2]}', '$.a[*]', 10)` LIMIT 100;
SELECT json_set('{"a": [1, 2]}', '$.a[*]', 10) AS `json_set('{"a": [1, 2]}', '$.a[*]', 10)`;
SELECT json_set('$.a[*]', '$.a[*]', 10) AS `json_set('$.a[*]', '$.a[*]', 10)`;
SELECT json_set('{"a": [1, 2]}', '$.a[*]', '$.a[*]') AS `json_set('{"a": [1, 2]}', '$.a[*]', '$.a[*]')`;
SELECT json_set('{"a": [1, 2]}', '$.a[*]', json_set('{"a": [1, 2]}', '$.a[*]', 10)) AS `json_set('{"a": [1, 2]}', '$.a[*]', json_set('{"a": [1, 2]}', '$.a[*]', 10))`;
SELECT json_set('{"a": [1, 2]}', '$.a[*]', 10) AS `json_set('{"a": [1, 2]}', '$.a[*]', 10)` LIMIT 1, 1;
SELECT json_set('{"a": [1, 2]}', '$.a[*]', '$[0]') AS `json_set('{"a": [1, 2]}', '$.a[*]', '$[0]')`;
SELECT json_set('{"a": [1, 2]}', '$.a[*]', 10) AS `json_set('{"a": [1, 2]}', '$.a[*]', 10)` LIMIT 7, 5;
SELECT json_set('{"a": [1, 2]}', '$.a[*]', '$.a[*]') AS `json_set('{"a": [1, 2]}', '$.a[*]', '$.a[*]')`;
SELECT json_set('{"a": [1, 2]}', '', 10) AS `json_set('{"a": [1, 2]}', '', 10)`;
SELECT json_set('{"a": [1, 2]}', NULL, 10) AS `json_set('{"a": [1, 2]}', NULL, 10)`;
SELECT json_set('{"a": [1, 2]}', '$.a[*]', json_set('{"a": [1, 2]}', '$.a[*]', 10)) AS `json_set('{"a": [1, 2]}', '$.a[*]', json_set('{"a": [1, 2]}', '$.a[*]', 10))`;
SELECT json_set('$.a[*]', '$.a[*]', 10) AS `json_set('$.a[*]', '$.a[*]', 10)`;
SELECT json_set('{"a": [1, 2]}', -9223372036854775808, 10) AS `json_set('{"a": [1, 2]}', -9223372036854775808, 10)`;
SELECT json_set(10, '$.a[*]', 10) AS `json_set(10, '$.a[*]', 10)`;