SELECT `srfuzz_mut_701`.`t_like_escape`.`c0`, `srfuzz_mut_701`.`t_like_escape`.`c1` FROM `srfuzz_mut_701`.`t_like_escape` WHERE `srfuzz_mut_701`.`t_like_escape`.`c1` LIKE '%\\\\%' ORDER BY `srfuzz_mut_701`.`t_like_escape`.`c0` ASC;
SELECT `srfuzz_mut_701`.`t_like_escape`.`c0`, `srfuzz_mut_701`.`t_like_escape`.`c1` FROM `srfuzz_mut_701`.`t_like_escape` WHERE `srfuzz_mut_701`.`t_like_escape`.`c1` LIKE '%\\\\asdf' ORDER BY `srfuzz_mut_701`.`t_like_escape`.`c0` ASC;
SELECT `srfuzz_mut_701`.`t_like_escape`.`c0`, `srfuzz_mut_701`.`t_like_escape`.`c1` FROM `srfuzz_mut_701`.`t_like_escape` WHERE `srfuzz_mut_701`.`t_like_escape`.`c1` LIKE 'star\\\\%' ORDER BY `srfuzz_mut_701`.`t_like_escape`.`c0` ASC;
SELECT `srfuzz_mut_701`.`t_like_escape`.`c0`, `srfuzz_mut_701`.`t_like_escape`.`c1` FROM `srfuzz_mut_701`.`t_like_escape` WHERE `srfuzz_mut_701`.`t_like_escape`.`c1` LIKE 'star\\\\' ORDER BY `srfuzz_mut_701`.`t_like_escape`.`c0` ASC;
SELECT `srfuzz_mut_701`.`t_like_escape`.`c0`, `srfuzz_mut_701`.`t_like_escape`.`c1` FROM `srfuzz_mut_701`.`t_like_escape` WHERE `srfuzz_mut_701`.`t_like_escape`.`c1` LIKE 'star\\%' ORDER BY `srfuzz_mut_701`.`t_like_escape`.`c0` ASC;
SELECT `srfuzz_mut_701`.`t_like_escape`.`c0`, `srfuzz_mut_701`.`t_like_escape`.`c1` FROM `srfuzz_mut_701`.`t_like_escape` WHERE like(`srfuzz_mut_701`.`t_like_escape`.`c1`, '%\\\\%') ORDER BY `srfuzz_mut_701`.`t_like_escape`.`c0` ASC;
SELECT `srfuzz_mut_701`.`t_like_escape`.`c0`, `srfuzz_mut_701`.`t_like_escape`.`c1` FROM `srfuzz_mut_701`.`t_like_escape` WHERE like(`srfuzz_mut_701`.`t_like_escape`.`c1`, 'star\\\\') ORDER BY `srfuzz_mut_701`.`t_like_escape`.`c0` ASC;
SELECT `srfuzz_mut_701`.`t_like_escape`.`c0`, `srfuzz_mut_701`.`t_like_escape`.`c1` FROM `srfuzz_mut_701`.`t_like_escape` WHERE (`srfuzz_mut_701`.`t_like_escape`.`c1` LIKE '%\\\\%') OR (`srfuzz_mut_701`.`t_like_escape`.`c1` LIKE 'star%') ORDER BY `srfuzz_mut_701`.`t_like_escape`.`c0` ASC;
SELECT `srfuzz_mut_701`.`t_like_escape`.`c0`, `srfuzz_mut_701`.`t_like_escape`.`c1` FROM `srfuzz_mut_701`.`t_like_escape` WHERE `srfuzz_mut_701`.`t_like_escape`.`c1` LIKE 'abc\\_def' ORDER BY `srfuzz_mut_701`.`t_like_escape`.`c0` ASC;
SELECT 'a\\b' LIKE 'a\\\\b' AS `'a\\b' LIKE 'a\\\\b'`;
SELECT 'a\\b' LIKE 'a\\b' AS `'a\\b' LIKE 'a\\b'`;
SELECT '100%' LIKE '100\\%' AS `'100%' LIKE '100\\%'`;
SELECT '100abc' LIKE '100\\%' AS `'100abc' LIKE '100\\%'`;
SELECT 'a_b' LIKE 'a\\_b' AS `'a_b' LIKE 'a\\_b'`;
SELECT 'aXb' LIKE 'a\\_b' AS `'aXb' LIKE 'a\\_b'`;
SELECT 'abc%xyz' LIKE 'abc\\%%' AS `'abc%xyz' LIKE 'abc\\%%'`;
SELECT 'abcXyz' LIKE 'abc\\%%' AS `'abcXyz' LIKE 'abc\\%%'`;
SELECT 'xyz%abc' LIKE '%\\%abc' AS `'xyz%abc' LIKE '%\\%abc'`;
SELECT 'xa%by' LIKE '%a\\%b%' AS `'xa%by' LIKE '%a\\%b%'`;
SELECT 'xaXby' LIKE '%a\\%b%' AS `'xaXby' LIKE '%a\\%b%'`;
SELECT 'a\\xyz' LIKE 'a\\\\%' AS `'a\\xyz' LIKE 'a\\\\%'`;
SELECT 'abc\\' LIKE 'abc\\\\' AS `'abc\\' LIKE 'abc\\\\'`;
SELECT 'abcdef' LIKE 'abc%' AS `'abcdef' LIKE 'abc%'`;
SELECT 'xyzabc' LIKE '%abc' AS `'xyzabc' LIKE '%abc'`;
SELECT 'xyzabcdef' LIKE '%abc%' AS `'xyzabcdef' LIKE '%abc%'`;
SELECT 'a\\b' LIKE 'a\\\\b' AS `fe_fold`, `srfuzz_mut_701`.`t_like_cmp`.`txt` LIKE 'a\\\\b' AS `be_exec` FROM `srfuzz_mut_701`.`t_like_cmp` WHERE `srfuzz_mut_701`.`t_like_cmp`.`id` = 1;
SELECT 'a\\b' LIKE 'a\\b' AS `fe_fold`, `srfuzz_mut_701`.`t_like_cmp`.`txt` LIKE 'a\\b' AS `be_exec` FROM `srfuzz_mut_701`.`t_like_cmp` WHERE `srfuzz_mut_701`.`t_like_cmp`.`id` = 1;
SELECT '100%' LIKE '100\\%' AS `fe_fold`, `srfuzz_mut_701`.`t_like_cmp`.`txt` LIKE '100\\%' AS `be_exec` FROM `srfuzz_mut_701`.`t_like_cmp` WHERE `srfuzz_mut_701`.`t_like_cmp`.`id` = 2;
SELECT '100abc' LIKE '100\\%' AS `fe_fold`, `srfuzz_mut_701`.`t_like_cmp`.`txt` LIKE '100\\%' AS `be_exec` FROM `srfuzz_mut_701`.`t_like_cmp` WHERE `srfuzz_mut_701`.`t_like_cmp`.`id` = 3;
SELECT 'a_b' LIKE 'a\\_b' AS `fe_fold`, `srfuzz_mut_701`.`t_like_cmp`.`txt` LIKE 'a\\_b' AS `be_exec` FROM `srfuzz_mut_701`.`t_like_cmp` WHERE `srfuzz_mut_701`.`t_like_cmp`.`id` = 4;
SELECT 'aXb' LIKE 'a\\_b' AS `fe_fold`, `srfuzz_mut_701`.`t_like_cmp`.`txt` LIKE 'a\\_b' AS `be_exec` FROM `srfuzz_mut_701`.`t_like_cmp` WHERE `srfuzz_mut_701`.`t_like_cmp`.`id` = 5;
SELECT 'abc%xyz' LIKE 'abc\\%%' AS `fe_fold`, `srfuzz_mut_701`.`t_like_cmp`.`txt` LIKE 'abc\\%%' AS `be_exec` FROM `srfuzz_mut_701`.`t_like_cmp` WHERE `srfuzz_mut_701`.`t_like_cmp`.`id` = 6;
SELECT 'abcXyz' LIKE 'abc\\%%' AS `fe_fold`, `srfuzz_mut_701`.`t_like_cmp`.`txt` LIKE 'abc\\%%' AS `be_exec` FROM `srfuzz_mut_701`.`t_like_cmp` WHERE `srfuzz_mut_701`.`t_like_cmp`.`id` = 7;
SELECT 'xyz%abc' LIKE '%\\%abc' AS `fe_fold`, `srfuzz_mut_701`.`t_like_cmp`.`txt` LIKE '%\\%abc' AS `be_exec` FROM `srfuzz_mut_701`.`t_like_cmp` WHERE `srfuzz_mut_701`.`t_like_cmp`.`id` = 8;
SELECT 'xa%by' LIKE '%a\\%b%' AS `fe_fold`, `srfuzz_mut_701`.`t_like_cmp`.`txt` LIKE '%a\\%b%' AS `be_exec` FROM `srfuzz_mut_701`.`t_like_cmp` WHERE `srfuzz_mut_701`.`t_like_cmp`.`id` = 9;
SELECT 'xaXby' LIKE '%a\\%b%' AS `fe_fold`, `srfuzz_mut_701`.`t_like_cmp`.`txt` LIKE '%a\\%b%' AS `be_exec` FROM `srfuzz_mut_701`.`t_like_cmp` WHERE `srfuzz_mut_701`.`t_like_cmp`.`id` = 10;
SELECT 'a\\xyz' LIKE 'a\\\\%' AS `fe_fold`, `srfuzz_mut_701`.`t_like_cmp`.`txt` LIKE 'a\\\\%' AS `be_exec` FROM `srfuzz_mut_701`.`t_like_cmp` WHERE `srfuzz_mut_701`.`t_like_cmp`.`id` = 11;
SELECT 'abc\\' LIKE 'abc\\\\' AS `fe_fold`, `srfuzz_mut_701`.`t_like_cmp`.`txt` LIKE 'abc\\\\' AS `be_exec` FROM `srfuzz_mut_701`.`t_like_cmp` WHERE `srfuzz_mut_701`.`t_like_cmp`.`id` = 12;
SELECT 'abcdef' LIKE 'abc%' AS `fe_fold`, `srfuzz_mut_701`.`t_like_cmp`.`txt` LIKE 'abc%' AS `be_exec` FROM `srfuzz_mut_701`.`t_like_cmp` WHERE `srfuzz_mut_701`.`t_like_cmp`.`id` = 13;
SELECT 'xyzabc' LIKE '%abc' AS `fe_fold`, `srfuzz_mut_701`.`t_like_cmp`.`txt` LIKE '%abc' AS `be_exec` FROM `srfuzz_mut_701`.`t_like_cmp` WHERE `srfuzz_mut_701`.`t_like_cmp`.`id` = 14;
SELECT 'xyzabcdef' LIKE '%abc%' AS `fe_fold`, `srfuzz_mut_701`.`t_like_cmp`.`txt` LIKE '%abc%' AS `be_exec` FROM `srfuzz_mut_701`.`t_like_cmp` WHERE `srfuzz_mut_701`.`t_like_cmp`.`id` = 15;
SELECT 'a\\b' LIKE (repeat('x', 65536)) AS `'a\\b' LIKE (repeat('x', 65536))`;
SELECT 'a\\b' LIKE 'a\\\\b' AS `'a\\b' LIKE 'a\\\\b'`;
SELECT 'a\\b' LIKE 'a\\\\b' AS `'a\\b' LIKE 'a\\\\b'` ORDER BY 'a\\b' LIKE 'a\\\\b' DESC;
SELECT DISTINCT 'a\\b' LIKE 'a\\\\b' AS `'a\\b' LIKE 'a\\\\b'`;
SELECT 'a\\b' LIKE 'a\\\\b' AS `'a\\b' LIKE 'a\\\\b'` LIMIT 7, 2;
SELECT 'a\\\\b' LIKE 'a\\\\b' AS `'a\\\\b' LIKE 'a\\\\b'`;
SELECT 'a\\b' LIKE 'a\\\\b' AS `'a\\b' LIKE 'a\\\\b'`;
SELECT 'a\\b' LIKE 'a\\\\b' AS `'a\\b' LIKE 'a\\\\b'`;
SELECT 'a\\b' LIKE 'a\\\\b' AS `'a\\b' LIKE 'a\\\\b'` GROUP BY 'a\\b' LIKE 'a\\\\b';
SELECT 'a\\b' LIKE 'a\\\\b' AS `'a\\b' LIKE 'a\\\\b'`;
SELECT 'a\\b' LIKE 'a\\\\b' AS `'a\\b' LIKE 'a\\\\b'` LIMIT 1, 5;
SELECT 'a\\b' LIKE 'a\\\\b' AS `'a\\b' LIKE 'a\\\\b'`;
SELECT 'a\\\\b' LIKE 'a\\\\b' AS `'a\\\\b' LIKE 'a\\\\b'`;
SELECT 'a\\b' LIKE 'a\\\\b' AS `'a\\b' LIKE 'a\\\\b'` LIMIT 0;
SELECT 'a\\b' LIKE 'a\\\\b' AS `'a\\b' LIKE 'a\\\\b'` LIMIT 7, 1;
SELECT (repeat('x', 65536)) LIKE 'a\\\\b' AS `(repeat('x', 65536)) LIKE 'a\\\\b'`;
SELECT CAST(('a\\b' LIKE 'a\\\\b') AS CHAR(1)) AS `CAST(('a\\b' LIKE 'a\\\\b') AS CHAR(1))`;
SELECT 'a\\b' LIKE 'a\\\\b' AS `'a\\b' LIKE 'a\\\\b'`;
SELECT 'a\\b' LIKE 'a\\\\b' AS `'a\\b' LIKE 'a\\\\b'` WHERE 'abcdef' LIKE 'abc%';
SELECT 'a\\b' LIKE '0000-00-00' AS `'a\\b' LIKE '0000-00-00'`;
SELECT json_query(CAST(('a\\b' LIKE 'a\\b') AS JSON), '$.a') AS `json_query(CAST(('a\\b' LIKE 'a\\b') AS JSON), '$.a')`;
SELECT 'a\\b' LIKE 'a\\b' AS `'a\\b' LIKE 'a\\b'` GROUP BY 'a\\b' LIKE 'a\\b';
SELECT '%abc%' LIKE 'a\\b' AS `'%abc%' LIKE 'a\\b'`;
SELECT 'a\\b' LIKE '' AS `'a\\b' LIKE ''`;
SELECT 'a\\b' LIKE '' AS `'a\\b' LIKE ''`;
SELECT 'a\\b' LIKE 'a\\b' AS `'a\\b' LIKE 'a\\b'`;
SELECT 'a\\b' LIKE 'a\\b' AS `'a\\b' LIKE 'a\\b'`;
SELECT 'a\\b' LIKE 'a\\b' AS `'a\\b' LIKE 'a\\b'` GROUP BY 'a\\b' LIKE 'a\\b';
SELECT 'a\\b' LIKE 'a\\b' AS `'a\\b' LIKE 'a\\b'`;
SELECT 'a\\b' LIKE 'a\\b' AS `'a\\b' LIKE 'a\\b'` ORDER BY 'a\\b' LIKE 'a\\b' DESC NULLS FIRST;
SELECT 'a\\b' LIKE 'a\\b' AS `'a\\b' LIKE 'a\\b'`;
SELECT json_query(CAST(('a\\b' LIKE 'a\\b') AS JSON), '$.a') AS `json_query(CAST(('a\\b' LIKE 'a\\b') AS JSON), '$.a')`;
SELECT 'a\\b' LIKE 'a\\b' AS `'a\\b' LIKE 'a\\b'`;
SELECT 'a\\b' LIKE 'a\\b' AS `'a\\b' LIKE 'a\\b'`;
SELECT 'a\\b' LIKE 'a\\b' AS `'a\\b' LIKE 'a\\b'`;
SELECT 'a\\b' LIKE 'a\\b' AS `'a\\b' LIKE 'a\\b'`;
SELECT 'a\\b' LIKE 'a\\b' AS `'a\\b' LIKE 'a\\b'`;
SELECT 'a\\b' LIKE 'a\\b' AS `'a\\b' LIKE 'a\\b'`;
SELECT '0000-00-00' LIKE 'a\\b' AS `'0000-00-00' LIKE 'a\\b'`;
SELECT 'a\\b' LIKE 'a\\b' AS `'a\\b' LIKE 'a\\b'` GROUP BY 'a\\b' LIKE 'a\\b';
SELECT '100\\%' LIKE '100\\%' AS `'100\\%' LIKE '100\\%'`;
SELECT DISTINCT '100%' LIKE '100\\%' AS `'100%' LIKE '100\\%'`;
SELECT DISTINCT '100%' LIKE '100\\%' AS `'100%' LIKE '100\\%'`;
SELECT '100%' LIKE '100\\%' AS `'100%' LIKE '100\\%'` LIMIT 100;
SELECT '100%' LIKE '100\\%' AS `'100%' LIKE '100\\%'` LIMIT 1;
SELECT '100%' LIKE '100\\%' AS `'100%' LIKE '100\\%'` LIMIT 1;
SELECT '\\' LIKE '100\\%' AS `'\\' LIKE '100\\%'`;
SELECT '100%' LIKE '100\\%' AS `'100%' LIKE '100\\%'`;
SELECT '100\\%' LIKE '100\\%' AS `'100\\%' LIKE '100\\%'`;
SELECT '100%' LIKE '' AS `'100%' LIKE ''`;
SELECT '100%' LIKE (get_json_string(CAST('100\\%' AS JSON), '$.a')) AS `'100%' LIKE (get_json_string(CAST('100\\%' AS JSON), '$.a'))`;
SELECT '100%' LIKE NULL AS `'100%' LIKE NULL`;
SELECT '100%' LIKE '100%' AS `'100%' LIKE '100%'`;
SELECT '' LIKE '100\\%' AS `'' LIKE '100\\%'`;
SELECT '100\\%' LIKE '100\\%' AS `'100\\%' LIKE '100\\%'`;
SELECT '100%' LIKE '100\\%' AS `'100%' LIKE '100\\%'`;
SELECT '100%' LIKE '100\\%' AS `'100%' LIKE '100\\%'` WHERE 'xa%by' LIKE '%a\\%b%';
SELECT '100%' LIKE '100\\%' AS `'100%' LIKE '100\\%'`;
SELECT '100\\%' LIKE '100\\%' AS `'100\\%' LIKE '100\\%'`;
SELECT '100%' LIKE '1970-01-01' AS `'100%' LIKE '1970-01-01'`;
SELECT '100%' LIKE '100%' AS `'100%' LIKE '100%'`;
SELECT '100%' LIKE '100\\%' AS `'100%' LIKE '100\\%'`;
SELECT '1970-01-01' LIKE '100\\%' AS `'1970-01-01' LIKE '100\\%'`;
SELECT '%' LIKE '100\\%' AS `'%' LIKE '100\\%'`;
SELECT '100abc' LIKE '100\\%' AS `'100abc' LIKE '100\\%'` ORDER BY '100abc' LIKE '100\\%' ASC;
SELECT DISTINCT '100abc' LIKE '100\\%' AS `'100abc' LIKE '100\\%'`;
SELECT DISTINCT '100abc' LIKE '100\\%' AS `'100abc' LIKE '100\\%'`;
SELECT '100abc' LIKE '100\\%' AS `'100abc' LIKE '100\\%'` GROUP BY '100abc' LIKE '100\\%';
SELECT '100abc' LIKE '100abc' AS `'100abc' LIKE '100abc'`;
SELECT '100abc' LIKE '100abc' AS `'100abc' LIKE '100abc'`;
SELECT '0' LIKE '100\\%' AS `'0' LIKE '100\\%'`;
SELECT '100abc' LIKE '100\\%' AS `'100abc' LIKE '100\\%'`;
SELECT '100abc' LIKE '100\\%' AS `'100abc' LIKE '100\\%'` GROUP BY '100abc' LIKE '100\\%';
SELECT '100abc' LIKE '100\\%' AS `'100abc' LIKE '100\\%'`;
SELECT '100abc' LIKE '100\\%' AS `'100abc' LIKE '100\\%'` WHERE '100abc' LIKE '100\\%';
SELECT '100abc' LIKE '100\\%' AS `'100abc' LIKE '100\\%'` GROUP BY '100abc' LIKE '100\\%';
SELECT '100abc' LIKE '9999-12-31 23:59:59' AS `'100abc' LIKE '9999-12-31 23:59:59'`;
SELECT '100abc' LIKE '100\\%' AS `'100abc' LIKE '100\\%'` GROUP BY '100abc' LIKE '100\\%';
SELECT '100abc' LIKE '100\\%' AS `'100abc' LIKE '100\\%'` LIMIT 7, 1;
SELECT '100abc' LIKE '100\\%' AS `'100abc' LIKE '100\\%'` ORDER BY '100abc' LIKE '100\\%' DESC;
SELECT '100abc' LIKE 'a\\xyz' AS `'100abc' LIKE 'a\\xyz'`;
SELECT '100abc' LIKE '100\\%' AS `'100abc' LIKE '100\\%'`;
SELECT '100abc' LIKE 'abc%xyz' AS `'100abc' LIKE 'abc%xyz'`;
SELECT '100abc' LIKE '100abc' AS `'100abc' LIKE '100abc'`;
SELECT get_json_string(CAST(('100abc' LIKE '100\\%') AS JSON), '$.a') AS `get_json_string(CAST(('100abc' LIKE '100\\%') AS JSON), '$.a')`;
SELECT count('100abc' LIKE '100\\%') OVER () AS `count('100abc' LIKE '100\\%') OVER ()`;
SELECT '0' LIKE '100\\%' AS `'0' LIKE '100\\%'`;
SELECT '100abc' LIKE '' AS `'100abc' LIKE ''`;
SELECT '100abc' LIKE '100\\%' AS `'100abc' LIKE '100\\%'` GROUP BY '100abc' LIKE '100\\%';
SELECT '%' LIKE 'a\\_b' AS `'%' LIKE 'a\\_b'`;
SELECT CAST(('a_b' LIKE 'a\\_b') AS DECIMAL128(38,0)) AS `CAST(('a_b' LIKE 'a\\_b') AS DECIMAL128(38,0))`;
SELECT 'a_b' LIKE 'a_b' AS `'a_b' LIKE 'a_b'`;
SELECT 'a_b' LIKE 'a\\_b' AS `'a_b' LIKE 'a\\_b'`;
SELECT '9999-12-31 23:59:59' LIKE 'a\\_b' AS `'9999-12-31 23:59:59' LIKE 'a\\_b'`;
SELECT 'a_b' LIKE 'a\\_b' AS `'a_b' LIKE 'a\\_b'`;
SELECT 'a_b' LIKE 'a\\_b' AS `'a_b' LIKE 'a\\_b'`;
SELECT 'a_b' LIKE 'a\\_b' AS `'a_b' LIKE 'a\\_b'`;
SELECT 'a_b' LIKE '1970-01-01' AS `'a_b' LIKE '1970-01-01'`;
SELECT '9999-12-31 23:59:59' LIKE 'a\\_b' AS `'9999-12-31 23:59:59' LIKE 'a\\_b'`;
SELECT 'a\\_b' LIKE 'a\\_b' AS `'a\\_b' LIKE 'a\\_b'`;
SELECT 'a_b' LIKE 'a\\_b' AS `'a_b' LIKE 'a\\_b'` ORDER BY 'a_b' LIKE 'a\\_b' ASC NULLS LAST;
SELECT 'a_b' LIKE 'a\\_b' AS `'a_b' LIKE 'a\\_b'` ORDER BY 'a_b' LIKE 'a\\_b' DESC NULLS FIRST;
SELECT DISTINCT 'a_b' LIKE 'a\\_b' AS `'a_b' LIKE 'a\\_b'`;
SELECT 'a_b' LIKE 'a\\_b' AS `'a_b' LIKE 'a\\_b'`;
SELECT 'a_b' LIKE 'a\\_b' AS `'a_b' LIKE 'a\\_b'` LIMIT 100;
SELECT 'a_b' LIKE '1970-01-01' AS `'a_b' LIKE '1970-01-01'`;
SELECT 'a_b' LIKE 'a_b' AS `'a_b' LIKE 'a_b'`;
SELECT 'a_b' LIKE 'a\\_b' AS `'a_b' LIKE 'a\\_b'`;
SELECT DISTINCT 'a_b' LIKE 'a\\_b' AS `'a_b' LIKE 'a\\_b'`;
SELECT 'a_b' LIKE 'a\\_b' AS `'a_b' LIKE 'a\\_b'`;
SELECT 'aXb' LIKE 'aXb' AS `'aXb' LIKE 'aXb'`;
SELECT 'aXb' LIKE 'a\\_b' AS `'aXb' LIKE 'a\\_b'`;
SELECT '\\' LIKE 'a\\_b' AS `'\\' LIKE 'a\\_b'`;
SELECT 'aXb' LIKE 'a\\_b' AS `'aXb' LIKE 'a\\_b'` LIMIT 5;
SELECT 'aXb' LIKE 'a\\_b' AS `'aXb' LIKE 'a\\_b'`;
SELECT 'aXb' LIKE 'aXb' AS `'aXb' LIKE 'aXb'`;
SELECT 'aXb' LIKE 'aXb' AS `'aXb' LIKE 'aXb'`;
SELECT (repeat('x', 65536)) LIKE 'a\\_b' AS `(repeat('x', 65536)) LIKE 'a\\_b'`;
SELECT 'aXb' LIKE (repeat('x', 65536)) AS `'aXb' LIKE (repeat('x', 65536))`;
SELECT 'aXb' LIKE 'a\\_b' AS `'aXb' LIKE 'a\\_b'`;
SELECT 'aXb' LIKE 'a\\_b' AS `'aXb' LIKE 'a\\_b'`;
SELECT 'a\\_b' LIKE 'a\\_b' AS `'a\\_b' LIKE 'a\\_b'`;
SELECT 'aXb' LIKE 'a\\_b' AS `'aXb' LIKE 'a\\_b'`;
SELECT 'aXb' LIKE 'a\\_b' AS `'aXb' LIKE 'a\\_b'` GROUP BY 'aXb' LIKE 'a\\_b';
SELECT 'aXb' LIKE 'a\\_b' AS `'aXb' LIKE 'a\\_b'` ORDER BY 'aXb' LIKE 'a\\_b' DESC;
SELECT '0000-00-00' LIKE 'a\\_b' AS `'0000-00-00' LIKE 'a\\_b'`;
SELECT 'aXb' LIKE 'a\\_b' AS `'aXb' LIKE 'a\\_b'`;
SELECT 'aXb' LIKE 'a\\_b' AS `'aXb' LIKE 'a\\_b'` GROUP BY 'aXb' LIKE 'a\\_b';
SELECT 'a\\_b' LIKE 'a\\_b' AS `'a\\_b' LIKE 'a\\_b'`;
SELECT 'aXb' LIKE 'a\\_b' AS `'aXb' LIKE 'a\\_b'`;
SELECT 'aXb' LIKE 'aXb' AS `'aXb' LIKE 'aXb'`;
SELECT 'aXb' LIKE 'a\\_b' AS `'aXb' LIKE 'a\\_b'`;
SELECT DISTINCT 'aXb' LIKE 'a\\_b' AS `'aXb' LIKE 'a\\_b'`;
SELECT 'abc\\%%' LIKE 'abc\\%%' AS `'abc\\%%' LIKE 'abc\\%%'`;
SELECT 'abc\\%%' LIKE 'abc\\%%' AS `'abc\\%%' LIKE 'abc\\%%'`;
SELECT 'abc%xyz' LIKE 'abc\\%%' AS `'abc%xyz' LIKE 'abc\\%%'`;
SELECT 'abc%xyz' LIKE 'abc%xyz' AS `'abc%xyz' LIKE 'abc%xyz'`;
SELECT 'abc\\%%' LIKE 'abc\\%%' AS `'abc\\%%' LIKE 'abc\\%%'`;
SELECT 'abc%xyz' LIKE 'abc\\%%' AS `'abc%xyz' LIKE 'abc\\%%'`;
SELECT count('abc%xyz' LIKE 'abc\\%%') OVER () AS `count('abc%xyz' LIKE 'abc\\%%') OVER ()`;
SELECT 'abc%xyz' LIKE 'abc\\_def' AS `'abc%xyz' LIKE 'abc\\_def'`;
SELECT '9999-12-31 23:59:59' LIKE 'abc\\%%' AS `'9999-12-31 23:59:59' LIKE 'abc\\%%'`;
SELECT 'abc%xyz' LIKE 'abc\\%%' AS `'abc%xyz' LIKE 'abc\\%%'`;
SELECT sum('abc%xyz' LIKE 'abc\\%%') OVER () AS `sum('abc%xyz' LIKE 'abc\\%%') OVER ()`;
SELECT 'abc%xyz' LIKE '' AS `'abc%xyz' LIKE ''`;
SELECT 'abc%xyz' LIKE NULL AS `'abc%xyz' LIKE NULL`;
SELECT DISTINCT 'abc%xyz' LIKE 'abc\\%%' AS `'abc%xyz' LIKE 'abc\\%%'`;
SELECT 'a\\_b' LIKE 'abc\\%%' AS `'a\\_b' LIKE 'abc\\%%'`;
SELECT 'abc%xyz' LIKE 'abc\\%%' AS `'abc%xyz' LIKE 'abc\\%%'`;
SELECT 'abc%xyz' LIKE 'abc%xyz' AS `'abc%xyz' LIKE 'abc%xyz'`;
SELECT 'abc%xyz' LIKE 'abc\\%%' AS `'abc%xyz' LIKE 'abc\\%%'`;
SELECT 'abc%xyz' LIKE 'abc\\%%' AS `'abc%xyz' LIKE 'abc\\%%'`;
SELECT 'abc%xyz' LIKE 'abc%xyz' AS `'abc%xyz' LIKE 'abc%xyz'`;
SELECT 'abc%xyz' LIKE '%' AS `'abc%xyz' LIKE '%'`;
SELECT 'abc\\%%' LIKE 'abc\\%%' AS `'abc\\%%' LIKE 'abc\\%%'`;
SELECT 'abcXyz' LIKE (get_json_string(CAST('abc\\%%' AS JSON), '$.a')) AS `'abcXyz' LIKE (get_json_string(CAST('abc\\%%' AS JSON), '$.a'))`;
SELECT 'abcXyz' LIKE 'abc\\%%' AS `'abcXyz' LIKE 'abc\\%%'` LIMIT 1;
SELECT 'abcXyz' LIKE 'abc\\%%' AS `'abcXyz' LIKE 'abc\\%%'`;
SELECT '0000-00-00' LIKE 'abc\\%%' AS `'0000-00-00' LIKE 'abc\\%%'`;
SELECT CAST(('abcXyz' LIKE 'abc\\%%') AS DOUBLE) AS `CAST(('abcXyz' LIKE 'abc\\%%') AS DOUBLE)`;
SELECT 'a\\\\b' LIKE 'abc\\%%' AS `'a\\\\b' LIKE 'abc\\%%'`;
SELECT '0' LIKE 'abc\\%%' AS `'0' LIKE 'abc\\%%'`;
SELECT 'abcXyz' LIKE 'abc\\%%' AS `'abcXyz' LIKE 'abc\\%%'` GROUP BY 'abcXyz' LIKE 'abc\\%%';
SELECT 'abcXyz' LIKE 'abc\\%%' AS `'abcXyz' LIKE 'abc\\%%'`;
SELECT 'abcXyz' LIKE 'abcXyz' AS `'abcXyz' LIKE 'abcXyz'`;
SELECT 'abcXyz' LIKE '1970-01-01' AS `'abcXyz' LIKE '1970-01-01'`;
SELECT DISTINCT 'abcXyz' LIKE 'abc\\%%' AS `'abcXyz' LIKE 'abc\\%%'`;
SELECT 'abcXyz' LIKE 'abc\\%%' AS `'abcXyz' LIKE 'abc\\%%'`;
SELECT 'abcXyz' LIKE 'abcXyz' AS `'abcXyz' LIKE 'abcXyz'`;
SELECT 'abc\\%%' LIKE 'abc\\%%' AS `'abc\\%%' LIKE 'abc\\%%'`;
SELECT 'abcXyz' LIKE 'abc\\%%' AS `'abcXyz' LIKE 'abc\\%%'`;
SELECT 'abc\\%%' LIKE 'abc\\%%' AS `'abc\\%%' LIKE 'abc\\%%'`;
SELECT 'abcXyz' LIKE 'abcXyz' AS `'abcXyz' LIKE 'abcXyz'`;
SELECT 'abcXyz' LIKE 'abc\\%%' AS `'abcXyz' LIKE 'abc\\%%'`;
SELECT 'abcXyz' LIKE 'abcXyz' AS `'abcXyz' LIKE 'abcXyz'`;
SELECT '' LIKE 'abc\\%%' AS `'' LIKE 'abc\\%%'`;
SELECT 'abcXyz' LIKE '\\' AS `'abcXyz' LIKE '\\'`;
SELECT 'xyz%abc' LIKE '0' AS `'xyz%abc' LIKE '0'`;
SELECT 'xyz%abc' LIKE '%\\%abc' AS `'xyz%abc' LIKE '%\\%abc'` ORDER BY 'xyz%abc' LIKE '%\\%abc' DESC;
SELECT 'xyz%abc' LIKE 'xyz%abc' AS `'xyz%abc' LIKE 'xyz%abc'`;
SELECT 'xyz%abc' LIKE '%\\%abc' AS `'xyz%abc' LIKE '%\\%abc'` WHERE 'xa%by' LIKE '%a\\%b%';
SELECT 'xyz%abc' LIKE 'xyz%abc' AS `'xyz%abc' LIKE 'xyz%abc'`;
SELECT DISTINCT 'xyz%abc' LIKE '%\\%abc' AS `'xyz%abc' LIKE '%\\%abc'`;
SELECT 'xyz%abc' LIKE '%\\%abc' AS `'xyz%abc' LIKE '%\\%abc'`;
SELECT (get_json_string(CAST('xyz%abc' AS JSON), '$.a')) LIKE '%\\%abc' AS `(get_json_string(CAST('xyz%abc' AS JSON), '$.a')) LIKE '%\\%abc'`;
SELECT CAST((CAST((CAST(('xyz%abc' LIKE '%\\%abc') AS TIME)) AS DECIMAL128(38,37))) AS TIME) AS `CAST((CAST((CAST(('xyz%abc' LIKE '%\\%abc') AS TIME)) AS DECIMAL128(38,37))) AS TIME)`;
SELECT 'xyz%abc' LIKE 'xyz%abc' AS `'xyz%abc' LIKE 'xyz%abc'`;
SELECT DISTINCT 'xyz%abc' LIKE '%\\%abc' AS `'xyz%abc' LIKE '%\\%abc'`;
SELECT 'xyz%abc' LIKE '%\\%abc' AS `'xyz%abc' LIKE '%\\%abc'` GROUP BY 'xyz%abc' LIKE '%\\%abc';
SELECT 'xyz%abc' LIKE '%\\%abc' AS `'xyz%abc' LIKE '%\\%abc'`;
SELECT '%\\%abc' LIKE '%\\%abc' AS `'%\\%abc' LIKE '%\\%abc'`;
SELECT 'abc\\\\' LIKE '%\\%abc' AS `'abc\\\\' LIKE '%\\%abc'`;
SELECT 'xyz%abc' LIKE (get_json_string(CAST('%\\%abc' AS JSON), '$.a')) AS `'xyz%abc' LIKE (get_json_string(CAST('%\\%abc' AS JSON), '$.a'))`;
SELECT '%\\%abc' LIKE '%\\%abc' AS `'%\\%abc' LIKE '%\\%abc'`;
SELECT '%\\%abc' LIKE '%\\%abc' AS `'%\\%abc' LIKE '%\\%abc'`;
SELECT 'xyz%abc' LIKE '%\\%abc' AS `'xyz%abc' LIKE '%\\%abc'` GROUP BY 'xyz%abc' LIKE '%\\%abc';
SELECT 'xyz%abc' LIKE 'xyz%abc' AS `'xyz%abc' LIKE 'xyz%abc'`;
SELECT 'xyz%abc' LIKE '%\\%abc' AS `'xyz%abc' LIKE '%\\%abc'`;
SELECT 'xyz%abc' LIKE '%\\%abc' AS `'xyz%abc' LIKE '%\\%abc'`;
SELECT 'xa%by' LIKE '%a\\%b%' AS `'xa%by' LIKE '%a\\%b%'`;
SELECT 'xa%by' LIKE '%a\\%b%' AS `'xa%by' LIKE '%a\\%b%'`;
SELECT 'xa%by' LIKE '%a\\%b%' AS `'xa%by' LIKE '%a\\%b%'`;
SELECT 'xa%by' LIKE '%a\\%b%' AS `'xa%by' LIKE '%a\\%b%'` ORDER BY 'xa%by' LIKE '%a\\%b%' DESC;
SELECT DISTINCT 'xa%by' LIKE '%a\\%b%' AS `'xa%by' LIKE '%a\\%b%'`;
SELECT 'xa%by' LIKE '%a\\%b%' AS `'xa%by' LIKE '%a\\%b%'` GROUP BY 'xa%by' LIKE '%a\\%b%';
SELECT avg('xa%by' LIKE '%a\\%b%') OVER () AS `avg('xa%by' LIKE '%a\\%b%') OVER ()`;
SELECT 'xa%by' LIKE '%a\\%b%' AS `'xa%by' LIKE '%a\\%b%'`;
SELECT 'xa%by' LIKE '%a\\%b%' AS `'xa%by' LIKE '%a\\%b%'`;
SELECT 'xa%by' LIKE (get_json_string(CAST('%a\\%b%' AS JSON), '$.a')) AS `'xa%by' LIKE (get_json_string(CAST('%a\\%b%' AS JSON), '$.a'))`;
SELECT '9999-12-31 23:59:59' LIKE '%a\\%b%' AS `'9999-12-31 23:59:59' LIKE '%a\\%b%'`;
SELECT 'xa%by' LIKE '%a\\%b%' AS `'xa%by' LIKE '%a\\%b%'` ORDER BY 'xa%by' LIKE '%a\\%b%' ASC;
SELECT CAST((CAST(('xa%by' LIKE '%a\\%b%') AS INT)) AS DECIMAL128(38,38)) AS `CAST((CAST(('xa%by' LIKE '%a\\%b%') AS INT)) AS DECIMAL128(38,38))`;
SELECT '%a\\%b%' LIKE '%a\\%b%' AS `'%a\\%b%' LIKE '%a\\%b%'`;
SELECT 'xa%by' LIKE '%a\\%b%' AS `'xa%by' LIKE '%a\\%b%'` WHERE 'xyzabc' LIKE '%abc';
SELECT 'xa%by' LIKE 'xa%by' AS `'xa%by' LIKE 'xa%by'`;
SELECT '0000-00-00' LIKE '%a\\%b%' AS `'0000-00-00' LIKE '%a\\%b%'`;
SELECT '1970-01-01' LIKE '%a\\%b%' AS `'1970-01-01' LIKE '%a\\%b%'`;
SELECT 'xa%by' LIKE 'xa%by' AS `'xa%by' LIKE 'xa%by'`;
SELECT 'xa%by' LIKE 'xa%by' AS `'xa%by' LIKE 'xa%by'`;
SELECT 'xa%by' LIKE '%a\\%b%' AS `'xa%by' LIKE '%a\\%b%'` LIMIT 2;
SELECT CAST((CAST(('xa%by' LIKE '%a\\%b%') AS FLOAT)) AS DECIMAL128(38,38)) AS `CAST((CAST(('xa%by' LIKE '%a\\%b%') AS FLOAT)) AS DECIMAL128(38,38))`;
SELECT '%a\\%b%' LIKE '%a\\%b%' AS `'%a\\%b%' LIKE '%a\\%b%'`;
SELECT 'xa%by' LIKE '%a\\%b%' AS `'xa%by' LIKE '%a\\%b%'` ORDER BY 'xa%by' LIKE '%a\\%b%' DESC;
SELECT DISTINCT 'xa%by' LIKE '%a\\%b%' AS `'xa%by' LIKE '%a\\%b%'`;
SELECT '0000-00-00' LIKE '%a\\%b%' AS `'0000-00-00' LIKE '%a\\%b%'`;
SELECT '%a\\%b%' LIKE '%a\\%b%' AS `'%a\\%b%' LIKE '%a\\%b%'`;
SELECT 'xa%by' LIKE '%a\\%b%' AS `'xa%by' LIKE '%a\\%b%'`;
SELECT 'xa%by' LIKE '%a\\%b%' AS `'xa%by' LIKE '%a\\%b%'`;
SELECT '%a\\%b%' LIKE '%a\\%b%' AS `'%a\\%b%' LIKE '%a\\%b%'`;
SELECT 'xaXby' LIKE '%a\\%b%' AS `'xaXby' LIKE '%a\\%b%'`;
SELECT 'xaXby' LIKE 'xaXby' AS `'xaXby' LIKE 'xaXby'`;
SELECT 'xaXby' LIKE '%a\\%b%' AS `'xaXby' LIKE '%a\\%b%'` LIMIT 5;
SELECT 'xaXby' LIKE 'xaXby' AS `'xaXby' LIKE 'xaXby'`;
SELECT 'xaXby' LIKE '%a\\%b%' AS `'xaXby' LIKE '%a\\%b%'`;
SELECT 'xaXby' LIKE '%a\\%b%' AS `'xaXby' LIKE '%a\\%b%'`;
SELECT '%a\\%b%' LIKE '%a\\%b%' AS `'%a\\%b%' LIKE '%a\\%b%'`;
SELECT 'xaXby' LIKE '%a\\%b%' AS `'xaXby' LIKE '%a\\%b%'` ORDER BY 'xaXby' LIKE '%a\\%b%' DESC;
SELECT 'xaXby' LIKE '%a\\%b%' AS `'xaXby' LIKE '%a\\%b%'` ORDER BY 'xaXby' LIKE '%a\\%b%' ASC;
SELECT 'xaXby' LIKE '%a\\%b%' AS `'xaXby' LIKE '%a\\%b%'`;
SELECT '0000-00-00' LIKE '%a\\%b%' AS `'0000-00-00' LIKE '%a\\%b%'`;
SELECT 'xaXby' LIKE '%a\\%b%' AS `'xaXby' LIKE '%a\\%b%'`;
SELECT 'xaXby' LIKE 'xaXby' AS `'xaXby' LIKE 'xaXby'`;
SELECT '%a\\%b%' LIKE '%a\\%b%' AS `'%a\\%b%' LIKE '%a\\%b%'`;
SELECT 'xaXby' LIKE '%a\\%b%' AS `'xaXby' LIKE '%a\\%b%'` GROUP BY 'xaXby' LIKE '%a\\%b%';
SELECT '\\' LIKE '%a\\%b%' AS `'\\' LIKE '%a\\%b%'`;
SELECT 'xaXby' LIKE 'xaXby' AS `'xaXby' LIKE 'xaXby'`;
SELECT 'xaXby' LIKE '%a\\%b%' AS `'xaXby' LIKE '%a\\%b%'`;
SELECT 'xaXby' LIKE '%' AS `'xaXby' LIKE '%'`;
SELECT 'xaXby' LIKE '%a\\%b%' AS `'xaXby' LIKE '%a\\%b%'` LIMIT 0;
SELECT 'xaXby' LIKE 'xaXby' AS `'xaXby' LIKE 'xaXby'`;
SELECT 'xaXby' LIKE '%a\\%b%' AS `'xaXby' LIKE '%a\\%b%'` ORDER BY 'xaXby' LIKE '%a\\%b%' ASC NULLS LAST;
SELECT 'xaXby' LIKE '%a\\%b%' AS `'xaXby' LIKE '%a\\%b%'`;
SELECT 'xaXby' LIKE 'xaXby' AS `'xaXby' LIKE 'xaXby'`;
SELECT 'xaXby' LIKE 'xaXby' AS `'xaXby' LIKE 'xaXby'`;
SELECT 'xaXby' LIKE '%a\\%b%' AS `'xaXby' LIKE '%a\\%b%'`;
SELECT DISTINCT 'xaXby' LIKE '%a\\%b%' AS `'xaXby' LIKE '%a\\%b%'`;
SELECT 'xaXby' LIKE '%a\\%b%' AS `'xaXby' LIKE '%a\\%b%'` LIMIT 2;
SELECT 'a\\xyz' LIKE 'a\\\\%' AS `'a\\xyz' LIKE 'a\\\\%'`;
SELECT 'a\\xyz' LIKE 'a\\\\%' AS `'a\\xyz' LIKE 'a\\\\%'`;
SELECT 'a\\xyz' LIKE 'a\\\\%' AS `'a\\xyz' LIKE 'a\\\\%'`;
SELECT 'a\\\\%' LIKE 'a\\\\%' AS `'a\\\\%' LIKE 'a\\\\%'`;
SELECT 'a\\\\%' LIKE 'a\\\\%' AS `'a\\\\%' LIKE 'a\\\\%'`;
SELECT 'a\\xyz' LIKE 'a\\\\%' AS `'a\\xyz' LIKE 'a\\\\%'` LIMIT 5;
SELECT 'a\\xyz' LIKE 'a\\\\%' AS `'a\\xyz' LIKE 'a\\\\%'` GROUP BY 'a\\xyz' LIKE 'a\\\\%';
SELECT 'a\\\\%' LIKE 'a\\\\%' AS `'a\\\\%' LIKE 'a\\\\%'`;
SELECT 'a\\xyz' LIKE 'a\\xyz' AS `'a\\xyz' LIKE 'a\\xyz'`;
SELECT 'a\\xyz' LIKE 'a\\\\%' AS `'a\\xyz' LIKE 'a\\\\%'`;
SELECT 'a\\\\%' LIKE 'a\\\\%' AS `'a\\\\%' LIKE 'a\\\\%'`;
SELECT 'a\\xyz' LIKE 'a\\\\%' AS `'a\\xyz' LIKE 'a\\\\%'`;
SELECT 'a\\xyz' LIKE 'a\\\\%' AS `'a\\xyz' LIKE 'a\\\\%'`;
SELECT 'a\\xyz' LIKE 'a\\\\%' AS `'a\\xyz' LIKE 'a\\\\%'`;
SELECT 'a\\xyz' LIKE 'a\\\\%' AS `'a\\xyz' LIKE 'a\\\\%'`;
SELECT (repeat('x', 65536)) LIKE 'a\\\\%' AS `(repeat('x', 65536)) LIKE 'a\\\\%'`;
SELECT CAST(('a\\xyz' LIKE 'a\\\\%') AS JSON)->'$' AS `CAST(('a\\xyz' LIKE 'a\\\\%') AS JSON)->'$'`;
SELECT 'a\\\\%' LIKE 'a\\\\%' AS `'a\\\\%' LIKE 'a\\\\%'`;
SELECT 'a\\xyz' LIKE 'a\\\\%' AS `'a\\xyz' LIKE 'a\\\\%'`;
SELECT 'a\\xyz' LIKE '%abc%' AS `'a\\xyz' LIKE '%abc%'`;
SELECT 'abc\\' LIKE 'abc\\\\' AS `'abc\\' LIKE 'abc\\\\'`;
SELECT 'abcdef' LIKE 'abc\\\\' AS `'abcdef' LIKE 'abc\\\\'`;
SELECT 'abc\\' LIKE 'abc\\\\' AS `'abc\\' LIKE 'abc\\\\'` ORDER BY 'abc\\' LIKE 'abc\\\\' DESC NULLS FIRST;
SELECT 'abc\\\\' LIKE 'abc\\\\' AS `'abc\\\\' LIKE 'abc\\\\'`;
SELECT 'abc\\' LIKE 'abc\\\\' AS `'abc\\' LIKE 'abc\\\\'` WHERE 'a\\b' LIKE 'a\\\\b';
SELECT 'abc\\' LIKE 'abc\\\\' AS `'abc\\' LIKE 'abc\\\\'` GROUP BY 'abc\\' LIKE 'abc\\\\';
SELECT 'abc\\\\' LIKE 'abc\\\\' AS `'abc\\\\' LIKE 'abc\\\\'`;
SELECT DISTINCT 'abc\\' LIKE 'abc\\\\' AS `'abc\\' LIKE 'abc\\\\'`;
SELECT 'abc\\' LIKE 'abc\\\\' AS `'abc\\' LIKE 'abc\\\\'`;
SELECT CAST(('abc\\' LIKE 'abc\\\\') AS JSON)->'$' AS `CAST(('abc\\' LIKE 'abc\\\\') AS JSON)->'$'`;
SELECT NULL LIKE 'abc\\\\' AS `NULL LIKE 'abc\\\\'`;
SELECT 'abc\\' LIKE 'abc\\' AS `'abc\\' LIKE 'abc\\'`;
SELECT 'abc\\' LIKE 'abc\\' AS `'abc\\' LIKE 'abc\\'`;
SELECT 'abc\\' LIKE 'abc\\\\' AS `'abc\\' LIKE 'abc\\\\'` LIMIT 1;
SELECT 'abc\\\\' LIKE 'abc\\\\' AS `'abc\\\\' LIKE 'abc\\\\'`;
SELECT 'abc\\\\' LIKE 'abc\\\\' AS `'abc\\\\' LIKE 'abc\\\\'`;
SELECT '' LIKE 'abc\\\\' AS `'' LIKE 'abc\\\\'`;
SELECT 'abc\\\\' LIKE 'abc\\\\' AS `'abc\\\\' LIKE 'abc\\\\'`;
SELECT 'abc\\' LIKE 'abc\\\\' AS `'abc\\' LIKE 'abc\\\\'` GROUP BY 'abc\\' LIKE 'abc\\\\';
SELECT 'abc\\' LIKE 'abc\\\\' AS `'abc\\' LIKE 'abc\\\\'`;
SELECT 'abc\\' LIKE 'abc\\\\' AS `'abc\\' LIKE 'abc\\\\'` ORDER BY 'abc\\' LIKE 'abc\\\\' DESC;
SELECT (repeat('x', 65536)) LIKE 'abc\\\\' AS `(repeat('x', 65536)) LIKE 'abc\\\\'`;
SELECT 'abc\\' LIKE 'abc\\\\' AS `'abc\\' LIKE 'abc\\\\'` GROUP BY 'abc\\' LIKE 'abc\\\\';
SELECT 'abcdef' LIKE 'abc%' AS `'abcdef' LIKE 'abc%'` GROUP BY 'abcdef' LIKE 'abc%';
SELECT 'abcdef' LIKE 'abc%' AS `'abcdef' LIKE 'abc%'` ORDER BY 'abcdef' LIKE 'abc%' ASC NULLS LAST;
SELECT 'abcdef' LIKE 'abc%' AS `'abcdef' LIKE 'abc%'`;
SELECT 'abcdef' LIKE 'abc%' AS `'abcdef' LIKE 'abc%'` ORDER BY 'abcdef' LIKE 'abc%' ASC;
SELECT '%' LIKE 'abc%' AS `'%' LIKE 'abc%'`;
SELECT 'abcdef' LIKE 'a\\b' AS `'abcdef' LIKE 'a\\b'`;
SELECT '' LIKE 'abc%' AS `'' LIKE 'abc%'`;
SELECT 'abcdef' LIKE 'abcdef' AS `'abcdef' LIKE 'abcdef'`;
SELECT 'abcdef' LIKE 'abc%' AS `'abcdef' LIKE 'abc%'`;
SELECT 'abcdef' LIKE 'abcdef' AS `'abcdef' LIKE 'abcdef'`;
SELECT 'aXb' LIKE 'abc%' AS `'aXb' LIKE 'abc%'`;
SELECT 'abcdef' LIKE 'abcdef' AS `'abcdef' LIKE 'abcdef'`;
SELECT 'abcdef' LIKE 'abc%' AS `'abcdef' LIKE 'abc%'` GROUP BY 'abcdef' LIKE 'abc%';
SELECT '1970-01-01' LIKE 'abc%' AS `'1970-01-01' LIKE 'abc%'`;
SELECT '0' LIKE 'abc%' AS `'0' LIKE 'abc%'`;
SELECT (repeat('x', 65536)) LIKE 'abc%' AS `(repeat('x', 65536)) LIKE 'abc%'`;
SELECT '9999-12-31 23:59:59' LIKE 'abc%' AS `'9999-12-31 23:59:59' LIKE 'abc%'`;
SELECT 'abcdef' LIKE 'abc%' AS `'abcdef' LIKE 'abc%'`;
SELECT 'abc%' LIKE 'abc%' AS `'abc%' LIKE 'abc%'`;
SELECT 'abcdef' LIKE 'abcdef' AS `'abcdef' LIKE 'abcdef'`;
SELECT 'abc%' LIKE 'abc%' AS `'abc%' LIKE 'abc%'`;
SELECT 'abcdef' LIKE 'abc%' AS `'abcdef' LIKE 'abc%'` GROUP BY 'abcdef' LIKE 'abc%';
SELECT 'abcdef' LIKE 'abc\\%%' AS `'abcdef' LIKE 'abc\\%%'`;
SELECT (repeat('x', 65536)) LIKE 'abc%' AS `(repeat('x', 65536)) LIKE 'abc%'`;
SELECT 'abcdef' LIKE '\\' AS `'abcdef' LIKE '\\'`;
SELECT 'abc%' LIKE 'abc%' AS `'abc%' LIKE 'abc%'`;
SELECT 'xyzabc' LIKE '%abc' AS `'xyzabc' LIKE '%abc'`;
SELECT 'xyzabc' LIKE '%abc' AS `'xyzabc' LIKE '%abc'`;
SELECT 'xyzabc' LIKE '0' AS `'xyzabc' LIKE '0'`;
SELECT '%abc' LIKE '%abc' AS `'%abc' LIKE '%abc'`;
SELECT 'xyzabc' LIKE '%abc' AS `'xyzabc' LIKE '%abc'`;
SELECT '%abc' LIKE '%abc' AS `'%abc' LIKE '%abc'`;
SELECT 'xyzabc' LIKE '\\' AS `'xyzabc' LIKE '\\'`;
SELECT 'xyzabc' LIKE 'xyzabc' AS `'xyzabc' LIKE 'xyzabc'`;
SELECT 'xyzabc' LIKE 'aXb' AS `'xyzabc' LIKE 'aXb'`;
SELECT 'xyzabc' LIKE '%abc' AS `'xyzabc' LIKE '%abc'` ORDER BY 'xyzabc' LIKE '%abc' DESC;
SELECT '%abc' LIKE '%abc' AS `'%abc' LIKE '%abc'`;
SELECT 'xyzabc' LIKE '%abc' AS `'xyzabc' LIKE '%abc'`;
SELECT 'xyzabc' LIKE '' AS `'xyzabc' LIKE ''`;
SELECT DISTINCT 'xyzabc' LIKE '%abc' AS `'xyzabc' LIKE '%abc'`;
SELECT 'xyzabc' LIKE 'xyzabc' AS `'xyzabc' LIKE 'xyzabc'`;
SELECT NULL LIKE '%abc' AS `NULL LIKE '%abc'`;
SELECT 'xyzabc' LIKE '%abc' AS `'xyzabc' LIKE '%abc'` GROUP BY 'xyzabc' LIKE '%abc';
SELECT 'xyzabc' LIKE 'xyzabc' AS `'xyzabc' LIKE 'xyzabc'`;
SELECT DISTINCT 'xyzabc' LIKE '%abc' AS `'xyzabc' LIKE '%abc'`;
SELECT '%abc' LIKE '%abc' AS `'%abc' LIKE '%abc'`;
SELECT 'xyzabc' LIKE 'xyzabc' AS `'xyzabc' LIKE 'xyzabc'`;
SELECT DISTINCT 'xyzabc' LIKE '%abc' AS `'xyzabc' LIKE '%abc'`;
SELECT 'xyzabc' LIKE 'xyzabc' AS `'xyzabc' LIKE 'xyzabc'`;
SELECT '0' LIKE '%abc' AS `'0' LIKE '%abc'`;
SELECT 'xyzabc' LIKE 'xyzabc' AS `'xyzabc' LIKE 'xyzabc'`;
SELECT '%abc' LIKE '%abc' AS `'%abc' LIKE '%abc'`;
SELECT 'xyzabc' LIKE '%abc' AS `'xyzabc' LIKE '%abc'`;
SELECT 'xyzabc' LIKE '%abc' AS `'xyzabc' LIKE '%abc'`;
SELECT '9999-12-31 23:59:59' LIKE '%abc%' AS `'9999-12-31 23:59:59' LIKE '%abc%'`;
SELECT CAST(('xyzabcdef' LIKE '%abc%') AS CHAR(1)) AS `CAST(('xyzabcdef' LIKE '%abc%') AS CHAR(1))`;
SELECT 'xyzabcdef' LIKE '%abc%' AS `'xyzabcdef' LIKE '%abc%'`;
SELECT 'xyzabcdef' LIKE 'abcdef' AS `'xyzabcdef' LIKE 'abcdef'`;
SELECT '1970-01-01' LIKE '%abc%' AS `'1970-01-01' LIKE '%abc%'`;
SELECT DISTINCT 'xyzabcdef' LIKE '%abc%' AS `'xyzabcdef' LIKE '%abc%'`;
SELECT 'xyzabcdef' LIKE '%abc%' AS `'xyzabcdef' LIKE '%abc%'`;
SELECT CAST(('xyzabcdef' LIKE '%abc%') AS ARRAY<INT>) AS `CAST(('xyzabcdef' LIKE '%abc%') AS ARRAY<INT>)`;
SELECT 'xyzabcdef' LIKE '%abc%' AS `'xyzabcdef' LIKE '%abc%'`;
SELECT (get_json_string(CAST('xyzabcdef' AS JSON), '$.a')) LIKE '%abc%' AS `(get_json_string(CAST('xyzabcdef' AS JSON), '$.a')) LIKE '%abc%'`;
SELECT 'xyzabcdef' LIKE '%abc%' AS `'xyzabcdef' LIKE '%abc%'`;
SELECT 'xyzabcdef' LIKE 'xyzabcdef' AS `'xyzabcdef' LIKE 'xyzabcdef'`;
SELECT '%abc%' LIKE '%abc%' AS `'%abc%' LIKE '%abc%'`;
SELECT 'xyzabcdef' LIKE '%abc%' AS `'xyzabcdef' LIKE '%abc%'`;
SELECT 'xyzabcdef' LIKE '' AS `'xyzabcdef' LIKE ''`;
SELECT 'xyzabcdef' LIKE '1970-01-01' AS `'xyzabcdef' LIKE '1970-01-01'`;
SELECT json_query(CAST(('xyzabcdef' LIKE '%abc%') AS JSON), '$.a') AS `json_query(CAST(('xyzabcdef' LIKE '%abc%') AS JSON), '$.a')`;
SELECT (repeat('x', 65536)) LIKE '%abc%' AS `(repeat('x', 65536)) LIKE '%abc%'`;
SELECT 'xyzabcdef' LIKE '%abc%' AS `'xyzabcdef' LIKE '%abc%'` WHERE 'a\\b' LIKE 'a\\b';
SELECT 'xyzabcdef' LIKE '%abc%' AS `'xyzabcdef' LIKE '%abc%'`;
SELECT '%abc%' LIKE '%abc%' AS `'%abc%' LIKE '%abc%'`;
SELECT 'xyzabcdef' LIKE '%abc%' AS `'xyzabcdef' LIKE '%abc%'`;
SELECT '%abc%' LIKE '%abc%' AS `'%abc%' LIKE '%abc%'`;