CREATE TABLE `mt1` (
 k1 INT,
 k2 string,
 v1 INT,
 v2 INT
) ENGINE=OLAP
PARTITION BY RANGE(`k1`)
(
  PARTITION `p1` VALUES LESS THAN ('3'),
  PARTITION `p2` VALUES LESS THAN ('6'),
  PARTITION `p3` VALUES LESS THAN ('9')
)
DISTRIBUTED BY HASH(`k1`) BUCKETS 3
PROPERTIES (
"replication_num" = "1"
);
INSERT INTO mt1 values (1,'a',1,1), (2,'aa',1,2),  (3,'a',1,3), (4,'aa',1,4), (5,'aa',1,5), (6,'aa',1,6);
CREATE MATERIALIZED VIEW mv0 
PARTITION BY (k1) 
DISTRIBUTED BY HASH(k1) 
REFRESH DEFERRED MANUAL 
AS SELECT k1,k2, v1,v2 from mt1 where v2 != 2;
CREATE MATERIALIZED VIEW mv0 
PARTITION BY (k1) 
DISTRIBUTED BY HASH(k1) 
REFRESH DEFERRED MANUAL 
AS SELECT k1, k2, sum(v1), sum(v2) 
from mt1 where k2 != 'a'
group by k1, k2;
drop table mt1;