CREATE TABLE t_sync (id BIGINT NOT NULL, v ARRAY<FLOAT> NOT NULL) DUPLICATE KEY(id) DISTRIBUTED BY HASH(id) BUCKETS 1 PROPERTIES("replication_num" = "1");
insert into t_sync values (1, [1,0,0,0]), (2, [0,1,0,0]), (3, [0,0,1,0]), (4, [0,0,0,1]);
ALTER TABLE t_sync ADD INDEX idx_v (v) USING VECTOR ("index_type" = "hnsw", "metric_type" = "l2_distance", "is_vector_normed" = "false", "M" = "16", "dim" = "4");
insert into t_sync values (5, [0.9,0.1,0,0]);
CREATE TABLE t_async (id BIGINT NOT NULL, v ARRAY<FLOAT> NOT NULL) DUPLICATE KEY(id) DISTRIBUTED BY HASH(id) BUCKETS 1 PROPERTIES("replication_num" = "1");
insert into t_async values (1, [1,0,0,0]), (2, [0,1,0,0]), (3, [0,0,1,0]);
ALTER TABLE t_async ADD INDEX idx_v (v) USING VECTOR ("index_type" = "hnsw", "metric_type" = "l2_distance", "is_vector_normed" = "false", "M" = "16", "dim" = "4", "index_build_mode" = "async");
CREATE TABLE t_rb (id BIGINT NOT NULL, v ARRAY<FLOAT> NOT NULL) DUPLICATE KEY(id) DISTRIBUTED BY HASH(id) BUCKETS 1 PROPERTIES("replication_num" = "1");
insert into t_rb values (1, [1,0,0,0]), (2, [0,1,0,0]);
ALTER TABLE t_rb ADD INDEX idx_v (v) USING VECTOR ("index_type" = "hnsw", "metric_type" = "l2_distance", "is_vector_normed" = "false", "M" = "16", "dim" = "4");
ALTER TABLE t_rb DROP INDEX idx_v;
ALTER TABLE t_rb ADD INDEX idx_v (v) USING VECTOR ("index_type" = "hnsw", "metric_type" = "l2_distance", "is_vector_normed" = "false", "M" = "16", "dim" = "4");