SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(srfuzz_mut_779.event1.event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1` HAVING (count(*)) < 10;
SELECT count(CAST((CAST((CAST(`srfuzz_mut_779`.`event1`.`event_id` AS INT)) AS JSON)) AS VARCHAR)) AS `count(CAST((CAST((CAST(event_id AS INT)) AS JSON)) AS VARCHAR))` FROM `srfuzz_mut_779`.`event1`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_779`.`event1`.`event_id`, `srfuzz_mut_779`.`event1`.`event_type`, `srfuzz_mut_779`.`event1`.`event_time` FROM `srfuzz_mut_779`.`event1`) SELECT count(`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_n1` AS event1;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1` WHERE `srfuzz_mut_779`.`event1`.`event_id`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1` ORDER BY count(`srfuzz_mut_779`.`event1`.`event_id`) DESC;
SELECT count(`event1`.`event_id`) AS `count(event_id)` FROM (SELECT `srfuzz_mut_779`.`event1`.`event_id`, `srfuzz_mut_779`.`event1`.`event_type`, `srfuzz_mut_779`.`event1`.`event_time` FROM `srfuzz_mut_779`.`event1` UNION ALL SELECT `srfuzz_mut_779`.`event1`.`event_id`, `srfuzz_mut_779`.`event1`.`event_type`, `srfuzz_mut_779`.`event1`.`event_time` FROM `srfuzz_mut_779`.`event1`) `event1`;
SELECT count(`event1`.`event_id`) AS `count(event_id)` FROM (SELECT `srfuzz_mut_779`.`event1`.`event_id`, `srfuzz_mut_779`.`event1`.`event_type`, `srfuzz_mut_779`.`event1`.`event_time` FROM `srfuzz_mut_779`.`event1`) `event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(srfuzz_mut_779.event1.event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(srfuzz_mut_779.event1.event_id)` FROM `srfuzz_mut_779`.`event1`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_779`.`event1`.`event_id`, `srfuzz_mut_779`.`event1`.`event_type`, `srfuzz_mut_779`.`event1`.`event_time` FROM `srfuzz_mut_779`.`event1`) SELECT count(`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_n1` AS event1;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1` LIMIT 1, 1;
SELECT count(`event1`.`event_id`) AS `count(event_id)` FROM (SELECT `srfuzz_mut_779`.`event1`.`event_id`, `srfuzz_mut_779`.`event1`.`event_type`, `srfuzz_mut_779`.`event1`.`event_time` FROM `srfuzz_mut_779`.`event1` UNION ALL SELECT `srfuzz_mut_779`.`event1`.`event_id`, `srfuzz_mut_779`.`event1`.`event_type`, `srfuzz_mut_779`.`event1`.`event_time` FROM `srfuzz_mut_779`.`event1`) `event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(srfuzz_mut_779.event1.event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`event1`.`event_id`) AS `count(event_id)` FROM (SELECT `srfuzz_mut_779`.`event1`.`event_id`, `srfuzz_mut_779`.`event1`.`event_type`, `srfuzz_mut_779`.`event1`.`event_time` FROM `srfuzz_mut_779`.`event1`) `event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(srfuzz_mut_779.event1.event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT CAST((count(`srfuzz_mut_779`.`event1`.`event_id`)) AS JSON)->'$.a' AS `CAST((count(event_id)) AS JSON)->'$.a'` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(srfuzz_mut_779.event1.event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(srfuzz_mut_779.event1.event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(srfuzz_mut_779.event1.event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`event1`.`event_id`) AS `count(event_id)` FROM (SELECT `srfuzz_mut_779`.`event1`.`event_id`, `srfuzz_mut_779`.`event1`.`event_type`, `srfuzz_mut_779`.`event1`.`event_time` FROM `srfuzz_mut_779`.`event1` UNION ALL SELECT `srfuzz_mut_779`.`event1`.`event_id`, `srfuzz_mut_779`.`event1`.`event_type`, `srfuzz_mut_779`.`event1`.`event_time` FROM `srfuzz_mut_779`.`event1`) `event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1` GROUP BY `srfuzz_mut_779`.`event1`.`event_id`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1` HAVING (count(*)) >= 2;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(srfuzz_mut_779.event1.event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`event1`.`event_id`) AS `count(event_id)` FROM (SELECT `srfuzz_mut_779`.`event1`.`event_id`, `srfuzz_mut_779`.`event1`.`event_type`, `srfuzz_mut_779`.`event1`.`event_time` FROM `srfuzz_mut_779`.`event1` UNION ALL SELECT `srfuzz_mut_779`.`event1`.`event_id`, `srfuzz_mut_779`.`event1`.`event_type`, `srfuzz_mut_779`.`event1`.`event_time` FROM `srfuzz_mut_779`.`event1`) `event1`;
SELECT count(`event1`.`event_id`) AS `count(event_id)` FROM (SELECT `srfuzz_mut_779`.`event1`.`event_id`, `srfuzz_mut_779`.`event1`.`event_type`, `srfuzz_mut_779`.`event1`.`event_time` FROM `srfuzz_mut_779`.`event1` UNION SELECT `srfuzz_mut_779`.`event1`.`event_id`, `srfuzz_mut_779`.`event1`.`event_type`, `srfuzz_mut_779`.`event1`.`event_time` FROM `srfuzz_mut_779`.`event1`) `event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(srfuzz_mut_779.event1.event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1` WHERE `srfuzz_mut_779`.`event1`.`event_id`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1` GROUP BY `srfuzz_mut_779`.`event1`.`event_id`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1` HAVING (count(*)) > 1;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(srfuzz_mut_779.event1.event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(srfuzz_mut_779.event1.event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1` WHERE `srfuzz_mut_779`.`event1`.`event_id`;
SELECT count(`event1`.`event_id`) AS `count(event_id)` FROM (SELECT `srfuzz_mut_779`.`event1`.`event_id`, `srfuzz_mut_779`.`event1`.`event_type`, `srfuzz_mut_779`.`event1`.`event_time` FROM `srfuzz_mut_779`.`event1`) `event1`;
SELECT count(`event1`.`event_id`) AS `count(event_id)` FROM (SELECT `srfuzz_mut_779`.`event1`.`event_id`, `srfuzz_mut_779`.`event1`.`event_type`, `srfuzz_mut_779`.`event1`.`event_time` FROM `srfuzz_mut_779`.`event1` EXCEPT SELECT `srfuzz_mut_779`.`event1`.`event_id`, `srfuzz_mut_779`.`event1`.`event_type`, `srfuzz_mut_779`.`event1`.`event_time` FROM `srfuzz_mut_779`.`event1`) `event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1` GROUP BY `srfuzz_mut_779`.`event1`.`event_id`;
SELECT count(CAST((CAST(`srfuzz_mut_779`.`event1`.`event_id` AS VARCHAR(1))) AS FLOAT)) AS `count(CAST((CAST(event_id AS VARCHAR(1))) AS FLOAT))` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1`;
SELECT count(`srfuzz_mut_779`.`event1`.`event_id`) AS `count(event_id)` FROM `srfuzz_mut_779`.`event1`;