SELECT count(*) AS `n`, sum(array_length(array_agg_distinct_state_merge(`srfuzz_mut_67`.`st`.`v`))) AS `total_elems` FROM `srfuzz_mut_67`.`st`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_67`.`st`.`k`, `srfuzz_mut_67`.`st`.`v` FROM `srfuzz_mut_67`.`st`) SELECT count(*) AS `n`, sum(array_length(array_agg_distinct_state_merge(`st`.`v`))) AS `total_elems` FROM `srfuzz_n1` AS st;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_67`.`st`.`k`, `srfuzz_mut_67`.`st`.`v` FROM `srfuzz_mut_67`.`st`) SELECT count(*) AS `n`, sum(array_length(array_agg_distinct_state_merge(`st`.`v`))) AS `total_elems` FROM `srfuzz_n1` AS st;
SELECT count(*) AS `n`, sum(array_length(array_agg_distinct_state_merge(`srfuzz_mut_67`.`st`.`v`))) AS `total_elems` FROM `srfuzz_mut_67`.`st`;
SELECT count(*) AS `n`, sum(array_length(array_agg_distinct_state_merge(`srfuzz_mut_67`.`st`.`v`))) AS `total_elems` FROM `srfuzz_mut_67`.`st` GROUP BY `srfuzz_mut_67`.`st`.`v`;
SELECT count(*) AS `n`, sum(array_length(array_agg_distinct_state_merge(`srfuzz_mut_67`.`st`.`v`))) AS `total_elems` FROM `srfuzz_mut_67`.`st` ORDER BY sum(array_length(array_agg_distinct_state_merge(`srfuzz_mut_67`.`st`.`v`))) DESC;
SELECT count(*) AS `n`, sum(array_length(array_agg_distinct_state_merge(`st`.`v`))) AS `total_elems` FROM (SELECT `srfuzz_mut_67`.`st`.`k`, `srfuzz_mut_67`.`st`.`v` FROM `srfuzz_mut_67`.`st`) `st`;
SELECT count(*) AS `n`, sum(array_length(array_agg_distinct_state_merge(`srfuzz_mut_67`.`st`.`v`))) AS `total_elems` FROM `srfuzz_mut_67`.`st` ORDER BY count(*) DESC;
SELECT count(*) AS `n`, sum(array_length(array_agg_distinct_state_merge(`srfuzz_mut_67`.`st`.`v`))) AS `total_elems` FROM `srfuzz_mut_67`.`st`;
SELECT count(*) AS `n`, sum(array_length(array_agg_distinct_state_merge(`srfuzz_mut_67`.`st`.`v`))) AS `total_elems` FROM `srfuzz_mut_67`.`st` GROUP BY `srfuzz_mut_67`.`st`.`v`;
SELECT count(*) AS `n`, sum(array_length(array_agg_distinct_state_merge(`srfuzz_mut_67`.`st`.`v`))) AS `total_elems` FROM `srfuzz_mut_67`.`st`;
SELECT count(*) AS `n`, sum(array_length(array_agg_distinct_state_merge(`srfuzz_mut_67`.`st`.`v`))) AS `total_elems` FROM `srfuzz_mut_67`.`st` HAVING (count(*)) > 0;
SELECT count(*) AS `n`, sum(array_length(array_agg_distinct_state_merge(`srfuzz_mut_67`.`st`.`v`))) AS `total_elems` FROM `srfuzz_mut_67`.`st` HAVING (count(*)) > 0;
SELECT json_length(CAST((count(*)) AS JSON)) AS `n`, sum(array_length(array_agg_distinct_state_merge(`srfuzz_mut_67`.`st`.`v`))) AS `total_elems` FROM `srfuzz_mut_67`.`st`;