SELECT `srfuzz_mut_128`.`test_array_top_n`.`id`, array_top_n(`srfuzz_mut_128`.`test_array_top_n`.`array_int`, 3) AS `result` FROM `srfuzz_mut_128`.`test_array_top_n` ORDER BY `srfuzz_mut_128`.`test_array_top_n`.`id` ASC;
SELECT `srfuzz_mut_128`.`test_array_top_n`.`id`, array_top_n(`srfuzz_mut_128`.`test_array_top_n`.`array_bigint`, 3) AS `result` FROM `srfuzz_mut_128`.`test_array_top_n` ORDER BY `srfuzz_mut_128`.`test_array_top_n`.`id` ASC;
SELECT `srfuzz_mut_128`.`test_array_top_n`.`id`, array_top_n(`srfuzz_mut_128`.`test_array_top_n`.`array_float`, 3) AS `result` FROM `srfuzz_mut_128`.`test_array_top_n` ORDER BY `srfuzz_mut_128`.`test_array_top_n`.`id` ASC;
SELECT `srfuzz_mut_128`.`test_array_top_n`.`id`, array_top_n(`srfuzz_mut_128`.`test_array_top_n`.`array_double`, 3) AS `result` FROM `srfuzz_mut_128`.`test_array_top_n` ORDER BY `srfuzz_mut_128`.`test_array_top_n`.`id` ASC;
SELECT `srfuzz_mut_128`.`test_array_top_n`.`id`, array_top_n(`srfuzz_mut_128`.`test_array_top_n`.`array_decimalv2`, 3) AS `result` FROM `srfuzz_mut_128`.`test_array_top_n` ORDER BY `srfuzz_mut_128`.`test_array_top_n`.`id` ASC;
SELECT `srfuzz_mut_128`.`test_array_top_n`.`id`, array_top_n(`srfuzz_mut_128`.`test_array_top_n`.`array_boolean`, 3) AS `result` FROM `srfuzz_mut_128`.`test_array_top_n` ORDER BY `srfuzz_mut_128`.`test_array_top_n`.`id` ASC;
SELECT `srfuzz_mut_128`.`test_array_top_n`.`id`, array_top_n(`srfuzz_mut_128`.`test_array_top_n`.`array_date`, 3) AS `result` FROM `srfuzz_mut_128`.`test_array_top_n` ORDER BY `srfuzz_mut_128`.`test_array_top_n`.`id` ASC;
SELECT `srfuzz_mut_128`.`test_array_top_n`.`id`, array_top_n(`srfuzz_mut_128`.`test_array_top_n`.`array_datetime`, 3) AS `result` FROM `srfuzz_mut_128`.`test_array_top_n` ORDER BY `srfuzz_mut_128`.`test_array_top_n`.`id` ASC;
SELECT `srfuzz_mut_128`.`test_array_top_n`.`id`, array_top_n(`srfuzz_mut_128`.`test_array_top_n`.`array_varchar`, 3) AS `result` FROM `srfuzz_mut_128`.`test_array_top_n` ORDER BY `srfuzz_mut_128`.`test_array_top_n`.`id` ASC;
SELECT `srfuzz_mut_128`.`test_array_top_n`.`id`, array_top_n(`srfuzz_mut_128`.`test_array_top_n`.`array_int`, 0) AS `result` FROM `srfuzz_mut_128`.`test_array_top_n` WHERE `srfuzz_mut_128`.`test_array_top_n`.`id` = 1 ORDER BY `srfuzz_mut_128`.`test_array_top_n`.`id` ASC;
SELECT `srfuzz_mut_128`.`test_array_top_n`.`id`, array_top_n(`srfuzz_mut_128`.`test_array_top_n`.`array_int`, -1) AS `result` FROM `srfuzz_mut_128`.`test_array_top_n` WHERE `srfuzz_mut_128`.`test_array_top_n`.`id` = 1 ORDER BY `srfuzz_mut_128`.`test_array_top_n`.`id` ASC;
SELECT `srfuzz_mut_128`.`test_array_top_n`.`id`, array_top_n(`srfuzz_mut_128`.`test_array_top_n`.`array_int`, 10) AS `result` FROM `srfuzz_mut_128`.`test_array_top_n` WHERE `srfuzz_mut_128`.`test_array_top_n`.`id` = 1 ORDER BY `srfuzz_mut_128`.`test_array_top_n`.`id` ASC;
SELECT `srfuzz_mut_128`.`test_array_top_n`.`id`, array_top_n(`srfuzz_mut_128`.`test_array_top_n`.`array_int`, 1) AS `result` FROM `srfuzz_mut_128`.`test_array_top_n` WHERE `srfuzz_mut_128`.`test_array_top_n`.`id` = 1 ORDER BY `srfuzz_mut_128`.`test_array_top_n`.`id` ASC;
SELECT `srfuzz_mut_128`.`test_array_top_n`.`id`, array_top_n(`srfuzz_mut_128`.`test_array_top_n`.`array_int`, 1) AS `result` FROM `srfuzz_mut_128`.`test_array_top_n` WHERE `srfuzz_mut_128`.`test_array_top_n`.`id` = 4 ORDER BY `srfuzz_mut_128`.`test_array_top_n`.`id` ASC;
SELECT `srfuzz_mut_128`.`test_array_top_n`.`id`, array_top_n(`srfuzz_mut_128`.`test_array_top_n`.`array_int`, 3) AS `result` FROM `srfuzz_mut_128`.`test_array_top_n` WHERE `srfuzz_mut_128`.`test_array_top_n`.`id` = 6 ORDER BY `srfuzz_mut_128`.`test_array_top_n`.`id` ASC;
SELECT array_top_n(ARRAY<TINYINT>[1, 100, 2, 5, 3], 3) AS `result`;
SELECT array_top_n(ARRAY<TINYINT>[1, 100, 2, 5, 3], 3) AS `result`;
SELECT array_top_n(ARRAY<VARCHAR>['hello', 'world', 'aaa', 'zzz', 'mmm'], 3) AS `result`;
SELECT array_top_n(ARRAY<TINYINT>[1, NULL, 100, NULL, 5], 3) AS `result`;
SELECT array_top_n([], 3) AS `result`;
SELECT array_top_n(NULL, 3) AS `result`;
SELECT array_top_n(ARRAY<VARCHAR>['hello', 'world', 'aaa', 'zzz', 'mmm'], 3) AS `result`;
SELECT array_top_n(ARRAY<TINYINT>[1, NULL, 100, NULL, 5], 3) AS `result`;
SELECT array_top_n(array_top_n(ARRAY<TINYINT>[1, NULL, 100, NULL, 5], 3), 3) AS `result`;
SELECT array_top_n(ARRAY<TINYINT>[1, NULL, 100, NULL, 5], 3) AS `result`;
SELECT array_top_n(NULL, 1.0E308) AS `result`;
SELECT array_top_n(NULL, 3) AS `result`;
SELECT array_top_n(NULL, 3) AS `result` ORDER BY array_top_n(NULL, 3) DESC;
SELECT array_top_n(array_top_n(NULL, 3), 3) AS `result`;
SELECT array_top_n(NULL, FALSE) AS `result`;
SELECT DISTINCT array_top_n(NULL, 3) AS `result`;
SELECT array_top_n(NULL, NULL) AS `result`;
SELECT array_top_n(NULL, 3) AS `result`;
SELECT array_top_n(array_top_n(NULL, 3), 3) AS `result`;
SELECT array_top_n(NULL, 0.0) AS `result`;
SELECT array_top_n(NULL, 3) AS `result` GROUP BY array_top_n(NULL, 3);
SELECT array_top_n(NULL, '') AS `result`;
SELECT array_top_n(NULL, get_json_string(CAST(3 AS JSON), '$.a')) AS `result`;
SELECT array_top_n(array_top_n(NULL, 3), 3) AS `result`;
SELECT array_top_n(NULL, 3) AS `result`;
SELECT array_top_n(NULL, '0') AS `result`;
SELECT array_top_n(NULL, NULL) AS `result`;
SELECT array_top_n(NULL, 1) AS `result`;
SELECT array_top_n(NULL, NULL) AS `result`;
SELECT array_top_n(NULL, 3) AS `result`;