SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` ORDER BY `srfuzz_mut_778`.`mv1`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` ORDER BY `srfuzz_mut_778`.`mv1`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` ORDER BY `srfuzz_mut_778`.`mv1`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`;
SELECT `mv1`.`event_day`, `mv1`.`sum_pv` FROM (SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` INTERSECT SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`) `mv1` ORDER BY `mv1`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` ORDER BY `srfuzz_mut_778`.`mv1`.`event_day` ASC  LIMIT 100;
SELECT DISTINCT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` ORDER BY `srfuzz_mut_778`.`mv1`.`event_day` ASC;
SELECT `mv1`.`event_day`, `mv1`.`sum_pv` FROM (SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`) `mv1` ORDER BY `mv1`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` ORDER BY `srfuzz_mut_778`.`mv1`.`event_day` ASC  LIMIT 2;
SELECT `mv1`.`event_day`, `mv1`.`sum_pv` FROM (SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`) `mv1` ORDER BY `mv1`.`event_day` ASC;
SELECT `mv1`.`event_day`, `mv1`.`sum_pv` FROM (SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` UNION ALL SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`) `mv1` ORDER BY `mv1`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` ORDER BY `srfuzz_mut_778`.`mv1`.`event_day` ASC  LIMIT 7, 100;
SELECT `mv1`.`event_day`, `mv1`.`sum_pv` FROM (SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` UNION ALL SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`) `mv1` ORDER BY `mv1`.`event_day` ASC;
SELECT `mv1`.`event_day`, `mv1`.`sum_pv` FROM (SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` UNION ALL SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`) `mv1` ORDER BY `mv1`.`event_day` ASC;
SELECT `mv1`.`event_day`, `mv1`.`sum_pv`, `srfuzz_n1`.`e` FROM (SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`) `mv1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  ORDER BY `mv1`.`event_day` ASC;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`) SELECT `mv1`.`event_day`, `mv1`.`sum_pv` FROM `srfuzz_n1` AS mv1 ORDER BY `mv1`.`event_day` ASC;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`) SELECT `mv1`.`event_day`, `mv1`.`sum_pv` FROM `srfuzz_n1` AS mv1 ORDER BY `mv1`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`;
SELECT DISTINCT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC;
SELECT `mv2`.`event_day`, `mv2`.`count_pv` FROM (SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` INTERSECT SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`) `mv2` ORDER BY `mv2`.`event_day` ASC;
SELECT `mv2`.`event_day`, `mv2`.`count_pv` FROM (SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` UNION ALL SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`) `mv2` ORDER BY `mv2`.`event_day` ASC;
SELECT `mv2`.`event_day`, `mv2`.`count_pv` FROM (SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` UNION ALL SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`) `mv2` ORDER BY `mv2`.`event_day` ASC;
SELECT DISTINCT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`;
SELECT `mv2`.`event_day`, `mv2`.`count_pv` FROM (SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` UNION SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`) `mv2` ORDER BY `mv2`.`event_day` ASC;
SELECT `mv2`.`event_day`, `mv2`.`count_pv` FROM (SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` INTERSECT SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`) `mv2` ORDER BY `mv2`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` WHERE sleep(3) ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC;
SELECT `mv2`.`event_day`, `mv2`.`count_pv` FROM (SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` EXCEPT SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`) `mv2` ORDER BY `mv2`.`event_day` ASC;
SELECT `mv2`.`event_day`, `mv2`.`count_pv` FROM (SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` INTERSECT SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`) `mv2` ORDER BY `mv2`.`event_day` ASC;
SELECT `mv1`.`event_day`, `mv1`.`sum_pv`, `srfuzz_n1`.`e` FROM (SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`) `mv1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  ORDER BY `mv1`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`;
SELECT `mv1`.`event_day`, `mv1`.`sum_pv` FROM (SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` EXCEPT SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`) `mv1` ORDER BY `mv1`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` WHERE sleep(3) ORDER BY `srfuzz_mut_778`.`mv1`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`) SELECT `mv1`.`event_day`, `mv1`.`sum_pv` FROM `srfuzz_n1` AS mv1 ORDER BY `mv1`.`event_day` ASC;
SELECT `mv1`.`event_day`, `mv1`.`sum_pv` FROM (SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`) `mv1` ORDER BY `mv1`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`;
SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` ORDER BY `srfuzz_mut_778`.`mv1`.`event_day` ASC  LIMIT 0;
SELECT `mv1`.`event_day`, `mv1`.`sum_pv`, `srfuzz_n1`.`e` FROM (SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`) `mv1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  ORDER BY `mv1`.`event_day` ASC;
SELECT `mv1`.`event_day`, `mv1`.`sum_pv` FROM (SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`) `mv1` ORDER BY `mv1`.`event_day` ASC;
SELECT DISTINCT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` ORDER BY `srfuzz_mut_778`.`mv1`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` ORDER BY `srfuzz_mut_778`.`mv1`.`event_day` ASC  LIMIT 2;
SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`;
SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` WHERE sleep(3) ORDER BY `srfuzz_mut_778`.`mv1`.`event_day` ASC;
SELECT `mv1`.`event_day`, `mv1`.`sum_pv` FROM (SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` UNION ALL SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`) `mv1` ORDER BY `mv1`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`;
SELECT `mv2`.`event_day`, `mv2`.`count_pv` FROM (SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`) `mv2` ORDER BY `mv2`.`event_day` ASC;
SELECT `mv2`.`event_day`, `mv2`.`count_pv` FROM (SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` UNION ALL SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`) `mv2` ORDER BY `mv2`.`event_day` ASC;
SELECT DISTINCT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC;
SELECT `mv2`.`event_day`, `mv2`.`count_pv` FROM (SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` UNION ALL SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`) `mv2` ORDER BY `mv2`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC  LIMIT 2;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC  LIMIT 5;
SELECT `mv2`.`event_day`, `mv2`.`count_pv`, `srfuzz_n1`.`e` FROM (SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`) `mv2` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  ORDER BY `mv2`.`event_day` ASC;
SELECT `mv2`.`event_day`, `mv2`.`count_pv`, `srfuzz_n1`.`e` FROM (SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`) `mv2` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  ORDER BY `mv2`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` WHERE sleep(3) ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC  LIMIT 7, 5;
SELECT `mv2`.`event_day`, `mv2`.`count_pv` FROM (SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` EXCEPT SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`) `mv2` ORDER BY `mv2`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` WHERE sleep(3) ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC;
SELECT `mv2`.`event_day`, `mv2`.`count_pv` FROM (SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` INTERSECT SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`) `mv2` ORDER BY `mv2`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` WHERE sleep(3) ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC;
SELECT DISTINCT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC  LIMIT 0;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`;
SELECT `mv2`.`event_day`, `mv2`.`count_pv` FROM (SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`) `mv2` ORDER BY `mv2`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC  LIMIT 5;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC  LIMIT 7, 1;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`) SELECT `mv1`.`event_day`, `mv1`.`sum_pv` FROM `srfuzz_n1` AS mv1 ORDER BY `mv1`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` ORDER BY `srfuzz_mut_778`.`mv1`.`event_day` ASC  LIMIT 2;
SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` ORDER BY `srfuzz_mut_778`.`mv1`.`event_day` ASC  LIMIT 1;
SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`;
SELECT `mv1`.`event_day`, `mv1`.`sum_pv` FROM (SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` UNION SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`) `mv1` ORDER BY `mv1`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` WHERE sleep(3) ORDER BY `srfuzz_mut_778`.`mv1`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` ORDER BY `srfuzz_mut_778`.`mv1`.`event_day` ASC  LIMIT 100;
SELECT `mv1`.`event_day`, `mv1`.`sum_pv` FROM (SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`) `mv1` ORDER BY `mv1`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` ORDER BY `srfuzz_mut_778`.`mv1`.`event_day` ASC  LIMIT 1;
SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` WHERE sleep(3) ORDER BY `srfuzz_mut_778`.`mv1`.`event_day` ASC;
SELECT `mv1`.`event_day`, `mv1`.`sum_pv` FROM (SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` INTERSECT SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`) `mv1` ORDER BY `mv1`.`event_day` ASC;
SELECT `mv1`.`event_day`, `mv1`.`sum_pv` FROM (SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`) `mv1` ORDER BY `mv1`.`event_day` ASC;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`) SELECT `mv1`.`event_day`, `mv1`.`sum_pv` FROM `srfuzz_n1` AS mv1 ORDER BY `mv1`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`;
SELECT `mv1`.`event_day`, `mv1`.`sum_pv` FROM (SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` INTERSECT SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1`) `mv1` ORDER BY `mv1`.`event_day` ASC;
SELECT DISTINCT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` ORDER BY `srfuzz_mut_778`.`mv1`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv1`.`event_day`, `srfuzz_mut_778`.`mv1`.`sum_pv` FROM `srfuzz_mut_778`.`mv1` WHERE sleep(3) ORDER BY `srfuzz_mut_778`.`mv1`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC  LIMIT 7, 5;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC  LIMIT 5;
SELECT `mv2`.`event_day`, `mv2`.`count_pv` FROM (SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`) `mv2` ORDER BY `mv2`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC  LIMIT 2;
SELECT `mv2`.`event_day`, `mv2`.`count_pv` FROM (SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` INTERSECT SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`) `mv2` ORDER BY `mv2`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`;
SELECT DISTINCT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC  LIMIT 7, 5;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` WHERE sleep(3) ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC;
SELECT `mv2`.`event_day`, `mv2`.`count_pv` FROM (SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` INTERSECT SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`) `mv2` ORDER BY `mv2`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC  LIMIT 1, 5;
SELECT DISTINCT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC;
SELECT `mv2`.`event_day`, `mv2`.`count_pv`, `srfuzz_n1`.`e` FROM (SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`) `mv2` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  ORDER BY `mv2`.`event_day` ASC;
SELECT `mv2`.`event_day`, `mv2`.`count_pv` FROM (SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` EXCEPT SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`) `mv2` ORDER BY `mv2`.`event_day` ASC;
SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` WHERE sleep(3) ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC;
SELECT `mv2`.`event_day`, `mv2`.`count_pv` FROM (SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` UNION SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`) `mv2` ORDER BY `mv2`.`event_day` ASC;
SELECT `mv2`.`event_day`, `mv2`.`count_pv` FROM (SELECT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2`) `mv2` ORDER BY `mv2`.`event_day` ASC;
SELECT DISTINCT `srfuzz_mut_778`.`mv2`.`event_day`, `srfuzz_mut_778`.`mv2`.`count_pv` FROM `srfuzz_mut_778`.`mv2` ORDER BY `srfuzz_mut_778`.`mv2`.`event_day` ASC;
SELECT sleep(3) AS `sleep(3)` ORDER BY sleep(3) ASC;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)` ORDER BY sleep(3) DESC;
SELECT sleep('\\') AS `sleep('\\')`;
SELECT sleep('') AS `sleep('')`;
SELECT sleep(0.0) AS `sleep(0.0)`;
SELECT sleep(CAST(3 AS TIME)) AS `sleep(CAST(3 AS TIME))`;
SELECT sleep(repeat('x', 65536)) AS `sleep(repeat('x', 65536))`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(1) AS `sleep(1)`;
SELECT sleep(CAST(3 AS JSON)->'k') AS `sleep(CAST(3 AS JSON)->'k')`;
SELECT sleep(CAST(3 AS JSON)->'$') AS `sleep(CAST(3 AS JSON)->'$')`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)` GROUP BY sleep(3);
SELECT sleep('') AS `sleep('')`;
SELECT sleep(2147483647) AS `sleep(2147483647)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)` ORDER BY sleep(3) DESC;
SELECT sleep(3) AS `sleep(3)`;
SELECT CAST((sleep(3)) AS JSON)->'$.a' AS `CAST((sleep(3)) AS JSON)->'$.a'`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)` LIMIT 2;
SELECT DISTINCT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)` GROUP BY sleep(3);
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)` ORDER BY sleep(3) ASC;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)` LIMIT 7, 100;
SELECT sleep(TRUE) AS `sleep(TRUE)`;
SELECT DISTINCT sleep(3) AS `sleep(3)`;
SELECT DISTINCT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT DISTINCT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)` LIMIT 5;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(1) AS `sleep(1)`;
SELECT sleep(-9223372036854775808) AS `sleep(-9223372036854775808)`;
SELECT sleep(3) AS `sleep(3)` ORDER BY sleep(3) DESC NULLS FIRST;
SELECT sleep('%') AS `sleep('%')`;
SELECT sleep(json_length(CAST(3 AS JSON))) AS `sleep(json_length(CAST(3 AS JSON)))`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)` GROUP BY sleep(3);
SELECT sleep(CAST((CAST(3 AS VARCHAR(65533))) AS DECIMAL128(38,38))) AS `sleep(CAST((CAST(3 AS VARCHAR(65533))) AS DECIMAL128(38,38)))`;
SELECT sleep('0') AS `sleep('0')`;
SELECT sleep(3) AS `sleep(3)` ORDER BY sleep(3) DESC NULLS FIRST;
SELECT sleep(3) AS `sleep(3)` ORDER BY sleep(3) DESC;
SELECT sleep(3) AS `sleep(3)` ORDER BY sleep(3) ASC;
SELECT DISTINCT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(CAST(3 AS JSON)->'$.a') AS `sleep(CAST(3 AS JSON)->'$.a')`;
SELECT sleep(-1.0E308) AS `sleep(-1.0E308)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep('0') AS `sleep('0')`;
SELECT sleep(3) AS `sleep(3)` WHERE sleep(3);
SELECT sleep(2147483647) AS `sleep(2147483647)`;
SELECT dense_rank() OVER (ORDER BY sleep(3) ASC ) AS `dense_rank() OVER (ORDER BY sleep(3) ASC )`;
SELECT CAST((sleep(3)) AS JSON)->'$.a' AS `CAST((sleep(3)) AS JSON)->'$.a'`;
SELECT DISTINCT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)` LIMIT 5;
SELECT sleep(-1.0E308) AS `sleep(-1.0E308)`;
SELECT sleep(0.0) AS `sleep(0.0)`;
SELECT sleep('\\') AS `sleep('\\')`;
SELECT sleep(3) AS `sleep(3)` WHERE sleep(3);
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(0.0) AS `sleep(0.0)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)` WHERE sleep(3);
SELECT sleep(-9223372036854775808) AS `sleep(-9223372036854775808)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep('0000-00-00') AS `sleep('0000-00-00')`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(-2147483648) AS `sleep(-2147483648)`;
SELECT CAST((sleep(3)) AS INT) AS `CAST((sleep(3)) AS INT)`;
SELECT sleep(3) AS `sleep(3)` WHERE sleep(3);
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)` LIMIT 1;
SELECT sleep(3) AS `sleep(3)` ORDER BY sleep(3) DESC;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep('0000-00-00') AS `sleep('0000-00-00')`;