SELECT 'Query 1: Validate large array element extraction' AS `test_description`;
SELECT 'Query 2: Validate large map key extraction' AS `test_description`;
SELECT 'Query 3: Validate deep nesting path extraction' AS `test_description`;
SELECT 'Query 4: Validate mixed array/object deep nesting' AS `test_description`;
SELECT 'Query 5: Validate nested array access' AS `test_description`;
SELECT 'Query 6: Validate INT min/max boundary values' AS `test_description`;
SELECT 'Query 7: Validate BIGINT min/max boundary values' AS `test_description`;
SELECT 'Query 8: Validate SMALLINT boundary values' AS `test_description`;
SELECT 'Query 9: Validate DOUBLE extreme values' AS `test_description`;
SELECT 'Query 10: Validate DECIMAL precision and scale' AS `test_description`;
SELECT 'Query 11: Validate negative zero handling' AS `test_description`;
SELECT 'Query 12: Verify variant_typeof for numeric types' AS `test_description`;
SELECT 'Query 13: Array size and access performance summary' AS `test_description`;
SELECT max('Query 1: Validate large array element extraction') OVER () AS `test_description`;
SELECT 'Query 1: Validate large array element extraction' AS `test_description` WHERE 'Query 7: Validate BIGINT min/max boundary values';
SELECT CAST('Query 1: Validate large array element extraction' AS JSON)->'k' AS `test_description`;
SELECT 'Query 1: Validate large array element extraction' AS `test_description` LIMIT 5;
SELECT count('Query 1: Validate large array element extraction') OVER () AS `test_description`;
SELECT DISTINCT 'Query 1: Validate large array element extraction' AS `test_description`;
SELECT 'Query 1: Validate large array element extraction' AS `test_description` LIMIT 7, 0;
SELECT 'Query 1: Validate large array element extraction' AS `test_description` LIMIT 1;
SELECT DISTINCT 'Query 1: Validate large array element extraction' AS `test_description`;
SELECT 'Query 1: Validate large array element extraction' AS `test_description` ORDER BY 'Query 1: Validate large array element extraction' DESC;
SELECT DISTINCT 'Query 1: Validate large array element extraction' AS `test_description`;
SELECT max('Query 1: Validate large array element extraction') OVER () AS `test_description`;
SELECT 'Query 1: Validate large array element extraction' AS `test_description` ORDER BY 'Query 1: Validate large array element extraction' DESC;
SELECT CAST((CAST('Query 1: Validate large array element extraction' AS DOUBLE)) AS DOUBLE) AS `test_description`;
SELECT CAST('Query 1: Validate large array element extraction' AS JSON)->'k' AS `test_description`;
SELECT CAST('Query 1: Validate large array element extraction' AS ARRAY<INT>) AS `test_description`;
SELECT CAST('Query 1: Validate large array element extraction' AS JSON)->'k' AS `test_description`;
SELECT 'Query 1: Validate large array element extraction' AS `test_description` LIMIT 1;
SELECT 'Query 2: Validate large map key extraction' AS `test_description` LIMIT 7, 100;
SELECT CAST('Query 2: Validate large map key extraction' AS JSON)->'k' AS `test_description`;
SELECT 'Query 2: Validate large map key extraction' AS `test_description` LIMIT 2;
SELECT sum('Query 2: Validate large map key extraction') OVER () AS `test_description`;
SELECT 'Query 2: Validate large map key extraction' AS `test_description` ORDER BY 'Query 2: Validate large map key extraction' DESC NULLS FIRST;
SELECT DISTINCT 'Query 2: Validate large map key extraction' AS `test_description`;
SELECT DISTINCT 'Query 2: Validate large map key extraction' AS `test_description`;
SELECT DISTINCT 'Query 2: Validate large map key extraction' AS `test_description`;
SELECT 'Query 2: Validate large map key extraction' AS `test_description` LIMIT 1, 1;
SELECT 'Query 2: Validate large map key extraction' AS `test_description` ORDER BY 'Query 2: Validate large map key extraction' DESC;
SELECT 'Query 2: Validate large map key extraction' AS `test_description` GROUP BY 'Query 2: Validate large map key extraction';
SELECT CAST('Query 2: Validate large map key extraction' AS JSON)->'$' AS `test_description`;
SELECT CAST('Query 2: Validate large map key extraction' AS JSON)->'$.a' AS `test_description`;
SELECT 'Query 3: Validate deep nesting path extraction' AS `test_description` GROUP BY 'Query 3: Validate deep nesting path extraction';
SELECT 'Query 3: Validate deep nesting path extraction' AS `test_description` ORDER BY 'Query 3: Validate deep nesting path extraction' DESC;
SELECT 'Query 3: Validate deep nesting path extraction' AS `test_description` WHERE 'Query 6: Validate INT min/max boundary values';
SELECT 'Query 3: Validate deep nesting path extraction' AS `test_description` WHERE 'Query 8: Validate SMALLINT boundary values';
SELECT 'Query 3: Validate deep nesting path extraction' AS `test_description` LIMIT 1;
SELECT CAST('Query 3: Validate deep nesting path extraction' AS JSON)->'$.a' AS `test_description`;
SELECT DISTINCT 'Query 3: Validate deep nesting path extraction' AS `test_description`;
SELECT 'Query 3: Validate deep nesting path extraction' AS `test_description` ORDER BY 'Query 3: Validate deep nesting path extraction' DESC;
SELECT 'Query 3: Validate deep nesting path extraction' AS `test_description` WHERE 'Query 7: Validate BIGINT min/max boundary values';
SELECT 'Query 3: Validate deep nesting path extraction' AS `test_description` GROUP BY 'Query 3: Validate deep nesting path extraction';
SELECT 'Query 3: Validate deep nesting path extraction' AS `test_description` ORDER BY 'Query 3: Validate deep nesting path extraction' DESC;
SELECT avg('Query 4: Validate mixed array/object deep nesting') OVER () AS `test_description`;
SELECT 'Query 4: Validate mixed array/object deep nesting' AS `test_description` GROUP BY 'Query 4: Validate mixed array/object deep nesting';
SELECT 'Query 4: Validate mixed array/object deep nesting' AS `test_description` ORDER BY 'Query 4: Validate mixed array/object deep nesting' DESC;
SELECT 'Query 4: Validate mixed array/object deep nesting' AS `test_description` GROUP BY 'Query 4: Validate mixed array/object deep nesting';
SELECT 'Query 4: Validate mixed array/object deep nesting' AS `test_description` LIMIT 1;
SELECT CAST('Query 4: Validate mixed array/object deep nesting' AS DECIMAL128(38,0)) AS `test_description`;
SELECT sum('Query 4: Validate mixed array/object deep nesting') OVER () AS `test_description`;
SELECT 'Query 4: Validate mixed array/object deep nesting' AS `test_description` LIMIT 2;
SELECT 'Query 4: Validate mixed array/object deep nesting' AS `test_description` LIMIT 1;
SELECT 'Query 4: Validate mixed array/object deep nesting' AS `test_description` WHERE 'Query 8: Validate SMALLINT boundary values';
SELECT 'Query 4: Validate mixed array/object deep nesting' AS `test_description` LIMIT 5;
SELECT json_length(CAST('Query 4: Validate mixed array/object deep nesting' AS JSON)) AS `test_description`;
SELECT 'Query 4: Validate mixed array/object deep nesting' AS `test_description` ORDER BY 'Query 4: Validate mixed array/object deep nesting' ASC;
SELECT 'Query 5: Validate nested array access' AS `test_description` ORDER BY 'Query 5: Validate nested array access' DESC;
SELECT 'Query 5: Validate nested array access' AS `test_description` LIMIT 100;
SELECT DISTINCT 'Query 5: Validate nested array access' AS `test_description`;
SELECT DISTINCT 'Query 5: Validate nested array access' AS `test_description`;
SELECT 'Query 5: Validate nested array access' AS `test_description` ORDER BY 'Query 5: Validate nested array access' DESC;
SELECT CAST((CAST('Query 5: Validate nested array access' AS BOOLEAN)) AS ARRAY<JSON>) AS `test_description`;
SELECT min('Query 5: Validate nested array access') OVER () AS `test_description`;
SELECT 'Query 5: Validate nested array access' AS `test_description` ORDER BY 'Query 5: Validate nested array access' DESC;
SELECT CAST('Query 5: Validate nested array access' AS ARRAY<INT>) AS `test_description`;
SELECT count('Query 5: Validate nested array access') OVER () AS `test_description`;
SELECT DISTINCT 'Query 5: Validate nested array access' AS `test_description`;
SELECT 'Query 5: Validate nested array access' AS `test_description` WHERE 'Query 6: Validate INT min/max boundary values';
SELECT 'Query 5: Validate nested array access' AS `test_description` LIMIT 0;
SELECT 'Query 5: Validate nested array access' AS `test_description` GROUP BY 'Query 5: Validate nested array access';
SELECT 'Query 5: Validate nested array access' AS `test_description` LIMIT 1, 1;
SELECT 'Query 5: Validate nested array access' AS `test_description` LIMIT 7, 0;
SELECT get_json_string(CAST('Query 6: Validate INT min/max boundary values' AS JSON), '$.a') AS `test_description`;
SELECT 'Query 6: Validate INT min/max boundary values' AS `test_description` LIMIT 1, 5;
SELECT DISTINCT 'Query 6: Validate INT min/max boundary values' AS `test_description`;
SELECT CAST('Query 6: Validate INT min/max boundary values' AS DATE) AS `test_description`;
SELECT 'Query 6: Validate INT min/max boundary values' AS `test_description` GROUP BY 'Query 6: Validate INT min/max boundary values';
SELECT get_json_string(CAST('Query 6: Validate INT min/max boundary values' AS JSON), '$.a') AS `test_description`;
SELECT 'Query 6: Validate INT min/max boundary values' AS `test_description` LIMIT 0;
SELECT CAST((CAST('Query 7: Validate BIGINT min/max boundary values' AS VARCHAR(65533))) AS LARGEINT) AS `test_description`;
SELECT 'Query 7: Validate BIGINT min/max boundary values' AS `test_description` ORDER BY 'Query 7: Validate BIGINT min/max boundary values' DESC NULLS FIRST;
SELECT 'Query 7: Validate BIGINT min/max boundary values' AS `test_description` WHERE 'Query 7: Validate BIGINT min/max boundary values';
SELECT 'Query 7: Validate BIGINT min/max boundary values' AS `test_description` LIMIT 5;
SELECT 'Query 7: Validate BIGINT min/max boundary values' AS `test_description` LIMIT 0;
SELECT DISTINCT 'Query 7: Validate BIGINT min/max boundary values' AS `test_description`;
SELECT 'Query 7: Validate BIGINT min/max boundary values' AS `test_description` ORDER BY 'Query 7: Validate BIGINT min/max boundary values' ASC;
SELECT get_json_string(CAST('Query 8: Validate SMALLINT boundary values' AS JSON), '$.a') AS `test_description`;
SELECT CAST('Query 8: Validate SMALLINT boundary values' AS JSON)->'k' AS `test_description`;
SELECT min('Query 8: Validate SMALLINT boundary values') OVER () AS `test_description`;
SELECT count('Query 8: Validate SMALLINT boundary values') OVER () AS `test_description`;
SELECT 'Query 8: Validate SMALLINT boundary values' AS `test_description` GROUP BY 'Query 8: Validate SMALLINT boundary values';
SELECT min('Query 8: Validate SMALLINT boundary values') OVER () AS `test_description`;
SELECT 'Query 8: Validate SMALLINT boundary values' AS `test_description` ORDER BY 'Query 8: Validate SMALLINT boundary values' ASC;
SELECT 'Query 8: Validate SMALLINT boundary values' AS `test_description` GROUP BY 'Query 8: Validate SMALLINT boundary values';
SELECT DISTINCT 'Query 8: Validate SMALLINT boundary values' AS `test_description`;
SELECT DISTINCT 'Query 8: Validate SMALLINT boundary values' AS `test_description`;
SELECT 'Query 8: Validate SMALLINT boundary values' AS `test_description` ORDER BY 'Query 8: Validate SMALLINT boundary values' ASC;
SELECT CAST('Query 9: Validate DOUBLE extreme values' AS ARRAY<VARCHAR(1)>) AS `test_description`;
SELECT DISTINCT 'Query 9: Validate DOUBLE extreme values' AS `test_description`;
SELECT CAST((CAST('Query 9: Validate DOUBLE extreme values' AS DECIMAL128(38,0))) AS DOUBLE) AS `test_description`;
SELECT 'Query 9: Validate DOUBLE extreme values' AS `test_description` LIMIT 100;
SELECT 'Query 9: Validate DOUBLE extreme values' AS `test_description` LIMIT 0;
SELECT 'Query 9: Validate DOUBLE extreme values' AS `test_description` LIMIT 0;
SELECT 'Query 9: Validate DOUBLE extreme values' AS `test_description` ORDER BY 'Query 9: Validate DOUBLE extreme values' ASC;
SELECT count('Query 9: Validate DOUBLE extreme values') OVER () AS `test_description`;
SELECT json_length(CAST('Query 9: Validate DOUBLE extreme values' AS JSON)) AS `test_description`;
SELECT 'Query 10: Validate DECIMAL precision and scale' AS `test_description` LIMIT 1, 2;
SELECT 'Query 10: Validate DECIMAL precision and scale' AS `test_description` LIMIT 7, 100;
SELECT 'Query 10: Validate DECIMAL precision and scale' AS `test_description` LIMIT 0;
SELECT json_length(CAST('Query 10: Validate DECIMAL precision and scale' AS JSON)) AS `test_description`;
SELECT CAST('Query 10: Validate DECIMAL precision and scale' AS JSON)->'k' AS `test_description`;
SELECT 'Query 10: Validate DECIMAL precision and scale' AS `test_description` LIMIT 1, 2;
SELECT 'Query 10: Validate DECIMAL precision and scale' AS `test_description` LIMIT 7, 1;
SELECT 'Query 10: Validate DECIMAL precision and scale' AS `test_description` ORDER BY 'Query 10: Validate DECIMAL precision and scale' DESC;
SELECT DISTINCT 'Query 10: Validate DECIMAL precision and scale' AS `test_description`;
SELECT DISTINCT 'Query 10: Validate DECIMAL precision and scale' AS `test_description`;
SELECT get_json_string(CAST('Query 11: Validate negative zero handling' AS JSON), '$.a') AS `test_description`;
SELECT 'Query 11: Validate negative zero handling' AS `test_description` WHERE 'Query 4: Validate mixed array/object deep nesting';
SELECT 'Query 11: Validate negative zero handling' AS `test_description` GROUP BY 'Query 11: Validate negative zero handling';
SELECT 'Query 11: Validate negative zero handling' AS `test_description` ORDER BY 'Query 11: Validate negative zero handling' ASC;
SELECT CAST((CAST('Query 11: Validate negative zero handling' AS VARCHAR(1))) AS VARCHAR(1)) AS `test_description`;
SELECT 'Query 11: Validate negative zero handling' AS `test_description` WHERE 'Query 3: Validate deep nesting path extraction';
SELECT count('Query 11: Validate negative zero handling') OVER () AS `test_description`;
SELECT DISTINCT 'Query 11: Validate negative zero handling' AS `test_description`;
SELECT 'Query 12: Verify variant_typeof for numeric types' AS `test_description` WHERE 'Query 1: Validate large array element extraction';
SELECT DISTINCT 'Query 12: Verify variant_typeof for numeric types' AS `test_description`;
SELECT 'Query 12: Verify variant_typeof for numeric types' AS `test_description` ORDER BY 'Query 12: Verify variant_typeof for numeric types' ASC;
SELECT 'Query 12: Verify variant_typeof for numeric types' AS `test_description` ORDER BY 'Query 12: Verify variant_typeof for numeric types' DESC NULLS FIRST;
SELECT 'Query 12: Verify variant_typeof for numeric types' AS `test_description` WHERE 'Query 9: Validate DOUBLE extreme values';
SELECT 'Query 12: Verify variant_typeof for numeric types' AS `test_description` LIMIT 5;
SELECT 'Query 12: Verify variant_typeof for numeric types' AS `test_description` LIMIT 1, 5;
SELECT CAST('Query 12: Verify variant_typeof for numeric types' AS JSON) AS `test_description`;
SELECT 'Query 12: Verify variant_typeof for numeric types' AS `test_description` LIMIT 0;
SELECT 'Query 12: Verify variant_typeof for numeric types' AS `test_description` ORDER BY 'Query 12: Verify variant_typeof for numeric types' DESC;
SELECT 'Query 12: Verify variant_typeof for numeric types' AS `test_description` GROUP BY 'Query 12: Verify variant_typeof for numeric types';
SELECT CAST('Query 13: Array size and access performance summary' AS JSON)->'$.a' AS `test_description`;
SELECT count('Query 13: Array size and access performance summary') OVER () AS `test_description`;
SELECT DISTINCT 'Query 13: Array size and access performance summary' AS `test_description`;
SELECT 'Query 13: Array size and access performance summary' AS `test_description` WHERE 'Query 4: Validate mixed array/object deep nesting';
SELECT 'Query 13: Array size and access performance summary' AS `test_description` ORDER BY 'Query 13: Array size and access performance summary' ASC NULLS LAST;
SELECT 'Query 13: Array size and access performance summary' AS `test_description` GROUP BY 'Query 13: Array size and access performance summary';
SELECT 'Query 13: Array size and access performance summary' AS `test_description` WHERE 'Query 7: Validate BIGINT min/max boundary values';
SELECT min('Query 13: Array size and access performance summary') OVER () AS `test_description`;
SELECT sum('Query 13: Array size and access performance summary') OVER () AS `test_description`;
SELECT 'Query 13: Array size and access performance summary' AS `test_description` GROUP BY 'Query 13: Array size and access performance summary';
SELECT 'Query 13: Array size and access performance summary' AS `test_description` GROUP BY 'Query 13: Array size and access performance summary';
SELECT 'Query 13: Array size and access performance summary' AS `test_description` GROUP BY 'Query 13: Array size and access performance summary';
SELECT 'Query 13: Array size and access performance summary' AS `test_description` LIMIT 2;