SELECT from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC') AS `from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC')`;
SELECT from_unixtime(1, '', 'UTC') AS `from_unixtime(1, '', 'UTC')`;
SELECT from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', CAST(NULL AS JSON)) AS `from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', CAST(NULL AS JSON))`;
SELECT from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', '\\') AS `from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', '\\')`;
SELECT from_unixtime(-1, NULL, 'UTC') AS `from_unixtime(-1, NULL, 'UTC')`;
SELECT from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC') AS `from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC')`;
SELECT from_unixtime('', 'yyyy-MM-dd HH:mm:ss', 'UTC') AS `from_unixtime('', 'yyyy-MM-dd HH:mm:ss', 'UTC')`;
SELECT from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC') AS `from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC')`;
SELECT from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC') AS `from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC')` LIMIT 5;
SELECT from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC') AS `from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC')` GROUP BY from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC');
SELECT from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC') AS `from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC')` WHERE 'UTC';
SELECT from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'yyyy-MM-dd HH:mm:ss') AS `from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'yyyy-MM-dd HH:mm:ss')`;
SELECT from_unixtime(-1, '', 'UTC') AS `from_unixtime(-1, '', 'UTC')`;
SELECT from_unixtime(-1, json_length(CAST('yyyy-MM-dd HH:mm:ss' AS JSON)), 'UTC') AS `from_unixtime(-1, json_length(CAST('yyyy-MM-dd HH:mm:ss' AS JSON)), 'UTC')`;
SELECT from_unixtime(-1, 'UTC', 'UTC') AS `from_unixtime(-1, 'UTC', 'UTC')`;
SELECT from_unixtime(0.0, 'yyyy-MM-dd HH:mm:ss', 'UTC') AS `from_unixtime(0.0, 'yyyy-MM-dd HH:mm:ss', 'UTC')`;
SELECT from_unixtime(-1, -1, 'UTC') AS `from_unixtime(-1, -1, 'UTC')`;
SELECT from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC') AS `from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC')`;
SELECT from_unixtime(-1, TRUE, 'UTC') AS `from_unixtime(-1, TRUE, 'UTC')`;
SELECT from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC') AS `from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC')` WHERE 'UTC';
SELECT from_unixtime(-1, from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC'), 'UTC') AS `from_unixtime(-1, from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC'), 'UTC')`;
SELECT from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC') AS `from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC')` LIMIT 1;
SELECT from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC') AS `from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC')` GROUP BY from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC');
SELECT from_unixtime(-1, 'UTC', 'UTC') AS `from_unixtime(-1, 'UTC', 'UTC')`;
SELECT from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC') AS `from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC')`;
SELECT DISTINCT from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC') AS `from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC')`;
SELECT from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC') AS `from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC')` LIMIT 0;
SELECT from_unixtime(-1, 9223372036854775807, 'UTC') AS `from_unixtime(-1, 9223372036854775807, 'UTC')`;
SELECT from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC') AS `from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC')`;
SELECT from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC') AS `from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC')` WHERE -1;
SELECT from_unixtime(-1, from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC'), 'UTC') AS `from_unixtime(-1, from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 'UTC'), 'UTC')`;
SELECT from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 0) AS `from_unixtime(-1, 'yyyy-MM-dd HH:mm:ss', 0)`;
SELECT from_unixtime(1, 9223372036854775807, 'UTC') AS `from_unixtime(1, 9223372036854775807, 'UTC')`;
SELECT from_unixtime('', '', 'UTC') AS `from_unixtime('', '', 'UTC')`;
SELECT from_unixtime(1, '', 'UTC') AS `from_unixtime(1, '', 'UTC')` ORDER BY from_unixtime(1, '', 'UTC') ASC NULLS LAST;
SELECT from_unixtime(1, '', '') AS `from_unixtime(1, '', '')`;
SELECT DISTINCT from_unixtime(1, '', 'UTC') AS `from_unixtime(1, '', 'UTC')`;
SELECT from_unixtime(1, '', '') AS `from_unixtime(1, '', '')`;
SELECT from_unixtime('UTC', '', 'UTC') AS `from_unixtime('UTC', '', 'UTC')`;
SELECT from_unixtime(1, '', 'UTC') AS `from_unixtime(1, '', 'UTC')` WHERE 'UTC';
SELECT from_unixtime(1, 1, 'UTC') AS `from_unixtime(1, 1, 'UTC')`;
SELECT from_unixtime('UTC', '', 'UTC') AS `from_unixtime('UTC', '', 'UTC')`;
SELECT from_unixtime(1, '', 0.0) AS `from_unixtime(1, '', 0.0)`;
SELECT from_unixtime(1, 'UTC', 'UTC') AS `from_unixtime(1, 'UTC', 'UTC')`;
SELECT from_unixtime('', '', 'UTC') AS `from_unixtime('', '', 'UTC')`;
SELECT from_unixtime(1, '', 'UTC') AS `from_unixtime(1, '', 'UTC')`;
SELECT from_unixtime(-1.0E308, '', 'UTC') AS `from_unixtime(-1.0E308, '', 'UTC')`;
SELECT from_unixtime(1, '1970-01-01', 'UTC') AS `from_unixtime(1, '1970-01-01', 'UTC')`;
SELECT DISTINCT from_unixtime(1, '', 'UTC') AS `from_unixtime(1, '', 'UTC')`;
SELECT from_unixtime(-9223372036854775808, '', 'UTC') AS `from_unixtime(-9223372036854775808, '', 'UTC')`;
SELECT from_unixtime(1, '', 'UTC') AS `from_unixtime(1, '', 'UTC')` GROUP BY from_unixtime(1, '', 'UTC');
SELECT from_unixtime(1, '', 'UTC') AS `from_unixtime(1, '', 'UTC')` WHERE 'UTC';
SELECT from_unixtime(1, '', '%') AS `from_unixtime(1, '', '%')`;
SELECT from_unixtime(1, '', 'UTC') AS `from_unixtime(1, '', 'UTC')` WHERE 'yyyy-MM-dd HH:mm:ss';
SELECT max(from_unixtime(1, '', 'UTC')) OVER () AS `max(from_unixtime(1, '', 'UTC')) OVER ()`;
SELECT from_unixtime(1, '', 'UTC') AS `from_unixtime(1, '', 'UTC')`;
SELECT from_unixtime(1, '', 'UTC') AS `from_unixtime(1, '', 'UTC')` LIMIT 1, 0;
SELECT from_unixtime(1, CAST(NULL AS JSON), 'UTC') AS `from_unixtime(1, CAST(NULL AS JSON), 'UTC')`;
SELECT from_unixtime(1, '', 'UTC') AS `from_unixtime(1, '', 'UTC')` LIMIT 2;
SELECT from_unixtime(-9223372036854775808, '', 'UTC') AS `from_unixtime(-9223372036854775808, '', 'UTC')`;
SELECT from_unixtime(1, '', 'UTC') AS `from_unixtime(1, '', 'UTC')`;