SELECT min(`srfuzz_mut_948`.`t1_partial_empty`.`dt`) AS `min(dt)` FROM `srfuzz_mut_948`.`t1_partial_empty`;
SELECT min(`srfuzz_mut_948`.`t1_partial_empty`.`dt`) AS `min(srfuzz_mut_948.t1_partial_empty.dt)` FROM `srfuzz_mut_948`.`t1_partial_empty`;
SELECT min(`srfuzz_mut_948`.`t1_partial_empty`.`dt`) AS `min(dt)` FROM `srfuzz_mut_948`.`t1_partial_empty`;
SELECT min(`t1_partial_empty`.`dt`) AS `min(dt)` FROM (SELECT `srfuzz_mut_948`.`t1_partial_empty`.`dt`, `srfuzz_mut_948`.`t1_partial_empty`.`id`, `srfuzz_mut_948`.`t1_partial_empty`.`value` FROM `srfuzz_mut_948`.`t1_partial_empty` UNION ALL SELECT `srfuzz_mut_948`.`t1_partial_empty`.`dt`, `srfuzz_mut_948`.`t1_partial_empty`.`id`, `srfuzz_mut_948`.`t1_partial_empty`.`value` FROM `srfuzz_mut_948`.`t1_partial_empty`) `t1_partial_empty`;
SELECT min(`srfuzz_mut_948`.`t1_partial_empty`.`dt`) AS `min(dt)` FROM `srfuzz_mut_948`.`t1_partial_empty` HAVING (count(*)) < 10;
SELECT min(`srfuzz_mut_948`.`t1_partial_empty`.`dt`) AS `min(dt)` FROM `srfuzz_mut_948`.`t1_partial_empty`;
SELECT min(`srfuzz_mut_948`.`t1_partial_empty`.`dt`) AS `min(dt)` FROM `srfuzz_mut_948`.`t1_partial_empty`;
SELECT min(`srfuzz_mut_948`.`t1_partial_empty`.`dt`) AS `min(dt)` FROM `srfuzz_mut_948`.`t1_partial_empty` LIMIT 7, 2;
SELECT min(`srfuzz_mut_948`.`t1_partial_empty`.`dt`) AS `min(dt)` FROM `srfuzz_mut_948`.`t1_partial_empty`;
SELECT min(`srfuzz_mut_948`.`t1_partial_empty`.`dt`) AS `min(dt)` FROM `srfuzz_mut_948`.`t1_partial_empty`;
SELECT min(`srfuzz_mut_948`.`t1_partial_empty`.`dt`) AS `min(srfuzz_mut_948.t1_partial_empty.dt)` FROM `srfuzz_mut_948`.`t1_partial_empty`;
SELECT min(`srfuzz_mut_948`.`t1_partial_empty`.`dt`) AS `min(srfuzz_mut_948.t1_partial_empty.dt)` FROM `srfuzz_mut_948`.`t1_partial_empty`;
SELECT min(`t1_partial_empty`.`dt`) AS `min(dt)` FROM (SELECT `srfuzz_mut_948`.`t1_partial_empty`.`dt`, `srfuzz_mut_948`.`t1_partial_empty`.`id`, `srfuzz_mut_948`.`t1_partial_empty`.`value` FROM `srfuzz_mut_948`.`t1_partial_empty`) `t1_partial_empty`;
SELECT min(`srfuzz_mut_948`.`t1_partial_empty`.`dt`) AS `min(dt)` FROM `srfuzz_mut_948`.`t1_partial_empty`;
SELECT min(`srfuzz_mut_948`.`t1_partial_empty`.`dt`) AS `min(dt)` FROM `srfuzz_mut_948`.`t1_partial_empty` GROUP BY `srfuzz_mut_948`.`t1_partial_empty`.`dt`;
SELECT min(`srfuzz_mut_948`.`t1_partial_empty`.`dt`) AS `min(dt)` FROM `srfuzz_mut_948`.`t1_partial_empty`;
SELECT min(`srfuzz_mut_948`.`t1_partial_empty`.`dt`) AS `min(srfuzz_mut_948.t1_partial_empty.dt)` FROM `srfuzz_mut_948`.`t1_partial_empty`;
SELECT min(`srfuzz_mut_948`.`t1_partial_empty`.`dt`) AS `min(srfuzz_mut_948.t1_partial_empty.dt)` FROM `srfuzz_mut_948`.`t1_partial_empty`;
SELECT min(`srfuzz_mut_948`.`t1_partial_empty`.`dt`) AS `min(dt)` FROM `srfuzz_mut_948`.`t1_partial_empty`;
SELECT min(`srfuzz_mut_948`.`t1_partial_empty`.`dt`) AS `min(dt)` FROM `srfuzz_mut_948`.`t1_partial_empty`;
SELECT min(`srfuzz_mut_948`.`t1_partial_empty`.`dt`) AS `min(dt)` FROM `srfuzz_mut_948`.`t1_partial_empty`;
SELECT min(`srfuzz_mut_948`.`t1_partial_empty`.`dt`) AS `min(dt)` FROM `srfuzz_mut_948`.`t1_partial_empty`;
SELECT min(`srfuzz_mut_948`.`t1_partial_empty`.`dt`) AS `min(dt)` FROM `srfuzz_mut_948`.`t1_partial_empty`;
SELECT min(`srfuzz_mut_948`.`t1_partial_empty`.`dt`) AS `min(dt)` FROM `srfuzz_mut_948`.`t1_partial_empty`;
SELECT min(`srfuzz_mut_948`.`t1_partial_empty`.`dt`) AS `min(dt)` FROM `srfuzz_mut_948`.`t1_partial_empty` HAVING (count(*)) >= 2;