SELECT `srfuzz_mut_291`.`test_delete_dup_rename`.`name1` FROM `srfuzz_mut_291`.`test_delete_dup_rename`;
SELECT `srfuzz_mut_291`.`test_delete_dup_rename`.`name1` FROM `srfuzz_mut_291`.`test_delete_dup_rename`;
SELECT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename`;
SELECT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename`;
SELECT DISTINCT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename`;
SELECT DISTINCT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename`;
SELECT `test_delete_dup_rename`.`name2` FROM (SELECT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename`) `test_delete_dup_rename`;
SELECT `test_delete_dup_rename`.`name2` FROM (SELECT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename` UNION SELECT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename`) `test_delete_dup_rename`;
SELECT `test_delete_dup_rename`.`name2` FROM (SELECT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename`) `test_delete_dup_rename`;
SELECT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename` LIMIT 5;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename`) SELECT `test_delete_dup_rename`.`name2` FROM `srfuzz_n1` AS test_delete_dup_rename;
SELECT DISTINCT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename`;
SELECT `test_delete_dup_rename`.`name2` FROM (SELECT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename` EXCEPT SELECT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename`) `test_delete_dup_rename`;
SELECT `test_delete_dup_rename`.`name2`, `srfuzz_n1`.`e` FROM (SELECT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename`) `test_delete_dup_rename` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename`) SELECT `test_delete_dup_rename`.`name2` FROM `srfuzz_n1` AS test_delete_dup_rename;
SELECT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename` LIMIT 2;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename`) SELECT `test_delete_dup_rename`.`name2` FROM `srfuzz_n1` AS test_delete_dup_rename;
SELECT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename` LIMIT 1, 5;
SELECT `test_delete_dup_rename`.`name2` FROM (SELECT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename` UNION SELECT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename`) `test_delete_dup_rename`;
SELECT `test_delete_dup_rename`.`name2`, `srfuzz_n1`.`e` FROM (SELECT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename`) `test_delete_dup_rename` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename`) SELECT `test_delete_dup_rename`.`name2` FROM `srfuzz_n1` AS test_delete_dup_rename;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename`) SELECT `test_delete_dup_rename`.`name2` FROM `srfuzz_n1` AS test_delete_dup_rename;
SELECT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename` LIMIT 2;
SELECT DISTINCT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename`;
SELECT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename` LIMIT 7, 1;
SELECT `test_delete_dup_rename`.`name2` FROM (SELECT `srfuzz_mut_291`.`test_delete_dup_rename`.`name2` FROM `srfuzz_mut_291`.`test_delete_dup_rename`) `test_delete_dup_rename`;