SELECT @var AS `@var`;
SELECT @var AS `@var`;
WITH `tx` AS (SELECT @var2 AS `x`) SELECT `tx`.`x` FROM `tx`;
SELECT @var2 AS `@var2`;
WITH `tx` AS (SELECT @var2 AS `x`) SELECT `tx`.`x` FROM `tx`;
SELECT percentile_approx(`srfuzz_mut_1268`.`t0`.`c0`, CAST(NULL AS DOUBLE)) AS `percentile_approx(c0, CAST(NULL AS DOUBLE))` FROM `srfuzz_mut_1268`.`t0`;
SELECT `srfuzz_mut_1268`.`pk1`.`c0`, `srfuzz_mut_1268`.`pk1`.`dt` FROM `srfuzz_mut_1268`.`pk1`;
SELECT get_json_string(CAST((@var) AS JSON), '$.a') AS `get_json_string(CAST((@var) AS JSON), '$.a')`;
SELECT @var AS `@var` LIMIT 1;
SELECT @var AS `@var` WHERE @var2;
SELECT @var AS `@var` ORDER BY @var ASC;
SELECT @var AS `@var` ORDER BY @var DESC;
SELECT DISTINCT @var AS `@var`;
SELECT @var AS `@var` LIMIT 2;
SELECT DISTINCT @var AS `@var`;
SELECT @var AS `@var` GROUP BY @var;
SELECT json_length(CAST((@var) AS JSON)) AS `json_length(CAST((@var) AS JSON))`;
SELECT @var AS `@var` ORDER BY @var ASC;
SELECT @var AS `@var` GROUP BY @var;
SELECT @var AS `@var` LIMIT 5;
SELECT @var AS `@var` ORDER BY @var ASC;
SELECT @var AS `@var` WHERE NULL;
SELECT @var AS `@var` GROUP BY @var;
WITH `tx` AS (SELECT @var2 AS `x`) SELECT `tx`.`x` FROM (SELECT `tx`.`x` FROM `tx` INTERSECT SELECT `tx`.`x` FROM `tx`) `tx`;
WITH `tx` AS (SELECT @var2 AS `x`) SELECT `tx`.`x` FROM (SELECT `tx`.`x` FROM `tx`) `tx`;
WITH `tx` AS (SELECT @var2 AS `x`) SELECT `tx`.`x` FROM (SELECT `tx`.`x` FROM `tx` UNION ALL SELECT `tx`.`x` FROM `tx`) `tx`;
WITH `tx` AS (SELECT @var2 AS `x`) SELECT DISTINCT `tx`.`x` FROM `tx`;
WITH `tx` AS (SELECT @var2 AS `x`) SELECT DISTINCT `tx`.`x` FROM `tx`;
WITH `tx` AS (SELECT @var2 AS `x`) SELECT `tx`.`x`, `srfuzz_n1`.`e` FROM (SELECT `tx`.`x` FROM `tx`) `tx` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
WITH `tx` AS (SELECT @var2 AS `x`) SELECT `tx`.`x` FROM (SELECT `tx`.`x` FROM `tx` INTERSECT SELECT `tx`.`x` FROM `tx`) `tx`;
WITH `tx` AS (SELECT @var2 AS `x` WHERE CAST(NULL AS DOUBLE)) SELECT `tx`.`x` FROM `tx`;
SELECT @var2 AS `@var2` GROUP BY @var2;
SELECT DISTINCT @var2 AS `@var2`;
SELECT @var2 AS `@var2` ORDER BY @var2 DESC NULLS FIRST;
SELECT DISTINCT @var2 AS `@var2`;
SELECT @var2 AS `@var2` ORDER BY @var2 ASC;
SELECT DISTINCT @var2 AS `@var2`;
SELECT @var2 AS `@var2` WHERE @var;
SELECT @var2 AS `@var2` LIMIT 2;
SELECT @var2 AS `@var2` WHERE @var2;
SELECT DISTINCT @var2 AS `@var2`;
SELECT @var2 AS `@var2` ORDER BY @var2 ASC;
SELECT @var2 AS `@var2` LIMIT 1;
WITH `tx` AS (SELECT @var2 AS `x`) SELECT `tx`.`x` FROM `tx` WHERE @var;
WITH `tx` AS (SELECT CAST((@var2) AS JSON) AS `x`) SELECT `tx`.`x` FROM `tx`;
WITH `tx` AS (SELECT @var2 AS `x`) SELECT `tx`.`x` FROM (SELECT `tx`.`x` FROM `tx` EXCEPT SELECT `tx`.`x` FROM `tx`) `tx`;
WITH `tx` AS (SELECT CAST((@var2) AS JSON)->'$.a' AS `x`) SELECT `tx`.`x` FROM `tx`;
WITH `tx` AS (SELECT @var2 AS `x`) SELECT DISTINCT `tx`.`x` FROM `tx`;
WITH `tx` AS (SELECT @var2 AS `x`) SELECT `tx`.`x` FROM `tx` LIMIT 1, 5;
WITH `tx` AS (SELECT @var2 AS `x`) SELECT `tx`.`x`, `srfuzz_n1`.`e` FROM (SELECT `tx`.`x` FROM `tx`) `tx` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
WITH `tx` AS (SELECT DISTINCT @var2 AS `x`) SELECT `tx`.`x` FROM `tx`;
WITH `tx` AS (SELECT @var2 AS `x`) SELECT `tx`.`x` FROM (SELECT `tx`.`x` FROM `tx` UNION ALL SELECT `tx`.`x` FROM `tx`) `tx`;
WITH `tx` AS (SELECT @var2 AS `x`) SELECT `tx`.`x` FROM (SELECT `tx`.`x` FROM `tx` INTERSECT SELECT `tx`.`x` FROM `tx`) `tx`;
WITH `tx` AS (SELECT @var2 AS `x` WHERE CAST(NULL AS DOUBLE)) SELECT `tx`.`x` FROM `tx`;
WITH `tx` AS (SELECT DISTINCT @var2 AS `x`) SELECT `tx`.`x` FROM `tx`;
WITH `tx` AS (SELECT @var2 AS `x`) SELECT `tx`.`x`, `srfuzz_n1`.`e` FROM (SELECT `tx`.`x` FROM `tx`) `tx` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
WITH `tx` AS (SELECT @var2 AS `x` GROUP BY @var2) SELECT `tx`.`x` FROM `tx`;
SELECT percentile_approx(`srfuzz_mut_1268`.`t0`.`c0`, `srfuzz_mut_1268`.`t0`.`c0`) AS `percentile_approx(c0, srfuzz_mut_1268.t0.c0)` FROM `srfuzz_mut_1268`.`t0`;
SELECT percentile_approx(`srfuzz_mut_1268`.`t0`.`c0`, CAST(170141183460469231731687303715884105727 AS DOUBLE)) AS `percentile_approx(c0, CAST(170141183460469231731687303715884105727 AS DOUBLE))` FROM `srfuzz_mut_1268`.`t0`;
SELECT percentile_approx(`srfuzz_mut_1268`.`t0`.`c0`, CAST(NULL AS DOUBLE)) AS `percentile_approx(c0, CAST(NULL AS DOUBLE))` FROM `srfuzz_mut_1268`.`t0`;
SELECT percentile_approx(`srfuzz_mut_1268`.`t0`.`c0`, CAST(NULL AS DOUBLE)) AS `percentile_approx(c0, CAST(NULL AS DOUBLE))` FROM `srfuzz_mut_1268`.`t0` HAVING (count(*)) > 1;
SELECT percentile_approx(`srfuzz_mut_1268`.`t0`.`c0`, CAST(NULL AS DOUBLE)) AS `percentile_approx(c0, CAST(NULL AS DOUBLE))` FROM `srfuzz_mut_1268`.`t0`;
SELECT percentile_approx(`srfuzz_mut_1268`.`t0`.`c0`, CAST(NULL AS DOUBLE)) AS `percentile_approx(srfuzz_mut_1268.t0.c0, CAST(NULL AS DOUBLE))` FROM `srfuzz_mut_1268`.`t0`;
SELECT percentile_approx(`srfuzz_mut_1268`.`t0`.`c0`, `srfuzz_mut_1268`.`t0`.`c0`) AS `percentile_approx(c0, srfuzz_mut_1268.t0.c0)` FROM `srfuzz_mut_1268`.`t0`;
SELECT percentile_approx(`t0`.`c0`, CAST(NULL AS DOUBLE)) AS `percentile_approx(c0, CAST(NULL AS DOUBLE))` FROM (SELECT `srfuzz_mut_1268`.`t0`.`c0`, `srfuzz_mut_1268`.`t0`.`c1`, `srfuzz_mut_1268`.`t0`.`c2`, `srfuzz_mut_1268`.`t0`.`c3` FROM `srfuzz_mut_1268`.`t0` INTERSECT SELECT `srfuzz_mut_1268`.`t0`.`c0`, `srfuzz_mut_1268`.`t0`.`c1`, `srfuzz_mut_1268`.`t0`.`c2`, `srfuzz_mut_1268`.`t0`.`c3` FROM `srfuzz_mut_1268`.`t0`) `t0`;
SELECT percentile_approx(`srfuzz_mut_1268`.`t0`.`c0`, CAST(NULL AS DOUBLE)) AS `percentile_approx(c0, CAST(NULL AS DOUBLE))` FROM `srfuzz_mut_1268`.`t0`;
SELECT percentile_approx(`srfuzz_mut_1268`.`t0`.`c0`, CAST(NULL AS DOUBLE)) AS `percentile_approx(c0, CAST(NULL AS DOUBLE))` FROM `srfuzz_mut_1268`.`t0` HAVING (count(*)) >= 2;
SELECT percentile_approx(`srfuzz_mut_1268`.`t0`.`c0`, CAST(NULL AS DOUBLE)) AS `percentile_approx(c0, CAST(NULL AS DOUBLE))` FROM `srfuzz_mut_1268`.`t0`;
SELECT percentile_approx(`t0`.`c0`, CAST(NULL AS DOUBLE)) AS `percentile_approx(c0, CAST(NULL AS DOUBLE))` FROM (SELECT `srfuzz_mut_1268`.`t0`.`c0`, `srfuzz_mut_1268`.`t0`.`c1`, `srfuzz_mut_1268`.`t0`.`c2`, `srfuzz_mut_1268`.`t0`.`c3` FROM `srfuzz_mut_1268`.`t0`) `t0`;
SELECT percentile_approx(`t0`.`c0`, CAST(NULL AS DOUBLE)) AS `percentile_approx(c0, CAST(NULL AS DOUBLE))` FROM (SELECT `srfuzz_mut_1268`.`t0`.`c0`, `srfuzz_mut_1268`.`t0`.`c1`, `srfuzz_mut_1268`.`t0`.`c2`, `srfuzz_mut_1268`.`t0`.`c3` FROM `srfuzz_mut_1268`.`t0` UNION SELECT `srfuzz_mut_1268`.`t0`.`c0`, `srfuzz_mut_1268`.`t0`.`c1`, `srfuzz_mut_1268`.`t0`.`c2`, `srfuzz_mut_1268`.`t0`.`c3` FROM `srfuzz_mut_1268`.`t0`) `t0`;
SELECT percentile_approx(`srfuzz_mut_1268`.`t0`.`c0`, CAST(NULL AS DOUBLE)) AS `percentile_approx(c0, CAST(NULL AS DOUBLE))` FROM `srfuzz_mut_1268`.`t0`;
SELECT percentile_approx(`srfuzz_mut_1268`.`t0`.`c0`, CAST(NULL AS DOUBLE)) AS `percentile_approx(c0, CAST(NULL AS DOUBLE))` FROM `srfuzz_mut_1268`.`t0`;
SELECT percentile_approx(`srfuzz_mut_1268`.`t0`.`c0`, `srfuzz_mut_1268`.`t0`.`c0`) AS `percentile_approx(c0, srfuzz_mut_1268.t0.c0)` FROM `srfuzz_mut_1268`.`t0`;
SELECT percentile_approx(`srfuzz_mut_1268`.`t0`.`c0`, CAST(NULL AS DOUBLE)) AS `percentile_approx(c0, CAST(NULL AS DOUBLE))` FROM `srfuzz_mut_1268`.`t0`;
SELECT percentile_approx(`t0`.`c0`, CAST(NULL AS DOUBLE)) AS `percentile_approx(c0, CAST(NULL AS DOUBLE))` FROM (SELECT `srfuzz_mut_1268`.`t0`.`c0`, `srfuzz_mut_1268`.`t0`.`c1`, `srfuzz_mut_1268`.`t0`.`c2`, `srfuzz_mut_1268`.`t0`.`c3` FROM `srfuzz_mut_1268`.`t0` UNION ALL SELECT `srfuzz_mut_1268`.`t0`.`c0`, `srfuzz_mut_1268`.`t0`.`c1`, `srfuzz_mut_1268`.`t0`.`c2`, `srfuzz_mut_1268`.`t0`.`c3` FROM `srfuzz_mut_1268`.`t0`) `t0`;
SELECT percentile_approx(CAST(NULL AS DOUBLE), CAST(NULL AS DOUBLE)) AS `percentile_approx(CAST(NULL AS DOUBLE), CAST(NULL AS DOUBLE))` FROM `srfuzz_mut_1268`.`t0`;
SELECT percentile_approx(`srfuzz_mut_1268`.`t0`.`c0`, CAST(NULL AS DOUBLE)) AS `percentile_approx(c0, CAST(NULL AS DOUBLE))` FROM `srfuzz_mut_1268`.`t0` GROUP BY `srfuzz_mut_1268`.`t0`.`c0`;
SELECT percentile_approx(`srfuzz_mut_1268`.`t0`.`c0`, CAST(NULL AS DOUBLE)) AS `percentile_approx(c0, CAST(NULL AS DOUBLE))` FROM `srfuzz_mut_1268`.`t0` LIMIT 1;
SELECT percentile_approx(`srfuzz_mut_1268`.`t0`.`c0`, CAST(NULL AS DOUBLE)) AS `percentile_approx(c0, CAST(NULL AS DOUBLE))` FROM `srfuzz_mut_1268`.`t0`;
SELECT percentile_approx(`srfuzz_mut_1268`.`t0`.`c0`, CAST(NULL AS DOUBLE)) AS `percentile_approx(c0, CAST(NULL AS DOUBLE))` FROM `srfuzz_mut_1268`.`t0` LIMIT 100;
SELECT percentile_approx(`srfuzz_mut_1268`.`t0`.`c0`, `srfuzz_mut_1268`.`t0`.`c0`) AS `percentile_approx(c0, srfuzz_mut_1268.t0.c0)` FROM `srfuzz_mut_1268`.`t0`;
SELECT percentile_approx(`t0`.`c0`, CAST(NULL AS DOUBLE)) AS `percentile_approx(c0, CAST(NULL AS DOUBLE))` FROM (SELECT `srfuzz_mut_1268`.`t0`.`c0`, `srfuzz_mut_1268`.`t0`.`c1`, `srfuzz_mut_1268`.`t0`.`c2`, `srfuzz_mut_1268`.`t0`.`c3` FROM `srfuzz_mut_1268`.`t0` EXCEPT SELECT `srfuzz_mut_1268`.`t0`.`c0`, `srfuzz_mut_1268`.`t0`.`c1`, `srfuzz_mut_1268`.`t0`.`c2`, `srfuzz_mut_1268`.`t0`.`c3` FROM `srfuzz_mut_1268`.`t0`) `t0`;
SELECT percentile_approx(`t0`.`c0`, CAST(NULL AS DOUBLE)) AS `percentile_approx(c0, CAST(NULL AS DOUBLE))` FROM (SELECT `srfuzz_mut_1268`.`t0`.`c0`, `srfuzz_mut_1268`.`t0`.`c1`, `srfuzz_mut_1268`.`t0`.`c2`, `srfuzz_mut_1268`.`t0`.`c3` FROM `srfuzz_mut_1268`.`t0` UNION SELECT `srfuzz_mut_1268`.`t0`.`c0`, `srfuzz_mut_1268`.`t0`.`c1`, `srfuzz_mut_1268`.`t0`.`c2`, `srfuzz_mut_1268`.`t0`.`c3` FROM `srfuzz_mut_1268`.`t0`) `t0`;
SELECT `srfuzz_mut_1268`.`pk1`.`c0`, `srfuzz_mut_1268`.`pk1`.`dt` FROM `srfuzz_mut_1268`.`pk1` ORDER BY `srfuzz_mut_1268`.`pk1`.`c0` ASC;
SELECT `srfuzz_mut_1268`.`pk1`.`c0`, `srfuzz_mut_1268`.`pk1`.`dt` FROM `srfuzz_mut_1268`.`pk1` LIMIT 1, 100;
SELECT `srfuzz_mut_1268`.`pk1`.`c0`, `srfuzz_mut_1268`.`pk1`.`dt` FROM `srfuzz_mut_1268`.`pk1` LIMIT 1, 5;
SELECT `srfuzz_mut_1268`.`pk1`.`c0`, `srfuzz_mut_1268`.`pk1`.`dt` FROM `srfuzz_mut_1268`.`pk1` ORDER BY `srfuzz_mut_1268`.`pk1`.`c0` ASC;
SELECT `pk1`.`c0`, `pk1`.`dt` FROM (SELECT `srfuzz_mut_1268`.`pk1`.`c0`, `srfuzz_mut_1268`.`pk1`.`dt` FROM `srfuzz_mut_1268`.`pk1` UNION SELECT `srfuzz_mut_1268`.`pk1`.`c0`, `srfuzz_mut_1268`.`pk1`.`dt` FROM `srfuzz_mut_1268`.`pk1`) `pk1`;
SELECT `srfuzz_mut_1268`.`pk1`.`c0`, `srfuzz_mut_1268`.`pk1`.`dt` FROM `srfuzz_mut_1268`.`pk1` WHERE @var2;
SELECT `srfuzz_mut_1268`.`pk1`.`c0`, `srfuzz_mut_1268`.`pk1`.`dt` FROM `srfuzz_mut_1268`.`pk1` ORDER BY `srfuzz_mut_1268`.`pk1`.`c0` ASC;
SELECT `pk1`.`c0`, `pk1`.`dt`, `srfuzz_n1`.`e` FROM (SELECT `srfuzz_mut_1268`.`pk1`.`c0`, `srfuzz_mut_1268`.`pk1`.`dt` FROM `srfuzz_mut_1268`.`pk1`) `pk1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_1268`.`pk1`.`c0`, `srfuzz_mut_1268`.`pk1`.`dt` FROM `srfuzz_mut_1268`.`pk1`) SELECT `pk1`.`c0`, `pk1`.`dt` FROM `srfuzz_n1` AS pk1;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_1268`.`pk1`.`c0`, `srfuzz_mut_1268`.`pk1`.`dt` FROM `srfuzz_mut_1268`.`pk1`) SELECT `pk1`.`c0`, `pk1`.`dt` FROM `srfuzz_n1` AS pk1;
SELECT `srfuzz_mut_1268`.`pk1`.`c0`, `srfuzz_mut_1268`.`pk1`.`dt` FROM `srfuzz_mut_1268`.`pk1` LIMIT 100;
SELECT `srfuzz_mut_1268`.`pk1`.`c0`, `srfuzz_mut_1268`.`pk1`.`dt` FROM `srfuzz_mut_1268`.`pk1` WHERE NULL;
SELECT `pk1`.`c0`, `pk1`.`dt` FROM (SELECT `srfuzz_mut_1268`.`pk1`.`c0`, `srfuzz_mut_1268`.`pk1`.`dt` FROM `srfuzz_mut_1268`.`pk1` UNION ALL SELECT `srfuzz_mut_1268`.`pk1`.`c0`, `srfuzz_mut_1268`.`pk1`.`dt` FROM `srfuzz_mut_1268`.`pk1`) `pk1`;
SELECT `srfuzz_mut_1268`.`pk1`.`c0`, `srfuzz_mut_1268`.`pk1`.`dt` FROM `srfuzz_mut_1268`.`pk1` ORDER BY `srfuzz_mut_1268`.`pk1`.`c0` DESC NULLS FIRST;
SELECT `pk1`.`c0`, `pk1`.`dt`, `srfuzz_n1`.`e` FROM (SELECT `srfuzz_mut_1268`.`pk1`.`c0`, `srfuzz_mut_1268`.`pk1`.`dt` FROM `srfuzz_mut_1268`.`pk1`) `pk1` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_1268`.`pk1`.`c0`, `srfuzz_mut_1268`.`pk1`.`dt` FROM `srfuzz_mut_1268`.`pk1`) SELECT `pk1`.`c0`, `pk1`.`dt` FROM `srfuzz_n1` AS pk1;
SELECT `srfuzz_mut_1268`.`pk1`.`c0`, `srfuzz_mut_1268`.`pk1`.`dt` FROM `srfuzz_mut_1268`.`pk1` LIMIT 7, 1;
SELECT DISTINCT `srfuzz_mut_1268`.`pk1`.`c0`, `srfuzz_mut_1268`.`pk1`.`dt` FROM `srfuzz_mut_1268`.`pk1`;