SELECT '=== Test 1: Basic Type <-> VARIANT Bidirectional Casting ===' AS `test_section`;
SELECT '=== Test 3: VARIANT -> STRUCT Casting ===' AS `test_section`;
SELECT '=== Test 5: VARIANT -> ARRAY Casting ===' AS `test_section`;
SELECT '=== Test 7: VARIANT -> MAP Casting ===' AS `test_section`;
SELECT '=== Test 8: Deep Nested VARIANT Path Extraction ===' AS `test_section`;
SELECT '=== Test 9: Bidirectional Roundtrip Validation ===' AS `test_section`;
SELECT '=== Test 1: Basic Type <-> VARIANT Bidirectional Casting ===' AS `test_section` GROUP BY '=== Test 1: Basic Type <-> VARIANT Bidirectional Casting ===';
SELECT min('=== Test 1: Basic Type <-> VARIANT Bidirectional Casting ===') OVER () AS `test_section`;
SELECT '=== Test 1: Basic Type <-> VARIANT Bidirectional Casting ===' AS `test_section` LIMIT 1;
SELECT count('=== Test 1: Basic Type <-> VARIANT Bidirectional Casting ===') OVER () AS `test_section`;
SELECT '=== Test 1: Basic Type <-> VARIANT Bidirectional Casting ===' AS `test_section` GROUP BY '=== Test 1: Basic Type <-> VARIANT Bidirectional Casting ===';
SELECT '=== Test 1: Basic Type <-> VARIANT Bidirectional Casting ===' AS `test_section` GROUP BY '=== Test 1: Basic Type <-> VARIANT Bidirectional Casting ===';
SELECT '=== Test 1: Basic Type <-> VARIANT Bidirectional Casting ===' AS `test_section` LIMIT 2;
SELECT '=== Test 1: Basic Type <-> VARIANT Bidirectional Casting ===' AS `test_section` ORDER BY '=== Test 1: Basic Type <-> VARIANT Bidirectional Casting ===' DESC;
SELECT CAST('=== Test 1: Basic Type <-> VARIANT Bidirectional Casting ===' AS ARRAY<ARRAY<INT>>) AS `test_section`;
SELECT '=== Test 3: VARIANT -> STRUCT Casting ===' AS `test_section` WHERE '=== Test 9: Bidirectional Roundtrip Validation ===';
SELECT '=== Test 3: VARIANT -> STRUCT Casting ===' AS `test_section` WHERE '=== Test 7: VARIANT -> MAP Casting ===';
SELECT '=== Test 3: VARIANT -> STRUCT Casting ===' AS `test_section` ORDER BY '=== Test 3: VARIANT -> STRUCT Casting ===' ASC;
SELECT '=== Test 3: VARIANT -> STRUCT Casting ===' AS `test_section` LIMIT 1, 2;
SELECT '=== Test 3: VARIANT -> STRUCT Casting ===' AS `test_section` GROUP BY '=== Test 3: VARIANT -> STRUCT Casting ===';
SELECT CAST('=== Test 3: VARIANT -> STRUCT Casting ===' AS TIME) AS `test_section`;
SELECT max('=== Test 3: VARIANT -> STRUCT Casting ===') OVER () AS `test_section`;
SELECT '=== Test 3: VARIANT -> STRUCT Casting ===' AS `test_section` WHERE '=== Test 5: VARIANT -> ARRAY Casting ===';
SELECT DISTINCT '=== Test 3: VARIANT -> STRUCT Casting ===' AS `test_section`;
SELECT '=== Test 3: VARIANT -> STRUCT Casting ===' AS `test_section` GROUP BY '=== Test 3: VARIANT -> STRUCT Casting ===';
SELECT '=== Test 5: VARIANT -> ARRAY Casting ===' AS `test_section` LIMIT 7, 2;
SELECT CAST('=== Test 5: VARIANT -> ARRAY Casting ===' AS JSON)->'k' AS `test_section`;
SELECT '=== Test 5: VARIANT -> ARRAY Casting ===' AS `test_section` LIMIT 7, 1;
SELECT avg('=== Test 5: VARIANT -> ARRAY Casting ===') OVER () AS `test_section`;
SELECT '=== Test 5: VARIANT -> ARRAY Casting ===' AS `test_section` GROUP BY '=== Test 5: VARIANT -> ARRAY Casting ===';
SELECT DISTINCT '=== Test 5: VARIANT -> ARRAY Casting ===' AS `test_section`;
SELECT '=== Test 5: VARIANT -> ARRAY Casting ===' AS `test_section` LIMIT 7, 1;
SELECT avg('=== Test 5: VARIANT -> ARRAY Casting ===') OVER () AS `test_section`;
SELECT '=== Test 5: VARIANT -> ARRAY Casting ===' AS `test_section` ORDER BY '=== Test 5: VARIANT -> ARRAY Casting ===' DESC;
SELECT '=== Test 5: VARIANT -> ARRAY Casting ===' AS `test_section` WHERE '=== Test 9: Bidirectional Roundtrip Validation ===';
SELECT '=== Test 5: VARIANT -> ARRAY Casting ===' AS `test_section` ORDER BY '=== Test 5: VARIANT -> ARRAY Casting ===' DESC;
SELECT '=== Test 5: VARIANT -> ARRAY Casting ===' AS `test_section` LIMIT 7, 5;
SELECT DISTINCT '=== Test 5: VARIANT -> ARRAY Casting ===' AS `test_section`;
SELECT '=== Test 5: VARIANT -> ARRAY Casting ===' AS `test_section` WHERE '=== Test 5: VARIANT -> ARRAY Casting ===';
SELECT '=== Test 5: VARIANT -> ARRAY Casting ===' AS `test_section` WHERE '=== Test 7: VARIANT -> MAP Casting ===';
SELECT '=== Test 7: VARIANT -> MAP Casting ===' AS `test_section` WHERE '=== Test 1: Basic Type <-> VARIANT Bidirectional Casting ===';
SELECT DISTINCT '=== Test 7: VARIANT -> MAP Casting ===' AS `test_section`;
SELECT '=== Test 7: VARIANT -> MAP Casting ===' AS `test_section` ORDER BY '=== Test 7: VARIANT -> MAP Casting ===' DESC;
SELECT '=== Test 7: VARIANT -> MAP Casting ===' AS `test_section` ORDER BY '=== Test 7: VARIANT -> MAP Casting ===' DESC NULLS FIRST;
SELECT '=== Test 7: VARIANT -> MAP Casting ===' AS `test_section` LIMIT 100;
SELECT CAST('=== Test 7: VARIANT -> MAP Casting ===' AS VARCHAR) AS `test_section`;
SELECT '=== Test 7: VARIANT -> MAP Casting ===' AS `test_section` GROUP BY '=== Test 7: VARIANT -> MAP Casting ===';
SELECT '=== Test 7: VARIANT -> MAP Casting ===' AS `test_section` ORDER BY '=== Test 7: VARIANT -> MAP Casting ===' DESC;
SELECT '=== Test 8: Deep Nested VARIANT Path Extraction ===' AS `test_section` WHERE '=== Test 9: Bidirectional Roundtrip Validation ===';
SELECT '=== Test 8: Deep Nested VARIANT Path Extraction ===' AS `test_section` LIMIT 2;
SELECT DISTINCT '=== Test 8: Deep Nested VARIANT Path Extraction ===' AS `test_section`;
SELECT DISTINCT '=== Test 8: Deep Nested VARIANT Path Extraction ===' AS `test_section`;
SELECT sum('=== Test 8: Deep Nested VARIANT Path Extraction ===') OVER () AS `test_section`;
SELECT get_json_string(CAST('=== Test 8: Deep Nested VARIANT Path Extraction ===' AS JSON), '$.a') AS `test_section`;
SELECT min('=== Test 8: Deep Nested VARIANT Path Extraction ===') OVER () AS `test_section`;
SELECT max('=== Test 8: Deep Nested VARIANT Path Extraction ===') OVER () AS `test_section`;
SELECT DISTINCT '=== Test 8: Deep Nested VARIANT Path Extraction ===' AS `test_section`;
SELECT CAST((CAST('=== Test 8: Deep Nested VARIANT Path Extraction ===' AS LARGEINT)) AS DATE) AS `test_section`;
SELECT min('=== Test 9: Bidirectional Roundtrip Validation ===') OVER () AS `test_section`;
SELECT '=== Test 9: Bidirectional Roundtrip Validation ===' AS `test_section` LIMIT 1, 1;
SELECT DISTINCT '=== Test 9: Bidirectional Roundtrip Validation ===' AS `test_section`;
SELECT DISTINCT '=== Test 9: Bidirectional Roundtrip Validation ===' AS `test_section`;
SELECT '=== Test 9: Bidirectional Roundtrip Validation ===' AS `test_section` LIMIT 7, 0;
SELECT '=== Test 9: Bidirectional Roundtrip Validation ===' AS `test_section` ORDER BY '=== Test 9: Bidirectional Roundtrip Validation ===' ASC;
SELECT '=== Test 9: Bidirectional Roundtrip Validation ===' AS `test_section` ORDER BY '=== Test 9: Bidirectional Roundtrip Validation ===' DESC;
SELECT '=== Test 9: Bidirectional Roundtrip Validation ===' AS `test_section` LIMIT 2;
SELECT '=== Test 9: Bidirectional Roundtrip Validation ===' AS `test_section` GROUP BY '=== Test 9: Bidirectional Roundtrip Validation ===';
SELECT json_length(CAST('=== Test 9: Bidirectional Roundtrip Validation ===' AS JSON)) AS `test_section`;
SELECT '=== Test 9: Bidirectional Roundtrip Validation ===' AS `test_section` WHERE '=== Test 8: Deep Nested VARIANT Path Extraction ===';
SELECT '=== Test 9: Bidirectional Roundtrip Validation ===' AS `test_section` GROUP BY '=== Test 9: Bidirectional Roundtrip Validation ===';