SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c1`) AS `count(DISTINCT c1)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT c3)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT srfuzz_mut_13.t0.c0)` FROM `srfuzz_mut_13`.`t0`;
SELECT get_json_string(CAST((count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`)) AS JSON), '$.a') AS `get_json_string(CAST((count(DISTINCT c0)) AS JSON), '$.a')` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0` LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `t0`.`c0`) AS `count(DISTINCT c0)` FROM (SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0` UNION SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0`) `t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `t0`.`c0`) AS `count(DISTINCT c0)` FROM (SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0` UNION SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0`) `t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0` HAVING (count(*)) > 0;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT srfuzz_mut_13.t0.c0)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0` ORDER BY count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) DESC;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT srfuzz_mut_13.t0.c2)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c1`) AS `count(DISTINCT srfuzz_mut_13.t0.c1)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `t0`.`c0`) AS `count(DISTINCT c0)` FROM (SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0`) `t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT srfuzz_mut_13.t0.c0)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT srfuzz_mut_13.t0.c2)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT srfuzz_mut_13.t0.c0)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT c3)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c1`) AS `count(DISTINCT c1)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c1`) AS `count(DISTINCT c1)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c1`) AS `count(DISTINCT c1)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c1`) AS `count(DISTINCT srfuzz_mut_13.t0.c1)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c1`) AS `count(DISTINCT c1)` FROM `srfuzz_mut_13`.`t0` WHERE `srfuzz_mut_13`.`t0`.`c3`;
SELECT count(DISTINCT `t0`.`c1`) AS `count(DISTINCT c1)` FROM (SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0` UNION SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0`) `t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c1`) AS `count(DISTINCT srfuzz_mut_13.t0.c1)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c1`) AS `count(DISTINCT c1)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c1`) AS `count(DISTINCT srfuzz_mut_13.t0.c1)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c1`) AS `count(DISTINCT c1)` FROM `srfuzz_mut_13`.`t0` WHERE `srfuzz_mut_13`.`t0`.`c1`;
SELECT count(DISTINCT `t0`.`c1`) AS `count(DISTINCT c1)` FROM (SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0` UNION ALL SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0`) `t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c1`) AS `count(DISTINCT c1)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c1`) AS `count(DISTINCT c1)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c1`) AS `count(DISTINCT c1)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c1`) AS `count(DISTINCT srfuzz_mut_13.t0.c1)` FROM `srfuzz_mut_13`.`t0`;
SELECT json_length(CAST((count(DISTINCT `srfuzz_mut_13`.`t0`.`c1`)) AS JSON)) AS `json_length(CAST((count(DISTINCT c1)) AS JSON))` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c1`) AS `count(DISTINCT c1)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `t0`.`c2`) AS `count(DISTINCT c2)` FROM (SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0` UNION SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0`) `t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `t0`.`c2`) AS `count(DISTINCT c2)` FROM (SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0` UNION SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0`) `t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT srfuzz_mut_13.t0.c2)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT srfuzz_mut_13.t0.c2)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `t0`.`c2`) AS `count(DISTINCT c2)` FROM (SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0` INTERSECT SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0`) `t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT srfuzz_mut_13.t0.c2)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `t0`.`c2`) AS `count(DISTINCT c2)` FROM (SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0`) `t0` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT srfuzz_mut_13.t0.c2)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `t0`.`c2`) AS `count(DISTINCT c2)` FROM (SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0` INTERSECT SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0`) `t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT srfuzz_mut_13.t0.c2)` FROM `srfuzz_mut_13`.`t0`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0`) SELECT count(DISTINCT `t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_n1` AS t0;
SELECT json_length(CAST((count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`)) AS JSON)) AS `json_length(CAST((count(DISTINCT c2)) AS JSON))` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `t0`.`c2`) AS `count(DISTINCT c2)` FROM (SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0` UNION ALL SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0`) `t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0` LIMIT 5;
SELECT count(DISTINCT `t0`.`c2`) AS `count(DISTINCT c2)` FROM (SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0`) `t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT c3)` FROM `srfuzz_mut_13`.`t0` LIMIT 2;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT c3)` FROM `srfuzz_mut_13`.`t0` LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT c3)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `t0`.`c3`) AS `count(DISTINCT c3)` FROM (SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0`) `t0` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`);
SELECT json_length(CAST((count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`)) AS JSON)) AS `json_length(CAST((count(DISTINCT c3)) AS JSON))` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT c3)` FROM `srfuzz_mut_13`.`t0` HAVING (count(*)) > 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT srfuzz_mut_13.t0.c3)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT c3)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT json_length(CAST(`srfuzz_mut_13`.`t0`.`c3` AS JSON))) AS `count(DISTINCT json_length(CAST(c3 AS JSON)))` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT c3)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT srfuzz_mut_13.t0.c3)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT srfuzz_mut_13.t0.c3)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT srfuzz_mut_13.t0.c3)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `t0`.`c3`) AS `count(DISTINCT c3)` FROM (SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0` INTERSECT SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0`) `t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT c3)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `t0`.`c3`) AS `count(DISTINCT c3)` FROM (SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0` INTERSECT SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0`) `t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT srfuzz_mut_13.t0.c3)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT srfuzz_mut_13.t0.c3)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT c3)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT c3)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `t0`.`c3`) AS `count(DISTINCT c3)` FROM (SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0` UNION ALL SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0`) `t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT c3)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT srfuzz_mut_13.t0.c3)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT srfuzz_mut_13.t0.c3)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT c3)` FROM `srfuzz_mut_13`.`t0` WHERE `srfuzz_mut_13`.`t0`.`c2`;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0`) SELECT count(DISTINCT `t0`.`c3`) AS `count(DISTINCT c3)` FROM `srfuzz_n1` AS t0;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT c3)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT c3)` FROM `srfuzz_mut_13`.`t0`;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT c3)` FROM `srfuzz_mut_13`.`t0` HAVING (count(*)) < 10;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0` WHERE `srfuzz_mut_13`.`t0`.`c3` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT DISTINCT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT srfuzz_mut_13.t0.c2)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT srfuzz_mut_13.t0.c0)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT count(DISTINCT `t0`.`c0`) AS `count(DISTINCT c0)` FROM (SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0` UNION SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0`) `t0` GROUP BY `t0`.`c2` ORDER BY `t0`.`c2` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT DISTINCT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT count(DISTINCT `t0`.`c0`) AS `count(DISTINCT c0)` FROM (SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0`) `t0` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  GROUP BY `t0`.`c2` ORDER BY `t0`.`c2` ASC  LIMIT 1;
SELECT count(DISTINCT CAST((CAST((CAST(`srfuzz_mut_13`.`t0`.`c0` AS JSON)) AS DECIMAL128(38,37))) AS DECIMAL64(1,0))) AS `count(DISTINCT CAST((CAST((CAST(c0 AS JSON)) AS DECIMAL128(38,37))) AS DECIMAL64(1,0)))` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT count(DISTINCT `t0`.`c0`) AS `count(DISTINCT c0)` FROM (SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0` EXCEPT SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0`) `t0` GROUP BY `t0`.`c2` ORDER BY `t0`.`c2` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT srfuzz_mut_13.t0.c2)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` HAVING (count(*)) < 10 ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT DISTINCT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0` WHERE `srfuzz_mut_13`.`t0`.`c2` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT srfuzz_mut_13.t0.c2)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT srfuzz_mut_13.t0.c2)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT CAST((count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`)) AS JSON)->'$.a' AS `CAST((count(DISTINCT c0)) AS JSON)->'$.a'` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c2` ORDER BY `srfuzz_mut_13`.`t0`.`c2` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT srfuzz_mut_13.t0.c2)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT srfuzz_mut_13.t0.c2)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` HAVING (count(*)) > 0 ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT srfuzz_mut_13.t0.c3)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT srfuzz_mut_13.t0.c3)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` HAVING (count(*)) < 10 ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT srfuzz_mut_13.t0.c3)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT srfuzz_mut_13.t0.c3)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0` WHERE `srfuzz_mut_13`.`t0`.`c1` GROUP BY `srfuzz_mut_13`.`t0`.`c3` ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT srfuzz_mut_13.t0.c3)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT srfuzz_mut_13.t0.c3)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT srfuzz_mut_13.t0.c3)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `t0`.`c2`) AS `count(DISTINCT c2)` FROM (SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0` UNION ALL SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0`) `t0` GROUP BY `t0`.`c3` ORDER BY `t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT srfuzz_mut_13.t0.c3)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT srfuzz_mut_13.t0.c2)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c0`) AS `count(DISTINCT c0)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c3`) AS `count(DISTINCT c3)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `srfuzz_mut_13`.`t0`.`c2`) AS `count(DISTINCT c2)` FROM `srfuzz_mut_13`.`t0` GROUP BY `srfuzz_mut_13`.`t0`.`c3` ORDER BY `srfuzz_mut_13`.`t0`.`c3` ASC  LIMIT 1;
SELECT count(DISTINCT `t0`.`c2`) AS `count(DISTINCT c2)` FROM (SELECT `srfuzz_mut_13`.`t0`.`c0`, `srfuzz_mut_13`.`t0`.`c1`, `srfuzz_mut_13`.`t0`.`c2`, `srfuzz_mut_13`.`t0`.`c3` FROM `srfuzz_mut_13`.`t0`) `t0` , LATERAL generate_series(1,3,1) srfuzz_n1(`e`)  GROUP BY `t0`.`c3` ORDER BY `t0`.`c3` ASC  LIMIT 1;