SELECT `srfuzz_mut_95`.`t`.`c0` FROM `srfuzz_mut_95`.`t` ORDER BY `srfuzz_mut_95`.`t`.`c0` ASC;
SELECT `t`.`c0` FROM (SELECT `srfuzz_mut_95`.`t`.`c0` FROM `srfuzz_mut_95`.`t`) `t` ORDER BY `t`.`c0` ASC;
SELECT `srfuzz_mut_95`.`t`.`c0` FROM `srfuzz_mut_95`.`t`;
SELECT `srfuzz_mut_95`.`t`.`c0` FROM `srfuzz_mut_95`.`t`;
SELECT `srfuzz_mut_95`.`t`.`c0` FROM `srfuzz_mut_95`.`t` WHERE `srfuzz_mut_95`.`t`.`c0` ORDER BY `srfuzz_mut_95`.`t`.`c0` ASC;
SELECT `srfuzz_mut_95`.`t`.`c0` FROM `srfuzz_mut_95`.`t` WHERE `srfuzz_mut_95`.`t`.`c0` ORDER BY `srfuzz_mut_95`.`t`.`c0` ASC;
SELECT `srfuzz_mut_95`.`t`.`c0` FROM `srfuzz_mut_95`.`t`;
SELECT `srfuzz_mut_95`.`t`.`c0` FROM `srfuzz_mut_95`.`t` WHERE `srfuzz_mut_95`.`t`.`c0` ORDER BY `srfuzz_mut_95`.`t`.`c0` ASC;
SELECT `srfuzz_mut_95`.`t`.`c0` FROM `srfuzz_mut_95`.`t` ORDER BY `srfuzz_mut_95`.`t`.`c0` ASC  LIMIT 7, 1;
SELECT `srfuzz_mut_95`.`t`.`c0` FROM `srfuzz_mut_95`.`t` ORDER BY `srfuzz_mut_95`.`t`.`c0` ASC  LIMIT 1, 2;
SELECT `srfuzz_mut_95`.`t`.`c0` FROM `srfuzz_mut_95`.`t` WHERE `srfuzz_mut_95`.`t`.`c0` ORDER BY `srfuzz_mut_95`.`t`.`c0` ASC;
SELECT `srfuzz_mut_95`.`t`.`c0` FROM `srfuzz_mut_95`.`t` WHERE `srfuzz_mut_95`.`t`.`c0` ORDER BY `srfuzz_mut_95`.`t`.`c0` ASC;
SELECT `srfuzz_mut_95`.`t`.`c0` FROM `srfuzz_mut_95`.`t`;
SELECT `srfuzz_mut_95`.`t`.`c0` FROM `srfuzz_mut_95`.`t` WHERE `srfuzz_mut_95`.`t`.`c0` ORDER BY `srfuzz_mut_95`.`t`.`c0` ASC;
SELECT `t`.`c0` FROM (SELECT `srfuzz_mut_95`.`t`.`c0` FROM `srfuzz_mut_95`.`t` INTERSECT SELECT `srfuzz_mut_95`.`t`.`c0` FROM `srfuzz_mut_95`.`t`) `t` ORDER BY `t`.`c0` ASC;
WITH `srfuzz_n1` AS (SELECT `srfuzz_mut_95`.`t`.`c0` FROM `srfuzz_mut_95`.`t`) SELECT `t`.`c0` FROM `srfuzz_n1` AS t ORDER BY `t`.`c0` ASC;
SELECT `t`.`c0` FROM (SELECT `srfuzz_mut_95`.`t`.`c0` FROM `srfuzz_mut_95`.`t` UNION SELECT `srfuzz_mut_95`.`t`.`c0` FROM `srfuzz_mut_95`.`t`) `t` ORDER BY `t`.`c0` ASC;
SELECT `t`.`c0` FROM (SELECT `srfuzz_mut_95`.`t`.`c0` FROM `srfuzz_mut_95`.`t` EXCEPT SELECT `srfuzz_mut_95`.`t`.`c0` FROM `srfuzz_mut_95`.`t`) `t` ORDER BY `t`.`c0` ASC;
SELECT DISTINCT `srfuzz_mut_95`.`t`.`c0` FROM `srfuzz_mut_95`.`t` ORDER BY `srfuzz_mut_95`.`t`.`c0` ASC;
SELECT `srfuzz_mut_95`.`t`.`c0` FROM `srfuzz_mut_95`.`t` WHERE `srfuzz_mut_95`.`t`.`c0` ORDER BY `srfuzz_mut_95`.`t`.`c0` ASC;
SELECT DISTINCT `srfuzz_mut_95`.`t`.`c0` FROM `srfuzz_mut_95`.`t` ORDER BY `srfuzz_mut_95`.`t`.`c0` ASC;
SELECT DISTINCT `srfuzz_mut_95`.`t`.`c0` FROM `srfuzz_mut_95`.`t` ORDER BY `srfuzz_mut_95`.`t`.`c0` ASC;