SELECT bitmap_to_base64(NULL) AS `bitmap_to_base64(NULL)`;
SELECT bitmap_to_base64(bitmap_from_string('abc')) AS `bitmap_to_base64(bitmap_from_string('abc'))`;
SELECT bitmap_to_base64('0') AS `bitmap_to_base64('0')`;
SELECT bitmap_to_base64(NULL) AS `bitmap_to_base64(NULL)`;
SELECT bitmap_to_base64(NULL) AS `bitmap_to_base64(NULL)`;
SELECT bitmap_to_base64(NULL) AS `bitmap_to_base64(NULL)` ORDER BY bitmap_to_base64(NULL) DESC NULLS FIRST;
SELECT bitmap_to_base64(NULL) AS `bitmap_to_base64(NULL)`;
SELECT bitmap_to_base64(NULL) AS `bitmap_to_base64(NULL)`;
SELECT bitmap_to_base64(NULL) AS `bitmap_to_base64(NULL)`;
SELECT bitmap_to_base64(bitmap_to_base64(NULL)) AS `bitmap_to_base64(bitmap_to_base64(NULL))`;
SELECT bitmap_to_base64(bitmap_to_base64(NULL)) AS `bitmap_to_base64(bitmap_to_base64(NULL))`;
SELECT bitmap_to_base64(NULL) AS `bitmap_to_base64(NULL)` GROUP BY bitmap_to_base64(NULL);
SELECT bitmap_to_base64('0000-00-00') AS `bitmap_to_base64('0000-00-00')`;
SELECT bitmap_to_base64(NULL) AS `bitmap_to_base64(NULL)` GROUP BY bitmap_to_base64(NULL);
SELECT bitmap_to_base64(NULL) AS `bitmap_to_base64(NULL)` GROUP BY bitmap_to_base64(NULL);
SELECT bitmap_to_base64('abc') AS `bitmap_to_base64('abc')`;
SELECT bitmap_to_base64(repeat('x', 65536)) AS `bitmap_to_base64(repeat('x', 65536))`;
SELECT bitmap_to_base64(bitmap_to_base64(NULL)) AS `bitmap_to_base64(bitmap_to_base64(NULL))`;
SELECT bitmap_to_base64(NULL) AS `bitmap_to_base64(NULL)` GROUP BY bitmap_to_base64(NULL);
SELECT bitmap_to_base64('0') AS `bitmap_to_base64('0')`;
SELECT max(bitmap_to_base64(NULL)) OVER () AS `max(bitmap_to_base64(NULL)) OVER ()`;
SELECT bitmap_to_base64('1970-01-01') AS `bitmap_to_base64('1970-01-01')`;
SELECT bitmap_to_base64('%') AS `bitmap_to_base64('%')`;
SELECT bitmap_to_base64(bitmap_to_base64(NULL)) AS `bitmap_to_base64(bitmap_to_base64(NULL))`;
SELECT bitmap_to_base64(NULL) AS `bitmap_to_base64(NULL)` ORDER BY bitmap_to_base64(NULL) ASC;
SELECT bitmap_to_base64(NULL) AS `bitmap_to_base64(NULL)` ORDER BY bitmap_to_base64(NULL) ASC;
SELECT bitmap_to_base64(bitmap_to_base64(NULL)) AS `bitmap_to_base64(bitmap_to_base64(NULL))`;
SELECT bitmap_to_base64('%') AS `bitmap_to_base64('%')`;
SELECT bitmap_to_base64(repeat('x', 65536)) AS `bitmap_to_base64(repeat('x', 65536))`;
SELECT bitmap_to_base64(NULL) AS `bitmap_to_base64(NULL)`;
SELECT max(bitmap_to_base64(NULL)) OVER () AS `max(bitmap_to_base64(NULL)) OVER ()`;
SELECT bitmap_to_base64(bitmap_from_string('abc')) AS `bitmap_to_base64(bitmap_from_string('abc'))` GROUP BY bitmap_to_base64(bitmap_from_string('abc'));
SELECT bitmap_to_base64(bitmap_from_string('abc')) AS `bitmap_to_base64(bitmap_from_string('abc'))` GROUP BY bitmap_to_base64(bitmap_from_string('abc'));
SELECT bitmap_to_base64(bitmap_from_string('0000-00-00')) AS `bitmap_to_base64(bitmap_from_string('0000-00-00'))`;
SELECT bitmap_to_base64(bitmap_from_string(bitmap_to_base64(bitmap_from_string('abc')))) AS `bitmap_to_base64(bitmap_from_string(bitmap_to_base64(bitmap_from_string('abc'))))`;
SELECT bitmap_to_base64(bitmap_from_string('abc')) AS `bitmap_to_base64(bitmap_from_string('abc'))`;
SELECT bitmap_to_base64(bitmap_from_string(TRUE)) AS `bitmap_to_base64(bitmap_from_string(TRUE))`;
SELECT bitmap_to_base64(bitmap_to_base64(bitmap_from_string('abc'))) AS `bitmap_to_base64(bitmap_to_base64(bitmap_from_string('abc')))`;
SELECT bitmap_to_base64(bitmap_from_string(bitmap_to_base64(bitmap_from_string('abc')))) AS `bitmap_to_base64(bitmap_from_string(bitmap_to_base64(bitmap_from_string('abc'))))`;
SELECT bitmap_to_base64(bitmap_from_string('abc')) AS `bitmap_to_base64(bitmap_from_string('abc'))` ORDER BY bitmap_to_base64(bitmap_from_string('abc')) DESC;
SELECT sum(bitmap_to_base64(bitmap_from_string('abc'))) OVER () AS `sum(bitmap_to_base64(bitmap_from_string('abc'))) OVER ()`;
SELECT bitmap_to_base64(bitmap_from_string('abc')) AS `bitmap_to_base64(bitmap_from_string('abc'))`;
SELECT bitmap_to_base64(unhex('abc')) AS `bitmap_to_base64(unhex('abc'))`;
SELECT bitmap_to_base64(bitmap_from_string(NULL)) AS `bitmap_to_base64(bitmap_from_string(NULL))`;
SELECT bitmap_to_base64(bitmap_from_string('0')) AS `bitmap_to_base64(bitmap_from_string('0'))`;
SELECT sum(bitmap_to_base64(bitmap_from_string('abc'))) OVER () AS `sum(bitmap_to_base64(bitmap_from_string('abc'))) OVER ()`;
SELECT DISTINCT bitmap_to_base64(bitmap_from_string('abc')) AS `bitmap_to_base64(bitmap_from_string('abc'))`;
SELECT bitmap_to_base64(bitmap_from_string('abc')) AS `bitmap_to_base64(bitmap_from_string('abc'))` LIMIT 0;
SELECT bitmap_to_base64(bitmap_from_string(bitmap_to_base64(bitmap_from_string('abc')))) AS `bitmap_to_base64(bitmap_from_string(bitmap_to_base64(bitmap_from_string('abc'))))`;
SELECT bitmap_to_base64(bitmap_from_string('abc')) AS `bitmap_to_base64(bitmap_from_string('abc'))` ORDER BY bitmap_to_base64(bitmap_from_string('abc')) DESC;
SELECT bitmap_to_base64('abc') AS `bitmap_to_base64('abc')`;
SELECT bitmap_to_base64(bitmap_from_string(NULL)) AS `bitmap_to_base64(bitmap_from_string(NULL))`;
SELECT bitmap_to_base64(bitmap_from_string(NULL)) AS `bitmap_to_base64(bitmap_from_string(NULL))`;
SELECT bitmap_to_base64(bitmap_from_string('abc')) AS `bitmap_to_base64(bitmap_from_string('abc'))` LIMIT 100;
SELECT bitmap_to_base64('abc') AS `bitmap_to_base64('abc')`;