SELECT regexp_extract_all('bbb', '(a*)', 1) AS `regexp_extract_all('bbb', '(a*)', 1)`;
SELECT regexp_extract_all('a1b2', '(\\d*)', 1) AS `regexp_extract_all('a1b2', '(\\d*)', 1)`;
SELECT regexp_extract_all(`t`.`s`, `t`.`p`, 1) AS `regexp_extract_all(s, p, 1)` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t`;
SELECT regexp_extract_all('bbb', 'a*', 0) AS `regexp_extract_all('bbb', 'a*', 0)`;
SELECT regexp_extract_all('', '(a*)', 1) AS `regexp_extract_all('', '(a*)', 1)`;
SELECT regexp_extract_all('abc', '($)', 1) AS `regexp_extract_all('abc', '($)', 1)`;
SELECT regexp_extract_all('abc', '$', 0) AS `regexp_extract_all('abc', '$', 0)`;
SELECT regexp_extract_all('a1b2c3', '([0-9])', 1) AS `regexp_extract_all('a1b2c3', '([0-9])', 1)`;
SELECT regexp_extract_all('(a*)', '(a*)', 1) AS `regexp_extract_all('(a*)', '(a*)', 1)`;
SELECT regexp_extract_all('(\\d*)', '(a*)', 1) AS `regexp_extract_all('(\\d*)', '(a*)', 1)`;
SELECT regexp_extract_all('bbb', '(a*)', 0.0) AS `regexp_extract_all('bbb', '(a*)', 0.0)`;
SELECT regexp_extract_all('bbb', '(a*)', 1) AS `regexp_extract_all('bbb', '(a*)', 1)` ORDER BY regexp_extract_all('bbb', '(a*)', 1) ASC;
SELECT regexp_extract_all('(a*)', '(a*)', 1) AS `regexp_extract_all('(a*)', '(a*)', 1)`;
SELECT regexp_extract_all('0000-00-00', '(a*)', 1) AS `regexp_extract_all('0000-00-00', '(a*)', 1)`;
SELECT regexp_extract_all('bbb', -9223372036854775808, 1) AS `regexp_extract_all('bbb', -9223372036854775808, 1)`;
SELECT regexp_extract_all('bbb', 'bbb', 1) AS `regexp_extract_all('bbb', 'bbb', 1)`;
SELECT regexp_extract_all('bbb', 0.0, 1) AS `regexp_extract_all('bbb', 0.0, 1)`;
SELECT regexp_extract_all('bbb', '(a*)', 1) AS `regexp_extract_all('bbb', '(a*)', 1)` LIMIT 7, 2;
SELECT regexp_extract_all('bbb', '(a*)', 1) AS `regexp_extract_all('bbb', '(a*)', 1)` GROUP BY regexp_extract_all('bbb', '(a*)', 1);
SELECT regexp_extract_all('bbb', '(a*)', '1970-01-01') AS `regexp_extract_all('bbb', '(a*)', '1970-01-01')`;
SELECT regexp_extract_all(2147483647, '(a*)', 1) AS `regexp_extract_all(2147483647, '(a*)', 1)`;
SELECT regexp_extract_all('bbb', '(a*)', 'bbb') AS `regexp_extract_all('bbb', '(a*)', 'bbb')`;
SELECT regexp_extract_all('bbb', '(a*)', 1) AS `regexp_extract_all('bbb', '(a*)', 1)` LIMIT 100;
SELECT regexp_extract_all(CAST(NULL AS JSON), '(a*)', 1) AS `regexp_extract_all(CAST(NULL AS JSON), '(a*)', 1)`;
SELECT DISTINCT regexp_extract_all('bbb', '(a*)', 1) AS `regexp_extract_all('bbb', '(a*)', 1)`;
SELECT regexp_extract_all('bbb', '(a*)', 1) AS `regexp_extract_all('bbb', '(a*)', 1)`;
SELECT regexp_extract_all('bbb', '(a*)', 1) AS `regexp_extract_all('bbb', '(a*)', 1)` WHERE 'a1b2c3';
SELECT regexp_extract_all('bbb', '(a*)', 1) AS `regexp_extract_all('bbb', '(a*)', 1)` LIMIT 2;
SELECT regexp_extract_all('bbb', -9223372036854775808, 1) AS `regexp_extract_all('bbb', -9223372036854775808, 1)`;
SELECT regexp_extract_all('bbb', '(a*)', 1) AS `regexp_extract_all('bbb', '(a*)', 1)`;
SELECT regexp_extract_all('bbb', '', 1) AS `regexp_extract_all('bbb', '', 1)`;
SELECT regexp_extract_all('bbb', '(a*)', repeat('x', 65536)) AS `regexp_extract_all('bbb', '(a*)', repeat('x', 65536))`;
SELECT regexp_extract_all('bbb', 1, 1) AS `regexp_extract_all('bbb', 1, 1)`;
SELECT regexp_extract_all('bbb', 0.0, 1) AS `regexp_extract_all('bbb', 0.0, 1)`;
SELECT regexp_extract_all('bbb', '(a*)', -2147483648) AS `regexp_extract_all('bbb', '(a*)', -2147483648)`;
SELECT regexp_extract_all('($)', '(a*)', 1) AS `regexp_extract_all('($)', '(a*)', 1)`;
SELECT regexp_extract_all('bbb', '(a*)', 0.0) AS `regexp_extract_all('bbb', '(a*)', 0.0)`;
SELECT regexp_extract_all('a1b2', json_length(CAST('(\\d*)' AS JSON)), 1) AS `regexp_extract_all('a1b2', json_length(CAST('(\\d*)' AS JSON)), 1)`;
SELECT regexp_extract_all('a1b2', 1, 1) AS `regexp_extract_all('a1b2', 1, 1)`;
SELECT regexp_extract_all('a1b2', 'a*', 1) AS `regexp_extract_all('a1b2', 'a*', 1)`;
SELECT regexp_extract_all('a1b2', '(\\d*)', '(\\d*)') AS `regexp_extract_all('a1b2', '(\\d*)', '(\\d*)')`;
SELECT regexp_extract_all('a1b2', '(\\d*)', '0') AS `regexp_extract_all('a1b2', '(\\d*)', '0')`;
SELECT regexp_extract_all(json_query(CAST('a1b2' AS JSON), '$.a'), '(\\d*)', 1) AS `regexp_extract_all(json_query(CAST('a1b2' AS JSON), '$.a'), '(\\d*)', 1)`;
SELECT regexp_extract_all('a1b2', '(\\d*)', 1) AS `regexp_extract_all('a1b2', '(\\d*)', 1)` GROUP BY regexp_extract_all('a1b2', '(\\d*)', 1);
SELECT regexp_extract_all('a1b2', '(\\d*)', 1) AS `regexp_extract_all('a1b2', '(\\d*)', 1)`;
SELECT regexp_extract_all('a1b2', '(\\d*)', 1) AS `regexp_extract_all('a1b2', '(\\d*)', 1)` GROUP BY regexp_extract_all('a1b2', '(\\d*)', 1);
SELECT regexp_extract_all('a1b2', '(\\d*)', 1) AS `regexp_extract_all('a1b2', '(\\d*)', 1)`;
SELECT regexp_extract_all('([0-9])', '(\\d*)', 1) AS `regexp_extract_all('([0-9])', '(\\d*)', 1)`;
SELECT regexp_extract_all('a1b2', '(\\d*)', 1) AS `regexp_extract_all('a1b2', '(\\d*)', 1)`;
SELECT regexp_extract_all('a1b2', '(\\d*)', 'a1b2') AS `regexp_extract_all('a1b2', '(\\d*)', 'a1b2')`;
SELECT regexp_extract_all('a1b2', '(\\d*)', 1) AS `regexp_extract_all('a1b2', '(\\d*)', 1)` LIMIT 1;
SELECT regexp_extract_all('a1b2', '(\\d*)', 1) AS `regexp_extract_all('a1b2', '(\\d*)', 1)` ORDER BY regexp_extract_all('a1b2', '(\\d*)', 1) DESC;
SELECT regexp_extract_all('a1b2', '0', 1) AS `regexp_extract_all('a1b2', '0', 1)`;
SELECT regexp_extract_all('$', '(\\d*)', 1) AS `regexp_extract_all('$', '(\\d*)', 1)`;
SELECT regexp_extract_all(-1.0E308, '(\\d*)', 1) AS `regexp_extract_all(-1.0E308, '(\\d*)', 1)`;
SELECT regexp_extract_all('a1b2', 1, 1) AS `regexp_extract_all('a1b2', 1, 1)`;
SELECT regexp_extract_all('a1b2', '(\\d*)', 1) AS `regexp_extract_all('a1b2', '(\\d*)', 1)`;
SELECT regexp_extract_all('a1b2', '(\\d*)', '9999-12-31 23:59:59') AS `regexp_extract_all('a1b2', '(\\d*)', '9999-12-31 23:59:59')`;
SELECT regexp_extract_all('a1b2', '(\\d*)', 1) AS `regexp_extract_all('a1b2', '(\\d*)', 1)` WHERE '';
SELECT regexp_extract_all('a1b2', '(\\d*)', 1) AS `regexp_extract_all('a1b2', '(\\d*)', 1)` LIMIT 0;
SELECT regexp_extract_all('a1b2', CAST((CAST('(\\d*)' AS DATETIME)) AS VARCHAR), 1) AS `regexp_extract_all('a1b2', CAST((CAST('(\\d*)' AS DATETIME)) AS VARCHAR), 1)`;
SELECT regexp_extract_all('a1b2', '(\\d*)', 'a1b2') AS `regexp_extract_all('a1b2', '(\\d*)', 'a1b2')`;
SELECT regexp_extract_all('a1b2', '(\\d*)', '(\\d*)') AS `regexp_extract_all('a1b2', '(\\d*)', '(\\d*)')`;
SELECT regexp_extract_all('a1b2', '(\\d*)', 1) AS `regexp_extract_all('a1b2', '(\\d*)', 1)`;
SELECT regexp_extract_all('', '(\\d*)', 1) AS `regexp_extract_all('', '(\\d*)', 1)`;
SELECT regexp_extract_all(`t`.`s`, `t`.`p`, 1) AS `regexp_extract_all(t.s, p, 1)` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t`;
SELECT regexp_extract_all(`t`.`s`, `t`.`p`, repeat('x', 65536)) AS `regexp_extract_all(s, p, repeat('x', 65536))` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t`;
SELECT regexp_extract_all(`t`.`s`, `t`.`p`, 1) AS `regexp_extract_all(s, p, 1)` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t` ORDER BY regexp_extract_all(`t`.`s`, `t`.`p`, 1) DESC;
SELECT regexp_extract_all(`t`.`s`, `t`.`p`, '0000-00-00') AS `regexp_extract_all(s, p, '0000-00-00')` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t`;
SELECT regexp_extract_all(`t`.`s`, `t`.`p`, 1) AS `regexp_extract_all(s, p, 1)` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p` LIMIT 5) `t`;
SELECT regexp_extract_all(`t`.`p`, `t`.`p`, 1) AS `regexp_extract_all(p, p, 1)` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t`;
SELECT regexp_extract_all(`t`.`s`, `t`.`p`, 1) AS `regexp_extract_all(s, t.p, 1)` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t`;
SELECT regexp_extract_all(`t`.`s`, `t`.`p`, 1) AS `regexp_extract_all(s, p, 1)` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t`;
SELECT regexp_extract_all(`t`.`s`, `t`.`p`, 1) AS `regexp_extract_all(s, p, 1)` FROM (SELECT `t`.`s`, `t`.`p` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t` UNION SELECT `t`.`s`, `t`.`p` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t`) `t`;
SELECT regexp_extract_all(`t`.`s`, `t`.`p`, 1) AS `regexp_extract_all(s, p, 1)` FROM (SELECT `t`.`s`, `t`.`p` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t`) `t`;
SELECT DISTINCT regexp_extract_all(`t`.`s`, `t`.`p`, 1) AS `regexp_extract_all(s, p, 1)` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t`;
SELECT regexp_extract_all(`t`.`s`, `t`.`p`, 1) AS `regexp_extract_all(s, p, 1)` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p` LIMIT 5) `t`;
SELECT regexp_extract_all(`t`.`s`, `t`.`p`, '1970-01-01') AS `regexp_extract_all(s, p, '1970-01-01')` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t`;
SELECT regexp_extract_all(`t`.`s`, `t`.`p`, 1) AS `regexp_extract_all(s, p, 1)` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t` WHERE 1;
SELECT regexp_extract_all(`t`.`s`, `t`.`p`, NULL) AS `regexp_extract_all(s, p, NULL)` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t`;
SELECT regexp_extract_all(CAST(`t`.`s` AS JSON)->'$.a', `t`.`p`, 1) AS `regexp_extract_all(CAST(s AS JSON)->'$.a', p, 1)` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t`;
SELECT regexp_extract_all(`t`.`s`, `t`.`p`, 1) AS `regexp_extract_all(s, p, 1)` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t`;
SELECT regexp_extract_all(`t`.`s`, `t`.`p`, 1) AS `regexp_extract_all(s, p, 1)` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t` LIMIT 1;
SELECT regexp_extract_all(`t`.`s`, `t`.`p`, 1) AS `regexp_extract_all(s, p, 1)` FROM (SELECT `t`.`s`, `t`.`p` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t` UNION SELECT `t`.`s`, `t`.`p` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t`) `t`;
SELECT regexp_extract_all(`t`.`s`, 'abc', 1) AS `regexp_extract_all(s, 'abc', 1)` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t`;
SELECT row_number() OVER (ORDER BY regexp_extract_all(`t`.`s`, `t`.`p`, 1) ASC ) AS `row_number() OVER (ORDER BY regexp_extract_all(s, p, 1) ASC )` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t`;
SELECT regexp_extract_all(`t`.`s`, `t`.`p`, 1) AS `regexp_extract_all(s, p, 1)` FROM (SELECT `t`.`s`, `t`.`p` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t` EXCEPT SELECT `t`.`s`, `t`.`p` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t`) `t`;
WITH `srfuzz_n1` AS (SELECT `t`.`s`, `t`.`p` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t`) SELECT regexp_extract_all(`t`.`s`, `t`.`p`, 1) AS `regexp_extract_all(s, p, 1)` FROM `srfuzz_n1` AS t;
SELECT regexp_extract_all(`t`.`s`, `t`.`p`, 1) AS `regexp_extract_all(s, p, 1)` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t`;
SELECT regexp_extract_all(`t`.`s`, `t`.`p`, 1) AS `regexp_extract_all(s, t.p, 1)` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t`;
SELECT regexp_extract_all(`t`.`s`, `t`.`s`, 1) AS `regexp_extract_all(s, s, 1)` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t`;
SELECT regexp_extract_all(`t`.`s`, `t`.`p`, 1) AS `regexp_extract_all(s, p, 1)` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t`;
SELECT regexp_extract_all(`t`.`s`, `t`.`p`, 1) AS `regexp_extract_all(s, p, 1)` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t`;
SELECT regexp_extract_all(`t`.`s`, `t`.`p`, 1) AS `regexp_extract_all(s, p, 1)` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p` GROUP BY 'bbb', '(a*)') `t`;
SELECT regexp_extract_all(`t`.`s`, `t`.`p`, 1) AS `regexp_extract_all(s, p, 1)` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t` GROUP BY regexp_extract_all(`t`.`s`, `t`.`p`, 1);
SELECT regexp_extract_all(`t`.`s`, `t`.`p`, 1) AS `regexp_extract_all(s, p, 1)` FROM (SELECT `t`.`s`, `t`.`p` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t` UNION SELECT `t`.`s`, `t`.`p` FROM (SELECT 'bbb' AS `s`, '(a*)' AS `p`) `t`) `t`;
SELECT regexp_extract_all('bbb', 'a*', 0) AS `regexp_extract_all('bbb', 'a*', 0)` ORDER BY regexp_extract_all('bbb', 'a*', 0) ASC NULLS LAST;
SELECT regexp_extract_all('bbb', 'a*', '0') AS `regexp_extract_all('bbb', 'a*', '0')`;
SELECT regexp_extract_all('bbb', 'a*', 0) AS `regexp_extract_all('bbb', 'a*', 0)`;
SELECT regexp_extract_all('bbb', 'a*', 'bbb') AS `regexp_extract_all('bbb', 'a*', 'bbb')`;
SELECT regexp_extract_all('bbb', 'a*', 'bbb') AS `regexp_extract_all('bbb', 'a*', 'bbb')`;
SELECT regexp_extract_all('bbb', 'a*', -2147483648) AS `regexp_extract_all('bbb', 'a*', -2147483648)`;
SELECT regexp_extract_all(-1, 'a*', 0) AS `regexp_extract_all(-1, 'a*', 0)`;
SELECT regexp_extract_all('bbb', 'a*', 0) AS `regexp_extract_all('bbb', 'a*', 0)` GROUP BY regexp_extract_all('bbb', 'a*', 0);
SELECT regexp_extract_all('a*', 'a*', 0) AS `regexp_extract_all('a*', 'a*', 0)`;
SELECT array_sum(regexp_extract_all('bbb', 'a*', 0)) AS `array_sum(regexp_extract_all('bbb', 'a*', 0))`;
SELECT regexp_extract_all('bbb', 'a*', 0) AS `regexp_extract_all('bbb', 'a*', 0)`;
SELECT DISTINCT regexp_extract_all('bbb', 'a*', 0) AS `regexp_extract_all('bbb', 'a*', 0)`;
SELECT regexp_extract_all('bbb', 'a*', 0.0) AS `regexp_extract_all('bbb', 'a*', 0.0)`;
SELECT regexp_extract_all('bbb', 'a*', 0) AS `regexp_extract_all('bbb', 'a*', 0)`;
SELECT regexp_extract_all('bbb', 'a*', 0) AS `regexp_extract_all('bbb', 'a*', 0)`;
SELECT regexp_extract_all('bbb', NULL, 0) AS `regexp_extract_all('bbb', NULL, 0)`;
SELECT regexp_extract_all('bbb', -1.0E308, 0) AS `regexp_extract_all('bbb', -1.0E308, 0)`;
SELECT regexp_extract_all(json_length(CAST('bbb' AS JSON)), 'a*', 0) AS `regexp_extract_all(json_length(CAST('bbb' AS JSON)), 'a*', 0)`;
SELECT regexp_extract_all('bbb', get_json_string(CAST('a*' AS JSON), '$.a'), 0) AS `regexp_extract_all('bbb', get_json_string(CAST('a*' AS JSON), '$.a'), 0)`;
SELECT regexp_extract_all('bbb', 'a*', 0) AS `regexp_extract_all('bbb', 'a*', 0)` LIMIT 0;
SELECT count(regexp_extract_all('bbb', 'a*', 0)) OVER () AS `count(regexp_extract_all('bbb', 'a*', 0)) OVER ()`;
SELECT regexp_extract_all(FALSE, 'a*', 0) AS `regexp_extract_all(FALSE, 'a*', 0)`;
SELECT regexp_extract_all('', '(a*)', '') AS `regexp_extract_all('', '(a*)', '')`;
SELECT regexp_extract_all(0, '(a*)', 1) AS `regexp_extract_all(0, '(a*)', 1)`;
SELECT regexp_extract_all('', '(a*)', 1) AS `regexp_extract_all('', '(a*)', 1)`;
SELECT regexp_extract_all('', '(a*)', 0.0) AS `regexp_extract_all('', '(a*)', 0.0)`;
SELECT DISTINCT regexp_extract_all('', '(a*)', 1) AS `regexp_extract_all('', '(a*)', 1)`;
SELECT regexp_extract_all('', '(a*)', 1) AS `regexp_extract_all('', '(a*)', 1)` GROUP BY regexp_extract_all('', '(a*)', 1);
SELECT DISTINCT regexp_extract_all('', '(a*)', 1) AS `regexp_extract_all('', '(a*)', 1)`;
SELECT regexp_extract_all('', -1, 1) AS `regexp_extract_all('', -1, 1)`;
SELECT regexp_extract_all('', '(a*)', 0.0) AS `regexp_extract_all('', '(a*)', 0.0)`;
SELECT DISTINCT regexp_extract_all('', '(a*)', 1) AS `regexp_extract_all('', '(a*)', 1)`;
SELECT regexp_extract_all('', 1, 1) AS `regexp_extract_all('', 1, 1)`;
SELECT DISTINCT regexp_extract_all('', '(a*)', 1) AS `regexp_extract_all('', '(a*)', 1)`;
SELECT regexp_extract_all('9999-12-31 23:59:59', '(a*)', 1) AS `regexp_extract_all('9999-12-31 23:59:59', '(a*)', 1)`;
SELECT regexp_extract_all('', '(a*)', 1) AS `regexp_extract_all('', '(a*)', 1)` GROUP BY regexp_extract_all('', '(a*)', 1);
SELECT regexp_extract_all('', '', 1) AS `regexp_extract_all('', '', 1)`;
SELECT regexp_extract_all('', '(a*)', 1) AS `regexp_extract_all('', '(a*)', 1)`;
SELECT regexp_extract_all('', '(a*)', '9999-12-31 23:59:59') AS `regexp_extract_all('', '(a*)', '9999-12-31 23:59:59')`;
SELECT regexp_extract_all('', TRUE, 1) AS `regexp_extract_all('', TRUE, 1)`;
SELECT regexp_extract_all('', '(a*)', 1) AS `regexp_extract_all('', '(a*)', 1)` ORDER BY regexp_extract_all('', '(a*)', 1) DESC NULLS FIRST;
SELECT regexp_extract_all('', '(a*)', CAST(NULL AS JSON)) AS `regexp_extract_all('', '(a*)', CAST(NULL AS JSON))`;
SELECT regexp_extract_all('', 1, 1) AS `regexp_extract_all('', 1, 1)`;
SELECT regexp_extract_all('', '(a*)', 1) AS `regexp_extract_all('', '(a*)', 1)` GROUP BY regexp_extract_all('', '(a*)', 1);
SELECT regexp_extract_all('', '(a*)', CAST(1 AS JSON)->'$') AS `regexp_extract_all('', '(a*)', CAST(1 AS JSON)->'$')`;
SELECT regexp_extract_all('', '(a*)', 1) AS `regexp_extract_all('', '(a*)', 1)` LIMIT 100;
SELECT regexp_extract_all('', '', 1) AS `regexp_extract_all('', '', 1)`;
SELECT regexp_extract_all(0.0, '(a*)', 1) AS `regexp_extract_all(0.0, '(a*)', 1)`;
SELECT regexp_extract_all('', '(a*)', 1)[2147483647] AS `regexp_extract_all('', '(a*)', 1)[2147483647]`;
SELECT regexp_extract_all('', '', 1) AS `regexp_extract_all('', '', 1)`;
SELECT DISTINCT regexp_extract_all('abc', '($)', 1) AS `regexp_extract_all('abc', '($)', 1)`;
SELECT regexp_extract_all('abc', CAST((CAST('($)' AS DOUBLE)) AS TINYINT), 1) AS `regexp_extract_all('abc', CAST((CAST('($)' AS DOUBLE)) AS TINYINT), 1)`;
SELECT regexp_extract_all(0.0, '($)', 1) AS `regexp_extract_all(0.0, '($)', 1)`;
SELECT regexp_extract_all('%', '($)', 1) AS `regexp_extract_all('%', '($)', 1)`;
SELECT array_length(regexp_extract_all('abc', '($)', 1)) AS `array_length(regexp_extract_all('abc', '($)', 1))`;
SELECT regexp_extract_all('abc', 1, 1) AS `regexp_extract_all('abc', 1, 1)`;
SELECT regexp_extract_all('abc', '($)', '') AS `regexp_extract_all('abc', '($)', '')`;
SELECT regexp_extract_all('abc', '($)', 1) AS `regexp_extract_all('abc', '($)', 1)`;
SELECT regexp_extract_all('abc', '($)', 1) AS `regexp_extract_all('abc', '($)', 1)`;
SELECT regexp_extract_all('abc', '($)', 'abc') AS `regexp_extract_all('abc', '($)', 'abc')`;
SELECT regexp_extract_all('abc', 1, 1) AS `regexp_extract_all('abc', 1, 1)`;
SELECT regexp_extract_all('abc', '($)', 1) AS `regexp_extract_all('abc', '($)', 1)`;
SELECT regexp_extract_all('abc', '($)', 1) AS `regexp_extract_all('abc', '($)', 1)`;
SELECT regexp_extract_all('abc', -1, 1) AS `regexp_extract_all('abc', -1, 1)`;
SELECT regexp_extract_all('abc', '($)', 1) AS `regexp_extract_all('abc', '($)', 1)`;
SELECT regexp_extract_all('abc', '($)', 1) AS `regexp_extract_all('abc', '($)', 1)`;
SELECT DISTINCT regexp_extract_all('abc', '($)', 1) AS `regexp_extract_all('abc', '($)', 1)`;
SELECT regexp_extract_all(repeat('x', 65536), '($)', 1) AS `regexp_extract_all(repeat('x', 65536), '($)', 1)`;
SELECT regexp_extract_all('abc', '($)', '1970-01-01') AS `regexp_extract_all('abc', '($)', '1970-01-01')`;
SELECT regexp_extract_all('9999-12-31 23:59:59', '($)', 1) AS `regexp_extract_all('9999-12-31 23:59:59', '($)', 1)`;
SELECT regexp_extract_all('abc', '($)', 1) AS `regexp_extract_all('abc', '($)', 1)` GROUP BY regexp_extract_all('abc', '($)', 1);
SELECT regexp_extract_all('a1b2c3', '($)', 1) AS `regexp_extract_all('a1b2c3', '($)', 1)`;
SELECT regexp_extract_all('abc', '($)', '($)') AS `regexp_extract_all('abc', '($)', '($)')`;
SELECT regexp_extract_all('abc', '($)', 1) AS `regexp_extract_all('abc', '($)', 1)` GROUP BY regexp_extract_all('abc', '($)', 1);
SELECT regexp_extract_all('abc', '$', 0) AS `regexp_extract_all('abc', '$', 0)`;
SELECT regexp_extract_all('abc', '$', '$') AS `regexp_extract_all('abc', '$', '$')`;
SELECT regexp_extract_all('abc', '$', CAST(NULL AS JSON)) AS `regexp_extract_all('abc', '$', CAST(NULL AS JSON))`;
SELECT regexp_extract_all('abc', '$', 0.0) AS `regexp_extract_all('abc', '$', 0.0)`;
SELECT regexp_extract_all('abc', '$', 0) AS `regexp_extract_all('abc', '$', 0)` ORDER BY regexp_extract_all('abc', '$', 0) DESC NULLS FIRST;
SELECT regexp_extract_all('abc', repeat('x', 65536), 0) AS `regexp_extract_all('abc', repeat('x', 65536), 0)`;
SELECT regexp_extract_all('abc', '0000-00-00', 0) AS `regexp_extract_all('abc', '0000-00-00', 0)`;
SELECT regexp_extract_all('$', '$', 0) AS `regexp_extract_all('$', '$', 0)`;
SELECT regexp_extract_all('abc', '$', '9999-12-31 23:59:59') AS `regexp_extract_all('abc', '$', '9999-12-31 23:59:59')`;
SELECT regexp_extract_all(170141183460469231731687303715884105727, '$', 0) AS `regexp_extract_all(170141183460469231731687303715884105727, '$', 0)`;
SELECT regexp_extract_all('abc', 0.0, 0) AS `regexp_extract_all('abc', 0.0, 0)`;
SELECT regexp_extract_all('abc', '$', TRUE) AS `regexp_extract_all('abc', '$', TRUE)`;
SELECT regexp_extract_all('abc', '$', get_json_string(CAST(0 AS JSON), '$.a')) AS `regexp_extract_all('abc', '$', get_json_string(CAST(0 AS JSON), '$.a'))`;
SELECT regexp_extract_all('abc', '$', json_query(CAST(0 AS JSON), '$.a')) AS `regexp_extract_all('abc', '$', json_query(CAST(0 AS JSON), '$.a'))`;
SELECT regexp_extract_all('abc', '$', json_length(CAST(0 AS JSON))) AS `regexp_extract_all('abc', '$', json_length(CAST(0 AS JSON)))`;
SELECT regexp_extract_all('9999-12-31 23:59:59', '$', 0) AS `regexp_extract_all('9999-12-31 23:59:59', '$', 0)`;
SELECT regexp_extract_all('abc', '1970-01-01', 0) AS `regexp_extract_all('abc', '1970-01-01', 0)`;
SELECT regexp_extract_all('$', '$', 0) AS `regexp_extract_all('$', '$', 0)`;
SELECT regexp_extract_all('abc', '$', 0) AS `regexp_extract_all('abc', '$', 0)`;
SELECT regexp_extract_all('abc', '$', '9999-12-31 23:59:59') AS `regexp_extract_all('abc', '$', '9999-12-31 23:59:59')`;
SELECT regexp_extract_all('abc', '$', repeat('x', 65536)) AS `regexp_extract_all('abc', '$', repeat('x', 65536))`;
SELECT regexp_extract_all(0.0, '$', 0) AS `regexp_extract_all(0.0, '$', 0)`;
SELECT regexp_extract_all('abc', -9223372036854775808, 0) AS `regexp_extract_all('abc', -9223372036854775808, 0)`;
SELECT regexp_extract_all('abc', '$', 0) AS `regexp_extract_all('abc', '$', 0)` GROUP BY regexp_extract_all('abc', '$', 0);
SELECT regexp_extract_all('abc', '$', CAST(0 AS JSON)->'k') AS `regexp_extract_all('abc', '$', CAST(0 AS JSON)->'k')`;
SELECT regexp_extract_all('abc', '$', '$') AS `regexp_extract_all('abc', '$', '$')`;
SELECT DISTINCT regexp_extract_all('abc', '$', 0) AS `regexp_extract_all('abc', '$', 0)`;
SELECT regexp_extract_all(TRUE, '([0-9])', 1) AS `regexp_extract_all(TRUE, '([0-9])', 1)`;
SELECT regexp_extract_all('([0-9])', '([0-9])', 1) AS `regexp_extract_all('([0-9])', '([0-9])', 1)`;
SELECT regexp_extract_all('a1b2c3', '([0-9])', 'a1b2c3') AS `regexp_extract_all('a1b2c3', '([0-9])', 'a1b2c3')`;
SELECT regexp_extract_all('a1b2c3', '([0-9])', 1) AS `regexp_extract_all('a1b2c3', '([0-9])', 1)` LIMIT 7, 100;
SELECT regexp_extract_all('a1b2c3', '([0-9])', 1) AS `regexp_extract_all('a1b2c3', '([0-9])', 1)` ORDER BY regexp_extract_all('a1b2c3', '([0-9])', 1) ASC;
SELECT regexp_extract_all(CAST('a1b2c3' AS DATE), '([0-9])', 1) AS `regexp_extract_all(CAST('a1b2c3' AS DATE), '([0-9])', 1)`;
SELECT regexp_extract_all('a1b2c3', '([0-9])', '%') AS `regexp_extract_all('a1b2c3', '([0-9])', '%')`;
SELECT regexp_extract_all('a1b2c3', '([0-9])', 1) AS `regexp_extract_all('a1b2c3', '([0-9])', 1)`;
SELECT regexp_extract_all('a1b2c3', '([0-9])', 1) AS `regexp_extract_all('a1b2c3', '([0-9])', 1)` LIMIT 7, 2;
SELECT regexp_extract_all('a1b2c3', 2147483647, 1) AS `regexp_extract_all('a1b2c3', 2147483647, 1)`;
SELECT regexp_extract_all('a1b2c3', -1, 1) AS `regexp_extract_all('a1b2c3', -1, 1)`;
SELECT regexp_extract_all('a1b2c3', 0.0, 1) AS `regexp_extract_all('a1b2c3', 0.0, 1)`;
SELECT regexp_extract_all('a1b2c3', '([0-9])', '9999-12-31 23:59:59') AS `regexp_extract_all('a1b2c3', '([0-9])', '9999-12-31 23:59:59')`;
SELECT regexp_extract_all('a1b2c3', '([0-9])', 1) AS `regexp_extract_all('a1b2c3', '([0-9])', 1)` LIMIT 1, 5;
SELECT regexp_extract_all('a1b2c3', '([0-9])', 1) AS `regexp_extract_all('a1b2c3', '([0-9])', 1)` WHERE 'a*';
SELECT regexp_extract_all('a1b2c3', '([0-9])', 1) AS `regexp_extract_all('a1b2c3', '([0-9])', 1)` GROUP BY regexp_extract_all('a1b2c3', '([0-9])', 1);
SELECT regexp_extract_all(170141183460469231731687303715884105727, '([0-9])', 1) AS `regexp_extract_all(170141183460469231731687303715884105727, '([0-9])', 1)`;
SELECT regexp_extract_all('a1b2c3', 1, 1) AS `regexp_extract_all('a1b2c3', 1, 1)`;
SELECT regexp_extract_all('a1b2c3', '([0-9])', '([0-9])') AS `regexp_extract_all('a1b2c3', '([0-9])', '([0-9])')`;
SELECT regexp_extract_all('a1b2c3', 0.0, 1) AS `regexp_extract_all('a1b2c3', 0.0, 1)`;
SELECT regexp_extract_all(CAST('a1b2c3' AS JSON)->'$', '([0-9])', 1) AS `regexp_extract_all(CAST('a1b2c3' AS JSON)->'$', '([0-9])', 1)`;
SELECT regexp_extract_all('a1b2c3', 0, 1) AS `regexp_extract_all('a1b2c3', 0, 1)`;
SELECT regexp_extract_all('a1b2c3', -9223372036854775808, 1) AS `regexp_extract_all('a1b2c3', -9223372036854775808, 1)`;
SELECT regexp_extract_all('a1b2c3', '([0-9])', 1.0E308) AS `regexp_extract_all('a1b2c3', '([0-9])', 1.0E308)`;
SELECT regexp_extract_all('a1b2c3', 'a1b2c3', 1) AS `regexp_extract_all('a1b2c3', 'a1b2c3', 1)`;
SELECT regexp_extract_all('a1b2c3', '0', 1) AS `regexp_extract_all('a1b2c3', '0', 1)`;
SELECT regexp_extract_all('a1b2c3', '([0-9])', 1) AS `regexp_extract_all('a1b2c3', '([0-9])', 1)`;
SELECT regexp_extract_all('a1b2c3', '([0-9])', 1) AS `regexp_extract_all('a1b2c3', '([0-9])', 1)` LIMIT 0;
SELECT regexp_extract_all('a1b2c3', '([0-9])', 1) AS `regexp_extract_all('a1b2c3', '([0-9])', 1)` GROUP BY regexp_extract_all('a1b2c3', '([0-9])', 1);