SELECT @@enable_ivm_refresh AS `@@enable_ivm_refresh`;
SELECT @@tvr_target_mvid AS `@@tvr_target_mvid`;
SELECT DISTINCT @@enable_ivm_refresh AS `@@enable_ivm_refresh`;
SELECT @@enable_ivm_refresh AS `@@enable_ivm_refresh` LIMIT 7, 0;
SELECT DISTINCT @@enable_ivm_refresh AS `@@enable_ivm_refresh`;
SELECT @@enable_ivm_refresh AS `@@enable_ivm_refresh` ORDER BY @@enable_ivm_refresh DESC NULLS FIRST;
SELECT @@enable_ivm_refresh AS `@@enable_ivm_refresh` LIMIT 0;
SELECT @@enable_ivm_refresh AS `@@enable_ivm_refresh` LIMIT 2;
SELECT CAST((@@enable_ivm_refresh) AS JSON)->'k' AS `CAST((@@enable_ivm_refresh) AS JSON)->'k'`;
SELECT @@enable_ivm_refresh AS `@@enable_ivm_refresh` LIMIT 0;
SELECT @@enable_ivm_refresh AS `@@enable_ivm_refresh` WHERE @@enable_ivm_refresh;
SELECT DISTINCT @@enable_ivm_refresh AS `@@enable_ivm_refresh`;
SELECT @@enable_ivm_refresh AS `@@enable_ivm_refresh` ORDER BY @@enable_ivm_refresh ASC;
SELECT @@enable_ivm_refresh AS `@@enable_ivm_refresh` GROUP BY @@enable_ivm_refresh;
SELECT @@enable_ivm_refresh AS `@@enable_ivm_refresh` WHERE @@enable_ivm_refresh;
SELECT @@tvr_target_mvid AS `@@tvr_target_mvid` GROUP BY @@tvr_target_mvid;
SELECT @@tvr_target_mvid AS `@@tvr_target_mvid` WHERE @@enable_ivm_refresh;
SELECT @@tvr_target_mvid AS `@@tvr_target_mvid` WHERE @@enable_ivm_refresh;
SELECT @@tvr_target_mvid AS `@@tvr_target_mvid` GROUP BY @@tvr_target_mvid;
SELECT DISTINCT @@tvr_target_mvid AS `@@tvr_target_mvid`;
SELECT @@tvr_target_mvid AS `@@tvr_target_mvid` ORDER BY @@tvr_target_mvid ASC;
SELECT get_json_string(CAST((@@tvr_target_mvid) AS JSON), '$.a') AS `get_json_string(CAST((@@tvr_target_mvid) AS JSON), '$.a')`;
SELECT @@tvr_target_mvid AS `@@tvr_target_mvid` WHERE @@enable_ivm_refresh;
SELECT json_query(CAST((@@tvr_target_mvid) AS JSON), '$.a') AS `json_query(CAST((@@tvr_target_mvid) AS JSON), '$.a')`;
SELECT @@tvr_target_mvid AS `@@tvr_target_mvid` ORDER BY @@tvr_target_mvid ASC NULLS LAST;