SELECT array_length(array_distinct(`srfuzz_mut_116`.`t2`.`c2`)) AS `array_length(array_distinct(c2))` FROM `srfuzz_mut_116`.`t2`;
SELECT array_length(array_distinct(`srfuzz_mut_116`.`t2`.`c2`)) AS `array_length(array_distinct(srfuzz_mut_116.t2.c2))` FROM `srfuzz_mut_116`.`t2`;
SELECT array_length(array_distinct(array_distinct(`srfuzz_mut_116`.`t2`.`c2`))) AS `array_length(array_distinct(array_distinct(srfuzz_mut_116.t2.c2)))` FROM `srfuzz_mut_116`.`t2`;
SELECT array_length(array_distinct(`srfuzz_mut_116`.`t2`.`c2`)) AS `array_length(array_distinct(c2))` FROM `srfuzz_mut_116`.`t2`;
SELECT array_length(array_distinct(`srfuzz_mut_116`.`t2`.`c2`)) AS `array_length(array_distinct(srfuzz_mut_116.t2.c2))` FROM `srfuzz_mut_116`.`t2`;
SELECT array_length(array_distinct(array_distinct(`srfuzz_mut_116`.`t2`.`c2`))) AS `array_length(array_distinct(array_distinct(srfuzz_mut_116.t2.c2)))` FROM `srfuzz_mut_116`.`t2`;
SELECT array_length(array_distinct(`t2`.`c2`)) AS `array_length(array_distinct(c2))` FROM (SELECT `srfuzz_mut_116`.`t2`.`c1`, `srfuzz_mut_116`.`t2`.`c2` FROM `srfuzz_mut_116`.`t2` EXCEPT SELECT `srfuzz_mut_116`.`t2`.`c1`, `srfuzz_mut_116`.`t2`.`c2` FROM `srfuzz_mut_116`.`t2`) `t2`;
SELECT DISTINCT array_length(array_distinct(`srfuzz_mut_116`.`t2`.`c2`)) AS `array_length(array_distinct(c2))` FROM `srfuzz_mut_116`.`t2`;
SELECT array_length(array_distinct(`srfuzz_mut_116`.`t2`.`c2`)) AS `array_length(array_distinct(srfuzz_mut_116.t2.c2))` FROM `srfuzz_mut_116`.`t2`;
SELECT DISTINCT array_length(array_distinct(`srfuzz_mut_116`.`t2`.`c2`)) AS `array_length(array_distinct(c2))` FROM `srfuzz_mut_116`.`t2`;
SELECT array_length(array_distinct(`srfuzz_mut_116`.`t2`.`c2`)) AS `array_length(array_distinct(srfuzz_mut_116.t2.c2))` FROM `srfuzz_mut_116`.`t2`;
SELECT array_length(array_distinct(array_distinct(`srfuzz_mut_116`.`t2`.`c2`))) AS `array_length(array_distinct(array_distinct(srfuzz_mut_116.t2.c2)))` FROM `srfuzz_mut_116`.`t2`;
SELECT array_length(array_distinct(`srfuzz_mut_116`.`t2`.`c2`)) AS `array_length(array_distinct(c2))` FROM `srfuzz_mut_116`.`t2`;
SELECT array_length(array_distinct(`srfuzz_mut_116`.`t2`.`c2`[CAST(NULL AS INT)])) AS `array_length(array_distinct(c2[CAST(NULL AS INT)]))` FROM `srfuzz_mut_116`.`t2`;
SELECT array_length(array_distinct(`srfuzz_mut_116`.`t2`.`c2`)) AS `array_length(array_distinct(c2))` FROM `srfuzz_mut_116`.`t2` WHERE array_length(array_distinct(`srfuzz_mut_116`.`t2`.`c2`));
SELECT array_length(array_distinct(`t2`.`c2`)) AS `array_length(array_distinct(c2))` FROM (SELECT `srfuzz_mut_116`.`t2`.`c1`, `srfuzz_mut_116`.`t2`.`c2` FROM `srfuzz_mut_116`.`t2` EXCEPT SELECT `srfuzz_mut_116`.`t2`.`c1`, `srfuzz_mut_116`.`t2`.`c2` FROM `srfuzz_mut_116`.`t2`) `t2`;
SELECT array_length(array_distinct(`srfuzz_mut_116`.`t2`.`c2`)) AS `array_length(array_distinct(c2))` FROM `srfuzz_mut_116`.`t2` ORDER BY array_length(array_distinct(`srfuzz_mut_116`.`t2`.`c2`)) ASC;
SELECT array_length(array_distinct(`t2`.`c2`)) AS `array_length(array_distinct(c2))` FROM (SELECT `srfuzz_mut_116`.`t2`.`c1`, `srfuzz_mut_116`.`t2`.`c2` FROM `srfuzz_mut_116`.`t2` EXCEPT SELECT `srfuzz_mut_116`.`t2`.`c1`, `srfuzz_mut_116`.`t2`.`c2` FROM `srfuzz_mut_116`.`t2`) `t2`;
SELECT array_length(array_distinct(`t2`.`c2`)) AS `array_length(array_distinct(c2))` FROM (SELECT `srfuzz_mut_116`.`t2`.`c1`, `srfuzz_mut_116`.`t2`.`c2` FROM `srfuzz_mut_116`.`t2` INTERSECT SELECT `srfuzz_mut_116`.`t2`.`c1`, `srfuzz_mut_116`.`t2`.`c2` FROM `srfuzz_mut_116`.`t2`) `t2`;
SELECT array_length(array_distinct(array_distinct(`srfuzz_mut_116`.`t2`.`c2`))) AS `array_length(array_distinct(array_distinct(srfuzz_mut_116.t2.c2)))` FROM `srfuzz_mut_116`.`t2`;
SELECT array_length(`srfuzz_mut_116`.`t2`.`c2`) AS `array_length(srfuzz_mut_116.t2.c2)` FROM `srfuzz_mut_116`.`t2`;
SELECT array_length(array_distinct(array_distinct(`srfuzz_mut_116`.`t2`.`c2`))) AS `array_length(array_distinct(array_distinct(srfuzz_mut_116.t2.c2)))` FROM `srfuzz_mut_116`.`t2`;
SELECT array_length(array_distinct(`srfuzz_mut_116`.`t2`.`c2`)) AS `array_length(array_distinct(c2))` FROM `srfuzz_mut_116`.`t2`;
SELECT array_length(array_distinct(`srfuzz_mut_116`.`t2`.`c2`)) AS `array_length(array_distinct(srfuzz_mut_116.t2.c2))` FROM `srfuzz_mut_116`.`t2`;
SELECT array_length(array_distinct(`srfuzz_mut_116`.`t2`.`c2`)) AS `array_length(array_distinct(c2))` FROM `srfuzz_mut_116`.`t2`;
SELECT array_length(`srfuzz_mut_116`.`t2`.`c2`) AS `array_length(srfuzz_mut_116.t2.c2)` FROM `srfuzz_mut_116`.`t2`;
SELECT array_length(array_distinct(`srfuzz_mut_116`.`t2`.`c2`)) AS `array_length(array_distinct(c2))` FROM `srfuzz_mut_116`.`t2`;
SELECT array_length(array_distinct(`srfuzz_mut_116`.`t2`.`c2`)) AS `array_length(array_distinct(c2))` FROM `srfuzz_mut_116`.`t2`;
SELECT array_length(array_distinct(`srfuzz_mut_116`.`t2`.`c2`)) AS `array_length(array_distinct(c2))` FROM `srfuzz_mut_116`.`t2`;