SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)` ORDER BY sleep(3) ASC;
SELECT sleep(3) AS `sleep(3)` LIMIT 1, 100;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep('%') AS `sleep('%')`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT json_length(CAST((sleep(3)) AS JSON)) AS `json_length(CAST((sleep(3)) AS JSON))`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)` LIMIT 7, 1;
SELECT sleep(0.0) AS `sleep(0.0)`;
SELECT sleep(3) AS `sleep(3)` LIMIT 7, 0;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep('') AS `sleep('')`;
SELECT CAST((sleep(3)) AS ARRAY<MAP<VARCHAR(16),INT>>) AS `CAST((sleep(3)) AS ARRAY<MAP<VARCHAR(16),INT>>)`;
SELECT sleep(TRUE) AS `sleep(TRUE)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(1.0E308) AS `sleep(1.0E308)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)` LIMIT 7, 0;
SELECT sleep('0') AS `sleep('0')`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(3) AS `sleep(3)`;
SELECT sleep(0.0) AS `sleep(0.0)`;
SELECT CAST((sleep(3)) AS DECIMAL64(1,0)) AS `CAST((sleep(3)) AS DECIMAL64(1,0))`;