SELECT tokenize('english', 'Today is saturday') AS `tokenize('english', 'Today is saturday')`;
SELECT tokenize('standard', 'hello world') AS `tokenize('standard', 'hello world')`;
SELECT tokenize('chinese', '中华人民共和国') AS `tokenize('chinese', '中华人民共和国')`;
SELECT `srfuzz_mut_629`.`t_tokenized_table`.`id`, tokenize('english', `srfuzz_mut_629`.`t_tokenized_table`.`english_text`) AS `tokenize('english', english_text)`, tokenize('standard', `srfuzz_mut_629`.`t_tokenized_table`.`standard_text`) AS `tokenize('standard', standard_text)`, tokenize('chinese', `srfuzz_mut_629`.`t_tokenized_table`.`chinese_text`) AS `tokenize('chinese', chinese_text)` FROM `srfuzz_mut_629`.`t_tokenized_table` ORDER BY `srfuzz_mut_629`.`t_tokenized_table`.`id` ASC;
SELECT array_length(tokenize('english', 'Today is saturday')) AS `array_length(tokenize('english', 'Today is saturday'))`;
SELECT tokenize('english', 'Today is saturday') AS `tokenize('english', 'Today is saturday')` GROUP BY tokenize('english', 'Today is saturday');
SELECT tokenize('english', -1.0E308) AS `tokenize('english', -1.0E308)`;
SELECT tokenize('english', '\\') AS `tokenize('english', '\\')`;
SELECT tokenize('english', 0) AS `tokenize('english', 0)`;
SELECT tokenize('english', TRUE) AS `tokenize('english', TRUE)`;
SELECT tokenize('english', '%') AS `tokenize('english', '%')`;
SELECT array_slice(tokenize('english', 'Today is saturday'), 1, 3) AS `array_slice(tokenize('english', 'Today is saturday'), 1, 3)`;
SELECT tokenize('english', 'Today is saturday') AS `tokenize('english', 'Today is saturday')`;
SELECT tokenize('english', 'english') AS `tokenize('english', 'english')`;
SELECT tokenize('english', 'Today is saturday') AS `tokenize('english', 'Today is saturday')`;
SELECT tokenize(-9223372036854775808, 'Today is saturday') AS `tokenize(-9223372036854775808, 'Today is saturday')`;
SELECT tokenize('english', 'Today is saturday') AS `tokenize('english', 'Today is saturday')` LIMIT 100;
SELECT tokenize('english', '0000-00-00') AS `tokenize('english', '0000-00-00')`;
SELECT tokenize('english', 0.0) AS `tokenize('english', 0.0)`;
SELECT tokenize('english', '0000-00-00') AS `tokenize('english', '0000-00-00')`;
SELECT tokenize('english', 'Today is saturday') AS `tokenize('english', 'Today is saturday')`;
SELECT tokenize('english', 'Today is saturday') AS `tokenize('english', 'Today is saturday')`;
SELECT tokenize('english', 1) AS `tokenize('english', 1)`;
SELECT tokenize('english', 'Today is saturday') AS `tokenize('english', 'Today is saturday')` ORDER BY tokenize('english', 'Today is saturday') DESC;
SELECT tokenize('Today is saturday', 'Today is saturday') AS `tokenize('Today is saturday', 'Today is saturday')`;
SELECT tokenize('english', 'Today is saturday') AS `tokenize('english', 'Today is saturday')` ORDER BY tokenize('english', 'Today is saturday') ASC NULLS LAST;
SELECT tokenize(CAST('english' AS TIME), 'Today is saturday') AS `tokenize(CAST('english' AS TIME), 'Today is saturday')`;
SELECT tokenize('standard', 'hello world') AS `tokenize('standard', 'hello world')` ORDER BY tokenize('standard', 'hello world') ASC;
SELECT DISTINCT tokenize('standard', 'hello world') AS `tokenize('standard', 'hello world')`;
SELECT tokenize('standard', 'hello world') AS `tokenize('standard', 'hello world')` LIMIT 2;
SELECT tokenize(1.0E308, 'hello world') AS `tokenize(1.0E308, 'hello world')`;
SELECT tokenize('', 'hello world') AS `tokenize('', 'hello world')`;
SELECT tokenize('standard', '') AS `tokenize('standard', '')`;
SELECT DISTINCT tokenize('standard', 'hello world') AS `tokenize('standard', 'hello world')`;
SELECT tokenize('hello world', 'hello world') AS `tokenize('hello world', 'hello world')`;
SELECT tokenize('standard', 'hello world') AS `tokenize('standard', 'hello world')` WHERE '中华人民共和国';
SELECT tokenize('standard', 'hello world') AS `tokenize('standard', 'hello world')`;
SELECT tokenize('Today is saturday', 'hello world') AS `tokenize('Today is saturday', 'hello world')`;
SELECT tokenize('standard', 'standard') AS `tokenize('standard', 'standard')`;
SELECT tokenize('standard', 'hello world') AS `tokenize('standard', 'hello world')`;
SELECT tokenize('hello world', 'hello world') AS `tokenize('hello world', 'hello world')`;
SELECT tokenize(0, 'hello world') AS `tokenize(0, 'hello world')`;
SELECT tokenize('standard', 'standard') AS `tokenize('standard', 'standard')`;
SELECT tokenize('standard', 'hello world') AS `tokenize('standard', 'hello world')` WHERE 'standard';
SELECT tokenize('standard', 170141183460469231731687303715884105727) AS `tokenize('standard', 170141183460469231731687303715884105727)`;
SELECT tokenize(-9223372036854775808, 'hello world') AS `tokenize(-9223372036854775808, 'hello world')`;
SELECT tokenize('standard', 'hello world') AS `tokenize('standard', 'hello world')` LIMIT 1, 2;
SELECT tokenize('english', 'hello world') AS `tokenize('english', 'hello world')`;
SELECT tokenize('standard', 'hello world') AS `tokenize('standard', 'hello world')`;
SELECT tokenize(-2147483648, 'hello world') AS `tokenize(-2147483648, 'hello world')`;
SELECT tokenize(1.0E308, 'hello world') AS `tokenize(1.0E308, 'hello world')`;
SELECT tokenize('standard', '%') AS `tokenize('standard', '%')`;
SELECT tokenize('%', 'hello world') AS `tokenize('%', 'hello world')`;
SELECT tokenize('standard', 'hello world') AS `tokenize('standard', 'hello world')`;
SELECT DISTINCT tokenize('standard', 'hello world') AS `tokenize('standard', 'hello world')`;
SELECT tokenize('standard', CAST(NULL AS JSON)) AS `tokenize('standard', CAST(NULL AS JSON))`;
SELECT tokenize('standard', 'hello world') AS `tokenize('standard', 'hello world')`;
SELECT tokenize('chinese', 'chinese') AS `tokenize('chinese', 'chinese')`;
SELECT tokenize('chinese', 0.0) AS `tokenize('chinese', 0.0)`;
SELECT tokenize('0000-00-00', '中华人民共和国') AS `tokenize('0000-00-00', '中华人民共和国')`;
SELECT tokenize('chinese', '中华人民共和国') AS `tokenize('chinese', '中华人民共和国')`;
SELECT tokenize('chinese', -1.0E308) AS `tokenize('chinese', -1.0E308)`;
SELECT tokenize(-1, '中华人民共和国') AS `tokenize(-1, '中华人民共和国')`;
SELECT tokenize('中华人民共和国', '中华人民共和国') AS `tokenize('中华人民共和国', '中华人民共和国')`;
SELECT tokenize('chinese', '中华人民共和国') AS `tokenize('chinese', '中华人民共和国')` ORDER BY tokenize('chinese', '中华人民共和国') DESC;
SELECT tokenize('chinese', '中华人民共和国') AS `tokenize('chinese', '中华人民共和国')`;
SELECT tokenize('chinese', '中华人民共和国') AS `tokenize('chinese', '中华人民共和国')` ORDER BY tokenize('chinese', '中华人民共和国') ASC;
SELECT tokenize(-2147483648, '中华人民共和国') AS `tokenize(-2147483648, '中华人民共和国')`;
SELECT tokenize('chinese', 'chinese') AS `tokenize('chinese', 'chinese')`;
SELECT tokenize('chinese', -2147483648) AS `tokenize('chinese', -2147483648)`;
SELECT tokenize('chinese', '%') AS `tokenize('chinese', '%')`;
SELECT tokenize('chinese', '中华人民共和国') AS `tokenize('chinese', '中华人民共和国')`;
SELECT tokenize(CAST('chinese' AS JSON)->'$.a', '中华人民共和国') AS `tokenize(CAST('chinese' AS JSON)->'$.a', '中华人民共和国')`;
SELECT tokenize('chinese', '中华人民共和国') AS `tokenize('chinese', '中华人民共和国')`;
SELECT tokenize(NULL, '中华人民共和国') AS `tokenize(NULL, '中华人民共和国')`;
SELECT tokenize('中华人民共和国', '中华人民共和国') AS `tokenize('中华人民共和国', '中华人民共和国')`;
SELECT tokenize(2147483647, '中华人民共和国') AS `tokenize(2147483647, '中华人民共和国')`;
SELECT tokenize('chinese', 'chinese') AS `tokenize('chinese', 'chinese')`;
SELECT tokenize('chinese', '9999-12-31 23:59:59') AS `tokenize('chinese', '9999-12-31 23:59:59')`;
SELECT tokenize('chinese', '中华人民共和国') AS `tokenize('chinese', '中华人民共和国')`;
SELECT tokenize('0', '中华人民共和国') AS `tokenize('0', '中华人民共和国')`;
SELECT tokenize('chinese', '中华人民共和国') AS `tokenize('chinese', '中华人民共和国')` GROUP BY tokenize('chinese', '中华人民共和国');
SELECT tokenize('chinese', '中华人民共和国') AS `tokenize('chinese', '中华人民共和国')` WHERE 'Today is saturday';